qdrant/qdrant

- README.md
Some minor adjustments
2. [x] Have you lint your code locally prior to submission?
> README spellcheck fixes

- Cargo.lock
- Cargo.toml
- docs/redoc/openapi.json
- lib/collection/Cargo.toml
- lib/collection/src/collection.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/segment_manager/holders/proxy_segment.rs
- lib/collection/tests/collection_test.rs
- lib/segment/Cargo.toml
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/id_mapper/id_mapper.rs
- lib/segment/src/id_mapper/simple_id_mapper.rs
- lib/segment/src/segment.rs
- openapi/models.json
- openapi/openapi-merged.yaml
- openapi/openapi.yaml
- src/api/retrieve_api.rs
- src/main.rs
- src/schema_generator.rs
- tests/basic_api_test.sh
- tools/generate_openapi_models.sh
- This PR adds a new API endpoint for retrieving points based on a filter. If no filter provided - API iterates over each point
- API is paginated - each request returns an offset which should be used to retrieve the next page
2. [x] Have you lint your code locally prior to submission?
> Implementation of points scroll API #38

- Dockerfile
- lib/segment/src/spaces/simple.rs
> dynamic arch

- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/mod.rs
- lib/collection/src/collection_manager/tests/mod.rs
Related to https://github.com/qdrant/qdrant/issues/80
> Fix point retrieve from copy-on-write proxy segment

- Cargo.lock
- lib/storage/Cargo.toml
- lib/storage/src/content_manager/collections_ops.rs
- lib/storage/src/content_manager/mod.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/tests/alias_tests.rs
- tests/basic_api_test.sh
> fix alias operation deadlock (#103)

- lib/segment/benches/vector_search.rs
- lib/segment/src/payload_storage/payload_storage_base.rs
- lib/segment/src/spaces/tools.rs
- lib/storage/tests/alias_tests.rs
Adds some leftover refactorings, e.g. more `IntoIter` stuff, code simplifications etc.
> Add more refactorings

- lib/segment/src/index/hnsw_index/search_context.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/tests/segment_tests.rs
> fix refactoring

- .gitignore
- Cargo.toml
- Dockerfile
- lib/collection/Cargo.toml
- lib/segment/Cargo.toml
- lib/storage/Cargo.toml
- update rust version in Dockerfile
- use rust edition 2021
> Upgrade rust version

- Dockerfile
> fix build of docker image - update version of libgfortran

- Dockerfile
> fix debian version in dockerfile

- Cargo.lock
- lib/segment/Cargo.toml
- lib/segment/src/index/hnsw_index/build_cache.rs
replace incompatible hashlib with compatible one
> Fix Apple M1 compatibility

- docs/redoc/openapi.json
- openapi/openapi-merged.yaml
- openapi/openapi.yaml
> Update api descriptions 37

- lib/segment/src/entry/entry_point.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/index_selector.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/payload_config.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/index/visited_pool.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/segment.rs
- lib/segment/src/spaces/metric.rs
- lib/segment/src/types.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
> add comments for segment entitites

- QUICK_START_GRPC.md
- expanded.rs
- src/actix/api/update_api.rs
- src/common/mod.rs
- src/common/points.rs
- src/tonic/api/mod.rs
- src/tonic/api/points_api.rs
- src/tonic/mod.rs
- src/tonic/proto/points.proto
- src/tonic/proto/qdrant.proto
- tests/basic_grpc_test.sh
Adds the ability to load new points to the store using GRPC protocol.
See quick start for the API syntax. Tried to keep it as close as possible to json, however there is no way to use custom field name in protobuf, so had to go with ``"key": "city", "value":  { payload }``
How to test:
Run both http and grpc (know issue: ctrl+c does not work)
```
cargo run --features=grpc  --bin qdrant
```
Follow the readme for GRPC to create collection and insert poitns, test using curl as not grpc for retrieve yet:
```
curl http://localhost:6333/collections/test_collection/points/1
{"result":{"id":1,"payload":{"city":{"type":"keyword","value":["Berlin"]},"coords":{"type":"geo","value":[{"lon":2.0,"lat":1.0}]},"country":{"type":"keyword","value":["Germany"]},"population":{"type":"integer","value":[1000000 …
```
> [GRPC] Expose upsert points API

- docs/redoc/index.html
- docs/redoc/master/openapi.json
- docs/redoc/openapi.json
- docs/redoc/v0.4.2/openapi.json
- lib/collection/src/operations/types.rs
- openapi/models.json
- openapi/openapi-main.ytt.yaml
- openapi/openapi-merged.yaml
Updates OpenAPI redoc page, allows user to select version of the API documentation
> Add OpenAPI version selector

- docs/redoc/openapi.json
- lib/collection/src/collection.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/simple_collection_searcher.rs
- lib/collection/src/operations/types.rs
- lib/collection/tests/collection_test.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/segment.rs
- lib/segment/src/types.rs
- lib/segment/tests/payload_index_test.rs
- lib/segment/tests/segment_tests.rs
- openapi/models.json
- openapi/openapi-merged.yaml
- add `with_vector` parameter to search api which tells app whether to include actual vectors data into search results (address https://github.com/qdrant/qdrant/issues/50);
- regenerate docs.
> Allow to include vector into search result

- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/hnsw_index/entry_points.rs
- lib/segment/src/index/hnsw_index/graph_layers.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/src/index/sample_estimation.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/segment_constructor/simple_segment_constructor.rs
- lib/segment/src/types.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
- doc links
- explicit deref
- if instead of match for single bool condition
- combine similar match branches
> fix clippy warnings

- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/hnsw_index/graph_layers.rs
- lib/segment/src/index/hnsw_index/point_scorer.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/spaces/simple.rs
https://rust-lang.github.io/rust-clippy/master/index.html#cloned_instead_of_copied
> use copied instead of cloned

- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/hnsw_index/build_cache.rs
- lib/segment/src/index/hnsw_index/graph_layers.rs
- lib/segment/src/index/hnsw_index/point_scorer.rs
- lib/segment/src/index/hnsw_index/search_context.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/index/visited_pool.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
> add missing commas

- lib/segment/src/index/visited_pool.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
https://rust-lang.github.io/rust-clippy/master/index.html#map_unwrap_or
> use map_or instead of map & unwrap_or

- config/config.yaml
- src/actix/mod.rs
- src/settings.rs
> Fix #187. Add config for limiting actix workers.

- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/mod.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/merge_optimizer.rs
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/lib.rs
- lib/collection/src/tests/mod.rs
- lib/collection/src/update_handler.rs
- src/tonic/qdrant.rs
Create multiprocessing optimizer test + fix found issues
> Multiprocessing optimization fix

- lib/segment/src/index/hnsw_index/entry_points.rs
> hnsw entry points - replace filter+next by find

- QUICK_START_GRPC.md
- lib/collection/src/collection.rs
- src/actix/api/collections_api.rs
- src/common/collections.rs
- src/tonic/api/collections_api.rs
- src/tonic/api/common.rs
- src/tonic/api/mod.rs
- src/tonic/proto/collections.proto
- src/tonic/qdrant.rs
- tests/basic_grpc_test.sh
> [gRPC] get collection method

- src/tonic/api/collections_api.rs
- src/tonic/api/points_api.rs
- src/tonic/proto/collections.proto
- src/tonic/proto/points.proto
- src/tonic/qdrant.rs
ToDo: Merge https://github.com/qdrant/qdrant/pull/153 first
> [gPRC] use status instead of error field in response structures

- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/merge_optimizer.rs
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/tests/mod.rs
- lib/collection/src/update_handler.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/index_base.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/tests/filtrable_hnsw_test.rs
- lib/segment/tests/segment_builder_test.rs
- lib/storage/src/content_manager/errors.rs
ToDo: merge after https://github.com/qdrant/qdrant/pull/156
> [WIP] Force optimization stop #31

- QUICK_START.md
- benches/service/collection_stress.js
- docs/redoc/master/openapi.json
- docs/redoc/openapi.json
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/tests/collection_restore_test.rs
- lib/collection/tests/collection_test.rs
- openapi/models.json
- openapi/openapi-main.ytt.yaml
- openapi/openapi-merged.yaml
- openapi/openapi.lib.yml
- src/actix/api/update_api.rs
- src/tonic/api/points_api.rs
- tests/basic_api_test.sh
- tools/generate_openapi_models.sh
- add `redocly/openapi-cli lint` as a part of schema generation pipeline
- fix redocly warnings
> add openapi validation during generation #208

- docs/redoc/master/openapi.json
- docs/redoc/openapi.json
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/tests/collection_restore_test.rs
- lib/collection/tests/collection_test.rs
- openapi/models.json
- openapi/openapi-merged.yaml
Rename
`BatchInsertOperation` -> `PointsBatch`
> rename point update api structure #208

- QUICK_START.md
- docs/redoc/master/openapi.json
- docs/redoc/openapi.json
- openapi/models.json
- openapi/openapi-merged.yaml
- src/actix/api/retrieve_api.rs
> enable `with_vector` flag in api #50

- Cargo.lock
- lib/collection/Cargo.toml
- lib/collection/src/collection.rs
- lib/collection/src/collection_builder/collection_builder_base.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/update_handler.rs
> Use tokio::sync channels instead of async-channel

- docs/DEVELOPMENT.md
Adding a short documentation to help devs starting with `gRPC`.
> add dev. doc for gRPC

- src/actix/api/collections_api.rs
- src/actix/api/update_api.rs
> enable deprecated API back for now

- lib/collection/src/collection.rs
- lib/collection/src/collection_builder/collection_builder_base.rs
- lib/collection/src/collection_builder/collection_loader.rs
- lib/collection/src/collection_builder/mod.rs
- lib/collection/src/collection_builder/optimizers_builder.rs
- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/merge_optimizer.rs
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/segment/src/payload_storage/mod.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/payload_storage/schema_storage.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/segment_constructor/simple_segment_constructor.rs
- lib/segment/tests/filtrable_hnsw_test.rs
- lib/segment/tests/fixtures/segment.rs
- lib/segment/tests/payload_index_test.rs
- lib/segment/tests/segment_builder_test.rs
- lib/segment/tests/set_payload_test.rs
- tests/basic_api_test.sh
> fix: #101 Payload type consistency is not enforced.

- lib/segment/src/types.rs
https://github.com/qdrant/qdrant/issues/294
> geo coordinates range validation

- Cargo.lock
- Cargo.toml
- src/tonic/api/points_api.rs
- src/tonic/proto/points.proto
- src/tonic/qdrant.rs
- tests/basic_grpc_test.sh
Alternative num. 1 for https://github.com/qdrant/qdrant/issues/299
> UUID support in gRPC with oneof

- docs/redoc/master/openapi.json
- lib/collection/tests/collection_restore_test.rs
- lib/segment/src/types.rs
- src/actix/api/search_api.rs
- src/common/points.rs
- src/tonic/api/conversions.rs
- src/tonic/api/mod.rs
- src/tonic/api/points_api.rs
- src/tonic/proto/points.proto
- src/tonic/qdrant.rs
- tests/basic_api_test.sh
- tests/basic_grpc_test.sh
https://github.com/qdrant/qdrant/issues/300
> [gPRC] search method

- Cargo.lock
- lib/collection/Cargo.toml
- lib/collection/src/collection.rs
- lib/collection/src/collection_builder/collection_builder_base.rs
- lib/collection/src/update_handler.rs
- openapi/tests/openapi_integration/test_collection_update.py
- openapi/tests/run_docker.sh
Reproduction for https://github.com/qdrant/qdrant/issues/309
> reproduce with integration test

- lib/collection/src/collection_manager/holders/proxy_segment.rs
Allow flushing of the temporary segment during the optimization (and hence, truncation of WAL) if there are no data moved from the wrapped segment.
> better logic for proxy segment flushing #317

- Cargo.lock
- Cargo.toml
> use stable actix-web 4

- Dockerfile
> Docker build with Rust 1.59

- docs/redoc/master/openapi.json
- lib/collection/src/collection_manager/simple_collection_searcher.rs
- lib/collection/src/lib.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shard.rs
- lib/collection/tests/collection_restore_test.rs
- lib/collection/tests/collection_test.rs
- lib/storage/src/content_manager/toc.rs
- src/actix/api/retrieve_api.rs
- src/common/points.rs
- src/schema_generator.rs
- src/tonic/api/conversions.rs
- src/tonic/api/points_api.rs
- src/tonic/proto/points.proto
- src/tonic/qdrant.rs
- tests/basic_grpc_test.sh
This PR adds the retrieve methods to the gRPC interface https://github.com/qdrant/qdrant/issues/301
> gRPC retrieve methods

- docs/redoc/master/openapi.json
- lib/segment/src/types.rs
- openapi/tests/openapi_integration/test_basic_retrieve_api.py
Previous version was incorrectly displayed in OpenAPI and generated poor code in python client.
> fix PayloadSelector enum for better openapi compatibility

- docs/grpc/docs.md
- lib/storage/src/content_manager/storage_ops.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/tests/alias_tests.rs
- src/tonic/api/collections_api.rs
- src/tonic/api/points_api.rs
- src/tonic/mod.rs
- src/tonic/proto/collections.proto
- src/tonic/proto/points.proto
- src/tonic/qdrant.rs
- tests/basic_grpc_test.sh
- tools/generate_grpc_docs.sh
Documentation generation script for gRPC + basic comments for methods.
+ additional refactoring `name`, `collection` -> `collecton_name`, to make it consistent with REST
> [gPRC] docs + refactoring

- docs/grpc/docs.md
- src/tonic/api/points_api.rs
- src/tonic/proto/points.proto
- src/tonic/qdrant.rs
- tests/basic_grpc_test.sh
https://github.com/qdrant/qdrant/issues/356
ToDo: merge https://github.com/qdrant/qdrant/pull/363 first
> [gRPC] recommendation method

- lib/collection/src/lib.rs
Loading old collection storage is replaced with migrating this storage to new one on load.
> Migrate legacy collection storage

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/config.rs
- lib/collection/src/lib.rs
- lib/collection/src/operations/types.rs
- lib/collection/tests/common/mod.rs
- lib/storage/src/content_manager/errors.rs
- lib/storage/src/content_manager/storage_ops.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/tests/alias_tests.rs
- src/tonic/api/collections_api.rs
- src/tonic/proto/collections.proto
- src/tonic/qdrant.rs
> Sharding related collection API changes

- docs/redoc/master/openapi.json
- openapi/openapi-collections.ytt.yaml
> upd openAPI schema names

- lib/segment/benches/hnsw_build_asymptotic.rs
- lib/segment/benches/hnsw_build_graph.rs
- lib/segment/benches/hnsw_search_graph.rs
- lib/segment/src/fixtures/index_fixtures.rs
- lib/segment/src/index/hnsw_index/build_condition_checker.rs
- lib/segment/src/index/hnsw_index/graph_layers.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/hnsw_index/point_scorer.rs
- lib/segment/src/index/index_base.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/payload_storage_base.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/tests/filtrable_hnsw_test.rs
> [json storage] Filtering context

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/geo_index.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/types.rs
- lib/segment/tests/payload_index_test.rs
- openapi/tests/openapi_integration/test_basic_retrieve_api.py
https://github.com/qdrant/qdrant/issues/414
> Is empty condition

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/index/field_index/geo_index.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/types.rs
- lib/segment/tests/filtrable_hnsw_test.rs
- lib/segment/tests/payload_index_test.rs
https://github.com/qdrant/qdrant/issues/437
> Values count condition

- lib/segment/Cargo.toml
- lib/segment/benches/conditional_search.rs
- lib/segment/src/common/arc_atomic_ref_cell_iterator.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/fixtures/mod.rs
- lib/segment/src/fixtures/payload_context_fixture.rs
- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/id_tracker/mod.rs
- lib/segment/src/id_tracker/points_iterator.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/in_memory_payload_storage.rs
- lib/segment/src/payload_storage/mod.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/vector_storage/mod.rs
- lib/segment/src/vector_storage/storage_points_iterator.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
- lib/segment/tests/filtrable_hnsw_test.rs
- lib/segment/tests/payload_index_test.rs
https://github.com/qdrant/qdrant/issues/425
> Condition search benchmark

- Cargo.lock
- lib/storage/Cargo.toml
- lib/storage/src/content_manager/errors.rs
- lib/storage/src/content_manager/mod.rs
- lib/storage/src/content_manager/raft_state.rs
- lib/storage/src/content_manager/toc.rs
> Persistent Raft State

- lib/storage/src/content_manager/raft_state.rs
- lib/storage/src/content_manager/toc.rs
- src/consensus.rs
> Save unapplied committed entries indexes

- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/proto/collections_internal_service.proto
- lib/api/src/grpc/proto/collections_service.proto
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/proto/qdrant.proto
- lib/collection/src/shard/local_shard.rs
- lib/storage/src/content_manager/toc.rs
As the project does not use java code generation
> Remove java related proto3 options

- lib/collection/src/lib.rs
It looks cleaner for me to use `try_join_all` in this case, but maybe there are some performance pitfalls. WDYT?
P.S. also removed `.expect` as potentially dangerous.
> use try_join_all

- lib/collection/src/lib.rs
Follow up on https://github.com/qdrant/qdrant/pull/484 (#467)
This PR performs shard update operations concurrently.
I am not super happy about cloning twice the `operation` on the `OperationToShard::ToAll` path.
> [Sharding] shard update operations are executed concurrently

- openapi/tests/openapi_integration/test_basic_retrieve_api.py
Found out that `scroll` test is checking not exactly what it is expected to check.
> fix and extend interation test for scrolling over points

- lib/collection/src/lib.rs
- lib/storage/Cargo.toml
- lib/storage/src/content_manager/raft_state.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/src/types.rs
- lib/storage/tests/alias_tests.rs
- src/consensus.rs
Also some raft state refactoring and map of peers to ids moved
Closes #374
> Adds `this_peer_id` generation as part of raft state

- Cargo.lock
- lib/collection/Cargo.toml
- lib/storage/Cargo.toml
> use qdrant/wal

- lib/api/src/grpc/proto/raft_service.proto
- lib/api/src/grpc/qdrant.rs
- src/consensus.rs
- src/main.rs
- src/tonic/api/raft_api.rs
> Derive this peer uri if not supplied

- docs/redoc/master/openapi.json
- lib/segment/src/types.rs
Tiny PR to keep our openapi spec beautfiull.
> fix typo in openapi spec

- docs/redoc/index.html
Changed a code background color in redoc theme
> Changed a code background color in redoc

- Cargo.lock
- lib/segment/Cargo.toml
- lib/segment/src/index/field_index/geo_hash.rs
- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/field_index/mod.rs
Prove-of-Concept for Equi-Depth Exact Histogram which could be dynamically updated without sampling and re-building.
> histogram PoC + some chore

- lib/segment/src/index/key_encoding.rs
- lib/segment/src/index/mod.rs
> add key encoding for numeric index.

- lib/segment/src/common/mod.rs
- lib/segment/src/common/rocksdb_operations.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
Logs changes:
-limiting size of logs
-log only errors
> rocksdb limited logs and common settings

- src/settings.rs
fixes https://github.com/qdrant/qdrant/issues/574
> default values for debug and info configuration params

- lib/segment/benches/vector_search.rs
- lib/segment/src/common/rocksdb_operations.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/payload_storage/payload_storage_enum.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/payload_storage/simple_payload_storage_impl.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
> Unite rocksdb of segment

- lib/storage/src/content_manager/toc.rs
Async directories creation in `toc.rs`
> async create collection path

- lib/collection/src/lib.rs
- lib/collection/src/shard/local_shard.rs
Async directories creation while collection creation
> async create_dir_all while create collection

- lib/collection/src/shard/local_shard.rs
> Parallel segments creation

- lib/segment/src/index/field_index/btree_index.rs
This PR add write-through and load from a RocksDB instance.
> [real-time index] add write to and load from rocksdb instance.

- .github/workflows/integration-tests.yml
- lib/storage/src/content_manager/toc.rs
- tests/consensus_tests/test_collection_created_after.py
- tests/consensus_tests/test_collection_created_before.py
- tests/consensus_tests/utils.py
Fixes #606 
Also adds a regression test
> Fix deadlock on collection creation from snapshot

- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/index/field_index/on_disk_map_index.rs
Related to https://github.com/qdrant/qdrant/issues/592
This PR is a copy of map index with rocksdb support.
> [real-time index] OnDisk persistence layer for keyword index

- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/index/field_index/on_disk_geo_index.rs
`on_disk_geo_index` duplicate the code on `geo_index` and add rocksdb as storage.
> [real-time index] add OnDIsk persistence layer for geo index

- lib/segment/src/index/field_index/btree_index.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/geo_index.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/field_index/on_disk_geo_index.rs
- lib/segment/src/index/field_index/on_disk_map_index.rs
> [real-time index] Extend PayloadFieldIndex trait with load, update and flush

- docs/redoc/master/openapi.json
- lib/storage/src/content_manager/raft_state.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/src/types.rs
- openapi/.gitignore
- openapi/openapi-cluster.ytt.yaml
- openapi/openapi-main.ytt.yaml
- src/actix/api/cluster_api.rs
- src/actix/api/mod.rs
- src/actix/mod.rs
- src/schema_generator.rs
- tools/generate_openapi_models.sh
Issue: https://github.com/qdrant/qdrant/issues/605
Example output:
```
{
"result": {
"status": "enabled",
"peer_id": 5721686520442062168,
"peers": {
"5721686520442062168": {
"uri": "http://qdrant_node_1:6335/"
},
"11870689967274302261": {
"uri": "http://172.30.0.3:6335/"
}
},
"raft_info": {
"term": 1,
"commit": 4,
"pending_operations": 1
}
},
"status": "ok",
"time": 0.000020509
}
```
> Cluster api

- QUICK_START_GRPC.md
Fixed proto import paths
Fixed some payload keys
Changed default req ip to be ipv4
> Changed enabling grpc from feature to env var

- lib/segment/src/index/field_index/btree_index.rs
- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/key_encoding.rs
> Integration of improved histogram

- lib/collection/src/lib.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/common/version.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
Issue: https://github.com/qdrant/qdrant/issues/614
> add version to the segment

- lib/segment/src/index/field_index/histogram.rs
There are a lot of if-else corner cases in this implementation. I don't expect the reviewer to dig through them, just check out the test visulalization:
```
x
0|0 x
0|0  0|0 x
x 0|1 . 1|0 
x 0|2 .. 2|0 
0|3 .x.. 3|0 
0|4 ....x 4|0 
0|5 ..... 5|0 x
x 0|5 ..... 5|0  0|0 
x 0|0  0|5 ..... 5|0  0|0 
0|1 . 1|5 ..... 5|0  0|0 x
0|1 . 1|5 ..x... 5|1 . 1|0 
0|1 . 1|5 x..... 5|2 .. 2|0 
0|2 ..x 2|5 ..... 5|2 .. 2|0 
0|3 ... 3|5 ...x.. 5|2 .. 2|0 
0|3 .x.. 3|5 ..... 5|3 ... 3|0 
0|4 .x... 4|5 ..... 5|3 ... 3|0 
0|5 ..... 5|5 ....x. 5|3 ... 3|0 
0|5 ....x. 5|5 ..... 5|4 .... 4|0 
0|5 ..... 5|0  0|5 ..... …
```
> Remove method for histogram

- .github/workflows/integration-tests.yml
- lib/storage/src/content_manager/raft_state.rs
- lib/storage/src/content_manager/toc.rs
- src/consensus.rs
- tests/consensus_tests/create_collection_and_check.py
- tests/consensus_tests/test_restart.sh
Closes #621 
Fixes TODOs about restart and adds a test for checking restart.
> Skip consensus init on restart

- lib/segment/src/index/field_index/histogram.rs
Avoid using `Cell` in histogram to make it Send + Sync
> refactor histogram: remove cell

- lib/api/src/grpc/qdrant.rs
> fix handwrited comment in qdrant.rs

- lib/segment/src/index/field_index/histogram.rs
> histogram: method to derive range by size

- Cargo.lock
- Cargo.toml
- docs/redoc/master/openapi.json
- lib/api/Cargo.toml
- lib/collection/Cargo.toml
- lib/segment/Cargo.toml
- lib/storage/Cargo.toml
- tools/generate_openapi_models.sh
Adjust OpenAPI generation script to preserve field order in the documentation.
> preserve fields order in OpenAPI schema

- lib/api/src/grpc/qdrant.rs
> mismatch generated file

- Cargo.lock
- Cargo.toml
- config/config.yaml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v0.8.0/openapi.json
- docs/roadmap/README.md
- lib/api/Cargo.toml
> release v0.8.0

- docs/redoc/master/openapi.json
- openapi/openapi-main.ytt.yaml
> allow server selection in OpenAPI schema

- lib/storage/src/content_manager/consensus_state.rs
Removes an unnecessary `RwLock` from parking-lot to avoid possible issues in the future regarding async. and deadlocks.
> There are no readers for on_consensus_op - it can be a simple Mutex

- lib/collection/src/collection_manager/holders/proxy_segment.rs
This PR fixes bug, reported in https://github.com/qdrant/qdrant/issues/724 detected by https://github.com/BurtonQin/lockbud
Thanks @BurtonQin for finding this!
> Fix possible double read deadlock

- tests/storage-compat/storage.tar.bz2
This PR refreshes the data used for the storage compatibility test.
It nows contains the raft state and payload indexes. 
```
agourlay@agourlay-thinkpad:~/Workspace/qdrant$ tar -cjvf storage.tar.bz2 storage
storage/
storage/raft_state
storage/collections/
storage/collections/test_collection/
storage/collections/test_collection/version.info
storage/collections/test_collection/0/
storage/collections/test_collection/0/segments/
storage/collections/test_collection/0/segments/d3958c52-2e75-4148-b18b-3e98241e0c59/
storage/collections/test_collection/0/segments/d3958c52-2e75-4148-b18b-3e98241e0c59/000005.log
storage/collections/test_collection/0/segments/d3958c52-2e75-4148-b18b-3e98241e0c59/IDENTITY
storage/collections/test_collection/0/segments/d3958c52-2e75-4148-b18b-3e98241e0c59/OPTIONS-000013 …
```
> Refresh storage compat. data

- tests/consensus_tests/test_collection_created_before.py
- tests/consensus_tests/test_many_collections.py
- tests/consensus_tests/utils.py
This PR adds an integration test to validate that the distributed deployment supports the creation of many collections in a row.
> Test many collections through consensus

- README.md
> Add clients to README.md

- tests/consensus_tests/test_learners_promoted_to_voters.py
- tests/consensus_tests/utils.py
A test for https://github.com/qdrant/qdrant/pull/735
Also added general `wait_for` python function for tests.
> Learners switch to voters test

- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/operation_effect.rs
- lib/collection/src/shard/local_shard.rs
- lib/collection/src/shard/local_shard_operations.rs
- lib/collection/src/shard/mod.rs
Traits for estimating how many points will be affected by some operation
> Operation effect estimation

- src/actix/api/collections_api.rs
- src/actix/api/update_api.rs
- src/common/points.rs
- src/tonic/api/points_common.rs
> Remove deprecated API for collections and points update

- lib/collection/src/lib.rs
- lib/collection/src/shard/proxy_shard.rs
- lib/collection/src/update_handler.rs
> Upd shard proxy

- lib/collection/src/update_handler.rs
- lib/segment/benches/hnsw_build_asymptotic.rs
- lib/segment/benches/hnsw_build_graph.rs
- lib/segment/benches/hnsw_search_graph.rs
- lib/segment/src/index/hnsw_index/graph_layers.rs
- lib/segment/src/index/hnsw_index/graph_layers_builder.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/hnsw_index/mod.rs
- lib/segment/src/index/hnsw_index/tests/mod.rs
> Graph layers remove code duplications

- lib/collection/src/lib.rs
- lib/collection/tests/common/mod.rs
- lib/collection/tests/snapshot_test.rs
- lib/storage/src/content_manager/consensus_state.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/src/lib.rs
Bring back shard number suggestion which was accidentally removed during refactor in #675 
Also some refactoring of shard distribution struct for shard number logic to fit better.
> Fix: bring back shard number suggestion

- lib/segment/src/telemetry.rs
> sliding window avg

- lib/collection/Cargo.toml
- lib/collection/benches/hash_ring_bench.rs
- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/lib.rs
- lib/collection/src/shard/local_shard_operations.rs
- lib/collection/src/shard/mod.rs
- lib/collection/src/shard/proxy_shard.rs
- lib/collection/src/shard/remote_shard.rs
- lib/collection/src/shard/shard_holder.rs
- lib/collection/src/tests/mod.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/storage/src/content_manager/shard_distribution.rs
- lib/storage/src/content_manager/toc.rs
- Creates a dedicated lock for shards storage inside the collection - collection does not need to be acquired as mutable if we only need to modify shards
- Simplify shards distribution proposal
Additional:
- hash ring benchmark
> Collection shards lock

- Cargo.lock
- Cargo.toml
- src/actix/actix_telemetry.rs
- src/actix/mod.rs
- src/common/mod.rs
- src/common/user_telemetry.rs
- src/main.rs
> Actix web telemetry

- lib/api/src/grpc/proto/collections_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection.rs
- lib/collection/src/shard/shard_holder.rs
- lib/storage/src/content_manager/toc.rs
- src/tonic/api/collections_internal_api.rs
- tests/consensus_tests/docker-compose.yaml
This PR adds the receiving part of a shard transfer as described in https://github.com/qdrant/qdrant/issues/789
Follow up to https://github.com/qdrant/qdrant/pull/794 but with better locking scheme introduced in https://github.com/qdrant/qdrant/pull/825
> [Sharding] Temporary shards for receiving transfer

- docs/redoc/master/openapi.json
- lib/collection/src/telemetry.rs
- lib/segment/src/telemetry.rs
- openapi/.gitignore
- openapi/openapi-telemetry.ytt.yaml
- src/common/telemetry.rs
- src/schema_generator.rs
- tools/generate_openapi_models.sh
> telemetry openapi

- docs/redoc/master/openapi.json
- lib/collection/src/telemetry.rs
- lib/segment/src/telemetry.rs
- openapi/.gitignore
- openapi/openapi-telemetry.ytt.yaml
- src/actix/api/mod.rs
- src/actix/api/telemetry_api.rs
- src/actix/mod.rs
- src/common/telemetry.rs
- src/schema_generator.rs
- tools/generate_openapi_models.sh
> telemetry web api

- lib/storage/src/content_manager/consensus/persistent.rs
- lib/storage/src/content_manager/consensus_state.rs
- src/consensus.rs
Based on our today's discussion with @generall . We decided that we shouldn't just log and skip consensus operation entries, instead we should try to reapply them and not progress further.
> Retry entries in case of service errors

- src/actix/mod.rs
> temporary disable actix telemetry middleware

- lib/api/src/grpc/transport_channel_pool.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shard/remote_shard.rs
- src/consensus.rs
> Recreate channel upd

- lib/segment/src/index/field_index/geo_index.rs
- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/field_index/numeric_index.rs
fixes https://github.com/qdrant/qdrant/issues/848
Apparently, we didn't check point value existed in index. That could create a problem in case of multiple insertions of the same point.
> Fix payload index overwrite vals

- Cargo.lock
- lib/api/Cargo.toml
- lib/api/src/grpc/transport_channel_pool.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shard/remote_shard.rs
- src/consensus.rs
Switches the channel use to closures as this way we can handle network errors
> Recreate transport channels on network error

- src/actix/mod.rs
> Turn on telemetry actix middleware

- docs/redoc/master/openapi.json
- lib/storage/src/types.rs
- src/common/telemetry.rs
Add Cluster state to telemetry data and add anonymization for cluster state
> cluster status telemetry

- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/shard/shard_holder.rs
Relates to https://github.com/qdrant/qdrant/pull/831 additional tasks
> Include shards transfer state in raft snapshot

- docs/redoc/master/openapi.json
- lib/collection/src/collection.rs
- lib/collection/src/operations/cluster_ops.rs
- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shard/shard_holder.rs
- openapi/openapi-collections.ytt.yaml
- src/actix/api/collections_api.rs
- src/common/collections.rs
- src/schema_generator.rs
- tests/consensus_tests/test_collection_shard_transfer.py
- tests/consensus_tests/utils.py
This PR adds a new API to trigger the shard transfers explicitly. (https://github.com/qdrant/qdrant/issues/861) 
It contains a new consensus test showing that the transfer works in practice.
> Move shard API

- docs/redoc/master/openapi.json
- lib/storage/src/content_manager/consensus_state.rs
- lib/storage/src/types.rs
- src/consensus.rs
- src/main.rs
Closes #864 
The failures can happen only in very rare corner cases, so I am bit unsure as to how to test it.
> Stop consensus on error

- lib/collection/src/shard/forward_proxy_shard.rs
- lib/collection/src/shard/transfer/shard_transfer.rs
> enable transferring of the current payload index during shard transfer

- docs/redoc/master/openapi.json
- lib/collection/src/collection.rs
- lib/collection/src/operations/cluster_ops.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shard/mod.rs
- lib/collection/tests/collection_test.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/toc.rs
- src/common/collections.rs
- tests/consensus_tests/test_collection_shard_transfer.py
Required in order to support the precise cancellation of transfer in case of reboot recovery
> Shard transfer from

- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/merge_optimizer.rs
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/shard/local_shard.rs
- lib/collection/src/telemetry.rs
- lib/segment/src/index/field_index/geo_index.rs
- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/telemetry.rs
> Optimizers and indices telemetry

- docs/redoc/master/openapi.json
> Openapi for optimizators telemetry

- lib/storage/src/content_manager/consensus/persistent.rs
- lib/storage/src/content_manager/consensus_state.rs
- src/consensus.rs
- src/main.rs
- src/startup.rs
- src/tonic/api/raft_api.rs
- src/tonic/mod.rs
- add comments
- move blocks of initialization out of main
- simplify interaction with consensus
> Refactor main startup foo

- config/config.yaml
Updates storage.optimizers.max_optimization_threads comment to reflect implementation.
* [✅] Have you followed the guidelines in our Contributing document?
* [✅] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
> Updates comment for max_optimization_threads

- lib/storage/src/content_manager/snapshots.rs
> remove temporary snapshot files during full snapshot

- lib/collection/src/shard/local_shard.rs
This PR removes the feature providing a default max number of optimizer threads when it is set to 0.
Why?:
- the feature was not completely wired up to the `UpdateHandler` which made it not functional
- we actually encourage users to use a single thread per optimizer to avoid contention
- it makes it possible to explicitly disable the optimizers by setting `max_optimization_threads` to 0
> remove default max optim. threads to enable switching off the optimizer

- lib/collection/src/collection_manager/optimizers/merge_optimizer.rs
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- tests/integration-tests.sh
> Fix integration test

- lib/collection/src/collection.rs
- lib/storage/src/content_manager/toc.rs
- src/main.rs
> Abort transfer on restart

- lib/storage/src/content_manager/consensus/operation_sender.rs
- lib/storage/src/content_manager/toc.rs
> Cancel transmission on bad arguments

- lib/collection/src/update_handler.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/common/rocksdb_operations.rs
- lib/segment/src/fixtures/payload_context_fixture.rs
- lib/segment/src/id_tracker/id_tracker_base.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/geo_index.rs
- lib/segment/src/index/field_index/index_selector.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/index_base.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs
- lib/segment/src/payload_storage/on_disk_payload_storage.rs
- lib/segment/src/payload_storage/payload_storage_base.rs
- lib/segment/src/payload_storage/payload_storage_enum.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/payload_storage/simple_payload_storage_impl.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
> flush as separate function

- lib/collection/src/collection.rs
Follow up on https://github.com/qdrant/qdrant/pull/954
Remove the dedicated implementation of `recommend` to avoid code duplication.
> recommend uses recommend_batch with single batch

- src/greeting.rs
> allow colored welcome in docker

- docs/redoc/master/openapi.json
- lib/collection/benches/batch_search_bench.rs
- lib/collection/src/collection.rs
- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/tests/common/mod.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/toc.rs
Relates to #934 
Current PR does not propagate the changes to API, this is left to be done after the release of the `0.10`.
> Add replication factor

- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/simple_segment_constructor.rs
- lib/segment/src/vector_storage/chunked_vectors.rs
- lib/segment/tests/fail_recovery_test.rs
- lib/segment/tests/filtrable_hnsw_test.rs
- lib/segment/tests/fixtures/segment.rs
- lib/segment/tests/payload_index_test.rs
- lib/segment/tests/segment_builder_test.rs
- tests/removes_test.sh
> small refactoring

- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection_manager/collection_updater.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/collection_manager/tests/mod.rs
- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/operation_effect.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/src/shard/conversions.rs
- lib/collection/src/shard/remote_shard.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/segment.rs
- src/tonic/api/points_common.rs
- src/tonic/api/points_internal_api.rs
Issue: https://github.com/qdrant/qdrant/issues/984
> Sync Points API

- lib/collection/src/collection.rs
- lib/collection/src/shard/replica_set.rs
- lib/collection/src/shard/shard_holder.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/toc.rs
> `SetShardReplicaState` operation

- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/shard/local_shard.rs
- lib/collection/src/shard/mod.rs
- lib/collection/src/shard/replica_set.rs
- lib/storage/src/content_manager/toc.rs
> Adds replica info to consensus snapshots

- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/collection/benches/batch_search_bench.rs
- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/segments_searcher.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/src/operations/types.rs
- lib/collection/tests/multi_vec_test.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/common/utils.rs
- lib/segment/src/data_types/mod.rs
- lib/segment/src/data_types/named_vectors.rs
- lib/segment/src/data_types/vectors.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/segment.rs
- lib/segment/tests/fixtures/segment.rs
- lib/segment/tests/segment_tests.rs
> [WIP] Named vectors struct

- Cargo.lock
- lib/segment/Cargo.toml
- lib/segment/benches/map_benchmark.rs
- lib/segment/src/data_types/mod.rs
- lib/segment/src/data_types/tiny_map.rs
On-stack implementation of Map, which works faster for small number of records.
Insert + get 3 records benchmark:
> tiny-map + benchmark

- docs/grpc/docs.md
Keeping the gRPC doc. in sync with the latest code changes.
> update gRPC docs

- docs/redoc/master/openapi.json
- lib/collection/src/collection.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/types.rs
- lib/collection/tests/multi_vec_test.rs
- src/tonic/api/points_common.rs
There were no good solution in codegen, so...
> use structure for better openapi generator compatibility

- lib/collection/src/config.rs
- lib/segment/src/data_types/vectors.rs
- lib/segment/src/types.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- openapi/tests/openapi_integration/helpers/collection_setup.py
- tests/basic_api_test.sh
> Minor doc and api in tests updates for multiple vectors

- lib/segment/src/common/utils.rs
- lib/segment/src/data_types/named_vectors.rs
- lib/segment/src/data_types/tiny_map.rs
> Integrate tiny vec to named vectors

- lib/segment/src/segment.rs
> change service error into field error

- QUICK_START.md
- QUICK_START_GRPC.md
- benches/service/collection_stress.js
- docs/redoc/master/openapi.json
- openapi/openapi-main.ytt.yaml
- openapi/tests/openapi_integration/test_euclid_dist.py
- openapi/tests/openapi_integration/test_fts.py
- tests/consensus_tests/create_collection_and_check.py
- tests/consensus_tests/test_collection_created_after.py
- tests/consensus_tests/test_collection_created_before.py
- tests/consensus_tests/test_collection_shard_transfer.py
- tests/consensus_tests/test_collection_sharding.py
- tests/consensus_tests/test_many_collections.py
- tests/consensus_tests/test_points_recommendation.py
- tests/consensus_tests/test_points_search.py
- tests/removes_test.sh
- tests/storage-compat/gen_storage_compat_data.sh
Multivector feature introduces changes in colletion creation api. Update usage of new api for
1. python integration tests
2. docs for rest and grpc
3. stress bench
+update openapi
> More multivector api updates

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/qdrant.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
Also removes `JsonSchema` from structs not exposed in API
> [replication] Generate API - replication factor PR follow up

- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/shard/replica_set.rs
`clippy::diverging_sub_expression` is needed to use `todo` in arguments
> Replication set `Change` enum

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/save_on_disk.rs
- lib/collection/src/shard/collection_shard_distribution.rs
- lib/collection/src/shard/replica_set.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/tests/common/mod.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/consensus_state.rs
- lib/storage/src/content_manager/conversions.rs
- lib/storage/src/content_manager/shard_distribution.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/src/dispatcher.rs
- lib/storage/tests/alias_tests.rs
- src/consensus.rs
Revert replication-related changes since v0.10.1
> Revert changes

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/save_on_disk.rs
- lib/collection/src/shard/collection_shard_distribution.rs
- lib/collection/src/shard/replica_set.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/tests/common/mod.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/consensus_state.rs
- lib/storage/src/content_manager/conversions.rs
- lib/storage/src/content_manager/shard_distribution.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/src/dispatcher.rs
- lib/storage/tests/alias_tests.rs
- src/consensus.rs
This reverts commit 28e8487542bc203486027be417f8ed6b1acbf8eb.
Some history changes due to branching into `dev` and `master`. They will be reintroduced in the next PR.
> Revert replication changes

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/save_on_disk.rs
- lib/collection/src/shard/collection_shard_distribution.rs
- lib/collection/src/shard/replica_set.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/tests/common/mod.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/consensus_state.rs
- lib/storage/src/content_manager/conversions.rs
- lib/storage/src/content_manager/shard_distribution.rs
- lib/storage/src/content_manager/toc.rs
- lib/storage/src/dispatcher.rs
- lib/storage/tests/alias_tests.rs
- src/consensus.rs
This reverts commit a2ed0cf5db1d387606e7dbaa998cb72e60156c30.
Continuation of https://github.com/qdrant/qdrant/pull/1055
> Revert "Revert replication changes (#1055)"

- lib/collection/src/shard/local_shard.rs
- lib/collection/src/shard/local_shard_operations.rs
- lib/collection/src/shard/proxy_shard.rs
- lib/collection/src/update_handler.rs
Limit the update queue size to apply back pressure on the uploader
> Limited queue

- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/shard/local_shard.rs
- lib/collection/src/shard/local_shard_operations.rs
- lib/collection/src/shard/proxy_shard.rs
- lib/collection/src/update_handler.rs
> Fix upsert freezes on rust client stress test

- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/shard/mod.rs
- lib/collection/src/shard/replica_set.rs
- lib/collection/tests/collection_test.rs
- src/common/collections.rs
Some stubs for the proposed replication design - https://github.com/qdrant/qdrant/issues/1036#issuecomment-1262247585
> Add `sync` and `sync_source` for transfers

- lib/collection/src/update_handler.rs
ibh, I was expecting clippy to catch this error
> send is a future

- lib/collection/src/collection.rs
- lib/collection/src/shard/mod.rs
- lib/collection/src/shard/replica_set.rs
- lib/collection/src/shard/shard_holder.rs
- lib/storage/src/content_manager/shard_distribution.rs
- lib/storage/src/content_manager/toc.rs
Other `todos` will be moved into separate issues as their scope is bigger
> Fix minor todos in ReplicaSet

- docs/redoc/master/openapi.json
- lib/storage/src/content_manager/consensus_state.rs
- lib/storage/src/types.rs
- src/consensus.rs
Duplicate of https://github.com/qdrant/qdrant/pull/1102 opened into dev
Also adds recording for last consensus update
> Fix: Do not rely on empty message for is_leader_established flag

- src/main.rs
- src/startup.rs
This should catch and log panic from all threads.
Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8bc8da0057aaff1d8bfb57095b07a355
> Adds panic hook

- lib/collection/src/shard/local_shard.rs
- lib/collection/src/shard/mod.rs
- lib/collection/src/shard/remote_shard.rs
- lib/collection/src/shard/replica_set.rs
- lib/collection/src/telemetry.rs
Closes https://github.com/qdrant/qdrant/issues/1098
> Telemetry data for replica set shard

- docs/redoc/master/openapi.json
- lib/collection/src/collection.rs
- lib/collection/src/operations/cluster_ops.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- src/common/collections.rs
https://github.com/qdrant/qdrant/issues/1120
> shard replica manipulation API

- docs/redoc/master/openapi.json
- lib/collection/src/collection.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shards/replica_set.rs
- lib/collection/src/shards/shard_holder.rs
- lib/collection/src/shards/transfer/shard_transfer.rs
- lib/collection/src/shards/transfer/transfer_tasks_pool.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/consensus/operation_sender.rs
- lib/storage/src/content_manager/mod.rs
- lib/storage/src/content_manager/toc.rs
- src/common/collections.rs
- tests/consensus_tests/test_collection_shard_transfer.py
- Fix validation of removing shard
- Fix shard transfer in case of existing local shard
> Replication transfer fixes

- docs/redoc/master/openapi.json
- lib/collection/src/collection.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/shards/replica_set.rs
- lib/storage/src/content_manager/consensus_state.rs
- lib/storage/src/content_manager/mod.rs
- lib/storage/src/content_manager/toc.rs
- openapi/openapi-cluster.ytt.yaml
- src/actix/api/cluster_api.rs
- src/consensus.rs
- src/tonic/api/raft_api.rs
> Allow peer force removal

- lib/collection/src/collection.rs
Warn: This logic does not cover all possible scenarios, where recovering node is so long dead, that it does not know where the alive shard is located. In this case cluster should rely on the external controller (in the cloud)
> Try to request sync if replica on the current node is dead

- lib/storage/src/content_manager/toc.rs
- tests/consensus_tests/test_collection_shard_transfer.py
- tests/consensus_tests/test_collection_shard_update.py
- tests/consensus_tests/test_collection_sharding.py
- tests/consensus_tests/test_many_collections.py
- tests/consensus_tests/test_points_recommendation.py
- tests/consensus_tests/test_points_search.py
- tests/consensus_tests/utils.py
This PR enables replication on our existing consensus tests to increase our coverage.
The number of shards was sometimes decreased to reduce the total amount of segments.
> Replication consensus tests

- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/types.rs
- lib/segment/tests/exact_search_test.rs
- lib/segment/tests/filtrable_hnsw_test.rs
Issue https://github.com/qdrant/qdrant/issues/1042
This PR provides an additional search option `exact` that disables approximate search.
> exact search parameter

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shards/local_shard.rs
- lib/collection/src/shards/local_shard_operations.rs
- lib/segment/src/index/index_base.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/segment.rs
- lib/segment/src/types.rs
- tests/consensus_tests/create_collection_and_check.py
- tests/consensus_tests/docker-compose.yaml
- tests/consensus_tests/insert_points.py
- tests/consensus_tests/test_restart.sh
- improve comments
- a bit more stable tests
- Report number of indexed points in the Info API:
> report indexed payload points in info api + other fixes

- src/consensus.rs
`handle_committed_entries` saved the increased applied index, before hard state (which includes increased commit index) was saved. Therefore if a peer was switched off in between this two save actions, the state on loading was incorrect - `applied > commit` - which is an impossible situation from the point of view of Raft consensus.
Move `handle_committed_entries` after all states were saved.
Previous order of operations was taken from raft lib [examples](https://github.com/tikv/raft-rs/blob/master/examples/five_mem_node/main.rs#L312), which used in memory storage and therefore did not account for the problems which might arise due to persisting state. Many other cases as we can see were not handled in that examples.
> Fix bug: applied index higher than commit on restart

- lib/segment/src/fixtures/payload_context_fixture.rs
- lib/segment/src/id_tracker/id_tracker_base.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
> Use less ram for id tracker fixes

- Cargo.lock
- Cargo.toml
- docs/grpc/docs.md
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v0.11.1/openapi.json
- lib/api/Cargo.toml
> Update to v0.11.1

- lib/collection/benches/batch_search_bench.rs
- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/tests/common/mod.rs
- lib/collection/tests/multi_vec_test.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/conversions.rs
- lib/storage/tests/alias_tests.rs
- src/consensus.rs
Fixes
```
[2022-11-09T10:18:06.583Z ERROR storage::content_manager::consensus_state] Failed to apply collection meta operation entry with service error: Service internal error: Json error: missing field `vectors`
```
> fix colletion params update

- lib/collection/src/shards/local_shard.rs
- lib/storage/src/content_manager/toc.rs
Small improvements in thread naming following my tracing deep dive.
> Improve thread naming

- lib/collection/src/shards/replica_set.rs
- src/tonic/api/raft_api.rs
- tests/consensus_tests/fixtures.py
- tests/consensus_tests/test_cluster_rejoin.py
* Use tokio Mutex instead of sync one
* Do not await for shard deactivation if it error is logical
* Integration Test for reproducing deadlock
> Fix consensus freezes

- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/operations/operation_effect.rs
- lib/collection/src/operations/payload_ops.rs
- lib/collection/src/shards/remote_shard.rs
- openapi/openapi-points.ytt.yaml
- openapi/tests/openapi_integration/test_payload_operations.py
- src/actix/api/update_api.rs
- src/common/points.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- src/tonic/api/points_internal_api.rs
Implement https://github.com/qdrant/qdrant/issues/1228
> Full payload update

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection_manager/collection_updater.rs
- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/operation_effect.rs
- lib/collection/src/operations/payload_ops.rs
- lib/collection/src/shards/conversions.rs
- lib/collection/tests/collection_test.rs
- openapi/tests/openapi_integration/test_payload_operations.py
- src/tonic/api/points_common.rs
I am not really proud with this one, mostly due to code duplication and some API inconsistency, that have to maintain due to backward compatibility.
But the code should be simplified once we can remove deprecated fields from the gRPC
> Update points by filter

- lib/collection/src/operations/types.rs
Fixes https://github.com/qdrant/qdrant/issues/1275
> fix 404 error code propagation

- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
> Remove obsolete internal scorer

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection.rs
- lib/collection/src/lib.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/recommendations.rs
- lib/collection/tests/collection_test.rs
- lib/collection/tests/multi_vec_test.rs
- lib/storage/src/content_manager/toc.rs
- openapi/tests/openapi_integration/test_multicollection_reco.py
- src/actix/api/recommend_api.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- src/tonic/api/points_internal_api.rs
Implements https://github.com/qdrant/qdrant/issues/1265
> Recommendation with other collection

- src/consensus.rs
This PR tackles the flaky `triple_replication` consensus test https://github.com/qdrant/qdrant/issues/1315
Being [able](https://github.com/qdrant/qdrant/pull/1335) to retrieve and [enrich](https://github.com/qdrant/qdrant/pull/1337) logs has shown the root cause of the test flakiness.
When starting a node with a Raft state, we check if the node has changed its address. 
If it is the case, we need to contact the known peers to inform them that the `peer_id` of this node is now associated to a different address.
Otherwise no information can be pushed to the node.
During a [failed](https://github.com/qdrant/qdrant/actions/runs/3904145015) run, the logs show clearly that we were unable to inform any of the nodes.
```
[peer_0_restarted.log][8482310807476585694][2023-01-12T18:05:55.295Z WARN …
```
> Retry recovering from known peers

- lib/collection/src/collection.rs
While investigating a problem with collection snapshots I realized that we do not have user facing logs for it.
There are only debug logs for the snapshotting of the underlying segments.
With this PR users can clearly see when a collection is being snapshotted and were it is saved.
> Add user facing logs for collection snapshot

- lib/segment/tests/filtrable_hnsw_test.rs
fix for https://github.com/qdrant/qdrant/issues/1378
> Fix flacky hnsw

- lib/collection/src/collection.rs
- lib/collection/src/shards/replica_set.rs
- lib/collection/src/shards/transfer/shard_transfer.rs
- tests/consensus_tests/test_two_follower_nodes_down.py
This PR detects dead shard and request pro-actively transfers if possible.
> Recover dead shards pro-actively

- lib/collection/src/operations/consistency_params.rs
- lib/collection/src/operations/mod.rs
Issue: https://github.com/qdrant/qdrant/issues/1372
Added both - majority and quorum with slightly different pattern
> add enum for read consistency

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/src/shards/conversions.rs
- lib/collection/src/shards/remote_shard.rs
- openapi/openapi-collections.ytt.yaml
- openapi/openapi-points.ytt.yaml
- src/actix/api/update_api.rs
- src/common/points.rs
- src/schema_generator.rs
- src/tonic/api/points_common.rs
- tests/basic_grpc_test.sh
Issue: https://github.com/qdrant/qdrant/issues/1374
> add write consistency param to rest and grpc api

- Cargo.toml
Use link time optimization. Shows a speedup in most benchmarks.
> Use LTO for release and benchmark builds

- .github/workflows/rust.yml
- Cargo.lock
- lib/collection/Cargo.toml
- lib/collection/benches/batch_search_bench.rs
- lib/collection/benches/hash_ring_bench.rs
- lib/collection/src/common/stoppable_task_async.rs
- lib/collection/src/wal.rs
- lib/segment/Cargo.toml
- lib/segment/benches/conditional_search.rs
- lib/segment/benches/hnsw_build_asymptotic.rs
- lib/segment/benches/hnsw_build_graph.rs
- lib/segment/benches/hnsw_search_graph.rs
- lib/segment/benches/id_type_benchmark.rs
- lib/segment/benches/map_benchmark.rs
- lib/segment/benches/serde_formats.rs
- lib/segment/src/madvise.rs
- lib/storage/Cargo.toml
Fixes for windows:
- disable pprof
- minor fixes in test
- update CI
- use compatible WAL
> Windows support

- Cargo.lock
- lib/segment/Cargo.toml
- lib/segment/src/types.rs
- lib/segment/src/utils/fmt.rs
- lib/segment/src/utils/mod.rs
Trying to properly fix [this](https://github.com/qdrant/qdrant/commit/1a39990ee91e76e07fcf5f8d0410394d7d43e074) issue.
> Reimplement `ExtendedPointId` deserialization

- lib/collection/src/shards/replica_set.rs
Issue: https://github.com/qdrant/qdrant/issues/1423
> fix file hamdlers release order

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/segment/src/index/field_index/map_index.rs
- lib/segment/src/index/query_optimization/condition_converter.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/types.rs
- openapi/tests/openapi_integration/test_filter.py
This adds the necessary parsing and handling for filtering over a collection of values ergonomically, rather than having to write multiple match statements inside a dedicated `should`.
Resolves #1196 
This allows for the following syntax:
```json
{
"filter": {
"must": [
{
"should": [
{
"key": "city",
"match": {
"value": "New York"
}
},
{
"key": "city",
"match": {
"value": "San Francisco"
}
},
{
"key": "city",
"match": {
"value": "Tokio"
}
}
]
}
]
}
...
}
```
To be simplified into:
```json
{
"filter": {
"must": [
{
"key": "city",
"match": {
"any": [
"San Francisco",
"New York",
"Tokyo",
]
}
}
]
}
...
}
```
Which makes it a lot more pleasant to write.
Should this PR be merged, I'll write the appropriate documentation in the docs repo
2. [x] Have you …
> feat: add `"any"` to `"match"` statements

- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/operations/payload_ops.rs
- lib/collection/tests/collection_restore_test.rs
- lib/segment/src/common/utils.rs
- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/geo_index.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/types.rs
- lib/segment/tests/payload_index_test.rs
- openapi/tests/openapi_integration/test_nested_payload_indexing.py
Follow up on https://github.com/qdrant/qdrant/pull/1465
This PR:
- propagates the multi-values extracted from the payload by path to indexing
- unit test nested indexing
- integration test nested indexing
Some of the testing infra. was duplicated to accommodate the specifics of nested fields. It might be able to merge it later.
> Nested payload filters

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.0.3/openapi.json
- lib/api/Cargo.toml
> upd to v1.0.3

- lib/collection/src/collection_manager/tests/mod.rs
- lib/segment/benches/vector_search.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
- lib/segment/tests/hnsw_quantized_search_test.rs
- lib/segment/tests/payload_index_test.rs
> Vector storages enum

- lib/storage/src/content_manager/alias_mapping.rs
- lib/storage/src/content_manager/toc.rs
- openapi/tests/openapi_integration/test_alias.py
- Check if alias exists on collection creation
- Force delete alias on collection deletion
- Tests
> improve validation for aliases

- lib/segment/benches/vector_search.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/segment/src/vector_storage/quantized/scalar_quantized.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
> Remove vector scorer trait

- lib/segment/src/index/mod.rs
- lib/segment/src/index/payload_index_base.rs
- lib/segment/src/index/vector_index_base.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
> Enum vector index

- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/field_index/tests/histogram_i64_tests.rs
- lib/segment/src/index/field_index/tests/histogram_test_utils.rs
- lib/segment/src/index/field_index/tests/histogram_tests.rs
- lib/segment/src/index/field_index/tests/mod.rs
related issue:  https://github.com/qdrant/qdrant/issues/1552
> Fix histogram for large integer values

- lib/collection/src/tests/mod.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/src/tests/wal_recovery_test.rs
- lib/segment/src/index/field_index/geo_index.rs
- openapi/tests/openapi_integration/test_geo_payload_index.py
> Fix values count loading in geoindex

- lib/segment/src/index/field_index/geo_index.rs
> fix remove geo index

- Cargo.lock
> update quantization build

- config/config.yaml
- src/actix/mod.rs
- src/common/helpers.rs
- src/consensus.rs
- src/settings.rs
- src/tonic/mod.rs
Tiny fixes on top of #1581. Opened a separate PR, as adding these changes directly to #1581 would require pushing to @stencillogic's repo, which seems kinda annoying to everyone involved.
> Add TLS support bikeshedding (#1593, #1581)

- README.md
- docs/DEVELOPMENT.md
- docs/grpc/docs.md
- docs/roadmap/roadmap-2022.md
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/proto/json_with_int.proto
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/config_diff.rs
fixed typo and small grammatical errors in the documentation.
> fixed typos in *.proto files

- src/common/helpers.rs
- src/common/telemetry_ops/app_telemetry.rs
Some minor nitpicks or improvements of things I came across that didn't really fit in another PR.
See commits for specific changes.
I'll keep doing these if they appear useful.
> General improvements

- lib/api/Cargo.toml
- lib/collection/Cargo.toml
- lib/storage/Cargo.toml
Fixes <https://github.com/qdrant/qdrant/issues/1632>.
> Fix `lib/collection` tests

- docs/redoc/master/openapi.json
- lib/api/src/grpc/models.rs
- lib/storage/src/content_manager/snapshots/mod.rs
- openapi/openapi-snapshots.ytt.yaml
- openapi/openapi.lib.yml
- openapi/tests/openapi_integration/test_snapshot.py
- src/actix/api/cluster_api.rs
- src/actix/api/retrieve_api.rs
- src/actix/api/snapshot_api.rs
- src/actix/helpers.rs
- src/common/collections.rs
- src/tonic/api/snapshots_api.rs
- src/tonic/mod.rs
> feat: add wait param for all snapshot API

- lib/segment/src/common/utils.rs
- openapi/tests/openapi_integration/test_basic_retrieve_api.py
Is Empty
- This condition will match all records where the field reports either does not exist, or have NULL or [] value.
> Restore is empty functions as before

- lib/collection/src/shards/replica_set.rs
- lib/segment/benches/vector_search.rs
This is a WIP/partial fix. Node still fails. :(
> Fix node failure during highly parallel updates

- QUICK_START_GRPC.md
> Fix typo in QUICK_START_GRPC.md

- docs/redoc/master/openapi.json
- lib/segment/src/types.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
The quantization configuration should be verified as well on collection creation.
> Verify quantization configuration on collection creation

- docs/redoc/master/openapi.json
- src/common/telemetry.rs
- src/common/telemetry_ops/app_telemetry.rs
Adds the app's startup date to the telemetry endpoint.
Waiting for #1668:
- Anonymize date
- Format date
- Update telemetry test
> [WIP] Include startup date in telemetry

- config/config.yaml
This updates a comment in `config.yml` to match new changes. Done in tandem with <https://github.com/qdrant/docs/pull/89>.
> Minor HNSW configuration comment improvement to match docs

- lib/segment/Cargo.toml
- lib/segment/src/common/utils.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/types.rs
Fix `IsEmpty` for the nested payload case
> make is-empty condition consistent with all other conditions

- docs/redoc/master/openapi.json
- lib/collection/benches/batch_search_bench.rs
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/optimizers_builder.rs
- lib/collection/src/shards/replica_set.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/tests/common/mod.rs
- lib/storage/tests/alias_tests.rs
- openapi/tests/openapi_integration/test_vector_config.py
The suggested way of disabling indexing is to put a really high number in this field, so I just converted it to an Option, and in case it is None -> it becomes usize::max.
Fixes #1621 
> Allow `indexing_threshold=null` to disable indexing

- .github/PULL_REQUEST_TEMPLATE.md
> doc: `cargo fmt` is not linting

- Cargo.lock
- lib/collection/Cargo.toml
- lib/storage/Cargo.toml
upd wal dep, related issue: https://github.com/qdrant/qdrant/issues/1735
> update wal deps

- lib/segment/src/utils/fs.rs
- tests/consensus_tests/test_snapshot_recovery.py
While restoring snapshot, we have to untar and move some files and/or directories on disk. In case we are moving a directory, and the destination directory already exists, sub-files of the source directory were moved improperly. This PR fixes it.
__TODO:__
> Fix payload index snapshot restoration

- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/segments_searcher.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/data_types/named_vectors.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/fixtures/index_fixtures.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
- lib/segment/tests/disbalanced_vectors_test.rs
Added a test which is supposed to pass in current version, but it does not.
Also implemented changes in segment interface to be able to perform the test
> update segment to handle optional vectors + add test

- .github/workflows/release-artifacts.yml
> Added workflow to link binaries with releases

- config/config.yaml
- src/consensus.rs
- src/main.rs
- src/settings.rs
Closes #1771.
This is an alternative to #1773.
> feat: embed default config file at compile time

- docs/redoc/master/openapi.json
- lib/api/build.rs
- lib/api/src/grpc/qdrant.rs
- lib/segment/src/types.rs
HNSW `m=0` case is valid and required in API
> Revert hnsw m min value validation

- docs/redoc/master/openapi.json
- lib/collection/src/operations/config_diff.rs
> remove m validation for hnswconfig

- docs/grpc/docs.md
- lib/api/build.rs
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/proto/collections_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/conversions.rs
- src/tonic/api/collections_api.rs
GRPC implementation of Collection Cluster API. 
As requested by https://github.com/qdrant/rust-client/issues/32
Related with https://github.com/qdrant/rust-client/pull/33
> Collection Cluster API via GRPC

- README.md
Changes:
1. Fixes Broken link for Llama Index
> Fix broken link for Llama Index

- README.md
> Add link to blog for Semantic Kernel

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/build.rs
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/grpc/validate.rs
- lib/collection/src/operations/conversions.rs
- lib/segment/src/types.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/tests/hnsw_quantized_search_test.rs
> Product quantization compression api

- lib/segment/src/index/hnsw_index/graph_links.rs
> Fix typo in graph_links.rs

- .github/workflows/docker-image.yml
- Cargo.toml
- Dockerfile
- lib/segment/src/index/struct_payload_index.rs
- tools/mold_arch.sh
> Custom build profile for CI docker builds

- .github/workflows/integration-tests.yml
- Cargo.toml
- Dockerfile
- tests/consensus_tests/run_tests.sh
- tests/consensus_tests/test_restart.sh
- tests/low-ram/low-ram.sh
- tests/tls/test_tls.sh
fixes:
```
warning: /home/generall/projects/vector_search/qdrant/Cargo.toml: unused manifest key: profile.ci.linker
```
CC  @Jesse-Bakker
> move linker to docker

- lib/segment/src/common/utils.rs
- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/query_optimization/condition_converter.rs
- lib/segment/src/index/query_optimization/mod.rs
- lib/segment/src/index/query_optimization/nested_filter.rs
- lib/segment/src/index/query_optimization/nested_optimizer.rs
- lib/segment/src/index/query_optimization/optimizer.rs
- lib/segment/src/index/struct_filter_context.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/payload_storage/nested_query_checker.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/types.rs
- lib/segment/tests/nested_filtering_test.rs
Done:
- Switch to bitset
- Fix should integrstion test
ToDo:
- Check values_count in `nested_field_condition_index`
- More tests: index retrieve vs checks , text index, ???
> WIP: Nested object filter suggestions

- Cargo.lock
- lib/segment/Cargo.toml
- lib/segment/src/fixtures/index_fixtures.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
- lib/segment/tests/hnsw_quantized_search_test.rs
> product quantization with stopper

- lib/segment/src/vector_storage/mmap_vectors.rs
Resolves:
```
mnt-qdrant_bench-1  | [2023-05-12T10:40:42.502Z ERROR segment::vector_storage::mmap_vectors] Failed to lock deleted flags for quantized mmap segment in memory: Cannot allocate memory (os error 12)
```
in case of using inside docker with memory limits
> disable mlock

- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs
The path was wrong.
ToDo:
tests to prevent this from happening again
> fix broken snapshot for quantized data

- lib/collection/src/collection_manager/fixtures.rs
This fixes a flaky vacuum optimizer test that started appearing when optional named vectors were implemented.
The failing test relied on an exact number of points. The test fixture to generate a random segment sporadically generated overlapping point IDs, resulting in a lower number of points.
This change adds a simple point generator struct generating unique points to prevent this in the future.
---
Fixes: https://github.com/qdrant/qdrant/actions/runs/4870451938/jobs/8686212075?pr=1602#step:6:101
```
---- collection_manager::optimizers::vacuum_optimizer::tests::test_vacuum_deleted_vectors stdout ----
thread 'collection_manager::optimizers::vacuum_optimizer::tests::test_vacuum_deleted_vectors' panicked at 'assertion failed: `(left == right)`
left: `999`,
right: `1000`', …
```
> Fix flaky vacuum test since optional named vectors

- openapi/tests/openapi_integration/test_optional_vectors.py
Part of <https://github.com/qdrant/qdrant/issues/1045>.
Adds an additional test case for optional vectors, which was not explicitly tested yet.
> Add integration test for error when updating vectors on unknown point

- docs/grpc/docs.md
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/shards/conversions.rs
- src/tonic/api/points_common.rs
More consistent gRPC API for updating vectors
> Update default vector with proto

- lib/segment/src/index/struct_payload_index.rs
Fixes the potential problem of corrupted persistence of payload index.
We want to always save configuration as the last step, cause configuration save is atomic and works as an indicator if operation was correctly applied or not.
bonus: removes outdated `drop_index` logic
> always save config after operation is done

- config/config.yaml
- src/main.rs
- tests/tls/tls_config.yaml
> Fix documentation links

- .gitignore
- Dockerfile
- config/development.yaml
- src/actix/api_key.rs
- src/actix/mod.rs
- src/greeting.rs
- src/main.rs
- src/settings.rs
- tools/sync-web-ui.sh
ToDo:
- Exception for authentication
- Option to disable web ui from config
- ???
> Web UI integration

- lib/segment/tests/integration/segment_builder_test.rs
This PR adds basic debug info for the test `test_building_cancellation` which is quite flaky on Windows.
e.g. https://github.com/qdrant/qdrant/actions/runs/5189405490/jobs/9357556238?pr=2032#step:6:1302
```
failures:
---- tests::test_building_cancellation stdout ----
thread 'tests::test_building_cancellation' panicked at 'assertion failed: time_fast < time_long', lib\segment\tests\segment_builder_test.rs:144:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
tests::test_building_cancellation
test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.39s
error: test failed, to rerun pass `-p segment --test segment_builder_test`
Error: Process completed with exit code 1.
```
> Add debug info for flaky test Windows

- src/actix/mod.rs
Refs: https://github.com/qdrant/qdrant/pull/2046#issuecomment-1584445594
> Downgrade missing static folder error to warning

- lib/collection/src/operations/types.rs
- lib/storage/src/content_manager/toc.rs
- openapi/tests/openapi_integration/test_init_from_collection.py
ToDo: check if creating collection with more vectors that original doesn't cause problems
> more accurate check for collections compatibility

- lib/segment/src/segment.rs
- lib/segment/src/utils/fs.rs
- check if snapshot have symlinks instead of files and fail if so
> check integrity of snapshot

- lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs
- openapi/tests/openapi_integration/helpers/collection_setup.py
- openapi/tests/openapi_integration/test_optional_vectors.py
- openapi/tests/run_docker.sh
- fix insertion of vectors in chunked mmap vector storage
- enables running of all integration tests with on_disk vectors
> run all integration tests with on_disk=true and false

- lib/segment/src/common/mod.rs
- lib/segment/src/segment.rs
Fixes <https://github.com/qdrant/qdrant/issues/2121>. Supersedes <https://github.com/qdrant/qdrant/pull/2123>.
Check for vector compatibility on our segment interface.
We did some basic compatibility checks before for vector names, this extends it to vector elements (dimensionality) as well and adds it to all relevant functions.
> Improve vector compatibility checks, fix dimensionality panic

- lib/segment/src/types.rs
This is the first commit for the new feature `Geo Filter by Polygon`(#795) that introduces the GeoPolygon struct, representing a polygon defined by a list of coordinates. It includes the check_point method to determine if a given point is inside the polygon. Test cases validate the functionality for different scenarios.
Summary:
- Added GeoPolygon struct with coordinate vertices.
- Implemented check_point method for point-in-polygon check.
- Added corresponding test cases for coverage.
> Add GeoPolygon and tests

- src/tonic/mod.rs
Add SIGTERM listener to the gRPC services
> support for SIGTERM

- lib/storage/src/content_manager/toc.rs
The problem reliably reproduces on at least 2 machines with the following script: https://gist.github.com/timvisee/af63be53bef8d60b0542bddc2a29be8a
Might be related to: https://github.com/qdrant/qdrant/issues/2141
Further audit for double-read problem with tokio locks might be required
> Fix double-read deadlock in the get-collection

- lib/storage/src/content_manager/toc.rs
- src/actix/mod.rs
Fixes <https://github.com/qdrant/qdrant/issues/2126>.
> Use configured temporary directory in actix multipart file uploads

- Cargo.lock
- lib/collection/Cargo.toml
- lib/collection/src/grouping/aggregator.rs
- lib/collection/src/grouping/group_by.rs
- improve termination condition check
- add all_ids to aggregator to avoid flat_map
- use ahash for aggregator hashmaps and hashsets
> Small group_by improvements

- lib/storage/src/content_manager/toc.rs
Check that collection directory is empty before creating
- If directory exists and collection config presents (collection is loadable), then report an error. (should not happen because of the lock, but still better to check)
- If directory exists but no collection config (collection if partially created or corrupted) - clear directory and start over.
Related issue: https://github.com/qdrant/qdrant/issues/2176
> clear collection directory before creating a new collection

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- tools/missed_cherry_picks.sh
A patch release bumping Qdrant to v1.3.1.
> Bump version to v1.3.1

- lib/segment/src/index/field_index/geo_hash.rs
This is one of a series of commits for the new feature Geo Filter by Polygon(https://github.com/qdrant/qdrant/issues/795) that add function polygon_hashes that retrieves as-high-as-possible with maximum of `max_regions` number of geo-hash guaranteed to contain the whole polygon. It also includes two helper functions: 1) `check_polygon_intersection` and 2) `minimum_bounding_rectangle_for_polygon`. Test cases validate the functionality for different scenarios.
> Add fn polygon_hashes and its helper functions

- src/main.rs
- src/snapshots.rs
Fixes <https://github.com/qdrant/qdrant/issues/2127>.
> Use configured temporary directory for recovering snapshots

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/shards/conversions.rs
- lib/segment/Cargo.toml
- lib/segment/benches/boolean_filtering.rs
- lib/segment/src/fixtures/payload_context_fixture.rs
- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/index/field_index/index_selector.rs
- lib/segment/src/types.rs
- openapi/tests/openapi_integration/test_payload_indexing.py
- src/tonic/api/points_common.rs
Exposes #2107 to rest and grpc interfaces
> Expose & benchmark binary index

- .github/workflows/release-artifacts.yml
- .github/workflows/rust.yml
- .github/workflows/storage-compat.yml
Also run CI tests on macOS. This hopefully minimizes the chance of sudden macOS errors on release.
> Also run CI tests on macOS

- Cargo.lock
- Cargo.toml
- lib/collection/Cargo.toml
- lib/storage/Cargo.toml
Include fix for ignoring extra files
> upd wal deps

- lib/collection/src/collection.rs
- lib/collection/src/shards/transfer/shard_transfer.rs
Alternative to https://github.com/qdrant/qdrant/pull/2246
> limit transfers scheduling on sync-local-state

- .codespellrc
- .github/workflows/codespell.yml
- docs/DEVELOPMENT.md
- lib/api/src/grpc/transport_channel_pool.rs
- lib/collection/src/collection.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/collection_manager/segments_searcher.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/collection/src/shards/local_shard.rs
- lib/segment/src/common/mmap_type.rs
- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/index/hnsw_index/graph_layers_builder.rs
- lib/segment/src/index/query_optimization/condition_converter.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/storage/src/content_manager/consensus/persistent.rs
- openapi/tests/openapi_integration/test_basic_retrieve_multivec_api.py
- openapi/tests/openapi_integration/test_nested_payload_indexing.py
- src/tonic/mod.rs
* [I think so] Have you followed the guidelines in our Contributing document?
> codespell: workflow, config, typos fixed

- lib/collection/src/common/stoppable_task.rs
Trying to find a reason why stopable task is flacky on windows and macos
> try to fix flacky macos test

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/segment/src/types.rs
For release purposes, we are going to disable unfinished geo_polygon functionality from the API for now.
Feel free to rollback with PR as soon as geo-polygon functions are implemented internally
> temporary exclude geo_polygon from API

- lib/collection/src/shards/replica_set.rs
> Fix `ShardReplicaSet::update_locally_disabled` logic

- Cargo.lock
> Apply quantization lib fix of quantile interval panic

- lib/collection/src/shards/replica_set.rs
Caused here:
https://github.com/qdrant/qdrant/actions/runs/5726188204
> fix codespell error for inconcistency word

- openapi/tests/requirements-freeze.txt
- tests/storage-compat/populate_db/requirements-freeze.txt
This PR addresses the security updates of `certifi`
- https://github.com/qdrant/qdrant/security/dependabot/46
- https://github.com/qdrant/qdrant/security/dependabot/45
This PR supersedes the following PRs:
- https://github.com/qdrant/qdrant/pull/2329
- https://github.com/qdrant/qdrant/pull/2331
- https://github.com/qdrant/qdrant/pull/2332
> certifi 2023.7.22

- lib/collection/src/collection.rs
- lib/collection/src/shards/replica_set.rs
> Log shard state change

- openapi/tests/openapi_integration/test_snapshot.py
- openapi/tests/openapi_integration/test_vector_config.py
- openapi/tests/run_docker.sh
- tests/basic_grpc_test.sh
Fix the timeout CI on windows
/claim #2265
> increment time-out on CI windows

- lib/segment/src/vector_storage/common.rs
- lib/segment/src/vector_storage/mmap_vectors.rs
- lib/segment/src/vector_storage/mod.rs
- lib/segment/src/vector_storage/raw_scorer.rs
- lib/segment/src/vector_storage/tests/async_raw_scorer.rs
- src/main.rs
related issue: https://github.com/qdrant/qdrant/issues/2350
Thanks @ava57r for reporting the issue!
> do not initialize io-uring object if async scorer is not enabled

- lib/segment/src/id_tracker/id_tracker_base.rs
Fixes https://github.com/qdrant/qdrant/issues/2374
This removes randomness from point sampling by using a fixed seed for it. Sampling is used by HNSW/ID tracker.
It fixes _randomness_ observed in <https://github.com/qdrant/qdrant/issues/2374>.
After this change the number of points in a collection determines tits sampling pattern. I have no concerns about that though.
> Use seeded randomness for ID tracker point sampling

- lib/collection/src/shards/replica_set.rs
This PR re-enabled deactivation of failed shards in `Initializing` state.
In #1286 we explicitly switched to only deactivating shards in `Active` state on update failure. See:
- [`replica_set.rs` blame](https://github.com/qdrant/qdrant/blame/master/lib/collection/src/shards/replica_set.rs#L1195-L1229)
- [#1286 PR](https://github.com/qdrant/qdrant/pull/1286/files#diff-8772e4c0f0c259c45baa424c4c69c0d16236cf71bc592d46918c7630b13f680dR877-R913)
__TODO:__
- kill cluster node
- create collection and upsert some points to it
- restart cluster node
- wait for a little while, and check that restarted node synchronized any missing points …
> Deactivate failed nodes in `Initializing` state

- lib/segment/src/entry/entry_point.rs
> Cancel quantization without panic

- .github/workflows/integration-tests.yml
- tests/consensus_tests/test_collection_creation_after_dropping.py
- Add a test case to replicate #1662
> Add test case for create collection after dropping in cluster mode

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/google.protobuf.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/segments_searcher.rs
- lib/collection/src/optimizers_builder.rs
- lib/collection/src/shards/local_shard.rs
- lib/collection/src/shards/local_shard_operations.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/segment.rs
- lib/segment/src/telemetry.rs
- lib/segment/src/types.rs
- lib/segment/tests/integration/segment_tests.rs
- lib/storage/src/content_manager/snapshots/download.rs
> Add `indexed_only` to speed up search

- Cargo.lock
- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/build.rs
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/grpc/validate.rs
- lib/collection/src/collection.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/shards/local_shard.rs
- lib/segment/Cargo.toml
- lib/segment/src/compat.rs
- lib/segment/src/types.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
Integrate Binary Quantization provided here https://github.com/qdrant/quantization/pull/18
> binary quantization

- docs/redoc/master/openapi.json
- src/common/points.rs
Prevents unnamed structures in OpenAPI:
> Fix batch update api schema

- lib/collection/src/shards/replica_set.rs
> Improve local shard read operation handling in case shard is write-locked

- Cargo.lock
> Quantization version up

- src/common/metrics.rs
- src/common/telemetry_ops/app_telemetry.rs
Issue: https://github.com/qdrant/qdrant/issues/2535
result preview:
```
app_status_recovery_mode 0
```
> Recovery mode in metrics

- docs/redoc/master/openapi.json
- lib/collection/src/operations/snapshot_ops.rs
- openapi/openapi-shard-snapshots.ytt.yaml
- openapi/tests/openapi_integration/test_shard_snapshot.py
- src/actix/api/snapshot_api.rs
- src/schema_generator.rs
- tools/generate_openapi_models.sh
- OpenAPI definitions
- OPenAPI tests
- minor consistency changes
> openapi definitions for shard shashots API

- .github/workflows/docker-image.yml
- Dockerfile
Exploring https://github.com/qdrant/qdrant/issues/2572
Context: https://github.com/opencontainers/image-spec/blob/main/annotations.md
This makes one more version to update.
> add OCI labels on docker image

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.5.x/openapi.json
- lib/api/Cargo.toml
A feature release bumping Qdrant to v1.5.0.
> Bump version to 1.5.0

- lib/segment/tests/integration/segment_builder_test.rs
I merged #2094 which has a bit old. This PR solves clippy errors that now came up because of the merge.
> Fix clippy errors on segment_builder_test.rs

- lib/storage/src/content_manager/toc.rs
> Remove unused constant

- lib/collection/src/collection_manager/holders/segment_holder.rs
Fix for segment deadlock that occurred along with the following warning:
```
WARN collection::collection_manager::holders::segment_holder: Trying to read-lock all collection segments is taking a long time. This could be a deadlock and may block new updates.
```
A deadlock could occur because we were locking multiple segments from multiple places in different orders. This solves the issue by always locking non-appendable segments before appendable ones.
I've tested this fix locally a few times with a reproducable test case.
> Fix segment deadlock, reverse lock order during flush

- .github/workflows/rust.yml
- CONTRIBUTING.md
> Cargo test --all is deprecated, use --workspace instead

- lib/collection/src/save_on_disk.rs
Fixes #2676 
I had no reproducible way of making this flake locally, but increasing these times might work.
> Reduce `test_wait_for_condition_change` flakiness with higher times

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/recommendations.rs
- openapi/tests/openapi_integration/test_recommend.py
- src/tonic/api/points_common.rs
Needs #2661 and  #2662 
- Enable raw vectors as positive and negative examples
- Deprecates point id fields in favor for new enum in grpc
- Transparent enum in REST
> Allow vectors in recommend API

- lib/segment/src/spaces/simple_neon.rs
> Fix ARM-specific import after moving `ScoreType` to `common`

- docs/redoc/master/openapi.json
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/types.rs
Spotted by @joein in qdrant/qdrant-client#314
Updates the doc comments to reflect raw vectors as input
> Update new reco doc comments

- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/index/field_index/numeric_index.rs
- lib/segment/src/index/field_index/utils.rs
Fix for https://github.com/qdrant/qdrant/issues/2739
Basically replace `==` with `>=`
> better check for boundaries in range request

- lib/collection/src/collection.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shards/local_shard.rs
- lib/collection/src/shards/replica_set.rs
- lib/collection/src/shards/shard_holder.rs
Check that vector data (vector size and distance metric) from `segment.json` matches collection config (during collection load).
__TODO:__
> Check that segments are compatible with the collection on collection load

- lib/segment/benches/hnsw_build_asymptotic.rs
Benches panic on the fake metric. There is a user fix for this panic: https://github.com/qdrant/qdrant/pull/1958. Such a fix is incorrect because a mixture of metrics appears. Currently, the raw scorer constructor doesn't allow to use of custom metric types. That's why I propose to remove Fake Metric from the benches and use Dot instead.
> Remove fake metric from benches

- lib/segment/src/index/field_index/geo_hash.rs
- lib/segment/src/index/field_index/geo_index.rs
GeoHash has max len 12. We don't need to allocate memory for geohash string because we integrated `SmolStr` which allows storing string data on the stack.
> Stack allocated geohash

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection/collection_ops.rs
- lib/collection/src/collection/snapshots.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shards/shard_holder.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/conversions.rs
- lib/storage/src/content_manager/shard_distribution.rs
- lib/storage/src/content_manager/toc/collection_meta_ops.rs
- lib/storage/src/content_manager/toc/create_collection.rs
- lib/storage/src/dispatcher.rs
- lib/storage/tests/integration/alias_tests.rs
- src/consensus.rs
- src/migrations/single_to_cluster.rs
Tracking issue: https://github.com/qdrant/qdrant/issues/2807
- Add params to create collection with custom sharding
- fix snapshot persistence - save shard mapping with collection snapshot
- allow loading of shards by list of ids instead of iterator
> Shard key - create collection

- lib/segment/src/index/hnsw_index/graph_layers.rs
This PR resolves https://github.com/qdrant/qdrant/issues/2863
When creating a payload index, recall performance significantly deteriorates. 
I also tested searching with extremely high `hnsw_ef` values which didn't help with recall - which pointed me to a disconnected graph and I audited the graph construction code but couldn't find any case where it's being significantly mangled!
Eventually I found a bug in the search logic (which also somewhat affects graph construction, but from testing it's not as big of a problem there as much as it's on query time behavior).
The problem: When searching on a graph level and we're examining a node, we consider and score only `m` links (this is so that we prioritize the original `m` links instead of following the added links that came from payload …
> Fix overeager marking of visited points during search

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/collection/src/shards/replica_set/update.rs
> Add `ReplicaState::PartialSnapshot`

- lib/segment/src/index/field_index/geo_index.rs
> Mutable geo index

- config/config.yaml
> add update_rate_limit param into config file

- lib/storage/src/content_manager/mod.rs
> Remove unused function from content manager

- lib/collection/src/collection_manager/segments_searcher.rs
- lib/collection/src/discovery.rs
- lib/collection/src/lib.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/recommendations.rs
- lib/segment/src/data_types/vectors.rs
- lib/segment/src/vector_storage/async_raw_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs
- lib/segment/src/vector_storage/query/context_query.rs
- lib/segment/src/vector_storage/query/discovery_query.rs
- lib/segment/src/vector_storage/query/mod.rs
- lib/segment/src/vector_storage/query/reco_query.rs
- lib/segment/src/vector_storage/raw_scorer.rs
Needs #2851, tracked by #2790
- Created `DiscoveryRequest`
- Added `discovery.rs` with the logic for transforming a request with `RecommendExamples` to a `CoreSearchRequest`, so it includes all the batched vector fetching logic.
> Add `DiscoveryRequest` and preprocessing

- lib/segment/src/common/mod.rs
- lib/segment/src/data_types/vectors.rs
- lib/segment/src/fixtures/index_fixtures.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/src/vector_storage/simple_vector_storage.rs
> Remove temporary conversion to dense vector

- lib/segment/src/index/sparse_index/sparse_vector_index.rs
- lib/segment/tests/integration/sparse_vector_index_search_tests.rs
This PR adds extra tests for the `SparseVectorIndex` to assert that it can work with an underlying memmap inverted index.
I will comment some of the changes made.
> Extra tests for Sparse Vector Index

- lib/segment/src/index/hnsw_index/hnsw.rs
This PR improves the plain search fallback for HNSW.
The plain search is used for small cardinality and exact search, so it may handle a large amount of points.
I have noticed that we are re-evaluating the filter for each query vectors in the batch query.
This PR pre-computes the filtered points once to reuse it.
> Share filter results for plain search in HNSW

- lib/collection/src/collection/search.rs
Following #2904 and the new discovery api, while implementing brute-force local mode I realized ordering was not quite right when using euclidean metric. It would show the same results as in python implementation, but in inverse order.
This fixes it by setting the order to depend on metric but also on `QueryEnum` variant of the search.
> Fix results ordering for custom scored searches

- tests/consensus_tests/test_shard_snapshot_transfer.py
- tests/consensus_tests/test_shard_snapshot_transfer_cancel.py
tracking: https://github.com/qdrant/qdrant/issues/2432
- Integration test for snapshot-based shard transfer
- Test for transfer cancellation
> Test snapshot transfer during updates

- lib/collection/src/common/batching.rs
- lib/collection/src/common/fetch_vectors.rs
- lib/collection/src/discovery.rs
- lib/collection/src/recommendations.rs
- src/common/points.rs
Addition to <https://github.com/qdrant/qdrant/pull/3004>.
> Simplify signature of `batch_requests` in shard key routing

- lib/segment/benches/sparse_index_build.rs
- lib/segment/src/index/sparse_index/sparse_vector_index.rs
This PR fixes the issue of broken clippy on dev.
Two PRs conflicting with each other got merged without an intermediary rebase causing compilation issue.
> Fix sparse index build benchmark compilation

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/proto/collections_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/grpc/validate.rs
- lib/collection/src/collection/sharding_keys.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/operations/conversions.rs
- lib/storage/src/content_manager/toc/mod.rs
- lib/storage/src/dispatcher.rs
- openapi/openapi-shards.ytt.yaml
- src/actix/api/collections_api.rs
- src/actix/api/mod.rs
- src/actix/api/shards_api.rs
- src/actix/mod.rs
- src/common/collections.rs
- src/tonic/api/collections_api.rs
- tools/generate_openapi_models.sh
Tracking: https://github.com/qdrant/qdrant/issues/2807
- Create a dedicate APIs for creating and deleting shard
- Check consensus sync after shard key create operation is submitted
- Add missing operations into gRPC `UpdateCollectionClusterSetupRequest`
> Shard key create confirmation

- tests/consensus_tests/test_snapshot_recovery.py
- tests/consensus_tests/utils.py
Alternative to https://github.com/qdrant/qdrant/pull/3031
> await for uniform consensus after index creation

- lib/collection/src/shards/replica_set/update.rs
If user specified `write_consistency_factor = N`, it would mean, that failure to apply operation to `N` replicas will result in API failure (e.g. http 500).
This PR changes logic of shard deactivation to prevent reporting shards as dead in case if the whole operation is considered failed.
This logic might be desirable, cause it should create overall less amount of expensive shards transfers. 
In case write operation failed, it would be users responsibility to retry it and resolve storage consistency by re-trying the update operation.
Practical examples:
- replication factor 2, write_consistency_factor = 2
In this case update operation will never cause dead shards, but update will fail if any replica fail. 
Might be useful to scale throughput and eliminate SPOF for reads in the …
> alter deactivation behavior for write_consistency_factor

- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/collection/src/collection_manager/collection_updater.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/segments_searcher.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/point_ops.rs
- lib/segment/benches/vector_search.rs
- lib/segment/src/data_types/named_vectors.rs
- lib/segment/src/data_types/vectors.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs
- lib/segment/tests/integration/segment_tests.rs
- src/schema_generator.rs
Sparse vectors REST api (everything without collection/segment configs)
> Sparse vectors rest search and upsert

- README.md
- docs/roadmap/README.md
Updates main readme with dotnet client, and roadmap with done achievements.
Also updates myself as `code` contributor 💻
> Update main and roadmap READMEs

- lib/segment/src/common/rocksdb_wrapper.rs
We had `just_seeked` in our RocksDB iterator branching the iteration process.
I've removed this field by restructuring the iteration logic. On `next()`, we now return the current item and always seek to the next right after before returning.
This change likely has no effect on performance, it just makes iterating a bit nicer.
> Simplify RocksDB column operator, restructure to remove `just_seeked`

- lib/collection/src/collection_manager/segments_updater.rs
- lib/segment/src/spaces/simple.rs
> Remove redundant copy from sum iterator

- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/sparse_index/sparse_vector_index.rs
- lib/segment/src/index/vector_index_base.rs
- lib/segment/src/segment.rs
- lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
> sparse vector basic python client tests fixes

- lib/storage/src/content_manager/shard_distribution.rs
Extends <https://github.com/qdrant/qdrant/pull/3088>.
The above PR has just been merged, but I still wanted to add this change to it.
It is very unlikely that we ever need the 3rd level of comparison, and so this makes it lazy.
> Micro optimization for comparing peer shard count

- lib/sparse/src/index/search_context.rs
This PR introduces a mechanism for plain search over the inverted index.
The vectors are returned:
- by ascending point id
- only with values overlapping the query vector
> Plain search for inverted index

- docs/redoc/master/openapi.json
- lib/segment/benches/sparse_index_build.rs
- lib/segment/src/fixtures/sparse_fixtures.rs
- lib/segment/src/index/sparse_index/sparse_index_config.rs
- lib/segment/src/index/sparse_index/sparse_vector_index.rs
- lib/segment/src/types.rs
Full scan threshold for sparse vectors may be optional
> Optional sparse full scan threshold

- lib/api/src/grpc/conversions.rs
- tests/consensus_tests/test_sparse_points_search.py
Fix plus test to enable once the API lands on dev.
> Fix gRPC conversion for named sparse vectors

- docs/redoc/master/openapi.json
- lib/sparse/src/common/sparse_vector.rs
- openapi/tests/openapi_integration/test_sparse_vector_validations.py
This PR adds integration tests for the sparse vector validations.
It also improves the openapi documentation.
> Integration tests sparse vector validation

- Cargo.lock
- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/conversions.rs
- lib/segment/Cargo.toml
- lib/segment/src/spaces/simple.rs
- lib/segment/src/spaces/simple_avx.rs
- lib/segment/src/spaces/simple_neon.rs
- lib/segment/src/spaces/simple_sse.rs
- lib/segment/src/types.rs
- lib/segment/src/vector_storage/async_raw_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/src/vector_storage/raw_scorer.rs
- lib/segment/src/vector_storage/tests/async_raw_scorer.rs
- lib/segment/tests/integration/hnsw_quantized_search_test.rs
- openapi/tests/openapi_integration/test_manhattan_dist.py
- tools/schema2openapi/schema.json
Depends on <https://github.com/qdrant/quantization/pull/21>.
This pull request adds `Manhattan` (L1, taxicab) as a 4th distance type (related to https://github.com/qdrant/qdrant/issues/3052). I am aware that this is an ambitious pull request as a first contribution, but I need the functionality and I think it has a justified place in the product.
The related issue mentions generalized Lp, but I thought it did not make much sense to try to implement AVX/SSE/Neon versions for it.
I have tried to follow the `Euclid` distance implementation as close as I could and I have copied the tests related to `Euclid` distance and converted them to `Manhattan` distance tests. I have also created an OpenAPI integration test for it.
I have implemented all AVX, SSE and Neon optimized similarity functions, …
> Manhattan distance

- lib/segment/src/fixtures/sparse_fixtures.rs
- lib/segment/src/index/sparse_index/sparse_vector_index.rs
- lib/segment/tests/integration/sparse_vector_index_search_tests.rs
- lib/sparse/src/index/inverted_index/inverted_index_mmap.rs
- lib/sparse/src/index/inverted_index/inverted_index_ram.rs
- lib/sparse/src/index/inverted_index/mod.rs
Sparse index persistence using rebuild RAM inverted index while loading. Mmap index is not touched. Added test for persistence.
> Sparse index persistence

- lib/collection/src/collection_manager/segments_searcher.rs
- lib/collection/src/shards/local_shard_operations.rs
> make indexed_only search threshold more lenient

- openapi/tests/openapi_integration/test_sparse_dense_batch_update.py
- openapi/tests/openapi_integration/test_sparse_vector_config_update.py
This PR adds an integration test for changing the sparse vector configuration.
> Test sparse vector configuration update

- docs/grpc/docs.md
- lib/api/src/grpc/proto/qdrant_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/common/stoppable_task.rs
- lib/collection/src/shards/local_shard.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/collection/src/update_handler.rs
- lib/common/common/src/lib.rs
- lib/common/common/src/panic.rs
- openapi/tests/openapi_integration/test_k8s_health.py
- src/actix/api/service_api.rs
- src/actix/mod.rs
- src/common/health.rs
- src/common/mod.rs
- src/consensus.rs
- src/main.rs
- src/tonic/mod.rs
> Extend `/readyz` with shards readiness check (#3053)

- lib/collection/src/collection_manager/segments_searcher.rs
- lib/segment/src/vector_storage/async_raw_scorer.rs
Remove one unnecessary TODO and a turn a panic into an error.
> Clean two sparse vectors todos

- lib/segment/benches/sparse_index_search.rs
The latest changes for opening the sparse inverted index broke the mmap benchmark.
```
Benchmarking sparse-vector-search-group/mmap-inverted-index: Warming up for 3.0000 sthread 'main' panicked at lib/segment/benches/sparse_index_search.rs:89:13:
assertion `left == right` failed
left: 0
right: 10
```
This because the index was built manually without generating the underlying sparse configuration file.
> Fix bench for mmap sparse search

- src/greeting.rs
> fix: display the real bind addr

- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
Looks like we had a bad merge.
> Fix dev build

- docs/redoc/master/openapi.json
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/types.rs
- lib/segment/src/types.rs
Minor improvements detected while regenerating clients.
> Minor API documentation fixes

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.7.x/openapi.json
- lib/api/Cargo.toml
> Bump version to 1.7.0

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
Bump Qdrant to version 1.7.1.
This includes an important fix for <https://github.com/qdrant/qdrant/issues/3193>.
> Bump version to v1.7.1

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
> Bump version to 1.7.2

- lib/collection/src/shards/replica_set/update.rs
> report shard error in the api response

- README.md
- Mention official Java client
- Update *features* section of the documentation.
> suggestions to update README

- Cargo.lock
- Cargo.toml
- src/actix/certificate_helpers.rs
Supersedes <https://github.com/qdrant/qdrant/pull/3244>.
Similar to the above dependabot PR, but with additional code changes due to the API being changed.
> Bump rustls-pemfile to 2.0.0

- docs/roadmap/README.md
- docs/roadmap/roadmap-2023.md
Suggestion for 2024 roadmap.
Most likely we will come up with some new unexpected stuff anyway, but general direction is this.
Please feel free to comment and suggest
> suggestions for 2024 roadmap

- README.md
This PR intends to add "Run On Replit" buttons to the README.
> docs: Replit runner buttons README.md

- lib/collection/src/collection_manager/segments_updater.rs
- lib/segment/src/data_types/vectors.rs
- openapi/tests/openapi_integration/test_optional_vectors.py
Fixes <https://github.com/qdrant/qdrant/issues/3376>.
This PR fixes an issue where multiple vector (not point) updates on the same point don't work if they are in the same batch. Instead, only the last operation for each point was applied.
For example, the following would drop the first change, and only apply the second change, because they are for the same point ID. Updating `b` and leaving `a` unchanged:
```
PUT /collections/{collection}}/points/vectors
{
"points": [
{
"id": 1,
"vector": {
"a": [0.8, 0.1, 0.3]
}
},
{
"id": 1,
"vector": {
"b": [0.2, 0.4, 0.3]
}
}
]
}
```
To fix this, all vector updates are now merged into a single operation per point. This merged from first to last, to ensure the last item in the batch has the highest priority.
I've also added a bunch of tests ensuring …
> Fix multiple vector updates on same point in batch not working

- lib/sparse/src/index/search_context.rs
This PR optimizes the sparse vector search by removing empty posting lists.
This is based on the insight that real life data sets are [very skewed](https://github.com/qdrant/qdrant/pull/3393) with a large amount of very small posting lists.
By tracking the exact moment when to remove those, we can shorten the length of the loops over `self.postings_iterators` which are very hot.
Using the [sparse-vector-benchmarks](https://github.com/qdrant/sparse-vectors-benchmark) with `python main.py --skip-creation false --dataset small --graph-y-limit 150`
```
DEV
Latency distribution:
50p: 54.86 millis
95p: 85.31 millis
99p: 100.23 millis
999p: 115.24 millis
max: 126.31 millis
PR
Latency distribution:
50p: 47.02 millis
95p: 73.8 millis
99p: 88.48 millis
999p: 105.0 millis
max: 117.82 millis
```
DEV …
> Optimize sparse search by deleting empty postings

- QUICK_START_GRPC.md
Updated the QUICK_START_GRPC document and added the new structure for the request as suggested.
> Updated QUICK_START_GRPC document

- docs/redoc/master/openapi.json
- lib/storage/src/content_manager/consensus_manager.rs
- lib/storage/src/types.rs
> Add latest_error_timestamp to message_send_failures

- .dockerignore
- .github/workflows/dev-docker-image-build.yml
- Dockerfile
- lib/api/build.rs
- lib/api/src/grpc/models.rs
Try to include git commit ID while building docker image if .git is present. Otherwise, show a warning.
> fix: Include git commit id while building docker image if possible

- .dockerignore
- .github/workflows/dev-docker-image-build.yml
- Dockerfile
- lib/api/build.rs
- lib/api/src/grpc/models.rs
> Revert "fix: Include git commit id while building docker image if possible"

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/build.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/proto/collections_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/types.rs
- openapi/openapi-collections.ytt.yaml
- openapi/tests/openapi_integration/test_collection_exists.py
- src/actix/api/collections_api.rs
- src/common/collections.rs
- src/schema_generator.rs
- src/tonic/api/collections_api.rs
- src/tonic/api_key.rs
- tests/openapi_consistency_check.sh
> API for checking collection exists

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
Bump Qdrant to version 1.7.4.
This is a small patch release including:
- https://github.com/qdrant/qdrant/pull/3318
- https://github.com/qdrant/qdrant/pull/3458
To prevent CI failures due to recent clippy changes this also includes:
- https://github.com/qdrant/qdrant/pull/3270
> Bump version to 1.7.4

- Dockerfile
and ignore recommended packages; delete cache from build step
Also, fix consistency with `AS` for alias
> Only install the main packages

- lib/api/build.rs
- lib/collection/src/collection_manager/segments_searcher.rs
- lib/common/common/src/validation.rs
> Fix lints clippy 1.76

- lib/collection/src/shards/local_shard.rs
- lib/segment/benches/sparse_index_build.rs
- lib/segment/benches/sparse_index_search.rs
- lib/segment/benches/vector_search.rs
- lib/segment/src/fixtures/sparse_fixtures.rs
- lib/segment/src/index/sparse_index/sparse_vector_index.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs
- lib/segment/src/vector_storage/memmap_vector_storage.rs
- lib/segment/src/vector_storage/simple_dense_vector_storage.rs
- lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
- lib/segment/src/vector_storage/tests/async_raw_scorer.rs
- lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs
- lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs
- lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs
- lib/segment/tests/integration/segment_tests.rs
- lib/segment/tests/integration/sparse_discover_test.rs
- lib/segment/tests/integration/sparse_vector_index_search_tests.rs
fixes #3140 
Interestingly rustc panics when running `cargo clippy -all --all-features` on dev and this branch (on master it doesn't). Is this only a thing on my machine?
> allow stopping segment loading

- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/types.rs
- openapi/tests/openapi_integration/test_payload_indexing.py
Related issue: https://github.com/qdrant/qdrant/issues/3529
All local tests passed.
I have added a deserializer for datetime, which is very flexible.
https://github.com/Okabe-Rintarou-0/qdrant/blob/3212f2d3345cb2eac9d71ca396b5707163d073a0/lib/segment/src/types.rs#L66-L101
/claim #3529
> Extend datetime formats in REST API (#3529)

- .codespellrc
- Cargo.lock
- lib/common/issues/Cargo.toml
- lib/common/issues/src/dashboard.rs
- lib/common/issues/src/issue.rs
- lib/common/issues/src/lib.rs
- lib/common/issues/src/problems/mod.rs
- lib/common/issues/src/problems/too_many_collections.rs
- lib/common/issues/src/problems/unindexed_field.rs
- lib/common/issues/src/solution.rs
Tracked by #3471.
Creates a new internal crate for submitting and solving issues related to possible improvements of qdrant usage.
This works in a logger-like fashion, in which you have a singleton for using it from anywhere in the code. All issues are compared only using their `code`.
Sample usage (from the module documentation):
```rust
use issues;
use issues::{Issue, Solution};
pub(crate) struct DummyIssue {
pub code: String,
}
impl DummyIssue {
pub fn new(code: impl Into<String>) -> Self {
Self { code: code.into() }
}
}
impl Issue for DummyIssue {
fn code(&self) -> String {
self.code.clone()
}
fn description(&self) -> String {
"".to_string()
}
fn solution(&self) -> Solution {
Solution::None
}
}
// Submit an issue
issues::submit(DummyIssue::new("issue1")); …
```
> Issues API: internal crate

- lib/collection/src/shards/local_shard/clock_map.rs
- lib/collection/src/shards/local_shard/shard_ops.rs
Some minor `ClockMap` improvements:
- simplify documentation and implementation
- remove accidentally committed debug logging
- restructure the code, so that we still accept all operations, but without modifying `ClockMap` itself
> Refactor `ClockMap`

- lib/collection/src/shards/local_shard/clock_map.rs
- lib/collection/src/shards/local_shard/mod.rs
- lib/collection/src/shards/local_shard/wal_delta.rs
- lib/collection/src/shards/queue_proxy_shard.rs
- lib/collection/src/shards/replica_set/shard_transfer.rs
- lib/collection/src/shards/shard.rs
- lib/collection/src/wal.rs
Depends on: <https://github.com/qdrant/qdrant/pull/3510>, <https://github.com/qdrant/qdrant/pull/3551>
Add a function to resolve a WAL delta from some recovery point.
It is based on what we described in our design document, but might need another pass to get all the fine details right.
This will be used in <https://github.com/qdrant/qdrant/pull/3509> to actually select a part of the WAL for the shard diff transfer.
> Resolve WAL delta for shard diff transfer

- lib/collection/src/shards/queue_proxy_shard.rs
Yes, our queue proxy was forwarding all successful requests 3 times. That is because we didn't break the retry loop on successful forwarding.
This PR fixes that. :man_facepalming: 
> Fix queue proxy always forwarding successful requests three times

- lib/collection/src/shards/local_shard/clock_map.rs
- lib/collection/src/shards/local_shard/wal_delta.rs
Before this PR, the recovery point lists the last seen clock ticks. After this PR, the recovery point lists the clock ticks right after the last seen ones.
In other words, the recovery point defines a lower bound which is now inclusive, rather than exclusive. It describes what clock ticks we want to have on recovery, not the clock ticks we already have.
We must do this so that we can extend the recovery point with `0` ticks for clocks the recovering node might not have seen yet. In this case, recovery should include operation 0 for that clock (making it inclusive). Before this change, the 0 operation would be skipped.
The WAL resolving logic always assumed the recovery point had an inclusive lower bound. Because of it, it's logic …
> Recovery point should list first unseen ticks rather than last seen

- lib/collection/src/shards/local_shard/clock_map.rs
Two small (mostly cosmetic) changes in `clock_map` module:
- Don't allocate in `impl fmt::Display for RecoveryPoint`
- Move stuff in `RecoveryPoint`'s `From` implementations
> Minor cleanup in `clock_map` module

- lib/segment/src/common/utils.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/types.rs
See rationale here: https://github.com/qdrant/qdrant/pull/3637/files/bdbfe88fc60dc5b41522bff2f387c9beebd6c257#diff-67789d4c34760731373bcb8f515d365b74879a36818aa92d638cb80cb929e7f3.
Additionally, this PR passes a test added in #3655.
> Drop PayloadContainer::get_value_opt

- lib/collection/src/wal_delta.rs
> Use WAL fixture in our basic WAL delta tests

- lib/api/src/grpc/proto/collections_internal_service.proto
- lib/api/src/grpc/qdrant.rs
> Revert changes to `collections_internal_service.proto` introduced in #3510

- lib/segment/src/json_path/mod.rs
- tests/openapi/openapi_integration/test_payload_operations.py
This PR switches the old `JsonPathString` with the new `JsonPathV2`.
> Switch to JsonPathV2

- lib/segment/src/types.rs
Right now, as we adhere to the RCF3999 standard, we only accept `+09:00`-like timezones (with colon), but if a timezone is in `+0900` format (without colon), it is just ignored. Here I am proposing to also accept this timezone format, as well as `+09` (without minutes).
This can introduce a little performance penalty during indexation and during search over unindexed datetime field, but I think it is more useful to have this extra flexibility. 
The way @joein and I noticed it was when the parsing of timezones in Python work in both scenarios, but for formatting, the same template would produce timezones without colon. In other words, both `+09:00` and `+0900` are accepted, but only `+0900` is produced by the `%z` specifier.
2. [x] Have you formatted …
> Datetimes: Accept timezones without colon separator

- lib/segment/src/types.rs
I moved too fast and was deserializing into `NaiveDateTime`, which caused all of these dates to be on UTC instead of the specified timezone. Sorry!
> Fixup for #3729: Deserialize into timezone-aware date

- lib/collection/src/shards/replica_set/shard_transfer.rs
- lib/collection/src/shards/transfer/wal_delta.rs
Fix the order of state switching in WAL delta transfer.
Before:
- Transfer all queue proxy items
- Transform queue proxy into forward proxy
- Switch shard from PartialSnapshot to Partial
After:
- Transfer all queue proxy items
- Switch shard from PartialSnapshot to Partial
- Transform queue proxy into forward proxy
Before, it was possible that the forward proxy forwarded a new operation just before switching to Partial state. The remote shard would still be in PartialSnapshot state, rejecting the operation. The sending node would see this as failure, marking the shard as dead (again).
This is the flakyness that appeared in WAL delta tests on CI. Sometimes this did happen, causing the test to fail.
With this change this cannot …
> Fix state switching order in WAL delta transfer: forward proxy vs partial state

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.8.x/openapi.json
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
Bumps the Qdrant version to 1.8.0.
Follow the pattern of <https://github.com/qdrant/qdrant/pull/3175>.
> Bump version to 1.8.0

- Cargo.lock
- Cargo.toml
- lib/rbac/Cargo.toml
- lib/rbac/src/jwt.rs
- lib/rbac/src/lib.rs
- pkg/appimage/qdrant.desktop
- Adds a new crate for keeping the RBAC-specific logic together.
- Includes the claims for expiration (`exp`) and write access (`w`), read access is always granted.
- Uses HMAC SHA-256 encryption.
- Validates expiration claim as part of decoding.
> RBAC: Initial implementation for decoding `Claims`

- docs/redoc/v1.8.x/openapi.json
> Set correct OpenAPI version for v1.8.x release

- lib/collection/src/shards/forward_proxy_shard.rs
Tracked in: <https://github.com/qdrant/qdrant/pull/3789>
Currently, `ForwardProxyShard::update` always returns *local* ("wrapped") shard update result to the caller, completely ignoring *remote* shard result.
This PR "merges" two results together, i.e.:
- we pick the *newest* `clock_tag` among the two results
- and if remote node *rejected* the operation, we propagate `ClockRejected` status
This fix is not critical for diff transfer and should be backward compatible with 1.8.0, so it should be safe to include in any future release (both 1.8.* patch, or 1.9.*).
Tracked in #3477. …
> Merge `wrapped_shard` and `remote_shard` update results in `ForwarProxyShard::update`

- tests/consensus_tests/test_peer_snapshot_bootstrap.py
- tests/consensus_tests/utils.py
https://github.com/qdrant/qdrant/issues/3821
> attempt to fix flacky test_peer_snapshot_bootstrap

- lib/segment/src/lib.rs
> Remove unused tests

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
> bump version to v1.8.2

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- lib/api/src/grpc/conversions.rs
- lib/collection/Cargo.toml
- lib/collection/src/operations/snapshot_ops.rs
- lib/common/issues/Cargo.toml
- lib/segment/Cargo.toml
- lib/segment/src/common/anonymize.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/storage/Cargo.toml
As per https://github.com/qdrant/qdrant/pull/3809#issuecomment-1991123674, this little refactor attempt PR intends to bump Chrono to latest.
P.S. I couldn't run all the tests. Ran into OOM issues.
> refactor: Update to Chrono 0.4.35

- lib/api/src/grpc/conversions.rs
- lib/api/src/rest/conversions.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/recommendations.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/common/operation_error.rs
- lib/segment/src/data_types/named_vectors.rs
- lib/segment/src/data_types/vectors.rs
- lib/segment/src/vector_storage/async_raw_scorer.rs
Introduce new multi vector types to support our ColBERT initiative.
> Introduce MultiDenseVector to models

- lib/segment/src/data_types/vectors.rs
Follow up on https://github.com/qdrant/qdrant/pull/3826#discussion_r1528639745
> Remove unused function internal VectorStruct::is_empty

- lib/collection/src/operations/point_ops.rs
- lib/segment/src/types.rs
> Better error message on inserting wrong-formatted point ID

- lib/segment/src/data_types/named_vectors.rs
Follow up on https://github.com/qdrant/qdrant/pull/3826
Mostly mechanical to enable later storage implementations.
> Add MultiDense vector to CowVector

- lib/collection/src/collection/snapshots.rs
- lib/collection/src/shards/shard_holder.rs
- lib/storage/src/content_manager/snapshots/mod.rs
- tests/openapi/openapi_integration/test_shard_snapshot.py
- tests/openapi/openapi_integration/test_snapshot.py
Extends <https://github.com/qdrant/qdrant/pull/3856>
Along with the full snapshot API, also test the collection and shard API for arbitrary path traversal problems.
> Extend shard snapshot security tests

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
A new patch version for Qdrant, most notably fixing a security vulnerability.
> Bump version to v1.8.3

- lib/segment/src/data_types/vectors.rs
- lib/segment/src/segment.rs
> Remove duplicate VectorRef ownership conversions

- lib/storage/src/content_manager/consensus_manager.rs
CI on dev is currently failing.
This compilation error slipped through somehow. Maybe due to a bad merge or a stacked PR.
In any case, this resolve the problem.
> Fix CI: fix compilation error due to incorrect PeerMetadata import

- lib/segment/src/data_types/named_vectors.rs
We have nice existing `From` implementations for those.
> Remove duplicated conversions in NamedVectors

- lib/segment/src/vector_storage/query_scorer/mod.rs
- lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
Implement Metric scorer for Colbert. It's required for raw scorer 
> colbert query scorers

- lib/storage/src/content_manager/claims.rs
- lib/storage/src/content_manager/snapshots/mod.rs
- lib/storage/src/content_manager/snapshots/recover.rs
- src/actix/api/snapshot_api.rs
- src/common/collections.rs
- src/common/snapshots.rs
- src/tonic/api/snapshots_api.rs
Tracked by #3777.
This PR adds RBAC claims checks for for snapshots API.
> RBAC support for snapshots API

- lib/segment/src/data_types/vectors.rs
- lib/segment/src/vector_storage/simple_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs
Additional tests for the multi dense vector simple storage leveraging the new raw scorer.
> Test MultiDense storage via raw scorer

- src/actix/api/cluster_api.rs
- src/actix/api/service_api.rs
- src/actix/helpers.rs
Tracked in #3777.
This PR adds claims checks for the remaining APIs. Namely, the following require manage rights:
- `GET    /cluster`
- `POST   /cluster/recover`
- `DELETE /cluster/peer/{peer_id}`
- `GET    /telemetry`
- `GET    /metrics`
- `POST   /locks`
- `GET    /locks`
- `GET    /stacktrace`
After this PR got merged, all of the HTTP and gRPC APIs should be protected, with the exception of `/healthz`, `/livez`, `/readyz`. I think we should keep these unprotected.
> RBAC support for remaining APIs

- config/config.yaml
- docs/redoc/master/openapi.json
- src/common/auth.rs
- src/common/telemetry_ops/app_telemetry.rs
- src/settings.rs
- tests/consensus_tests/test_jwt_validation.py
- Additionally adds JWT config to telemetry, so we could properly configure web-ui to only enable JWT page when JWT is available
> add config property to disable jwt by default

- lib/collection/src/shards/local_shard/clock_map.rs
- lib/collection/src/wal_delta.rs
> Minor code cleanup for #3882

- lib/collection/src/collection/snapshots.rs
- lib/collection/src/operations/types.rs
Make `Collection::create_snapshot` errors more descriptive in attempt to debug #3875.
> Add context to `Collection::create_snapshot` errors

- .github/workflows/dev-docker-image-build.yml
Also remove `Swatinem/rust-cache@v2` action. It's not being used here because the containers are built inside using Docker.
> feat: Remove existing buildx containers before building dev branch

- Cargo.toml
- src/main.rs
> keep jemalloc dependency only for builds on aarch64 and amd64 platforms, fixes #2474

- lib/collection/src/operations/conversions.rs
Fixing bug found with https://github.com/qdrant/qdrant-client/pull/567
> Fix gRPC discovery with sparse vectors

- lib/collection/src/update_handler.rs
Only report 'pending optimizations' status if we never triggered optimizers yet.
With the following test:
```bash
QDRANT_NUM_CPUS=8 cargo run
bfb -n 1000000 --indexing-threshold 10 --shards 2
```
it showed yellow and pending together before, while now it only shows yellow xor pending.
> Only report pending optimizations status if we never triggered optimizers yet

- lib/storage/src/rbac/mod.rs
- src/common/auth/jwt_parser.rs
> [RBAC] remove option to specify multiple collection names in one rule

- lib/collection/src/collection_manager/holders/proxy_segment.rs
change order of locking to prevent a situation where point is marked as removed before moved
> Fix lock ordering in proxy segment

- Cargo.lock
Supersedes: <https://github.com/qdrant/qdrant/pull/3979>
Instead of merging into master, this merges into dev.
> Bump h2 to 0.3.26

- lib/segment/Cargo.toml
- lib/segment/benches/multi_vector_search.rs
A new benchmark to validate the performance of the multivector search.
> Introduce multi vector search benchmark

- tests/openapi/requirements-freeze.txt
- tests/storage-compat/populate_db/requirements-freeze.txt
Supersedes <https://github.com/qdrant/qdrant/pull/4019>, <https://github.com/qdrant/qdrant/pull/4018>
> Bump idna to 3.7

- lib/collection/src/collection/point_ops.rs
- lib/collection/src/collection/shard_transfer.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/collection/src/shards/replica_set/update.rs
- lib/storage/src/content_manager/conversions.rs
- lib/storage/src/content_manager/errors.rs
- src/actix/helpers.rs
- tests/consensus_tests/test_shard_stream_transfer.py
- tests/consensus_tests/test_shard_wal_delta_transfer.py
This integration test highlights the problem with stream shard transfer. Not 100% of the times, but reproducible locally
> test of stream shard transfer consistency

- lib/segment/src/vector_storage/query_scorer/mod.rs
This PR optimizes the scoring function for colBERT multivector.
While running benchmarks I noticed that the `max_by` function took a significant amount of CPU time.
It seems it is not properly optimized.
I rewrote it in a manual fashion and got more or less the expected overhead back.
```
multi-vector-search-group/hnsw-multivec-search
time:   [547.90 µs 549.36 µs 550.95 µs]
change: [-37.207% -35.869% -34.653%] (p = 0.00 < 0.05)
Found 8 outliers among 100 measurements (8.00%)
6 (6.00%) high mild
2 (2.00%) high severe
```
> Optimize colBERT maxsim scoring

- src/common/collections.rs
- tests/consensus_tests/auth_tests/test_jwt_validation.py
- tests/consensus_tests/test_jwt_validation.py
Needs #3961 
Checks the collection with payload restriction access for both `r` and `rw` modes
Tests that check payload constraint filtering fail on `dev` but pass with #4006
> RBAC: [tests] Add payload constraint spec

- Cargo.toml
I made changes to the optimization option for release.
* using a single `codegen-unit`
> Applying the optimization options

- lib/collection/src/collection/snapshots.rs
- lib/collection/src/common/mod.rs
- lib/collection/src/common/validate_snapshot_archive.rs
- lib/collection/src/shards/shard_holder.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/common/validate_snapshot_archive.rs
- lib/segment/src/segment.rs
- src/snapshots.rs
add validation for snapshot archives for not containing any symlinks
> Fix snapshot tar symlinks validation

- docs/redoc/master/openapi.json
- lib/collection/src/collection/collection_ops.rs
- lib/collection/src/operations/types.rs
- lib/collection/tests/integration/collection_restore_test.rs
- tests/basic_api_test.sh
- tests/basic_grpc_test.sh
- tests/basic_sparse_test.sh
- tests/consensus_tests/test_init_collection_from.py
- tests/consensus_tests/utils.py
- tests/openapi/openapi_integration/test_basic_retrieve_api.py
- tests/openapi/openapi_integration/test_basic_retrieve_multivec_api.py
- tests/openapi/openapi_integration/test_delete_points.py
- tests/openapi/openapi_integration/test_vector_config.py
Remove approximate `vectors_count` field from CollectionInfo, as it is too confusing.
> remove usage of vectors_count

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/benches/batch_search_bench.rs
- lib/collection/src/collection_manager/fixtures.rs
- lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs
- lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
- lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/operations/vector_params_builder.rs
- lib/collection/src/shards/replica_set/update.rs
- lib/collection/src/tests/snapshot_test.rs
- lib/collection/src/tests/wal_recovery_test.rs
- lib/collection/tests/integration/common/mod.rs
- lib/collection/tests/integration/multi_vec_test.rs
- lib/collection/tests/integration/snapshot_recovery_test.rs
- lib/segment/src/data_types/named_vectors.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/types.rs
- lib/storage/tests/integration/alias_tests.rs
- src/consensus.rs
Implement API integration of byte storage
> Byte storage api support

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.9.x/openapi.json
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
Bumps the Qdrant version to 1.9.0.
Follow the pattern of <https://github.com/qdrant/qdrant/pull/3779>.
> Bump version to 1.9.0

- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/shards/local_shard/mod.rs
> When reading with a filter, go over non-appendable segments first

- src/consensus.rs
- tests/consensus_tests/test_shard_snapshot_transfer_cancel.py
This PR restructure consensus thread loop to be more efficient.
> Speedup consensus thread

- .github/workflows/dev-docker-image-build.yml
> feat: Build any branch using GH workflow

- lib/segment/src/index/field_index/geo_hash.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/types.rs
I am not a Rust programmer. I would appreciate community assistance in adding a unit test file! We can use the reproduction example in #4102
> Handle bounding box crossing the 180th meridian

- Cargo.toml
- lib/segment/Cargo.toml
- lib/segment/benches/range_filtering.rs
- lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
Tried to optimize the immutable numeric index but it does not improve things according to new benchmarks.
> Optimize NumericIndex value_range

- lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs
Might be related to: https://github.com/qdrant/qdrant/issues/4131
but there are no reproduction scenario yet
> Use safe reading of deleted flags

- lib/collection/src/shards/local_shard/mod.rs
- lib/segment/src/fixtures/payload_context_fixture.rs
- lib/segment/src/id_tracker/id_tracker_base.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
…oned points after WAL recovery
Fixes: https://github.com/qdrant/qdrant/issues/4154
> Clean-up unversioned points

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
> bump version to v1.9.1

- tests/openapi/openapi_integration/test_multi_vector.py
- tests/openapi/openapi_integration/test_multi_vector_uint8.py
Follow up on https://github.com/qdrant/qdrant/pull/4194
> Test Multivector storage mmap and uint8

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/grpc/validate.rs
- lib/collection/src/operations/cluster_ops.rs
- lib/collection/src/operations/conversions.rs
- src/tonic/api/points_common.rs
> make grpc service type enums unique for UpdateCollectionClusterSetupRequest and PointsUpdateOperation

- Cargo.lock
- docs/redoc/master/openapi.json
- lib/segment/Cargo.toml
- lib/segment/src/common/utils.rs
- lib/segment/src/types.rs
- tests/openapi/openapi_integration/test_basic_retrieve_api.py
> Simplify REST API nesting (#3323)

- lib/collection/src/shards/transfer/driver.rs
- lib/segment/src/index/field_index/full_text_index/posting_list.rs
- lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- src/common/auth/jwt_parser.rs
Fix minor lints reported by Rover.
> Minor cleanup from Rover's lints

- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/universal_query/planned_query.rs
- lib/collection/src/operations/universal_query/shard_query.rs
- lib/collection/src/shards/local_shard/query.rs
- Rename some internal structure
- Use enum instead of boolean value for fusion
> [universal-search] refactoring suggestions

- lib/segment/src/problems/unindexed_field.rs
Change messages for better readability
> Nitpick phrasing in `UnindexedField` messages

- Cargo.lock
- lib/api/Cargo.toml
- lib/common/dataset/Cargo.toml
- lib/common/issues/Cargo.toml
- lib/segment/Cargo.toml
- lib/sparse/Cargo.toml
A bit of of spring cleaning :broom:
> Cleanup unused dependencies

- config/config.yaml
- lib/collection/src/config.rs
- lib/segment/src/types.rs
- lib/storage/src/content_manager/toc/create_collection.rs
- lib/storage/src/types.rs
- lib/storage/tests/integration/alias_tests.rs
- src/settings.rs
Extends the configs parameters for some collection related defaults
> Add vectors and quantization options and defaults

- lib/collection/src/collection/search.rs
> dedup in shards suggestion: less intermediate allocation and kmerge

- .github/workflows/dev-docker-image-build.yml
> fix: Replace with space

- CODE_OF_CONDUCT.md
- lib/collection/src/tests/points_dedup.rs
I just merged #4303 which had unsuspecting conflicting changes. This fixes it
> Fix recent dev merge

- lib/collection/src/hash_ring.rs
> Prepare re-sharding

- docs/grpc/docs.md
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/rest/conversions.rs
- lib/collection/src/operations/universal_query/collection_query.rs
- lib/storage/src/rbac/ops_checks.rs
> universal-query: Converge API types into `CollectionQueryRequest`

- lib/collection/src/shards/local_shard/query.rs
Adds the missing implementation of rescoring with an OrderBy query
> universal-query: Rescore with order-by

- lib/collection/src/collection/mod.rs
- lib/collection/src/hash_ring.rs
- lib/collection/src/shards/shard_holder.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/toc/collection_meta_ops.rs
- src/common/collections.rs
Basically, subject. Further cleanup/improvement following #4346 and #4349. 
> Refactor and cleanup resharding consensus operations

- config/config.yaml
- lib/segment/src/types.rs
- lib/storage/src/content_manager/toc/collection_meta_ops.rs
- lib/storage/src/content_manager/toc/mod.rs
- lib/storage/src/dispatcher.rs
Adds `shard_number_per_node` option to the config
> Add config option shard_nr_per_node

- lib/collection/src/collection/mod.rs
Fixes a compilation error on dev due to a conflict from a cross merge. CI doesn't retrigger in this case, so we weren't aware of it.
Sorry!
> Fix compilation error on dev caused by cross merge

- lib/segment/tests/integration/fixtures/segment.rs
- lib/segment/tests/integration/segment_builder_test.rs
Test for https://github.com/qdrant/qdrant/pull/4396
> Test fix segment builder for sparse

- CONTRIBUTING.md
Updated documentation to have link for reporting bugs on GitHub. 
> doc: updated CONTRIBUTING.md with link for opening new issue on GitHub

- lib/api/src/rest/schema.rs
- lib/api/src/rest/validate.rs
Needs #4362
Implements `Validate` for REST-facing `QueryRequest`
> universal-query: validate REST query request

- tests/openapi/openapi_integration/helpers/collection_setup.py
- tests/openapi/openapi_integration/helpers/helpers.py
- tests/openapi/openapi_integration/helpers/settings.py
- tests/openapi/openapi_integration/test_payload_operations.py
- tests/openapi/openapi_integration/test_query.py
Adds basic comparison to current existing endpoints
> universal-query: Basic integration tests

- lib/collection/src/optimizers_builder.rs
Since we potentially use less CPUs for indexing, default max segment size should reflect that
> better default max segment size estimation

- lib/collection/src/collection/query.rs
- lib/storage/src/content_manager/toc/point_ops_internal.rs
I forgot to remove these TODOs before 😃
> universal-query: connect internal service query in ToC

- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection/query.rs
- lib/collection/src/shards/dummy_shard.rs
- lib/collection/src/shards/forward_proxy_shard.rs
- lib/collection/src/shards/local_shard/query.rs
- lib/collection/src/shards/local_shard/scroll.rs
- lib/collection/src/shards/local_shard/shard_ops.rs
- lib/collection/src/shards/proxy_shard.rs
- lib/collection/src/shards/queue_proxy_shard.rs
- lib/collection/src/shards/remote_shard.rs
- lib/collection/src/shards/replica_set/read_ops.rs
- lib/collection/src/shards/shard_trait.rs
- lib/collection/src/tests/shard_query.rs
- lib/storage/src/content_manager/toc/point_ops.rs
- lib/storage/src/content_manager/toc/point_ops_internal.rs
- src/actix/api/query_api.rs
- src/tonic/api/points_internal_api.rs
This PR add support for timeout in universal query API.
> universal-query: timeout support

- lib/segment/build.rs
Fix docker build after brocken PR https://github.com/qdrant/qdrant/pull/4464
> Fix docker arm f16 build

- tests/consensus_tests/test_points_query.py
Tests for the query API in a cluster setup to make sure the inter shards communication works properly.
> universal-query: cluster test for query API

- docs/grpc/docs.md
- lib/api/build.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/universal_query/collection_query.rs
- src/common/points.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- src/tonic/api/points_internal_api.rs
- tests/basic_query_grpc_test.sh
- tests/consensus_tests/auth_tests/test_jwt_access.py
- tests/integration-tests.sh
This PR adds a new gRPC endpoint for the query API.
> universal-query: gRPC query API

- docs/grpc/docs.md
- lib/api/build.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/universal_query/collection_query.rs
- src/common/points.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- tests/basic_query_grpc_test.sh
- tests/consensus_tests/auth_tests/test_jwt_access.py
Introduces gRPC API for the batch query API.
> universal-query: gRPC batch API

- lib/collection/src/operations/universal_query/collection_query.rs
- src/tonic/api/points_internal_api.rs
Tackling two `universal-query` TODOs for good measure.
> universal-query: Handle TODOs

- docs/redoc/master/openapi.json
- lib/api/src/rest/schema.rs
- lib/collection/src/operations/types.rs
> Fixing various API docs

- lib/api/src/rest/schema.rs
Reverts parts of #4394 before a patch release
> revert skip-serializing

- docs/redoc/master/openapi.json
- lib/api/src/rest/schema.rs
- lib/collection/src/operations/universal_query/collection_query.rs
- tests/openapi/openapi_integration/test_multi_vector.py
- tests/openapi/openapi_integration/test_multi_vector_unnamed.py
- tests/openapi/openapi_integration/test_query.py
Adding some missing validations to the query API input.
> universal-query: Add validations to query input

- lib/segment/src/index/hnsw_index/hnsw.rs
> Include HNSW config file in snapshots

- lib/collection/src/recommendations.rs
- tests/openapi/openapi_integration/test_recommendation_multivector.py
Fix the missing average multivector and integration test for it
> Avg multivector

- docs/grpc/docs.md
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
> Fix two documentation mistakes in our gRPC definitions

- lib/api/src/rest/schema.rs
> Revert "revert skip-serializing" [v1.10]

- src/actix/api/query_api.rs
> Add query_points_batch to actix

- lib/segment/src/telemetry.rs
> Remove unused struct VectorIndexesTelemetry

- Cargo.lock
- Cargo.toml
- lib/collection/Cargo.toml
- lib/common/memory/Cargo.toml
- lib/segment/Cargo.toml
- lib/sparse/Cargo.toml
- lib/storage/Cargo.toml
The `log` crate is a good candidate for promotion.
> Promote log dep to workspace

- Cargo.toml
- lib/api/Cargo.toml
- lib/collection/Cargo.toml
- lib/segment/Cargo.toml
- lib/sparse/Cargo.toml
- lib/storage/Cargo.toml
The `rand` crate is a good candidate for promotion.
> Promote Rand dependency to workspace

- tests/consensus_tests/test_resharding.py
Increase upsertion rate during resharding test.
> Do 10x more upsertions during resharding test

- lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs
- lib/segment/src/common/rocksdb_wrapper.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/index/field_index/binary_index.rs
- lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
- lib/segment/src/index/field_index/map_index/mutable_map_index.rs
- lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
- lib/segment/src/payload_storage/on_disk_payload_storage.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
This PR amends #4653. It implements an alternative to the approach described in https://github.com/qdrant/qdrant/pull/4653#discussion_r1673626968.
I suggest to review it per-commit.
> Introduce iterator for DatabaseColumnScheduledDeleteWrapper

- lib/collection/src/shards/local_shard/scroll.rs
The suggested algorithm:
- guarantees to finish in O(limit)  - assuming the selected points are unique
- subjectively easier to understand
> sample in O(limit)

- .codespellrc
- Cargo.lock
- Cargo.toml
- lib/collection/Cargo.toml
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/segment/Cargo.toml
- lib/segment/src/common/mmap_bitslice_buffered_update_wrapper.rs
- lib/segment/src/common/mmap_slice_buffered_update_wrapper.rs
- lib/segment/src/common/mod.rs
- lib/segment/src/fixtures/payload_context_fixture.rs
- lib/segment/src/id_tracker/id_tracker_base.rs
- lib/segment/src/id_tracker/immutable_id_tracker.rs
- lib/segment/src/id_tracker/mod.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
- lib/segment/src/segment.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/types.rs
> Persistent immutable id tracker

- lib/segment/src/id_tracker/immutable_id_tracker.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
I just merged #4619 which conflicted with #4403, this PR fixes it + fixes the case where a segment is empty, it would crash the Uniform distribution builder.
> fixup: Implement `iter_random` for `ImmutableIdTracker`

- lib/segment/src/id_tracker/immutable_id_tracker.rs
- lib/segment/src/id_tracker/in_memory_id_tracker.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
Depends on #4658 
- Prevent growing the versions vector needlessly
- Other minor improvements (thanks @ffuugoo for pointing them out!)
> Minor ImmutableIdTracker improvements

- lib/segment/src/index/field_index/numeric_index/mod.rs
> Fix build after merge numeric field index internal type

- Cargo.lock
- Cargo.toml
- lib/segment/Cargo.toml
- lib/segment/benches/in_memory_id_tracker.rs
- lib/segment/src/id_tracker/id_tracker_base.rs
- lib/segment/src/id_tracker/immutable_id_tracker.rs
- lib/segment/src/id_tracker/in_memory_id_tracker.rs
- lib/segment/src/id_tracker/mod.rs
- lib/segment/src/id_tracker/point_mappings.rs
- lib/segment/src/id_tracker/simple_id_tracker.rs
> In memory IdTracker

- docs/redoc/master/openapi.json
- lib/api/src/grpc/models.rs
- lib/collection/src/operations/snapshot_ops.rs
- lib/collection/src/operations/types.rs
- openapi/openapi.lib.yml
[Fern api demo docs link](https://qdrant-preview-a46b1a55-4c80-4748-ba62-2f844d5afa4f.docs.buildwithfern.com/master/api-reference)
> schemars example for CollectionsResponse, ScrollResult, SnapshotDescription, AliasDescription

- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/tests.rs
This PR changes the construction of the numeric index in tests. It's a preparation step to add mmap numeric index tests which have to be constructed using builder
> Use filed index builder in numeric index tests

- Cargo.toml
- docs/redoc/master/openapi.json
- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
Fixing weird errors this time.
> Fix Clippy 1.80

- tests/consensus_tests/test_resharding.py
Accidentally skipped the wrong test in #4699. 🤦‍♀️
2. [ ] ~~Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?~~
3. [ ] ~~Have you checked your code using `cargo clippy --all --all-features` command?~~
> Skip `test_resharding_abort` test

- Cargo.lock
- Cargo.toml
- docs/redoc/master/openapi.json
- lib/collection/Cargo.toml
- lib/collection/src/collection/mod.rs
- lib/collection/src/collection/resharding.rs
- lib/collection/src/hash_ring.rs
- lib/collection/src/operations/cluster_ops.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shards/resharding/driver.rs
- lib/collection/src/shards/resharding/mod.rs
- lib/collection/src/shards/resharding/stage_migrate_points.rs
- lib/collection/src/shards/resharding/stage_replicate.rs
- lib/collection/src/shards/shard_holder/mod.rs
- lib/collection/src/shards/shard_holder/resharding.rs
- lib/segment/Cargo.toml
- src/common/collections.rs
- tests/consensus_tests/test_resharding.py
Add support for resharding downwards, to reduce the number of shards.
This adds a `direction: up/down` parameter to specify whether to scale up or down. Scaling down has been integrated within the same resharding framework we had for just scaling up.
```json
// Example to scale up
POST /collections/benchmark/cluster
{
"start_resharding": {
"direction": "up",
"peer_id": 3359110923272967
}
}
// Example to scale down
POST /collections/benchmark/cluster
{
"start_resharding": {
"direction": "down"
}
}
```
We use the same resharding stages, but some function a bit different when scaling down. Migrating points does not use transfers, and replicating/propagating deletes are skipped when scaling down.
To migrate when scaling down, this PR currently uses a scroll+upsert loop. We …
> Implement resharding down

- lib/common/common/src/mmap_hashmap.rs
This PR adds iterator over keys
> Mmap hashmap iterate over keys

- lib/segment/src/common/mmap_bitslice_buffered_update_wrapper.rs
- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/field_index/mmap_point_to_values.rs
- lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/tests.rs
> Mmap numeric index

- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/operations/types.rs
- lib/segment/src/common/operation_error.rs
- lib/segment/src/data_types/facets.rs
- lib/segment/src/data_types/mod.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/map_index/immutable_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/map_index/mutable_map_index.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/segment.rs
- lib/segment/tests/integration/payload_index_test.rs
Adds implementation of internals for getting counts of each value in a map index.
Currently enabled for:
- Keyword index
> Facets in segment

- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/segments_updater.rs
Prevents blocking segments too long when deleting by filter.
> Non blocking filtered deletion

- lib/collection/src/collection_manager/segments_updater.rs
> Non blocking vector operations

- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/shards/local_shard/facet.rs
- lib/collection/src/shards/local_shard/mod.rs
- lib/segment/src/data_types/facets.rs
Aggregates faceting from multiple segments inside local shard
> Facets in local shard

- docs/grpc/docs.md
- lib/api/build.rs
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/shards/dummy_shard.rs
- lib/collection/src/shards/forward_proxy_shard.rs
- lib/collection/src/shards/local_shard/facet.rs
- lib/collection/src/shards/local_shard/shard_ops.rs
- lib/collection/src/shards/proxy_shard.rs
- lib/collection/src/shards/queue_proxy_shard.rs
- lib/collection/src/shards/remote_shard.rs
- lib/collection/src/shards/shard_trait.rs
- lib/segment/src/data_types/facets.rs
- src/tonic/api/points_internal_api.rs
Needs #4785 
Adds `facet` to `ShardOperations` trait, and to the internal grpc service
> Facets in internal service

- lib/common/common/src/mmap_hashmap.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/segment_constructor/segment_builder.rs
Mmap map index with it's builder
> Mmap map index

- lib/api/src/grpc/conversions.rs
- lib/collection/benches/hash_ring_bench.rs
- lib/collection/src/collection/point_ops.rs
- lib/collection/src/hash_ring.rs
- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/payload_ops.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/src/operations/vector_ops.rs
- lib/collection/src/shards/forward_proxy_shard.rs
- lib/collection/src/shards/replica_set/shard_transfer.rs
- lib/collection/src/shards/shard_holder/mod.rs
- lib/collection/src/shards/shard_holder/resharding.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/src/index/query_optimization/condition_converter.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/problems/unindexed_field.rs
- lib/segment/src/types.rs
- Remove mentions of re-sharding from segment
- rename hash ring structures to avoid generic names
- Remove PatrialEq from custom checking condition
> Refactor resharding filter

- lib/segment/src/index/field_index/map_index/mod.rs
> Fix bug in payload mmap index

- lib/segment/src/index/field_index/map_index/mod.rs
The same PR as #4814 by @JojiiOfficial, but rebased onto `dev` branch rather than into an integration branch.
> Fix mmap payload index building (rebase)

- lib/segment/src/index/field_index/binary_index.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/index_selector.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/struct_payload_index.rs
This PR integrates map and numeric mmap indices.
> Integrate map/numeric mmap indices

- docs/DEVELOPMENT.md
Adding missing instructions when adding new APIs.
> Add missing integration steps to new API doc

- lib/collection/src/shards/replica_set/read_ops.rs
- lib/collection/src/shards/resolve.rs
Implements facets up to the `ShardReplicaSet`, notably implements the resolving of replica results facet results
> Facets in ShardReplicaSet

- lib/segment/src/index/struct_payload_index.rs
- lib/segment/tests/integration/main.rs
- lib/segment/tests/integration/segment_on_disk_snapshot.rs
Add mmap field indices files to snapshot and add integration test with snapshottings of all mmap-components.
> fix mmap field index snapshot

- docs/grpc/docs.md
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
> docs: Use // for proto comments

- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
> fix grpc enumeration

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.11.x/openapi.json
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
Release Qdrant 1.11.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4585> and <https://github.com/qdrant/qdrant/pull/4083>.
> Bump version to 1.11.0

- Cargo.lock
- Cargo.toml
- lib/common/io/Cargo.toml
- lib/common/io/src/file_operations.rs
- lib/common/memory/src/madvise.rs
- lib/common/memory/src/mmap_ops.rs
- lib/common/memory/src/mmap_type.rs
- lib/segment/src/id_tracker/immutable_id_tracker.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/mmap_point_to_values.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/vector_storage/chunked_mmap_vectors.rs
- lib/segment/src/vector_storage/chunked_utils.rs
- lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
- lib/segment/src/vector_storage/dense/dynamic_mmap_flags.rs
- lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs
- lib/segment/src/vector_storage/in_ram_persisted_vectors.rs
- lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
- lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs
- lib/sparse/src/index/inverted_index/inverted_index_mmap.rs
- lib/sparse/src/index/loaders.rs
> InRamChunkedMmap: optimize using madvise

- lib/collection/src/operations/cluster_ops.rs
- src/common/collections.rs
Required for external resharding driver.
> Expose `FinishResharding` operation in `update_collection_cluster` HTTP API

- lib/common/memory/src/chunked_utils.rs
- lib/common/memory/src/lib.rs
- lib/common/memory/src/mmap_type.rs
- lib/segment/src/vector_storage/chunked_mmap_vectors.rs
- lib/segment/src/vector_storage/chunked_utils.rs
- lib/segment/src/vector_storage/mod.rs
Another mmap convenience refactoring, needed for 
https://github.com/qdrant/qdrant/pull/4885
> Refactor chunked mmaps

- lib/collection/src/operations/cluster_ops.rs
- src/common/collections.rs
Required for external resharding driver.
> Add `FinishMigratingPoints` operation to `update_collection_cluster` HTTP API

- Cargo.lock
- Cargo.toml
Performing update manually due to breaking changes.
> bump Tower 0.5.0

- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/segments_updater.rs
- lib/segment/src/types.rs
> Storage improvement

- lib/collection/src/operations/snapshot_storage_ops.rs
Fixes bug https://github.com/qdrant/qdrant/issues/4908
> Fix `MAX_UPLOAD_SIZE`

- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/rest/conversions.rs
- lib/api/src/rest/schema.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/shards/local_shard/facet.rs
- lib/collection/src/shards/local_shard/shard_ops.rs
- lib/collection/src/shards/remote_shard.rs
- lib/segment/src/data_types/facets.rs
- lib/segment/src/entry/entry_point.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/segment.rs
- lib/segment/tests/integration/payload_index_test.rs
- src/tonic/api/points_internal_api.rs
Needs #4848 
Adds faceting in exact mode to be able to debug and make comparisons against the ground truth.
This is not expected to be fast, but is expected to be correct.
> Exact facet mode

- src/actix/helpers.rs
Fixes https://github.com/qdrant/qdrant/issues/4925
> log errors when wait=false

- tests/storage-compat/populate_db.py
> mmap field indices storage compat

- docs/grpc/docs.md
- lib/api/build.rs
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/qdrant.rs
- src/common/metrics.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- tests/basic_grpc_test.sh
- tests/consensus_tests/auth_tests/test_jwt_access.py
Adds grpc endpoint with:
- request validation
- implementation of points service
- jwt access test
- basic grpc test
- conversion to `FacetParams`
> Add grpc endpoint for Facet

- docs/redoc/master/openapi.json
- lib/api/src/rest/conversions.rs
- lib/api/src/rest/schema.rs
- lib/api/src/rest/validate.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/src/operations/universal_query/collection_query.rs
> Data structures for inference 

- docs/redoc/master/openapi.json
- src/common/metrics.rs
- src/common/telemetry_ops/cluster_telemetry.rs
> include peers list into telemetry

- lib/api/src/grpc/conversions.rs
- lib/collection/src/grouping/group_by.rs
- lib/collection/src/operations/universal_query/planned_query.rs
- lib/segment/src/data_types/facets.rs
- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/query_optimization/condition_converter.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/problems/unindexed_field.rs
- lib/segment/src/types.rs
- lib/segment/tests/integration/payload_index_test.rs
- lib/storage/src/rbac/mod.rs
- src/common/auth/jwt_parser.rs
- Implement MatchAny and Except
> Implement better handling of UUID index

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
Changelog
```
* https://github.com/qdrant/qdrant/pull/4855 - allow to modify data before writing on disk for copy-on-write operations
* https://github.com/qdrant/qdrant/pull/4941 - Non-blocking payload index building
* https://github.com/qdrant/qdrant/pull/4947 - include peers list into telemetry
* https://github.com/qdrant/qdrant/pull/4961 - Support for MatchAny and Except conditions for UUID index
* https://github.com/qdrant/qdrant/pull/4952 - Fix point deletions on mmap segment optimization.
* https://github.com/qdrant/qdrant/pull/4909 - Fix Max Upload Size for s3 snapshot storage
* https://github.com/qdrant/qdrant/pull/4929 - Fix configuration of bool and geo index params with explicit schema
* https://github.com/qdrant/qdrant/pull/4953 - Proper handle of UUID index in issue reporting …
```
> bump version to v1.11.1

- tests/openapi/test_payload_indexing.py
- tests/openapi/test_query_full.py
- tests/openapi/test_query_indexes.py
* Parameterize existing tests with different filters 
* Also add tests for query batches with and without filters.
> Add tests on uuid payload index queries with filters

- src/common/telemetry_reporting.rs
Creating a Reqwest client is a rather expensive operation as it involves setting up a connection pool, configuring DNS resolver and setting up TLS things.
This PR proposes to create a single client for the telemetry reporter which is reused enabling to leverage connection pooling if possible.
Even if our reporting interval is high, it does not mean we should be wasteful with resources :earth_americas:
> Create Telemetry client only once

- lib/collection/src/shards/shard_holder/mod.rs
We don't include the target shard while resharding in shard selection. We should only do this when resharding up. While resharding down, the target shard already has all relevant points from the start.
> Only omit new shard from shard selection when resharding up

- lib/segment/src/index/field_index/field_index_base.rs
> prefer explicit function definitions instead of macros

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/build.rs
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/grpc/validate.rs
- lib/api/src/rest/schema.rs
- lib/collection/src/collection/distance_matrix.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- tests/consensus_tests/auth_tests/test_jwt_access.py
context: https://github.com/qdrant/qdrant/milestone/11
This PR adds gRPC endpoints to the new distance matrix API
> gRPC API for Distance Matrix

- lib/collection/src/operations/verification/count.rs
- lib/collection/src/operations/verification/discovery.rs
- lib/collection/src/operations/verification/facet.rs
- lib/collection/src/operations/verification/local_shard.rs
- lib/collection/src/operations/verification/mod.rs
- lib/collection/src/operations/verification/recommend.rs
- lib/collection/src/operations/verification/search.rs
- lib/collection/src/operations/verification/update.rs
- src/actix/api/count_api.rs
- src/actix/api/discovery_api.rs
- src/actix/api/facet_api.rs
- src/actix/api/local_shard_api.rs
- src/actix/api/query_api.rs
- src/actix/api/recommend_api.rs
- src/actix/api/retrieve_api.rs
- src/actix/api/search_api.rs
- src/actix/api/update_api.rs
- src/common/points.rs
Depends on #4935
Implements strict mode checking for most REST requests.
> [Strict-mode] Request verification implementation

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/rest/schema.rs
- openapi/openapi-main.ytt.yaml
API documentation improvements which surfaced during the implementation of the local mode.
> Distance matrix docs improvements

- lib/collection/src/collection/mod.rs
- lib/collection/src/collection_manager/mod.rs
- lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs
- lib/segment/src/data_types/query_context.rs
- lib/segment/src/index/field_index/histogram.rs
- lib/segment/src/index/field_index/mmap_point_to_values.rs
- lib/segment/src/index/field_index/tests/histogram_test_utils.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/utils/mem.rs
- lib/segment/tests/integration/fixtures/segment.rs
Found unnecessary clippy allow statements that we can get rid of.
> Remove unecessary clippy allow deadcode

- lib/collection/src/hash_ring.rs
- lib/collection/src/shards/resharding/driver.rs
- lib/collection/src/shards/shard_holder/mod.rs
- lib/collection/src/shards/shard_holder/resharding.rs
This PR fixes a few bugs in `hash_ring` module:
- make `HashRing::add`/`HashRingRouter::add` idempotent
- `hashring::HashRing::add` is not idempotent
- adding same node multiple times adds multiple instances of the node to the inner state
- and each call to `remove` only removes a single instance of the node
- so, to ensure `HashRing::add` is idempotent, we add a `HashSet` into `HashRing`, to explicitly track nodes added to the hashring
- correctly switch hashring into `Resharding` mode
- before, when switching into `Resharding` mode, we only ensured new node is added to/removed from `new` hashring
- however, when recovering `Resharding` hashring state from disk, we
- initialize hashring in `Single` mode
- add *all* shards (including *resharding target shard*) to the hashring
- switch …
> Fix bugs in and refactor `hash_ring` module

- lib/common/common/benches/mmap_hashmap.rs
- lib/common/common/src/mmap_hashmap.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/inverted_index_ops.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
Make MmapHashMap work with different datatypes
> make mmap hashmap value param generic

- docs/redoc/master/openapi.json
- src/common/telemetry_ops/app_telemetry.rs
- src/settings.rs
> custom key to hide jwt dashboard

- lib/common/common/benches/mmap_hashmap.rs
- lib/common/common/src/mmap_hashmap.rs
- lib/common/memory/src/mmap_type.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_chunks_reader.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_common.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_iterator.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_list.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_visitor.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/mod.rs
- lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/inverted_index_ops.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/postings_iterator.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs
Continue working on mmap text index
> initial structures for reading mmap text index

- .github/workflows/rust.yml
- lib/collection/src/collection/mod.rs
- lib/collection/src/collection/point_ops.rs
- lib/collection/src/operations/mod.rs
- lib/collection/src/operations/payload_ops.rs
- lib/collection/src/operations/point_ops.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/operations/vector_ops.rs
- lib/collection/src/shards/replica_set/update.rs
- lib/collection/src/shards/resharding/stage_migrate_points.rs
- lib/collection/src/shards/resharding/stage_propagate_deletes.rs
- lib/collection/src/shards/shard_holder/resharding.rs
- src/main.rs
This is _yet another_ alternative to filtering operations on read/write during resharding. The (main) goal is the same as with filtering: prevent any "stale" data to show up in read request results during `CommitReadHashRing`/`CommitWriteHashRing` transition.
This PR reuses a lot of #4867 code, but this time it's not used to filter-out point IDs from update operations, but to "split" update operations into "update all points"/"update existing points" operations (conceptually similar to `split_by_shard`). These split operations are then applied to the replica set (mostly) as usual. The only difference is that for "update existing points" operations, we simply ignore any "No point with id found" errors.
There is one moderate caveat with this PR: if we want to apply "upsert" operation in …
> Split operations into `update_all`/`update_existing` during resharding

- lib/common/common/src/tar_ext.rs
- lib/segment/src/segment/entry.rs
- lib/storage/src/content_manager/snapshots/mod.rs
ToDo: Revert this PR after releasing 1.11.4
> disable sparse tar arcive creation for backward compatibility

- lib/collection/src/operations/snapshot_storage_ops.rs
- lib/common/common/src/cpu.rs
- tests/shard-snapshot-api.sh
> fix: OOM when uploading a large snapshot to S3

- lib/common/memory/src/mmap_type.rs
Related to: https://github.com/qdrant/qdrant/issues/5084
This PR fixes reading of the "corrupted" files, but doesn't prevent "corruption". 
So we assume that corrupted files are just declared normal.
(reason for extension of the file size with zeros is still unclear)
> mmap_to_type_unbounded -> mmap_prefix_to_type_unbounded

- lib/segment/src/segment_constructor/segment_builder.rs
This uses `TempDir` and comes with its caveats, e.g. the temporary segment directory will not be deleted if the process exits (see https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#resource-leaking). This should not be a problem in practice, as all temporary segments get deleted when the shard is loaded (see PR #2319).
To reproduce the issue I've created a collection with a sample dataset and repeatedly changed the HNSW configuration:
```
curl -X PATCH "$qdrant_url/collections/test" \
-d '{"hnsw_config":{"m": 24}}'
curl -X PATCH "$qdrant_url/collections/test" \
-d '{"hnsw_config":{"m": 32}}'
curl -X PATCH "$qdrant_url/collections/test" \
-d '{"hnsw_config":{"m": 8}}'
```
Before applying this fix, this results in segment directories in `storage/collections/test/0/temp_segments` …
> Clean temporary segments if optimization is cancelled

- Cargo.lock
- Cargo.toml
- lib/quantization/Cargo.toml
- lib/quantization/benches/binary.rs
- lib/quantization/benches/encode.rs
- lib/quantization/benches/pq.rs
- lib/quantization/build.rs
- lib/quantization/cpp/avx2.c
- lib/quantization/cpp/export_macro.h
- lib/quantization/cpp/neon.c
- lib/quantization/cpp/sse.c
- lib/quantization/src/encoded_storage.rs
- lib/quantization/src/encoded_vectors.rs
- lib/quantization/src/encoded_vectors_binary.rs
- lib/quantization/src/encoded_vectors_pq.rs
- lib/quantization/src/encoded_vectors_u8.rs
- lib/quantization/src/kmeans.rs
- lib/quantization/src/lib.rs
- lib/quantization/src/quantile.rs
- lib/quantization/src/utils.rs
- lib/quantization/tests/empty_storage.rs
- lib/quantization/tests/metrics.rs
- lib/quantization/tests/stop_condition.rs
- lib/quantization/tests/test_avx2.rs
- lib/quantization/tests/test_binary.rs
- lib/quantization/tests/test_neon.rs
- lib/quantization/tests/test_pq.rs
- lib/quantization/tests/test_simple.rs
- lib/quantization/tests/test_sse.rs
- lib/segment/Cargo.toml
Copy-paste quantization repo into qdrant. Includes tests and benches.
Sourced from: <https://github.com/qdrant/quantization/commit/0caf67d96f022a792bda2e41fa878ba1e113113f>
> Move quantization repo

- lib/collection/src/collection/mod.rs
- lib/collection/src/shards/dummy_shard.rs
- lib/collection/src/shards/forward_proxy_shard.rs
- lib/collection/src/shards/local_shard/mod.rs
- lib/collection/src/shards/proxy_shard.rs
- lib/collection/src/shards/queue_proxy_shard.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/collection/src/shards/shard.rs
- lib/collection/src/shards/shard_holder/mod.rs
- lib/storage/src/content_manager/snapshots/recover.rs
> Trigger optimizers when uploading snapshots

- lib/collection/src/operations/verification/discovery.rs
- lib/collection/src/operations/verification/facet.rs
- lib/collection/src/operations/verification/matrix.rs
- lib/collection/src/operations/verification/query.rs
- lib/collection/src/operations/verification/recommend.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- src/tonic/api/points_internal_api.rs
- src/tonic/mod.rs
- src/tonic/verification.rs
> [Strict mode] GRPC verification

- config/config.yaml
- docs/grpc/docs.md
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/collection/collection_ops.rs
- lib/collection/src/config.rs
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/operations/verification/discovery.rs
- lib/collection/src/operations/verification/mod.rs
- lib/collection/src/operations/verification/query.rs
- lib/collection/src/operations/verification/search.rs
- lib/segment/src/types.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/toc/create_collection.rs
- src/common/points.rs
- src/migrations/single_to_cluster.rs
Depends on #5003
Since we need the strict mode config struct to be in `/lib/segment` but also need a struct that derives `Merge`, I decided to create two structs for strict mode: StrictModeDiff and StrictMode.
> [Strict mode] default config

- lib/collection/src/operations/verification/mod.rs
> [Strict mode] Unit tests

- Cargo.lock
- Cargo.toml
- docs/grpc/docs.md
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/Cargo.toml
- lib/collection/src/operations/config_diff.rs
- lib/collection/src/operations/conversions.rs
- lib/segment/Cargo.toml
- lib/segment/src/types.rs
- lib/storage/src/content_manager/collection_meta_ops.rs
- lib/storage/src/content_manager/conversions.rs
- src/migrations/single_to_cluster.rs
Depends on #5124 
Merges `StrictModeConfig` and `StrictModeConfigDiff` into a single struct, as they have the same fields.
> [Strict mode] Merge StrictMode config types

- lib/collection/src/shards/shard_holder/mod.rs
While we're removing a shard, the process may be killed in the middle. Before this PR it was possible keep only part of the shard data on disk, causing an error on load.
This ensures we remove the shard configuration file first to prevent this from happening. Even if other files are left behind, we won't try to load them. If we later create the shard again, the directory is recreated.
> When removing a shard, remove config first to prevent leaving corrupt state

- lib/common/common/src/tar_ext.rs
- lib/storage/src/content_manager/snapshots/mod.rs
Upgrade of https://github.com/qdrant/qdrant/pull/5082
> enable sparse snapshots

- lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
- lib/segment/src/index/field_index/full_text_index/tests/mod.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/geo_hash.rs
- lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
- lib/segment/src/index/field_index/index_selector.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/tests.rs
Memory map geo index.
This PR contains list of changes:
1. `MutableGeoIndex` was separated into `InMemoryGeoIndex`, struct without DB, and `MutableGeoIndex` with aggregated `DynamicGeoIndex`. The same trick has `MapIndex` and it's important to create builder for mmap index, where we need constructed collections without DB.
2. `MmapGeoIndex` structure with mmaped collections
3. `MmapGeoIndex` as enum variant for `GeoIndex`. Integration, mmap builder and tests
4. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
5. [x] Have you checked your code using `cargo clippy --all --all-features` command?
> Mmap geo index

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/segment/src/data_types/index.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/index_selector.rs
- lib/segment/src/types.rs
REST/grpc api and integration of mmap geo index
> mmap geo index api

- lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs
What the title says :)
`shedule` -> `schedule`
> Fix typo in RocksDB wrapper type

- lib/collection/src/collection_manager/holders/proxy_segment.rs
Looking at a profile of a heavy update workload, I can see that `ProxySegment::available_vectors_size_in_bytes` is rather hot.
This PR changes things in order to make sure the function is doing less work:
- take less read locks
- create less Arc clones
- renaming and misc.
> Refactor available_vectors_size_in_bytes

- tests/openapi/test_strictmode.py
Adds integration tests for strict mode
> Strict mode integration tests

- lib/collection/src/shards/local_shard/scroll.rs
Remove an unnecessary clone. Can be beneficial on large point records.
> Remove unnecessary clone when reordering records

- lib/collection/src/common/snapshots_manager.rs
- lib/collection/src/lookup/mod.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/wal.rs
- lib/segment/src/index/field_index/mmap_point_to_values.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/segment/entry.rs
- lib/storage/src/content_manager/consensus/consensus_wal.rs
- lib/storage/src/content_manager/toc/create_collection.rs
- src/actix/web_ui.rs
- src/tonic/api/collections_api.rs
- src/tonic/api/points_common.rs
This PR cleans up call sites that were creating error values eagerly to be dismissed right away.
I tried to find the places which were allocating and left the very cheap one untouched.
> Do not create errors eagerly

- lib/common/common/src/counter/counter_cell.rs
- lib/segment/src/data_types/query_context.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/sparse_index/sparse_vector_index.rs
- lib/segment/src/vector_storage/async_raw_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/custom_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/mod.rs
- lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/sparse_custom_query_scorer.rs
- lib/segment/src/vector_storage/raw_scorer.rs
- lib/segment/tests/integration/sparse_discover_test.rs
Depends on #5239 
Adds measurement for multi-vector search and some sparse vector search implementations.
> Add CPU measurement for multivectors

- Cargo.toml
- lib/collection/Cargo.toml
- lib/common/common/Cargo.toml
- lib/segment/Cargo.toml
- lib/sparse/Cargo.toml
Applying the usual reduction of version repetition.
> Promote ordered-float to workspace

- config/development.yaml
- src/common/inference/config.rs
- src/common/inference/service.rs
- src/main.rs
Add `billing_id` for inference service.
> Inference Service, billing-id

- Cargo.toml
- lib/collection/Cargo.toml
- lib/common/common/Cargo.toml
- lib/quantization/Cargo.toml
- lib/segment/Cargo.toml
- lib/sparse/Cargo.toml
> Promote criterion to workspace

- docs/redoc/master/openapi.json
- lib/collection/src/shards/replica_set/mod.rs
- lib/collection/src/shards/transfer/mod.rs
- lib/collection/src/shards/transfer/snapshot.rs
- lib/collection/src/shards/transfer/wal_delta.rs
- lib/storage/src/content_manager/toc/transfer.rs
Minor improvements on <https://github.com/qdrant/qdrant/pull/5271>.
This is mostly refactoring which I didn't have the time for yesterday. It contains no significant logic changes.
> Minor improvements around the WAL delta fix

- lib/segment/src/common/rocksdb_wrapper.rs
Do not reallocate a native RocksDB `write_options` object on every `put` call.
According to a benchmark, it takes up to 32% of the memory allocation during payload + index upsert.
> [perf] Do not reallocate RocksDB write_options

- lib/segment/src/common/rocksdb_wrapper.rs
Similar to https://github.com/qdrant/qdrant/pull/5301
Less prominent but it does show up in memory profiles weirdly.
> Allocate less rocksdb options

- lib/collection/src/collection/distance_matrix.rs
In order to fully leverage the batch search, all search requests should use the same filter.
In this PR the distance matrix API is changed to not create a dedicated specialized filter for scoring each sample.
A single filter using all point ids is reused with additional oversampling to account for scoring against itself.
At the end a postprocessing step is required to filter the results.
> Leverage shared filter in distance matrix API

- lib/collection/src/collection/distance_matrix.rs
- lib/segment/src/types.rs
Replaces the iterative process to sample points with a given vector by a single request using the newly introduced `HasVector` condition.
> Distance matrix leverages HasVector condition

- config/config.yaml
- docs/redoc/master/openapi.json
- lib/api/src/grpc/models.rs
- lib/common/common/src/counter/counter_cell.rs
- lib/common/common/src/counter/hardware_accumulator.rs
- lib/common/common/src/counter/hardware_counter.rs
- lib/common/common/src/counter/mod.rs
- openapi/openapi.lib.yml
- src/actix/api/collections_api.rs
- src/actix/api/discovery_api.rs
- src/actix/api/facet_api.rs
- src/actix/api/query_api.rs
- src/actix/api/recommend_api.rs
- src/actix/api/search_api.rs
- src/actix/api/service_api.rs
- src/actix/api/shards_api.rs
- src/actix/api/update_api.rs
- src/actix/helpers.rs
- src/actix/mod.rs
- src/schema_generator.rs
- src/settings.rs
Depends on #5288
Adds information about hardware usage to the API and a config to toggle this.
> Add hardware measurements in API

- lib/collection/src/collection/collection_ops.rs
- lib/collection/src/collection/point_ops.rs
- lib/collection/src/grouping/builder.rs
- lib/collection/src/shards/dummy_shard.rs
- lib/collection/src/shards/forward_proxy_shard.rs
- lib/collection/src/shards/local_shard/shard_ops.rs
- lib/collection/src/shards/proxy_shard.rs
- lib/collection/src/shards/queue_proxy_shard.rs
- lib/collection/src/shards/remote_shard.rs
- lib/collection/src/shards/replica_set/read_ops.rs
- lib/collection/src/shards/shard_trait.rs
- lib/collection/src/shards/transfer/resharding_stream_records.rs
- lib/collection/src/shards/transfer/stream_records.rs
- lib/collection/tests/integration/collection_test.rs
- lib/collection/tests/integration/grouping_test.rs
- lib/storage/src/content_manager/toc/point_ops.rs
- src/actix/api/count_api.rs
- src/actix/api/local_shard_api.rs
- src/actix/api/query_api.rs
- src/actix/api/recommend_api.rs
- src/actix/api/search_api.rs
- src/common/points.rs
- src/tonic/api/points_common.rs
Depends on #5308
Adds hardware information for requests to more endpoints in the REST API
> Hardware utilization information in endpoints

- lib/sparse/src/index/search_context.rs
> batch increment of counter

- lib/collection/src/collection_manager/collection_updater.rs
- lib/collection/src/shards/forward_proxy_shard.rs
- lib/collection/src/update_handler.rs
Tiny improvements I made on top of <https://github.com/qdrant/qdrant/pull/5298>.
To prevent cluttering the main PR - making the problem harder to understand - I moved them to a separate PR.
These changes are not significant and don't include any logic changes.
> Tiny refactoring during data race investigation

- lib/segment/src/index/visited_pool.rs
The PR #5336 introduced a in `VisitedListHandle` bug which is reproducible after two `u8` wraparounds.
This PR fixes it by reseting `visit_counters` every `255` iterations, not every `256`.
> Fixups for VistedPool

- docs/grpc/docs.md
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_common.rs
- src/tonic/api/points_internal_api.rs
- src/tonic/mod.rs
Depends on #5328
Adds basic hardware utilization information for most GRPC endpoints
> Add hardware usage to grpc API

- Cargo.lock
- lib/api/src/grpc/conversions.rs
- lib/collection/src/shards/remote_shard.rs
- lib/common/common/src/counter/hardware_accumulator.rs
- lib/common/common/src/counter/hardware_counter.rs
- lib/quantization/Cargo.toml
- lib/quantization/benches/binary.rs
- lib/quantization/benches/pq.rs
- lib/quantization/src/encoded_vectors.rs
- lib/quantization/src/encoded_vectors_binary.rs
- lib/quantization/src/encoded_vectors_pq.rs
- lib/quantization/src/encoded_vectors_u8.rs
- lib/quantization/tests/test_binary.rs
- lib/quantization/tests/test_pq.rs
- lib/quantization/tests/test_simple.rs
- lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs
- lib/segment/src/vector_storage/quantized/quantized_query_scorer.rs
> Hardware counting for quantization

- lib/collection/src/config.rs
> better error on missing vector name

- lib/collection/src/shards/transfer/driver.rs
Remove the assertion as it of no use.
> Remove unnecessary assert

- lib/collection/src/collection/distance_matrix.rs
- lib/collection/src/collection_manager/segments_searcher.rs
- lib/segment/src/segment/entry.rs
- lib/segment/src/segment/search.rs
Let the compiler optimize memory reuse.
> Optimize search batch

- lib/collection/src/collection/distance_matrix.rs
Decrease memory allocations when building large matrix API results.
> Optimize matrix API result rendering

- lib/collection/src/shards/replica_set/update.rs
Refactor the replica set update logic to make the possible branches easier to understand. Make tiny adjustments alongside it.
Most notably this refactors the two separate if-blocks into a single if{if-else} block to clarify both branches are mutually exclusive.
> Refactor replica set update

- lib/collection/src/shards/collection_shard_distribution.rs
- lib/storage/src/content_manager/toc/create_collection.rs
> Two tiny refactors while looking through the codebase

- src/common/health.rs
Make `/readyz` a more strict and let it catch up to the latest current consensus commit, instead of just the latest commit at the time the peer started.
In other words, it now constantly polls the latest commit and tries to catch up to that, instead of just trying to catch up to the latest commit we saw at the time of starting the peer.
This is important because if a replica is marked as dead and is then recovered, the active state of that replica might blink on the restarted peer while it is already accepting updates. That could result in missing updates.
Some potential negative side effects of this change are:
- it might take longer to be ready
- if there is a constant stream of new consensus operations we may never catch up
- we have more calls across the cluster to synchronize /readyz …
> Make /readyz catch up to latest consensus commit

- lib/common/common/src/lib.rs
- lib/common/common/src/mmap_hashmap.rs
- lib/common/common/src/zeros.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
Add a small helper extension trait to write zeros into `std::io::Writer`.
> Add WriteZerosExt to write zeros

- docs/redoc/master/openapi.json
- lib/api/src/rest/models.rs
- lib/storage/src/content_manager/toc/mod.rs
- lib/storage/src/content_manager/toc/request_hw_counter.rs
- lib/storage/src/dispatcher.rs
- src/common/metrics.rs
- src/common/telemetry.rs
- src/common/telemetry_ops/hardware.rs
- src/common/telemetry_ops/mod.rs
> Add hardware metrics to /metrics and /telemetry API

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/verification/mod.rs
- lib/collection/src/operations/verification/update.rs
- lib/segment/src/types.rs
- lib/storage/src/content_manager/conversions.rs
- src/actix/api/update_api.rs
- src/common/points.rs
- tests/openapi/test_strictmode.py
> [Strict mode] Max upsert batch size

- lib/storage/src/content_manager/toc/mod.rs
Potential fix for panicking in debug mode + tests when dropping ToC.
> Fix hardware counter panic in Toc

- lib/collection/src/shards/replica_set/update.rs
During stream shard transfer in ForwardShardProxy we modify `wait` parameter for internal and forwarded requests.
This can lead to inconsistent responses across replicas, as wait=true/false affects when the validation of request is happening. It might be, that some replicas accept the request, while the one with shard transfer doesn't. 
This inconsistency triggers the consistency resolution mechanism, which previously ignored the difference between transient and non-transient errors. 
This PR makes consistency resolution more careful with non-transient errors and only deactivate the replica if there are others who completely applied update operation
> better handle non-transient errors

- lib/collection/src/collection_manager/segments_searcher.rs
Similar to https://github.com/qdrant/qdrant/pull/5505 but for segments during search.
Process the results from segments out of order as soon as possible.
Tested against CI benchmarks does not show any visible improvements.
I assume it shines with a large number of segments which are not balanced.
> SegmentSearcher stream results

- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/collection/src/collection_manager/tests/mod.rs
- lib/segment/src/types.rs
- test to demonstrate inconsistency failure during optimization
> Points inconsistency during cancel of optimization

- lib/gpu/src/basic_test.rs
- lib/gpu/src/device.rs
- lib/gpu/src/instance.rs
- lib/segment/src/index/hnsw_index/gpu/batched_points.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_devices_manager.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_graph_builder.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_heap_tests.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_level_builder.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_links.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_search_context.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_visited_flags.rs
- lib/segment/src/index/hnsw_index/gpu/mod.rs
- lib/segment/src/index/hnsw_index/gpu/shader_builder.rs
- lib/segment/src/index/hnsw_index/gpu/shaders/bheap.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/links.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/run_greedy_search.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/run_insert_vector.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/search_context.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/shared_buffer.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_candidates_heap.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_heuristic.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_hnsw_search.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_nearest_heap.comp
- lib/segment/src/index/hnsw_index/gpu/shaders/visited_flags.comp
- lib/segment/src/index/hnsw_index/graph_layers.rs
- lib/segment/src/index/hnsw_index/graph_layers_builder.rs
Full black-boxed HNSW construction on GPU without integration.
> Gpu hnsw construction

- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/segments_updater.rs
> Minor improvements during testing

- Cargo.toml
- src/segment_inspector.rs
- src/wal_inspector.rs
- tests/consensus_tests/fixtures.py
> segment inspector + small fixes

- src/tonic/logging.rs
Fallback to using the gRPC response status code to pick the log message when the `grpc-status` header is missing.
So far I have seen it missing only in case of success but it is better to not have a blind spot.
> Improve gRPC logging middleware

- lib/api/src/conversions/json.rs
- Memory Optimization: Improved allocation by eliminating raw loops.
- Code Readability: Enhanced code readability by reducing nesting and restructuring logic for clarity.
- Unit Tests: Added unit tests to assert correctness and reliability of the JSON-Proto conversion.
> Optimize JSON-Proto Conversion, Improve Memory Allocation, and Add Unit Tests

- Cargo.lock
> Bump tonic from 0.12.1 to 0.12.3 to fix CWE

- lib/common/issues/src/dashboard.rs
- lib/common/issues/src/issue.rs
- lib/common/issues/src/lib.rs
- lib/common/issues/src/problems/too_many_collections.rs
- lib/segment/src/problems/unindexed_field.rs
- lib/storage/src/rbac/mod.rs
- src/actix/api/issues_api.rs
- tests/consensus_tests/auth_tests/test_jwt_access.py
This is required for those users, who only have collection-level access, but still want to use web-ui dashboard.
> allow to read related issues with collection-level access

- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/collection_manager/holders/segment_holder.rs
- lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
- lib/collection/src/shards/local_shard/mod.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/segment/src/segment/segment_ops.rs
Contains no logic changes, just slight improvements.
> Minor refactorings I collected during recent testing

- Cargo.lock
- lib/quantization/Cargo.toml
- lib/quantization/src/encoded_vectors_binary.rs
- lib/quantization/src/encoded_vectors_pq.rs
- lib/quantization/src/encoded_vectors_u8.rs
Quantization metadata file should be serialized atomically.
> Atomic save quantization metadata

- .github/workflows/release-artifacts.yml
- Cargo.toml
- config/deb.yaml
- src/settings.rs
- **explicit configuration of deb package**
- **use special build feature**
Bonus: now works with web-ui
> Explict configuration for deb package build

- Cargo.lock
- Cargo.toml
- src/tracing/default.rs
- src/tracing/handle.rs
- src/tracing/test.rs
Enhances https://github.com/qdrant/qdrant/issues/5347 
I haven't been able to test this by just running the integration tests, so please suggest me how to test this.
> Support for JSON logging

- lib/collection/src/shards/dummy_shard.rs
- lib/collection/src/shards/forward_proxy_shard.rs
- lib/collection/src/shards/local_shard/mod.rs
- lib/collection/src/shards/proxy_shard.rs
- lib/collection/src/shards/queue_proxy_shard.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/collection/src/shards/shard.rs
- tests/openapi/test_strictmode.py
This PR is a follow up on https://github.com/qdrant/qdrant/pull/5653#discussion_r1893581924 but for the read rate limiter
- fix disabling rate limiter
- refactor `Mutex<Option>` to `Option<Mutex>`
> Reshape read rate limiter and fix disabled mode

- config/config.yaml
A bit of [yak shaving](https://www.wordnik.com/words/yak%20shaving) I came across when handling <https://github.com/qdrant/landing_page/pull/1357>.
> Update config descriptions

- Cargo.lock
- Cargo.toml
- lib/blob_store/Cargo.toml
- lib/collection/Cargo.toml
- lib/segment/Cargo.toml
- lib/storage/Cargo.toml
This PR refactors our proptest integration
- promote dependency to workspace
- remove [default features](https://docs.rs/crate/proptest/1.6.0/features)
> Refactor proptest usage

- Cargo.toml
- lib/common/issues/Cargo.toml
- lib/gpu/Cargo.toml
Miscellaneous changes that I gathered from my latest build optimizations.
> Misc. cargo file changes

- lib/collection/src/collection/collection_ops.rs
- tests/consensus_tests/test_resharding.py
This PR (re)implements resharding integration tests, because existing ones are not applicable anymore, since we moved resharding driver into cluster-manager.
> Add resharding integration tests

- .github/workflows/integration-tests.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/rust-gpu.yml
- .github/workflows/rust-lint.yml
- .github/workflows/rust.yml
- .github/workflows/storage-compat.yml
- lib/segment/Cargo.toml
Potential improvement after <https://github.com/qdrant/qdrant/pull/5765>.
This might relax the build time requirements for RocksDB.
> Experiment: enable bindgen-runtime for RocksDB

- lib/segment/src/index/hnsw_index/hnsw.rs
Prepare for the release of Qdrant 1.13 and enable HNSW graph links compression by default. This allows us to test it on chaos testing for some time.
This removes the configurability and enables it by default. Converting existing graphs is disabled, thus only new graphs are affected.
> Enable HNSW graph links compression by default

- docs/redoc/master/openapi.json
- lib/collection/src/operations/cluster_ops.rs
- lib/collection/src/operations/types.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/collection/src/shards/transfer/mod.rs
Expose resharding related types in API.
> Resharding: expose types

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/operations/verification/mod.rs
- lib/segment/src/types.rs
- lib/storage/src/content_manager/conversions.rs
- tests/openapi/helpers/helpers.py
- tests/openapi/test_strictmode.py
Adds 2 new limits to strict mode:
- Max amount of total conditions in the filter
- Max elements in a condition
> [Strict mode] limits for filter and conditions

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.13.x/openapi.json
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
Prepare for the Qdrant 1.13 release.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5203>.
> Bump version to v1.13.0

- lib/segment/src/payload_storage/simple_payload_storage_impl.rs
Fixes a bug where in memory payload storage doesn't persist after restart of Qdrant when upserted using `set_by_key`
> [Bugfix] Fix set_by_key not persisted between reload

- lib/blob_store/benches/bustle_bench/payload_storage.rs
- lib/blob_store/benches/random_data_bench.rs
- lib/blob_store/benches/real_data_bench.rs
- lib/blob_store/src/blob_store.rs
- lib/segment/benches/range_filtering.rs
- lib/segment/benches/sparse_index_search.rs
- lib/segment/src/fixtures/payload_context_fixture.rs
- lib/segment/src/index/payload_index_base.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/query_optimization/payload_provider.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs
- lib/segment/src/payload_storage/mmap_payload_storage.rs
- lib/segment/src/payload_storage/on_disk_payload_storage.rs
- lib/segment/src/payload_storage/payload_storage_base.rs
- lib/segment/src/payload_storage/payload_storage_enum.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/payload_storage/simple_payload_storage_impl.rs
- lib/segment/src/payload_storage/tests.rs
- lib/segment/src/segment/entry.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
- lib/segment/tests/integration/nested_filtering_test.rs
- lib/segment/tests/integration/payload_index_test.rs
- lib/segment/tests/integration/sparse_vector_index_search_tests.rs
Renames `*_measured` functions back to their original + more signature changes
> Io measurement rename functions

- lib/segment/src/payload_storage/simple_payload_storage_impl.rs
Fixes compilation of `test_set_by_key_consistency ` test, to fix CI on `dev`.
> Fix `test_set_by_key_consistency` test

- lib/blob_store/benches/bustle_bench/payload_storage.rs
- lib/blob_store/benches/random_data_bench.rs
- lib/blob_store/benches/real_data_bench.rs
- lib/blob_store/src/blob_store.rs
- lib/blob_store/src/tracker.rs
- lib/segment/src/index/payload_index_base.rs
- lib/segment/src/index/plain_payload_index.rs
- lib/segment/src/index/query_optimization/payload_provider.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs
- lib/segment/src/payload_storage/mmap_payload_storage.rs
- lib/segment/src/payload_storage/on_disk_payload_storage.rs
- lib/segment/src/payload_storage/payload_storage_base.rs
- lib/segment/src/payload_storage/payload_storage_enum.rs
- lib/segment/src/payload_storage/query_checker.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/payload_storage/simple_payload_storage_impl.rs
- lib/segment/src/payload_storage/tests.rs
- lib/segment/src/segment/entry.rs
- lib/segment/src/segment/segment_ops.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
> Implement more IO measurements for PayloadStorage

- lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
> Fix flush of deleted flags for mmap payload storage

- lib/segment/src/id_tracker/mod.rs
A point without a version did not go through the full flushing sequence because the version is flushed last.
An incomplete point should not be visible when merging points from the different segments.
The current behavior creates false positive for the data consistency check, where points without vectors get a synthetic version `Some(0)` generated.
Example of broken storage created by [crasher](https://github.com/qdrant/crasher)
```
025-01-23T14:40:08.473815Z ERROR segment::segment::segment_ops: Vector storage 'sparse-vector-float16-1' is missing point Some(NumId(750)) point_offset: 1600 version: Some(0)    
2025-01-23T14:40:08.473900Z ERROR segment::segment::segment_ops: Vector storage 'sparse-vector-float16-2' is missing point Some(NumId(750)) point_offset: 1600 version: Some(0) …
```
> id_tracker filters out points without version to honor flushing sequence

- lib/collection/src/collection_manager/holders/segment_holder.rs
Same motivation as https://github.com/qdrant/qdrant/pull/5866
Points without version are not well defined and should not be updated, only deleted.
> update filters out points without version to honor flushing sequence

- lib/collection/src/collection_manager/segments_searcher.rs
- lib/collection/src/shards/local_shard/facet.rs
- lib/collection/src/shards/local_shard/scroll.rs
- lib/common/common/src/counter/hardware_accumulator.rs
- lib/common/common/src/counter/hardware_counter.rs
- lib/segment/src/data_types/query_context.rs
- lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
- lib/sparse/src/index/search_context.rs
- src/actix/auth.rs
- src/common/auth/mod.rs
- src/tonic/auth.rs
> Chore: HwCounter cleanup 

- lib/storage/src/content_manager/consensus_manager.rs
Fix debug assertion as explained in <https://github.com/qdrant/qdrant/pull/5903#issuecomment-2624344071>.
> Fix debug assertion for consensus compacting

- lib/gpu/src/instance.rs
> Fixing Foung to Found

- src/main.rs
Fixes <https://github.com/qdrant/qdrant/issues/5880>
> check if bootrap is the same as URI

- Cargo.lock
- lib/segment/Cargo.toml
- lib/segment/src/json_path/parse.rs
Update to nom v8 https://github.com/rust-bakery/nom/blob/main/CHANGELOG.md#800-2025-01-25
> Update to nom 8

- lib/quantization/tests/integration/empty_storage.rs
- lib/quantization/tests/integration/test_binary.rs
Minor improvements in quantization integration tests
> Quantization test improvements

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/common/collection_size_stats.rs
- lib/collection/src/operations/verification/update.rs
- lib/collection/src/shards/replica_set/mod.rs
- lib/segment/src/types.rs
- lib/storage/src/content_manager/conversions.rs
- tests/openapi/test_strictmode.py
New strict mode config for the max number of points per collection.
> Add strict mode for max points count

- lib/storage/src/content_manager/consensus_manager.rs
Found by `lockbud`
```
[2025-02-13T20:25:26Z WARN  lockbud::callbacks] [
{
"ConflictLock": {
"bug_kind": "ConflictLock",
"possibility": "Possibly",
"diagnosis": [
{
"first_lock_type": "ParkingLotRead(content_manager::consensus::persistent::Persistent)",
"first_lock_span": "lib/storage/src/content_manager/consensus_manager.rs:984:13: 984:23 (#0)",
"second_lock_type": "ParkingLotMutex(content_manager::consensus::consensus_wal::ConsensusOpWal)",
"second_lock_span": "lib/storage/src/content_manager/consensus_manager.rs:1012:13: 1012:28 (#0)",
"callchains": []
},
{
"first_lock_type": "ParkingLotMutex(content_manager::consensus::consensus_wal::ConsensusOpWal)",
"first_lock_span": "lib/storage/src/content_manager/consensus_manager.rs:965:27: 965:42 (#0)",
"second_lock_type": …
```
> Fix deadlock in consensus manager

- lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
- lib/segment/src/index/query_optimization/mod.rs
- lib/segment/src/index/query_optimization/rescore_formula/mod.rs
- lib/segment/src/index/query_optimization/rescore_formula/value_extractor.rs
- lib/segment/src/index/query_optimization/rescore_formula/value_retriever.rs
- lib/segment/src/index/struct_payload_index.rs
- lib/segment/src/types.rs
This is the first PR to implement score boosting. 
This PR introduces internals to retrieve values from points in an optimized way by creating closures for each variable in the formula, similar to what we do for condition checkers.
> [score boosting] value retrievers

- lib/segment/src/index/query_optimization/optimized_filter.rs
- lib/segment/src/index/query_optimization/optimizer.rs
- lib/segment/src/index/query_optimization/rescore_formula/formula_scorer.rs
- lib/segment/src/index/query_optimization/rescore_formula/mod.rs
- lib/segment/src/index/query_optimization/rescore_formula/value_retriever.rs
Builds on top of #5979 
Creates a structure which can be reused to score many points.
> [score boosting] formula scorer

- lib/api/src/rest/conversions.rs
- lib/collection/src/collection/mod.rs
- lib/collection/src/collection/search.rs
- lib/collection/src/grouping/group_by.rs
- lib/collection/src/lookup/types.rs
- lib/collection/src/operations/conversions.rs
- lib/collection/src/shards/local_shard/clock_map.rs
- lib/collection/src/wal_delta.rs
- lib/common/common/src/bitpacking_ordered.rs
- lib/segment/benches/sparse_index_search.rs
- lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
- lib/segment/src/types.rs
- lib/sparse/src/index/compressed_posting_list.rs
- lib/storage/src/content_manager/consensus/persistent.rs
- src/actix/api/local_shard_api.rs
Handles lints for Rust [1.85](https://releases.rs/docs/1.85.0/)
> Fix Clippy 1.85

- src/common/update.rs
- src/tonic/api/update_common.rs
The last small refactoring for the update API layer. Adds a common `update` function that is a bit easier to call than `toc.update(<lots-of-garbage>)` and tweaks all `do_update_operation` functions to use it. This way we only need to destructure `UpdateParams` and `InternalUpdateParams` ***once***.
> Add `common::update::update` function

- lib/storage/src/content_manager/consensus/persistent.rs
- lib/storage/src/content_manager/consensus_manager.rs
We forgot to include `ClusterMetadata` into Raft snapshots. Oops. This PR fixes this.
> Include `ClusterMetadata` into Raft snapshot

- shell.nix
This PR adds more missing GPU tools and libraries to the `shell.nix`.
Particularly, it fixes the following failure during unit tests run:
```
test basic_test::basic_gpu_test ... FAILED
failures:
---- basic_test::basic_gpu_test stdout ----
thread 'basic_test::basic_gpu_test' panicked at lib/gpu/src/basic_test.rs:30:10:
called `Result::unwrap()` on an `Err` value: Other("Layer VK_LAYER_KHRONOS_validation not found")
```
> nix-shell: add more GPU tools/libraries

- lib/collection/src/shards/local_shard/mod.rs
Fixes <https://github.com/qdrant/qdrant/issues/6025>
When loading a local shard, only load segments from valid directory paths.
Before, we'd try to load every entry in the segments directory as if it was a segment. This caused a panic during segment loading if macOS places a `.DS_Store` file in there.
More specifically, we now ignore:
- non-directories
- hidden directories prefixed with a `.`
- `.DS_Store`
We now also walk over all segment path entries before trying to load them. That is significant because we now catch any IO errors before spawning threads. Before we would leak threads if crashing in the middle.
Log example when trying to load such invalid segment:
```
2025-02-20T18:17:10.241651Z DEBUG collection::shards::local_shard: Segments path entry prefixed with a period, ignoring: …
```
> Improve segment loading, don't load invalid segments

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/rest/schema.rs
- lib/collection/src/operations/universal_query/formula.rs
- lib/collection/src/operations/universal_query/shard_query.rs
- lib/segment/src/index/query_optimization/rescore_formula/parsed_formula.rs
- src/common/inference/batch_processing_grpc.rs
- src/common/inference/query_requests_grpc.rs
Builds on top of #6024 
Adds gRPC interface to score boosting formula
> [score boosting] add gRPC structures

- .github/workflows/dev-docker-image-build-triggered.yml
Add a workflow that can be triggered with specific event.
> Add a workflow to build ghcr image that can be triggered

- Cargo.lock
- lib/gpu/Cargo.toml
- lib/gpu/src/basic_test.rs
- lib/gpu/src/debug_messenger.rs
- lib/gpu/src/device.rs
- lib/gpu/src/instance.rs
- lib/gpu/src/lib.rs
- lib/segment/Cargo.toml
- lib/segment/src/index/hnsw_index/gpu/gpu_devices_manager.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_graph_builder.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_heap_tests.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_level_builder.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
- lib/segment/tests/integration/gpu_hnsw_test.rs
NVidia drivers on linux have a bug that disallows creation a lot of Vulkan instances in the same process. To allow to run unit tests on linux&NVidia, this PR makes Vulkan instance a singleton for unit tests.
> Gpu singleton for tests

- lib/api/src/conversions/inference.rs
- lib/api/src/conversions/vectors.rs
- lib/api/src/rest/conversions.rs
- lib/collection/src/operations/conversions_rest.rs
- lib/collection/src/operations/payload_ops.rs
- lib/collection/src/shards/conversions.rs
- lib/storage/src/content_manager/conversions.rs
Follow up on https://github.com/qdrant/qdrant/pull/6062
> Struct deconstruction in conversions

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/rest/schema.rs
- lib/collection/src/operations/universal_query/formula.rs
- lib/collection/src/operations/universal_query/shard_query.rs
- lib/segment/src/index/query_optimization/rescore_formula/formula_scorer.rs
- lib/segment/src/index/query_optimization/rescore_formula/parsed_formula.rs
Adds the following operations to expression:
- sqrt
- pow
- exp
- log (base 10)
- ln
- abs
> [score boosting] add more expressions

- lib/segment/src/json_path/mod.rs
- **implement proper anonymization for json path**
- **fmt**
> fix json path anonymization

- tests/openapi/test_strictmode.py
All optional fields in `StrictModeConfig` are suffering from the same issue, they can't be unset.
This PR documents the current behavior with a test.
> Document no unset strict config fields

- src/tonic/api/query_common.rs
Stumbled upon that one while performing the struct deconstruction migration.
Decided to finally get rid of the TODO.
> Remove code duplication for recommendation conversion

- lib/collection/src/collection_manager/segments_updater.rs
Removing straight up copy pasta to clear payload by filters.
> Remove code duplication for clear payload

- lib/collection/src/shards/replica_set/update.rs
- tests/openapi/test_strictmode.py
This PR makes sure all update operation are priced according to the content of their content.
It leverages an existing infrastructure for computing the cost of updates from https://github.com/qdrant/qdrant/pull/5729.
> Write rate limit batch update per point count

- lib/collection/src/collection/sharding_keys.rs
- lib/common/common/src/counter/mod.rs
- lib/common/common/src/counter/referenced_counter.rs
- lib/gridstore/benches/bustle_bench/payload_storage.rs
- lib/gridstore/benches/random_data_bench.rs
- lib/gridstore/benches/real_data_bench.rs
- lib/gridstore/src/gridstore.rs
- lib/segment/src/payload_storage/mmap_payload_storage.rs
- lib/segment/src/payload_storage/simple_payload_storage.rs
- lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
- tests/consensus_tests/fixtures.py
- tests/consensus_tests/test_hw_measurement.py
Depends on #5944
- State unmeasured functions in comments
- New consensus test for measuring on remote shard
> Io measurement cleanup and tests

- lib/segment/src/id_tracker/simple_id_tracker.rs
Minor reformat/refactoring changes I collected in the simple ID tracker while changing something else.
This is purely cosmetic, except for one place where we now preallocate a vector.
> Reformat simple ID tracker, preallocate internal to version list

- lib/common/common/src/counter/hardware_counter.rs
- lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
- lib/segment/src/index/field_index/bool_index/mod.rs
- lib/segment/src/index/field_index/bool_index/simple_bool_index.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/tests/mod.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/query_optimization/condition_converter.rs
- lib/segment/src/index/query_optimization/condition_converter/match_converter.rs
- lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs
- lib/segment/src/payload_storage/query_checker.rs
Depends on #5951
Adds IO read measurements for filtering over full text index and bool index.
> Payload fulltext index IO read measurements

- lib/segment/src/id_tracker/immutable_id_tracker.rs
> In immutable ID tracker, embed storage type bytes in enum

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/rest/schema.rs
- lib/collection/src/operations/universal_query/formula.rs
- lib/collection/src/operations/universal_query/shard_query.rs
- lib/common/common/src/math.rs
- lib/segment/src/common/operation_error.rs
- lib/segment/src/index/query_optimization/rescore_formula/formula_scorer.rs
- lib/segment/src/index/query_optimization/rescore_formula/parsed_formula.rs
Adds exponential, gaussian, and linear decay expressions.
Plots and formulas can be visualized here https://www.desmos.com/calculator/htg0vrfmks
I really tried to name the variables as straightforward as I could, but I know there is room for improvement if anyone comes up with a better name.
> [score boosting] Add decay expressions

- lib/common/common/src/counter/hardware_counter.rs
- lib/common/common/src/counter/iterator_hw_measurement.rs
- lib/common/common/src/counter/mod.rs
- lib/common/common/src/iterator_ext/mod.rs
- lib/common/common/src/iterator_ext/on_final_count.rs
- lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
- lib/segment/src/index/field_index/bool_index/mod.rs
- lib/segment/src/index/field_index/bool_index/simple_bool_index.rs
- lib/segment/src/index/field_index/facet_index.rs
- lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
- lib/segment/src/index/field_index/immutable_point_to_values.rs
- lib/segment/src/index/field_index/map_index/immutable_map_index.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/map_index/mutable_map_index.rs
- lib/segment/src/index/field_index/null_index/mmap_null_index.rs
- lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
- lib/segment/src/index/hnsw_index/hnsw.rs
- lib/segment/src/segment/facet.rs
> Payload Index Io measurements with Iterator

- lib/segment/src/segment/segment_ops.rs
> Fix minor typo in logging

- lib/segment/src/common/rocksdb_wrapper.rs
Tracked in: #6157
When the new mutable ID tracker is enabled, don't create the RocksDB column families anymore for the old ID tracker.
If using the new ID tracker, this still loads the RocksDB ID tracker column families if they already exist.
This will prevent old Qdrant versions from trying to load the unused RocksDB ID tracker.
> Mutable ID tracker: when using new tracker, don't create RocksDB CFs

- lib/segment/src/segment_constructor/segment_builder.rs
Tracked in: #6157 
Seems like we missed a feature flag check in one place when implementing `MutableIdTracker`.
> Check `use_mutable_id_tracker_without_rocksdb` feature flag when building new segment

- lib/collection/src/shards/local_shard/mod.rs
- lib/collection/src/update_handler.rs
- lib/segment/src/segment/segment_ops.rs
Make it easier to understand what's going on for debugging.
> Snapshot logging improve

- tests/openapi/test_sparse_idf.py
Test failed with this log:
```
2025-03-21T11:47:39.144200Z DEBUG actix_web::middleware::logger: Error in response: Validate(ValidationErrors({"points": List({1: ValidationErrors({"vector": Struct(ValidationErrors({"?": Struct(ValidationErrors({"indices": Field([ValidationError { code: "must be unique", message: None, params: {} }])}))}))})})}))    
2025-03-21T11:47:39.145162Z  INFO actix_web::middleware::logger: 127.0.0.1 "PUT /collections/test_sparse_idf/points?wait=true HTTP/1.1" 422 127 "-" "python-requests/2.32.3" 0.002846    
```
> Decrease collision probability in sparse vectors test

- lib/collection/src/collection/mod.rs
- lib/collection/src/collection/snapshots.rs
- lib/collection/src/collection/state_management.rs
- lib/collection/src/collection_state.rs
- lib/collection/src/shards/shard_holder/mod.rs
- lib/collection/src/shards/shard_holder/shard_mapping.rs
- lib/storage/src/content_manager/toc/collection_meta_ops.rs
- src/migrations/single_to_cluster.rs
This PR simplifies new `ShardKeyMapping` format support introduced in #6209.
> Simplify `ShardKeyMapping` implementation

- tests/storage-compat/populate_db.py
Add multivector coverage for storage compatibility tests.
I will regenerate the test data once I am done increasing coverage.
> Add multivector to storage compat. tests

- tests/storage-compat/populate_db.py
Adds coverage for `float16` and `uint8` datatypes in the storage compatibility tests.
Adding two new collections will create a 90MB test archive.
> Add all datatypes to storage compat. tests

- config/config.yaml
Suggest that the feature should not be used yet.
Related: <https://github.com/qdrant/qdrant-client/issues/935>
> Mark hardware reporting feature as experimental in the configuration

- README.md
> Update link in README.md for 2025 roadmap

- lib/collection/src/collection/query.rs
- lib/collection/src/collection_manager/holders/proxy_segment.rs
- lib/collection/src/operations/snapshot_storage_ops.rs
- lib/collection/src/shards/proxy_shard.rs
- lib/collection/src/shards/shard_holder/resharding.rs
- lib/collection/tests/integration/collection_test.rs
- lib/quantization/tests/integration/stop_condition.rs
- lib/quantization/tests/integration/test_pq.rs
- lib/segment/src/id_tracker/mutable_id_tracker.rs
- lib/segment/src/index/hnsw_index/graph_layers.rs
- src/common/pyroscope_state.rs
Minor cleanups prompted by RustRover.
> Minor cleanups

- lib/common/common/src/counter/iterator_hw_measurement.rs
- lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
- lib/segment/src/index/field_index/bool_index/mod.rs
- lib/segment/src/index/field_index/bool_index/simple_bool_index.rs
Depends on #6295 
Only measure bool index io if index is on disk
> Only measure HW if on disk for bool index

- lib/common/common/src/counter/conditioned_counter.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_chunks_reader.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_list.rs
- lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
- lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
> Don't measure in-memory hw for full text indices

- lib/common/common/src/counter/iterator_hw_measurement.rs
- lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
- lib/segment/src/index/field_index/map_index/immutable_map_index.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/map_index/mutable_map_index.rs
- lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
> Don't measure in memory geo, map and numeric indices

- lib/collection/src/shards/local_shard/mod.rs
- lib/collection/src/shards/local_shard/shard_ops.rs
We want to make the read rate limiter compute a realistic cost based on the content of the queries.
The first step in that direction is to make the cost computation lazy to ensure we will not impact the performance of non rate limited usage.
> Make read rate limiter cost lazy

- Cargo.lock
- lib/segment/Cargo.toml
> Remove unused Issues dependency on Segment

- lib/common/common/src/counter/conditioned_counter.rs
- lib/common/common/src/counter/counter_cell.rs
- lib/common/common/src/counter/iterator_hw_measurement.rs
- lib/segment/benches/numeric_index_check_values.rs
- lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_list.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_visitor.rs
- lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/postings_iterator.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/mmap_point_to_values.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
> Improve performance of ConditionedCounter

- docs/redoc/master/openapi.json
- lib/common/common/src/counter/conditioned_counter.rs
- lib/common/common/src/counter/counter_cell.rs
- lib/common/common/src/counter/iterator_hw_measurement.rs
- lib/segment/Cargo.toml
- lib/segment/benches/numeric_index_check_values.rs
- lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
- lib/segment/src/index/field_index/bool_index/simple_bool_index.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_list.rs
- lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_visitor.rs
- lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/postings_iterator.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/mmap_point_to_values.rs
- lib/segment/src/index/field_index/null_index/mmap_null_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
- lib/segment/src/telemetry.rs
In this PR:
- Expose index type into telemetry 
- Fix problem with hardware counters
> faster mmap numeric index

- .github/workflows/integration-tests.yml
- .github/workflows/storage-compat.yml
- Cargo.toml
- tests/consensus_tests/utils.py
This PR optimizes our GitHub Actions workflows:
- use explicit `rust-cache` key for a bunch of integration test workflows, so that we store a single GHA cache file instead of 5 copies of it
- disable debug symbols for `dev` builds
- as far as I can tell, we pretty much never need debug symbols (at least, not on CI)
- on my (pretty fast!) machine, disabling debug symbols speeds up builds 20%
- and also reduces `target` dir size 2-3 times
- which should make `rust-cache` 2-3 times smaller
- which should make cache restore faster (which currently takes 20-30s)
- remove unnecessary Rust toolchain setup steps from workflows that only use Dockerized builds
(Currently based on #6280.)
__TODO:__
- another optimization that we can do, is to change Docker layer cache storage from GHA to GHCR
- …
> Optimize GitHub Actions workflows

- docs/redoc/master/openapi.json
- lib/collection/src/shards/dummy_shard.rs
- lib/collection/src/shards/local_shard/telemetry.rs
- lib/collection/src/shards/telemetry.rs
- lib/collection/src/telemetry.rs
- lib/segment/src/common/operation_time_statistics.rs
- lib/storage/src/types.rs
- tests/openapi/test_service.py
Some improvements on top of https://github.com/qdrant/qdrant/pull/6390. 
Also checked latency of telemetry requests with level 3 vs 10 in chaos testing.
Before: (level 10)
```
p50 0.8347805
p99 1.5783391899999997
```
After: (level 3)
```
p50 0.7328605
p99 0.93947373
```
That's a 40% speed up in this case :)
> Improve telemetry logic and test

- lib/collection/src/tests/mod.rs
- lib/collection/src/tests/query_prefetch_offset_limit.rs
Asserts fixed behavior in <https://github.com/qdrant/qdrant/pull/6412>, which broke before in <https://github.com/qdrant/qdrant/pull/6357>.
> Add test for limit and offset in query with prefetch

- lib/segment/src/index/field_index/full_text_index/inverted_index.rs
I had missed to remove the other place where the [introduced assertion](https://github.com/qdrant/qdrant/pull/6264/files#diff-c1c4979963732637d05ae6643868a63e27c517f270e6fb90d138cbc04dfa3d04R391-R436) was incorrect.
This also fixes #6266
> [#6266] Remove incorrect assertion

- lib/segment/src/index/struct_payload_index.rs
- tests/storage-compat/storage-compatibility.sh
We should never enter this condition during development as it could actually hide a different problem https://github.com/qdrant/qdrant/pull/6191
> Debug assert a missing column family or not loaded  payload index

- lib/collection/src/collection/clean.rs
- lib/collection/src/collection/mod.rs
- lib/collection/src/collection/sharding_keys.rs
- lib/collection/src/operations/verification/discovery.rs
- lib/collection/src/operations/verification/mod.rs
- lib/collection/src/operations/verification/query.rs
- lib/collection/src/operations/verification/search.rs
- lib/collection/src/operations/verification/update.rs
- lib/collection/src/shards/channel_service.rs
- lib/collection/src/shards/local_shard/query.rs
- lib/collection/src/shards/shard_holder/mod.rs
- lib/collection/tests/integration/common/mod.rs
- src/common/update.rs
Small refactoring for style consistency.
> Use CollectionResult where possible

- Cargo.lock
- lib/gpu/Cargo.toml
- lib/gpu/src/instance.rs
`cargo build --release --features gpu` failed without this PR on FreeBSD 14.
> build with GPU feature on FreeBSD 14.2

- lib/segment/src/fixtures/index_fixtures.rs
- lib/segment/src/segment_constructor/batched_reader.rs
- lib/segment/src/segment_constructor/mod.rs
- lib/segment/src/segment_constructor/segment_builder.rs
- lib/segment/src/vector_storage/chunked_mmap_vectors.rs
- lib/segment/src/vector_storage/chunked_vector_storage.rs
- lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
- lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
- lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
- lib/segment/src/vector_storage/in_ram_persisted_vectors.rs
- lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
- lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
Main measurements are in
https://github.com/qdrant/qdrant/pull/6508
> Batched reader for segment construction

- lib/collection/src/problems/unindexed_field.rs
- lib/collection/src/update_handler.rs
- lib/common/issues/src/solution.rs
- lib/segment/src/id_tracker/immutable_id_tracker.rs
- src/common/telemetry_ops/collections_telemetry.rs
Follow up to https://github.com/qdrant/qdrant/pull/6516 with non controversial changes.
> Fix Clippy 1.87 bis

- lib/segment/src/fixtures/payload_fixtures.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/mod.rs
- lib/segment/src/types.rs
This test was flaky at first, but this has now been fixed. The test is fully deterministic now. The failure cases were acceptable because the different index types behave a little bit different - that is expected.
> Add full text payload index congruence test

- Cargo.toml
- lib/segment/src/spaces/simple_avx.rs
- lib/segment/src/spaces/simple_sse.rs
Since <https://github.com/qdrant/qdrant/pull/6554> is merged, we can now bump the MSRV to 1.87.
Resolves the TODOs left in <https://github.com/qdrant/qdrant/pull/6540>.
> Bump MSRV to 1.87

- config/config.yaml
- docs/redoc/master/openapi.json
- lib/storage/src/content_manager/toc/create_collection.rs
- lib/storage/src/content_manager/toc/mod.rs
- lib/storage/src/content_manager/toc/telemetry.rs
- lib/storage/src/types.rs
- lib/storage/tests/integration/alias_tests.rs
- src/common/telemetry_ops/collections_telemetry.rs
```
QDRANT__STORAGE__MAX_COLLECTIONS=1000
```
> Add setting to limit max number of collections

- lib/collection/src/problems/unindexed_field.rs
- lib/segment/src/types.rs
- tests/openapi/test_strictmode.py
Follow up to https://github.com/qdrant/qdrant/pull/6363#issuecomment-2847187070
This PR fills a hole in the missing index detection where the `lookup` & `range` capabilities were not taken into account.
Also no fix required for `Formula` because of https://github.com/qdrant/qdrant/pull/6494
> Fix UnindexedField infra to handle lookup&range index requirements

- Cargo.lock
- Cargo.toml
- lib/gridstore/benches/bitmask_bench.rs
- lib/gridstore/benches/real_data_bench.rs
- lib/segment/benches/dynamic_mmap_flags.rs
- lib/segment/benches/mmap_bitslice_buffered_update_wrapper.rs
https://github.com/bheisler/criterion.rs/blob/master/CHANGELOG.md#060---2025-05-17
> Update Criterion 0.6

- lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
- lib/segment/src/vector_storage/multi_dense/mod.rs
- lib/segment/src/vector_storage/multi_dense/volatile_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/src/vector_storage/raw_scorer.rs
- lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
Depends on <https://github.com/qdrant/qdrant/pull/6561>
Same as <https://github.com/qdrant/qdrant/pull/6561>, but for multi dense vectors.
> Add volatile multi dense vector storage

- docs/redoc/master/openapi.json
- lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
- lib/segment/src/types.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/src/vector_storage/raw_scorer.rs
- lib/segment/src/vector_storage/sparse/mod.rs
- lib/segment/src/vector_storage/sparse/volatile_sparse_vector_storage.rs
- lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs
- lib/segment/src/vector_storage/vector_storage_base.rs
Depends on <https://github.com/qdrant/qdrant/pull/6564>
Same as <https://github.com/qdrant/qdrant/pull/6564>, but for sparse vectors.
> Add volatile sparse vector storage

- lib/storage/src/content_manager/snapshots/recover.rs
Payload index is registered in 2 places: in collection level and on segment level.
When recovering snapshot, we forgot to also register payload index on collection (aka consensus) level.
This might not be noticeable from collection info, as info reads from segment level, but functions like strict mode and notifications warning might be malfunctioning because of it.
> register payload index fields on recovering snapshot

- lib/segment/src/segment_constructor/segment_builder.rs
Previously optimizer used vector storage to estimate range of internal points
But this approach became problematic once we introduced multivectors. And in case of empty vectors it doesn't even work properly.
This PR simplified assignment of the internal range, by using id tracker instead of vectors storage
> use id-tracker to estimate internal points range

- docs/grpc/docs.md
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/ops.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/proto/points_internal_service.proto
- lib/api/src/grpc/qdrant.rs
- lib/api/src/rest/conversions.rs
- lib/collection/src/shards/remote_shard.rs
- src/actix/api/update_api.rs
- src/common/inference/query_requests_grpc.rs
- src/common/update.rs
- src/tonic/api/points_api.rs
- src/tonic/api/points_internal_api.rs
- src/tonic/api/query_common.rs
- src/tonic/api/update_common.rs
> InferenceUsage in grpc

- lib/api/src/grpc/conversions.rs
- lib/segment/src/data_types/index.rs
- lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/immutable_postings_enum.rs
- lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings_enum.rs
- lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
- lib/segment/src/index/field_index/full_text_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
- lib/segment/src/index/field_index/full_text_index/positions.rs
- lib/segment/src/index/field_index/full_text_index/tests/mod.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/full_text_index/tokenizers.rs
Builds on top of #6619
Enables positions in postings by introducing two new enums:
- `ImmutablePostings` for immutable index.
- `MmapPostingsEnum` for mmap index.
> [phrase match] Mmap full text index for phrase

- lib/collection/src/config.rs
- lib/segment/src/data_types/collection_defaults.rs
- lib/segment/src/data_types/mod.rs
- lib/segment/src/types.rs
- lib/storage/src/content_manager/toc/collection_meta_ops.rs
- lib/storage/src/content_manager/toc/create_collection.rs
- lib/storage/src/content_manager/toc/mod.rs
- lib/storage/src/dispatcher.rs
- lib/storage/src/types.rs
Fixes https://github.com/qdrant/qdrant/issues/6623
(also fixes the same problem for configurable number of shards)
> Fix default replication factor

- .github/workflows/docker-image.yml
Closes #1957
There is another open pull request, but it need changes and based of too old code.
> Added major and minor tags

- .github/workflows/docker-image.yml
> Replaced ::set-output(deprecated) with

- lib/common/common/src/disk.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
- lib/segment/src/segment_constructor/segment_constructor_base.rs
- lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
- lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
- lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
- lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs
- lib/segment/tests/integration/multivector_hnsw_test.rs
Depends on <https://github.com/qdrant/qdrant/pull/6603>.
In the same vein as <https://github.com/qdrant/qdrant/pull/6603>, but for multi dense vector storage.
> Migrate away from RocksDB based multi dense vector storage

- lib/segment/src/index/field_index/full_text_index/inverted_index/positions.rs
https://github.com/qdrant/qdrant/actions/runs/15640413402/job/44066148907
> Fix release build

- lib/quantization/src/encoded_storage.rs
- lib/quantization/src/encoded_vectors.rs
- lib/quantization/src/encoded_vectors_binary.rs
- lib/quantization/src/encoded_vectors_pq.rs
- lib/quantization/src/encoded_vectors_u8.rs
- lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/gpu_multivectors.rs
- lib/segment/src/vector_storage/async_raw_scorer.rs
- lib/segment/src/vector_storage/chunked_vectors.rs
- lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_mmap_storage.rs
- lib/segment/src/vector_storage/quantized/quantized_multi_custom_query_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_multi_query_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs
- lib/segment/src/vector_storage/quantized/quantized_query_scorer.rs
- lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs
- lib/segment/src/vector_storage/quantized/quantized_vectors.rs
- lib/segment/src/vector_storage/query_scorer/custom_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/mod.rs
- lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs
- lib/segment/src/vector_storage/query_scorer/sparse_custom_query_scorer.rs
- lib/segment/src/vector_storage/raw_scorer.rs
This PR replaces some trait generic parameters with associated types. Consequentially, these generic parameters could be omitted in places where they are redundant.
> Replace some generic parameters with associated types

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
- lib/segment/src/data_types/index.rs
- lib/segment/src/index/field_index/full_text_index/tests/mod.rs
- lib/segment/src/index/field_index/full_text_index/tokenizers.rs
- tests/openapi/test_phrase_matching.py
Builds on top of #6670  
This exposes the phrase matching feature, so let's merge only until necessary.
> [phrase matching] expose `phrase_matching` flag in rest and grpc

- src/common/inference/infer_processing.rs
- src/common/inference/service.rs
- **fix error handling in inference**
- **fmt**
> inference errors

- lib/common/common/src/either_variant.rs
- lib/common/common/src/lib.rs
- lib/segment/src/index/struct_payload_index.rs
An alternative implementation to https://github.com/qdrant/qdrant/pull/6789
> Optimize detect when primary condition is sufficient review

- docs/grpc/docs.md
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/collections.proto
- lib/api/src/grpc/qdrant.rs
For consistency between gRPC and REST
> rename stemming -> stemmer

- lib/collection/src/collection/distance_matrix.rs
- lib/collection/src/operations/verification/query.rs
- src/common/inference/query_requests_grpc.rs
- src/common/inference/query_requests_rest.rs
- src/tonic/api/query_common.rs
Avoid minor unnecessary allocations.
> Remove fallback eager allocation

- lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
Additional changes to <https://github.com/qdrant/qdrant/pull/6837>, suggested by <https://github.com/qdrant/qdrant/pull/6810#discussion_r2204629605>.
In mmap payload indices, replace temporary boxing with [`Either`](https://docs.rs/either/latest/either/enum.Either.html).
After the 1.15 release, these indices will be refactored to remove all empty iterator branches. That will remove the boxing (and now the use of `Either`). I've added TODO markers to emphasize this.
> In mmap payload indices, replace boxing with Either

- lib/quantization/benches/binary.rs
- lib/quantization/src/encoded_vectors_binary.rs
Criterion benchmark for the new scalar query BQ feature. It compares SIMD acceleration vs native implementation
> bq scalar query benches

- lib/collection/src/collection/resharding.rs
- lib/collection/src/shards/shard_holder/resharding.rs
Applied suggestion from https://github.com/qdrant/qdrant/pull/6800#discussion_r2182234121
> Remove `is_in_progress` since `check_abort_resharding` exists

- Cargo.lock
- Cargo.toml
- docs/redoc/default_version.js
- docs/redoc/index.html
- docs/redoc/v1.15.x/openapi.json
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
Release Qdrant 1.15.0
Follows the pattern of <https://github.com/qdrant/qdrant/pull/6404>
> Bump version to 1.15.0

- src/common/metrics.rs
Fix for https://github.com/qdrant/qdrant/issues/6908
> check for empty collection data

- src/tonic/auth.rs
This PR removes the authentication requirement for gRPC health check endpoints, allowing them to be accessed without API keys or JWT tokens. This change enables proper health monitoring and load balancer checks in production environments where authentication credentials may not be available or appropriate (we're using ALB's in AWS and can't really add keys)
- **`src/tonic/auth.rs`**: Updated the authentication middleware to bypass validation for health check endpoints
- Added path-based routing logic in the `check()` function to identify health check requests
- Health check endpoints now bypass the standard `auth_keys.validate_request()` flow
- Endpoints are granted full access with appropriate `Access` and `InferenceToken` extensions
- Early return prevents unnecessary authentication …
> Allow health check endpoints to bypass authentication

- lib/quantization/src/encoded_vectors.rs
Another fix to satisfy clippy 1.89 in `dev`.
> Fix clippy warnings for Rust 1.89

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
Follows the pattern of <https://github.com/qdrant/qdrant/pull/6934>
> Bump version to 1.15.2

- lib/segment/src/index/field_index/index_selector.rs
- lib/segment/src/index/field_index/map_index/immutable_map_index.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/map_index/mutable_map_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
Same as <https://github.com/qdrant/qdrant/pull/6999>, but for the map index.
> Open and load map payload indices in single stage

- lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
- lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
- lib/segment/src/index/field_index/full_text_index/tests/mod.rs
- lib/segment/src/index/field_index/full_text_index/tests/test_congruence.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/index_selector.rs
Same as <https://github.com/qdrant/qdrant/pull/6999>, but for the full text index.
> Open and load full text payload indices in single stage

- config/development.yaml
- src/common/inference/config.rs
- src/common/inference/service.rs
- src/main.rs
- tests/openapi/test_bm25.py
Fixes BM25 inference, which failed due to InferenceService not being loaded.
Also adds a test for this case.
> Always load InferenceService

- lib/segment/src/index/field_index/bool_index/mod.rs
- lib/segment/src/index/field_index/bool_index/mutable_bool_index.rs
- lib/segment/src/index/field_index/bool_index/simple_bool_index.rs
- lib/segment/src/index/field_index/field_index_base.rs
- lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
- lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
- lib/segment/src/index/field_index/geo_index/mod.rs
- lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
- lib/segment/src/index/field_index/map_index/immutable_map_index.rs
- lib/segment/src/index/field_index/map_index/mmap_map_index.rs
- lib/segment/src/index/field_index/map_index/mod.rs
- lib/segment/src/index/field_index/map_index/mutable_map_index.rs
- lib/segment/src/index/field_index/null_index/mutable_null_index.rs
- lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/mod.rs
- lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
- lib/segment/src/index/field_index/numeric_index/tests.rs
- lib/segment/src/index/struct_payload_index.rs
Remove higher level load functions.
See <https://github.com/qdrant/qdrant/pull/6999> for more details.
> Remove load function in payload indices

- Cargo.lock
- Cargo.toml
- lib/collection/Cargo.toml
Bump development dependencies in one PR as there are somehow not handled by Dependabot lately.
> Bump dev deps

- docs/grpc/docs.md
- docs/redoc/master/openapi.json
- lib/api/src/grpc/conversions.rs
- lib/api/src/grpc/proto/points.proto
- lib/api/src/grpc/qdrant.rs
- lib/collection/src/problems/unindexed_field.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/immutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/mod.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/mutable_inverted_index.rs
- lib/segment/src/index/field_index/full_text_index/inverted_index/postings_iterator.rs
- lib/segment/src/index/field_index/full_text_index/tests/test_congruence.rs
- lib/segment/src/index/field_index/full_text_index/text_index.rs
- lib/segment/src/index/query_estimator.rs
- lib/segment/src/index/query_optimization/condition_converter/match_converter.rs
- lib/segment/src/payload_storage/condition_checker.rs
- lib/segment/src/types.rs
- tests/openapi/test_fts.py
- **internal implementation for filter any**
- **implement api for match `text_any`**
ToDo:
- Tests
- Examples
> filter text any

- lib/shard/src/segment_holder/tests.rs
This test was used to detect the bug fixed by https://github.com/qdrant/qdrant/pull/7109
This PR proposes to keep the test to avoid regressions in the future.
> Test for segment double proxies

- Cargo.lock
- Cargo.toml
- lib/api/Cargo.toml
- lib/common/common/src/defaults.rs
- tools/missed_cherry_picks.sh
Follows the pattern of <https://github.com/qdrant/qdrant/pull/7061>
> Bump version to 1.15.4

- .github/workflows/docker-image.yml
> Fix docker image pipeline

- lib/collection/src/update_handler.rs
Small fixes to `UpdateHandler::flush_worker` based on [this coderabbitai comment](https://github.com/qdrant/qdrant/pull/7146#pullrequestreview-3155219304) in #7146.
- rename `wal_flash_job` to `wal_flush_job`
- correctly handle/report WAL flush errors
> Flush worker fixes

- lib/api/src/rest/schema.rs
- lib/collection/src/operations/vector_ops.rs
- lib/segment/src/data_types/facets.rs
- lib/shard/src/operations/payload_ops.rs
Various missing filter validations in the REST API.
Backported from https://github.com/qdrant/qdrant/pull/7216
> Fix missing REST API Filter validations

- lib/common/common/src/mmap_hashmap.rs
- lib/segment/src/id_tracker/immutable_id_tracker.rs
- lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
- lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs
Also checked other places with sync_all, seems to be the only one missing.
> Fix missing flush, flush before sync
