qdrant/qdrant

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
This PR fixes the optimizer to apply the `on_disk` parameter to a sparse vector index once the memap threshold is reached.
=> Fix optimizer change sparse index on disk

lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/replica_set/mod.rs
Prevents
```
2023-12-04T21:07:20.019429Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/Sync unexpectedly failed with Internal error "Service internal error: No target shard 1 found for update" 0.253019    
```
on shard reocvery.
=> Better shard transfer init

lib/sparse/src/index/search_context.rs
This PR adds a new mechanism for plain search on the sparse inverted index for a set of ids.
Supersedes  https://github.com/qdrant/qdrant/pull/3113
=> Plain search by ids in sparse vector inverted index

lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
Snapshots for mmap sparse index could not be restored because a mandatory configuration files was not captured.
I validated the fix manually.
=> Fix sparse mmap snapshot

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/collection_ops.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/local_shard_operations.rs, lib/collection/tests/integration/collection_restore_test.rs
Makes the point, vector and indexed vector counts from the collection information response optional. This changes the API and allows us to potentially remove these counts in the future.
The problem is that these counts are very inaccurate due to architectural limitations. Many users have been asking questions about it. If we cannot improve these counters we may as well better remove them.
More specifically, these are now made optionally in both our REST and gRPC APIs:
```json
GET /collections/my_collection
{
"vectors_count": 123,
"indexed_vectors_count": 10,
"points_count": 123
}
```
Internally we use a new structure called `CollectionInfoInternal` which doesn't have optionals. That way we ensure there won't be issues with missing counts for critical calculations.
1. [x] Does your …
=> Make point, vector and indexed vector counts optional in collection info

lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/vector_storage/query_scorer/sparse_custom_query_scorer.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
This PR protects the sparse vector index build from crashing over an inconsistent storage.
This situation can be created using [crasher](https://github.com/qdrant/crasher) with the experimental [sparse vector branch](https://github.com/qdrant/crasher/tree/sparse-vectors).
Running with `cargo run -- --working-dir "/home/agourlay/Workspace/qdrant/" --exec-path "target/release/qdrant"`
Yields after a few minutes:
```
2023-12-07T10:10:23.044680Z DEBUG segment::segment_constructor::segment_constructor_base: Mismatch of point and vector counts (3100 != 0, storage: ./storage/collections/workload-crasher/0/segments/c3f149e2-3182-4643-b1e4-162d61a7dd17/vector_storage-sparse-name)    
2023-12-07T10:10:23.230269Z ERROR qdrant::startup: Panic backtrace: 
0: …
```
=> Sparse vector index build handles missing points in storage

.github/workflows/release-artifacts.yml
This fixes building macOS release artifacts when publishing a new release ([failed run for latest release](https://github.com/qdrant/qdrant/actions/runs/7140593745)).
The Rust compiler shipped on macOS runners was outdated and doesn't match our requirements. This PR ensures that we always install the latest stable version.
Bonus:
- install latest stable on Linux as well
- add `rustup show` and `cargo -Vv` commands to make debugging this easier in the future
The current CI run doesn't test this, as it's for release builds only. But I've tested the changes manually with a dry run here: https://github.com/qdrant/qdrant/actions/runs/7166079287?pr=3194
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to …
=> Fix release artifacts for macOS

src/common/health.rs
Fixes <https://github.com/qdrant/qdrant/issues/3193>.
When doing rolling upgrade from Qdrant v1.6.* to v1.7.*, the `/readyz` check would fail _indefinitely_, practically preventing graceful rolling upgrades in Kubernetes. 🤦‍♀️
The issue is that v1.6.* (and earlier) versions simply don't have gRPC APIs required for the `/readyz` check in v1.7.*, and "unimplemented" errors aren't handled properly.
This PR implements "unimplemented" errors handling during `/readyz`, allowing upgrade to v1.7.*.
=> Fix `/readyz` when upgrading cluster from 1.6 to 1.7

src/actix/api/service_api.rs, src/actix/mod.rs, src/common/health.rs
This PR removes strict check that node received `cluster_size / 2` successful `GetConsensusCommit` responses during `/readyz` check to allow `/readyz` check to pass, when not enough nodes are available.
Fixes #3193.
=> Fix `/readyz` if nodes are unavailable

.github/workflows/release-artifacts.yml
Follow up after <https://github.com/qdrant/qdrant/pull/3194>.
It appears those changes weren't good enough. We need to run `rustup update` explicitly.
Somehow this wasn't needed in my testing on CI. Maybe we're getting different macOS machines assigned on CI having a different image.
Test run: https://github.com/qdrant/qdrant/actions/runs/7179454708/job/19549668581?pr=3214
- 'install dependencies' now really shows installing the latest Rust version
=> Fix release artifacts for macOS, explicitly update

docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/collection/src/common/fetch_vectors.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/recommendations.rs, lib/collection/tests/integration/grouping_test.rs, lib/collection/tests/integration/multi_vec_test.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/spaces/metric.rs, lib/segment/src/spaces/simple.rs, lib/segment/src/spaces/simple_avx.rs, lib/segment/src/spaces/simple_neon.rs, lib/segment/src/spaces/simple_sse.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/async_raw_scorer.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/query/mod.rs, lib/segment/src/vector_storage/query_scorer/custom_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs, lib/segment/src/vector_storage/raw_scorer.rs, src/tonic/api/points_common.rs
`VectorType` is an obsolete name. After sparse vector release it's a dense vector.
Also was renamed:
`NamedVectorStruct::Named` -> `NamedVectorStruct::Dense`
`RecommendExample::Vector` -> `RecommendExample::Dense`
=> Rename `VectorType` to `DenseVector`

lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs
Fix for https://github.com/qdrant/qdrant/issues/3137
Here is a test for quantization existing during HNSW building.
Also a refactoring. All segment entities (and connections between them!!!) are defined during construction. Fix this concept for quantization.
=> Remove quantization update from hnsw index

lib/sparse/src/index/search_context.rs
This PR optimizes the plain search through the inverted index for sparse vectors.
```
sparse-vector-search-group/inverted-index-filtered-plain
time:   [134.17 ms 134.44 ms 134.70 ms]
change: [-34.599% -34.462% -34.317%] (p = 0.00 < 0.05)
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
...
sparse-vector-search-group/plain-filtered-payload-index
time:   [128.26 ms 128.41 ms 128.56 ms]
change: [-35.495% -35.337% -35.185%] (p = 0.00 < 0.05)
```
The insight is that by sorting the input ids, we can actually fully leverage the posting list iterator by performing binary search on a shrinking space.
=> Faster sparse vectors plain search

lib/segment/src/index/sparse_index/indices_tracker.rs, lib/segment/src/index/sparse_index/mod.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/tests/integration/sparse_discover_test.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs, tests/consensus_tests/test_snapshot_recovery.py, tests/consensus_tests/test_snapshot_upload.py
Currently, sparse vector index does not support large indices (like `u32::MAX`). Fixed it using indices remapping
=> sparse vectors with large indices support

lib/segment/src/common/utils.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/types.rs, openapi/tests/openapi_integration/test_payload_indexing.py
What happened:
- Payload `assign` operation was trying to upgrade index no matter is the value was actually present in the index or not. It was considering the non-present value as `None` (which is incorrect)
Why it broke only in 1.7.x?
- The change introduced in https://github.com/qdrant/qdrant/commit/8b05c4a388504ab3473db70a61702b9a8e8642b5 was removing point from index before inserting a new one. It was fixing a different issue. But it was made under the assumption that `assign` will not try to insert non-existing fields.
Current changes are tested manually on the reproducible example, proper integration tests will be introduces in another PR by @KShivendu 
---
Scenario to reproduce:
- Create a collection with vectors and payload
- Create payload index
- Make sure the vectors are …
=> fix missing indexing values on set-payload operation

tests/storage-compat/full-snapshot.snapshot.gz, tests/storage-compat/storage.tar.bz2
This PR regenerates the data for the storage compatibility tests.
The rational is to capture the latest `indices_tracker.json` file introduced in https://github.com/qdrant/qdrant/pull/3230
e.g.
```
./storage/collections/test_collection_product_x64/0/segments/d40060bb-3737-4ff6-9b84-faba16f51e6b/vector_index-text/
./storage/collections/test_collection_product_x64/0/segments/d40060bb-3737-4ff6-9b84-faba16f51e6b/vector_index-text/inverted_index.data
./storage/collections/test_collection_product_x64/0/segments/d40060bb-3737-4ff6-9b84-faba16f51e6b/vector_index-text/inverted_index_config.json
./storage/collections/test_collection_product_x64/0/segments/d40060bb-3737-4ff6-9b84-faba16f51e6b/vector_index-text/indices_tracker.json
./storage/collections/test_collection_product_x64/0/segments/d40060bb …
```
=> Regenerate storage compatibility data with new sparse index_tracker

lib/collection/src/collection_manager/collection_updater.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/update_handler.rs, lib/collection/tests/integration/collection_test.rs, lib/segment/src/common/utils.rs, lib/segment/src/index/field_index/full_text_index/tokenizers.rs, lib/segment/src/index/field_index/geo_hash.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/query/discovery_query.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs, lib/segment/tests/integration/payload_index_test.rs, lib/segment/tests/integration/segment_tests.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs
Rust 1.75 is landing on [December 28th](https://blog.rust-lang.org/inside-rust/2023/12/21/1.75.0-prerelease.html) so now is a good time to make sure our CI won't fail on that day.
This PR fixes new clippy lints issues and a bunch of minor reports from RustRover.
The main source of noise is the [get_first lint](https://rust-lang.github.io/rust-clippy/master/index.html#/get_first).
=> Fix clippy 1.75

lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
Small performance optimization to simplify the posting iterator advancing sequence.
Using `Iterator::next` to move the iterator forward is sub-optimal as we always `peek` beforehand to verify if the point id matches. 
This yields around 2% performance improvements.
=> Optimize sparse inverted index advance

src/actix/mod.rs
Extension to <https://github.com/qdrant/qdrant/pull/3257>.
Avoid logging `/healthz`, `/readyz` and `/livez` in access logs because it can be quite noisy.
=> Avoid logging `/healthz`, `/readyz`, `/livez` in access logs

lib/sparse/src/common/sparse_vector_fixture.rs
This PR increases the size of the sparse vectors used in tests and benchmarks.
The goal is to have a more challenging workload reflecting what can happen with SPLADE.
Previously the number of generated dimensions would be under 200 dimensions.
By decreasing the skip probability, it now reaches 300 dimensions.
=> Larger sparse vectors in test & bench

Cargo.toml
This PR enables debug information for cargo benchmarks.
I often end up enabling the debug info when profiling benchmarks in order to get more precise flamegraphs and pprof files.
=> Enable debug info in benchmarks

Cargo.lock, lib/storage/Cargo.toml, lib/storage/src/content_manager/collections_ops.rs
Since Rust 1.75 we can remove this usage of [`async-trait`](https://docs.rs/async-trait/latest/async_trait/).
We still have some other usages left but we cannot remove those due to other constraints and due to code generation including them.
=> Remove one usage of `async-trait`

lib/collection/src/shards/local_shard.rs
During collection recovery, we normally show a progress bar as part of recovering the WAL. This is useful information because this step can take a very long time if it contains expensive operations.
The progress bar is not rendered if the output is non-interactive, making it hidden. This is what happens on our cloud, making it very hard to determine whether a long recovery is going on or not.
This PR adds a fall back to render the current progression in text:
```
2024-01-02T16:35:25.606991Z  INFO collection::shards::local_shard: Recovering collection benchmark: 0/749 (0%)
2024-01-02T16:35:25.824195Z  INFO collection::shards::local_shard: 100/749 (13%)
2024-01-02T16:35:26.048062Z  INFO collection::shards::local_shard: 200/749 (26%)
2024-01-02T16:35:26.273770Z  INFO …
```
=> If we cannot render a progress bar, fall back to text

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/utils/mem.rs
Supersedes <https://github.com/qdrant/qdrant/pull/3303>.
Bumps `sysinfo` to `0.30.3` with additional required code changes.
This also removes an explicit `refresh()`, as the `System::new_with_specifics` before it already does this for us.
=> Bump sysinfo to 0.30.3

.github/workflows/dev-docker-image-build.yml
This should fix the bloating of disk in our self hosted GH runner
=> fix: Prune containers and volumes in self-hosted gh runner

Cargo.lock, lib/collection/Cargo.toml, lib/common/common/Cargo.toml, lib/common/common/src/cpu.rs, lib/common/common/src/lib.rs, lib/segment/src/index/hnsw_index/hnsw.rs, src/consensus.rs
Set custom priorities for consensus and HNSW build threads on Linux. This should not affect regular operation but will improve reliability in extreme cases. For example, this can help prevent consensus lagging behind if the machine if very busy building HNSW.
For HNSW build threads the priority is lowered, since these usually fully saturate CPU cores lowering the priority attempts to make affecting ongoing updates/searches less likely. The consensus threads the priority is raised, to allow handling consensus updates as soon as possible. Raising the thread priority likely fails because it requires special permissions on most systems, so it soft-fails with a debug message.
More specifically, on Linux this tries to set:
- consensus threads: nice=-10
- HNSW build threads: nice=10
- all other …
=> Custom thread priorities on Linux

Cargo.toml
This [sets](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) our MSRV to 1.75 in `Cargo.toml`, which is now our minimum version since merging <https://github.com/qdrant/qdrant/pull/3314>.
It will inform users with an outdated toolchain when trying to compile:
```bash
$ cargo +1.74.0 build
error: package `qdrant v0.11.1 (/home/timvisee/git/qdrant)` cannot be built because it requires rustc 1.75 or newer, while the currently active rustc version is 1.74.0
```
We could also list the MSRV as requirement in our README, but I think it's easy to miss if we change it again. The above is probably good enough to prevent users being confused about it.
=> Set MSRV in Cargo.toml

src/greeting.rs
In <https://github.com/qdrant/qdrant/pull/3169> we updated our greeting to render the bind address, rather than localhost.
If the bind address is `0.0.0.0`/`127.0.0.1` or the IPv6 equivalent, render `localhost` instead.
=> When bind IP is zero, render it as localhost in greeting

.github/workflows/release-artifacts.yml
Added MUSL build release targets for
- x86_64-unknown-linux-musl
- aarch64-unknown-linux-musl
You can check on the [Fork action](https://github.com/Dhanus3133/qdrant/actions/runs/7429125259) for successful builds
/claim #3334
=> feat: add musl release 

lib/sparse/src/index/search_context.rs
This PR is a low hanging fruit I noticed while working on a larger optimization.
We currently fetch the query weight corresponding to a posting list iterator every time we score a point.
This small cost adds up and actually shows in profiling.
The proposed fix is to precompute for each posting list their corresponding query information.
The result is a consistent 3% gain on the inverted index search:
```
sparse-vector-search-group/inverted-index-search
time:   [30.959 ms 31.025 ms 31.098 ms]
change: [-4.5531% -3.8959% -3.3699%] (p = 0.00 < 0.05)
sparse-vector-search-group/inverted-index-filtered-payload-index
time:   [34.407 ms 34.544 ms 34.693 ms]
change: [-3.3703% -2.7161% -2.1013%] (p = 0.00 < 0.05)
```
And  8% on the plain search: …
=> Optimize sparse search by precomputing once the query info per posting

.github/workflows/release-artifacts.yml
This PR adds build step for Debian package.
[Release](https://github.com/neo773/qdrant/releases/tag/v1.7.10)
[CI Run](https://github.com/neo773/qdrant/actions/runs/7434325055/job/20228354047#step:7:146)
/claim #3335
=> feat: debian package build step

lib/sparse/src/index/search_context.rs
This PR is a low hanging fruit for filtered search on sparse vector search.
For the case where no index is present for the payload, a high number of candidate will be discarded by the filtering condition.
Given that the request cancellation shows up in profiling, it makes sense to perform the filtering check first in order to shortcut the iteration.
This yields a 2% performance improvement almost for free.
```
sparse-vector-search-group/inverted-index-filtered-plain
time:   [277.97 ms 278.39 ms 278.79 ms]
change: [-2.4829% -2.2152% -1.9612%] (p = 0.00 < 0.05)
```
=> Check cancellation after filtering condition to speedup filtered sparse search

lib/common/common/src/fixed_length_priority_queue.rs, lib/sparse/src/index/search_context.rs
This PR optimizes the sparse vector search.
One short-coming of the current implementation is that it recomputes continuously the min record ids across posting lists to know how to advance the cursors.
This PR proposes to track the min records ids across all posting lists in a min-heap to avoid performing extra work.
It yields a 20% performance improvement.
```
sparse-vector-search-group/inverted-index-search
time:   [23.966 ms 24.069 ms 24.180 ms]
change: [-21.418% -20.990% -20.558%] (p = 0.00 < 0.05)
```
=> Optimize inverted index search by tracking min record ids

lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/sparse/src/index/search_context.rs
With https://github.com/qdrant/qdrant/pull/3347 we introduced a new min-heap to track the min record id.
This min-heap expects to be sized with a non-zero capacity otherwise it panics.
This PR makes sure that this situation cannot occur by:
- protecting the search context at construction time
- filtering empty search query vectors at the sparse vector index level
=> Handle empty sparse vector search

Cargo.lock, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/snapshots_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/Cargo.toml, lib/collection/src/collection/snapshots.rs, lib/collection/src/common/mod.rs, lib/collection/src/common/sha_256.rs, lib/collection/src/operations/snapshot_ops.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/transfer/snapshot.rs, lib/collection/src/tests/mod.rs, lib/collection/src/tests/sha_256_test.rs, lib/collection/src/tests/snapshot_test.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/snapshots/mod.rs, src/common/collections.rs, src/common/snapshots.rs
Adds a `checksum` field as suggested in #2830 
This implementation calculates an index file checksum on the fly. Because of this, one thing that's still up for discussion is the buffer size for calculating the checksum. Currently, the intermediate buffer is set to 1MB which might be too little if the snapshot files are big.
=> Add checksum to `SnapshotDescription`

lib/collection/src/collection/snapshots.rs, lib/collection/src/common/sha_256.rs, lib/storage/src/content_manager/snapshots/mod.rs
Very small change. This puts the debug message for computing a file checksum in a central place.
Hashing can be quite expensive on large files, so it's useful to print a debug line to sense what might be going on.
I decided to put it here because we'll be using the file hashing function in a lot more places, in <https://github.com/qdrant/qdrant/pull/3381> for example.
=> Put checksum computation debug message in a central place

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/segment/src/data_types/integer_index.rs, lib/segment/src/types.rs, lib/segment/tests/integration/payload_index_test.rs, src/tonic/api/points_common.rs
Fixes naming inconsistency in <https://github.com/qdrant/qdrant/pull/3380>.
We had `IntegerParams`, but on second thought, I changed it to `IntegerIndexParams` in this PR. It makes it consistent with `TextIndexParams` and may prevent naming conflicts in the future.
=> Rename IntegerParams to IntegerIndexParams to be consistent with text

lib/collection/src/collection_manager/segments_searcher.rs
Interesting side-effect of Context Search made this shine: many (or all) results can have score of `0.0`, which triggers search re-runs. 
The main reason of this optimization is that using large search `ef` values is expensive, but currently it is also being used for non-indexed segments (where there is no `ef` value). This causes that even for small limits, there is sampling happening.
This fix disables the sampling optimization for when a plain index is being used.
=> Disable large limit optimization for plain indices

lib/common/common/src/fixed_length_priority_queue.rs, lib/sparse/src/index/search_context.rs
This PR optimizes the sparse vector search for real life data.
The work done in https://github.com/qdrant/qdrant/pull/3347 & https://github.com/qdrant/qdrant/pull/3359 has yielded great gains on synthetic random data.
However, a more end to end test with a real SPLADE embeddings for MSMARCO revealed that the performance actually worsened compared to 1.7.3.
Using a min-heap to track the minimum record ids works well when posting lists have more or less the same size but **not** when the distribution is highly skewed. The cost of repeatedly pushing new values onto the heap starts to dominate.
Here is an example of real distribution where most posting lists are very short except a few which contains a large amount of data.
In order to fix this issue it is necessary to rollback the min-heap …
=> Optimize sparse vector for real life distribution

.github/workflows/dev-docker-image-build.yml
This should make it easier to pull the latest dev branch container from Github Container registry in our CI benchmarks
=> fix: Update main dev image tag in ghcr

.github/workflows/dev-docker-image-build.yml
All of our containers were getting pushed as `ghcr.io/qdrant/qdrant/qdrant:dev` instead of `ghcr.io/qdrant/qdrant:dev`
See [this](https://github.com/qdrant/qdrant/pkgs/container/qdrant%2Fqdrant)
=> fix: ghcr image name should be just qdrant

lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
This PR is the logically continuation of https://github.com/qdrant/qdrant/pull/3413 which deletes exhausted empty posting lists.
The insight is that reaching a single posting list enables to quickly generate the scores by-passing the whole "advance" machinery.
Using the [sparse-vector-benchmarks](https://github.com/qdrant/sparse-vectors-benchmark) with `python main.py --skip-creation false --dataset small --graph-y-limit 150`
Best of 3 runs.
```
DEV
Latency distribution:
50p: 39.38 millis
95p: 62.93 millis
99p: 74.37 millis
999p: 90.5 millis
max: 116.35 millis
PR
Latency distribution:
50p: 36.67 millis
95p: 61.06 millis
99p: 72.09 millis
999p: 84.94 millis
max: 98.15 millis
```
DEV             |  PR
:-------------------------:|:-------------------------:
=> Optimize sparse search reaching single posting list

lib/collection/src/collection/mod.rs
In <https://github.com/qdrant/qdrant/pull/3255> we added a property to set the default shard transfer method, which is `null` by default for automatic selection.
At the call site where we initiate automatic shard transfers, we simply passed this null value along as `None`. Because we didn't selected a specific method here we render the following warning further down the line. This appears for every automatic shard transfer which can be quite noisy:
```
2024-01-22T16:39:27.608842Z  WARN collection::collection::shard_transfer: No shard transfer method selected, defaulting to StreamRecords   
```
This PR makes sure we select `stream_records` as default method from this place to prevent the warnings from popping up. It is the same as our current behavior, but prevents the warning.
In the …
=> For automatic shard transfers, prevent no shard transfer method warning

Cargo.lock
Supersedes <https://github.com/qdrant/qdrant/pull/3443>, merging into `dev`.
Fixes security alert: https://github.com/qdrant/qdrant/security/dependabot/62
=> Bump shlex from 1.1.0 to 1.3.0

lib/storage/src/content_manager/collections_ops.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/errors.rs, openapi/tests/openapi_integration/test_alias.py, src/actix/helpers.rs
Fixes  #3217
- This PR fixes the return of AlreadyExists error instead of returning InvalidArgument in case there is an attemp to create a collection that already exists.
- To achieve this i have created a AlreadyExists error type and AlreadyExists function for StorageError enum and changed the return of StorageError from BadInput to AlreadyExists.
- This  uses tonic::Code::AlreadyExists for the returning status code.
- It also adds AlreadyExists error type for actix to handle this.
- This uses HttpResponse::Conflict for building HttpResp.
- It also adds status code and description for HttpError.
=> fixes gRPC API return status code.

lib/storage/src/dispatcher.rs, src/actix/api/shards_api.rs, src/tonic/api/collections_api.rs, tests/consensus_tests/test_collection_creation_after_dropping.py
Fixes <https://github.com/qdrant/qdrant/issues/2616>, <https://github.com/qdrant/qdrant/issues/3254>.
After creating a collection in distributed mode, synchronize all nodes. This ensures the collection is ready on all nodes for follow-up operations such as upsertions.
If we don't do this, upserting into the collection on another node can fail as it may still be setting things up.
When synchronization fails a warning is reported and the collection creation call returns as if it was successful. This can happen if a node is unreachable during that time. This is better than failing, because this will eventually resolve itself and firing the same call another time will result in a 'already exists' error.
We don't have to do this for collection deletion, as it is unlikely that we expect …
=> Synchronize nodes after collection creation

docs/redoc/master/openapi.json, lib/api/build.rs, lib/api/src/grpc/proto/shard_snapshots_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/common/sha_256.rs, lib/collection/src/operations/snapshot_ops.rs, lib/collection/src/shards/remote_shard.rs, lib/common/common/src/validation.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/snapshots/recover.rs, openapi/openapi-shard-snapshots.ytt.yaml, openapi/openapi-snapshots.ytt.yaml, openapi/tests/openapi_integration/conftest.py, openapi/tests/openapi_integration/test_shard_snapshot.py, openapi/tests/openapi_integration/test_snapshot.py, src/actix/api/snapshot_api.rs, src/actix/helpers.rs, src/common/snapshots.rs, src/tonic/api/snapshots_api.rs
Add `checksum` option to `RecoverShardSnapshotRequest` (GRPC), `/collections/{collection_name}/snapshots/recover`, `/collections/{collection}/shards/{shard}/snapshots/recover`, and (REST).
Closes #3371.
=> add optional checksum to snapshot recovery request

lib/segment/src/index/field_index/immutable_point_to_values.rs, lib/segment/src/index/field_index/map_index/immutable_map_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/mod.rs, lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/tests.rs
`ImmutableMapIndex` and `ImmutableNumericIndex` have a similar pattern for mapping from point id to values. This pattern is a flattened `Vec<Vec<_>>` structure.
Because geo index will use the same pattern too, I find it important to separate this pattern to avoid logic copying.
`ImmutablePointToValues` is a flattened representation of `Vec<Vec<_>>` with deletion.
=> Filed index point-to-values as separate struct

.github/workflows/rust.yml, lib/segment/src/common/utils.rs, lib/segment/src/index/query_estimator.rs
This PR migrates all our doctest to regular unit tests.
It is motivated by the fact that we currently spends several minutes on CI for executing only 3 tests.
=> Remove doctest usage

lib/sparse/src/index/posting_list.rs
Tiny change spotted during the great sparse vector accelerator program.
=> PostingElement does not need to be Copy

Cargo.lock
Tackling https://github.com/qdrant/qdrant/security/dependabot/61
Initial PR to master was stuck by clippy https://github.com/qdrant/qdrant/pull/3429.
This PR can be backported later to master.
=> Update h2 0.3.24

lib/segment/src/vector_storage/query/context_query.rs
Context search combines the "loss"es of multiple positive-negative pairs, right now the formula is 
$L(x)=min(s(a,p)-s(a,n), 0)$
where $s(v_1, v_2)$: similarity between two vectors, $a$: vector we are evaluating, $p$: positive vector, $n$: negative vector
This function creates a __linear__ loss once a point $a$ is closer to the negative vector. However, it may be problematic, as pointed out by @generall, when a pair of examples is at the periphery of the embedding space, and the negative vector points towards the rest of the points, relative to the positive vector.
This makes the combination with other pairs hard, because the loss of single pair can eclipse the loss of other pairs. There is no lower limit to how much loss is assigned to a pair.
By plugging in our current loss function …
=> Fix potential context search edge case

Cargo.lock, Cargo.toml, benches/search-points/Cargo.toml, lib/api/Cargo.toml, lib/collection/Cargo.toml, lib/common/cancel/Cargo.toml, lib/common/common/Cargo.toml, lib/common/io/Cargo.toml, lib/common/memory/Cargo.toml, lib/segment/Cargo.toml, lib/sparse/Cargo.toml, lib/storage/Cargo.toml
This explores the idea of moving dependencies we use often to our workspace as described [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace).
It forces us to use the same dependency definition (version, features) in all our sub crates, because we only define it once. Before this change, we had wildly different definitions across all crates.
I manually selected these to subjectively be:
- used often
- having difficult feature flags
- having inconsistent configurations across our sub-crates
- requiring strict versions across multiple crates
With this PR I'd like to **request for comment**. What do we think about this? We can include more/less dependencies on the workspace level if we do desire.
1. [x] Does your submission …
=> Move common dependencies to workspace

lib/segment/src/index/hnsw_index/hnsw.rs
On some systems we fail to set lower thread priority.
To prevent the noisy warnings below, we downgrade them to a debug message:
```
2024-01-30T16:29:10.443672Z  WARN segment::index::hnsw_index::hnsw: Failed to set low thread priority for HNSW building, ignoring: Failed to set thread priority: PriorityNotInRange(0..=0)    
2024-01-30T16:29:10.443675Z  WARN segment::index::hnsw_index::hnsw: Failed to set low thread priority for HNSW building, ignoring: Failed to set thread priority: PriorityNotInRange(0..=0)
```
=> Demote thread priority setting warning to debug message

src/common/metrics.rs, tests/openapi_consistency_check.sh
This adds the `discover` and `discover_batch` endpoints to the `metrics` whitelist.
=> metrics endpoint: Whitelist `discover` endpoints

lib/collection/src/update_handler.rs
This log is a bit confusing for the users https://github.com/qdrant/qdrant/issues/3507.
Let's demote it to debug because:
- it is not actionable
- this is about an internal implementation
=> Demote missing client for update ack. log

config/config.yaml, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/benches/batch_search_bench.rs, lib/collection/src/operations/config_diff.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/optimizers_builder.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/replica_set/update.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/integration/common/mod.rs, lib/common/common/src/cpu.rs, lib/common/common/src/defaults.rs, lib/segment/src/types.rs, lib/storage/tests/integration/alias_tests.rs
In <https://github.com/qdrant/qdrant/pull/3364> we made the groundwork for dynamically saturating CPU usage while optimizing.
This PR integrates the feature with additionally required public API/configuration changes. Instead of having fixed optimization limits in the configuration, everything now defaults to being dynamic (automatic).
Configuration changes are mostly described in review comments below. I've also added a `cpu_budget` property to configure what number of CPUs to saturate for optimization tasks.
The idea is to merge this as part of Qdrant 1.8.
=> Dynamic CPU saturation integration

Cargo.lock
Reinstate those 3 updates from:
- https://github.com/qdrant/qdrant/pull/3489
- https://github.com/qdrant/qdrant/pull/3482
- https://github.com/qdrant/qdrant/pull/3485
Lost after merging https://github.com/qdrant/qdrant/pull/3364/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eL2047
=> Restore dependency upgrades after merge

docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/segment/src/index/field_index/histogram.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/tests.rs, lib/segment/src/index/query_estimator.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/types.rs, openapi/tests/openapi_integration/test_payload_indexing.py
Initially it made sense to me to keep different types separate in `FieldCondition`, but now I propose to handle all `Range` conditions similarly and together, so here we add a new `RangeInterface` enum to wrap them together.
This change also made me realize we missed using the actual index sometimes when filtering `datetime_range` conditions (this is fixed now, but not very pretty, see `PayloadFieldIndex` implementation).
Note: this only affects the REST interface, GRPC is intact.
A bonus change I did is to use pattern matching and destructuring in the checkers section, so it will be checked by compiler to not forget any new conditions.
3. [x] …
=> Datetime index: Introduce `RangeInterface`

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/mod.rs
Adds `force` field to the `ClockTag` type, to be used for "diff" shard transfer stuff. Currently, does nothing with the field, but it will (may?) be utilized in the future PRs.
=> Add `force` field to the `ClockTag` type

src/actix/api/collections_api.rs, src/actix/api_key.rs, src/actix/mod.rs
Fixes <https://github.com/qdrant/qdrant/issues/3543>, <https://github.com/qdrant/qdrant-web-ui/issues/158>.
This reorders our actix web REST API services so that we don't have pattern matching conflicts.
As a micro optimization, I now also binary search of the list of allowed patterns.
=> Fix REST API pattern match ordering problem

lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
context: https://github.com/qdrant/qdrant/pull/3464
Optimize sparse vector search by advancing posting lists without binary search.
We know exactly where to move the cursor for the posting list when reaching the end of the batch.
No need to use `skip_to` with a point id which performs a binary search internally.
- server `Standard D8ds v5 (8 vcpus, 32 GiB memory)`
- client `Standard D4s v3 (4 vcpus, 16 GiB memory)`
- 8 segments
- index.on_disk=false
- full data set with 9M points
- 6980 queries
```
DEV
min: 125.61 millis
50p: 374.41 millis
95p: 570.08 millis
99p: 644.55 millis
999p: 723.14 millis
max: 772.38 millis
```
```
PR
min: 90.75 millis
50p: 179.43 millis
95p: 310.99 millis
99p: 408.16 millis
999p: 462.66 millis
max: 533.39 millis
```
DEV             |  PR …
=> Optimize sparse search by advancing postings without binary search

lib/collection/src/operations/mod.rs, lib/collection/src/shards/replica_set/clock_set.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/update.rs
This PR
- add `ClockSet` type to generate clock tags for update operations
- assign clock tags to update operations (and update operation responses)
Currently based on #3408, but will be rebased on `dev` once #3408 is merged.
=> Assign clock tags to internal update operations (and update operation responses)

lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/update_handler.rs, lib/collection/src/wal.rs
Required for: <https://github.com/qdrant/qdrant/pull/3509>
We had a field called `max_ack_version` to specify limit what the last version was that could be acknowledged/truncated from the WAL. This PR changes to specify what WAL version to keep instead, shifting the logic by one.
To accompany this, I've renamed the field from `max_ack_version` to `wal_keep_from`.
This change is important because it now allows keeping the first entry in the WAL by setting it to `0`, while this was not possible before. It is required for <https://github.com/qdrant/qdrant/pull/3509>.
3. [x] Have you checked …
=> Change `max_ack_version` to be `wal_keep_from`

Cargo.lock, lib/collection/Cargo.toml, lib/storage/Cargo.toml
This bumps the `env_logger` dependency from 0.10.2 to 0.11.
We want this because we also use that version in our latest `wal` crate:
https://github.com/qdrant/wal/blob/acaf1b2ebd5de3a871f4d2c48e13fc8788ffa43b/Cargo.toml#L30
=> Bump env_logger to 0.11

Cargo.lock, Cargo.toml, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/collection/Cargo.toml, lib/collection/src/grouping/group_by.rs, lib/segment/Cargo.toml, lib/segment/benches/conditional_search.rs, lib/segment/src/fixtures/payload_fixtures.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/types.rs, lib/segment/tests/integration/payload_index_test.rs
/claim #3522 
**Note:** in /Cargo.toml:181 I used a custom fork of schemars to allow using SmolStr directly in the API. This is unsecure and should be replaced with a fork in the qdrant organization like the tonic patch above!
I created a new bench function `conditional-search-large-match-any` that measures the performance increase. To test the performance of the old implementation one can simply checkout the first commit of this PR.
Results for 100k points, 1k MatchAny values of which 15% can be a matching value:
Old: `1.07ms`
This PR: `561.12µs`
=> Optimize MatchAny

lib/segment/src/data_types/order_by.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/segment.rs, openapi/tests/openapi_integration/test_order_by.py
Tracked by: #3521 
Currently all `order_by` calls use a streaming approach from the BTree of the numeric index. But this is inefficient when there is already a high-constraining filter in the request, which can potentially make the stream have to iterate through an excessive amount of values to fulfill the requested `limit`. In this case, it makes more sense to get iterate through the filtered points first, and then sort the top points only.
This is the same optimization that is done without `order_by` on scroll calls, so it reuses the same estimation logic to choose streaming vs pre-filtering.
I have confirmed locally that this yields performance improvements by manually querying with web-ui dashboard. It can be between 4-10x faster, compared to `dev` branch.
1. [x] Does your submission …
=> Order-by: use pre-filtering for high-constraining filters

lib/segment/src/common/rocksdb_wrapper.rs
This PR configures the `default` column family like all other column families.
After https://github.com/qdrant/qdrant/pull/3557 it was [reported](https://github.com/qdrant/qdrant/pull/3557#discussion_r1482184228) that the RocksDB logs still mentioned an incorrect `write_buffer_size` once at startup.
I was able to see the same locally and after some digging I found out that RocksDB always creates a default column family just in case there are key-value pairs without column.
See https://github.com/facebook/rocksdb/wiki/Column-Families
By applying the following patch I was able to configure properly the default column family.
see `OPTIONS-00000xx` files.
```
[CFOptions "default"]
...
write_buffer_size=10485760
```
I have not found how to disable this column family completely.
=> Configure default RocksDB column family

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/point_ops.rs, lib/collection/src/operations/conversions.rs, lib/segment/src/data_types/order_by.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/types.rs, openapi/tests/openapi_integration/test_order_by.py
Tracked by: #3521 
We recently added support for a datetime index, which also has range-able capabilities. This PR enables the usage of datetimes for ordering in scroll with minimal interface changes.
- Allow integers as `start_from` parameter. But this should also be paired with a new `RangeInterface::Int(Range<i64>)`
=> Order-by: support datetimes

tests/basic_api_test.sh, tests/basic_grpc_test.sh, tests/basic_sparse_grpc_test.sh, tests/basic_sparse_test.sh, tests/consensus_tests/run_tests.sh, tests/consensus_tests/test_restart.sh, tests/grpc_consistency_check.sh, tests/integration-tests-api-key.sh, tests/integration-tests.sh, tests/low-ram/low-ram.sh, tests/openapi_consistency_check.sh, tests/openapi_integration_test.sh, tests/removes_test.sh, tests/snapshots/snapshots-recovery.sh, tests/storage-compat/gen_storage_compat_data.sh, tests/storage-compat/storage-compatibility.sh, tests/tls/gen.sh, tests/tls/test_tls.sh, tests/tls/test_tls_snapshot_shard_transfer.sh, tools/clean-old-rocksdb-logs.sh, tools/generate_openapi_models.sh
Script beginning with `#!/bin/bash` are failing to run on systems where `bash` has a different path in the FS, e.g. on NixOS.
```console
$ ./tools/generate_openapi_models.sh
zsh: ./tools/generate_openapi_models.sh: bad interpreter: /bin/bash: no such file or directory
$ file /bin/bash
/bin/bash: cannot open `/bin/bash' (No such file or directory)
$ which bash
/run/current-system/sw/bin/bash
```
Replacing `#!/bin/bash` with `#!/usr/bin/env bash` fixes that.
---
=> Use /usr/bin/env bash in shebangs

lib/collection/src/shards/local_shard/clock_map.rs
My auto formatter constantly keeps removing the `::` prefix from `use io::file_operations;`, breaking imports.
I suggest to change imports like this to prevent this problem.
=> Change `io` imports because it breaks on auto formatters

lib/collection/src/shards/replica_set/clock_set.rs
This adds a bunch of tests for the `ClockSet` structure we added for shard diff transfer (<https://github.com/qdrant/qdrant/issues/3477>).
We'll need to add more tests for other types, but we'll be doing that in separate PRs.
=> Add clock set unit tests

lib/api/build.rs, lib/api/src/grpc/proto/collections_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/mod.rs, lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/shard.rs, src/tonic/api/collections_internal_api.rs
This adds an gRPC (internal) interface to request the recovery point of a remote shard. It also adds a convenience function to the `RemoteShard` to easily access this.
It has a new `RecoveryPoint` type, similar to the `ClockMap`, to hold the clock states. Right now it just returns the last seen clock states as recovery point.
=> Add endpoint to request recovery point for remote shard

lib/segment/src/vector_storage/chunked_vectors.rs
Fix https://github.com/qdrant/qdrant/issues/3579
While insertion in `ChunkedVectors`, we may add a large internal ID and skip allocation for points with lower ID. We cannot read vector data for such points afterwards. But vector storage has to guarantee that all vectors from 0 to `total_points_count` are presented
=> Allocate all chunks data in chunked vectors except the last one

lib/api/src/grpc/conversions.rs, lib/collection/src/operations/conversions.rs, lib/segment/src/data_types/order_by.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/payload_storage/query_checker.rs, lib/segment/src/types.rs
Creates a newtype pattern for `DateTime<Utc>`, so that we can encapsulate the special deserialization and conversion to timestamp in a single entity.
=> refactor: add DateTime wrapper

lib/api/build.rs, lib/api/src/grpc/conversions.rs, lib/collection/src/operations/conversions.rs, src/tonic/api/points_common.rs, tests/basic_sparse_grpc_test.sh
Add custom validation step in grpc while conversion. We cannot use default field-based validation because sparse requests require checking 2 separate fields. I find the custom implementation of struct validation bad because It affects another validated field.
=> Validate sparse indices in grpc search

lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/transfer/snapshot.rs, lib/collection/src/wal.rs
Depends on: <https://github.com/qdrant/qdrant/pull/3550>
Required for: https://github.com/qdrant/qdrant/pull/3509
This widens the usability of our queue proxy to allow using it for queuing and transferring WAL entries that are in the past. Before we could only queue and transfer new WAL entries after creating the queue proxy.
This is essential for <https://github.com/qdrant/qdrant/pull/3509>, as it will be used for transferring the WAL diff. I choose to use the queue proxy for this because it already had all the bells and whistles to handle this transfer safely. 
3. [x] Have you checked …
=> Allow using queue proxy on WAL in the past

lib/common/issues/src/dashboard.rs
The mistake here was to make the test depend on timings, which made the test brittle for CI.
I've refactored it to avoid using them, it should completely remove flakiness.
Fixes #3566
=> Fix flaky `dashboard::tests::test_singleton`

lib/collection/src/shards/local_shard/clock_map.rs
This changes the `Display` implementation for `RecoveryPoint`. Most importantly, this removes the `)` after each entry, which should not be there.
Changes from
```
RecoveryPoint [ 6538154117724707(1): 53), 6538154117724707(0): 245) ]
```
to
```
RecoveryPoint[6538154117724707(1):53, 6538154117724707(0):245]
```
=> Improve recovery point display formatting

src/wal_inspector.rs
Our WAL inspector binary currently crashes when inspecting WAL's that include the new clock tag.
This fixes the problem by using our wrapper type.
Before this PR I got:
```
thread 'main' panicked at /home/timvisee/git/qdrant/lib/collection/src/wal.rs:154:18:
Can't deserialize entry, probably corrupted WAL on version mismatch: Syntax("data did not match any variant of untagged enum CollectionUpdateOperations")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
And now I get:
```
==========================
Entry: 98
Operation: PointOperation(UpsertPoints(PointsList([PointStruct { id: NumId(98), vector: Single([0.3784349, 0.24649405]), payload: Some(Payload({})) }])))
Clock: ClockTag { peer_id: …
```
=> Make WAL inspector support operations with clock tag

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/update_handler.rs
Fixes: <https://github.com/qdrant/qdrant/issues/3585>
The current implementation of `ClockMap` fails to serialize when there's any data in it. It holds a `HashMap<Key, Clock>`, but `serde_json` cannot serialize `Key` as it must be a string.
More specifically, when we try to serialize I'm getting this error:
```
Error("key must be a string", line: 0, column: 0)
```
This PR fixes that by utilizing [`serde_with::serde_as`](https://docs.rs/serde_with/3.6.1/serde_with/attr.serde_as.html), mapping our hash map into a `Vec<(Key, Clock)>` on (de)serialization.
We now get:
```json
{"clocks":[[{"peer_id":123,"clock_id":1},152],[{"peer_id":123,"clock_id":0},246]]}
```
If we don't like the tuple representation we may also decide to implement …
=> Fix broken serialization of ClockMap

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/types.rs
Initially we wanted to keep a (value, id) composite ordering, but implementation details forced us to drop the id ordering guarantee. However, the description wasn't updated. 
This PR reflects those decisions in the description of the `order_by` parameter
=> Remove secondary ordering by id description from `order_by` parameter

lib/segment/benches/sparse_index_build.rs
The benchmark for sparse vector index build is not realistic.
The parameters are too high for the benchmark too finish quickly enough.
```
Running benches/sparse_index_build.rs (target/release/deps/sparse_index_build-a102265c83263f8d)
Benchmarking sparse-vector-build-group/build-ram-index: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 2076.8s, or reduce sample count to 10.
Benchmarking sparse-vector-build-group/build-ram-index: Collecting 100 samples in estimated 2076.8 s (100 iterations)
```
The motivation is to restore this benchmark to be able to use it easily in a later PR comparing with dev.
=> Decrease sparse vector index build bench parameters

lib/segment/benches/sparse_index_build.rs
This PR extracts the `SparseVectorIndex::open` instruction out of the benchmark loop.
The motivation is that opening the index does a bit of extra work and I/O that pollute the measurements.
=> Fix bench for sparse vector build index

lib/collection/src/lib.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/local_shard/wal_delta.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/shard.rs, lib/collection/src/update_handler.rs, lib/collection/src/wal.rs, lib/collection/src/wal_delta.rs
This adds a `RecoverableWal` type which is a `SerdeWal` with integrated `ClockMap`. Since these two types are almost always used in close proximity, this merges them together.
Writing to it ensures that we also update the clock map, without having to do this manually. This is especially useful for testing in <https://github.com/qdrant/qdrant/pull/3610>, to ensure we use the same logic in practice versus tests.
In specialized use cases we can extend this type when needed.
=> Add WAL type with integrated clock map

.gitignore, lib/segment/src/types.rs, openapi/.gitignore, tests/integration-tests.sh, tests/openapi/openapi_integration/helpers/settings.py, tests/openapi/openapi_integration/test_order_by.py, tests/openapi/openapi_integration/test_payload_indexing.py
This PR enables parsing a date like `2024-02-15T15:49:33.449041` in the same way as `2024-02-15T15:49:33.449041Z` (with or without the Z). Previously we introduced this flexibility (#3549) but it wouldn't parse the datetime if it had decimals in the timezone-less format.
Additional changes:
- capture qdrant pid via `$!` in integration tests
- fix the default openapi path when env variable is not provided (after moving this section in #3606), and add python cache to gitignore
=> Datetime parser: Parse decimals without timezone

src/actix/api/snapshot_api.rs
Do not trust file_name from the multipart upload.
=> Security patch for snapshot upload filename

lib/segment/src/index/field_index/full_text_index/inverted_index.rs, lib/segment/src/index/field_index/full_text_index/posting_list.rs
Text index posting loading is `O(N^2)`. Fixing it to `O(N)` decreases loading speed dramatically.
Test snapshot: https://storage.googleapis.com/common-datasets-snapshots/arxiv_abstracts-3083016565637815127-2023-06-02-07-26-29.snapshot
Loading logs on branch (13 seconds):
```
2024-02-14T23:42:01.549756Z  INFO storage::content_manager::toc: Loading collection: text    
2024-02-14T23:42:01.746631Z DEBUG segment::vector_storage::simple_dense_vector_storage: Segment vectors: 0    
2024-02-14T23:42:01.746657Z DEBUG segment::vector_storage::simple_dense_vector_storage: Estimated segment size 0 MB    
2024-02-14T23:42:06.448546Z DEBUG segment::vector_storage::simple_dense_vector_storage: Segment vectors: 260000    
2024-02-14T23:42:06.448572Z DEBUG …
```
=> Text field index loading optimization

Cargo.lock, lib/segment/Cargo.toml
This PR updates `rust-rocksdb` to 0.22.0.
https://github.com/rust-rocksdb/rust-rocksdb/releases/tag/v0.22.0
I am doing it manually because the release just landed and I want to make sure we test drive it ASAP.
The crate does a **massive** internal version upgrade with a ton of bug fixes, memory leak fixes and performance improvements.
From 8.1.1 to 8.10;
- https://github.com/facebook/rocksdb/releases/tag/v8.3.2
- https://github.com/facebook/rocksdb/releases/tag/v8.3.3
- https://github.com/facebook/rocksdb/releases/tag/v8.4.4
- https://github.com/facebook/rocksdb/releases/tag/v8.5.3
- https://github.com/facebook/rocksdb/releases/tag/v8.5.4
- https://github.com/facebook/rocksdb/releases/tag/v8.6.7
- https://github.com/facebook/rocksdb/releases/tag/v8.7.3
- …
=> Update rust-rocksdb 0.22

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/index/sparse_index/indices_tracker.rs
This PR optimizes sparse vector remapping which happens a lot during index build.
The remapping was introduced in https://github.com/qdrant/qdrant/pull/3230 to not use the user defined sparse dimensions in order to avoid memory issues.
The remapping takes place during:
- index rebuild
- vector search
- vector update
For those reasons it makes sense to make it as fast as possible.
This PR yields the best benefit for the build use case where every vector is remapped in a tight loop from storage.
```
sparse-vector-build-group/build-ram-index
time:   [89.460 ms 91.249 ms 93.034 ms]
change: [-12.800% -10.444% -7.8901%] (p = 0.00 < 0.05)
```
The mapped indices are persisted via the `IndiceTracker` into a JSON file. 
The `AHashmap` uses the same serde format as a …
=> Optimize sparse vector remapping

lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/update_handler.rs, lib/collection/src/wal_delta.rs
Add a cutoff clock map to our recoverable WAL structure. This defines clocks below which we cannot resolve a WAL delta.
It is similar to the truncation clock map idea we had before, but without actually linking it to truncations. After further investigation, this seems to be unnecessary, as we can derive this from the current WAL and the highest clock map.
Also:
- update the WAL delta resolve function to consider this cutoff point
- add method to update this cutoff point based on a recovery point
- renamed last seen clock map to highest clock map
We still have to:
- test this in practice: I propose to merge this so we can test this in our other [testing](https://github.com/qdrant/qdrant/pull/3610) PRs
- set this cutoff point in …
=> Add WAL cutoff clock map

lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/replica_set/clock_set.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/shard.rs, lib/collection/src/wal.rs, lib/collection/src/wal_delta.rs
A series of WAL delta resolution and recovery related tests. These are similar to what we planned in Notion.
Along with tests this PR brings a few fixes and improvements where needed.
This tests:
- WAL recovery with one operation
- WAL recovery with many operations
- WAL recovery with operations from different entrypoints intermixed
- WAL recovery with operations in a different order on different nodes
- WAL recovery error on empty recovery point
- WAL recovery error with unknown clock
- WAL recovery error with higher requested clock than on the source node
- WAL recovery error where no operation satisfies recovery point
There are more scenarios to be tested for this, but I suggest to do that in a different PR.
1. [x] Does your …
=> WAL delta resolution and recovery tests

lib/collection/src/operations/conversions.rs, lib/segment/src/payload_storage/payload_storage_base.rs, lib/segment/src/segment_constructor/segment_builder.rs
Follow up on https://github.com/qdrant/qdrant/pull/3629
Found another case where we make up non existing payload.
=> Do not make up empty payloads during optimization

lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/wal_delta.rs
Depends on: <https://github.com/qdrant/qdrant/pull/3610>
This extends WAL tests by asserting the WAL ordering property.
This property assertion makes more sense in more dynamic tests, which is what I'll be working on after this PR. But it doesn't hurt to assert our existing tests too. That's what this PR is for.
It asserts this property:
> For each operation with peer+clock tick X, all following operations having the same peer+clock must cover ticks X+1, X+2, ..., X+n in order up to the highest tick value of that peer+clock in the WAL.
The implementation may not be the most efficient ever, but in my opinion that doesn't really matter here since it's purely for testing on WALs with a sane size.
1. [x] Does your submission pass …
=> Test WAL ordering property

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/wal_delta.rs
Depends on: <https://github.com/qdrant/qdrant/pull/3615>
Adds a more extensive test to test randomized configurations and scenarios.
This tests:
- Configurations of 2 up to 10 nodes.
- Randomizes:
- Number of operations
- Entrypoint node for each operation
- Which node dies
- 25 times:
- insert random number of operations on all nodes
- kill a random node
- write a random number of operations to all alive nodes
- recover the killed node
- assert correctness
=> Test WAL delta resolution more extensively with randomized configurations

lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/sparse/src/common/sparse_vector.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_ram_builder.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
This PR optimizes the sparse vector index build by using a builder that is cheap to update.
It leverages the existing `PostingListBuilder` for convenience.
It yields a significant gains for our micro benchmark.
```
sparse-vector-build-group/build-ram-index
time:   [84.856 ms 86.303 ms 87.754 ms]
change: [-26.476% -16.670% -9.7342%] (p = 0.00 < 0.05)
```
The tests have been updated to use the new builder, one needs to perform a bit of mental gymnastic to build the forward index from the inverted ones :)
=> Optimize sparse vector index build time

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/segment/src/entry/entry_point.rs
Follow up on https://github.com/qdrant/qdrant/pull/3629 & https://github.com/qdrant/qdrant/pull/3633
This seems to be the last place where we create empty payloads according to my research.
=> Do not set empty payload when moving points

Cargo.lock, lib/collection/src/grouping/aggregator.rs, lib/collection/tests/integration/collection_restore_test.rs, lib/segment/Cargo.toml, lib/segment/src/common/utils.rs, lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/numeric_index/tests.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/query_checker.rs, lib/segment/src/types.rs
This change is extracted from a bigger PR #3637.
Drop our `struct MultiValue` and use `smallvec::SmallVec` instead. It solves the same problem (avoids heap allocation for small vectors, and uses heap allocation for larger ones), but it's upstream and is more clean to use.
=> Use SmallVec instead of MultiValue

lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/wal_delta.rs
Related: <https://github.com/qdrant/qdrant/pull/3635>, <https://github.com/qdrant/qdrant/pull/3658>
Tests are here: https://github.com/qdrant/qdrant/pull/3658/checks (tests from <https://github.com/qdrant/qdrant/pull/3635>)
Fixes shard snapshot transfer problems as shown in <https://github.com/qdrant/qdrant/pull/3635>.
With this change, we keep the WAL lock longer, not just for writing to the WAL, but also for sending the update to the update sender channel.
=> Fix shard snapshot transfer flakyness

lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/update_handler.rs
Add a `LocalShardClocks` struct holding the highest and cutoff clock maps along with their storage paths.
It is a convenience struct because these types are commonly used together. It reduces 4 fields/parameters into 1 in cases where it is used.
=> Add struct combining local shard clock maps

Cargo.lock, lib/sparse/Cargo.toml
Not sure why it was added in https://github.com/qdrant/qdrant/pull/3408/files#diff-7b0aab90d02b16dd5489af3b665000e80c5eef3d4a9c12b18441f6a1ae7de6ebL10
=> Remove unused proptest on Sparse crate

Cargo.lock, docs/redoc/master/openapi.json, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/shards/local_shard/mod.rs, lib/common/common/src/types.rs, lib/segment/Cargo.toml, lib/segment/src/common/operation_time_statistics.rs, src/actix/api/service_api.rs, src/common/metrics.rs
Part of to #2857.
<details>
<summary>Example /metrics output.</summary>
```
rest_responses_duration_seconds_bucket{method="POST",endpoint="/collections/{name}/points/payload",status="200",le="0.000001"} 0
rest_responses_duration_seconds_bucket{method="POST",endpoint="/collections/{name}/points/payload",status="200",le="0.000005"} 0
rest_responses_duration_seconds_bucket{method="POST",endpoint="/collections/{name}/points/payload",status="200",le="0.00001"} 0
rest_responses_duration_seconds_bucket{method="POST",endpoint="/collections/{name}/points/payload",status="200",le="0.00005"} 0
rest_responses_duration_seconds_bucket{method="POST",endpoint="/collections/{name}/points/payload",status="200",le="0.0001"} 0
rest_responses_duration_seconds_bucket{method="POST",endpoint="/collections/{name}/ …
```
=> Prometheus histogram support

lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/wal_delta.rs
Our recovery point was a copy of a click map, but with all clocks +1. This removes the +1, making a recovery point the same as the current clock map.
It should help reduce confusion regarding the values in the recovery point.
The existing test suite added as part of <https://github.com/qdrant/qdrant/issues/3477> proves that this change is behaving fine.
=> Remove off-by-one logic in recovery point

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/update.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
Add a new `ReplicaState::Recovery` state. We don't send updates to this state by default. It only accepts operations that had a force flag set, and rejects all others. We want to have this for shard diff transfer (<https://github.com/qdrant/qdrant/issues/3477>).
Sadly, we cannot use it directly due to backwards compatibility limits. Because of this we repurpose the current `PartialSnapshot` state, and will eventually deprecate it moving over to `Recovery`.
Here's a rough plan:
- Qdrant 1.8:
- Change `PartialSnapshot` state:
- Reject operations like before
- But allow operations if a force flag is set
- Add `Recovery` state
- Only allow operations if a force flag is set
- Cannot be used yet due to backwards compatibility
- Qdrant …
=> Add replica state: Recovery

lib/api/build.rs, lib/api/src/grpc/proto/collections_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/mod.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/shard.rs, lib/collection/src/wal_delta.rs, src/tonic/api/collections_internal_api.rs
Add an endpoint to set the WAL cutoff point of a shard on a remote node.
This will be used when integrating shard diff transfer in <https://github.com/qdrant/qdrant/pull/3509>. It prevents recovered node from resolving a diff for other nodes on old WAL data we consider garbage.
=> Add gRPC API to set shard cutoff point

tests/consensus_tests/test_collection_recovery_limits.py, tests/consensus_tests/utils.py
This should prevent flakiness in some integration tests
Related experiment: https://github.com/qdrant/qdrant/pull/3668
=> use readyz

Cargo.lock, docs/redoc/master/openapi.json, lib/collection/Cargo.toml, lib/collection/src/collection/collection_ops.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/common/eta_calculator.rs, lib/collection/src/common/mod.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/transfer/driver.rs, lib/collection/src/shards/transfer/stream_records.rs, lib/collection/src/shards/transfer/transfer_tasks_pool.rs
Closes #3433.
The shard progress state is tracked locally inside `TransferTasksPool` (aka `Collection::transfer_tasks`).
Since it's local, only the sender node shows the progress in the result of `GET collections/{name}/cluster`.
Output of `GET collections/{name}/cluster`:
```json
{"result": {
"shard_transfers": [
{
"shard_id": 1,
"from": 3351940210608703,
"to": 7522668664620757,
"sync": false,
"method": "stream_records",
↓ ↓ ↓   This field is added   ↓ ↓ ↓
"comment": "Transferring records (136000/193725), started 15s ago, ETA: 6.83s"
↑ ↑ ↑   This field is added  ↑ ↑ ↑
}
],
"peer_id": 3351940210608703,
"local_shards": [
{
"shard_id": 1,
"points_count": 178839,
"state": "Active"
}, …
],
"remote_shards": [
{
"shard_id": 1,
"peer_id": 7522668664620757,
"state": "Partial"
}, …
], …
}, … }
``` …
=> Report shard transfer progress

tests/openapi/openapi_integration/test_payload_operations.py
Test for a bug fixed in [`39b9bfd` (#3548)](https://github.com/qdrant/qdrant/pull/3548/commits/39b9bfd2618ffeef14858efae7688e9749854a33#diff-5f9b18b9d6997f1e6f9e04c7440af70ad555bb5f25a937e8044a710be58e17a4R497-R500).
=> Test payload index overwrite

Cargo.lock, docs/grpc/docs.md, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/Cargo.toml, lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/transfer/driver.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/snapshot.rs, lib/collection/src/shards/transfer/stream_records.rs, lib/collection/src/shards/transfer/wal_delta.rs, lib/storage/src/content_manager/toc/mod.rs, tests/consensus_tests/test_collection_shard_transfer.py
Depends on: <https://github.com/qdrant/qdrant/pull/3551>, <https://github.com/qdrant/qdrant/pull/3571>
This adds a new `WalDelta` shard transfer method to allow shard diff transfers. This variant remains unused for now and is hidden by default.
It adds a `transfer_wal_delta` function to actually drive such transfer from a source node.
The method currently utilizes a queue proxy shard because it already has all the necessary bits and bots implemented for transferring a WAL including all new incoming updates.
We can set a `max_ack` version now, but this only limits the logical WAL. The physical WAL probably contains important data too which we should not truncate off while we still need it for transferring the diff.
1. [x] Does your …
=> Shard diff transfer integration

docs/redoc/master/openapi.json, lib/api/src/grpc/models.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/telemetry.rs, lib/collection/src/telemetry.rs, lib/common/issues/src/issue.rs, lib/segment/src/common/operation_time_statistics.rs, lib/segment/src/telemetry.rs, lib/segment/src/types.rs, lib/storage/src/types.rs, src/common/telemetry.rs, src/common/telemetry_ops/app_telemetry.rs, src/common/telemetry_ops/cluster_telemetry.rs, src/common/telemetry_ops/collections_telemetry.rs, src/common/telemetry_ops/requests_telemetry.rs, src/schema_generator.rs
A lot of structs has a `Deserialize` derive despite we never deserialize them. 
It is inconvenient for the following reasons:
- When adding new fields to structures, we need to provide validation or reason about "what if an user pass an unexpected data?". If a struct is not `Deserialize`, a developer could search and review all the places in the code base where this specific value originates. If it's `Deserialize`, this means that data could be arbitrary. E.g., my histogram bucket merging code works fine for data being generated by my code, but it's not true for arbitrary data.
- Double the work if we decide to add a custom `impl Serialize` for some field since then we have to implement a custom `Deserialize` too.
This PR drops unused `Deserialize` impls. Precisely, the following things …
=> Drop unused Deserialize

lib/collection/src/shards/shard.rs, tests/consensus_tests/test_shard_snapshot_transfer.py, tests/consensus_tests/test_shard_wal_delta_transfer.py, tests/consensus_tests/utils.py
This adds three basic integration tests for WAL delta transfer, similar to the tests we had for shard snapshot transfer.
The tests include:
- transfer empty WAL delta between two nodes
- transfer WAL delta to recover a failed node, with concurrent upsertions
- transfer WAL delta to empty node, falling back to default transfer method
=> Add basic integration tests for WAL delta transfer

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/segment/src/common/utils.rs, lib/segment/src/json_path/mod.rs, lib/segment/src/json_path/string.rs, lib/segment/src/json_path/v2.rs
Closes #2705.
This PR lets the caller of `SegmentHolder::apply_points_to_appendable()` (renamed to `apply_points_and_reindex`) to specify whether it is OK to update non-appendable segments.
It is safe when a non-indexed field is set or removed, or when the payload is being cleared in case if there are no indices at all.
---
=> Don't rebuild HNSW when updating non-indexed fields

lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_dense_vector_storage.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
Since Rust 1.75, now we can use [return-position `impl Trait` in traits](https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html#async-fn-and-return-position-impl-trait-in-traits), so we can now turn these return signatures into `impl Iterator<...>`s
=> Chore: use `impl` instead of `dyn` in vector storage

lib/segment/src/common/utils.rs
This PR updates the behavior `set_value_to_json_map` in the following ways:
1. Do not extend arrays with `null` values.
So, `set_value_to_json_map("a[5]", json!{}, x)` will no longer produce `{"a": [null, null, null, null, null, x]}`. Instead, it will produce `{ "a": [] }`.
Reason: while this behavior is consistent with object fields, it enables an amplification attack, e.g. `path=a[9223372036854775808]` could crash the server.
2. Replace non-object values with an object.
E.g. `set_value_to_json_map("a", json!{"a": 0}, json!{"x": 1})` will produce `{"a": {"x": 1}}` instead of `{"a": 0}`.
=> Fixups in set_value_to_json_map

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/common/utils.rs, lib/segment/src/json_path/mod.rs, lib/segment/src/json_path/parse.rs, lib/segment/src/json_path/v2.rs
This PR adds an implementation for `JsonPathV2`.
This PR is based on #3696 (precisely, on the updated test cases), so ignore the first commit when reviewing this PR. I'll rebase it after merging #3696.
=> Implement JsonPathV2

Cargo.lock, Cargo.toml
This [version](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.36.0) has been released 25 days ago but was not picked up by Dependabot.
Looking at the past weeks, the weekly update quota was not reached so I do not understand why it was not proposed automatically.
Maybe the recent workspace setup has some mysterious side effects :man_shrugging:
=> Update Tokio 1.36

docs/redoc/master/openapi.json, lib/common/common/src/types.rs, lib/segment/src/common/operation_time_statistics.rs, src/actix/api/service_api.rs
An OpenAPI generator chokes on schema changes introduced in #3552, in particular, on [heterogeneous arrays in the `duration_micros_histogram` field](https://github.com/qdrant/qdrant/commit/ff9e3a6ab98c72971b3ad2851227a953e1c92972#diff-1cb4c2c4798cfa586db32c8c5968891f1306c75861d5ede89241be8bb7bedc8fR9452-R9467).
The error message is:
```console
$ docker run --user 1000:100 --rm -v /run/user/1000/tmp.nu7jls5JNY/pydantic_openapi_v3/scripts/output:/generator-output -v /run/user/1000/tmp.nu7jls5JNY/pydantic_openapi_v3/openapi-qdrant.yaml:/local/openapi.yaml openapitools/openapi-generator-cli:v5.1.1 generate -g python --global-property debugModels=true -o /generator-output -i /local/openapi.yaml
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with …
```
=> Don't produce histograms in /telemetry JSON response

lib/api/src/grpc/conversions.rs, lib/collection/src/operations/types.rs, lib/segment/benches/vector_search.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/fixtures/payload_fixtures.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs, lib/segment/src/vector_storage/simple_dense_vector_storage.rs, lib/segment/tests/integration/fixtures/segment.rs
This PR expands the usage of the `DenseVector` alias where possible.
This is a cleanup phase before possibly introducing `MultiDenseVectors` in the future.
=> Use DenseVector alias where possible

tests/openapi/openapi_integration/test_snapshot.py
Fixes: <https://github.com/qdrant/qdrant/issues/3627>
Tested in <https://github.com/qdrant/qdrant/pull/3707> running it 100s of times: https://github.com/qdrant/qdrant/actions/runs/8078479540/job/22070892084?pr=3707
Our snapshot tests did not clean up snapshot files properly.
=> Fix flaky invalid URI snapshot test

lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/appendable_mmap_dense_vector_storage.rs, lib/segment/src/vector_storage/async_raw_scorer.rs, lib/segment/src/vector_storage/memmap_dense_vector_storage.rs, lib/segment/src/vector_storage/mmap_dense_vectors.rs, lib/segment/src/vector_storage/mod.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/tests/async_raw_scorer.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
This PR is a bunch of mechanical renaming for dense storage related types and files.
The motivation is that we want to add soon new types of storages for multi-vector points, so it is better to makes things explicit.
=> Clearer names for dense storage implementations

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/index/field_index/full_text_index/inverted_index.rs, lib/segment/src/index/field_index/full_text_index/posting_list.rs, lib/segment/src/index/field_index/full_text_index/postings_iterator.rs
Compressing postings list for text field index.
Compression is implemented using `bitpacking` crate: https://github.com/quickwit-oss/bitpacking. Compression works for immutable state only. Mutable state uses old postings list implementation.
Because `bitpacking` compresses only fixed-len chunks (128 of `u32` in this PR), compressed posting list is divided into chunks, each chunk is compressed separately and compressed data is flattened on one large collection.
Because `bitpacking` provides only pack/unpack methods, we have to decompress one chunk is we want to check if value is presented in compressed posting list. For intersection of posting list there are special helping visitor, who reuse decompressed chunks and shorten search ranges.
RAM difference was tested on …
=> Text index inverted index compression

tests/storage-compat/README.md, tests/storage-compat/storage-compatibility.sh
So far our strategy for testing storage compatibility has been to refresh from time to time a set of archives containing data and snapshots and making sure that the current `dev` branch understand those.
This PR proposes to make the contract clearer by only pulling the archives from the master branch during tests.
This makes sure we have a stable point of reference.
=> Enforce that storage compatibility validates master data on dev

config/config.yaml, lib/collection/src/collection/mod.rs, lib/collection/src/collection/snapshots.rs, lib/collection/src/common/mod.rs, lib/collection/src/common/snapshots_manager.rs, lib/collection/src/operations/shared_storage_config.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/src/content_manager/snapshots/mod.rs, lib/storage/src/content_manager/toc/snapshots.rs, lib/storage/src/types.rs, lib/storage/tests/integration/alias_tests.rs, src/common/snapshots.rs
This PR is a first step in an attempt to fix https://github.com/qdrant/qdrant/issues/3324. 
To be able to add S3 support and other storage back ends later I defined a trait that will contain all needed methods to handle created snapshots. I took a simplifying assumption that the snapshots will first be created in a temp local place and after the snapshotting is completed we will move the snapshot and checksum.
After S3 support is added, it should be straight forward to implement support for additional storage back ends, the only needed action being implementing the trait for the new type. 
To keep the PR small and easy to review, currently it only handles create_snapshot,delete,list (collection/full/shard). If the direction is good others could be implemented in subsequent PRs without …
=> Snapshot store

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/shard.rs, lib/collection/src/update_handler.rs, lib/collection/src/wal.rs, lib/collection/src/wal_delta.rs, src/wal_inspector.rs
Minor fixes/improvements/cleanups for diff transfer related code.
Tracked in: #3477
=> Diff transfer improvements

docs/grpc/docs.md, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/replica_set/update.rs, lib/collection/src/shards/transfer/mod.rs
Depends on: <https://github.com/qdrant/qdrant/pull/3719>
Add `UpdateStatus::ClockRejected` so that we can notify the operation sender of the operation being rejected due to an outdated clock.
=> Add update response status for clock rejection

docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/collection/src/operations/conversions.rs, lib/segment/src/data_types/order_by.rs
OrderBy tracked in #3521 
Right now we accept integers in gRPC, but not in REST, this adds integer variant to the `StartFrom` interface
=> OrderBy: Allow integer in `StartFrom`

lib/collection/src/collection_manager/segments_updater.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/json_path/mod.rs, lib/segment/src/json_path/v2.rs, tests/openapi/openapi_integration/test_payload_operations.py
* Use new `safe_to_set`/`safe_to_remove` functions. The new implementation will make features introduced in #3611 and #3548 to play well with each other.
* Fix `PayloadIndex::assign` by using `safe_to_set` check here.
* Make `JsonPathV2::value_remove()` idempotent by prohibiting deleting paths like `a[0]`.
This PR is based on #3709.
=> Use new safe_to_set/safe_to_remove functions

tests/consensus_tests/test_shard_wal_delta_transfer.py
Add a consensus test that recovers a chain of nodes.
It does:
- create cluster of 5 nodes: A, B, C, D, E
- create collection with 1 shard, replicated on all of them
- start insertions on all 5 nodes
- Kill node E
- Kill node D a bit later
- Restart node D and E
- Recover D from A
- Recover E from D (chain)
I thought it may be interesting to sweep all nodes, so all of them are killed, not just the two last ones. But this may already be good enough.
=> Add WAL delta consensus test for recovering chain of nodes

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/src/operations/cluster_ops.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/shards/transfer/mod.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, src/common/collections.rs
Related to: <https://github.com/qdrant/qdrant/pull/3703#discussion_r1507431125>
When restarting a shard transfer, set `sync=true` if the old transfer was also using sync.
This should have been part of <https://github.com/qdrant/qdrant/pull/3703>, but I accidentally merged too early.
=> When restarting shard transfer, keep sync if old transfer was sync

docs/grpc/docs.md, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/replica_set/clock_set.rs, lib/collection/src/shards/replica_set/update.rs, lib/collection/src/shards/test.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/wal.rs, lib/collection/src/wal_delta.rs
This PR tweaks WAL diff transfer related logic:
=> Logic tweaks for WAL diff shard transfer

lib/api/src/grpc/conversions.rs, lib/api/src/grpc/validate.rs, lib/collection/src/operations/conversions.rs
We were missing to include `datetime_range.is_none()` in the validation of FieldCondition, which caused any field condition with only a datetime range to fail validation, as if no condition was set.
=> Fix: Validate `datetime_range` in `FieldCondition` validation

.gitignore, tests/storage-compat/README.md, tests/storage-compat/full-snapshot.snapshot.gz, tests/storage-compat/gen_storage_compat_data.sh, tests/storage-compat/storage-compatibility.sh, tests/storage-compat/storage.tar.bz2
`git lfs` is completely nontransparent, non-intuitive to work with and causes errors.
(current files in master branch are modified without any commits to master)
This PR replaces `git lfs` with plain simple s3 storage.
Pros:
- Straightforward
- Very clear what actually happens, impossible to accidentally break
- no need to install any extra tools, just use `wget`
- very easy to see the full history
Cons:
- requires auth access to upload storage versions
=> Backward compatibility via s3

lib/collection/src/common/batching.rs, tests/openapi/openapi_integration/test_basic_retrieve_api.py
This PR fixes a panic reported in #3737. Basically, current qdrant crashes on empty batch searches like this
```
curl -X POST http://localhost:6333/collections/NAME/points/search/batch -d '{"searches": []}'
```
due to `.next().unwrap()` being used on a iterator.
Closes #3737.
=> Fix batch_requests

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/api/build.rs, lib/common/common/Cargo.toml, lib/common/common/src/defaults.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/consensus/persistent.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc/mod.rs, lib/storage/src/types.rs, src/consensus.rs, src/main.rs
Add peer metadata to consensus. Peers may propose new metadata once it becomes outdated.
At this time it holds the Qdrant version number. We may add more fields in the future.
Knowing the version number of all nodes is useful for feature gating. It may prevent us a lot of headaches in the future.
=> Add peer metadata to consensus, tracking Qdrant versions

tests/consensus_tests/test_shard_wal_delta_transfer.py
assert condition tends to log the whole comparing structure, which generates too much logs
=> avoid assert data1 == data2

docs/redoc/master/openapi.json, openapi/openapi-shard-snapshots.ytt.yaml, openapi/openapi-snapshots.ytt.yaml, src/actix/api/snapshot_api.rs
Endpoints
```
/collections/{collection_name}/snapshots/recover
/collections/{collection_name}/shards/{shard_id}/snapshots/recover
```
have `checksum` parameter as in a JSON body, not in query path. This PR removes non-exist query path parameters.
=> Remove checksum path parameter for snapshot recovery in openapi

lib/collection/src/collection/mod.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
- Add `RecoveryToPartial` operation (that is, basically, an alias for `SnapshotRecovered`)
- Slightly extend `SnapshotRecovered`/`RecoveryToPartial` handling...
- so that both operations switch to `Partial` from *either* `PartialSnapshot` *or* `Recovery`
- this is necessary, because *later*, when upgrading cluster from 1.8.* to 1.9.*, it is possible
- for 1.8.* nodes to have a replica in `PartialSnapshot` state, and receive `RecoveryToPartial` operation
- for 1.9.* nodes to have a replica in `Recovery` state, and receive `SnapshotRecovered` operation
- some other options are possible as well, but allowing switching from both states seems like a simple and safe solution
- Also added `Collection::set_shard_replica_state_impl` method …
=> Add `ShardTransferOperations::RecoveryToPartial`

lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/transfer/driver.rs, lib/collection/src/shards/transfer/snapshot.rs, lib/collection/src/shards/transfer/wal_delta.rs
Add basic progress reporting for WAL delta and snapshot transfer.
More specifically: enable reporting on how many records are being transferred (and how many to transfer in total) while the queue proxy is transferring updates to a remote shard.
This is not yet reported, and may be done in a separate PR later:
- process of resolving WAL delta
- snapshot creation
- snapshot transfer
- snapshot recovery
Exposing progress like this will help us improve our tests, and assertions we make in it.
=> Report basic progress for WAL delta and snapshot transfer

lib/collection/src/shards/queue_proxy_shard.rs, tests/consensus_tests/test_shard_wal_delta_transfer.py, tests/consensus_tests/utils.py
Depends on: <https://github.com/qdrant/qdrant/pull/3769>
We did depend on log messages to assert various WAL delta transfer states. It appears to be problematic, and does not work with <https://github.com/qdrant/qdrant/pull/3753>.
<https://github.com/qdrant/qdrant/pull/3769> exposes WAL delta transfer progress in the collection cluster output. These tests now depend on that instead.
I was not able to replace all assertions through this new exposed state, in which case I left a comment.
=> For WAL delta test assertions, use transfer status rather than logs

tests/consensus_tests/utils.py
context: https://github.com/qdrant/qdrant/pull/3733
This PR changes the consensus tests infrastructure to capture the logs from `stdout` instead of `stderr`.
After merging this, the logs will be available via downloading the archives again.
=> Consensus tests capture stdout

lib/segment/src/json_path/parse.rs, tests/openapi/openapi_integration/test_payload_indexing.py
Initially, the new JSON path implementation was rejecting identifiers starting with digits, to match up with `jq` and JavaScript syntax. However, some users reported that they rely on numerical paths which are rejected starting at v1.8.0.
This PR does the following change in accepted syntax for unquoted identifiers:
```diff
-First symbol is a letter, an underscore, or a hyphen.
+First symbol is a letter, a digit, an underscore, or a hyphen.
The rest consists of letters, digits, underscores, and hyphens.
```
=> Allow paths starting with numbers

Cargo.lock, Cargo.toml, src/actix/certificate_helpers.rs, src/actix/mod.rs
There are numerous breaking changes which made this rather tedious TBH
I followed the official [migration guide](https://github.com/rustls/rustls/releases/tag/v%2F0.22.0).
=> Update Rustls 0.22

Cargo.toml, src/tonic/api_key.rs, src/tonic/mod.rs, tests/api_key/test_grpc.py, tests/integration-tests-api-key.sh
Before implementing support for `jwt` decoding in the grpc middleware, I think we can clean it up by using the [`filter`](https://docs.rs/tower/latest/tower/filter/index.html) feature from `tower`.
It clears up a bit of boilerplate to keep only what we are interested in, which is validation.
I've tested the changes, and the resulting error message is kept exactly the same, so I have validated that these changes are merely an implementation detail:
```
<_InactiveRpcError of RPC that terminated with:
status = StatusCode.PERMISSION_DENIED
details = "Invalid api-key"
debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Invalid api-key", grpc_status:7, created_time:"2024-03-06T15:18:26.859917-03:00"}"
>
```
=> Refactor: use `FilterLayer` from `tower` in api-key middleware

lib/segment/src/vector_storage/memmap_dense_vector_storage.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs
This time only reporting about useless `!vec`.
=> Fix Clippy 1.77

lib/segment/src/index/hnsw_index/graph_links.rs
This PR fixes https://github.com/qdrant/qdrant/issues/3802 with debug assertions, introduced here https://github.com/qdrant/qdrant/pull/3806.
Structure of hnsw links file:
```
1. Header. 4 u64 values (alignment 8 bytes)
2. Reserved bytes for extending header, 32 bytes
3. An array of u64 values describes the size of each HNSW level (alignment 8 bytes)
4. An array with reindexing point id into the internal index, u32 with alignment 4 bytes
5. An array of all flattened links data, u32 with alignment 4 bytes
6. An array of points offset in flattened links data, u64 with alignment 8 bytes
```
All parts definition with the calculation of ranges inside file you can find in `GraphLinksFileHeader` methods:
https://github.com/qdrant/qdrant/blob/master/lib/segment/src/index/hnsw_index/graph_links.rs# …
=> Fix alignment in graph links file

tests/storage-compat/storage-compatibility.sh
This PR fixes https://github.com/qdrant/qdrant/pull/3807
It appears the storage compatibility tests did **not** detect when collections were not loaded properly.
```
2024-03-12T15:20:48.305815Z ERROR qdrant::startup: Panic occurred in file lib/segment/src/index/hnsw_index/graph_links.rs at line 73: boom
2024-03-12T15:20:48.310643Z ERROR collection::shards::replica_set: Failed to load local shard "./storage/collections/test_collection_product_x64/0", initializing "dummy" shard instead: Service internal error: Can't join segment load thread: TypeId { t: 337271291176647618489964333718931667905 }
```
In case of loading issue, we would simply setup a dummy shard and continue with the remaining collections.
The server would then be operational to serve data for other collections.
To detect …
=> Detect malformed collection during storage compatibility

tests/consensus_tests/test_peer_snapshot_bootstrap.py, tests/consensus_tests/test_triple_replication.py, tests/consensus_tests/utils.py
Hi @agourlay ! Following on the discussion on #2610 :
Would something like this work in this case? Just a simple mapping of the already allocated ports that is accessed whenever we allocate some random port and cleaned whenever the process is killed. This is meant to address the issue only on the test side.
One thing that I'm not sure about is that you mentioned `This list would have to be threadsafe and properly cleaned up when servers are shutdown.`. From what I see, the tests are run sequentially right now or is there some part that I'm missing and could mess the mapping up?
Thanks in advance for your input!
=> Managing assigned ports in the consensus tests #2610

tests/storage-compat/README.md, tests/storage-compat/storage-compatibility.sh
This PR updates our storage compatibility test to `v1.8.1`.
I have generated the data from master and uploaded it to our GCP bucket.
The storage archives contains [two new collections](https://github.com/qdrant/qdrant/pull/3715) with various mmap configuration.
EDIT: I also added the support for testing against the last minor and patch version,
=> Update storage compatibility version

lib/common/memory/src/mmap_ops.rs, lib/segment/src/index/hnsw_index/graph_links.rs
This PR fix data alignment issue in `GraphLinksConverter::serialize_to` that was discovered in #3802.
It also adds a few asserts to the `transmute_from_u8*` functions, to try to catch similar alignment mismatches in the future.
Fixes #3802. Includes #3807.
=> Fix `GraphLinksConverter::serialize_to` data alignment issues

src/common/health.rs, src/main.rs
Try to make `/readyz` check more reliable after cluster upgrade incident last week.
__TODO:__
- currently, the node may report "ready" right after startup, because for a short moment before *joining* the cluster, it considers itself the *only* node in the cluster, and `/readyz` instantly returns "ready" in that case
=> Try to make `/readyz` check more reliable

tests/consensus_tests/fixtures.py, tests/consensus_tests/test_shard_wal_delta_transfer.py, tests/consensus_tests/utils.py
Attempts to improve reliability for WAL delta tests by increasing the throttling interval.
It now hosts less concurrent insertions during tests - 10x less than before - which caused some flakyness on busy systems.
After merging this, I'll improve upon <https://github.com/qdrant/qdrant/pull/3723>.
=> Attempt to improve WAL delta reliability: more throttling

tests/consensus_tests/test_shard_wal_delta_transfer.py
Depends on: <https://github.com/qdrant/qdrant/pull/3790>
Add a consensus test that confirms that aborting and restarting a WAL delta transfer works.
This consensus test:
- Measures WAL delta recovery baseline time
- Kills the last node
- Starts WAL delta recovery, but aborts it in the middle
- Retries WAL delta recovery
- Asserts that all data is still intact
=> Add WAL delta consensus test for aborting and retrying diff transfer

lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/update_handler.rs
Prevent having a lot of IO writes by flushing clock maps constantly. Only write to disk if they have changed.
Note that I didn't check how this affects IO on syscall level.
=> Only flush clock maps to disk if they have changed

lib/segment/src/spaces/simple.rs
This PR makes the dependency on dot product more explicit and removes the code duplication.
=> Remove duplication in cosine similarity

Cargo.lock, Cargo.toml, lib/rbac/src/jwt.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/toc/point_ops.rs, src/actix/api/count_api.rs, src/actix/api/discovery_api.rs, src/actix/api/recommend_api.rs, src/actix/api/retrieve_api.rs, src/actix/api/search_api.rs, src/actix/api/update_api.rs, src/actix/auth.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs, src/tonic/auth.rs
Tracked by #3777 
There are some claims, like `filter` and `payload` which need to access the deserialized structures from `Filter` and `Payload`. To avoid code duplication in both tonic and actix layers, we'll handle these cases in the table of contents.
- Extracts claims from the extensions of the request in tonic and actix interfaces
- Routes them into table of contents
=> RBAC: Route `Claims` into `TableOfContent` for points API

lib/collection/src/collection/snapshots.rs, lib/collection/src/operations/types.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/snapshots/mod.rs, tests/openapi/openapi_integration/test_snapshot.py
Fix arbitrary path traversal in our full snapshot API.
We now enforce snapshot files to be within their snapshot directories.
A simple integration test is added to assert this behavior.
=> Fix arbitrary path traversal vulnerability in full snapshot REST API

src/common/collections.rs, src/tonic/api/collections_api.rs
Small refactoring.
These two methods (used in Tonic):
- `tonic::api::collections_api::CollectionsService::list_aliases`
- `tonic::api::collections_api::CollectionsService::list_collection_aliases`
are similar to these helper methods (used in Actix):
-  `common::collections::do_list_aliases`
-  `common::collections::do_list_collection_aliases`
This PR drops the former in favor of the latter, so now the same helper methods are used both in Tonic and Actix. This change would make RBAC checking a bit cleaner.
=> Use common helpers in tonic collections API

Cargo.lock, lib/rbac/Cargo.toml, lib/rbac/src/jwt.rs, lib/rbac/src/lib.rs, lib/segment/src/types.rs, lib/storage/src/content_manager/claims.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc/point_ops.rs, src/actix/helpers.rs
Tracked by #3777.
Depends on #3801.
In this PR changes are made for the Points API:
- The new claim `collections` are checked.
- The contents of the new `payload` claim is added to the filters.
- For the payload editing API (e.g. set payload/delete payload), added stubs that reject this action when the `payload` claim is present. Later we could implement query rewrite/vaidation for them.
=> Implement `collection` claims for points API

lib/collection/src/recommendations.rs, lib/segment/benches/vector_search.rs, lib/segment/src/common/mod.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/segment.rs
This PR removes the manual `to_vec_ref` converter to use the existing standard `From` implementation instead.
=> Remove duplicated VectorRef conversion

lib/storage/src/content_manager/consensus_manager.rs
Enable updating the peer metadata through consensus if it is outdated.
The groundwork for this was already implemented in <https://github.com/qdrant/qdrant/pull/3702>. But we postponed enabling it to 1.9 for backwards compatibility.
To prevent spamming consensus I've added a cooldown, limiting these updates to one per minute.
=> Update peer metadata through consensus for 1.9

docs/grpc/docs.md, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/update.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
Related: <https://github.com/qdrant/qdrant/pull/3848>
Deprecate the `PartialSnapshot` state and change both the snapshot and WAL delta transfers to use the `Recovery` shard replica set state instead.
This is compatible with nodes running 1.8 and up.
=> Switch to Recovery state, deprecated PartialSnapshot, for Qdrant 1.9

lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, lib/storage/src/content_manager/toc/transfer.rs
Related: <https://github.com/qdrant/qdrant/pull/3847>
Deprecate the `SnapshotRecovered` consensus call and change both the snapshot and WAL delta transfers to use the `RecoveryToPartial` consensus call instead.
This is compatible with nodes running 1.8 and up.
=> Switch to RecoveryToPartial, deprecated SnapshotRecovered in consensus, for Qdrant 1.9

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/transfer/driver.rs, lib/collection/src/shards/transfer/mod.rs, lib/common/common/src/defaults.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/toc/transfer.rs, tests/consensus_tests/test_shard_wal_delta_transfer.py, tests/consensus_tests/utils.py
In 1.8 we introduced WAL delta transfer which could fall back to the default shard transfer method. It was implemented in quite a hacky way.
This PR makes the fallback happen through consensus, which has a few advantages:
- we now properly clean up the old transfer and prepare the new one, preventing unexpected state issues
- all nodes are properly aware of the current shard transfer state (and method)
The WAL delta fallback test has been updated to assert we properly fall back.
=> Make shard diff transfer fallback to different method through consensus for 1.9

Cargo.lock, config/config.yaml, lib/collection/Cargo.toml, lib/collection/src/collection/mod.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/channel_service.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/consensus/persistent.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/types.rs, src/main.rs
Depends on: <https://github.com/qdrant/qdrant/pull/3792>
Enable WAL delta transfer by default for automatic shard recovery.
As extra safety measure I've added a check to ensure that all nodes are running 1.8+.
We only detect version 1.9 and higher through consensus. I still decided to keep the check at 1.8 and up because that's the first true version in which WAL delta transfer was available.
=> Use WAL delta transfer by default for shard recovery for 1.9

lib/api/src/rest/schema.rs, lib/collection/src/collection/point_ops.rs, lib/collection/src/collection_manager/collection_updater.rs, lib/collection/src/grouping/builder.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/conversions_rest.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/operations/types.rs, lib/collection/tests/integration/lookup_test.rs, lib/collection/tests/integration/multi_vec_test.rs, src/actix/api/retrieve_api.rs, src/schema_generator.rs, src/tonic/api/points_common.rs
Next step after https://github.com/qdrant/qdrant/pull/3829.
`Record` type has `Vector` inside. This PR decouples `Record` into REST and internal types. Rest one uses rest vector, internal `Record` uses internal vector.
=> Rest decouple collection record type

src/actix/helpers.rs
This PR adds logging to help investigate https://github.com/qdrant/qdrant/issues/3875
The REST API for snapshot operations does not use the `process_response` infrastructure since it was changed to be cancel-safe.
The new `time_impl` helpers do not contain the usual error logging on internal server error.
This PR adds it.
=> Log errors for snapshot operations

lib/collection/src/shards/mod.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/update_handler.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, src/settings.rs
Found an unnecessary `allow` so I decided to do a quick pass on the codebase.
=> Remove unecessary Clippy allows

lib/collection/src/operations/types.rs, lib/common/common/src/defaults.rs
Before this PR our development branch was rocking version 0.11.1 for a long while. In this PR I propose to assign an up-to-date development version to our development branch branch to closely match our release versions.
Please feel free to comment here if there are any questions/concerns.
My motivation for this is as follows: We've just implemented tracking of node versions in consensus (<https://github.com/qdrant/qdrant/pull/3702>, <https://github.com/qdrant/qdrant/pull/3792>, <https://github.com/qdrant/qdrant/pull/3800>). This allows version based gating for new features. In fact, that is already used for WAL delta transfer. Because of that our development version must have an up-to-date version number too, otherwise version gated features are not properly tested. Also, if an end user …
=> Configure development version on dev branch

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Part of <https://github.com/qdrant/qdrant/pull/3877>.
Change our development version to `1.9.0-dev`. We're confident the current development branch will be released as the next minor version in about two weeks.
=> Bump dev to 1.9.0-dev

lib/collection/src/operations/cluster_ops.rs, lib/storage/src/content_manager/claims.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/dispatcher.rs, lib/storage/tests/integration/alias_tests.rs, src/actix/api/collections_api.rs, src/actix/api/shards_api.rs, src/common/collections.rs, src/common/points.rs, src/consensus.rs, src/migrations/single_to_cluster.rs, src/tonic/api/collections_api.rs, src/tonic/api/collections_common.rs, src/tonic/api/collections_internal_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs
Tracked in #3777.
This PR adds RBAC checks for collections and shard APIs.
For `GET /aliases` and `GET /collections/{name}/aliases`, an alias is visible when both the collection name and the alias is listed in the `collections` claim.
This PR drops `claims` argument for `do_create_index_internal()` and `do_delete_index_internal()`. Reason:
- For user-facing APIs, it's checked in `common::points::do_delete_index()`→`submit_collection_meta_op()`.
- For internal APIs, we don't need to check it.
=> RBAC support for collections API

lib/collection/src/shards/local_shard/clock_map.rs, lib/collection/src/wal_delta.rs
Add a test asserting that WAL delta resolution works when there is gaps in our WAL clocks. It extends and improves our existing WAL delta code.
We normally don't expect this situation, but it's good to support it in case it ever happens unexpectedly.
As a bonus, this improves our WAL delta resolution logic. It appeared that the resolved delta included an extra and obsolete record if our records have any gap. The improvement prevent this, so that a resolved delta exclusively contains records that are not in the target shard yet. Note that the previous version is perfectly sound in terms of consistency, so we don't have to worry about this in the 1.8 releases.
The test function to assert WAL delta ordering got a new parameter to …
=> Test WAL delta resolution with gaps, improve resolution logic

docs/redoc/master/openapi.json, lib/collection/src/shards/transfer/mod.rs
Track: <https://github.com/qdrant/qdrant/issues/3477>
Expose the WAL delta transfer in our OpenAPI specification. It was hidden before, but it is totally fine for users to explicitly select it if desired.
Our gRPC specification already exposes it because we cannot hide it there.
=> Expose the WAL delta transfer method in our OpenAPI specification

lib/rbac/src/jwt.rs, src/common/auth.rs, tests/consensus_tests/test_jwt_validation.py
We might want to check for multiple keys and values. The example would be is that we want to check for the user exists AND they have required access level
=> [RBAC] allow multiple mathes in jwt validation check

lib/rbac/src/access_control/access_token.rs, lib/rbac/src/access_control/collection_access_token.rs, lib/rbac/src/access_control/error.rs, lib/rbac/src/access_control/mod.rs, lib/rbac/src/lib.rs
- Introduces AccessToken data structure, which should be used to
- check claims inside our code
- decouple Claims (interface structure) from check implementation
- Ensure that conditions are validated
=> [RBAC] Access control inside table of content

lib/storage/src/content_manager/snapshots/mod.rs, lib/storage/src/content_manager/snapshots/recover.rs, src/actix/api/cluster_api.rs, src/actix/api/retrieve_api.rs, src/actix/api/service_api.rs, src/actix/api/snapshot_api.rs, src/actix/helpers.rs, src/common/collections.rs, src/tonic/api/snapshots_api.rs
This PR refactors actix endpoints to use `helpers::{time, time_or_accept, time_or_accept_with_handle}` more, instead of calling `process_response` manually.
The updated code is more concise, particularly because of using `?` instead of more verbose `match`es.
A new helper function `time_or_accept_with_handle` is added, for handlers consisting of two stages: mandatory (various checks), and optional (runs in a background if `?wait=false`).
=> Refactor actix response handlers

Cargo.lock, Cargo.toml, lib/storage/Cargo.toml, lib/storage/src/content_manager/toc/collection_meta_ops.rs
https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#support-for-recursion-in-async-fn
Blocked by the update of the base docker container version.
=> Native async recursion with Rust 1.77

lib/storage/src/content_manager/toc/collection_meta_ops.rs
There were several reports, that it is impossible to create collection, even if it doesn't exist.
This change doesn't eliminate the root problem (if any), but allows to simply re-try deletion even if the collection is not loaded.
=> make sure that collection files are deleted even if the collection is not loaded

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/collection/collection_ops.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
Currently, when "remove shard replica" consensus operation is processed, we don't handle shard transfers related to the removed replica in any way.
This PR:
- cancels all shard transfer tasks and then remove all shard transfers related to the removed shard
- when processing `ShardTransferOperations::Abort`, check all preconditions more carefully, before changing local state:
- do *not* change replica state to `Dead`, if replica does not exist (happens if replica was deleted, and then transfer was aborted)
- do *not* remove replica, if shard transfer does not exist (could happen due to `Option::map_or` call)
- only revert local proxy shard, if transfer *exists* (it was possible to revert wrong shard if multiple `Abort`s were sent)
So far, @generall and I decided to *not* version gate these …
=> Cancel shard transfers when shard is deleted

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/src/operations/cluster_ops.rs, lib/collection/src/operations/conversions.rs, lib/common/common/src/validation.rs, tests/consensus_tests/test_collection_shard_transfer.py
Tracked in: https://github.com/qdrant/qdrant/issues/3409
This PR adds a new `AbortShardTransfer` struct, to be used by the `AbortTransfer` operation.
=> Removes method from abort shard transfer operation

lib/segment/src/segment.rs, lib/segment/src/spaces/simple.rs, lib/segment/src/spaces/simple_avx.rs, lib/segment/src/spaces/simple_neon.rs, lib/segment/src/spaces/simple_sse.rs, lib/segment/src/spaces/tools.rs
Preprocessing or normalizing vectors should be stable. Meaning that preprocessing or normalizing a second time should give the exact same values.
We need stability because transferring points to another shards with stream records transfer (and SyncPoints) normalizes vectors again. Their values must remain exactly the same.
This PR makes renormalization stable by using 1e-6 as normalization threshold. It adds a test to assert it works as expected for our use case.
=> Stabilize vector renormalisation

lib/storage/src/content_manager/claims.rs, lib/storage/src/content_manager/snapshots/mod.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/content_manager/toc/mod.rs, lib/storage/src/content_manager/toc/point_ops.rs, lib/storage/src/content_manager/toc/snapshots.rs, lib/storage/src/dispatcher.rs, lib/storage/src/rbac/access.rs, lib/storage/src/rbac/mod.rs, lib/storage/src/rbac/ops_checks.rs, src/actix/api/cluster_api.rs, src/actix/api/service_api.rs, src/actix/api/snapshot_api.rs, src/common/auth/claims.rs, src/common/auth/jwt_parser.rs, src/common/auth/mod.rs, src/common/collections.rs, src/common/snapshots.rs, src/migrations/single_to_cluster.rs, src/tonic/auth.rs
Part of #3777.
This PR introduces the concept of `CollectionPass`.
It is used to get `Collection` object from `TableOfContent`.
Instead of getting collection by raw string name, now we are forced to perform validation check using `Access` object.
```rust
// Old way:
let collection = toc.get_collection(collection_name /*: &str */)?;
// New way:
let collection_pass = access.check_whole_collection_rights(collection_name)?;
let collection = toc.get_collection_by_pass(&collection_pass /*: &CollectionPass */)?;
```
Additionally, this PR moves `Access` object deconstruction into its methods so the switch to the new claims schema would be easier.
There are still a few places where the old approach is used, we could cover them after updating the claims schema.
=> RBAC: introduce CollectionPass

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
A new patch version for Qdrant, [fixing](https://github.com/qdrant/qdrant/pull/3948) a nasty bug that could corrupt the consensus WAL bringing down a cluster.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/3868>.
=> Bump version to 1.8.4

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/update_handler.rs
Add a 'grey' collection status color to identify:
- pending optimizations
- but no optimizations are running
This happens while an instance is restarted while optimizations are ongoing. In previous versions we triggered optimizations on start, but we don't do this anymore to prevent OOM crash loops. A new update operation is required to trigger optimizations once more.
Currently we just show a green collection status, which may be confusing. This grey status should help identify the above described situation, so that users can act accordingly.
Due to compatibility reasons the grey status is not used right away. It is not compatible with our current clients. Until that is possible, we set an optimization error instead:
In Qdrant 1.10 we'll actually set the grey status, see the task below. …
=> Add grey collection status

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/config.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/shard.rs, src/main.rs, tests/consensus_tests/test_snapshot_consistency.py
Non-blocking collection and segment snapshots, by utilizing segment proxies.
While it already significantly decreases the likeliness of blocking significantly, it may not be fully gone yet.
I've added a few segment holder functions to make this happen in a controlled manner:
- `proxy_all_segments_and_apply`: proxy all segments, run a closure on them, and unproxy all
- `proxy_all_segments`: proxy all segments
- `unproxy_all_segments`: unproxy all segments and propagate changes
Snapshotting now simply calls `proxy_all_segments_and_apply` to snapshot each segment individually in a non-blocking manner.
The consensus tests asserts data consistency when upsertions are happening while snapshots are made. It helps detecting unsoundness with proxying and propagating changes because this is error …
=> Non-blocking snapshots

.github/workflows/dev-docker-image-build.yml
Because docker throws errors if we call the delete command without any container/volume IDs.
```sh
Buildx containers to delete:  
Buildx containers to delete:  
Container name cannot be empty
Error: Process completed with exit code 1.
```
=> fix: Dev build workflow

lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/rbac/mod.rs, src/actix/auth.rs, src/actix/helpers.rs, src/common/auth/jwt_parser.rs, src/common/auth/mod.rs, src/tonic/auth.rs
- Respond with `401 Unauthorized` for lacking or failed authentication credentials, and with `403 Permission Denied` when not enough permissions.
- Improve wording (see https://github.com/qdrant/qdrant/pull/3941#pullrequestreview-1976695179, https://github.com/qdrant/qdrant/pull/3941#pullrequestreview-1976709335)
=> RBAC: Improve errors

Cargo.toml, lib/storage/src/content_manager/consensus_manager.rs, src/consensus.rs
Consensus Operations might fail at any time, and this is Ok, consensus is design to live with that assumption.
We, however, prevented sent of new messages from repeating if one of them is failed first time.
This created crashloop in out brand new diff shard transfer logic, because we tried to send the same operation over and over, which didn't actually happen because it was already registered and never removed from registry.
=> remove consensus op from await queue if it timed out

lib/segment/benches/vector_search.rs, lib/segment/src/common/mod.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/fixtures/payload_fixtures.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs, lib/segment/src/vector_storage/query_scorer/mod.rs, lib/segment/src/vector_storage/tests/async_raw_scorer.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs, lib/segment/src/vector_storage/tests/test_appendable_dense_vector_storage.rs, lib/segment/tests/integration/main.rs, lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
This PR integrates the `MultiVector` support at the segment level.
It was tested using a version of `filtrable_hnsw_test.rs` adapted for `Multivectors`.
Two insights:
1. the accuracy of HNSW degrades as the number of vectors per multi-vectors increases
* most likely due to the random data
* could be validated against real data set  
2. the scoring gets expensive as the number of vectors per multi-vectors increases
=> Integrate Multivector at segment level

src/actix/api/snapshot_api.rs
- Prevent security risk of uploading snapshots into collection with malformed name
=> use StrictCollectionPath for uploading collection snapshot

lib/collection/src/collection_manager/holders/segment_holder.rs
When reading points from segments, always read from non-appendable segments first.
Points may be moved from non-appendable to appendable, because we don't lock all segments together read ordering is very important here.
=> When reading points, go over non-appendable segments first

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/shards/local_shard/shard_ops.rs
Extends <https://github.com/qdrant/qdrant/pull/3995>
All segment reading operations must read over non-appendable segments first.
Points may be moved from non-appendable to appendable, because we don't lock all segments together read ordering is very important here.
=> On read operations, go over non-appendable segments first

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/config.rs, lib/collection/src/shards/local_shard/mod.rs
Rust rover is complaining that methods starting with `into_*` are by convention consuming their input.
This PR follows the naming convention and rename those methods
=> Use idiomatic Rust naming

lib/segment/src/common/mod.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/fixtures/payload_fixtures.rs, lib/segment/src/segment.rs, lib/segment/src/vector_storage/query_scorer/mod.rs, lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs, lib/segment/src/vector_storage/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs, lib/segment/tests/integration/multivector_hnsw_test.rs
Use a flatten representation for `MultiDenseVector` for mechanical sympathy.
It will help in the future for the mmap and quantization work as well.
=> Flatten representation for MultiDenseVectors

Cargo.lock, Cargo.toml, lib/storage/Cargo.toml
This PR updates `reqwest` because we are lagging far behind.
Two important points:
- I promoted the dependency to workspace to avoid duplication
- [0.12.0](https://github.com/seanmonstar/reqwest/releases/tag/v0.12.0) introduced a new `http2` which is a default feature
=> Update Reqwest and promote to workspace

Cargo.toml, lib/api/Cargo.toml, lib/collection/Cargo.toml, lib/common/common/Cargo.toml, lib/segment/Cargo.toml, lib/sparse/Cargo.toml, lib/storage/Cargo.toml
`Validator` is prime for promotion because its version is repeated in 7 different places
=> promote Validator to workspace

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/segment/benches/sparse_index_search.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment.rs, lib/segment/tests/integration/batch_search_test.rs, lib/segment/tests/integration/exact_search_test.rs, lib/segment/tests/integration/filtrable_hnsw_test.rs, lib/segment/tests/integration/hnsw_discover_test.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs, lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs, lib/segment/tests/integration/multivector_hnsw_test.rs, lib/segment/tests/integration/sparse_discover_test.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
This is an attempt to rethink a suggestion proposed in https://github.com/qdrant/qdrant/pull/3186
Instead of introducing a new parameter, we simply fix the problem of excluding proxy shard with too many changes from the search by allowing each individual raw segment to decide if it can do search or not.
P.S.
There is a follow-up PR with post-refactoring of simple `search` method.
=> Fix indexed-only behavior for proxy shard

Cargo.lock, Cargo.toml
We are stuck on `rustls` 0.22.x due to a missing compatibility on `actix-web`.
This PR bumps the dependency to the latest patch version and adds a comment regarding the constraint.
=> Update rustls 0.22.3

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/collection/src/grouping/group_by.rs, lib/collection/src/lookup/mod.rs, lib/collection/src/lookup/types.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/operations/types.rs, lib/collection/src/operations/vector_ops.rs, lib/segment/src/data_types/order_by.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/query/context_query.rs, lib/segment/src/vector_storage/query/discovery_query.rs, lib/segment/src/vector_storage/query/reco_query.rs, lib/storage/Cargo.toml, lib/storage/src/rbac/mod.rs, lib/storage/src/rbac/ops_checks.rs
Tracked in #3777.
This PR adds units tests for operations check/rewrite rules.
Additionally this PR fixes a bug causing `payload` restriction to be ignored.
=> RBAC: add tests

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment.rs, lib/segment/tests/integration/batch_search_test.rs, lib/segment/tests/integration/payload_index_test.rs, lib/segment/tests/integration/segment_tests.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
This PR moved `search` method from Segment trait into impl of structures, to make sure that `search`method is only used in integration tests.
For simplicity, it hides some parameters of the "main" method `search_batch`, to make further refactoring of parameters esier.
=> Proxy shard indexed only post refactor

docs/redoc/master/openapi.json, lib/api/src/rest/conversions.rs, lib/api/src/rest/schema.rs, lib/api/src/rest/validate.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/tests/sparse_vectors_validation_tests.rs, lib/segment/src/data_types/vectors.rs, lib/storage/src/rbac/ops_checks.rs
This PR decouples the `NamedVectorStruct` segment type from the API.
A new REST only type is introduced with the necessary conversions.
=> Decouple named vector struct

lib/storage/src/content_manager/toc/collection_meta_ops.rs
This PR makes sure a collection deletion command cannot delete the storage of an ongoing collection create command.
Without this a user gets:
```
2024-04-12T14:23:49.535595Z  INFO storage::content_manager::toc::collection_meta_ops: Deleting collection collection-concurrent-lifecycle-drill
2024-04-12T14:23:49.539590Z  INFO storage::content_manager::toc::collection_meta_ops: Deleting collection collection-concurrent-lifecycle-drill
2024-04-12T14:23:49.539708Z  INFO storage::content_manager::toc::collection_meta_ops: Creating collection collection-concurrent-lifecycle-drill
2024-04-12T14:23:49.545063Z  INFO storage::content_manager::toc::collection_meta_ops: Deleting collection collection-concurrent-lifecycle-drill
2024-04-12T14:23:49.547703Z  WARN …
```
=> Do do not delete data of concurrent collection creation

lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
This PR relaxes the accuracy constraint to fix the following flaky tests.
- https://github.com/qdrant/qdrant/issues/3997
- https://github.com/qdrant/qdrant/issues/4022
=> Fix multivector flaky tests

src/actix/auth.rs, src/common/auth/mod.rs, src/tonic/auth.rs, tests/consensus_tests/auth_tests/conftest.py, tests/consensus_tests/auth_tests/test_jwt_access.py, tests/consensus_tests/auth_tests/utils.py
Tracked by #3777 
There were some endpoints in gRPC, which were not allowed by read-only api key, but allowed by the global `read` access token. 
With this we make them behave the same, and we get prepared to remove the `is_read_only` implementation entirely which can be substituted it with an Access struct
=> RBAC: Make read-only api key behave the same as global read-only token

lib/collection/src/recommendations.rs, lib/sparse/src/common/sparse_vector.rs
The recommendation API must sort the sparse vectors before computing the average because the `combine_aggregate` function requires sorted vectors.
Issue discovered while running the congruence tests locally with debug assertions enabled.
=> Fix average sparse vector recommendation

lib/segment/src/segment.rs
Supersedes: <https://github.com/qdrant/qdrant/pull/4051>
Separate version handling for segments and points. Some operations only need to do point level version checks, while others only need segment level checks.
Before this PR, point versions check did fall back to segment version checks if that point did not exist yet.
=> Separate segment and point level version handling

QUICK_START.md, README.md, docs/DEVELOPMENT.md
Currently, the docs refer to unauthenticated instances of Qdrant as "for production" when we actually discourage that: https://qdrant.tech/documentation/guides/security/
So in the README and QUICK_START guides, I've removed those mentions of "production" and instead included mentions of safer ways to run Qdrant in production.
=> Update docs to mention safer production practices

lib/collection/src/collection/point_ops.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/remote_shard.rs, lib/segment/src/data_types/order_by.rs, tests/consensus_tests/test_order_by.py
Fixes #4024
The root cause of the issue is that the remote shards were not actually sending the `____ordered_with____` value, because we were removing it right before sending it.
This fixes 2 main things:
- deserialization of this value into `OrderingValue`
- detects when it is a remote shard call to not erase the `____ordered_with____` value early. Then uglily adds the requested `with_payload` after merging from the shards.
=> [order-by] Fix remote shard calling

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/segment/src/segment.rs
Add two tests to assert correctness of point version handling and moving points across segments, typically with an old operation ID and a newer segment version.
Before <https://github.com/qdrant/qdrant/pull/4057>, these did show wrong behavior when doing a point operation with an operation ID that is older than the current segment version.
In the case of moving points across segments, it resulted in missing points. A move happens if we want to update a point in a non-appendable segment. We copy to a new segment, and delete it from the old segment. If the copy was (silently) rejected due to a version mismatch, the point is deleted and ends up missing.
The tests assert correctness in two places to make sure the same doesn't happen in the future.
The tests now succeed, while they fail before …
=> Test point version handling and moving correctness across segments

lib/collection/src/collection_manager/holders/segment_holder.rs
Extends <https://github.com/qdrant/qdrant/pull/3420>
Rather than releasing all segment proxies at once at the end, we release them one by one right after we're done with each segment.
We prefer to keep segment proxies as short as possible, because it induces extra overhead. All segment proxies forward their writes to a single temporary segment which may become a bottleneck in some cases. With this change, we have 50% less proxies overtime which should reduce the load on on this temporary segment.
The cost of this is a bit more read/write lock switching, but the above benefit outweighs that.
3. [x] Have you checked your code using `cargo clippy …
=> For non-blocking snapshots, release segments one by one right after use

lib/segment/src/segment.rs
Compilation on `dev` broke very recently, likely due to two PRs conflicting with each other.
This fixes that!
=> Fix compilation error on dev due to missing datatype field

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/storage/Cargo.toml
The `collection` crate and the `storage` crate use different version of the [wal](https://github.com/qdrant/wal) crate.
The gap is represented by those two PRs:
- https://github.com/qdrant/wal/pull/71
- https://github.com/qdrant/wal/pull/68 
In order to avoid subtle compatibility issues, I have unified the version in the workspace and bumped to the latest revision.
=> Fix different wal crate versions

lib/collection/src/collection_manager/holders/proxy_segment.rs
Add a unit test that checks that `ProxySegment::flush` works as expected. (Only tests `sync = true` flush currently.)
=> Add simple `ProxySegment::flush` unit-test

lib/segment/src/data_types/primitive.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/spaces/metric_uint/simple_dot.rs, lib/segment/src/spaces/metric_uint/simple_manhattan.rs, lib/segment/src/vector_storage/dense/appendable_mmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/segment/tests/integration/byte_storage_quantization_test.rs, lib/segment/tests/integration/main.rs
This PR adds quantization fixes for byte storage.
It supports all quantization types (SQ, BQ, and PQ) and adds unit tests covering PQ, SQ, PQ for Dot, Cosine metrics, and Nearest, Discovery, and Recommendation searches.
=> byte storage quantization fix and test

tests/openapi_consistency_check.sh
These variables are gone since #4046. No need to reference them anymore
=> Remove unexistent consts in test error message

lib/api/build.rs, lib/api/src/grpc/qdrant.rs, tests/basic_sparse_grpc_test.sh
The validation of `grpc::Vector` was not wired properly in `UpsertPoints`.
This validation is only relevant for sparse vectors currently.
Before this change we would return a validation during a conversion happening later instead of blocking the input right away.
=> Add missing validation for gRPC UpsertPoints

lib/common/common/src/lib.rs, lib/common/common/src/top_k.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/index/search_context.rs
Experiment median TopK based on the article from the nice folks at Quickwit https://quickwit.io/blog/top-k-complexity.
```
sparse-vector-search-group/inverted-index-search
time:   [566.19 µs 575.56 µs 584.71 µs]
change: [-9.0722% -7.3381% -5.5563%] (p = 0.00 < 0.05)
```
Running https://github.com/qdrant/sparse-vectors-benchmark with full dataset
```
DEV
min: 72.6 millis
50p: 157.3 millis
95p: 210.72 millis
99p: 235.89 millis
999p: 261.57 millis
max: 338.19 millis
```
```
PR
min: 62.32 millis
50p: 148.66 millis
95p: 197.56 millis
99p: 222.33 millis
999p: 246.36 millis
max: 273.89 millis
```
- checked congruence tests
- checked ground truth values in benchmarks
We might want to constraint the `limit` argument in search to avoid having someone reserving a huge …
=> Median based TopK for sparse vectors scoring

Cargo.lock, Cargo.toml
Supersedes: <https://github.com/qdrant/qdrant/pull/4076>
Bump vulnerable RusTLS versions.
Internal report: <https://github.com/qdrant/qdrant/security/dependabot/69>
=> Bump RusTLS to 0.22.4

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/segment/Cargo.toml, lib/storage/Cargo.toml
Remove unused `tar` dependency declaration at the root level and push it into the workspace for others dependents.
=> Clean tar dependency management

lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/primitive.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
This PR introduces generic multivector storage. We want to include byte-multivectors in the next release (like in dense vectors in v1.9.0).
=> Generic multidense vector storage

lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/query_scorer/mod.rs, lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
This PR introduces 2 changes:
First, it allows generic types over multivector scorers. It's required for typed multivectors (vectors of float and u8).
Second, it introduces `TypedMultidenseVectorRef` and integrates it into scorers. This additional type is better than `&MultidenseVector` because it allows to use of any slice as a multivector. It's required for mmap storage and future optimizations of ram multivector storage.
=> Generic multivector scorer

lib/segment/src/types.rs
We were missing the case of converting integer index type with integer index params in `TryFrom<PayloadIndexInfo> for PayloadFieldSchema`.
I have rewritten it so that we notice when some other type has their own params.
=> Fix `TryFrom<PayloadIndexInfo> for PayloadFieldSchema`

lib/collection/src/collection/point_ops.rs, lib/collection/src/collection/search.rs, lib/collection/src/grouping/aggregator.rs, lib/collection/src/grouping/types.rs, lib/collection/src/shards/replica_set/mod.rs, lib/common/issues/src/issue.rs, lib/segment/src/data_types/tiny_map.rs, lib/segment/src/index/hnsw_index/build_cache.rs, lib/segment/src/json_path/v2.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs, lib/storage/src/content_manager/consensus_manager.rs
Rust 1.78 is coming out in two days time https://releases.rs/docs/1.78.0/
Let's fix new Clippy lints proactively to ensure a smooth transition.
=> Proactively fix lints for Clippy 1.78

lib/collection/src/collection_manager/segments_updater.rs
Fix a debug assertion that fails quite often locally. This happens on stream records transfer with concurrent upsertions.
Our sync points logic is a multi step process. We select a list of points to be replaced, and eventually update all of them. When updating, we expect the number of replaced points to match the list of points we selected.
When concurrent upsertions are ongoing, some of these points may get updated in between this process. Those points will have a newer version and will not be updated. That results in a lower number of replaced points.
Roman and I investigated this some time ago. We believe this is expected, and we should relax the debug assertion as done in this PR.
2. [x] Have you formatted your code locally using `cargo +nightly …
=> Fix debug assertion, replaced points may be less than points to update

lib/collection/src/collection_manager/holders/segment_holder.rs
```
error: assigning the result of `Clone::clone()` may be inefficient
--> lib/collection/src/collection_manager/holders/segment_holder.rs:126:9
|
126 |         *self = source.clone();
|         ^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_from()`: `self.clone_from(source)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
= note: `-D clippy::assigning-clones` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::assigning_clones)]`
```
This PR removes the function because it is equivalent to the default implementation in the trait.
=> Missed lints for clippy 1.78

Cargo.lock, Cargo.toml, lib/collection/src/events.rs, lib/collection/src/lib.rs, lib/common/issues/src/broker.rs, lib/common/issues/src/lib.rs, lib/common/issues/src/typemap.rs, lib/storage/Cargo.toml, lib/storage/src/issues_subscribers.rs, lib/storage/src/lib.rs, src/issues_setup.rs, src/main.rs
Needs #4086 
This PR setups and demonstrates how issue subscribers listen to issue-able events. 
While this PR won't submit nor solve any `Issue`, it slims down further PRs, for easier reviewability.
=> Issues API: Listen for issues events in main app

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.9.2-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4085>.
=> Bump dev version to 1.9.2-dev

docs/redoc/master/openapi.json, lib/api/src/rest/conversions.rs, lib/api/src/rest/schema.rs, lib/api/src/rest/validate.rs, lib/collection/src/config.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/operations/vector_params_builder.rs, lib/common/common/src/validation.rs, lib/segment/src/data_types/primitive.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/types.rs, tests/openapi/openapi_integration/test_multi_vector.py
This PR adds the support for multivector in the REST API for writes and retrieve use case.
An important point is that I decided to keep the conversion between REST Vectors and Segment Vectors infallible because handling error would create a gigantic change through the codebase.
The assumption in this PR is that the input vectors will have gone through validation first.
I have integration added tests showing that:
- the validation kicks in properly
- writes work
- retrieves work
- search is not supported
=> REST API multivector for write and retrieve

.github/workflows/dev-docker-image-build.yml
Using `-a` is important while listing buildx containers. Otherwise, we might miss deleting the ones that failed. 
This hasn't caused any issues so far. But it's better to fix it.
=> ci: Force delete all existing buildx resources before building image

Cargo.lock
Follow up on https://github.com/qdrant/qdrant/pull/4164
Building `dev` updates the cargo.lock version automatically.
=> Bump cargo.lock version

lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/chunked_vectors.rs, lib/segment/src/vector_storage/simple_multi_dense_vector_storage.rs
This PR uses ideas from https://github.com/qdrant/qdrant/pull/4106 to refactor multivector RAM storage.
Currently, each multivector uses a separate allocated `Vec`. This PR uses `ChunkedVectors` from simple dense vector storage to store all multivector data in large flattened chunks.
All ideas and techniques as the same like in mmap storage.
No new unit test, multivector storage is already covered by tests
=> Multivector flattened ram storage

lib/segment/Cargo.toml, lib/segment/benches/dynamic_mmap_flags.rs, lib/segment/benches/map_benchmark.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/dense/appendable_mmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/dynamic_mmap_flags.rs, lib/segment/src/vector_storage/dense/mod.rs, lib/segment/src/vector_storage/tests/test_appendable_dense_vector_storage.rs
Improve our logic for counting deleted flags when opening the mmap based deleted flags from disk.
We're seeing some slowdowns when loading Qdrant collections, especially with memory mapping. I started this effort to improve one of the aspects of it.
The improvement is quite visible on large flag counts, such as 50m, where I see a 50x improvement. On low counts, such as 50k, things seem to be the other way around. I'm a bit confused on why this is the case, and may very well be noise from the benchmark itself. I think this potential slowdown like this is acceptable on low counts when including the potential increase on large counts.
Here are the bench results on various flag counts. Each second entry is the improved logic in this PR:
```bash
dynamic-mmap-delete-count/manual-count-loop …
```
=> Improve performance of dynamic mmap flags counting

lib/segment/benches/dynamic_mmap_flags.rs, lib/segment/src/vector_storage/dense/appendable_mmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/dynamic_mmap_flags.rs
Follow-up after <https://github.com/qdrant/qdrant/pull/4176>.
I merged it a bit to quickly. The return type can be a lot simpler.
=> Simplify return type when counting dynamic mmap flags

lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/vector_storage_base.rs
This PR tunrs on mmap multivector storages and add segment support of byte-multivector storages.
It extends `VectorStorageEnum`, add scorers construction of byte multivector storages, and construct mmap and byte-storages in segment constructor.
There are no unit tests. Integration tests will be added by @agourlay as separate PR.
=> Integrate multivector mmap and byte storages

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, src/tonic/api/points_internal_api.rs
We had previously changed the response of this endpoint to always return an error. Since this only affects internal API, it is safe to remove it by now.
=> Chore: remove deprecated internal search API

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/common/dataset/Cargo.toml, lib/common/dataset/src/lib.rs, lib/segment/Cargo.toml, lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/index/vector_index_base.rs, lib/sparse/Cargo.toml, lib/sparse/benches/prof.rs, lib/sparse/benches/search.rs, lib/sparse/src/common/sparse_vector.rs, lib/sparse/src/index/inverted_index/inverted_index_ram_builder.rs, lib/sparse/src/index/loaders.rs, lib/sparse/src/index/mod.rs
This PR brings a new set of benchmarks to `segment` and `sparse` crates, based on downloadable datasets.
These benchmarks would serve as a baseline to evaluate the performance of the new sparse index format (#4143).
There were a few problems with the current benchmark in the `segment` crate:
1. They were based on uniform random data, whereas the distribution of the real data usually follows Zipf's law distribution.
2. The same query vector is reused across all benchmark iterations.
We don't want to let CPU caches do a favor to less memory-efficient algorithms.
3. Segment crate is slow to compile. It makes it hard to iterate on the benchmarks.
This PR contains the following changes:
1. A new crate `lib/common/dataset` to download testing datasets during benchmarking.
1. Downloaded datasets …
=> Update sparse vector benchmarks

docs/grpc/docs.md, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/src/operations/conversions.rs, lib/common/common/src/validation.rs, tests/basic_multivector_grpc_test.sh, tests/integration-tests.sh
This PR adds a new gRPC API for multivector.
it supports write and retrieve operations. Search is not supported.
=> gRPC API multivector for write and retrieve

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/segment/src/segment.rs
Likely fixes: <https://github.com/qdrant/qdrant/issues/4199>
Fix a deadlock in the proxy segment. Locking in the `propagate_to_wrapped()` and search functions conflict.
The search function hold a lock on `deleted_points` after which it locked the wrapped segment. The propagation function did it the other way around.
I fixed this by not keeping a write lock on the write segment for the whole duration of the `propagate_to_wrapped()` function. Instead we now take an upgradable read lock and temporarily upgrade it on demand. An alternative would be to require mutable self on this function to ensure exclusive access to all locks, but I expect that to have a worse impact in terms of performance.
The last two days I managed to reproduce the problem very reliably. With this fix I've tested for …
=> Fix deadlock in proxy segment when propagating to write segment

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs, tools/missed_cherry_picks.sh
Release Qdrant 1.9.2.
We want to release a patch version to fix this deadlock: <https://github.com/qdrant/qdrant/pull/4206>
=> Bump version to 1.9.2

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.9.3-dev` after merging <https://github.com/qdrant/qdrant/pull/4207>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4164>.
=>  Bump dev version to 1.9.3-dev

.github/workflows/dev-docker-image-build.yml
Sometimes we ended up with multiple images from previous runs and the output of the docker ls commands was in multiple lines. That's why the delete commands sometimes threw errors like this:
```
Buildx containers to delete:  bcd97a723659
7c0422c69e6c
Error response from daemon: page not found
```
```
Buildx volumes to delete:  buildx_buildkit_boring_haslett0_state
buildx_buildkit_intelligent_bouman0_state
Error response from daemon: page not found
```
=> fix: Replace newline with spaces to find docker resources to remove

tests/openapi/openapi_integration/helpers/collection_setup.py, tests/openapi/openapi_integration/test_shard_snapshot.py, tests/openapi/openapi_integration/test_snapshot.py
Locally these two tests were taking ~70s to run, but by setting a low wal capacity, they now take ~9.5s.
I also tried changing the setting globally, but it only reduces around 3s for the whole suite, so I don't think it is enough gain.
=> Faster openapi-integration snapshot tests

docs/grpc/docs.md, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/update.rs, lib/collection/src/shards/shard_holder.rs
This PR adds a few basic types/variants/fields that are required as the most fundamental building blocks for resharding.
__TODO:__
=> Add basic resharding types

lib/collection/src/shards/local_shard/disk_usage_watcher.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/update_handler.rs
Instead of checking on flush, we would prefer to check _before_ inserting into WAL, but with smart heuristics.
=> refactor disk usage checks

lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/primitive.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs, lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs, lib/segment/tests/integration/multivector_hnsw_test.rs, tests/openapi/openapi_integration/test_multi_vector.py
`TypedMultiDenseVectorRef` replaces `&TypedMultiDenseVector`. `TypedMultiDenseVectorRef` is important because it allows referring multivector data from mmap or `ChunkedVectors`.
=> Use TypedMultiDenseVectorRef everywhere

lib/collection/src/operations/types.rs, lib/segment/src/common/mod.rs, lib/segment/src/common/operation_error.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/primitive.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/segment_constructor/simple_segment_constructor.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/multi_metric_query_scorer.rs, lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs, lib/segment/tests/integration/multivector_hnsw_test.rs, tests/basic_multivector_grpc_test.sh, tests/consensus_tests/test_collection_shard_update.py, tests/openapi/openapi_integration/test_multi_vector.py
This enables the support of basic multivec search on the current search API without changing the schema.
The trick is to expand a single dense vector into a multivector during conversion instead of returning an error.
A new search API will later be introduced to search using full fledged multivectors.
=> Allow basic multivec search on legacy API

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/primitive.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/spaces/metric_f16/mod.rs, lib/segment/src/spaces/metric_f16/simple_cosine.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/dense/appendable_mmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/segment/tests/integration/byte_storage_hnsw_test.rs, lib/segment/tests/integration/byte_storage_quantization_test.rs
Float16 REST and Grpc, storages, scorers, and constructors
=> Float16 integration and API

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/operations/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/operations/vector_ops.rs, lib/collection/src/shards/shard_holder.rs
This combines (re)sharding hash rings in a single type, replacing the single hash ring we had before. It provides a consistent interface for all scenarios, whether we have a single hash ring or multiple while resharding. It keeping most of the existing logic intact, and allows us to extend and/or tweak behavior in a single place in the future.
Here I propose to replace the initial approach with a separate hash ring on a shared resharding key introduced in <https://github.com/qdrant/qdrant/pull/4216>. It seems more future proof, easier to manage, and remains on the shard key level. When working with shards, we always namespace to a specific shard key and so it makes sense to combine all necessary state in a single type with a single lookup.
It doesn't only replace the way …
=> Combine (re)sharding hash rings in a single type, update split-by-shard logic

lib/common/issues/src/broker.rs, lib/common/issues/src/dashboard.rs
I could not reproduce #4233 locally, but making it not global-state dependent is a better idea
=> Make `Broker` test independent of a global dashboard

lib/segment/build.rs
Fix this docker build error:
https://github.com/qdrant/qdrant/actions/runs/9092581497/job/24989602531
=> fix arm linking error on docker

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/Cargo.toml, lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/operations/universal_query/shard_query.rs, lib/segment/src/data_types/vectors.rs
Needs #4245 
- Tests and fixes the `TryFrom<ShardQueryRequest> for PlannedQuery` implementation
- Adds `ScoringQuery::Rrf` variant
=> universal-query: Test and fix `PlannedQuery` conversion

Cargo.lock, Cargo.toml, lib/collection/src/hash_ring.rs, lib/collection/src/shards/shard_holder.rs
Tracked in <https://github.com/qdrant/qdrant/issues/4213>
Derive `Clone` on our hash ring types. This is needed for work on resharding.
For  this we temporarily switch to a patched crate until <https://github.com/jeromefroe/hashring-rs/pull/25> is merged.
=> Derive Clone on hash ring types

lib/collection/benches/hash_ring_bench.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/collection/sharding_keys.rs, lib/collection/src/collection/state_management.rs, lib/collection/src/hash_ring.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/operations/vector_ops.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, lib/storage/src/content_manager/toc/mod.rs, lib/storage/src/dispatcher.rs, lib/storage/src/rbac/ops_checks.rs
This PR adds `ReshardingOperation::Start` consensus message. And also (in the most trivial way) disables splitting read operations to the resharding shard.
Important TODO to be fixed in some future PR: consensus snapshot does not handle resharding in any way *yet*.
=> Add `ReshardingOperation::Start` consensus message

lib/segment/src/spaces/metric_f16/neon/dot.rs, lib/segment/src/spaces/metric_f16/neon/euclid.rs, lib/segment/src/spaces/metric_f16/neon/manhattan.rs
Gets rid of the [`clippy::missing_safety_doc`](https://rust-lang.github.io/rust-clippy/master/index.html#/missing_safety_doc) warnings that appear while developing on mac, only for the newly added similarity metrics for half precision floats.
=> Allow missing safety doc on half float similarity functions

lib/collection/src/collection/mod.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/collection_state.rs, lib/collection/src/operations/cluster_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, src/common/collections.rs
This PR adds `StartResharding` operation to `update_collection_cluster` REST API.
=> Add `StartResharding` operation to `update_collection_cluster` REST API

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/operations/universal_query/shard_query.rs, lib/collection/src/shards/local_shard/query.rs
- Adds `ScoringQuery::OrderBy` variant
- Modifies `PlannedQuery` to also store a list of scroll alongside the core search batch
- Adjusts the try_from conversion accordingly
- Internal grpc `QueryShardPoints` also gets the order-by variant
=> universal-query: Add `OrderBy` scoring, and add `scrolls` to `PlannedQuery`

src/tracing/config.rs, src/tracing/handle.rs, src/tracing/mod.rs, src/tracing/on_disk.rs, src/tracing/test.rs
Fixes #2505.
Extends logger to support logging to a file on disk.
=> Implement logging into a file on disk

lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/query_scorer/mod.rs, lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
Vector storage should return vectors count, not all inner vectors count. Because `0..self.total_vector_count()` is a range of valid internal ID's. Also removed obsolete `OrderedFloat` usage
=> Fix wrong multivectors count in storage

.github/workflows/integration-tests.yml
This PR bumps the version of the Python runtime used on CI for consensus tests.
The rational is:
- we use 3.11 for openapi tests
- it is good to stay one version behind
- I use 3.11 locally :)
=> Use Python 3.11 on CI for consensus tests

lib/segment/src/data_types/primitive.rs, lib/segment/src/vector_storage/dense/appendable_mmap_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs
This PR adds static lifetime to Primitive type. It's obvious because primitive types are `f32`, `f16` and `u8` which have static lifetime. It also adds `Send` and `Sync` for future quantization purpose
=> add static lifetime to primirive type

lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
Quantization crate takes this dense vectors iterator as an input:
```
impl Iterator<Item = impl AsRef<[f32]> + 'a> + Clone + Send,
```
Example is here:
https://github.com/qdrant/quantization/blob/master/quantization/src/encoded_vectors_pq.rs#L57
To achieve multivectors quantization, this PR adds `iterate_inner_vectors` to multivector storage which is quantization-compatible. Test for ram and mmap were added
=> multivector storage iterate over all inner vectors

lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs
This PR adds constructor from multivector for quantization scorers (through `new_multi` method for each quantization scorer). Also, this PR removes unnecessary fields `QuantizedQueryScorer.original_query` and `QuantizedCustomQueryScorer.original_query`.
No tests here because in dev there are no any quantization storage which allow to encode multivector - it will be added in next PR's
=> quantization scorer with multivector support

lib/collection/src/operations/types.rs, lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/tests/fixtures.rs, lib/collection/src/tests/mod.rs, lib/collection/src/tests/shard_query.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/src/tests/wal_recovery_test.rs, lib/segment/src/common/reciprocal_rank_fusion.rs
This PR adds the implementation for re-scoring with RRF or a query at the shard level.
I took extra care make this testable by setting up test fixtures for shard tests.
=> Rescore universal query

lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/operations/universal_query/mod.rs
Adds the bare types for `CollectionQueryRequest`. The type into which REST and gRPC will converge.
=> universal-query: Add `CollectionQueryRequest`

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/conversions.rs, lib/api/src/rest/schema.rs, lib/collection/src/collection/search.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/tests/test_search_aggregation.rs, lib/collection/src/grouping/aggregator.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/operations/query_enum.rs, lib/collection/src/shards/conversions.rs, lib/collection/src/shards/resolve.rs, lib/segment/src/common/reciprocal_rank_fusion.rs, lib/segment/src/data_types/order_by.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/segment.rs, lib/segment/src/types.rs
Supersedes #4251 #4278 
- Fix ordering in group-by for custom scoring
- Rename `OrderingValue` -> `OrderedValue`
- Introduce `order_value` field in `ScoredPoint` (internal, grpc, and rest)
=> universal-query: Introduce `order_value` field in `ScoredPoint`

lib/collection/src/shards/local_shard/query.rs, lib/collection/src/shards/local_shard/scroll.rs, lib/collection/src/shards/local_shard/shard_ops.rs
Needs #4291 
- Add basic batch scrolling of multiple requests
- Refactor `scroll_by_field` to return parallel lists instead of hacked `Record` with edited payload
=> universal-query: Add basic batch scrolling

lib/collection/src/collection/mod.rs
This was missing the `format!()` macro, and so it would just print `{shard_id}` in the error message.
=> Fix missing format macro in recovery point function

lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/tests/shard_query.rs
Hydrate query scores with `payload` and `vector` if necessary.
=> Query fetches payload and vector if necessary

lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/hash_ring.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/transfer/driver.rs, lib/collection/src/shards/transfer/helpers.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/resharding_stream_records.rs, lib/collection/src/shards/transfer/stream_records.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, lib/storage/src/content_manager/toc/snapshots.rs, src/common/collections.rs
Adds a `ReshardingStreamRecords` shard transfer method that will be utilized as part of resharding.
=> Add shard transfer method for resharding

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml
<https://github.com/jeromefroe/hashring-rs/pull/25> got merged, so we can switch back to the upstream crate.
=> Switch back to upstream hashring crate

lib/collection/src/collection/point_ops.rs
The scroll limit might overflow if providing `usize::MAX` because we add one to it if no ordering is used:
```rust
thread 'tests::snapshot_test::test_shard_dedup' panicked at lib/collection/src/collection/point_ops.rs:260:13:
attempt to add with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I've changed this to `saturating_add(1)`. It means we won't add one if the limit is `usize::MAX`, but I think it's unreasonable to reach that limit anyway. Better be safe than panic.
=> Fix overflow panic if scroll limit is usize::MAX

lib/collection/src/operations/snapshot_ops.rs
This is a breaking change, but it looks like nobody uses "priority=replica" and default behavior just creates a lot of confusion
=> Make default priority "snapshot" for snapshot recovery

lib/collection/src/collection/point_ops.rs, lib/collection/src/collection/search.rs, lib/collection/src/tests/mod.rs, lib/collection/src/tests/points_dedup.rs
Deduplicate points based on their point ID in all reads from shards.
This is necessary for resharding, where multiple shards may have a single point ID.
The idea was to only deduplicate this while resharding is active, but after a discussion with @generall we decided to enable it at all times. We might benefit from this in other cases too, such as when we have the same point ID across multiple shard keys. At this time it is unclear yet what performance impact that might have, so that's yet to be tested.
- Do we need to handle read errors in any special way?
- e.g., *ignore* read errors from new shard?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior …
=> Deduplicate points for shard reads

lib/common/common/src/fixed_length_priority_queue.rs, lib/segment/src/spaces/tools.rs
/claim #4321
After these changes, `FixedLengthPriorityQueue` will reallocate its underlying Binary Heap in case it's too large to be preallocated in one go.
=> Huge limit now does not crash

lib/collection/src/operations/universal_query/collection_query.rs, lib/storage/src/content_manager/toc/mod.rs, lib/storage/src/content_manager/toc/point_ops.rs, lib/storage/src/content_manager/toc/point_ops_internal.rs, lib/storage/src/rbac/ops_checks.rs, src/tonic/api/points_internal_api.rs
- Add `query()` to ToC, for user requests
- Implement handling of `Access` token
- Add `query_internal()`to ToC, for shard queries.
- Solve remaining TODOs in `points_internal_api::query()`
=> universal-query: add `query()` in toc and handle `Access` token

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/shards/local_shard/mod.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs
Fix issue where segments did go missing.
We created a new segments in the wrong directory, which means they would not be loaded on restart.
This also refactors some parameters, function names and documentation to remove a lot of confusion around what type of paths are used where.
=> Fix missing segments, use correct path for new segment created during snapshot

lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/operations/universal_query/shard_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/tests/shard_query.rs
Update `ShardQueryRequest` to make `query` parameter optional. 
If it is missing and it is a leaf node, it is a scroll request. Otherwise it means to merge without rescoring.
Open Question: If it merges without rescoring... which order (LargeBetter, or SmallBetter) should we choose?
=> universal-query: If query is missing, it's a scroll

Cargo.lock, Cargo.toml, lib/collection/src/collection/mod.rs, lib/collection/src/hash_ring.rs, lib/collection/src/operations/cluster_ops.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, src/common/collections.rs
This PR:
- adds `ReshardingOperation::Abort` consensus message
- and `AbortResharding` operation to `update_collection_cluster` REST API
- (currently not exposed in the OpenAPI spec)
- and also fixes incorrect serialization format of `StartResharding` operation for `update_collection_cluster` API
- `#[serde(untagged)]` is annoying to work with 😒
Abort operation is structured so that it can be applied to a partial/inconsistent resharding state, so that you can cleanup a broken state if something went wrong.
=> Add `ReshardingOperation::Abort` consensus message

lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/quantized/mod.rs, lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/query_scorer/mod.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/segment/tests/integration/main.rs, lib/segment/tests/integration/multivector_quantization_test.rs
Add quantization support for multivectors.
The main idea is to reuse quantization integration for multivectors.
Encoded vectors are a `struct` which implements `EncodedVectors` trait.
https://github.com/qdrant/quantization/blob/master/quantization/src/encoded_vectors.rs#L21
There are encoded vectors for scalar, PQ and binary quantizations:
https://github.com/qdrant/quantization/blob/master/quantization/src/encoded_vectors_u8.rs#L262
https://github.com/qdrant/quantization/blob/master/quantization/src/encoded_vectors_pq.rs#L497
https://github.com/qdrant/quantization/blob/master/quantization/src/encoded_vectors_binary.rs#L160
Multivector encoding aggregates one of this structure into generic encoded type
`struct QuantizedMultivectorStorage<TEncodedQuery, QuantizedStorage: …
=> Multidense vectors quantization

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/shards/local_shard/mod.rs
Related to: <https://github.com/qdrant/qdrant/pull/4332>
When loading a shard, ensure that we have at least one appendable segment. If we don't, create one.
Normally, we never expect this scenario. This just helps being on the safe side by preventing an unrecoverable crash loop if this somehow does occur.
However, a recent bug - fixed in <https://github.com/qdrant/qdrant/pull/4332> - did allow this situation to occur by misplacing the appendable shard in the wrong directory. We need to improvement to prevent accidental crash loops as described above.
=> On shard load, ensure we have any appendable segments

lib/collection/src/shards/local_shard/query.rs
- create a single core search request for all ids to rescore. Correct ordering is already handled within `do_search`
~- optimize taking from sources so that no extra cloning is made~
=> universal-query: Fix order in `LocalShard` vector rescoring

lib/collection/src/collection/mod.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/shards/mod.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, src/common/collections.rs
Move the resharding state from the collection struct into the shard holder. It now lives next to the shard transfers state.
I've also added a `ReshardingKey` which holds the peer ID, shard ID and resharding key because we commonly use these together. This matches with the shard transfer key.
=> Move resharding state into shard holder

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/index/sparse_index/indices_tracker.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/migrate.rs
Instead of implementing index migration, we could just drop and re-create the index from scratch when it is not compatible or fails to load. This PR implements this approach.
Pros of this approach over hand-written migration:
- Simpler and more robust.
- We can implement arbitrary changes in the index format as many times as we want without fear of losing/corrupting the data.
- It allows rolling back to the previous index version for free.
Cons:
- It takes 25 seconds of CPU time on my machine to rebuild an index in a single segment with 1.3M of points.
- Increased memory consumption during the first startup. Might significantly increase loading time if the system is swapping.
=> Recreate sparse vector index

lib/collection/src/operations/universal_query/shard_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/segment/src/common/reciprocal_rank_fusion.rs
- Introduce a custom iterator abstraction for going over the results of core searches, scrolls, and new merges.
- Reduce cloning by using `Cow`, since cloning is only necessary for RRF.
=> universal-query: Clone less in local shard

src/common/pyroscope_state.rs
Unused argument in non-linux platforms
=> fix pyroscope warning on non-linux platforms

src/actix/helpers.rs
Storage service error should be logged with the level ERROR when processing a REST request.
Example of output after this PR:
``` 
2024-05-29T14:25:52.118957Z ERROR qdrant::actix::helpers: error processing request: 1 of 1 read operations failed:
Service internal error: Inconsistent storage: Vector storage 'sparse-vector' is inconsistent, total_vector_count: 3401, point_offset: 3865
```
=> Log Service Error as error in actix processing

lib/sparse/src/index/compressed_posting_list.rs, lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/posting_list_common.rs, lib/sparse/src/index/search_context.rs
This PR optimizes implementation of the compressed posting list.
#4143
Previous results: #4253.
task | ram | ramc | diff | mmap | mmapc | diff
| - | - | - | - | - | - | -
random-50k | 0.75844 | 0.95927 | +26% | 0.75591 | 0.99954 | +32%
random-500k | 7.0467 | 8.5863 | +21% | 7.1477 | 8.7218 | +22%
neurips2023-1M | 11.628 | 13.191 | +13% | 11.591 | 13.650 | +17%
neurips2023-full-25pct | 27.021 | 30.671 | +13% | 26.939 | 30.986 | +15%
movies | 3.2623 | 4.0095 | +22% | 3.2435 | 4.0141 | +23%
task | ram | ramc | diff | mmap | mmapc | diff
| - | - | - | - | - | - | -
random-50k | 0.18326 | 0.18706 | +2% | 0.18369 | 0.18878 | +2%
random-500k | 1.5832 | 1.6346 | +3% | 1.5791 | 1.6348 | +3%
neurips2023-1M | 8.4410 | 8.9399 | +5% | 8.3978 | 8.9317 | +6%
neurips2023-full-25pct | 18.646 | 20.068 | …
=> Improve performance of compressed posting list

lib/collection/src/collection/mod.rs, lib/collection/src/hash_ring.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/update.rs
This PR enables sending update to the created shard and adds basic error handling for failed updates.
=> Send updates to the new shard during resharding

lib/collection/src/collection/mod.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/collection_state.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/resharding/tasks_pool.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, src/common/collections.rs
Lay out the initial stubs for the logic driving the whole resharding process.
=> Initial stubs for resharding driver

.github/workflows/integration-tests.yml, Cargo.toml, lib/collection/Cargo.toml, lib/collection/src/shards/local_shard/mod.rs, lib/segment/src/segment.rs, tests/storage-compat/storage-compatibility.sh
This PR adds a new post WAL application data consistency check.
The core assumption is that there must be no data consistency issue **after** the outstanding operations from the WAL have been applied.
The data consistency check looks for:
- dangling internal ids
- dangling external ids
- internal ids without version
- internal ids without stored vector
The proposal is to perform this new check behind a new feature flag in order for us to test internally our storage without impacting users.
I have added the feature flag in our CI pipelines where I believe it makes sense.
When an inconsistency is detected, the impacted shard cannot be loaded properly.
The server is still up but without the shards with corrupted segments.
=> Add optional post WAL data consistency check

lib/segment/Cargo.toml, lib/segment/benches/sparse_index_build.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/sparse/benches/search.rs, lib/sparse/src/common/mod.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_immutable_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_immutable_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/search_context.rs
Two small fixes in the `sparse` crate:
- `InvertedIndexRam` → `Cow<InvertedIndexRam>`.
- Hide module `sparse_vector_fixture` under `#[cfg(feature="testing")]`.
=> Sparse: misc fixes

lib/segment/src/id_tracker/id_tracker_base.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs
Introduceds enum dispatch for IdTracker. Currently falls back to `SimpleIdTracker` for ImmutableIdTracker as this will follow in a separater PR.
=> Add IdTrackerEnum

tools/generate_grpc_docs.sh, tools/generate_openapi_models.sh
1. Speedup `tools/generate_openapi_models.sh` by reducing the amount of `docker run` invocations.
- On my machine, it's now faster by 5 seconds.
- When `ytt` and `yq` are installed locally, it's faster by 7 seconds.
2. Clean up temp files in `tools/generate_grpc_docs.sh`. No need to pollute `/tmp`. Also, use a meaningful temporary directory name.
3. Do not call `sudo chmod` in `tools/generate_grpc_docs.sh`. [The causing issue](https://www.github.com/pseudomuto/protoc-gen-doc/issues/383) is solved.
4. Use proper shell quoting in `tools/generate_grpc_docs.sh`.
=> Improve tools/*.sh

lib/segment/src/segment.rs
It is a good practice to not ignore silently persistence errors.
This PR proposes to log at debug level failed segment flush on drop, this might help us one day.
=> Log failed segment flush on drop

lib/segment/src/common/rocksdb_wrapper.rs
For the sake of consistency, we should apply the same options to `remove` and `put` operations against RocksDB.
```rust
fn get_write_options() -> WriteOptions {
let mut write_options = WriteOptions::default();
write_options.set_sync(false); // default to false
write_options.disable_wal(true); // default to false
write_options
}
```
The current setup might cause some storage inconsistencies which are difficult to debug given that we control precisely the exact moment of the flushing.
=> Rocksdb remove should use the same options as put

lib/collection/src/collection/resharding.rs, lib/collection/src/hash_ring.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
Tracked in #4213. Based on #4351.
This PR adds `CommitHashRing` consensus operation.
We *might* still redesign this (e.g., to use multiple hashring commit steps or something), but I'd expect most of the code in this PR to be reused anyway.
=> Add `ReshardingOperations::CommitHashRing` consensus message

lib/collection/src/collection/resharding.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/transfer/driver.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/resharding_stream_records.rs, lib/collection/src/shards/transfer/snapshot.rs, lib/collection/src/shards/transfer/stream_records.rs, lib/collection/src/shards/transfer/wal_delta.rs, lib/storage/src/content_manager/toc/transfer.rs
For shard transfer and resharding, we passed in a `collection_id` and `collection_name`.
They are equal. This removes the `collection_name`.
=> Deduplicate collection ID in shard transfers/resharding

lib/segment/src/common/rocksdb_buffered_update_wrapper.rs
This PR fixes the atomicity of the `Versions` persistence (context https://github.com/qdrant/qdrant/issues/4318)
The operations on `Versions` are buffered with `DatabaseColumnScheduledUpdateWrapper` in order to flush all the changes at once on demand and not when the operations are requested.
To that end there are two methods for tracking deletions and insertion independently:
```rust
pub fn put<K, V>(&self, key: K, value: V) -> OperationResult<()>
where
K: AsRef<[u8]>,
V: AsRef<[u8]>,
{
self.deleted_pending_persistence.lock().remove(key.as_ref());
self.insert_pending_persistence
.lock()
.insert(key.as_ref().to_vec(), value.as_ref().to_vec());
Ok(())
}
pub fn remove<K>(&self, key: K) -> OperationResult<()>
where
K: AsRef<[u8]>,
{
let key = key.as_ref(); …
```
=> Fix Versions persistence atomicity

lib/collection/src/collection/payload_index_schema.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/save_on_disk.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/snapshots.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/shard_holder.rs
Depends on: <https://github.com/qdrant/qdrant/pull/4373>
Persist the resharding driver state on disk, so we can resume it on restart.
=> Persist state in resharding driver

README.md
In the readme file, Qdrant integration links have been updated for:
1. Cohere
2. DocArray
3. LangChain: Previous link (https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/qdrant.html) redirected to a page with a `Page Not Found` message.
=> doc: update links for integrating Qdrant with Cohere, DocArray and LangChain

lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/vector_storage/chunked_vectors.rs, lib/segment/src/vector_storage/dense/appendable_mmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs, lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
The newly introduced [data consistency check](https://github.com/qdrant/qdrant/pull/4359) relies on the `get_vector_opt` from storages.
In order to detect the absence of vector, the implementation must not crash in that case.
This PR adds dedicated function to retrieve a dense vector optional on `chunked_vector` which is the in-memory representation for dense simple storage.
Before this patch the consistency check fails with:
`2024-05-31T08:22:53.090417Z ERROR qdrant::startup: Panic occurred in file lib/segment/src/vector_storage/chunked_vectors.rs at line 58: range end index 3048448 out of range for slice of length 3047424`
After it can leverage the None:
`2024-05-31T10:07:20.229041Z ERROR segment::segment: Vector storage 'dense-vector-rocksdb' is missing point Some(NumId(1461)) …
=> Add get optional vector for all storages

lib/collection/src/collection_manager/fixtures.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/collection_manager/tests/mod.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/tests/mod.rs
Fix a deadlock that could occur when a snapshot happens during an active optimization.
With our non-blocking snapshot implementation, all segments are proxied for snapshotting. When unproxying, all segments get a new unique ID assigned. This causes the active optimization to loose track of the segments, because IDs don't match up anymore. If the optimizer unproxies, we get a broken state.
More specifically, when this happens we end up with both the proxy and the wrapped segment in the segment holder. The segment is effectively placed twice in the holder now. It causes a double read, causing a deadlock.
This PRs does a few things to mitigate the problem:
- when unproxing after a snapshot, put the segment back with their original ID
- change segment ID generation to be auto incrementing, …
=> Fix deadlock caused by concurrent snapshot and optimization

lib/collection/src/collection/resharding.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/transfer/mod.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/toc/transfer.rs
Depends on: <https://github.com/qdrant/qdrant/pull/4379>
Implements the third stage in the resharding driver. It keeps replicating our new shard until we match the desired replication factor. This is dynamic and will follow the latest configured replication factor, even while it changes during this process. If we don't have enough peers to allow that number of replicas it continues early.
This does not implement the following yet, marked as TODOs:
- using the preferred shard transfer method, as configured by the user
- balance the shard distribution across the peers …
=> Replicate new shard to match replication factor in resharding driver

lib/collection/src/collection/query.rs, lib/collection/src/common/fetch_vectors.rs, lib/collection/src/common/retrieve_request_trait.rs, lib/collection/src/discovery.rs, lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/operations/universal_query/shard_query.rs, lib/collection/src/recommendations.rs, lib/segment/src/vector_storage/query/context_query.rs, lib/storage/src/rbac/ops_checks.rs
Needs #4331 
- make `VectorQuery` generic
- retrieve ids from `CollectionQueryRequest` and convert into vectors
- implement `RetrieveRequest` trait for it
- calculate avg vector with logic from `recommendations.rs`
- convert `CollectionQueryRequest` into `ShardQueryRequest`
- begin implementing `query()` fn in collection
=> universal-query: convert `CollectionQueryRequest` into `ShardQueryRequest` (resolve ids into vectors)

lib/collection/src/collection/query.rs, lib/collection/src/collection/search.rs, lib/collection/src/operations/universal_query/shard_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/segment/src/common/reciprocal_rank_fusion.rs, lib/storage/src/content_manager/toc/point_ops.rs
Needs #4360
- reuse merging from shards in both `query()` and `query_internal()`
- check filters for issues if it was a slow request
=> universal-query: finish implementation of `query()` fn in collection

.github/workflows/rust.yml
Allow failures on Windows until the issue #4419 is solved.
=> Allow failures on Windows CI

src/consensus.rs
It seems like the trace of a previous experimentation before using `chaos-testing`.
=> Remove unused chaos-test feature

lib/collection/src/collection_manager/fixtures.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/optimizers_builder.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/tests/mod.rs, lib/collection/src/update_handler.rs, tests/consensus_tests/test_triple_replication.py, tests/consensus_tests/utils.py
Extend our optimizer loop to add a new empty segment if all segments are over capacity. The capacity check is based off `max_segment_size_kb` as configured by the user.
Routing writes to segments with capacity is done in the next PR: <https://github.com/qdrant/qdrant/pull/4420>
=> Ensure we have any segment within capacity, otherwise add new one

lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/segment/src/types.rs
Needs #4380 
- adds an `order` field in `planned_query::ResultsMerge` to indicate the desired direction of merging, and merges accordingly
- converting from `ShardQueryRequest` to `PlannedQuery` now needs the collection params to determine the required order depending on the vector config
- handles previously unhandled `filter` and `score_threshold` in `LocalShard::merge_prefetches()`, either by passing it to the core_search/scroll rescoring or during regular merging
=> universal-query: Fix local shard ordering

lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/operations/universal_query/shard_query.rs
Needs #4404 
In the Query API, all vector inputs can be ids, for convenience, but we were missing to exclude those ids from the response.
=> universal-query: Exclude referenced ids

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/schema.rs, lib/api/src/rest/validate.rs, lib/collection/src/operations/universal_query/collection_query.rs
Needs #4405 
in grpc:
- restructure `ContextInput`, so that it becomes easy to handle both pairs and positive/negative lists in the future
in rest: 
- restructure context queries so that they don't repeat the label in order to be used . E.g. turn `{ query: { context: { context: [ ... ] } } }` into `{ query: { context: [ ... ] } }` 
- fixes fusion so that `{query: { fusion: "rrf" } }` actually works
both:
- renames `RecommendInput` positives and negatives to singular (same as in reco api)
=> universal-query: some interface renaming/edits

lib/collection/src/operations/types.rs, lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/transfer/helpers.rs
Needs #4406 
Defining `prefetch`es without defining a rescoring `query` does not make much sense, and makes handling ambiguous. So we rather reject this combination.
=> universal-query: Reject having prefetches without a rescoring query

lib/collection/src/operations/universal_query/planned_query.rs
I realized we were sometimes ignoring `offset` when crafting the `PlannedQuery`, specifically in the case of root-level scroll-like requests. This PR fixes this and propagates the root level offset into all the limits in prefetches
=> universal-query: Fix lost offset in planned query conversion

lib/segment/src/index/hnsw_index/graph_layers_builder.rs
This PR is a subset of changes from https://github.com/qdrant/qdrant/pull/4412.
It's a minimal change to fix flacky `test_graph_connectivity`.
There is a bug while HNSW construction. We change entry points before linking. In multithreaded environment is cause such problem: point may take entry with no links.
The solution is updating entry points after linking.
=> Hnsw update entry point after linking

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/collection_manager/tests/mod.rs, lib/collection/src/optimizers_builder.rs
Builds on top of: <https://github.com/qdrant/qdrant/pull/4416>
Alternative to: <https://github.com/qdrant/qdrant/pull/4420>
Direct new writes to the smallest segment.
This attempts a non-blocking read lock on all segments and returns the smallest one. Segments that cannot be read locked at this time are skipped. If no segment accepted a read lock, a random one is returned.
=> When selecting a segment for writing, select the smallest one

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs, tools/missed_cherry_picks.sh
Release Qdrant 1.9.5.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4343>.
=> Bump version to 1.9.5

lib/segment/src/index/hnsw_index/hnsw.rs
While running my tests I often see large logs like this
```
2024-06-11T07:47:46.191447Z DEBUG segment::index::hnsw_index::hnsw: building HNSW for 0 vectors with 7 CPUs
2024-06-11T07:47:46.191954Z DEBUG segment::index::hnsw_index::hnsw: finish main graph
2024-06-11T07:47:46.192067Z DEBUG segment::index::hnsw_index::hnsw: building additional index for field crasher-payload-keyword
2024-06-11T07:47:46.198172Z DEBUG segment::index::hnsw_index::hnsw: finish additional payload field indexing
2024-06-11T07:47:46.219346Z DEBUG segment::index::hnsw_index::hnsw: building HNSW for 0 vectors with 7 CPUs
2024-06-11T07:47:46.219883Z DEBUG segment::index::hnsw_index::hnsw: finish main graph
2024-06-11T07:47:46.220135Z DEBUG segment::index::hnsw_index::hnsw: building additional index for field …
```
=> Shortcut HNSW build on empty storages

lib/collection/src/collection/point_ops.rs, lib/collection/src/operations/types.rs, lib/segment/src/common/operation_error.rs, lib/segment/src/segment.rs
- delegates checking for a range index until segment, to unify the error to return.
- creates a new `OperationError::MissingRangeIndexForOrderBy` and improves error message
New error message:
=> order_by: don't check for index eagerly, improve error message

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.9.6-dev` after merging <https://github.com/qdrant/qdrant/pull/4443>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4345>.
=> Bump dev version to 1.9.6-dev

lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/segment/src/types.rs
This PR changes the planned query conversion to propagate every filter from the root of the query to each of the subqueries.
The motivation is so that every condition is already satisfied when merging multiple prefetches, and prevent post-filtering behavior.
=> universal-query: Propagate filters to leaf queries

lib/segment/src/data_types/vectors.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_immutable_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_immutable_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs, tests/openapi/openapi_integration/test_sparse_update.py
In the current dev version, the procedure of updating mutable sparse index didn't take into account, that there might be existing vectors with non-overlapping elements.
Those elements were not removed from the posting lists on insertion.
This PR fixes the insertion by introducing an additional optional parameter `old_vector`, which is used to properly cleaned the storage.
Dense index doesn't require old vector to do proper updates, so it is only retrieved when we are updating sparse index in-place.
=> Fix inplace updates for sparse index

lib/collection/src/shards/local_shard/query.rs, lib/collection/src/tests/fixtures.rs, lib/collection/src/tests/shard_query.rs
Fix and tests the order of the intermediate responses.
This important for some fusion requests, where the order of the prefetches in the request matters.
=> universal-query: Fix intermediate response order

lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/operations/universal_query/shard_query.rs
This PR adds a validation for the depth of the prefetches of universal queries.
This is a protection mechanism to avoid processing very large nested queries as it could be very expensive and potentially render the server irresponsive.
=> universal-query: limit max depth for prefetches

.github/workflows/rust.yml
Fixes <https://github.com/qdrant/qdrant/issues/4419>
According to various sources, the Windows CI image has been fixed. Hopefully that will no longer break our CI tests on Windows.
This PR enables our testing again, reverting <https://github.com/qdrant/qdrant/pull/4421>.
Let's run the Windows test two or three times to confirm the above.
=> Re-enable Windows CI

lib/collection/src/operations/universal_query/collection_query.rs, src/settings.rs
We are getting new warnings for fields which are used only in `main.rs` :shrug: 
```
warning: fields `grpc_port` and `slow_query_secs` are never read
--> src/settings.rs:22:9
|
18 | pub struct ServiceConfig {
|            ------------- fields in this struct
...
22 |     pub grpc_port: Option<u16>, // None means that gRPC is disabled
|         ^^^^^^^^^
...
47 |     pub slow_query_secs: Option<f32>,
|         ^^^^^^^^^^^^^^^
|
= note: `ServiceConfig` has derived impls for the traits `Clone` and `Debug`, but these are intentionally ignored during dead code analysis
= note: `#[warn(dead_code)]` on by default
warning: field `port` is never read
--> src/settings.rs:70:9
|
68 | pub struct P2pConfig {
|            --------- field in this struct
69 |     #[serde(default)]
70 |     pub port: …
```
=> Fix Rust 1.79 warnings

lib/segment/src/spaces/metric_f16/neon/dot.rs, lib/segment/src/spaces/metric_f16/neon/euclid.rs, lib/segment/src/spaces/metric_f16/neon/manhattan.rs, src/common/debugger.rs
On mac, these lints appeared with the latest rust version
=> macos lints: allow missing_safety_doc and dead_code

tests/openapi/openapi_integration/helpers/collection_setup.py, tests/openapi/openapi_integration/test_query_full.py
This PR introduces test for the new query API using several named vectors of different types:
- dense
- sparse
- multivector
The goal is to provide a larger safety net as we start to change the internals significantly.
=> universal-query: API testing with multi named vectors

lib/collection/src/operations/universal_query/mod.rs, lib/collection/src/operations/universal_query/planned_batch_query.rs, lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/operations/universal_query/planned_query_batch.rs, lib/collection/src/shards/local_shard/query.rs
Makes and tests the required transformations to turn multiple `PlannedQuery`s into a single `PlannedQueryBatch`, which holds all searches and scrolls to be performed at once.
Also gets rid of including an Arc inside of the `PlannedQuery`, as it is not its responsibility
=> universal-query: Plan batch queries

Cargo.lock, Cargo.toml
This PR bump itertools to [0.13.0](https://github.com/rust-itertools/itertools/blob/master/CHANGELOG.md#0130) released 1 month ago but Dependabot did not pick it up.
There was build incompatibility with the strum crate which I resolved by updating `strum_macros` to 0.26.4.
Check this [issue](https://github.com/rust-itertools/itertools/issues/942) out for more information.
=> Update to Itertools 0.13.0

lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/shards/local_shard/shard_ops.rs
Edits the `do_planned_query` function into a `do_planned_query_batch`, to generalize into a handling batch queries.
Most of the function is the same (doing searches and scrolls), but introduces extra complexity when fetching payload and vectors. 
This complexity comes from the fact that points may be deleted between search/scroll and after merging, so we now ignore those points which are not there anymore.
=> universal-query: Execute batch queries in `LocalShard`

lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/shard_trait.rs
simply adds a new `query_batch` fn to the `ShardOperations` trait.
The remote shard implementation is not yet here because we will add the required types and conversions in a subsequent PR
=> universal-query: add `query_batch` to `ShardOperations`

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/query.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/read_ops.rs, lib/collection/src/shards/resolve.rs, lib/storage/src/content_manager/toc/point_ops_internal.rs, src/tonic/api/points_internal_api.rs
To make it easy to review I've created separate methods to handle the batch queries. The single request version will be removed shortly.
=> universal-query: batch in internal service

lib/segment/benches/sparse_index_build.rs, lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/tests/integration/sparse_discover_test.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/benches/search.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_immutable_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_immutable_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/migrate.rs, lib/sparse/src/index/mod.rs, lib/sparse/src/index/search_context.rs
This PR integrates new compressed posting lists into `VectorIndexEnum`.
It doesn't affect the actual behavior (non-compressed index is still used non-conditionally), so it should be safe to include this into a patch release.
=> Integrate compressed posting list (attempt 2)

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/schema.rs, lib/collection/benches/batch_search_bench.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/lookup/mod.rs, lib/collection/src/lookup/types.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/tests/sparse_vectors_validation_tests.rs, lib/collection/tests/integration/collection_test.rs, lib/collection/tests/integration/grouping_test.rs, lib/collection/tests/integration/multi_vec_test.rs, lib/collection/tests/integration/pagination_test.rs, lib/collection/tests/integration/snapshot_recovery_test.rs, lib/storage/src/rbac/ops_checks.rs, src/common/points.rs
This PR adds the `lookup_from` field on the query API both at the root and prefetch level.
To that end, a number of types have been lifted up from the `collection` crate into the `api` crate.
It is necessary because the query definition lives in the `api` crate which does not have access to the lookup types in `collection`.
I also lifted the types for grouping which will be required later.
A future PR will add the actual implementation for `lookup_from` for queries.
=> universal-query: add lookups to query API definition

lib/common/common/src/validation.rs
Fixes typos in <https://github.com/qdrant/qdrant/pull/4478>.
=> Fix typos in #4478

lib/segment/tests/integration/segment_builder_test.rs
Next attempt to fix build cancellation flaky test.
Issue https://github.com/qdrant/qdrant/issues/2723
In this PR we don't have a magic number of required building time. The building time of the non-canceled segment is not a subject of this test.
=> Fix building cancellation flaky test

lib/api/src/rest/schema.rs, tests/consensus_tests/test_order_by.py, tests/openapi/openapi_integration/test_batch_update.py, tests/openapi/openapi_integration/test_group.py, tests/openapi/openapi_integration/test_payload_selector.py
With the intention of making the interface simpler, I propose to skip serializing the optional fields in `Record` and `ScoredPoint`.
From my POV, this has two advantages:
- Less noise in the response when `with_payload` and `with_vector` are not requested.
- Less confusion from users thinking their points don't have payload/vector ("It says payload is null!")
Python client will keep deserializing them into their classes as `None` fields, though, so the advantages only apply when doing plain REST requests.
=> Skip serializing null fields in `Record` and `ScoredPoint` (REST)

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/config.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/segment/benches/sparse_index_build.rs, lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/sparse_index/sparse_index_config.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/tests/integration/fixtures/segment.rs, lib/segment/tests/integration/sparse_discover_test.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/storage/src/content_manager/conversions.rs
Depends on #4453.
This PR adds an option `datatype` with possible values of `float16` and `float32`.
It's hidden in the OpenAPI docs for now, and is not usable until `USE_COMPRESSED` is false (see below).
The switch `pub const USE_COMPRESSED: bool = false;` is added as a feature gate until the v1.10 release. When it's false, the old index format is used.
=> Add datatype option for sparse vector index

tests/openapi/openapi_integration/test_query.py, tests/openapi/openapi_integration/test_query_full.py
hotfixes tests that were expecting `payload` to always be serialized
=> hotfix: use get instead of indexing syntax in tests

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/query.rs, lib/collection/src/common/retrieve_request_trait.rs, lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/read_ops.rs, lib/collection/src/shards/shard_trait.rs, lib/collection/src/tests/shard_query.rs, lib/storage/src/content_manager/toc/point_ops.rs, lib/storage/src/content_manager/toc/point_ops_internal.rs, src/actix/api/query_api.rs, src/tonic/api/points_internal_api.rs
Uses the batch implementation everywhere, and gets rid of the single implementation. 
For single endpoints, it is a batch of 1 request.
=> universal-query: use batch implementation everywhere

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/operations/cluster_ops.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/transfer/driver.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/resharding_stream_records.rs, lib/collection/src/shards/transfer/stream_records.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, lib/storage/src/content_manager/toc/transfer.rs, src/common/collections.rs
In <https://github.com/qdrant/qdrant/pull/4373> I implemented a first iteration of point migration. In practice, transferring still appeared to be broken because a lot more had to be done for replica set state switching and shard routing.
This PR does all that needs to be done in terms of shard transfers to make resharding work. Specifically, to actually migrate points from all shards to the new target shard, and to replicate the new shard matching the configured replication factor.
Most importantly, this does:
- support transfers with a different source/target shard (for resharding)
- extend the unique shard key with a target shard field (for resharding)
- resharding transfer must merge points in target shard, it should not …
=> Properly integrate replica set state switching in resharding transfers

docs/redoc/master/openapi.json, lib/api/src/rest/schema.rs, openapi/openapi-main.ytt.yaml, src/actix/api/query_api.rs, src/schema_generator.rs, tests/consensus_tests/auth_tests/test_jwt_validation.py, tests/consensus_tests/test_points_query.py, tests/openapi/openapi_integration/test_query.py, tests/openapi/openapi_integration/test_query_full.py
Introduces `QueryResponse` in rest api response, which allows our futures selves to extend it with other fields like `explain`, `total`, etc
=> universal-query: Add layer of response structure specific to query

lib/api/src/grpc/conversions.rs, lib/collection/src/collection/point_ops.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/collection/search.rs, lib/collection/src/hash_ring.rs, lib/collection/src/shards/replica_set/execute_read_operation.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/shard_holder.rs, lib/segment/src/index/query_estimator.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/query_checker.rs, lib/segment/src/problems/unindexed_field.rs, lib/segment/src/types.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
This PR reworks `CommitHashRing` into three separate operations: `CommitRead`, `CommitWrite` and `Finish`.
We need all three to make resharding process seem "transparent" to the user.
We don't (yet) properly track resharding state, so this PR adds some "stubs" and `TODO`s in places where we will introduce state later.
=> Rework `CommitHashRing` consensus message into `CommitRead`/`CommitWrite`/`Finish`

tests/consensus_tests/test_points_query.py
This PR enables tests for the query API using `order_by` that were broken.
Actually, there was no bug on the server side but the tests were not using the query API properly :face_with_head_bandage:
=> universal-query: Fix query order_by tests

lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/transfer/resharding_stream_records.rs
Depends on: <https://github.com/qdrant/qdrant/pull/4480>
Allow resharding migration transfers within the same node. It's a special case where the source and target shard are on the same machine, while our shard transfer mechanism doesn't support this.
This scenario must be supported if there's only one shard replica, exclusively on the node having the new target shard.
It's an initial approach, still relying on some building blocks of shard transfers and remote shards. It still talks over gRPC channels, but to itself. Eventually I'd like to improve upon this to migrate points from one shard replica to another directly instead of relying on transfers. But that requires significant refactoring as various components, such as our …
=> While resharding, support migrating points on a node locally

lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/transfer/resharding_stream_records.rs
Implement the 5th resharding stage: delete migrated points from their old shards.
This is a naive implementation, but it is functional. We can improve upon this later.
=> Propagate deletes for resharding, delete migrated points

lib/collection/src/shards/mod.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/snapshot.rs, lib/collection/src/shards/transfer/wal_delta.rs, lib/storage/src/content_manager/toc/transfer.rs
Implement the hashring commit stage in the resharding driver.
Commit the read and write hashrings separately and sync the cluster in both cases after doing so.
=> Commit read/write hashrings while resharding

lib/collection/src/operations/cluster_ops.rs, lib/collection/src/save_on_disk.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/tasks_pool.rs
This simplifies the resharding stages we have. We now don't have start/end variants anymore, but a single variant for each stage.
It also adds a method to describe the current stage in human readable format. This will be connected to the cluster info later to show the current progress to users.
=> Simplify resharding stages, add method to describe current stage for humans

lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/shard_holder.rs
Depends on: <https://github.com/qdrant/qdrant/pull/4491>
A user may configure incoming and outgoing shard transfer limits. This PR makes sure to respect these limits during resharding.
This also selects peers with the lowest number of shards while replicating to balance the shard distribution.
=> While resharding, respect configured shard transfer limits

Cargo.lock, lib/collection/benches/batch_search_bench.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/collection/sharding_keys.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/snapshots.rs, lib/collection/src/shards/replica_set/update.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/tests/fix_payload_indices.rs, lib/collection/src/tests/mod.rs, lib/collection/src/tests/shard_query.rs, lib/collection/src/tests/wal_recovery_test.rs, lib/collection/src/update_handler.rs, lib/segment/Cargo.toml, lib/segment/src/segment.rs, lib/segment/src/types.rs, tests/consensus_tests/fixtures.py, tests/consensus_tests/test_segment_max_size.py
We had a case where payload indexes were missing from some segments. This was caused by <https://github.com/qdrant/qdrant/pull/4416> not configuring these.
This primarily does two things:
- when creating a new appendable segment (if all are at max_segment_size capacity), create configured payload indexes in them
- when loading segments, re-apply the configure payload indexes if there are any differences
It can easily be tested with the following command, where before this PR it would not index a lot of points:
```bash
bfb -n 100000 -d 256 --keywords 10 --indexing-threshold 0 --max-segment-size 1000
```
3. [x] Have you checked your code using …
=> Fix new appendable segments not having payload indices

lib/segment/benches/multi_vector_search.rs, lib/segment/benches/sparse_index_build.rs, lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/tests/integration/batch_search_test.rs, lib/segment/tests/integration/byte_storage_hnsw_test.rs, lib/segment/tests/integration/byte_storage_quantization_test.rs, lib/segment/tests/integration/exact_search_test.rs, lib/segment/tests/integration/filtrable_hnsw_test.rs, lib/segment/tests/integration/hnsw_discover_test.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs, lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs, lib/segment/tests/integration/multivector_hnsw_test.rs, lib/segment/tests/integration/multivector_quantization_test.rs, lib/segment/tests/integration/sparse_discover_test.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/mod.rs
Based on #4454.
This PR removes `build_index()` method from `VectorIndex` implementation. Instead, the index is getting built inside `open()`.
Reason:
- For sparse vectors, it's already weird to have a separate `build_index()` method (it's getting rebuilt in `open()` in case of migration/missing files). Related comment: https://github.com/qdrant/qdrant/pull/4453#discussion_r1637799716
- For plain index, `build_index()` is a no-op.
- The remaining one trait implementation is HNSW. We can remove it for consistency with other trait implementations; and to avoid initializing it in an inconsistent state (like, when the index is "loaded", but not actually valid).
=> Move build_index out of VectorIndex

docs/redoc/master/openapi.json, lib/collection/src/operations/types.rs, lib/segment/src/index/sparse_index/sparse_index_config.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/sparse/benches/search.rs, lib/sparse/src/common/types.rs, lib/sparse/src/index/compressed_posting_list.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_immutable_ram.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/search_context.rs
This PR add Uint8 quantization for the sparse vector index.
Depends on #4490.
task | ram | ram_c32 | ram_c16 | ram_q8
| - | -: | -: | -: | -:|
random-50k | 0.78408<br>0% | 0.98727 <br> +25% | 1.1809 <br> +50% | 1.0488 <br> +33%
random-500k | 7.2848<br>0% | 8.7678 <br> +20% | 10.746 <br> +47% | 9.5777 <br> +31%
neurips2023-1M | 12.374<br>0% | 13.244 <br> +7% | 14.783 <br> +19% | 13.539 <br> +9%
neurips2023-full-25pct | 28.023<br>0% | 31.649 <br> +12% | 35.216 <br> +25% | 31.377 <br> +11%
movies | 3.3650<br>0% | 4.1182 <br> +22% | 4.6996 <br> +39% | 4.1280 <br> +22%
task | ram | ram_c32 | ram_c16 | ram_q8
| - | -: | -: | -: | -:|
random-50k | 0.18915<br>0% | 0.19317 <br> +2% | 0.19577 <br> +3% | 0.20082 <br> +6%
random-500k | 1.6066<br>0% | 1.6242 <br> +1% | 1.6740 <br> +4% | 1.7004 <br> …
=> U8 quantization for sparse vector index

docs/redoc/master/openapi.json, lib/collection/src/config.rs, lib/collection/src/operations/types.rs, lib/segment/benches/sparse_index_build.rs, lib/segment/src/index/sparse_index/sparse_index_config.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/tests/integration/sparse_discover_test.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
Fixup for #4514.
Drop `SparseVectorIndexDatatype` in favor of `VectorStorageDatatype`, as requested by @generall.
=> Drop SparseVectorIndexDatatype in favor of VectorStorageDatatype

lib/collection/src/grouping/group_by.rs, lib/collection/src/recommendations.rs, tests/openapi/openapi_integration/test_multicollection_reco.py
This PR fixes a bug in the current recommendation (discovered while working on https://github.com/qdrant/qdrant/pull/4508)
The recommendation API excludes from the results the vector ids used in the query (positives & negatives).
However, this should not happen when using `lookup_from` as the ids are pointing to a different collection.
=> Fix id exclusion when recommending from a different collection

lib/segment/src/index/sparse_index/sparse_vector_index.rs
This check prevented converting from 1.9.3 or 1.9.4 into newer versions, causing a panic in 1.9.5 or 1.9.6.
Removing this check makes us convert in all cases, which is what we want.
I've manually tested the conversion to work between versions:
- 1.8.4 -> PR
- 1.9.0 -> PR
- 1.9.2 -> PR
- 1.9.3 -> PR
=> Fix sparse vector mmap index conversion panic

src/actix/mod.rs, tools/sync-web-ui.sh
The web-ui `/dashboard` endpoint can currently be embedded as an iframe. Adding the header `X-Frame-Options: DENY` shall protect against it.
In terms of the approach taken with actix_web, it would have been ideal if `actix_files::Files` allowed to set HTTP headers, but it only allows a handful of flags like `etag`, `last_modified` or `content_disposition`, which fall short of our needs.
This is why for the root path reading the `index.html` file a custom handler has been introduced: `web_ui_index`.
Awaiting for feedback in the approach before writing any kind of tests.
3. [x] Have you checked your code using `cargo clippy --all --all-features` …
=> Fix web UI index path http security headers

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs, tools/missed_cherry_picks.sh
Release Qdrant 1.9.7.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4443>.
=> Bump version to 1.9.7

lib/collection/src/discovery.rs, lib/collection/src/operations/types.rs, tests/openapi/openapi_integration/test_discovery.py
Similar to https://github.com/qdrant/qdrant/pull/4551 but for the discovery API.
Additionally the `lookup_from` was wrongly used for the `using` field of the search query.
=> Fix discovery API id exclusion and lookup

lib/collection/src/collection_manager/collection_updater.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/shards/local_shard/scroll.rs, lib/collection/src/shards/local_shard/shard_ops.rs
Slight improvement. I have modified the return type of `SegmentsSearcher::retrieve` function to return the produced hashmap directly, to let the callers decide how to process it. 
Sometimes we were re-collecting it into a hashmap right away, which didn't make much sense
=> Make `SegmentsSearcher::retrieve` return a hashmap

lib/collection/src/collection/query.rs, lib/collection/src/common/fetch_vectors.rs, lib/collection/src/common/retrieve_request_trait.rs, lib/collection/src/operations/universal_query/collection_query.rs, lib/storage/src/content_manager/toc/point_ops.rs, lib/storage/src/rbac/ops_checks.rs, tests/consensus_tests/auth_tests/test_jwt_validation.py, tests/openapi/openapi_integration/test_query.py, tests/openapi/openapi_integration/test_query_full.py
This PR implements the logic for the `lookup_from` field on the query API.
Most of the complexity comes from resolving ids from different collections.
This change also makes sure `lookup_from` behave according to the user token.
=> universal-query: lookup_from implementation

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.9.8-dev` after merging <https://github.com/qdrant/qdrant/pull/4558>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4445>.
=> Bump dev version to 1.9.8-dev

lib/collection/src/collection/resharding.rs, lib/collection/src/shards/shard_holder/resharding.rs
Currently based on #4561.
Basically, subject. Stop task when `Resharding::Finish` or `Resharding::Abort` consensus message is received, similar to how shard transfer task is handled.
=> Stop resharding task on resharding finish and abort

lib/segment/src/common/validate_snapshot_archive.rs
Before, file contents were simply dumped to the end user if reading an (arbitrary) snapshot file failed. This now masks the error, and only reports the real error in stdout.
Try:
```json
PUT /collections/pentest/snapshots/recover
{
"location": "file:///etc/passwd"
}
```
Before, it showed:
```json
{
"error": "Service internal error: IO Error: numeric field was not a number: login\nsy when getting cksum for root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nbin:x:2:2:bin:/bin:/"
}
```
Now it shows:
```json
{
"error": "Service internal error: Failed to open snapshot archive, malformed format"
}
``` …
=> When opening a snapshot file, mask its contents on error

lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
* Set `USE_COMPRESSED` to true to enable sparse vector.
* Switch to using compressed posting lists in tests.
=> Set USE_COMPRESSED to true

lib/common/memory/src/mmap_ops.rs, lib/segment/src/vector_storage/chunked_utils.rs
There is a possibility to fails with file creation. Crash may happen between file creation and settings size. Solution: create temporary file and rename when ready
=> Atomic create_and_ensure_length

Cargo.lock, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/common/common/src/disk.rs, lib/common/common/src/lib.rs, lib/segment/Cargo.toml, lib/segment/src/common/mod.rs, lib/segment/src/common/operation_error.rs
/claim #4297
What this does is checks if there is twice as much free space on the volume as what the collection being optimized already takes.
I'm not happy with this, and I'm not sure this submission worth the hassle as it is, but I'd like to compare opinions.
* The free space checking works synchronously; even though the optimizations themselves take up background threads, I feel uneasy about it.
* The checking happens in the moment the optimization is about to start, not well beforehand.
* We still might run into OOD down the line because FS is non-atomic.
* It still logs the error, perhaps we want to special-case it as we do with `CollectionError::Cancelled`.
* Capture write error from `db.put_cf_opt`; it first happens somewhere around …
=> Fail early when encountering out-of-storage during optimization

lib/collection/src/collection/point_ops.rs, lib/collection/src/tests/points_dedup.rs, lib/segment/src/data_types/order_by.rs
Once implementing resharding deduplication, we introduced deduping by id. However, this broke one behavior for `order_by` in scroll: to repeat points if they had multiple values to order from.
With these changes now we output consistent (value, id) order, and we de-duplicate on the combination too.
=> order_by: Order by value, then id. Dedup by both

src/actix/mod.rs, src/actix/web_ui.rs
Follow up of https://github.com/qdrant/qdrant/pull/4517 separating web_ui into a mod and adding some tests. This way that part of the actix app can grow into a maintainable piece of code.
=> Extract web ui factory into module with tests

.github/workflows/integration-tests.yml, Cargo.lock, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/common/common/src/disk.rs, lib/common/common/src/lib.rs, lib/segment/Cargo.toml, lib/segment/src/common/mod.rs, tests/low-disk/create_and_search_items.py, tests/low-disk/low-disk.sh
Automate a test scenario for OutOfDisk error during indexing.
Scenario:
Limit Qdrant container disk to ~10 MB
1. create collection with "indexing_threshold": 0 (disabled indexing)
2. add points
3. enable indexing
4. wait for indexing
5. send a search request
Expected behavior: indexing should gracefully fail without crushing a container and post a log message, the container should continue running and accept search requests.
=> Add test for OOD during indexing

lib/collection/src/operations/types.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/transfer/resharding_stream_records.rs, lib/collection/src/shards/transfer/stream_records.rs
Follow-up to #4516.
Resharding shard transfer initializes `ForwardProxyShard` that forwards incoming updates from local shard `X` to remote shard `Y`.
In such case, `ForwardProxyShard` should additionally split operation by shard, and only forward a *part* of operation, that belongs to the remote shard.
E.g.:
- we are resharding from 2 shards to 3 shards
- there's a resharding shard transfer from shard 1 to shard 3
- and so, there's a `ForwardProxyShard` from shard 1 to shard 3
- user sends `upsert 42, 69, 128, 228, 666, 1337`
- we split-by-shard on the collection/shard-holder level and get
- shard 1: `upsert 42, 128, 228`
- shard 2: `upsert 69, 666, 1337`
- shard 3: `upsert 42, 69`
- now, imagine if we go down the callstack, to the local shard of shard 1 replica set
- …
=> Split-by-shard when forwarding operations during resharding shard transfer

lib/segment/src/vector_storage/dense/dynamic_mmap_flags.rs
I think `DynamicMmapFlag::count_flags` is not entirely correct as it relies on the `get` function to verify if a given position is set.
```rust
pub fn get<TKey>(&self, key: TKey) -> bool
where
TKey: num_traits::cast::AsPrimitive<usize>,
{
let key: usize = key.as_();
if key >= self.status.len {
return false;
}
self.flags[key]
}
```
However this function shortcuts any lookup for keys above `self.status.len` which prevents us from getting the real number of positive flag to subtract.
This PR proposes to look directly into the `flags` to fix the count.
=> Fix DynamicMmapFlag counting by not using get proxy

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/collection_ops.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/shard_holder/mod.rs
Depends on: <https://github.com/qdrant/qdrant/pull/4509>
Adds resharding status information to the gRPC API and REST API
=> Add resharding status to API

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.10.1-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4559>.
=> Bump dev version to 1.10.1-dev

Cargo.lock, lib/segment/Cargo.toml
Dependabot is not keeping `charabia` on its radar.
- https://github.com/meilisearch/charabia/releases/tag/v0.8.11
- https://github.com/meilisearch/charabia/releases/tag/v0.8.10
- https://github.com/meilisearch/charabia/releases/tag/v0.8.9
=> charabia 0.8.11

lib/collection/src/shards/resharding/driver.rs
Fix the resharding transfer limit check being inverted.
This also fixes the resharding replication stage getting stuck.
=> Fix resharding replication getting stuck, transfer limit was inverted

lib/segment/src/common/utils.rs, lib/segment/src/index/field_index/histogram.rs, lib/segment/src/index/field_index/numeric_index/mod.rs
This PR replaces `segment::common::utils::bound_map()` with `std::ops::Bound::map()` which is stabilized in 1.77.
=> Use stabilized Bound::map

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/update_handler.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment.rs, lib/segment/tests/integration/segment_tests.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
It's always flushing, isn't it? 😂🔫
Let's look at [`Segment::flush`] implementation first:
- there's a [check at the top][segment-flush-version-change-check] that checks if current version of the segment changed since last flush
- if current version *did not* change since last flush
- we "skip" flushing
- and report current segment version as "successfully flushed"
Generally, this behavior is desirable: it allows us to "skip" flushing if no changes were applied to the segment in between two flushes.
But let's look at [`LocalShard::load_from_wal`] now:
- during `load_from_wal` we (re-)apply all un-acknowledged operations from the WAL
- these operations may be *older* than the version of the segment the operations applied to
- most of these operations will be skipped due to further version …
=> Workaround for "missing payload" bug

lib/collection/src/collection/query.rs, tests/openapi/openapi_integration/test_query.py
We forgot to handle the `score_threshold` parameter when it was present in the root query. This PR fixes it.
We only need to handle it for fusions because it is the only case where we generate a new scoring at collection level.
For the other cases, it should already be resolved from shard level
=> universal-query: handle score threshold at collection level

lib/segment/src/common/mod.rs, lib/segment/src/common/score_fusion.rs
Adds an internal method for making parametrized score fusions, currently with:
- Normalizations
- MinMax
- Distribution-based
- Combinators
-  Sum
- Weighting
- Ordering
=> Fusions: add score fusion internals

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/common/common/Cargo.toml, lib/common/common/src/lib.rs, lib/common/common/src/mmap_hashmap.rs, lib/common/memory/Cargo.toml, lib/segment/Cargo.toml, lib/sparse/Cargo.toml, lib/storage/Cargo.toml
Tracking issue: #4502.
This PR adds `MmapHashMap`, an on-disk hash map baked by a memory-mapped file.
Some design decisions:
- Use `zerocopy` as a sound/safe alternative to our [`mmap_ops`](https://github.com/qdrant/qdrant/blob/v1.10.0/lib/common/memory/src/mmap_ops.rs#L124-L188).
- Put the implementation into the `lib/common/common` crate. It wouldn't make compilation of this crate noticeable slower.
- Make `MmapHashMap::create()` take `BTreeMap<String, BTreeSet<u32>>`, not `impl Iterator<…>`. Since this structure would be used in a single place (`segment`), we could hardcode it to take a specific data structure for better compile times.
=> Add MmapHashMap

lib/collection/src/shards/resharding/driver.rs, tests/consensus_tests/test_resharding.py, tests/consensus_tests/test_shard_wal_delta_transfer.py, tests/consensus_tests/utils.py
Add a few resharding integration tests in our consensus testing suite.
Currently this covers:
- reshard 3 times in sequence, asserts shard/point counts and point data consistency
- reshard 5 times in sequence, asserts replicas are automatically balanced on peers
- reshard 3 times with concurrent inserts, updates and deletes, asserts shard/point counts and point data consistency 
Later we may extend this with even more complex scenarios as we see fit.
=> Add resharding tests

docs/redoc/master/openapi.json, openapi/openapi-service.ytt.yaml
This PR proposes a fix for "/" response structure
During implementing https://github.com/qdrant/qdrant-client/pull/678
It was found out, that openapi scheme for `"/"` is no coherent with the actual implementation:
https://github.com/qdrant/qdrant/blob/851f03bbf6644116da56f6bc7b0baa04274e8057/docs/redoc/master/openapi.json#L200-L225
As it can be seen, it returns an object with `result`, `time`, `status` keys, however the actual implementation just returns an http response with `VersionInfo`
https://github.com/qdrant/qdrant/blob/851f03bbf6644116da56f6bc7b0baa04274e8057/src/actix/mod.rs#L48-L51
Usually, we use `accepted_response` or `process_response` methods, e.g. like in:
https://github.com/qdrant/qdrant/blob/851f03bbf6644116da56f6bc7b0baa04274e8057/src/actix/api/collections_api.rs#L52-L61 …
=> fix: fix root response structure

lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/update.rs
Fixes <https://github.com/qdrant/qdrant/issues/4629>
Prevents a shard becoming unresponsive because the last replica was locally disabled. This was possible when using medium/strong ordering. Now it does not allow locally disabling the last replica anymore.
I believe is the simplest approach and covers both scenarios we spoke about, for having just one or multiple replicas.
=> Don't disable last peer locally

lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs, lib/segment/src/common/rocksdb_wrapper.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs, lib/segment/src/index/field_index/map_index/immutable_map_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/map_index/mutable_map_index.rs, lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/tests.rs, lib/segment/src/payload_storage/on_disk_payload_storage.rs, lib/segment/src/payload_storage/simple_payload_storage.rs
If the user sends "delete by filter" requests, which request will do the following things:
- Mark point as deleted (persisted on flush)
- Remove associated payload from rocksdb (persisted at random moment)
If the service is killed before delete flags are persisted, but after payload removals, on recover from WAL we won't be able to delete partially deleted point, because we won't have payload anymore to identify it.
This PR changes persistence of payload storage to enforce persistence on flush in the same way it is enforced in IdTracker for Id mapper.
Important: further implementations of payload index, which won't rely on rocksdb _must_ also ensure that deletes are only persisted on flush.
=> Ensure payload is deleted on flush only

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs, tools/missed_cherry_picks.sh
Release Qdrant 1.10.1.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4558>.
=> Bump version to 1.10.1

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.10.2-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4603>.
=> Bump dev version to 1.10.2-dev

docs/grpc/docs.md, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/operations/universal_query/collection_query.rs, src/actix/api/query_api.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, tests/basic_query_grpc_test.sh, tests/consensus_tests/auth_tests/test_jwt_access.py
Follow up on https://github.com/qdrant/qdrant/pull/4616 for the gRPC API.
I introduced `CollectionQueryGroupsRequest` as a convergence type for REST and gRPC.
=> universal-query: gRPC group API

lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs, lib/segment/src/index/field_index/immutable_point_to_values.rs, lib/segment/src/index/field_index/map_index/immutable_map_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/map_index/mutable_map_index.rs, lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/tests.rs, lib/segment/src/index/query_optimization/condition_converter.rs
Tracking issue: #4502.
Integration of this PR https://github.com/qdrant/qdrant/pull/4641.
This PR changes signature of `[ImmutablePointToValues::get_values](https://github.com/qdrant/qdrant/blob/field-index-values-as-iterator-instead-of-slice/lib/segment/src/index/field_index/immutable_point_to_values.rs#L36)`
We cannot use slice anymore because we cannot store slice of strings in mmap file. Instead, `get_values` returns values iterator.
=> Field index values as iterator instead of slice

lib/segment/src/spaces/metric_uint/avx2/cosine.rs, lib/segment/src/spaces/metric_uint/neon/cosine.rs, lib/segment/src/spaces/metric_uint/simple_cosine.rs, lib/segment/src/spaces/metric_uint/sse2/cosine.rs
Fixes: <https://github.com/qdrant/qdrant/issues/4654>
Fixes NaN score on for zero vectors using the uint8 data type.
This occurred on machines supporting SSE2, AVX or NEON. The naive implementation was fine.
Our naive implementation prevents this with a zero norm check. I've added the same check in the above mentioned implementations: https://github.com/qdrant/qdrant/blob/85b0c5ba8f90e18cc3ec1f6096513b4a9ab37a30/lib/segment/src/spaces/metric_uint/simple_cosine.rs#L72-L74
Note that I did not test the NEON implementation myself as I don't have hardware available for it. Since the change is so simple, I'm not worried about problems. …
=> Fix NaN score for zeroed uint8 vectors

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/schema.rs, lib/api/src/rest/validate.rs, lib/collection/src/collection/query.rs, lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/operations/universal_query/shard_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/segment/src/common/score_fusion.rs, tests/openapi/openapi_integration/helpers/helpers.py, tests/openapi/openapi_integration/test_query.py
Needs #4601 
Exposes the ability to use [distribution-based score fusion](https://medium.com/plain-simple-software/distribution-based-score-fusion-dbsf-a-new-approach-to-vector-search-ranking-f87c37488b18) as 
```javascript
{
"prefetch": [ ... ],
"query": { "fusion": "dbsf" }
}
```
=> universal-query: Distribution-Based Score Fusion

lib/segment/src/index/payload_index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs, lib/segment/src/payload_storage/payload_storage_base.rs, lib/segment/src/payload_storage/payload_storage_enum.rs, lib/segment/src/payload_storage/simple_payload_storage_impl.rs
Current full payload update deletes existing payload and then writes a new one, which is:
- sub-optimal
- may lead to the lost payload if the service is killed with partial flush (not verified)
=> Fix full payload update

lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs, lib/segment/src/index/field_index/immutable_point_to_values.rs, lib/segment/src/index/field_index/map_index/immutable_map_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/map_index/mutable_map_index.rs, lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/query_optimization/condition_converter.rs
Attempt to fix performance after https://github.com/qdrant/qdrant/pull/4644
Instead of `Box<dyn Iterator>` use lambda with check.
=> Remove dyn iterator from field condition checker

lib/collection/src/collection/point_ops.rs, lib/collection/src/collection/search.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/shard_holder/mod.rs, lib/collection/src/shards/shard_holder/resharding.rs, tests/consensus_tests/test_resharding.py, tests/consensus_tests/utils.py
Depends on: #4609
This PR ensures that reads and point counting remain consistent while resharding is going on. It adds some tests to assert this behavior.
Most importantly, two changes in our read/filtering logic were required:
1. don't always apply resharding point filter, apply on _old_ shards, but not the _new_ shard
2. `select_shards` should include the _new_ shard on read hash ring commit (right after migrating points)
Tests cover stability assertions for point counts, scrolling and the query API. For each test we reshard 3 times in sequence and make sure the responses remain exactly the same.
3. [x] Have you checked …
=> Make reads and point counts consistent during resharding 

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/segment/Cargo.toml, lib/segment/src/json_path/mod.rs
Tracking issue: #4502.
This PR adds the method `JsonPath::filename()`. It would be used as a directory name for on-disk indices.
=> Add JsonPath::filename()

lib/collection/src/collection/point_ops.rs, lib/collection/src/collection/query.rs, lib/collection/src/collection/resharding.rs
Apply resharding filter from <https://github.com/qdrant/qdrant/pull/4617> to the query API.
This ensures consistent reads from the query API, including <https://github.com/qdrant/qdrant/pull/4619>/<https://github.com/qdrant/qdrant/pull/4657>.
=> Apply resharding filter to query API for consistent reads

lib/collection/src/collection/resharding.rs, lib/collection/src/shards/resharding/tasks_pool.rs, lib/collection/src/shards/shard_holder/mod.rs, lib/collection/src/shards/shard_holder/resharding.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, src/main.rs, tests/consensus_tests/test_resharding.py, tests/consensus_tests/utils.py
Depends on: <https://github.com/qdrant/qdrant/pull/4617>
Allow the resharding driver to resume at any arbitrary point. This allows the driving node to restart as if nothing has happened.
There is more to be done in terms of resumption and the ability to abort, but that'll be for separate PRs.
A new test is added interrupting the process at various stages, asserting the end result is what we expect.
=> Resume resharding driver on node restart

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/segment/src/data_types/index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/types.rs, lib/segment/tests/integration/payload_index_test.rs, lib/segment/tests/integration/segment_builder_test.rs
Replaces #4652 
In this version we don't automatically decide on a defragmentation key and only defragment if a user configured Qdrant to do so.
If we still agree on doing otherwise and intelligently try to automatically find a key to use for defragmentation, we can still implement this in a separate PR.
Also note that this PR only uses the first found key configured as tenant. To fix this, we need to agree on an algorithm for applying multiple keys, which I also suggest to use in a separate PR.
=> Defragmentation in api

lib/collection/src/grouping/group_by.rs, lib/collection/src/grouping/types.rs
When using the grouping API with prefetches, it is necessary to size the inner `limit` according to the number of groups to expand the space of values inspected.
=> universal-queries: Size prefetches according to number of groups

tests/consensus_tests/test_resharding.py, tests/consensus_tests/utils.py
The resharding CI test with concurrent updates appears to be a bit too heavy. I've seen some flakyness due to it timing out.
This attempts to fix that by doubling the allowed wait time.
Example failures:
- https://github.com/qdrant/qdrant/actions/runs/9957803914/job/27510643527?pr=4617#step:11:131
- https://github.com/qdrant/qdrant/actions/runs/9976681020/job/27569481287?pr=4682#step:11:131
- https://github.com/qdrant/qdrant/actions/runs/9980253921/job/27581182721#step:11:131
=> Fix flaky resharding CI test

lib/collection/src/collection/resharding.rs, lib/collection/src/save_on_disk.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
Depends on: <https://github.com/qdrant/qdrant/pull/4666>
When starting the resharding driver, wipe any existing state that may have been left on disk.
This prevents unintentionally trying to resume a resharding operation that has already been aborted, but wasn't cleaned up properly. It is important not to corrupt the cluster.
Resuming the operation on restart works fine, as this does not wipe the state file.
=> On resharding start, wipe any existing state

lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/resharding/stage_commit_hashring.rs, lib/collection/src/shards/resharding/stage_finalize.rs, lib/collection/src/shards/resharding/stage_init.rs, lib/collection/src/shards/resharding/stage_migrate_points.rs, lib/collection/src/shards/resharding/stage_propagate_deletes.rs, lib/collection/src/shards/resharding/stage_replicate.rs
The resharding driver logic was all contained in a single file that was becoming quite large.
This splits all the stages into separate modules.
It is a basic refactoring step that we'll eventually improve upon once all the bits and bots are there.
This has no logic changes.
=> Refactor resharding driver, extract stages into modules

src/common/telemetry_ops/app_telemetry.rs
After float16 and byte vectors support, we use more instruction sets. This PR adds them to the telemetry info
=> add more instructions set into cpu info telemetry

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/operations/types.rs, lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/shards/local_shard/scroll.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/fixtures/payload_context_fixture.rs, lib/segment/src/id_tracker/id_tracker_base.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/segment.rs
Implements reading randomly from segments.
The way it reads is not entirely optimal for large limits (it has rejection sampling to avoid repetition), but since we will not promise stable random output, offset won't affect the limit. In other words, it should be "fine" for most use-cases.
The other thing changed here is that I've edited the `QueryScrollRequestInternal` so that ordering is always specified, as by id, by field, or random.
=> random-query: Implement random reads from segments up to local shard

lib/collection/src/shards/resharding/tasks_pool.rs
The resharding status shows a timer. I recently changed the prefix to 'since' because I thought we restarted the timer with each stage.
That's not what happens so I suggest to change it back.
It now looks like:
```json
{
"resharding_operations": [
{
"shard_id": 1,
"peer_id": 4986007364297101,
"direction": "up",
"shard_key": null,
"comment": "replicate: replicate new shard to other peers, started 6s ago"
}
]
}
```
=> Prefix resharding timer with started, not since

lib/segment/src/index/field_index/histogram.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/tests/histogram_test_utils.rs, lib/segment/src/index/field_index/tests/histogram_tests.rs
This PR is a part of on-disk-payload-feature.
For the on-disk numeric index, it was decided that the histogram would be still on RAM because it's pretty small. But we need persistence anyway to avoid a full scan while loading.
This PR adds save-load for histogram and use it in histogram unit test.
=> Histogram save load

Cargo.lock, Cargo.toml, lib/segment/Cargo.toml, lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/index_selector.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/tests.rs
```rust
// This PR replaces this trait (old):
trait ValueIndexer<T> {
…
}
// With this trait (new):
trait ValueIndexer {
type ValueType;
…
}
```
We have this implementation of `build_field_indexes`: https://github.com/qdrant/qdrant/blob/v1.10.1/lib/segment/src/index/struct_payload_index.rs#L172-L191
How it build both appendable and non-appendable segments: it creates mutable index no matter what kind of segments it builds, and appends point into it. It assumes ("the assumption") that we have two kind of payload indices: mutable and immutable; and both of them use the same on-disk representation (aka rocksdb).
The on-disk payload index doesn't fit into this model: it's immutable and it doesn't have a mutable counterpart.
I am trying to untangle this code by moving "the assumption" from the …
=> Make ValueIndexer trait non-generic

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/schema.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/operations/universal_query/collection_query.rs, tests/openapi/openapi_integration/test_query_full.py
This PR adds the support for `lookup_from` in the query group API which was missing from https://github.com/qdrant/qdrant/pull/4656
It enables to reproduce the legacy recommend groups API.
=> universal-search: Query group API should support lookup_from

lib/common/common/src/mmap_hashmap.rs
Tracking issue: #4502.
This PR removes unnecessary lifetime constraints from MmapHashMap. Fixup for #4612/#4648.
=> Fixup for MmapHashMap

Cargo.lock, lib/common/memory/src/mmap_ops.rs, lib/segment/Cargo.toml, lib/segment/src/index/field_index/mmap_point_to_values.rs, lib/segment/src/index/field_index/mod.rs
This PR introduces a mmap analog of `ImmutablePointToValues`, which is required for mmap field indexes.
`MmapPointToValues` has almost the same API. The main difference is that the method returns an iterator of values instead of a slice. It's necessary because mmap file cannot contain slice of strings, we have to parse it.
=> Mmap points to values map

lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/index_selector.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/struct_payload_index.rs
Tracking issue: #4502. Continuation of #4690.
This PR introduces the following items:
- `trait FieldIndexBuilderTrait`.
- `enum FieldIndexBuilder` (contains all `FieldIndexBuilderTrait` implementations).
- `index_builder_selector()` which is similar to `index_selector()`.
- An implementation of `FieldIndexBuilderTrait` for each index type.
Right now, the builders are merely single-line methods that implement the same old logic. In subsequent PRs they will be extended to support mmap indices.
=> Introduce FieldIndexBuilder

Cargo.lock, lib/segment/Cargo.toml
Charabia [0.8.9](https://github.com/meilisearch/charabia/releases/tag/v0.8.9) broke our chinese tokenization by splitting the feature `chinese` into 3 different components.
https://github.com/meilisearch/charabia/pull/282
This PR reinstates the previous behavior.
Locally tested with:
```
qdrant on  fix-charabia-chinese-toknenization [!] is 📦 v1.10.2-dev via 🦀 v1.79.0 took 1m43s
❯ cargo t -p segment --lib test_multilingual_tokenizer_chinese --all-features
Locking 1 package to latest compatible version
Adding pinyin v0.10.0
Compiling pinyin v0.10.0
Compiling segment v0.6.0 (/home/agourlay/Workspace/qdrant/lib/segment)
Compiling charabia v0.8.12
Finished `test` profile [unoptimized + debuginfo] target(s) in 1m 39s
Running unittests src/lib.rs (target/debug/deps/segment-ea2d056be7f88852) …
```
=> Fix Charabia Chinese tokenization

tests/consensus_tests/test_resharding.py
We already doubled the timeout in <https://github.com/qdrant/qdrant/pull/4687>, but apparently that isn't good enough for GitHub CI machines. 👴
Here I double it once again.
Failing case:
- https://github.com/qdrant/qdrant/actions/runs/10043751950/job/27757211802?pr=4723#step:11:131
=> Double timeout in resharding with concurrent updates test one more time

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/schema.rs, lib/api/src/rest/validate.rs, lib/collection/src/collection/query.rs, lib/collection/src/grouping/aggregator.rs, lib/collection/src/operations/universal_query/collection_query.rs, lib/collection/src/operations/universal_query/planned_query.rs, lib/collection/src/operations/universal_query/shard_query.rs, lib/collection/src/shards/local_shard/query.rs, tests/openapi/openapi_integration/test_query.py, tests/openapi/openapi_integration/test_query_full.py
Finishes implementation from collection to rest and grpc API, effectively exposing it.
Sample REST request:
```
POST collections/{collection_name}/points/query
{
"query": { "sample": "random" }
}
```
It will produce a random, unstable output. If used without prefetches, offset will be ignored.
=> universal-query: Expose random sampling query

lib/segment/src/spaces/metric_uint/neon/cosine.rs, lib/segment/src/spaces/metric_uint/neon/dot.rs, lib/segment/src/spaces/metric_uint/neon/euclid.rs, lib/segment/src/spaces/metric_uint/neon/manhattan.rs, lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs, src/common/debugger.rs
The newly merged #4715 is triggering these lints on non-linux targets. This PR fixes them
=> Fix new pedantic lints on mac

lib/segment/tests/integration/segment_builder_test.rs
Fixes flaky test #4708 
When not defragmented, points in a newly built segment get placed in random order, which means it is possible they are already ordered - especially for segments with only a few points. However we assert that a non-defragmented segment always is unsorted.
This PR removes this part.
I think we can safely remove this part because:
- It was initially just to test that the defragmentation checking-logic was working properly.
- The important part, checking defragmented segments are sorted is untouched.
- I don't think another fix, addressing the actual issue, is worth the work that would be needed to fix it.
If you think it is still important to test the checking logic too, I'll create a fix that preserves the test.
=> remove testing non-defragmented segments for non-defragmentation

lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/tests/mod.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/tests.rs
Fixup for #4717.
This PR drops `FieldIndex::recreate()` as requested in https://github.com/qdrant/qdrant/pull/4717#discussion_r1686167578.
=> Drop FieldIndex::recreate() method

docs/redoc/master/openapi.json, openapi/openapi-service.ytt.yaml, src/common/metrics.rs, tests/openapi/openapi_integration/test_service.py
This PR addresses #4696 by:
- Changing app_info, app_status_recovery_mode, and cluster_enabled metrics from COUNTER to GAUGE
- Convert boolean to its f64 representation `true => 1.0` or `false => 0.0`
=> Refactor: Convert app and cluster info metrics from counters to gauges #4696

lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mod.rs
Value indexer does not need `self` for value conversion. Removing `self` is important for mmap field index builder, where value conversion may be applied without created field index
=> ValueIndexer get value without self

lib/segment/src/index/field_index/histogram.rs, lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/field_index/tests/histogram_i64_tests.rs
This PR removes `NumericIndexKey` structure and replace it by `Point` from histogram. The main goal of this PR is to unify type of id+value pair and don't define such pair multiple times with conversions to each other. All indices (Mutable+Immutable+MMap) will use only one type of id+value pair
=> Remove NumericIndexKey and use histogram point

lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
This PR removes `Vec<u8>` as numeric type in `MutableNumericIndex`. It's a part of mmap index because mmap builder will use the mutable index as data collector. Use `Point<T>` as unified type for id+value in numeric index
=> Remove vec u8 from mutable numeric index

lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
This PR splits `MutableNumericIndex` into `MutableNumericIndex` and `DynamicNumericIndex`. `DynamicNumericIndex` is an index with insertions and deletions but without persistence. It's required for future mmap builder where we need `DynamicNumericIndex` to construct all collections but without writing into RocksDB.
=> Dynamic numeric index without persistence

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/common/rocksdb_wrapper.rs
context: #804 
This PR changes the compression scheme used by RocksDB from Snappy to LZ4.
The change is visible in the `LOG` file for each segment:
```
2024/07/24-12:28:44.220547 63740 Compression algorithms supported:
2024/07/24-12:28:44.220552 63740 	kZSTD supported: 0
2024/07/24-12:28:44.220556 63740 	kXpressCompression supported: 0
2024/07/24-12:28:44.220558 63740 	kBZip2Compression supported: 0
2024/07/24-12:28:44.220561 63740 	kZSTDNotFinalCompression supported: 0
2024/07/24-12:28:44.220564 63740 	kLZ4Compression supported: 1
2024/07/24-12:28:44.220566 63740 	kZlibCompression supported: 0
2024/07/24-12:28:44.220568 63740 	kLZ4HCCompression supported: 1
2024/07/24-12:28:44.220570 63740 	kSnappyCompression supported: 1
...
2024/07/24-12:28:44.221588 63740 …
```
=> set RocksDB compression to lz4

lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/struct_payload_index.rs
In a [previous PR](https://github.com/qdrant/qdrant/commit/1611deaf034a8ec219b4aab80abe31200bb8fc15), we changed the output of `PayloadFieldIndex::filter` and `PayloadFieldIndex::estimate_cardinality` to an `OperationResult`. Apparently the reason was that it was better to propagate the error from geo `*_hashes` functions up to their respective usages. But in practice the two methods from the trait were designed to be used with an `Option`, as mismatched condition/index would just return `None` and become ignored.
This PR removes this level of propagation that was ignored anyway.
Main change:
```diff
- fn filter<'a>(&'a self, condition: &'a FieldCondition) -> OperationResult<Box<dyn Iterator<Item = PointOffsetType> + 'a>>;
+ fn filter<'a>(&'a self, condition: &'a FieldCondition) -> …
```
=> Use option in `filter` and `estimate_cardinality`

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/segment/src/data_types/index.rs, lib/segment/src/types.rs, lib/segment/tests/integration/payload_index_test.rs
This PR enables `on_disk` boolean parameter for the payload types affected by map and numeric indices. Namely, for Keyword, Integer, Float, Datetime.
Additionally, this PR adds `PayloadFieldSchema::is_on_disk()` method to get this value regardless of field schema type.
=> Add {Integer,Float,Datetime}IndexParams::on_disk to the API

lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
This PR a preparation step before opening https://github.com/qdrant/qdrant/pull/4721
It includes:
1. Remove direct usage of DB. Mmap numeric index does not have rocksdb
2. Remove usage of `NumericIndex` inside `MutableNumericIndex` and `ImmutableNumericIndex`. `NumericIndex` generic will have more generic restrictions then `MutableNumericIndex` and `ImmutableNumericIndex`.
3. Small refactor like remove `pub` from immutable index fields
=> numeric index remove direct db usage

lib/collection/src/collection/collection_ops.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/resharding.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/collection/sharding_keys.rs, lib/collection/src/shards/resharding/driver.rs, lib/collection/src/shards/resharding/mod.rs, lib/collection/src/shards/resharding/stage_commit_read_hashring.rs, lib/collection/src/shards/resharding/stage_commit_write_hashring.rs, lib/collection/src/shards/resharding/stage_finalize.rs, lib/collection/src/shards/resharding/stage_propagate_deletes.rs, lib/collection/src/shards/shard_holder/resharding.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, tests/consensus_tests/test_resharding.py
This PR adds two main features:
- forbid to abort resharding, if it reached `ReshardStage::WriteHashRingCommitted` stage
- automatically cancel/abort resharding, when certain consensus operations applied, that affect collection or shards that is involved in resharding:
- if collection is deleted, resharding is automatically aborted
- if shard key is deleted, resharding is automatically aborted
- if peer is force-removed from cluster, resharding is automatically aborted
- a few other relevant operations does not require special handling:
- it's impossible to delete last repilca of a shard, so no special handling required before new shard is replicated
- and it seems like if either replica of new shard is removed *during* replication, it should restart the whole …
=> Abort resharding when relevant consensus events happen

lib/collection/src/shards/shard_holder/resharding.rs
When resharding is aborted, we need to update the shard key mapping. This was not done.
=> When resharding is aborted, update the shard key mapping

lib/segment/src/id_tracker/immutable_id_tracker.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs
Enables the `ImmutableIdTracker` and `InMemroyIdTracker`.
Marked as draft until next release.
=> Enable new idtracker

docs/grpc/docs.md, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs
This was inconsistent with other enums, which causes to be inconsistent in python client too
=> Switch to camelcase in `Sample` proto enum

lib/collection/tests/integration/main.rs, lib/segment/tests/integration/main.rs, lib/storage/tests/integration/main.rs
This PR makes `main.rs` of integration tests more uniform.
=> Tidy up integration tests

src/tonic/api/points_common.rs
We added parameters to some field index types which didn't had parameters before. However we forgot them in conversion and verification.
=> Fix parameterized field params

lib/collection/src/collection_manager/segments_updater.rs
Prevents blocking all segments in a collection when executing a payload operation.
Setup: Searching with bfb while Qdrant sets payload values by filter targeting 2/3 of 2 million points.
```
bfb --skip-create --skip-upload --collection-name test --search -n 500 --dim 3 --skip-wait-index --parallel 1
```
--- Server timings ---
Min server time: 0.000038131
Avg server time: 0.0075637902780000005
Median server time: 0.005659279
p95 server time: 0.015388914
p99 server time: 0.016668033
Max server time: 0.046231222
Error in the response: The operation was cancelled
=> Non blocking payload operations

lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/segment.rs
Needs #4753 
In #4753 we added `iter_filtered_points` to the payload index struct, which allows us to return the filtered iterator.
This PR switches the use of `query_points` to the new `iter_filterd_points` when possible, to avoid an early filtered points allocation.
=> More filtering of points without preallocating

lib/storage/src/content_manager/consensus/persistent.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc/mod.rs, src/actix/api/cluster_api.rs, tests/consensus_tests/test_cluster_metadata.py
This PR adds `UpdateClusterMetadata` operation that allows to store arbitrary JSON values (under string keys) into Qdrant. These values are propagated to cluster nodes through consensus and stored as part of persistent consensus state.
**TODO:**
=> Add `UpdateClusterMetadata` consensus operation

lib/collection/src/shards/resolve.rs
Fixes same issue as #4511:
The order of results is not always the same, as the implementation had been considering. Nearest search can have different order direction depending on the metric (Euclidean vs Dot), and order-by can select its direction too.
~To preserve this ordering, I am introducing an extra `precedence` field in `ResolverRecord` to aggregate the sum of the positions of the same item in different results.~
~By having this number, in the end we can just sort in ascending order, and the resolved list should be ordered correctly.~
~I have not written any new tests yet, but the [`resolve_scored_points_batch_4_majority`](https://github.com/qdrant/qdrant/blob/dev/lib/collection/src/shards/resolve.rs#L397) test failed once we [stopped sorting …
=> Replica resolver sorts by overall index

Cargo.lock, Cargo.toml
Easy upgrade https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#0110-2024-02-08
I will check 0.12.x later once this upgrade settles.
=> Bump tonic 0.11.0

lib/collection/src/operations/cluster_ops.rs, src/common/collections.rs
This is required to be able to move resharding driver to a separate service.
=> Add `Commit*HashRing` resharding operations to update collection cluster API

Cargo.lock, Cargo.toml
Update apparently ignored by Dependabot.
https://github.com/tikv/pprof-rs/blob/master/CHANGELOG.md#0130---2023-09-27
I validated that we can still generate profiles.
=> Bump pprof 0.13.0

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/tests/integration/disbalanced_vectors_test.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs, lib/segment/tests/integration/payload_index_test.rs, lib/segment/tests/integration/segment_builder_test.rs
This PR adds mmap index payload tests to `payload_index_test.rs`.
Besides of a bit of refactoring, it updates the following tests so that they test both regular indices and mmap indices:
- `test_integer_index_types`
- `test_struct_payload_index`
Depends on #4809.
=> Integration tests for on-disk payload indices

lib/collection/src/collection/resharding.rs, lib/collection/src/shards/transfer/mod.rs, tests/consensus_tests/test_resharding.py
This should allow us to test bit and pieces we implemented recently (and will implement shortly) to move resharding driver to external service.
=> Disable resharding driver and intergration tests

src/common/metrics.rs
Adds `scroll` endpoint to `GRPC_ENDPOINT_WHITELIST` and `REST_ENDPOINT_WHITELIST`.
This is my first PR on `qdrant`, let me know if I am missing any steps. 
To check whether additional configuration or edits were required for adding metrics endpoints I had a look at some previous PRs that expanded the whitelists ( such as: https://github.com/qdrant/qdrant/pull/4497 ) but found no specific implementation, so I'm presuming expansion is as straightforward as this PR. Will post further thoughts in related issue.
Relates to: https://github.com/qdrant/qdrant/issues/4805 
3. [x] Have you checked your code using `cargo clippy --all --all-features` …
=> Add `scroll` endpoints to metrics whitelist

src/common/metrics.rs
Initially I wanted to just add the missing entry for the new Query Groups API.
However I realized that there were more API missing so I decided to add a few more for completeness.
=> Add more missing APIs to the metrics allow list

tests/openapi/test_payload_indexing.py
This PR adds `test_payload_schemas()` that checks that various payload schemas can be applied without errors. Primarily I want to check schemas with `"on_disk": True`.
AFAIK, we don't have the infrastructure to wait until the segment is optimized in tests, so this test doesn't check indexing; just index creation, querying, and deletion.
Also, this PR removes `on_disk_vectors` parametrization from `test_payload_indexing.py` to reduce test time as I think this parameter is not relevant for tests in this file, and these tests are taking too long already. cc: @timvisee
=> Test payload schemas

lib/api/src/grpc/conversions.rs, lib/collection/src/collection/facet.rs, lib/collection/src/collection/mod.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/toc/point_ops.rs, lib/storage/src/content_manager/toc/point_ops_internal.rs, lib/storage/src/rbac/ops_checks.rs, src/tonic/api/collections_api.rs, src/tonic/api/collections_common.rs, src/tonic/api/collections_internal_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs, src/tonic/api/snapshots_api.rs, src/tonic/auth.rs
Continue implementation up to the table of content, specifically:
- merge results from different shards in Collection
- implement CheckableCollectionOperation for FacetRequest
- add facet in Table of Content
- finalize connecting the internal service back into the Table of Content
- make error_to_status a From implementation, refactor accordingly
=> Facet in Table of Content

lib/collection/src/collection/query.rs, lib/collection/src/collection/search.rs, lib/collection/src/discovery.rs, lib/collection/src/grouping/builder.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/recommendations.rs
We have started to apply a more granular handling of timeouts by decreasing it for sequential operations.
However we need to be careful about overflow.
=> Prevent overflow when updating timeouts

lib/collection/benches/batch_query_bench.rs, lib/collection/benches/batch_search_bench.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/collection_manager/collection_updater.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/local_shard/query.rs, lib/collection/src/shards/local_shard/scroll.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/read_ops.rs, lib/collection/src/shards/replica_set/snapshots.rs, lib/collection/src/shards/shard_holder/mod.rs, lib/collection/src/shards/shard_trait.rs, lib/collection/src/tests/fix_payload_indices.rs, lib/collection/src/tests/shard_query.rs, lib/collection/src/tests/wal_recovery_test.rs
Performing a retrieve operation at the segment level is a blocking operation:
- the segment's read lock needs to be acquired
- the vectors are fetched from storage
- the payload are fetched from storage
This PR makes retrieving asynchronous & multithreaded so it does not block anymore Tokio threads which can cause various responsiveness issues.
It also applies additional measures to:
- honor user timeout where possible
- ensure cancellation of tasks
=> Non blocking retrieve with timeout and cancellation support

docs/redoc/master/openapi.json, openapi/openapi-main.ytt.yaml, openapi/openapi-points.ytt.yaml
The PR https://github.com/qdrant/qdrant/pull/4842 fixed the timeout implementation for the retrieve APIs:
- GetPoints
- CountPoints
- ScrollPoints
The timeout were already accepted but not fully used.
Now that the implementation has been fixed, we can advertise those to the clients.
=> Add missing timeout query params in openapi specs

lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/local_shard/shard_ops.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/read_ops.rs, lib/collection/src/shards/shard_trait.rs
Similar to https://github.com/qdrant/qdrant/pull/4844 for exact counts.
Exact counts can be very expensive, this PR make those non-blocking with the regular benefits on the Tokio runtime.
=> Non blocking exact count with timeout and cancellation support

lib/segment/src/json_path/mod.rs
This PR limits JsonPath::filename() to from 64 to 33 characters (24 for hash + 1 for underscore + 8 for human-readable field name).
Motivation: make it less like likely to hit 260 characters path length limit for Windows. This limitation should not affect modern Rust code, but it might affect legacy apps peeking into Qdrant storage directory (e.g. archivers).
=> Limit JsonPath::filename() to 33 characters

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.11.1-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4660>.
=> Bump dev version to 1.11.1-dev

lib/segment/src/vector_storage/dense/dynamic_mmap_flags.rs
`DynamicMmapFlags` is used to rotate the storage between `flags_a.dat` and `flags_b.dat` to extend its length. I find this is not necessary: we can extend the file without closing the existing mmap.
This PR drops this logic and makes Qdrant to always use `flags_a.dat`. The migration path is implemented.
---
New `set_len` sequence:
1. Open a file.
2. `file.set_len` (extend only, not shrink)
3. `mmap` it, `madvise`, create bit slice.
4. Put the new mmap into `self`, dropping the old `mmap`. 
In the worst-case scenario, we'll crash/bail out during step 3, resulting in a file twice as big. But it's not a big issue because:
1. It wouldn't affect data consistency.
2. The file will be truncated back during restart.
3. The rest of the file will be sparse, not affecting an on-disk size.
5. This PR …
=> Drop DynamicMmapFlags file rotation logic

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml
Follow up on https://github.com/qdrant/wal/pull/76 to keep the WAL up to date.
I updated `fs4` manually here as well so that we depend on and build a single version.
=> Bump latest WAL and fs4

lib/collection/src/shards/shard_holder/resharding.rs
Before, we were deleting migrated points (from "old" shards) during `WriteHashRingCommitted` stage. Current plan is to delete them during `ReadHashRingCommitted` stage, and so now we can't abort resharding once we switched to this stage.
=> Forbid aborting resharding after `ReadHashRingCommitted`

lib/segment/src/vector_storage/query/reco_query.rs
Last fix (#4815) didn't account for when the input would result in `before = Ordering::Greater, after = Ordering::Equal`. 
To fix this, we now do `total_cmp` on the "after", and skip the cases where the relaxed cmp on the "before" is Equal
=> tests: fix flaky `correct_positive_order`

src/actix/api/collections_api.rs, src/actix/api/count_api.rs, src/actix/api/discovery_api.rs, src/actix/api/recommend_api.rs, src/actix/api/retrieve_api.rs, src/actix/api/search_api.rs, src/actix/api/snapshot_api.rs, src/actix/api/update_api.rs
Wraps all cancel-safe operations in actix handlers in helpers::time.
This allows early-returning using `?` and makes the code cleaner.
=> Wrap handler body in helpers::time

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/shards/local_shard/facet.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/segment.rs, lib/segment/tests/integration/payload_index_test.rs
Currently the filtered iterator works great if the cardinality of the filter is small enough, but its performance slows linearly as the cardinality increases.
Here I introduce a second approach of going through the values->points map and filtering the points. This is essentially a full-scan always, independently of the filter cardinality, but it is faster than the existing approach after some threshold.
TODO:
- define a dynamic threshold based on the amount of unique values, cardinality and amount of available points?
Rudimentary experiments:
https://docs.google.com/spreadsheets/d/1CtdaBIGRVH1bzu_JuKmyNBnLX9GUh1LACbpswjdNiDs/edit?usp=sharing
=> perf: Limit bad performance of filtered faceting

src/tonic/api/points_common.rs, tests/basic_grpc_test.sh
We had a bug where selecting `field_type: Bool` and `field_index_params: { bool_index_params: {} }` would result in a mismatch error, and same for Geo type. 
With these changes we fix it and also we make sure to not forget it in the future via a compiler error.
=> fix mismatch of index parametrization and type

tests/storage-compat/gen_storage_compat_data.sh
Some files in the storage are created with 600 permissions
To mitigate this, script will try do chown.
Use less restrictive file permissions
=> Fix gen_storage_compat_data permissions

lib/collection/src/hash_ring.rs, lib/collection/src/shards/shard_holder/resharding.rs, src/actix/api/local_shard_api.rs, src/actix/api/mod.rs, src/actix/mod.rs
`delete` API is required to move resharding driver to external service. `get`/`scroll`/`count` are not strictly required, but seems useful for future debugging and troubleshouting.
__TODO:__
- disable automatic resharding filter for local shard points APIs
- currently, after read hash ring was committed, resharding filter is automatically applied to all read requests
- e.g., `get`/`scroll`/`count` start return empty/zero results...
- and `delete` stops working, because it relies on `scroll` requests internally
- it is still possible to test the API (just don't commit read hash ring), so this fix will be done in a follow-up PR
- integration tests
- I'd prefer to add tests in a follow-up PR as well, once everything is fixed and fully ready
2. [x] Have …
=> Add local shard points get/scroll/count/delete HTTP API

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/payload_index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment/entry.rs, tests/consensus_tests/fixtures.py, tests/consensus_tests/test_issues_api.py
Fixes #4934 
Currently, when we build a payload index, we hold a write lock the entire time the index is being built. This might be acceptable for small collections, but on bigger ones this means that searches will be completely interrupted (and even make them timeout) during building.
With these changes I've separated the building and applying sections, so that we only need a read lock when building, and upgrades to a write lock when applying it to the segment.
I've tested this manually with bfb + dashboard, and now searches keep responding normally during index building, with only a really small hiccup at the end.
=> fix: Non-blocking payload index building

lib/collection/src/collection/payload_index_schema.rs, lib/collection/src/operations/verification/mod.rs, lib/collection/src/tests/payload.rs, lib/segment/src/problems/unindexed_field.rs
I think the current extractor is too coupled with the issues API when it shouldn't be. 
This fixes it and renames some methods.
=> [StrictMode, review refactor]: decouple extractor from issues

lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/tests/async_raw_scorer.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs, lib/segment/src/vector_storage/tests/test_appendable_dense_vector_storage.rs, lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs, lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
Fixes <https://github.com/qdrant/qdrant/issues/4949>.
Fix `memmap_dense_vector_storage` incorrectly taking over vector deletions on segment optimization. This resulted in deleted vectors suddenly appearing again once segments get optimized.
This problem has existed for a long time but only came to light recently. Our input data on `update_from` may now contain points for multiple segments, in which case the previous logic breaks.
All other storage types implemented it correctly. This implementation has now been updated to match the others, fixing the problem.
=> Fix point deletions on mmap segment optimization

lib/segment/src/problems/unindexed_field.rs, lib/segment/src/types.rs
Fixes two things:
- When checking MatchValue conditions, the extractor will now report a UUID index as an alternative, not only keyword index.
- Parametrized indices are much more common now with `on_disk` and related stuff. So now we need to make better checks if a field is already indexed. For this I am am changing it to compare only unparametrized versions of schemas.
This fixes false-positives, but it is still possible to make a false-negative. I added a TODO comment for strict-mode to resolve this 😄
=> Issues: Accept UUID index

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.11.2-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4880>.
=> Bump dev version to 1.11.2-dev

docs/redoc/master/openapi.json, lib/collection/src/collection/mod.rs, lib/collection/src/telemetry.rs
Expose resharding operations of a collection in telemetry.
This is needed so cluster manager can assess this state.
=> Expose resharding operations for collection in telemetry

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/conversions.rs, lib/api/src/rest/schema.rs, lib/segment/src/data_types/facets.rs, lib/segment/src/index/field_index/facet_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/map_index/mmap_map_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/mmap_point_to_values.rs, lib/segment/src/index/field_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/types.rs, lib/segment/tests/integration/payload_index_test.rs
Enables faceting with the other existing map indexes: integer and uuid
Note: I decided to not add a special case for UUID in REST, and just use Keyword variant as output. This should be transparent when serializing, and we do not consume it in any form.
Note2: I edited the trait and implementations of `MmapValue` to allow references of `i64` and `u128`
=> Integer and UUID facets

lib/segment/src/segment/entry.rs
Fixes <https://github.com/qdrant/qdrant/issues/4970>
Fix a panic during payload index building.
We took a [`payload_index.borrow_mut()`](https://github.com/qdrant/qdrant/blob/8a46eb12478b6f535ac08a45228a2c17fd8d1730/lib/segment/src/segment/entry.rs#L657) while not having exclusive access to the parameter (`&self`). Other actors accessing the payload index at the same time trigger a panic.
We recently implemented non-blocking payload indexing in <https://github.com/qdrant/qdrant/pull/4941> which is where this problem was introduced. It didn't happen before because the function taking the mutable borrow enforced exclusive access on its own (with `&mut self`).
It turns out the `borrow_mut()` is obsolete now because we don't need mutability on the value anymore.
Changing the `borrow_mut()` to …
=> Fix panic during payload index building

docs/redoc/master/openapi.json, lib/segment/src/index/field_index/field_index_base.rs, openapi/openapi-main.ytt.yaml
Adds the missing read consistency query parameter to the openapi spec for the facets endpoint
=> Facets: add consistency param to openapi

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.11.3-dev` with the release of <https://github.com/qdrant/qdrant/pull/4974>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4965>.
=> Bump dev version to 1.11.3-dev

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs, tools/missed_cherry_picks.sh
PR to release Qdrant 1.11.2.
Most importantly, this fixes a potential panic during payload index building (<https://github.com/qdrant/qdrant/pull/4973>).
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4962>.
---
- https://github.com/qdrant/qdrant/pull/4973 - Fix potential panic during payload index building
=> Bump version to v1.11.2

lib/segment/src/data_types/facets.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/index/query_optimization/condition_converter/match_converter.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/types.rs
Refactors `condition_converter.rs` to make exhaustive matches on all combinations of index + condition, so we don't forget these in the future.
Also adds correct handling for:
- MatchValue of string with uuid map index
- MatchAny of string with uuid map index
- MatchExcept of string with uuid map index
- ~ValuesCount with any index~ Edit: This wasn't used intentionally
=> Refactor condition converter, use uuid index there too

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.11.4-dev` with the release of <https://github.com/qdrant/qdrant/pull/4984>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4975>.
=> Bump dev version to 1.11.4-dev

lib/segment/src/segment/facet.rs
Inside approximate faceting, there was a case where we would output hits with count=0, which isn't desirable and is incongruent with other cases.
This fixes those cases.
=> [Facet] Do not include values with count 0

lib/collection/src/collection/collection_ops.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/transfer/driver.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
This PR fixes a possible bug, when peer is removed right before shard transfer **to** removed peer is finished, which may create an "orphan" shard: a shard, that exists in shard replica state, but the **peer** this shard should belong to is already removed from cluster.
The fix is rather simple: when applying `ShardTransfer::Finish` conensus message, only mark replica as `Active`, if *peer* still exists in the cluster.
This PR also restructures/simplifies `Collection::finish_shard_transfer`, cause it was too hard to work with before.
=> Check that peer still exist, when applying finish transfer operation

lib/collection/src/collection/mod.rs
Similar to #4968, this PR fixes a potential bug, when peer is removed right before state of a replica on removed peer is changes, which may create an "orphan" shard.
Fix is conceptually the same as in #4968: check that peer still exists in the cluster before applying `SetShardReplicaSet` operation.
=> Check that peer still exist, when applying set shard replica set operation

tests/poetry.lock
Dependabot [complains] about outdated `certifi`, but it won't create a PR because "Pull request already exists for certifi@2024.7.4". So, let's bump it manually.
[complains]: https://github.com/qdrant/qdrant/security/dependabot/90
=> Bump certifi

lib/collection/src/shards/local_shard/mod.rs
This PR removes code to save shard config in `LocalShard::create_snapshot`.
Reason: this file is getting overwritten in the only code path in which this method is called. So, no need to write it in the first place. Here is the call graph:
```mermaid
graph TD
Collection::create_snapshot --> ShardReplicaSet::create_snapshot
ForwardProxyShard::create_snapshot --> LocalShard::create_snapshot
ProxyShard::create_snapshot --> LocalShard::create_snapshot
QueueProxyShard::create_snapshot --> LocalShard::create_snapshot
ShardReplicaSet::create_snapshot --> Shard::create_snapshot
Shard::create_snapshot --> LocalShard::create_snapshot
Shard::create_snapshot --> ProxyShard::create_snapshot
Shard::create_snapshot --> ForwardProxyShard::create_snapshot
Shard::create_snapshot --> …
```
=> Don't save shard config in `LocalShard::create_snapshot`

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
Rust 1.81 is landing [soon](https://releases.rs/docs/1.81.0/).
This time the clippy lints change is minimal.
=> Fix Clippy 1.81

Cargo.lock, tests/poetry.lock
Applies <https://github.com/qdrant/qdrant/pull/5015> and <https://github.com/qdrant/qdrant/pull/5014> on `dev`.
Dependabot opened the above two PRs as a security fix. They don't affect our release build so it's tolerable to apply these to the development branch to eventually release.
=> Bump cryptography and quinn-proto dependencies

lib/collection/src/collection/collection_ops.rs, lib/collection/src/operations/verification/mod.rs, lib/storage/src/content_manager/collection_verification.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/dispatcher.rs, src/actix/api/search_api.rs
Adds a trait for request verification and implements it for the search REST API.
To ensure we don't forget to implement checks for future endpoints, a new `toc_new` function gets introduced that requires a new, empty type created when verification was successful. 
We also need to check for access rights in strict mode, since it gets executed before the operation, which usually does the check. An alternative would be to combine `Access` and `Verification`, let `CollectionRequestVerification` do the access check and use only `Verification` as parameter for `toc(..)`.
=> [Strict-mode] Verification check in API

lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/update_handler.rs
Calling telemetry API now checks for pending optimizations while fetching shard status. So it looks like Qdrant is now repeatedly logging `Merge candidates: [...]` which gives a false appearance that Qdrant merge optimizer is stuck
=> Improve logging

docs/redoc/master/openapi.json, src/common/metrics.rs, src/common/telemetry.rs, src/common/telemetry_ops/cluster_telemetry.rs
Expose cluster metadata in telemetry with details level 1 and up:
```json
{
"id": "709a6909-3f61-45b4-a6fb-f541909bca95",
// -- snip --
"metadata": {
"_cluster_manager/resharding/collections/benchmark": {
"direction": "up",
"shard_id": 1,
"peer_id": 377010536499172,
"stage": "migrate_points",
"relevant_shards": [0],
"shards_migrating": [0],
"shards_migrated": [],
"replicas_migrating": [],
"replicas_migrated": [],
"replicas_deleting": [],
"replicas_deleted": []
}
}
}
```
=> Expose cluster metadata in telemetry

lib/collection/src/collection/distance_matrix.rs
This issue surfaced while working on the congruence tests in https://github.com/qdrant/qdrant-client/pull/769
It is not possible to build a matrix if less than 2 results are found.
=> Fix distance matrix min samples found

lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
This PR aborts resharding, when *resharding* shard transfer is aborted.
This is the most basic error handling strategy possible, but it's trivial to implement and we will revisit it later if required/desired.
=> Abort resharding when aborting resharding shard transfer

lib/storage/src/content_manager/alias_mapping.rs
It is possible that service if shut down after file is created, but before data is fsynced, which may leave us with empty file
(this reproduces on filesystem-level snapshots)
If we use atomic writes, it should be impossible to end up with corrupted file
=> use atomic write to initially create alias mapping

lib/segment/src/index/field_index/full_text_index/inverted_index.rs
Main change of this PR is to get rid of `None` posting lists, so we change the type of postings in the `ImmutableInvertedIndex`
``` diff
-postings: Vec<Option<CompressedPostingList>>,
+postings: Vec<CompressedPostingList>,
```
To do this we must filter them out, and update the vocabulary to point to the same posting lists which now will have a different position in the `postings` vector.
=> Immutable text index without optional posting lists

lib/api/src/grpc/validate.rs, lib/collection/src/operations/cluster_ops.rs, lib/common/common/src/validation.rs
Tracked in #4213
Allow a shard transfer from and to the same peer if the source and target shard is different.
Previously there was no use case for this. With resharding transfers we do want to support this though. A resharding shard transfer may need to happen on a single peer because replicas may be on a single peer.
=> Support shard transfers within same peer if from/to shard are different

Cargo.lock, lib/common/common/Cargo.toml, lib/common/common/src/mmap_hashmap.rs, lib/segment/src/index/field_index/map_index/mmap_map_index.rs
Current version of Mmap HashMap silently ignores errors if storage is malformed.
This PR proposes to do:
- better error messages, with captured important pieces of context
- debug asserts to potentially spot errors early in tests
- log errors to be able to detect problems in production
=> debug asserts for malformed hashmmap

lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/update_handler.rs
We should mark shard status as:
- Yellow if optimizers are suboptimal and we have run at least one since starting the node
- Grey if optimizers are suboptimal and we haven't run any since starting the node
This makes the status consistent
[Slack discussion](https://qdrant.slack.com/archives/C077CCW8NU8/p1725609571955249?thread_ts=1725568515.703859&cid=C077CCW8NU8)
=> Fix shard/collection status blinking

Cargo.lock, Cargo.toml, lib/collection/src/collection/snapshots.rs, lib/collection/src/shards/shard_holder/mod.rs, lib/segment/src/common/validate_snapshot_archive.rs, lib/segment/src/segment/entry.rs, lib/storage/src/content_manager/snapshots/mod.rs
This PR enables sparse tar implementation from our `tar-rs` fork.
It provides two main benefits:
- Snapshots archives become smaller, especially for newly created collections.
- Collection restored from snapshots would also take less on-disk size.
When you create an empty file and set it size, but do not explicitly write bytes into it, the file will be filled with zeroes. The modern filesystems do not store these zeroes. Instead, they efficiently store ranges of zeroed blocks as "holes".
Qdrant uses sparse files extensively. In particular, empty collections have a high sparse-to-dense ratio. For example, WAL[^1] files by default are 32MiB filled with zeroes. Or any storage file created by [`create_and_ensure_length()`] is sparse.
If we naively copy these files bytewise, we'll lose their …
=> Switch to sparse tar implementation

lib/segment/src/common/operation_error.rs, lib/segment/src/index/field_index/geo_hash.rs, lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs, lib/segment/src/index/field_index/geo_index/mod.rs, lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
This PR replaces `GeoHash` implementation from `SmolStr` into `u64`. It's possible because each string char can be one of 32 values (5bits), max chars 12 (5*12=60bits) and size 4 bit.
=> Packed geohash

src/consensus.rs
Currently, [when consensus is stopped][consensus-stop] due to `ServiceError` during consensus entry application, we only log ["context" message][service-error-context], without the actual underlying error itself.
When formatting `anyhow::Error` without any modifiers, it will only print top-most error or *context* message. To print the whole error stack (e.g., all context messages and all `std::error::Error::source` errors in `most recent: less recent: oldest` format) we can use "alternative" formatting.
[consensus-stop]: https://github.com/qdrant/qdrant/blob/dev/src/consensus.rs#L106-L109
[service-error-context]: https://github.com/qdrant/qdrant/blob/dev/lib/storage/src/content_manager/consensus_manager.rs#L330-L331
2. [ ] Have you formatted your …
=> Log underlying error, when consensus is stopped due to one

Cargo.toml, lib/collection/src/common/sha_256.rs, lib/collection/src/tests/sha_256_test.rs
Computing file checksums is extremely slow in our debug builds. I was experimenting with snapshots again today and decided to fix this because it was quite annoying.
This enables the release optimizations in all profiles for the sha2 sub crate to always benefit from the faster implementation.
Before: checksum takes 15.6s
After: checksum takes 0.4s
=> Make computing snapshot checksums faster in debug

Cargo.lock, lib/collection/src/collection/snapshots.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/config.rs, lib/collection/src/save_on_disk.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/snapshots.rs, lib/collection/src/shards/shard.rs, lib/collection/src/shards/shard_config.rs, lib/collection/src/shards/shard_holder/mod.rs, lib/common/common/Cargo.toml, lib/common/common/src/lib.rs, lib/common/common/src/tar_ext.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment/entry.rs, lib/segment/src/segment/segment_ops.rs, lib/segment/src/segment/tests.rs, lib/segment/tests/integration/segment_on_disk_snapshot.rs
This PR updates the snapshot creation logic.
Previously, the snapshot were created in two steps: (1) put files into a temporary directory, then (2) put this directory contents into an archive.
In this PR, the snapshot is written directly into an archive without an intermediate step.
Follow-up for #4943.
=> Direct snapshot creation

lib/collection/src/operations/cluster_ops.rs, lib/collection/src/shards/resharding/mod.rs
Someone was trying to trigger (officially unreleased) resharding some time ago, before we even added `direction` field (for scale-up/scale-down) resharding. Now this operation is stuck in their WAL, and if you try to replay this WAL on a never version of Qdrant (e.g., if you add a new node to the cluster) deserialization of consensus operation fails, because `direction` field is mandatory. 🙄
This PR "defaults" `ReshardKey::direction` to `ReshardingDirection::Up` if the field is missing.
=> Use `ReshardingDirection::Up` if `direction` field is missing when deserializing `ReshardKey`

lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs, lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs, lib/segment/src/index/field_index/full_text_index/inverted_index.rs, lib/segment/src/index/field_index/full_text_index/mod.rs, lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs, lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/index_selector.rs
- Refactors `InvertedIndex` from an enum into a trait
- Changes `FullTextIndex` from a struct into an enum which now holds mutable and immutable versions, but soon will also hold Mmap version. This also follows same pattern as current map and numeric indices.
All of this is done just because mmap text index doesn't need a db associated to it. So this refactor is necessary for integrating it.
=> Refactor `FullTextIndex` as enum

lib/segment/src/index/field_index/map_index/immutable_map_index.rs, lib/segment/src/index/field_index/map_index/mutable_map_index.rs
Some tiny improvements in the map indices. I collected these when working on #5072 and #5073.
This does not show a clear measurable difference in loading time while testing locally. But it may be nice to apply anyway.
- Restructure mutable map index loading a bit
- Preallocate container in immutable map index
- Shrink value to points in immutable map index after construction
=> Tiny improvements in map index

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shards/local_shard/mod.rs
Improve performance of dropping duplicate points on start in case there is a lot of them.
This parallelizes the deletions across segments, rather than doing them in sequence.
My test collection has a segment of about 750k points with 5 keyword indices having just 2 distinct values. This segment is duplicated to get 750k duplicates.
This is how long it takes when loading:
- Before PR: 149 seconds
- After PR: 44 seconds
A more extreme case with 5 copies of the above mentioned segment rather than just 2:
- Before PR: 277 seconds
- After PR: 259 seconds
- After PR with [#5072](https://github.com/qdrant/qdrant/pull/5072): 65 seconds
This obviously is an very unlikely scenario, but it's a good way to show the potential benefit.
2. [x] Have you formatted …
=> Parallelize duplicate point deletions across segments

Cargo.lock, Cargo.toml, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/config.rs, lib/common/memory/src/chunked_utils.rs, lib/common/memory/src/madvise.rs, lib/common/memory/src/mmap_ops.rs, lib/common/memory/src/mmap_type.rs, lib/segment/src/id_tracker/immutable_id_tracker.rs, lib/segment/src/index/field_index/full_text_index/inverted_index.rs, lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs, lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs, lib/segment/src/index/field_index/map_index/mmap_map_index.rs, lib/segment/src/index/field_index/mmap_point_to_values.rs, lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs, lib/segment/src/vector_storage/chunked_mmap_vectors.rs, lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs, lib/segment/src/vector_storage/dense/dynamic_mmap_flags.rs, lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs, lib/segment/src/vector_storage/in_ram_persisted_vectors.rs, lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs, lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/loaders.rs
- Instead of in-ram + mmap we can just force mmap in ram with populate
- Should solve double memory usage of experimental vector storage along with cold start and OOM problems
- required benchmarks
=> Allow explicit populate of mmap

lib/segment/benches/range_filtering.rs, lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/payload_context_fixture.rs, lib/segment/src/index/payload_index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs, lib/segment/src/payload_storage/on_disk_payload_storage.rs, lib/segment/src/payload_storage/payload_storage_base.rs, lib/segment/src/payload_storage/payload_storage_enum.rs, lib/segment/src/payload_storage/query_checker.rs, lib/segment/src/payload_storage/simple_payload_storage_impl.rs, lib/segment/src/segment/entry.rs, lib/segment/src/segment/segment_ops.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/tests/integration/nested_filtering_test.rs, lib/segment/tests/integration/payload_index_test.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
In the context of working on a new payload storage, I realized our internal naming could be improved.
This PR renames the internal payload storage consistency for consistency with our documentation and ubiquitous language.
Namely:
- `assign` becomes `set`
- `assign_all` becomes `overwrite`
- `drop` becomes `clear`
- `payload` becomes `get`
The payload index interface gets updated as well with additional verbs where possible for clarity.
=> Rename payload storage operations for consistency

lib/collection/src/collection/collection_ops.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/replica_set/mod.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs
abort shard transfer on delete of replica + check that we don't delete last active
Related to: https://github.com/qdrant/qdrant/issues/5076
=> Align delete replica logic with transfer cancellation

lib/segment/src/vector_storage/chunked_vectors.rs
Current approach takes 7% of CPU time in an internal flamegraph.
=> Optimize reading quantized vectors

Cargo.lock, Cargo.toml
In <https://github.com/qdrant/qdrant/pull/4923> we switched to a temporary new version because a new change wasn't released yet.
It has been now, so this switches back to the upstream release.
=> Bump memmap2 to latest upstream

src/consensus.rs
Continuation of #5066.
As it turned out, we made some "lossy" error conversions in `consensus` module, and so at the point where we were logging consensus error, the error did not contain the cause of the error.
This PR fixes error conversions, so that we preserve error cause.
=> Properly preserve full error chain, when `handle_committed_entries` returns an error

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs, tools/missed_cherry_picks.sh
PR to release Qdrant 1.11.4.
Follows the pattern of https://github.com/qdrant/qdrant/pull/4984.
---
- https://github.com/qdrant/qdrant/pull/4940 - Add grey collection status if optimizations are pending after restart
- https://github.com/qdrant/qdrant/pull/5073 - Parallelize deduplication of points on start, making startups faster
- https://github.com/qdrant/qdrant/pull/5072 - Significantly improve performance of lookup/delete in keyword index, making startups faster
- https://github.com/qdrant/qdrant/pull/5091 - Buffer reads when loading quantized vectors, making startups faster
- https://github.com/qdrant/qdrant/pull/5061, https://github.com/qdrant/qdrant/pull/4943 - Create snapshots without intermediate files, making it faster and requiring less disk space
- …
=> Bump version to 1.11.4

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.11.5-dev` with the release of <https://github.com/qdrant/qdrant/pull/5098>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/4986>.
=> Bump dev version to 1.11.5-dev

lib/segment/src/id_tracker/simple_id_tracker.rs
I noticed that the mapping between `internal_id` and `external_id` is maintained in `id_tracker/PointMappings`, but this code is duplicated with the implementation in `id_tracker/SimpleIdTracker`. Currently, `PointMappings` is used as a field in `SimpleIdTracker` to unify the management of the relationship between `internal_id` and `external_id` using the methods from `PointMappings`.
=> use point mappings in simple id tracker

lib/collection/src/shards/local_shard/mod.rs
Refactor the local shard status function to make it, in my opinion, a bit more readable.
It uses early returns without global lets to eliminate some condition checks/branching.
=> Refactor local shard status function

lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/shard_holder/resharding.rs
Error handling for scale-up resharding is rather trivial: when resharding is aborted, we simply delete "new" shard. However, in case of scale-down resharding, we transfer points into already existing shards, and so when resharding is aborted, we need to remove all points that might have already been transferred into existing shards.
This PR executes filtered delete when aborting scale-down resharding.
=> Cleanup shards when aborting scale-down resharding

lib/collection/src/collection/point_ops.rs, lib/collection/src/shards/shard_holder/resharding.rs, lib/storage/src/content_manager/toc/point_ops_internal.rs, src/actix/api/local_shard_api.rs
This PR refactors and simplifies `local_shard_points::delete_points` HTTP API into `cleanup_shard`, that reuses `ShardReplicaSet::delete_local_points` method added in #5021.
=> Refactor `local_shard_points::delete_points` API into `cleanup_shard` API

lib/segment/src/common/rocksdb_wrapper.rs
We have configured RocksDB to create missing column families opened.
```rust
options.create_missing_column_families(true);
```
There are two ways to open a column family, first `open_cf`:
```rust
/// Opens a database with the given database options and column family names.
///
/// Column families opened using this function will be created with default `Options`.
pub fn open_cf<P, I, N>(opts: &Options, path: P, cfs: I) -> Result<Self, Error>
```
Which only configure the database using the `Options`
Whereas  `open_cf_with_opts`:
```rust
/// Opens a database with the given database options and column family names.
///
/// Column families opened using given `Options`.
pub fn open_cf_with_opts<P, I, N>(opts: &Options, path: P, cfs: I) -> Result<Self, Error>
```
which also applies the `Options` …
=> Configure properly column families when using open_db_with_existing_cf

shell.nix
I've tried to check out qdrant source code and build it on x86 mac laptop, however, i found out a couple of issues with current `shell.nix`.
- Couple of dependencies were missing.
- Default `CXXFLAGS` are not compatible with rocks-db (needs higher deployment target).
- Mold setup did not work with clang out of the box.
This PR fixes all of the issues and allows to build `qdrant` from within nix shell on Intel macOS. I don't have access to ARM Mac at the moment, so I can not say for sure if this configuration will work there.
=> shell.nix: Allow to build on x86 darwin

lib/collection/src/update_handler.rs
This PR fixes a race condition which would allow the optimizers for a collection to get stuck. The result is a collection that remains in yellow state forever, unless a new update operation is send to trigger the remaining optimizations.
The PR has two changes:
1. patch race condition (with an extra branch)
2. remove a level of nesting in the match statement. The bulk of the logic now happens after the match rather than inside it, other branches use `continue`/`break`.
The data race is caused by an ordering problem between three things:
1. condition that checks max allowed handles (max 1 in this case)
2. clean up of handles that are finished
3. signal at the end of optimization to trigger new optimizations
Basically, we trigger the optimizers again before cleaning the finished handle up …
=> Fix race condition getting optimizers stuck, leaving collection in yellow state

lib/collection/src/collection_manager/segments_updater.rs, lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs, lib/segment/src/payload_storage/on_disk_payload_storage.rs, lib/segment/src/payload_storage/simple_payload_storage_impl.rs, lib/segment/src/types.rs
fixes: https://github.com/qdrant/qdrant-client/issues/780
The bug affects set payload operation using `key` on non appendable segments.
It manifest itself by the apparition of unexpected payload values at the root level, which are supposed to be added under `key`.
The bug was introduced in [1.11.1](https://github.com/qdrant/qdrant/releases/tag/v1.11.1) with https://github.com/qdrant/qdrant/pull/4855/files#diff-fe6fcf41822e7bcc71c22cfb9067f6e80e36228f69d2727724e4cc51abc12e07R193
The fix is to merge the payloads using the `key`.
I have tested the fix on a user snapshot file.
=> Fix set payload by key on non appendable segment

.github/workflows/docker-image.yml
Disable the 'Run workflow' button on the top right for the 'Build and deploy docker image' workflow:
This button pushes a new public release, also retagging the `latest` Docker image. We normally never use this as releases are triggered automatically through git tags.
A few days ago I accidentally used this button for a test release. What wasn't entirely obvious to me is that we should use a different workflow instead. This action did cause downtime in our cloud because it depends on the latest tag.
Because this button is more confusing than helpful I vote to remove it so we don't have the same problem again.
Note: this merges into `master` to immediately apply the change in the GitHub interface. I'll manually cherry-pick this back into `dev` on merge.
=> Disable manual trigger on Docker release image workflow

Cargo.lock, Cargo.toml
The `quantization` crate is not used in the root crate therefore the dependency can be removed :broom:
=> Remove quantization from root crate

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs, tools/missed_cherry_picks.sh
PR to release Qdrant 1.11.5.
Follows the pattern of https://github.com/qdrant/qdrant/pull/5098.
---
- https://github.com/qdrant/qdrant/pull/5113 - Fix set payload with nested key not updating nested structure properly in some cases
- https://github.com/qdrant/qdrant/pull/5111 - Fix optimizations potentially getting stuck if low optimization limit is configured
- https://github.com/qdrant/qdrant/pull/5105 - Properly configure RocksDB to use LZ4 compression for payload index
- https://github.com/qdrant/qdrant/pull/5123 - If populating mmap with syscall fails, fall back to naive population
=> Bump version to 1.11.5

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.11.6-dev` with the release of <https://github.com/qdrant/qdrant/pull/5121>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5099>.
=> Bump dev version to 1.11.6-dev

lib/collection/src/collection_manager/collection_updater.rs
This PR adds a non regression test for https://github.com/qdrant/qdrant/pull/5113
The conditions are:
- set_payload op
- targeting nested key
- key must be indexed
- the point must be on a non appendable segment
=> Add unit test for set_payload bug

lib/storage/src/content_manager/collection_verification.rs, lib/storage/src/content_manager/snapshots/mod.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/dispatcher.rs, lib/storage/tests/integration/alias_tests.rs, src/actix/api/cluster_api.rs, src/actix/api/collections_api.rs, src/actix/api/count_api.rs, src/actix/api/discovery_api.rs, src/actix/api/facet_api.rs, src/actix/api/local_shard_api.rs, src/actix/api/query_api.rs, src/actix/api/recommend_api.rs, src/actix/api/retrieve_api.rs, src/actix/api/search_api.rs, src/actix/api/service_api.rs, src/actix/api/snapshot_api.rs, src/actix/api/update_api.rs, src/actix/mod.rs, src/common/collections.rs, src/common/points.rs, src/common/telemetry.rs, src/tonic/api/collections_api.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs, src/tonic/api/snapshots_api.rs, src/tonic/mod.rs, src/tonic/verification.rs
Depends on #5037 
Migrates all `toc(..)` calls with the new toc function.
=> [Strict mode] migrate toc_new -> toc

lib/collection/src/operations/verification/count.rs, lib/collection/src/operations/verification/discovery.rs, lib/collection/src/operations/verification/facet.rs, lib/collection/src/operations/verification/local_shard.rs, lib/collection/src/operations/verification/matrix.rs, lib/collection/src/operations/verification/mod.rs, lib/collection/src/operations/verification/query.rs, lib/collection/src/operations/verification/recommend.rs, lib/collection/src/operations/verification/search.rs, lib/collection/src/operations/verification/update.rs, src/common/points.rs
Depends on #5137 
The `timeout()` function in the `StrictModeVerification` trait is not used anymore since we already check the timeout value in the `check_strict_mode` function. Therefore we can remove it from the trait definition.
=> [Strict mode] Remove obsolete timeout function

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/rest/conversions.rs, lib/api/src/rest/schema.rs, lib/segment/src/data_types/facets.rs, lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/field_index/facet_index.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/map_index/immutable_map_index.rs, lib/segment/src/index/field_index/map_index/mmap_map_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/map_index/mutable_map_index.rs, tests/openapi/test_facets.py
Adds support for boolean payloads with `bool` index in Facet API. It is a small change to fill a missing hole. 
Now it makes sense to say that any index which supports `MatchValue` conditions can be used for faceting.
cc @joein
=> Facets: Support for `bool` payload 

src/consensus.rs
Currently, when starting first peer of a new cluster, we have to wait for a short while (a second or two) until the first peer self-elects itself as a leader. Before the leader is elected, we can't bootstrap other nodes of the cluster or create a collection.
This PR checks if we are the only peer in the cluster and if so, ticks the node few times, so that it self-elects itself as a leader instantly.
=> Instantly self-elect Raft leader, when cluster contains single peer

lib/collection/src/collection/snapshots.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard/mod.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/snapshots.rs, lib/collection/src/shards/shard.rs, lib/collection/src/shards/shard_holder/mod.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment/entry.rs, lib/segment/src/segment/segment_ops.rs, lib/segment/src/segment/tests.rs, lib/segment/src/types.rs, lib/segment/tests/integration/segment_on_disk_snapshot.rs
This PR introduces `enum SnapshotFormat`. The usage in this PR is minimal:
- Passed across `create_snapshot()` invocations.
- The name appears in log output during unpacking.
In subsequent PRs it will be used to control the format of resulting snapshots.
=> Introduce SnapshotFormat

lib/storage/src/content_manager/toc/collection_meta_ops.rs, lib/storage/src/content_manager/toc/dispatcher.rs, lib/storage/src/content_manager/toc/mod.rs, lib/storage/src/content_manager/toc/transfer.rs, src/actix/api/cluster_api.rs, src/main.rs
Add a wait parameter to the cluster metadata API. This is desirable for resharding, because without it, data races are very likely on this interface.
If wait=true is set, the metadata API will wait for consensus to confirm the message before responding.
Along with this the PR has quite some refactoring going on as well to make it work with the consensus reference needed for this change.
=> Add wait parameter to cluster metadata API

Cargo.lock, Cargo.toml, docs/redoc/default_version.js, docs/redoc/index.html, docs/redoc/v1.12.x/openapi.json, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
```
* https://github.com/qdrant/qdrant/milestone/4?closed=1 - Facets API - adds ability to retrieve unique payload values with counts for a given index field under the given filter. [Documentation](https://qdrant.tech/documentation/concepts/explore/#distance-matrix)
* https://github.com/qdrant/qdrant/milestone/11?closed=1 - Distance Matrix API - adds ability to calculate many-to-many distances between stored vectors. This feature is useful for clustering, dimensionality reduction, visualization, and other data exploration tasks. [Documentation](https://qdrant.tech/documentation/concepts/payload/#facet-counts)
* https://github.com/qdrant/qdrant/pull/5188 - Use mmap vector storage by default. This change have several important implications: 
* We avoid using expensive `rocksdb` to make …
```
=> bump version to v1.12.0

lib/collection/src/shards/replica_set/mod.rs, src/common/health.rs
Shards that are under resharding can block scaling the cluster forever because the pod will consider itself as not ready. So our infra will not trigger any operations to scale the cluster.
```
$ curl -i localhost:6333/readyz
HTTP/1.1 503 Service Unavailable
content-length: 25
content-type: text/plain; charset=utf-8
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
date: Tue, 08 Oct 2024 12:28:01 GMT
some shards are not ready
```
This PR fixes this situation by considering resharding shards as healthy. So `/readyz` returns Healthy state
=> Dont consider resharding shards as unhealthy for /readyz

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/common/common/src/defaults.rs
Bumps the development version to `1.12.1-dev` with the release of <https://github.com/qdrant/qdrant/releases/tag/v1.12.0>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5122>.
=> Bump dev version to 1.12.1-dev

lib/segment/src/payload_storage/in_memory_payload_storage.rs, lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs, lib/segment/src/payload_storage/on_disk_payload_storage.rs, lib/segment/src/payload_storage/payload_storage_base.rs, lib/segment/src/payload_storage/payload_storage_enum.rs, lib/segment/src/payload_storage/simple_payload_storage.rs, lib/segment/src/payload_storage/simple_payload_storage_impl.rs
The function `iter` to apply a callback on all elements of the payload storage is in practice mandatory so we might as well promote it to make things consistent.
=> Promote iter function to payload storage interface

lib/segment/src/index/field_index/geo_hash.rs, lib/segment/src/index/field_index/geo_index/mod.rs
Without this fix service panics if `radius: 0`
=> handle the case of empty geo hashes

lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs, lib/segment/src/payload_storage/on_disk_payload_storage.rs, lib/segment/src/payload_storage/payload_storage_base.rs, lib/segment/src/payload_storage/payload_storage_enum.rs, lib/segment/src/payload_storage/simple_payload_storage_impl.rs, lib/segment/src/segment/entry.rs, lib/segment/src/segment/mod.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs
This PR extends the existing payload storage trait to expose files to be captured in the snapshots.
This logic is currently not necessary because the existing storages rely on RocksDB which is snapshotted independently.
However this change is required for the upcoming memap based payload storage whose files will have to part of the snapshots.
=> Payload storage can include files in snapshots

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/collection_ops.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, tests/openapi/test_strictmode.py
Allows changing strict mode configuration using the update collection API.
Also makes strict mode API docs visible.
Integration tests: #5189
=> Add strict mode config to update collection API + Populate strict mode in API
