Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/collection/src/collection_builder/collection_builder.rs, lib/collection/src/collection_builder/collection_loader.rs, lib/collection/src/segment_manager/fixtures.rs, lib/collection/src/segment_manager/simple_segment_searcher.rs, lib/collection/src/update_handler/update_handler.rs, lib/collection/tests/collection_test.rs, lib/collection/tests/common/mod.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/toc.rs
New tokio version splits the worker threads and blocking threads which allows it to gracefully handle the limited number of core.
This PR also fixes https://github.com/qdrant/qdrant/issues/34
2. [x] Have you lint your code locally prior to submission?
=> Update Tokio to the latest version 

.gitignore, lib/segment/src/spaces/tools.rs
The ``peek_top_scores_iterable`` method already accepts ``scores`` by value. The ``Iterator<Item=E>`` yelds ``E``, not ``&E``, so there is no need to call ``clone`` and have ``+Clone`` trait constraint
Also added a few lines to .gitignore: clion project and storage folder
2. [x] Have you lint your code locally prior to submission?
=> Avoid cloning ScoredPointOffset when peeking the top scores

lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/mmap_vectors.rs, src/main.rs
The PR fixes [unused_io_amount](https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount) and [option_env_unwrap](https://rust-lang.github.io/rust-clippy/master/index.html#option_env_unwrap). They are reported as errors by clippy, not as warnings.
The first one looks a real bug:
``io::Write::write(_vectored)`` and ``io::Read::read(_vectored)`` are not guaranteed to process the entire buffer. They return how many bytes were processed, which might be smaller than a given buffer’s length. If you don’t need to deal with partial-write/read, use write_all/read_exact instead.
There is no clippy detected errors left after this fix, only the set of warnings
1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally using ``cargo fmt`` command prior to …
=> [CLIPPY] Fix File::write and option_env!

lib/collection/src/segment_manager/holders/proxy_segment.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/index.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/segment.rs, lib/segment/src/spaces/metric.rs, lib/segment/src/spaces/simple.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage.rs
Imagine we have ``&Vec<VectorElementType>`` (or rather it should be ``&[VectorElementType]``, but that is not important) and we want to call  ``metric.preprocess``. As it accepts vector by value, we have to clone it. However, 2 of 3 metrics does not do any normalization, so clone is useless. For the 3rd one, the ``preprocess`` would anyway iterate over the vector and create a new one, so it would be another copying operation anyway, so it could be accepting reference.
Hence, if the caller of ``preprocess`` does not need the ``Vec<VectorElementType>``, cloning is useless in both cases. If the caller needs ``Vec<VectorElementType>`` instead of ``&Vec<VectorElementType>`` it *could* clone it only if new object was not returned by ``preprocess``.  
I think it is very critical for …
=> Avoid useless vector copy during scoring

lib/segment/src/types.rs, lib/storage/src/content_manager/toc.rs, src/main.rs
I did some cosmetic fixes. Some of them just replacing `unwrap` with more verbose `expect`. But in the next one I would rewrite constructor methods with moving some parts which can fail into initiation methods to allow error handling.
=> Small cosmetics

README.md
The docker example in README is not directly useful as it refers to a locally built image:
```
docker run -p 6333:6333 \
>     -v $(pwd)/path/to/data:/qdrant/storage \
>     -v $(pwd)/path/to/custom_config.yaml:/qdrant/config/production.yaml \
>     qdrant
Unable to find image 'qdrant:latest' locally
docker: Error response from daemon: pull access denied for qdrant, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
This PR updates docker examples in README to use `generall/qdrant` as image tag to be directly useful (by copy pasting).
=> Update docker usage example for pre-built images

lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/tests/payload_index_test.rs
Condition checker is always borrowed immutable (and it makes sense since its internals are guarded by AtomicRefCell) so it's not needed to wrap it by AtomicRefCell.
=> Remove AtomicRefCell wrapper for condition checker

lib/segment/benches/vector_search.rs
In my last PR, a bug seems to somehow have slipped under my radar - a clippy lint autofix must have removed too many imports from the `vector_search.rs` file.
=> Fix ndarray imports in segment benches

Cargo.lock, lib/collection/src/collection.rs, lib/collection/src/collection_builder/collection_builder_base.rs, lib/collection/src/collection_builder/collection_loader.rs, lib/collection/src/update_handler.rs, lib/storage/Cargo.toml
Fixes following check error:
```
error[E0277]: `*mut ()` cannot be sent between threads safely
--> src/tonic/api/points_api.rs:35:60
|
35 |       ) -> Result<Response<PointsOperationResponse>, Status> {
|  ____________________________________________________________^
36 | |         let UpsertPoints {
37 | |             collection,
38 | |             wait,
...  |
60 | |         Ok(Response::new(response))
61 | |     }
| |_____^ `*mut ()` cannot be sent between threads safely
```
=> refactor: replace parking_lot with tokio mutex for WAL

lib/collection/src/collection_builder/collection_loader.rs
This PR improves the error reporting in `collection_loader`.
My existing stored data can no longer be accessed when using master, the following error is thrown:
```
thread 'main' panicked at 'Can't read collection config at ./storage/collections/test_collection', lib/collection/src/collection_builder/collection_loader.rs:21:9
```
Improving the error handling shows that the issue is caused by the work in https://github.com/qdrant/qdrant/pull/134
```
thread 'main' panicked at 'Can't read collection config due to Service internal error: Json error: missing field `max_optimization_threads` at line 1 column 324
at ./storage/collections/test_collection', lib/collection/src/collection_builder/collection_loader.rs:22:9
```
I am not sure what is the backward compatibility story for `qdrant` but in …
=> Improve error reporting in collection_loader

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/storage/Cargo.toml
This PR updates tokio to the last version `1.14.0`.
The current dependency `1.7.0` is 6 months old and a lot has been improved in the meantime.
Given the place of tokio in the architecture, it is better to update early in order to not fall behind the release train.
=> tokio 1.14.0

Cargo.lock, lib/segment/Cargo.toml
This PR updates rocksdb to the last version 1.17.0.
The current dependency 1.15 is rather old (2020-08-25) including the underlying `librocksdb-sys` dependency.
- [0.16.0](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/CHANGELOG.md#0160-2021-04-18)
- [0.17.0](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/CHANGELOG.md#0170-2021-07-22)
Given the place of rocksdb in the architecture, it is better to update early in order to not fall behind the release train.
=> rocksdb 0.17.0

src/main.rs, src/tonic/mod.rs
- Log deadlocks as `error` instead of printing them
- Minor stylistic changes to messages for consistency
- Removes global export of log macros with `macro_use`
Generally it's harmful to have something exported globally. Previously in Rust `macro_use` was the only way to use macros, but now they can be imported and used as any other function.
=> Logging updates

lib/segment/benches/vector_search.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs
Simple performance proposition. At now, Metric in vector storage is used as dyn type. Dynamic typing for each comparison may be slower than using generic types.
=> Remove dyn Metric from vector storage and use generics

.github/workflows/rust-lint.yml, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/collection_manager/tests/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/tests/mod.rs, lib/segment/benches/hnsw_build_graph.rs, lib/segment/benches/hnsw_search_graph.rs, lib/segment/benches/vector_search.rs, lib/segment/src/id_tracker/id_tracker_base.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/query_estimator.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/payload_storage_base.rs, lib/segment/src/payload_storage/query_checker.rs, lib/segment/src/payload_storage/simple_payload_storage.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/segment_constructor/simple_segment_constructor.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/segment/tests/fixtures/segment.rs, lib/segment/tests/set_payload_test.rs
Fixes #197 
Resolves #198 
Hi!
I tried my best at describing my intents in two issues I'm referencing below. In a couple words, we have two problems with Clippy in project currently, particularly with GitHub Actions workflow step:
- linting step at workflow may potentially use an old version of clippy and rustfmt
- clippy step at workflow checks only the source code of the root package, ignoring other workspace members (`lib/`)
Additionally, I have tried to satisfy clippy warnings we have. 
I've had success with most of them: according to my UI, we've improved from 84 warnings to 10 warnings project-wide, 8 of which are temporary compilation problems not related to lints.
I feel like the last two lint warnings left unsolved require more thoughts and discussions, so it would make sense to …
=> Extend clippy to workspace and fix some warnings

Cargo.lock, Cargo.toml
This PR updates `actix-web` to 4.0.0-beta.20.
The motivation is to avoid falling back behind the release train too much as a lot is changing in terms of underlying dependencies.
=> actix-web 4.0.0-beta.20

lib/collection/src/collection.rs, lib/collection/src/common/mod.rs, lib/collection/src/common/stoppable_task.rs, lib/collection/src/lib.rs, lib/collection/src/tests/mod.rs, lib/collection/src/update_handler.rs, src/tonic/qdrant.rs
Use StoppableTaskHandler instead of regular `tokio::task` for better control over launched optimizations.
This wrapper allows to check if the optimization task is finished without consuming the handle.
Additionally it provides the interface for faster stopping of the tasks, which is required for https://github.com/qdrant/qdrant/issues/31
ToDo: merge after https://github.com/qdrant/qdrant/pull/155
=> [WIP] Clear optimization handles 30

Dockerfile
[1.58.1](https://github.com/rust-lang/rust/releases/tag/1.58.1) fixes a CVE
=> Rust 1.58.1 in Docker file

docs/DEVELOPMENT.md
Changing the API requires several manual steps to keep the `openapi` specification in sync. with the code.
Discovering and remembering those steps is not straight forward so this PR adds a documentation for it.
=> document API change process

lib/collection/src/collection.rs, lib/collection/src/collection_builder/collection_builder_base.rs, lib/segment/tests/segment_builder_test.rs, src/common/helpers.rs, src/main.rs, src/tonic/mod.rs
This PR adds names for most of the threads in the system to improve observability (appears in flamegraphs as well).
- Before
- After
There are still `number of cpu` threads that I could not find the origin of.
=> name threads for observability

lib/collection/src/collection.rs
The updater pipeline reply with only one message.
We can simplify the code by using a special purpose channel which is optimized for holding at most one message.
=> size client response channel to reflect reality

lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/toc.rs
Closes #275 
The problem was in the fact that stop signal was sent twice on collection deletion, which led to the signal being sent to an already closed channel (as worker stops after the first message) on the second attempt.
- In async-channels you could clone the `Receiver`
- So the sending will fail only if all receivers were dropped
- `UpdateHandler` that spawns worker threads, cloned the receiver to put it into the worker thread, but never used its own receiver
- So when the `Collection` is dropped and worker threads are ordered to close - their communication channel will never close as there was always a receiver in `UpdateHandler`
Now:
- In tokio ordinary unbounded channel receivers cannot be cloned
- To clone a receiver you would need a broadcast channel
- So in the …
=> Avoid sending stop signal more than once

lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/operations/payload_ops.rs, src/common/points.rs, tests/basic_api_test.sh
=> remove payload using filters (#269)

lib/segment/src/types.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/proto/points.proto, src/tonic/qdrant.rs
This PR performs the change to the gRPC API described in https://github.com/qdrant/qdrant/issues/242.
Interesting points for the reviewers:
- gRPC enums are modeled using [one_of](https://developers.google.com/protocol-buffers/docs/proto3#oneof).
- as `one_of` worked fine I decided to refactor existing enums as well for consistency
- decided to remove to not implement the `Upsert` API to keep things simple.
- introduced several dedicated `PayloadRequest` type as the regular ones hold a vector of data instead of a single element
=> new gRPC points update API #242

.github/workflows/integration-tests.yml, tests/basic_api_test.sh, tests/basic_grpc_test.sh, tests/integration-tests.sh
This PR is related to our effort to improve integration testing #232 
The goal of this change is to setup a safety net to avoid regressions while we decide on a long term strategy for integration testing. 
**This PR is not a long term solution**.
The change consists in executing our existing bash scripts tests as part of the CI pipeline.
It took me some time to make it work exactly like I wanted. 
1. build in debug mode
2. run binary in the background and capture PID for later
3. wait for the server to be up by probing it at regular interval
4. run REST tests
5. run gRPC tests
6. shutdown server with PID
Currently the main drawback is that the server is not shutdown if a tests fail, which is only a problem locally.
=> use existing integration tests as CI

.gitattributes, .github/workflows/storage-compat.yml, tests/storage-compat/README.md, tests/storage-compat/storage-compatibility.sh, tests/storage-compat/storage.tar.bz2
This PR tackles the validation of storage compatibility #286 
The goal is to detect when a PR breaks the storage compatibility with CI.
The strategy is to save the `storage` folder resulting from running `./tests/basic_api_test.sh` once and then check that we can still read it for each PR.
`storage.tar.bz2` needs to be refreshed every time we break the compatibility
```
du -sh storage.tar.bz2 
36K	storage.tar.bz2
```
edit: due to the size of the file, it is managed using https://git-lfs.github.com/
=> validate storage compatibility - (#286)

docs/redoc/master/openapi.json, lib/collection/src/collection.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/simple_collection_searcher.rs, lib/collection/src/collection_manager/tests/mod.rs, lib/collection/src/operations/types.rs, lib/collection/src/tests/mod.rs, lib/collection/src/update_handler.rs, lib/segment/src/common/file_operations.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/tests/fail_recovery_test.rs
this PR includes:
- New status field for optimizer error: if optimizer fails with error - it will be displayed in collection info, status of the collection will be `Red`
- Decouple segment exclusion from the collection and actual data removing. If data removing fails - all required segment swaps will still be performed. It also allowed to make some functions pure (without Result)
- Fix behavior of the optimizer, finished worker notifies the optimization handler that it might be good to check if some segments require further optimization 
=> Better optimizer error reporting + small bug fixes

benches/service/collection_stress.js, benches/service/run.sh
This PR performs a tiny cleanup of the `collection_stress` benchmark.
I got confused by the default 10m0s default max duration for `k6` which makes the bench stop way too early.
```
scenarios: (100.00%) 1 scenario, 10 max VUs, 10m30s max duration (incl. graceful stop):
* default: 500000 iterations shared among 10 VUs (maxDuration: 10m0s, gracefulStop: 30s)
```
Making the `duration` parameter explicit enables us to easily shoot for longer period of times.
```
scenarios: (100.00%) 1 scenario, 10 max VUs, 30m30s max duration (incl. graceful stop):
* default: 500000 iterations shared among 10 VUs (maxDuration: 30m0s, gracefulStop: 30s)
```
As a bonus I have added the extraction of a constant in the script.
=> clean collection stress

.github/workflows/integration-tests.yml, tests/integration-tests.sh
In https://github.com/qdrant/qdrant/pull/320 we have added a cache to reuse various artifacts generated by cargo.
This has successfully decreased the build time of all jobs but the integration tests jobs.
The reason is that all jobs are using the same cache key BUT the integration tests job is built with the `gRPC` flag.
To avoid false sharing, the integration test job is now using a dedicated key cache for differentiation. 
This brings the run time from 17 minutes to 10 minutes.
=> Integration tests use dedicated key cache to avoid false sharing

.github/workflows/rust-lint.yml
Same logic as in https://github.com/qdrant/qdrant/pull/335 but for Clippy this time.
=> Dedicated cache key for Clippy build

config/config.yaml, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shard.rs, lib/collection/src/update_handler.rs
Fixes a problem with not removed WAL files.
Ideally there should remain (after some time) at maximum 1 closed WAL files and 2 open. Before this fix there were situations when there would be multiple closed files and they were never removed as the time progressed. The problem seemed to be that at the time of flush requests (on update) not all segments have saved all updates yet.
With periodic flushing this problem is fixed and the system always comes to a state when there is at most 1 closed wal file if there are no more updates for some time. Additionally this introduces an advantage of decreased CPU and disk load.
=> Periodic flushing

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/storage/Cargo.toml
I was wondering why Dependabot did not propose this update as it is already 8 days old.
So this PR updates Tokio to 1.17 https://github.com/tokio-rs/tokio/releases/tag/tokio-1.17.0 as it contains interesting fixes.
=> update tokio 1.17

lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/segment/src/segment.rs, lib/segment/tests/fail_recovery_test.rs, lib/segment/tests/set_payload_test.rs
Updating to Rust 1.59 and using the latest [Clippy](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-159) version locally yields some errors.
This PR fixes those issues right away to avoid blocking the CI pipeline in the near future.
=> fix new clippy lints in 1.59

lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/lib.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/operations/point_ops.rs
Introduces traits and their implementations for update operations:
- `SplitByShard`
- `Validate`
In future PRs:
- consistent hashing will replace the `point_to_shard` stub
- Multiple shards will be added
=> Split operation by shard

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/mod.rs, lib/segment/src/lib.rs
issue context: https://github.com/qdrant/qdrant/issues/313
The goal of this PR is to turn a geo query into a set of [geohashes](https://en.wikipedia.org/wiki/Geohash) to probe later on the indexer for matching points (in a follow up PR).
To do so it introduces two main functions to deal with either circle or rectangle areas:
```rust
/// Return as-high-as-possible with maximum of `max_regions`
/// number of geo-hash guaranteed to contain the whole circle.
fn circle_hashes(circle: GeoRadius, max_regions: usize) -> Vec<GeoHash> {}
/// Return as-high-as-possible with maximum of `max_regions`
/// number of geo-hash guaranteed to contain the whole rectangle.
fn rectangle_hashes(rectangles: GeoBoundingBox, max_regions: usize) -> Vec<GeoHash> {}
```
Those functions work by estimating the …
=> Turn geo query into set of geohashes

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/lib.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/operations/point_ops.rs
Consistent hashing is used for shard selection based on point id.
Choice: https://github.com/jeromefroe/hashring-rs
Pros:
+ Default hash function is ok, can be swapped
+ Uses `Hash` trait
+ Updated in 2020
+ Uses binary search to find shard
Cons:
- Weird transformation at key generation, seems unneeded
Alt: https://github.com/mattnenterprise/rust-hash-ring
Pros:
+ Default hash function is ok, can be swapped
+ Updated in 2020
Cons:
- Needs `ToString` instead of `Hash`
- Uses linear search to find shard
Others have few downloads and are long forgotten or unfinished.
Generally it would not be difficult to write our own lib if we wanted to swap.
The selected library was forked to [fix](https://github.com/qdrant/hashring-rs/commit/36477e847213054db7eae7677a5b4652aef96655) minor issue with …
=> Add consistent hashing library

lib/segment/benches/hnsw_search_graph.rs
Found with the following log
```
16:35:27 [WARN] Benchmark group hnsw-index-build-group encountered again. Benchmark group IDs must be unique. First seen in the benchmark target 'hnsw_build_graph'
```
=> fix duplicate bench group

docs/redoc/master/openapi.json, openapi/openapi-collections.ytt.yaml, openapi/openapi-main.ytt.yaml, openapi/openapi-points.ytt.yaml, openapi/tests/openapi_integration/helpers/collection_setup.py, openapi/tests/openapi_integration/test_alias.py, openapi/tests/openapi_integration/test_basic_retrieve_api.py, openapi/tests/openapi_integration/test_collection_update.py, openapi/tests/openapi_integration/test_delete_points.py, openapi/tests/openapi_integration/test_payload_indexing.py, openapi/tests/openapi_integration/test_payload_operations.py, openapi/tests/openapi_integration/test_schema_consistency.py, openapi/tests/openapi_integration/test_uuid_ops.py
* Unifies naming of the path parameter `collection_name`
There were a problem with un-update python client which, which used `collection_name` instead of `name` in some places. It was impossible to update consistently without loosing backward compatibility, unfortunately.
This will require 0.6.0 release
=> upd naming in api

.github/workflows/integration-tests.yml, Cargo.toml, config/config.yaml, config/development.yaml, config/production.yaml, docs/DEVELOPMENT.md, src/actix/mod.rs, src/main.rs, src/settings.rs, src/tonic/mod.rs, tests/integration-tests.sh
This PR enables the gRPC endpoint via runtime configuration instead of a build feature https://github.com/qdrant/qdrant/issues/350
This is done by changing the `grpc_port` settings to be an `Option` which is not a breaking change for the serialization of the configuration.
=> enable gRPC via a runtime config

Cargo.lock, build.rs, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/collection/Cargo.toml, lib/collection/src/collection_manager/fixtures.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/config.rs, lib/collection/src/lib.rs, lib/collection/src/operations/types.rs, lib/collection/src/optimizers_builder.rs, lib/collection/src/shard.rs, lib/collection/tests/collection_restore_test.rs, lib/collection/tests/collection_test.rs, lib/collection/tests/common/mod.rs, lib/storage/src/content_manager/collections_ops.rs, lib/storage/src/content_manager/toc.rs, src/tonic/api/collections_api.rs, src/tonic/proto/collections.proto, src/tonic/qdrant.rs
Closes #323 
- Introduces option to have multiple shards in a collection
- Sets default number of shards to 1
- Read legacy format with 1 shard
- Async drop update for collection
- Collection tests for 1 and 10 shards 
- Hashring set to updated `0.2.1` version (our PR was merged)
- Fix tonic API generation problem
During tests it was noticed that with 10 or more shards, futures in Drop were stuck on await though technically ready. Upon closer investigation I found that `futures::block_on` is used in Drop, but `Drop` happens in tokio context - this probably leads to some wakers being lost.
Generally tokio does not allow spawning a new runtime inside another runtime. And with external runtimes (like `futures`) it is considered to be an undefined behavior AFAIK.
Therefore I introduce async …
=> Multiple shards in collection

lib/collection/src/lib.rs, lib/collection/src/shard.rs, lib/collection/tests/collection_restore_test.rs, lib/collection/tests/collection_test.rs, lib/collection/tests/common/mod.rs, lib/storage/src/content_manager/toc.rs
1. Fixes shard drop on collection creation (Closes #379 )
2. Fixes collection info method - 
previously info method could count same segment's info twice.
3. Concurrent waiting for the shard drop
4. Decreased number of shards per collection in tests to 3, number of segments to 2
=> Fixes shard drop on collection creation

benches/service/collection_stress.js
The current performance `k6` script does not work anymore as it is using the deprecated collection API which has changed the field `name` to `collection_name` for collection creation.
This PR fixes this benchmark  by migrating it to the latest API version.
```
✓ upsert_points is status 200
█ setup
✓ delete_collection_payload is status 200
✓ create_collection_payload is status 200
```
=> bench uses latest API

Cargo.lock, Cargo.toml, lib/collection/src/lib.rs, src/consensus.rs, src/main.rs
Closes #386 
Consensus will be used to synchronize global state which is:
- Collection meta
- Shard to Peer mapping
Most of this pull request is based on:
- Raft 1 peer example - https://github.com/tikv/raft-rs/blob/master/examples/single_mem_node/main.rs
- Raft snippets in https://docs.rs/raft/latest/raft/index.html
Consensus start is behind a feature gate to not worsen performance for users as consensus in 1 peer case is basically useless. It is only for development for now.
1. https://github.com/tikv/raft-rs
1. Pros: 
1. Used in production
2. Highly configurable/customizable
2. Cons: 
1. Slightly complicated to setup
4. Stars: 2k
5. Conclusion: Suggested to use
2. https://github.com/async-raft/async-raft
1. Pros:
1. Simple interface
2. Good documentation
2. Cons:
1. Limited …
=> Introduces consensus with Raft

lib/collection/src/lib.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/shard.rs, lib/collection/src/shard/local_shard.rs, lib/collection/src/shard/mod.rs, lib/collection/src/shard/remote_shard.rs
This PR introduces the possibility to have local and remote shards #373 
As a result the shard operations are abstracted behind a `ShardOperations` trait which will enable us to implement the remote shard later on.
The code regarding shards has been split and gathered under a new `shard` module.
The polymorphism has been implemented following the style found in `LockedSegment` for consistency.
It is easier to review commit by commit as some files moved.
=> [sharding] Introduce local & remote shards

.github/dependabot.yml
This PR setups Dependabot so that it updates as well the Github actions used.
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
=> setup dependabot for Github actions

Dockerfile
Fixes
```
Compiling qdrant v0.6.0 (/qdrant)
error: failed to run custom build command for `qdrant v0.6.0 (/qdrant)`
Caused by:
process didn't exit successfully: `/qdrant/target/release/build/qdrant-8318c117d38401e4/build-script-build` (exit status: 1)
--- stderr
error: 'rustfmt' is not installed for the toolchain '1.59.0-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt`
warning: build failed, waiting for other jobs to finish...
error: build failed
```
=> add rustfmt to build docker

lib/segment/src/fixtures/payload_fixtures.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/geo_hash.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/index_selector.rs, lib/segment/src/index/field_index/mod.rs, lib/segment/src/index/field_index/numeric_index.rs, lib/segment/src/index/field_index/stat_tools.rs, lib/segment/src/index/query_estimator.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/types.rs, lib/segment/tests/payload_index_test.rs
This PR adds a new indexing scheme for geo payloads https://github.com/qdrant/qdrant/issues/362
Notes:
- the initial `geo_index` file has been renamed to `geo_hash` to make space for the new `PersistedGeoMapIndex`
=> index geo payload

openapi/.gitignore
This PR adds the `__pycache__/` directories to the `.gitignore`.
Two of those are left behind after running `./tests/openapi_integration_test.sh`
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
openapi/tests/openapi_integration/__pycache__/
openapi/tests/openapi_integration/helpers/__pycache__/
```
=> gitignore __pycache__/

Cargo.lock, config/development.yaml, lib/segment/src/common/file_operations.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/index/hnsw_index/config.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/payload_config.rs, lib/segment/src/lib.rs, lib/segment/src/payload_storage/simple_payload_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/alias_mapping.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, openapi/tests/openapi_integration/test_alias.py, openapi/tests/run_docker.sh
This PR tackles #204 by migrating the persistence for alias mappings from [Sled](https://github.com/spacejam/sled) to a simple json file.
- The content of the mapping is kept in memory and sync. to disk when modified.
- In order to reuse the utilities in [file_operations](https://github.com/qdrant/qdrant/blob/e45379e4384062e92ee1c9be82c250047464c9ef/lib/segment/src/common/file_operations.rs#L22), a new error representation was introduced to cleanly separate `OperationError` and `StorageError`.
- Alias renaming is kept atomic as the previous implementation.
=> Remove sled for alias mappings

lib/storage/src/content_manager/toc.rs, src/tonic/api/collections_api.rs, src/tonic/proto/collections.proto, src/tonic/qdrant.rs, tests/basic_grpc_test.sh
This PR exposes the collection alias management feature as a gRPC endpoint https://github.com/qdrant/qdrant/issues/398
It follows closely the REST implementation as we need to preserve the atomicity property when applying several update operations sequentially.
=> alias gRPC endpoint

lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/index/field_index/numeric_index.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/types.rs
https://github.com/qdrant/qdrant/issues/392 - enable column-oriented storage of the values in the FieldIndex for faster condition checking.
=> Column index

QUICK_START.md, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/lib.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/payload_storage/query_checker.rs, lib/segment/src/types.rs, openapi/openapi-main.ytt.yaml, openapi/tests/openapi_integration/test_basic_retrieve_api.py, openapi/tests/openapi_integration/test_collection_update.py, openapi/tests/openapi_integration/test_uuid_ops.py, tests/basic_api_test.sh
Implements https://github.com/qdrant/qdrant/issues/415
Refactors `Match` condition so that it does not require explicit type specification.
=> Bool filter

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/proto/qdrant.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/lib.rs, lib/collection/src/operations/types.rs, lib/collection/tests/collection_restore_test.rs, lib/collection/tests/collection_test.rs, lib/storage/src/content_manager/toc.rs, src/actix/api/update_api.rs, src/common/points.rs, src/tonic/api/mod.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs, src/tonic/mod.rs
This PR adds a shard aware update API. https://github.com/qdrant/qdrant/issues/419
A new optional `shard_selection` parameter is propagated down the stack to choose how to handle the update:
- `update_from_client` is the current public API which splits batches by shards for redistribution
- `update_from_peer` is the new API which expects the `shard_selection` to be one of the peer's local shard (the error handling needs to be revised) 
In order to validate the current direction I have implemented a single method on a newly introduced internal gRPC API to get a feel for the complete integration.
I tried to mitigate code duplication by introducing a common API layer `points_common.rs`.
=> [Sharding] Shard aware updates for internal API

.github/workflows/integration-tests.yml, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/config_diff.rs, lib/segment/src/types.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/toc.rs, lib/storage/tests/alias_tests.rs, src/actix/api/collections_api.rs, src/consensus.rs, src/tonic/api/collections_api.rs
Relates to #429 
After this PR all collection meta operations with consensus feature enabled will be waiting for commit before answering request.
Integration tests are also enabled for consensus feature. As now their behavior is valid (they expect that each request returns when an operation is complete)
Actually propagating changes to the API was left out for a separate PR. 
- `CollectionMetaOperations` supplied by client are relatively unique and therefore can be compared by hash/eq
=> Wait for operation commit

lib/api/src/grpc/qdrant.rs, lib/storage/src/content_manager/toc.rs
New clippy version is breaking on our code base on CI.
```
error: question mark operator is useless here
--> lib/storage/src/content_manager/toc.rs:373:9
|
373 | /         Ok(tokio::time::timeout(wait_timeout, receiver)
374 | |             .await
375 | |             .map_err(
376 | |                 |_: tokio::time::error::Elapsed| StorageError::ServiceError {
...   |
382 | |                 // ??? - forwards 3 possible errors: timeout, sender dropped, operation failed
383 | |             )???)
| |_________________^
|
= note: `-D clippy::needless-question-mark` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_question_mark
help: try removing question mark and `Ok()`
|
373 ~ …
```
=> Make clippy 1.60 green

lib/api/src/grpc/mod.rs, lib/api/src/grpc/qdrant.rs
Tonic is formatting its output with `prettyplease` since [0.7](https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#070-2022-03-31=)
This conflicts with our pre-push commit hook which runs the standard `fmt`.
This PR avoids reformatting unnecessarily the generated files from Tonic.
=> do not format output of tonic as it is now using prettyplease

lib/segment/benches/hnsw_build_asymptotic.rs, lib/segment/benches/hnsw_search_graph.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/point_scorer.rs
There is some refactoring aimed to improve semantics of the function.
As I understood, the function `score_points_to_buffer` only used the buffer as internal temporary storage and never supposed to return anything in it.
**Considered alternative**
It was also possible to remove `action` instead and use the temporary buffer for returning the values. But in this case it would be a bit more complicated for the calling side, as it would be required to create and iterate over the buffer explicitly.
=> refactor `score_points` for better semantics

.github/dependabot.yml
This PR configures Dependabot to handle our docker file.
We will stay up to date on Rust and Debian versions automatically.
=> configure Dependabot to update our Dockerfile

CONTRIBUTING.md, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/storage/src/content_manager/conversions.rs, openapi/openapi-collections.ytt.yaml, src/actix/api/collections_api.rs, src/tonic/api/collections_api.rs
- Allows specifying collection meta operation commit timeout in API
- Also restructures a part of gRPC collection API to have less boilerplate 
Closes #429
=> Allows specifying collection meta operation commit timeout in API

lib/segment/benches/hnsw_build_asymptotic.rs, lib/segment/benches/hnsw_build_graph.rs, lib/segment/benches/hnsw_search_graph.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/hnsw_index/point_scorer.rs
Method `FilteredScorer.score_points` does only one thing: score points and return a slice of the scores result. I propose these changes because filtered scorer api is simpler (as an advantage). As a disadvantage, we have to use mutable references because FilteredScorer contains a buffer for results.
=> Remove overcomplicated iterator: no action in scorer

lib/segment/src/vector_storage/chunked_vectors.rs
According to benchmark, `CHUNK_SIZE` have a great impact on the HNSW search performance:
* 9% speedup for 1Mb  `CHUNK_SIZE` 
* 11% speedup for 10Mb  `CHUNK_SIZE` 
* 14% speedup for 20Mb  `CHUNK_SIZE`
At the same time allocating 20Mb of RAM for each segment for an empty collection might be too wasteful (100Mb of zeros).
The compromise solution I see here is to allow dynamic scaling within each chunk. We are avoiding large re-allocations - copying 16Mb of RAM  should be within the noise threshold. At the same time we achieve better memory locality and smaller starting memory consumption.
=> vector storage chunk autoscaling

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs
This PR addresses partially https://github.com/qdrant/qdrant/issues/433 by tackling first the `CollectionUpdateOperations`.
Others operations required broader change which would made a single PR difficult to review.
The approach is to exposed an API that looks like the existing one adding an extra argument to select the target shard.
The change ends up being rather mechanical as the between public and internal API is shared in `points_common`.
=> [sharding] add internal API for CollectionUpdateOperations

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/lib.rs, lib/collection/src/operations/types.rs, lib/collection/tests/collection_restore_test.rs, lib/collection/tests/collection_test.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/toc.rs, src/actix/api/recommend_api.rs, src/actix/api/retrieve_api.rs, src/actix/api/search_api.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs
Follow up on https://github.com/qdrant/qdrant/pull/445 (https://github.com/qdrant/qdrant/issues/433) for the methods:
- search
- recommend
- scroll
This PR uses the same approach regarding sharing code via `points_common.rs`.
I have decided to introduce at the collection level `local_shard_by_id` to unify the shard selection error handling.
After this PR, the only method left on `ShardOperation` to implement is `info(&self) -> CollectionResult<CollectionInfo>`
=> [sharding] Add internal gRPC API for search recommend & scroll

lib/segment/tests/payload_index_test.rs
Fixes https://github.com/qdrant/qdrant/issues/472
The reason was that test expected structure cardinality estimation to be more precise than naive one, but even a broken clock gets to be right twice a day.
=> also consider the corner case in test

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/storage/src/content_manager/toc.rs, src/actix/api/retrieve_api.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs
Follow up on https://github.com/qdrant/qdrant/pull/463 (https://github.com/qdrant/qdrant/issues/433).
This PR adds the `retrieve` method to the internal gRPC API for p2p communication.
=> [Sharding] internal API for shard-aware points retrieval

lib/api/src/grpc/proto/collections_internal_service.proto, lib/api/src/grpc/proto/qdrant.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/lib.rs, lib/collection/tests/collection_restore_test.rs, src/actix/api/collections_api.rs, src/common/collections.rs, src/tonic/api/collections_api.rs, src/tonic/api/collections_common.rs, src/tonic/api/collections_internal_api.rs, src/tonic/api/mod.rs, src/tonic/mod.rs
Follow up on https://github.com/qdrant/qdrant/pull/475 (https://github.com/qdrant/qdrant/issues/433).
This PR adds the method get collection info to the internal gRPC API for p2p communication.
This was the last method necessary to enable the implementation of `ShardOperation` for remote shards.
=> [Sharding] Internal gRPC API for get collection info

lib/collection/src/lib.rs, lib/collection/src/operations/types.rs
This PR is part of #467 and adds the concurrent execution of shard operations for:
- `search`
- `retrieve`
- `scroll_by`
- `recommend_by` (transitively)
- `info`
It tries to apply the same pattern using `FuturesUnordered` at every call sites to setup a convention.
Some methods are still performing the shard operations sequentially and could be tackled in another PR:
- `update_from_client` (tried to migrate it but more changes are required)
- `update_optimizer_params_from_diff`
- `update_optimizer_params`
I had some problems a long the way with rustc, thank to @e-ivkov for the help!
=> [Sharding] Shard operations are executed concurrently

.github/workflows/rust.yml, lib/storage/src/content_manager/alias_mapping.rs, lib/storage/src/content_manager/toc.rs, lib/storage/tests/alias_tests.rs
Closes #491 
Alias test uses `submit_collection_operation` which behavior differs based on `consensus` feature.
With this feature enabled it requires Raft to finalize the operation, but in this test Raft is not started.
1. Limit the test to work only without consensus feature
(We already have a specific case which checks collection operations with consensus)
2. Improve error reporting for cases when Raft was not started but ToC tries to access it.
3. Run with `--all` consensus tests to detect such cases faster
=> Fixes `test_alias_operation`

lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, lib/storage/tests/alias_tests.rs
It is done with `serde(default)` instead of feature as having features for config is usually ugly, it would force us to have 2 configs at this stage for example.
=> Adds `PeerAddressById` to `StorageConfig`

Cargo.lock, lib/api/Cargo.toml, lib/api/src/grpc/mod.rs, src/actix/mod.rs
There is a problem with version returned from `/` API. Data structure relies on compile-time variable in `lib/api` crate which might be different from main crate. 
I didn't find an easy way to ensure single source of truth for the version in both crates, so I decided to ensure equivalence instead.
Alternatives:
I considered using https://github.com/nvzqz/static-assertions-rs, but didn't succeed in making it work.
=> ensure lib/api version is same as main package

lib/segment/src/spaces/simple.rs
When the dimension is lower than simd processing stride, it is faster to use regular functions instead of simd
=> Disable simd on small dimensions

lib/segment/src/spaces/tools.rs
Small optimization. Do only `pop` in a binary tree instead of `push`+`pop`
=> optimize push in fixed priority queue

Cargo.lock
This PR is a first experiment with [cargo-audit](https://lib.rs/crates/cargo-audit) to track crates with security vulnerabilities.
Running `cargo audit` on master yields the following wall of text.
```
Scanning Cargo.lock for vulnerabilities (386 crate dependencies)
Crate:         crossbeam-deque
Version:       0.8.0
Title:         Data race in crossbeam-deque
Date:          2021-07-30
ID:            RUSTSEC-2021-0093
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0093
Solution:      Upgrade to >=0.7.4, <0.8.0 OR >=0.8.1
Dependency tree: 
crossbeam-deque 0.8.0
├── rayon-core 1.9.1
│   └── rayon 1.5.1
│       └── criterion 0.3.5
│           ├── segment 0.3.1
│           │   ├── storage 0.2.0
│           │   │   └── qdrant 0.7.0
│           │   ├── qdrant 0.7.0
│           │ …
```
=> Run cargo audit fix

lib/segment/tests/payload_index_test.rs
This PR documents and improve the error reporting for #534 
I have tried different strategies to reproduce the bug locally but none worked out:
- repeating the whole test many times
- increasing the number of `attempts`
- repeating the whole test many times with a different `StdRng::seed_from_u64`
Hopefully we will get more info next time it fails.
=> document flaky test and add more info in case of failure

Cargo.lock, Cargo.toml, lib/api/src/grpc/proto/raft_service.proto, lib/api/src/grpc/qdrant.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/raft_state.rs, lib/storage/src/content_manager/toc.rs, src/consensus.rs, src/main.rs, src/tonic/api/raft_api.rs, src/tonic/mod.rs
1. Peer address to id map is synced with consensus
2. New peers still have to pre-fetch the addresses as otherwise they will not be able to answer during sync (consequently failing sync)
3. For pre-fetching addresses and requesting peer addition bootstrap logic is introduced (CLI args, API, logic in consensus module)
Closes https://github.com/qdrant/qdrant/issues/514
1. Adding peer to consensus https://github.com/qdrant/qdrant/issues/530
2. Tests? 
At this stage they might not be very useful for bootstrap logic. After we implement https://github.com/qdrant/qdrant/issues/530 though we will be able to test the whole peer addresses sync.
=> Allows bootstrapping peer on addition

src/actix/mod.rs, tests/basic_api_test.sh
This PR tackles the issue #555 
The JSON decoding of input payload takes place in the Actix infrastructure in order to enable endpoints to handle directly the deserialized objects.
However this infra. does not follow the same convention as the errors created by the endpoints directly, in this case it returns error as plain text.
This PR fixes our `json_error_handler` called by Actix in order to serve a JSON error payload in those cases as well.
=> Return a JSON body in case of JSON decoding error

config/config.yaml, config/development.yaml, config/production.yaml, lib/collection/src/shard/remote_shard.rs, src/consensus.rs, src/main.rs, src/settings.rs
This PR introduce a proper configuration for the distributed deployment. #495
One decision I took is to separate the `consensus` configuration from the strictly `p2p` configuration as there are kind of orthogonal.
The cluster deployment is still hidden behind the compile time flag `--features consensus`, it will be addressed later on in #511.
=> [Sharding] Introduce cluster configuration

README.md
Dockerhub doesn't display Markdown emojis properly and doesn't support relative links to other files hosted on Github. This PR changes all emojis to corresponding UTF-8 characters and converts relative links to absolute ones, so Dockerhub is displayed in the same way as on Github.
=> Update README to fix links and emojis on Dockerhub

.github/workflows/integration-tests.yml, .github/workflows/rust.yml, Cargo.toml, lib/storage/Cargo.toml, lib/storage/src/content_manager/alias_mapping.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, lib/storage/tests/alias_tests.rs, src/consensus.rs, src/main.rs, src/settings.rs, src/tonic/api/mod.rs, src/tonic/mod.rs, tests/integration-tests.sh
This PR switch the consensus from a conditional compilation cargo feature to a runtime configuration https://github.com/qdrant/qdrant/issues/511
This means:
- the consensus code is now compiled by default
- the consensus unit tests are executed by default
- the distributed deployment toggle is the `cluster.enabled` configuration field (false by default)
- the integration test bash script has a new parameter to toggle the distributed mode
- the `toc` is aware of the distribution mode
=> Switch consensus to a runtime configuration

lib/segment/src/common/rocksdb_operations.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/payload_storage/simple_payload_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs
Disable writing to WAL for each rocksdb put calling
=> Disable wal for rocksdb

Cargo.lock, lib/api/Cargo.toml, lib/api/src/grpc/mod.rs, lib/api/src/grpc/transport_channel_pool.rs, lib/collection/src/shard/remote_shard.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/toc.rs, src/consensus.rs, src/main.rs, src/settings.rs
This PR adds a pooling system of gRPC transport channels #584
The pooling is used in both the Raft messaging and in the remote shards interactions to avoid having to establish network connections at each interactions with other peers.
The recommended way to pool Tonic's transport channels is to clone them.
https://github.com/hyperium/tonic/blob/de2e4ac077c076736dc451f3415ea7da1a61a560/tonic/src/transport/channel/mod.rs#L50-L67
The proposed solution is to hold in memory mappings between `URI` and a `Vec<Channel>` and to serve clones of the channels on demand.
Throughput can be increased by increasing the size of the pool of channels to clone from.
Those channels are configured with proper timeouts and will try to reconnect automatically on network errors.
I had to unify the `p2p` and …
=> Pool gRPC transport channels

lib/segment/src/index/field_index/btree_index.rs, lib/segment/src/index/field_index/mod.rs, lib/segment/src/index/key_encoding.rs
Implementation of `PayloadFieldIndex` for numeric data, which should replace currently used outdated implementation.
Old implementation uses sorted array, which could not be dynamically extended.
New implementation uses BTree with some clever encoding tricks explained in https://www.notion.so/qdrant/On-flight-index-updates-d20b4606bafa4f499488bf7cd67816af
Out of scope:
- cardinality estimation
- persistance
- integration with existing payload index interface
=> [real-time index] add In-mem btree numeric index

.github/workflows/integration-tests.yml, .gitignore, lib/storage/src/content_manager/toc.rs, src/main.rs, src/settings.rs, tests/python_tests/.gitignore, tests/python_tests/conftest.py, tests/python_tests/multipeer_test.py
Closes #582
Also contains fixes for snapshot and wal handling as several bugs were discovered during the test.
- Test is written in python as the logic seems too complex for bash script to handle it and be easy to understand
- Pytest python testing framework is used to run it
- Current number of peers is set to 5
=> Add multipeer deployment test

src/main.rs
- Proper setup of custom filter without env var
- Sets h2 logging to error only. During debugging consensus h2 logs are a pain as they are everywhere.
=> Log only h2 errors

Cargo.lock, Cargo.toml, config/config.yaml, src/actix/mod.rs, src/settings.rs
Allows to enable CORS headers in Actix web server - if configured - Actix will enable CORS (true by default)
Useful for accessing REST API with browser for debugging
Related to https://github.com/qdrant/qdrant/issues/610
=> add optional CORS headers

lib/storage/src/content_manager/raft_state.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/lib.rs
- Removes `RaftStateWrapper` and `PeerAddressByIdWrapper` which helped with serde serialization.
- Uses alternative way through serde attributes
This should help with limiting propagation of wrapper types to the outer code.
=> Remove serialization wrappers

lib/collection/src/lib.rs, lib/collection/src/shard/remote_shard.rs, lib/collection/tests/collection_restore_test.rs, lib/collection/tests/collection_test.rs, lib/collection/tests/common/mod.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/raft_state.rs, lib/storage/src/content_manager/shard_distribution.rs, lib/storage/src/content_manager/toc.rs, src/consensus.rs, tests/consensus_tests/test_collection_created_after.py, tests/consensus_tests/test_collection_created_before.py, tests/consensus_tests/test_collection_sharding.py
This PR handles remote shards during collection creation https://github.com/qdrant/qdrant/issues/519
When a peer receives a `create_collection` command, it generates a proposal to allocate the new collection's shards among all peers available.
The current strategy is to aim for having the same number of shards on all peers which should be good enough for the time being.
This proposal is bundled with the `create_collection` command and sent down the Raft consensus pipeline.
Once the bundle is committed, all peers will apply the `create_collection` command and respect the proposal regarding the shards that they have been attributed.
There is an integration test that inserts points and search works with several peers and several shards.
An important piece is left out of this PR in order to …
=> [sharding] Materialize remote shards

lib/segment/src/spaces/simple.rs
Fix compilation warning for arm build (`const MIN_DIM_SIZE_SIMD` on arm is needed only when neon presents)
=> arm unused const warning

lib/collection/src/lib.rs, lib/collection/src/operations/types.rs, lib/collection/src/shard/local_shard.rs, lib/collection/src/shard/mod.rs, lib/collection/src/shard/remote_shard.rs, lib/collection/src/shard/shard_config.rs, lib/collection/tests/common/mod.rs, lib/storage/src/content_manager/toc.rs
This PR adds persistence of the shard information https://github.com/qdrant/qdrant/issues/618
The information is required at startup time in order to keep track of the remote shards.
The solution proposed is to have a `config.json` file in **every** shard folder which will indicate:
- the shard type: local vs remote
- the peer_id which owns the shard in case of a remote shard
Some information about the file:
- it uses the JSON format as it is preferable to have something human readable
- it is created by default for existing local shards
This PR still misses an integration test where peers in a cluster are restarted.
=> [sharding] Persist shard information

config/config.yaml, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/collection/src/collection_manager/fixtures.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/operations/config_diff.rs, lib/collection/src/optimizers_builder.rs, lib/collection/src/shard/local_shard.rs, lib/collection/src/tests/mod.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/segment.rs, lib/segment/src/types.rs, lib/segment/tests/filtrable_hnsw_test.rs, tests/basic_api_test.sh
related Issue: https://github.com/qdrant/qdrant/issues/635
Changes:
- `default_segment_number` can now be auto-selected sing amount of CPUs
- `memmap_threshold` is now set to `max_segment_size` by default, to prevent usage of mmap by default
- thresholds are now configured in KiloBytes instead of number of vectors, it should better reflect the performance of large and small vectors
=> Smarter defaults

Cargo.lock, docs/redoc/master/openapi.json, lib/storage/Cargo.toml, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, src/consensus.rs
Fixes TODOs from https://github.com/qdrant/qdrant/pull/631
Looks like this now:
```json
{
"result": {
"status": "enabled",
"peer_id": 11532566549086892000,
"peers": {
"9834046559507417430": {
"uri": "http://172.18.0.3:6335/"
},
"11532566549086892528": {
"uri": "http://qdrant_node_1:6335/"
}
},
"raft_info": {
"term": 1,
"commit": 4,
"pending_operations": 1,
"leader": 11532566549086892000,
"role": "Leader"
}
},
"status": "ok",
"time": 5.731e-06
}
```
=> Add leader_id and role to cluster API

tests/consensus_tests/test_collection_created_after.py, tests/consensus_tests/test_collection_created_before.py, tests/consensus_tests/test_collection_sharding.py, tests/consensus_tests/utils.py
This PR tackles https://github.com/qdrant/qdrant/issues/673 by removing as many `sleep` instructions as possible.
Those sleep instructions were necessary to give time to the node to startup & join the cluster.
With this PR the cluster state is validated by repeatedly polling the cluster and collection API with an upper bound timeout.
I have created a bunch of utility functions for testing the eventually consistent interactions which I have moved into `utils.py`.
For example we can check that:
- the `/cluster` leader field is not null
- that all nodes see the same cluster size
A follow up work will be to have additional nodes join the cluster concurrently to execute the tests even faster by fixing #676.
=> Consensus tests use cluster API instead of sleep

src/consensus.rs
Tiny PR to add more context to the possible errors happening during consensus initialization. (related to https://github.com/qdrant/qdrant/issues/676)
This helped me chase the source of a timeout.
```
thread 'main' panicked at 'Can't initialize consensus: Failed to initialize Consensus for new Raft state
Caused by:
0: Failed to add peer to known participant
1: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }
2: transport error
3: Timeout expired', src/main.rs:103:10
```
=> add more error context for consenus init

src/settings.rs, src/tonic/api/raft_api.rs
This PR fixes the timeout which can appear during the bootstrapping phase of a node.
```
thread 'main' panicked at 'Can't initialize consensus: Failed to initialize Consensus for new Raft state
Caused by:
0: Failed to add peer to known
1: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }
2: transport error
3: Timeout expired', src/main.rs:103:10
```
During the bootstrap phase, the node performs a gRPC call to add itself as a known peer.
The node receiving this command needs to perform a synchronous meta operation on the consensus layer which can take up to 10 sec (`DEFAULT_META_OP_WAIT`).
However the gRPC client uses a timeout that is lower than 10 seconds.
This PR contains the following changes:
- increases the gRPC bootstrap timeout so …
=> fix: gRPC bootstrap timeout needs to be higher than DEFAULT_META_OP_WAIT

lib/storage/src/content_manager/consensus_state.rs
The `len()` method would previously give wrong answer at corner cases.
=> Fix unapplied entries len

src/consensus.rs, tests/consensus_tests/test_collection_created_after.py, tests/consensus_tests/test_collection_created_before.py, tests/consensus_tests/test_collection_sharding.py, tests/consensus_tests/utils.py
This PR harden the consensus tests and adds new debug logs to help the operators (context: https://github.com/qdrant/qdrant/issues/676)
The tests now check that all the nodes report the same leader and cluster size.
=> Harden consensus test and debugging

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment.rs, lib/storage/src/content_manager/toc.rs
Issue: https://github.com/qdrant/qdrant/issues/701
Overall problem is related to the unconventional behavior of the CIFS (samba) remote file system.
Being developed for windows, it has inherited some of the vices of the file systems of this family.
In particular, the file deletion procedure deviates from unix standards.
Instead of deleting the "used" file, CIFT considers it deleted, but does not release the so-called hard link.
As a result, you can observe funny visual effects:
This disregard for the standard was not initially considered in Qdrant.
Therefore, files could be deleted while still in use, which is perfectly normal in linux.
This PR changes that behavior. Objects must now be consumed before deleting files, which frees up file descriptors and makes deletion compatible with the …
=> Cifs dir delete

src/main.rs
Tiny PR to format the timestamp with milliseconds in the logs.
This helps to disambiguate certain operations in the logs during debugs. 
- Before
```
[2022-06-16T10:19:47Z DEBUG hyper::client::connect::http] connecting to 127.0.0.1:53377
[2022-06-16T10:19:47Z DEBUG hyper::client::connect::http] connected to 127.0.0.1:53377
[2022-06-16T10:19:47Z DEBUG hyper::client::connect::http] connecting to 127.0.0.1:53377
[2022-06-16T10:19:47Z DEBUG hyper::client::connect::http] connected to 127.0.0.1:53377
```
- After
```
[2022-06-16T10:21:15.723Z DEBUG hyper::client::connect::http] connecting to 127.0.0.1:43983
[2022-06-16T10:21:15.724Z DEBUG hyper::client::connect::http] connected to 127.0.0.1:43983
[2022-06-16T10:21:15.725Z DEBUG hyper::client::connect::http] connecting to 127.0.0.1:43983 …
```
=> Format timestamps with millis precision in log

.github/workflows/integration-tests.yml, lib/storage/src/content_manager/consensus_state.rs
This PR fixes a deadlock in the cluster status. (found in the context of https://github.com/qdrant/qdrant/issues/709)
Here is the deadlock detection report.
```
[2022-06-17T15:53:02.855Z ERROR qdrant] 1 deadlocks detected
Deadlock #0
Thread Id 140401950271040
0:     0x55e2e05bea4a - backtrace::backtrace::libunwind::trace::h48399522ee083924
at /home/agourlay/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/libunwind.rs:93:5
backtrace::backtrace::trace_unsynchronized::h4499f1decc2119c3
at /home/agourlay/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:66:5
1:     0x55e2e05be9c2 - backtrace::backtrace::trace::h40e7832466c0123d
at /home/agourlay/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod. …
```
=> Fix deadlock in cluster status.

lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/lib.rs, src/actix/api/cluster_api.rs
The `cluster_status` does not perform any async. operations.
=> Remove unecessary async fn on cluster status

lib/storage/src/content_manager/consensus_state.rs, src/consensus.rs, tests/consensus_tests/create_collection_and_check.py
Fixes https://github.com/qdrant/qdrant/issues/711
Raft library returns all committed entries after restart - which was not well documented or expected :smile:
=> Fix entry reapplication on restart

lib/api/build.rs, tests/consensus_tests/test_collection_created_after.py, tests/consensus_tests/test_collection_created_before.py, tests/consensus_tests/test_collection_sharding.py, tests/consensus_tests/utils.py
This PR removes the last sleep in the consensus test.
The insight is that having a non null `leader` field does not mean that the peer joined the cluster successfully.
The peer fully joined when its list of `peers` has the right size.
=> Remove last sleep consensus test

Cargo.lock, Cargo.toml, lib/storage/Cargo.toml, lib/storage/src/content_manager/consensus_state.rs
This PR uses the commit https://github.com/tikv/raft-rs/commit/52d84aac8734369d81c2d77413ea3ab8e58e0af9 as dependency version for raft-rs.
Some arguments for this:
- raft-rs has not published a release in more than a year
- there are some [unreleased bug fixes](https://github.com/tikv/raft-rs/compare/v0.6.0...master)
- it updated to `prost` 0.9.0 which would enable us to close https://github.com/qdrant/qdrant/issues/521
=> Use latest raft-rs

src/consensus.rs
This PR optimizes `handle_committed_entries` so that it acquires the persistent read lock only once.
It also ensure that no writer interleaves with those two calls.
=> handle_committed_entries acquires read lock only

lib/storage/src/content_manager/consensus_state.rs, src/consensus.rs, src/main.rs, src/tonic/api/raft_api.rs, tests/consensus_tests/test_collection_created_after.py, tests/consensus_tests/test_collection_created_before.py, tests/consensus_tests/test_collection_sharding.py
Partially fixes https://github.com/qdrant/qdrant/issues/676
As we discovered there are 2 possible faulty scenarios when peers join concurrently:
1. Node fails to join the network at all
2. Node joins and is lagging behind in number of commits
This change seems to fix the 1st issue.
1. entry retrieval fix at max_size = `Some(0)` should still return 1 entry
2. retain last applied snapshot info to use it to retrive `term`
This change fixes the 2nd issue
The fix is - adding the node as a `Learner` instead of `Voter`. This way the node will only sync and will not try to become a leader or vote for the leader. So there seem to be no conflicts in the nodes perception of the network during "Joint Consensus". 
Though we could not find the exact terminology of learner in the [Raft …
=> Add new peers as learners

lib/storage/src/content_manager/consensus_state.rs, src/consensus.rs
This PR initialize properly the `applied` field for the Raft config.
The raft library will not return entries to the application smaller or equal to `applied` on restart.
This enables us to clean the filtering logic in the handling of committed entries introduced in https://github.com/qdrant/qdrant/pull/715
=> Init. Raft config with last applied entry

docs/redoc/master/openapi.json, lib/api/src/grpc/proto/raft_service.proto, lib/api/src/grpc/qdrant.rs, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/types.rs, src/consensus.rs, src/tonic/api/raft_api.rs
- leader promotes learners when possible
- Fixes ERROR voters not found
Error `voters not found` relates to the fact that first peer is started with different conf_state that contains itself as a voter. Other peers are started with empty conf_state and did not get the appropriate conf_state through sync, because it was not represented in any entry.
We manually fetch the first_peer and inject it into the conf_state on bootstrap
Relates to #733
=> Promote learner

lib/storage/src/content_manager/consensus_state.rs
This PR introduces a hot-fix to ensure that the current raft state is compatible with previous versions (0.8.1).
We want to avoid the following error 
```
Error: Service internal error: cbor (de)serialization error: missing field `latest_snapshot_meta
```
A follow up PR will also make sure that the Raft state is not materialized in a single node setup.
=> Hot fix to ensure bin compat. of RaftState

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/segment.rs
This PR implement a basic snapshot capability at the segment level (#744)
A new function archived the whole segment directory as a tar file.
It is supposed to be called while holding a read lock on the segment.
=> introduce segment-level snapshots

lib/collection/src/operations/conversions.rs, lib/collection/src/shard/conversions.rs
This PR add support for `PointsBatch` to the internal upsert points API.
Missing feature in https://github.com/qdrant/qdrant/pull/505
=> internal point upserts support PointsBatch

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/segment/Cargo.toml, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment.rs
Context: issue https://github.com/qdrant/qdrant/issues/744 follow up on https://github.com/qdrant/qdrant/pull/751
This PR introduces `snapshot_all` at the `SegmentHolder` level.
I had to move the implementation of `take_snapshot` to `SegmentEntry`.
I have one concern regarding the lack of synchronization while we iterate over the segments, the operation is not viewing all the segments at the same time. Not sure if it could be an issue in practice.
=> SegmentHolder snapshot all segments

lib/segment/src/vector_storage/simple_vector_storage.rs, src/main.rs
As always, new Rust release can break our pipeline as it uses the latest version.
This PR fixes the new issue reported by Clippy.
=> Fix clippy 1.62

Cargo.lock, lib/storage/Cargo.toml, lib/storage/src/content_manager/alias_mapping.rs, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, src/consensus.rs, src/main.rs
Closes #730 
`Storage::initial_state` and `Storage::snapshot` are not tested as they are not good targets for property testing and are rather straightforward.
=> Property tests for Storage trait impl

Cargo.lock, docs/grpc/docs.md, lib/api/Cargo.toml, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/qdrant.proto, lib/api/src/grpc/proto/snapshots_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/snapshot_ops.rs, src/tonic/api/mod.rs, src/tonic/api/snapshots_api.rs, src/tonic/mod.rs
This PR introduces a gRPC API for the snapshot feature.
I have not been able to implement a `Get` API to stream the snapshot file to the users because of an impedance mismatch with the protocol buffer goals.
According to the [official doc](https://developers.google.com/protocol-buffers/docs/techniques#large-data) it is not made to stream large data set.
=> gRPC API for snapshot

lib/storage/src/content_manager/consensus_state.rs, src/consensus.rs, src/main.rs
Fixes #768 
Tested locally with one peer by providing it a bootstrap uri that was incorrect. Checked that after peer restart it tried bootstrapping again, even though it had a local raft state.
=> Retry bootstrap if `term` is `0`

lib/collection/src/shard/local_shard.rs
Issue: https://github.com/qdrant/qdrant/issues/774
Benchmarks:
loading of 200k vectors collection of 4 segments (50k + 50k + 100k + 0): 
- before change: 5s
- after change: 3s 
=> parallel segments loading

lib/collection/src/shard/conversions.rs, lib/collection/src/shard/remote_shard.rs
This PR is a bug fix to propagate properly the user's `wait` flag to the remote shard operations.
Currently we are always waiting for remote shards which is not correct.
=> Fix propagation of 'wait' flag to remote shard operations

src/settings.rs
This PR increases the default timeout used for the itnernal gRPC calls from 1 second to 1 minute.
```rust
#[serde(default = "default_timeout_ms")]
pub grpc_timeout_ms: u64,
```
This is the only call site for this function.
The current value is too aggressive and can prevent clients from using the `wait` flag properly.
Under high throughput, it is normal for a request using the `wait` flag to take more than 1 second.
=> Increase gRPC timeout to 1 minute

tests/consensus_tests/utils.py
This PR gives a unique `gRPC` port to every qdrant process in the consensus test.
It is necessary because since this [change](https://github.com/qdrant/qdrant/commit/8ac3eef4c7e1519d78c0036b779b192cab482c94#diff-38df760413887d0cc4ee5707919e6390456a863d326f6080644cc3d9c72e4bbaR96) enabled the gRPC endpoint by defaultt.
We get noisy errors during consensus tests in logs because all process try to bind on the same port.
```
[2022-07-11T16:00:26.882Z INFO  qdrant::tonic] Qdrant gRPC listening on 6334
thread 'grpc' panicked at 'called `Result::unwrap()` on an `Err` value: tonic::transport::Error(Transport, hyper::Error(Listen, Os { code: 98, kind: AddrInUse, message: "Address already in use" }))', src/tonic/mod.rs:68:10
stack backtrace:
```
=> Fix gRPC port for consensus tests

lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs
This PR fixes a nasty bug happening when remote shards use the wait flag to `false`.
It is due to an incomplete mapping of the gRPC `UpdateStatus` to the operations `UpdateStatus`.
Here is the mapping code.
```rust
impl From<UpdateResult> for api::grpc::qdrant::UpdateResult {
fn from(value: UpdateResult) -> Self {
Self {
operation_id: value.operation_id,
status: value.status as i32,
}
}
}
impl TryFrom<api::grpc::qdrant::UpdateResult> for UpdateResult {
type Error = Status;
fn try_from(value: api::grpc::qdrant::UpdateResult) -> Result<Self, Self::Error> {
Ok(Self {
operation_id: value.operation_id,
status: match value.status {
1 => UpdateStatus::Acknowledged,
2 => UpdateStatus::Completed,
_ => return Err(Status::invalid_argument("Malformed UpdateStatus type")),
},
})
}
}
```
The first …
=> Fix conversion for UpdateStatus from the gRPC layer

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/hash_ring.rs, lib/collection/src/lib.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/tests/mod.rs, lib/segment/src/common/version.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, tests/consensus_tests/utils.py
Relates to #815 
It was possible to use either `dyn Trait` or `enum` for the custom hash ring there. I decided to go with enum as implementation with it is much faster and the calls to shard selection are very frequent (1 call for 1 point for insertion). Also all variants are known to us and we do not plan to expose it as a library interface.
Should we expose shard scale as a configuration param?
=> Fair hash ring

lib/storage/src/content_manager/consensus_state.rs
Relates to #817
Tested locally with storage created at version `0.8.0`.
=> Default value for apply_progress_queue

docs/redoc/master/openapi.json, lib/collection/src/collection.rs, lib/collection/src/operations/types.rs, lib/storage/src/content_manager/toc.rs, openapi/openapi-collections.ytt.yaml, src/actix/api/collections_api.rs, src/common/collections.rs, src/schema_generator.rs, tests/consensus_tests/test_collection_sharding.py, tests/consensus_tests/utils.py
This PR adds a new REST API to get the collection cluster info. (#624)
With this API an operator can get extra information about the shard topology of a given collection.
It is tested via the sharding consensus test, here is an example of output.
edit: new format
```json
{
"shard_count": 6,
"local_shards": [
{
"shard_id": 2
}
],
"remote_shards": [
{
"shard_id": 0,
"peer_id": 5206661873001331473
},
{
"shard_id": 1,
"peer_id": 9153846410978676289
},
{
"shard_id": 3,
"peer_id": 11473594217186723880
},
{
"shard_id": 4,
"peer_id": 17502153356522390965
},
{
"shard_id": 5,
"peer_id": 5206661873001331473
}
]
}
```
=> [sharding] Collection cluster info API

lib/collection/src/collection.rs, lib/collection/src/collection_state.rs, lib/collection/src/shard/collection_shard_distribution.rs, lib/collection/src/shard/local_shard.rs, lib/collection/src/shard/mod.rs, lib/collection/src/shard/shard_config.rs, lib/collection/src/shard/shard_holder.rs, lib/collection/src/shard/shard_versioning.rs, lib/collection/tests/collection_test.rs
This PR is part a follow up to https://github.com/qdrant/qdrant/pull/829 (https://github.com/qdrant/qdrant/issues/789)
It adds a mechanism to promote a temporary shard as a local shard at the end of the shard transfer which is triggered through consensus via `finish_transfer`.
I tried my best to make the span of the write locks as short as possible to not block the reads but it is still significant.
There is a unit test for creating and promoting a temporary shard.
=> [sharding] Promote temporary shard at the end of transfer

lib/api/src/grpc/transport_channel_pool.rs, src/consensus.rs, src/main.rs, src/settings.rs
A smarter way to kill grpc connetion, if the service become unavailable.
Problem: 
If node gets restarted, it receives a new IP address. So the channel becomes invalid. But for the request it is un-distinguishable from just a long execution.
Solution:
If request takes too long time, we spawn another healthcheck request which should be executed fast. If it does not executed in smaller timeout - we assume that the channel is dead and we need to re-create it
=> Clever channel timeout

lib/collection/Cargo.toml, lib/collection/src/collection.rs, lib/collection/src/lib.rs, lib/collection/src/operations/types.rs, lib/collection/src/save_on_disk.rs, lib/collection/src/shard/mod.rs, lib/collection/src/shard/shard_holder.rs
Relates to #827 
Also adds a general abstraction for saving on disk.
1. Add shard_transfer state to collection snapshot
2. Use `SaveOnDisk` in other places that require this functionality
=> Save shard transfers state on disk

src/actix/api/cluster_api.rs, src/actix/api/collections_api.rs, src/actix/api/count_api.rs, src/actix/api/recommend_api.rs, src/actix/api/retrieve_api.rs, src/actix/api/search_api.rs, src/actix/api/snapshot_api.rs, src/actix/api/telemetry_api.rs, src/actix/api/update_api.rs, src/actix/mod.rs
This PR removes an unnecessary layer of indirection in our usage of Actix's `web::Data`.
The `web::Data` is a wrapper for an `Arc<T>`
```rust
pub struct Data<T: ?Sized>(Arc<T>);
```
This is what `web::Data::new` does under the hood
```rust
pub fn new(state: T) -> Data<T> {
Data(Arc::new(state))
}
```
This is why we get the following definitions in our services
```rust
toc: web::Data<Arc<TableOfContent>>,
```
This means we have two layers of stacked `Arc`.
This PR simplify this by using a single layer of `Arc` via the `web::Data::from` method which accepts an existing `Arc`.
I do not expect a visible performance improvement but that is definitely cleaner IMHO.
=> Remove unecessary Arc for web::Data

docs/redoc/master/openapi.json, lib/collection/src/collection_manager/fixtures.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/config.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/shard/local_shard.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/common/mod.rs, lib/segment/src/vector_storage/chunked_vectors.rs, lib/storage/src/content_manager/toc.rs
This PR prevents vector dim. of zero (https://github.com/qdrant/qdrant/issues/806).
I tried to hit a sweet spot between type safety and runtime validation.
The `CollectionParams` enforces a `NonZeroU64` for the vector size which should not be a breaking change in practice.
=> Prevent Vector size zero

docs/redoc/master/openapi.json, lib/storage/src/content_manager/consensus/persistent.rs, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, openapi/openapi-cluster.ytt.yaml, src/actix/api/cluster_api.rs
Relates to #874 
Do not shutdown peer if it receives its own removal from consensus. Peer should be later shutdown by script/admin. Otherwise it could interfere with Kubernetes cluster management (it can try to restart the peer).
=> Peer removal API

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/shard/forward_proxy_shard.rs, lib/collection/src/shard/local_shard_operations.rs, lib/collection/src/shard/remote_shard.rs, lib/collection/src/shard/transfer/shard_transfer.rs
This PR enables a smooth shard promotion at the end of the shard transfer.
Currently the shard is promoted right after the last points are sent over.
This cause a significant slowdown of the search requests because the indexes are not yet ready.
In this PR, we make sure the new shard reached a certain level in terms of indexing before triggering the promotion.
To do so we had to expose the number of indexed vector in the collection info.
=> Indexed vectors in collection info

lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, src/actix/api/cluster_api.rs, src/consensus.rs, tests/consensus_tests/downscale_cluster.py, tests/consensus_tests/test_restart.sh
Changes from the last attempt:
- Create a copy of id_to_address on the start of tick loop, so it should preserve addresses for at least tick duration
- on removed peer:
- Remove all other peer
- Stop consensus
With this changes removed leader stops sending pings and re-election happens properly
=> a third attempt to implement peer removal + integration test

lib/collection/src/collection.rs, lib/collection/src/collection_state.rs, lib/storage/src/content_manager/toc.rs
Some of the logic related to transfers was triggered only on entry application and did not account for the cases where entries were compacted into a snapshot. This PR addresses this issue.
=> Raft snapshot logic for handling transfers

docs/redoc/master/openapi.json, lib/collection/src/collection.rs, lib/collection/src/operations/cluster_ops.rs, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/dispatcher.rs, src/actix/api/cluster_api.rs, src/common/collections.rs, src/main.rs, src/tonic/api/raft_api.rs
- Wait for consensus leader to be elected before sending transfer cancellations
- Expose API for manual aborting transfers
=> Fix transfer abort on restart

lib/collection/src/shard/local_shard.rs
This PR improves the styling of the progress bar displayed while recovering the content of the WAL.
I looked into this topic because I found it weird that the progress bar did not have a message although we are using:
```rust
bar.set_message("Recovering collection");
```
The doc. says
> For the message to be visible, the {msg} placeholder must be present in the template
So I ended up:
- fixing the message display
- adding the collection name to the message
- adding the elapsed time and ETA
The new look in action
=> Improve WAL recovery progress bar

lib/api/src/grpc/proto/raft_service.proto, lib/api/src/grpc/qdrant.rs, lib/storage/src/content_manager/consensus_state.rs, src/consensus.rs, src/tonic/api/raft_api.rs
Adds a peer similar to the removal for consistency. PR tries to stay compatible with the previous version so that migration can happen without downtime.
Closes https://github.com/qdrant/qdrant/issues/915
=> AddPeer in one consensus operation

lib/collection/src/shard/local_shard.rs
This PR prevents the panic when `config.optimizer_config.max_optimization_threads` is 0
```
thread 'main' panicked at 'Max blocking threads cannot be set to 0', /qdrant/lib/collection/src/shard/local_shard.rs:73:14
```
Tested manually.
=> Do not panic if config.optimizer_config.max_optimization_threads is 0

src/actix/mod.rs
=> Use settings.service.max_request_size_mb

lib/storage/src/content_manager/toc.rs
Intellij was bugging me again about this unnecessary lifetime.
I gave it a try, performed a full clean and it seems to work now.
Possibly fixed by a recent Rust update.
=> Remove unnecessary lifetime in toc

lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/config.rs, lib/collection/src/operations/types.rs, lib/collection/src/shard/shard_config.rs, lib/collection/src/update_handler.rs, lib/collection/src/wal.rs, lib/segment/src/index/hnsw_index/config.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/types.rs
We usually have issues in our build pipeline when new versions of Rust are released.
This is due to the pipeline always pulling the latest version which can be problematic when new Clippy lints are introduced.
In this PR, I addressed proactively a bunch of new lints about to be enabled now or in the near future.
=> Clippy next

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/storage/src/content_manager/toc.rs, openapi/openapi-main.ytt.yaml, src/actix/api/recommend_api.rs, src/actix/mod.rs, src/schema_generator.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, tests/consensus_tests/test_collection_shard_transfer.py, tests/consensus_tests/test_collection_sharding.py, tests/consensus_tests/test_many_collections.py, tests/consensus_tests/test_points_recommendation.py
This PR adds a batch recommendation API #952 
- built on top of the new batched search API
- perform points retrieval in a batched fashion as well
- REST API tested by comparing the result of the batched version with the regular version
- hardened some tests to actually compare the expected payload across peers in distributed mode
- fixed a sneaky issue regarding double application of the `offset`
Once there is a consensus on the implementation, I will refactor the non-batched version so that it uses the batch version with a single request to avoid code duplication.
=> Batch recommendation API

lib/collection/src/operations/config_diff.rs, lib/collection/src/optimizers_builder.rs, lib/segment/src/types.rs, src/actix/actix_telemetry.rs
Cleaning up warnings when running `cargo doc`
```
warning: this URL is not a hyperlink
--> lib/collection/src/optimizers_builder.rs:53:32
|
53 |     /// Default value based on https://github.com/google-research/google-research/blob/master/scann/docs/algorithms.md
|                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/google-research/google-research/blob/master/scann/docs/algorithms.md>`
|
= note: bare URLs are not automatically turned into clickable links
```
=> properly format doc links for cargo doc

docs/redoc/master/openapi.json, lib/collection/src/operations/snapshot_ops.rs
Some filesystems do not support retrieving file creation time:
```{'result': None, 'status': {'error': 'Service internal error: File IO error: creation time is not available for the filesystem'}, 'time': 30.254521051}```
But it should not be a reason to fail on snapshot creation.
This PR enables changes creation time field to optional
=> do not fail if cannot get file creation time

docs/grpc/docs.md, lib/api/src/grpc/proto/points.proto
Small PR which changes :camel:  field names into :snake:, to be consistent with all other fields in the proto.
Also re-generates proto docs 
Backward compatibility is preserved, as field names are not used on binary level
=> rename grpc fields + re-generate docs

lib/collection/src/collection.rs, lib/collection/src/shard/mod.rs, lib/collection/src/shard/replica_set.rs, lib/collection/src/shard/shard_holder.rs
Introduces a general structure that handles synchronizing operations across shard replicas. Assuming that one peer cannot contain more than one replica of the same shard.
`todo()` are safe as the ReplicaSet type of shard is never created
=> Replica set

src/actix/mod.rs
Init telemetry thought `web::Data::from` instead of `web::Data::new`. Maybe telemetry branch was merged a bit of time after the migration to `web::Data::from` (this migration happened at the same time when telemetry was in develop)
=> Fix telemetry web init

lib/collection/src/shard/local_shard.rs, lib/collection/src/shard/replica_set.rs
Based on previous experience with shard transfers, it seems we should drop the whole struct first
=> Drop shard before deleting its folder in `ReplicaSet`

.cargo/config.toml, .github/workflows/docker-image.yml, Dockerfile, tools/target_arch.sh
- Based on https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
- If no emulator installed, it defaults to amd64 platform
- builds for `master` tag are preserved as-is on dockerhub, no multi-platform support for them for now
=> Multiplatform build fix 2

lib/collection/src/collection.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/collection_manager/tests/mod.rs, lib/collection/src/shard/local_shard.rs, lib/collection/src/shard/local_shard_operations.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/fixtures/mod.rs, lib/segment/src/fixtures/segment_fixtures.rs, lib/segment/src/segment.rs, lib/segment/src/spaces/tools.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/tests/scroll_filtering_test.rs
- old scroll implementation did a full scan, if the filter had low cardinality, which resulted in very high latency of the scroll query
- proposed implementation works similar to query planner, it estimates the cardinality of the filter first and then decides if it makes sense to use index first or filter the ids.
- This implementation resolves the case, where user wants to select some records from DB using the secondary index.
Our of scope:
current boundary threshold is hard-coded and naive. It would require additional telemetry data to decide how to adjust it.
Issue detected in demo by @joein
=> Faster filtered scroll

lib/collection/src/collection.rs, lib/collection/src/shard/replica_set.rs, lib/collection/src/shard/shard_holder.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/common/mod.rs, lib/storage/src/content_manager/toc.rs
This PR adds an implementation of `ShardOperation` for `ReplicaSet`.
Following the proposal of https://github.com/qdrant/qdrant/issues/993, the `ReplicaSet` now manages several remote shards and becomes responsible for the shard query coordination.
There is an optimization scheme for the read-only operation in order to reduce the latency:
1. prefer a local shard
2. try a subset of the remote shards concurrently (the ratio could be fully configurable)
3. try remaining remote shards 
Regarding the update operations, the processing must be acknowledged by all shards to be well formed.
Failing peers are reported as `inactive` in the `replica_state`.
I was not able to have a nice `update` path because of various struggles with `async` blocks and `Iterators`.
In short I wanted to somehow …
=> ReplicaSet ShardOperations

lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/config.rs, lib/collection/src/operations/conversions.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/toc.rs, lib/storage/tests/alias_tests.rs, src/consensus.rs
Several `todo` fixes that propagate API for replication from internal to external. As replication is planned to be enabled for the next release.
=> Replication related API changes

lib/collection/benches/batch_search_bench.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs
A new Rust version was released today, as usual small fixes are required for our CI using `latest`.
This time no formatting, just a single Clippy entry.
```bash
error: this expression can be written more simply using `.retain()`
--> lib/collection/src/collection_manager/holders/proxy_segment.rs:444:13
|
444 | /             read_points = read_points
445 | |                 .into_iter()
446 | |                 .filter(|idx| !deleted_points.contains(idx))
447 | |                 .collect();
| |__________________________^ help: consider calling `.retain()` instead: `read_points.retain(|idx| !deleted_points.contains(idx))`
|
= note: `-D clippy::manual-retain` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_retain …
```
=> Fix Clippy following Rust update

lib/collection/src/collection.rs, lib/collection/src/config.rs, lib/storage/src/content_manager/toc.rs
Fixes issue, where collection become inconsistent if some of the shards creation failed.
New logic:
- create collection shards first - save collection config as the last step
- If collection does not have config - it is considered malformed and skipped with warning
=> fix collection loading

.github/dependabot.yml
Dependabot should target our newly created `dev` branch to not introduce unnecessary into `master`
It currently still target master for instance https://github.com/qdrant/qdrant/pull/1063
This PR changes the configuration in the `master` branch as well to make it effective.
=> Dependatbot targets dev branch

lib/collection/src/collection.rs, lib/segment/src/spaces/tools.rs
Follow up on https://github.com/qdrant/qdrant/pull/1082
Enabling users to fetch the entire data set by using `limit:0` is dangerous.
The current behavior is not documented and looks like a bug.
This PR proposes to return an empty result instead which makes the semantic clearer.
The check is done first at a high level with `collection.rs` and then the sorting helpers have been updated to reflect this new behavior.
Applies to:
- search
- search_batch
- recommend
- recommend_batch
A follow up work would be to cap the maximum `limit` to protect the system.
=> limit set to zero returns an empty result

lib/storage/src/content_manager/consensus/consensus_wal.rs, lib/storage/src/content_manager/consensus/persistent.rs, lib/storage/src/content_manager/consensus_state.rs, tests/consensus_tests/docker-compose.yaml
- Raft paper proposes, that in case of leader conflict, entries with higher term should override submitted, but not yet committed entries in the consensus WAL.
- Previous implementation of consensus WAL didn't consider this case and only performed append to WAL, which caused inconsistency and undefined behavior of the raft-rs.
- This PR introduces index checks in the consensus WAL, allowing it to override existing entries based on raft index of the newly received entries.
- New code also assumes, the WAL index is not identical, but monotonous and does not contain any skips comparing to Raft index. In other words, WAL Index have a constant offset comparing to Raft index
Additional context:
reproduction of original bug involves multiple parallel consensus-related requests in combination …
=> ensure consequent entries in consensus wal

lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs
There is a possible scenario, where the `id_tracker` operation fails - the vectors storage stays updated. Even after proper recovery, the inserted vectors are no longer associated with external IDs. 
This PR allows to ignore abandoned ids instead of panicking.
Additional changes:
- Adds logging for the errored state of the segment
- Enables consistency checking in debug build
- Improves payload moving in multiple vector case
=> ignore points with missing expernal ids instead of panic

lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
- replace `update_vector` with `insert_vector` which assumes in-place change semantics
- Use `insert_vector` with max id to ensure synced named vector storage offsets
=> Force sync vector storage offset

lib/segment/src/index/field_index/geo_hash.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/types.rs, tests/basic_api_test.sh
This PR brings back validation for geo coordinates before insertion into a payload index.
Malformed geo coordinates (out of the range `lat` in [-90;90] and `lon` in [-180;180]) will be ignored by index.
=> validate geo coordinate before adding it to the payload index

config/development.yaml, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/segment/src/types.rs, lib/storage/src/content_manager/consensus/consensus_wal.rs
Temporary segments, created during the optimization, now should have same payload indexes as the optimized segments.
Temporary segments are then promoted to regular ones, should have same indexing pattern
=> propagate payload index to temporary segment during optimization

Cargo.toml
Currently the build contains the following warning
```
warning: /home/agourlay/Workspace/qdrant/Cargo.toml: unused manifest key: package.doctest
```
Looking at the documentation, it seems that the key `doctest` is only valid within a `[lib]` section.
https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-doctest-field
Also we have no doc tests to run.
```
agourlay@agourlay-thinkpad:~/Workspace/qdrant$ cargo test --all --doc
Finished test [unoptimized + debuginfo] target(s) in 0.19s
Doc-tests api
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests collection
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests segment
running 0 tests
test result: …
```
=> remove malformed doctest configuration

lib/storage/src/content_manager/toc.rs, lib/storage/src/dispatcher.rs, openapi/tests/openapi_integration/test_db_lock.py
Move write operation lock on the request level. Allow to apply write operations submitted by consensus or other peers even if lock exists - it should ensure cluster integrity and prevent chain reaction in case of lover resources.
Write operation lock should be applied on all nodes of the cluster and only in case if it is not possible to move shards for more even load distribution
=> Write lock for user requests

lib/collection/src/collection.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/index/field_index/numeric_index.rs
Now upsert will set exact payload as provided in the query and as it was intended.
(before fix it would override only specified fields)
Fixes replica sync transfer
=> Full reassign payload on upsert

lib/collection/src/shards/replica_set.rs, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, src/actix/api/cluster_api.rs
- Move remove peer validation into consensus
- Fix error handling in the read operations of replica set
- Forbid deactivating of shards if all replicas failed
=> Consensus fault tollerance improvements

benches/service/collection_stress.js, benches/service/run.sh, benches/service/stress.sh
This PR improves our basic load testing [k6](https://k6.io/docs/) script to make it more useful.
It now runs two scenarios sequentially:
- upsert random points over 1 minute while ramping up the number of virtual users to 30
- search for points using an indexed payload using the same ramping scheme
The parameters are easy to tweak for different experiments and more scenarios can be added as well.
Separating the ingestion from the search enabled me to do some manual testing on a distributed setup locally.
Hopefully more people find it useful.
=> Improve load testing k6 script

src/actix/mod.rs
=> exclude / from actix logger middleware

docs/redoc/master/openapi.json, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/types.rs, src/consensus.rs
1. Record message send failures instead of logging
2. Stop consensus on service error instead of trying to reapply
=> Record message send failures and stop consensus on service error

lib/segment/src/fixtures/payload_context_fixture.rs, lib/segment/src/id_tracker/id_tracker_base.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs
After RAM usage investigation we got that simple id tracker requires a lot of RAM. For test storage with 3M points tracker uses `473MB`. This PR implements ram usage optimization for the id tracker. On test storage id tracker uses only `208MB`.
The method of measurement is simple. I used a separate binary that only loads the id tracker and does nothing. Ram is measured by `top`.
The main idea of reducing is avoiding complicated key for `BTreeMap` and reducing the lenght of `HashMap` using `Vec` instead.
=> Use less ram for id tracker

lib/collection/src/collection.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/dispatcher.rs
Since we do not automatically re-balance the collection across peers on other events, it might make sense to do same in case of replication factor change. For sake of consistency
=> remove suggesting changes in replications on replication factor change

src/actix/mod.rs
This PR enables the HTTP compression middleware from actix-web.
> Compress will read the Accept-Encoding header to negotiate which compression codec to use. Payloads are not compressed if the header is not sent.
By [default](https://github.com/actix/actix-web/blob/master/actix-web/Cargo.toml#L31) it supports gzip, brotli and zstd.
We can then decide if we want to request by default compressed payload in our drivers.
=> enable HTTP compression middleware

tests/consensus_tests/assertions.py, tests/consensus_tests/check_points.py, tests/consensus_tests/create_collection_and_check.py, tests/consensus_tests/downscale_cluster.py, tests/consensus_tests/insert_points.py, tests/consensus_tests/test_collection_created_after.py, tests/consensus_tests/test_collection_created_before.py, tests/consensus_tests/test_collection_shard_transfer.py, tests/consensus_tests/test_collection_shard_update.py, tests/consensus_tests/test_collection_sharding.py, tests/consensus_tests/test_many_collections.py, tests/consensus_tests/test_points_search.py, tests/consensus_tests/test_recover_dead_node.py, tests/consensus_tests/test_remove_node.py, tests/consensus_tests/utils.py
This PR modifies the consensus test to systematically use `assert_http_ok` for better error reporting.
=> Use systematically assert_http_ok for better error reporting

lib/collection/src/operations/config_diff.rs, lib/collection/src/shards/replica_set.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/consensus_state.rs, lib/storage/src/dispatcher.rs, src/common/helpers.rs, src/consensus.rs, src/main.rs, src/migrations/mod.rs, src/migrations/single_to_cluster.rs, src/snapshots.rs
In cases of:
- collection is restored from snapshot
- instance with existing collections upgraded from single-node to cluster
we need to explicitly tell to the consensus, that those collections exists.
So it could replay related changes on all nodes in the cluster.
`handle_existing_collections` sends suggestions to create collection with proposed shard distribution equal to the local peer and marks newly registered shards as `Active`.
Test scenario:
- Create collection with single node deployment
- Kill and re-run qdrant in cluster deployment
- Attach another peer to cluster
- Replicate collection shard to the new node
Warn:
Log messages like:
```
[2022-11-03T22:12:09.272Z WARN  storage::content_manager::consensus_state] Failed to apply collection meta operation entry with user error: …
```
=> handle collections transition from single-node to cluster

lib/collection/src/save_on_disk.rs, lib/collection/src/shards/replica_set.rs
Ensures read-after-write consistency in case of replica failure and if requests are going to the same peer.
=> wait for state deactivation on replica update failure

Cargo.lock, docs/redoc/master/openapi.json, lib/collection/Cargo.toml, lib/collection/src/collection.rs, lib/collection/src/operations/snapshot_ops.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/snapshots/download.rs, lib/storage/src/content_manager/snapshots/mod.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/content_manager/toc.rs, openapi/openapi-snapshots.ytt.yaml, src/actix/api/snapshot_api.rs, src/consensus.rs, src/main.rs, src/schema_generator.rs, tests/consensus_tests/fixtures.py, tests/consensus_tests/test_snapshot_recovery.py, tests/consensus_tests/utils.py
Related to https://github.com/qdrant/qdrant/issues/1213
Introduces a new API for recovering existing collection (can't recover non-exiting collection from snapshot in distributed more, as collections are managed by consensus).
API can be used for recovery un-replicated shards and for speeding up replications of existing collections by avoiding indexing re-building with snapshots.
=> Recover distributed collection

lib/collection/src/collection.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/telemetry.rs, lib/collection/src/telemetry.rs, src/common/telemetry_ops/cluster_telemetry.rs
Extend telemetry so it would be possible to build monitoring tools using only the telemetry API, avoiding extra requests to cluster and collection
=> Extend telemetry

lib/collection/src/collection_manager/holders/proxy_segment.rs
Fix the following panic observed during testing.
```
qdrant::startup] Panic occurred in file lib/collection/src/collection_manager/holders/proxy_segment.rs at line 494: attempt to subtract with overflow
```
I also reordered the instruction to first perform all the additions.
=> Fix panic on substraction overflow

lib/storage/src/content_manager/snapshots/recover.rs, tests/consensus_tests/test_snapshot_recovery.py
Fix an issue, when during recovery, consensus was told to deactivate non-existing shards.
=> fix snapshot recovery - fix proper deactivation messages

Cargo.lock, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/config_diff.rs, lib/collection/src/operations/conversions.rs, lib/segment/Cargo.toml, lib/segment/benches/hnsw_build_asymptotic.rs, lib/segment/benches/hnsw_search_graph.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/index/hnsw_index/graph_links.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/hnsw_index/tests/mod.rs, lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/types.rs, lib/segment/tests/exact_search_test.rs, lib/segment/tests/filtrable_hnsw_test.rs
Performance difference between RAM and MMAP modes.
Test data: 40M points, dim 128, mmap vector storage and on disk payload.
Running in docker with different RAM limits. each row in table describes ram limit and searces count.
| Searches        | Links in RAM           | Links in MMAP  |
| ------------- |:-------------:| -----:|
| 3GB <br> 2K searches  | Out of memory | Avg: 1.3601s <br> p95: 1.6185s |
| 5GB <br> 2K searches | Avg: 1.1130s <br> p95: 1.3149s <br><br>  Avg: 1.1011s <br> p95: 1.2989s   |   Avg: 1.1233s <br> p95: 1.3426s <br><br> Avg: 1.1266s <br> p95: 1.3498s |
| 10GB <br> 2K searches | Avg: 0.7178s <br> p95: 0.9333s <br><br>  Avg: 0.7145s <br> p95: 0.9063s   |   Avg: 0.7334s <br> p95: 0.8898s <br><br> Avg: 0.7280s <br> p95: 0.8906s |
| 20GB  <br>  15K searches | Avg: 0.0682s …
=> Hnsw links memmap

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/wal.rs, lib/storage/Cargo.toml
This PR gets us to the latest revision of the [wal](https://github.com/qdrant/wal) project.
It contains mostly internal cleanups and dependencies updates.
The goal is to diminish the diff shipped when merging later https://github.com/qdrant/wal/pull/32
=> Bump wal to latest revision 94edd02

Cargo.lock, lib/collection/Cargo.toml, lib/storage/Cargo.toml
Update to wal revision https://github.com/qdrant/wal/commit/90471ad737dbd90c49bb8944cb8aeb5ad8664d30 to get the new error logs https://github.com/qdrant/wal/pull/34.
=> Update wal to revision 90471ad7

src/consensus.rs, src/tonic/api/raft_api.rs, src/tonic/mod.rs
This PR removes the blocking code in `RaftService` that impacts the threads of the internal gRPC Tokio runtime.
The current implementation protects a sync. bounded channel behind an async. mutex.
When the queue reaches its full capacity we get:
- one async. thread blocked on `send`
- `n` async. threads waiting for the mutex in a non blocking fashion.
Blocking a runtime thread is dangerous especially in the case when the runtime has a single thread.
The new implementation removes the need for a mutex on the producer side by using the async. mpsc from Tokio.
This solution is based on [Tokio's documentation](https://docs.rs/tokio/1.22.0/tokio/sync/mpsc/index.html#communicating-between-sync-and-async-code)
> When you want to communicate between synchronous and asynchronous code, there are two …
=> Do not block gRPC async threads in RaftService

lib/collection/src/collection.rs, lib/collection/src/tests/snapshot_test.rs, lib/storage/src/content_manager/toc.rs
Add peer id into the snapshot name to distinguish snapshots from different nodes
=> Peer id in snapshot name

lib/collection/src/collection.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/shards/local_shard.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/storage/src/content_manager/toc.rs
- Add more checks for `stop-optimization` to speed up collection destruction while optimizer is still working
- move collection to temp shard before removing, so that if delete is not finished, it won't be reused
- minor renaming
=> Shard build refactoring

lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/optimizers_builder.rs, lib/collection/src/save_on_disk.rs, lib/collection/src/shards/local_shard.rs, lib/segment/src/common/rocksdb_wrapper.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/histogram.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/index/field_index/numeric_index.rs, lib/segment/src/index/hnsw_index/graph_links.rs, lib/segment/src/payload_storage/on_disk_payload_storage.rs, lib/segment/src/payload_storage/simple_payload_storage.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/tests/payload_index_test.rs, src/snapshots.rs
As usual after a Rust release, we need to address the new Clippy lints for our CI.
=> Clippy for Rust 1.66

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/update_handler.rs, lib/collection/src/wal.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/consensus/consensus_wal.rs
This PR improves the reliability of the consensus WAL by explicitly flushing it after appending entries.
Otherwise, it is possible to lose data in case of crash.
To get there, the wal dependency had to be updated to:
- expose a flushing method for open segment
- support flushing truncated segment without crashing
See https://github.com/qdrant/wal/pull/36 for more details.
-- previous WIP description --
Trying to flush explicitly consensus wal breaks a unit test with a panic.
```
thread 'content_manager::consensus::consensus_wal::tests::test_log_rewrite' panicked at 'start = 80, end = 56', /home/agourlay/.cargo/git/checkouts/wal-b8dc0c9a3902e8fe/0e652e4/src/segment.rs:377:9
stack backtrace:
0:     0x563aac06f980 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
at …
```
=> Explicitly flush consensus WAL after

.github/scripts/protoc.sh, .github/workflows/integration-tests.yml, .github/workflows/rust-lint.yml, .github/workflows/rust.yml, .github/workflows/storage-compat.yml, Cargo.lock, Cargo.toml, Dockerfile, lib/api/Cargo.toml, lib/api/src/grpc/qdrant.rs, lib/collection/Cargo.toml, lib/storage/Cargo.toml, src/tonic/mod.rs
We have been stuck on old versions of `tonic` and `prost` due to incompatibilities with the `raft-rs` project.
I have updated the upstream dependencies in order to unblock us:
- https://github.com/tikv/protobuf-build/pull/63
- https://github.com/tikv/raft-rs/pull/496
As a result, pulling the latest version of `raft-rs` enables us to upgrade both `tonic` and `prost` to the latest version.
- https://github.com/tokio-rs/prost/releases/tag/v0.11.0
- https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#080-2022-07-29
I took this opportunity to cleanup the way we install `protoc` on our CI since we can now use a package manager https://github.com/qdrant/qdrant/pull/452#issuecomment-1092999981
I have tested that the current rust grpc client still works with those changes.
=> update tonic 0.8 & prost 0.11

Cargo.lock, lib/api/src/grpc/qdrant.rs
Now that the [tonic/prost](https://github.com/qdrant/qdrant/pull/1285) upgrade situation is solved, we can update all dependencies with `cargo update`.
=> Update all dependencies Cargo.lock

Cargo.lock, lib/api/Cargo.toml, lib/api/src/grpc/transport_channel_pool.rs, lib/collection/src/collection.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/storage/src/content_manager/toc.rs, src/consensus.rs, tests/consensus_tests/test_triple_replication.py
- add explicit timeout into connection pool, decrease timeout for consensus related messages to about 2xtick time
- Add auto-abort for transfers in case if source or target replica fails
- implement double-write strategy for maintaining consistency during the transfer finishing: now partial remote shards also forward the updates
=> Fixing missed leader inconsistency - transfers

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/update_handler.rs, lib/collection/src/wal.rs, lib/segment/src/fixtures/payload_context_fixture.rs, lib/segment/src/id_tracker/id_tracker_base.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/storage/Cargo.toml, tests/consensus_tests/test_cluster_rejoin.py
- enable async wal flush in the flush worker
- use index form id-mapper instead of vector storage id to prevent orphan id links in case of unfinished flush
=> Id mapper inconsistency

Cargo.lock, lib/collection/Cargo.toml, lib/storage/Cargo.toml, lib/storage/src/content_manager/consensus/consensus_wal.rs
This PR fixes the inconsistent state in a distributed setup causing panics at startup (https://github.com/qdrant/qdrant/issues/1235) 
This can be observed when recovering from a split brain when the raft log needs to be reconciled.
In that case the leader will override the conflicting entries in the raft logs of the followers to remove diverging histories.
To do so we truncate our consensus wal at the first conflicting index when appending entries.
The source of the issue is a bug in the truncation logic which has been very difficult to spot https://github.com/qdrant/wal/pull/38
This PR updates the version of the wal crate and ships a unit test proving that the log is now persisted properly.
=> Fix consensus wal data loss

src/consensus.rs, src/main.rs, src/settings.rs
Add an optional CLI arg for `qdrant` bin for selecting an alternative config file. 
This will help running two peers locally.
Example:
```sh
$ ./target/release/qdrant --config-path /path/to/config/file
```
=> Add the option to load alternative configuration file

.github/workflows/integration-tests.yml, .gitignore, tests/consensus_tests/utils.py
This PR enables to capture the logs of the peers used for consensus test in case of failure (https://github.com/qdrant/qdrant/issues/1318)
This is done using the [upload-artifact](https://github.com/actions/upload-artifact) Github action.
The logs files will be kept for 90 days as part of our free plan usage.
The links to the artifact can be found by clicking on the "Summary" button and scrolling all the way down.
For example https://github.com/qdrant/qdrant/suites/10313659846/artifacts/507345404
=> Save consensus logs in case of CI failure

src/consensus.rs, tests/consensus_tests/assertions.py
The change is originally motivated by https://github.com/qdrant/qdrant/issues/1315
This small PR adds extra logging to the node recovery process and improves the HTTP assertion to display more info.
=> Add extra logging to node consensus recovery process

.gitattributes, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/segment/src/common/rocksdb_wrapper.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/tiny_map.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/lib.rs, lib/segment/src/rocksdb_backup.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/utils/fs.rs, lib/segment/src/utils/mod.rs, lib/segment/src/utils/path.rs, lib/segment/src/utils/tar.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, tests/storage-compat/collection.snapshot.gz, tests/storage-compat/storage-compatibility.sh
So, the error in #1321 happens this way:
- as it turned out, RocksDB runs background jobs (i.e., threads) that may do database optimization
- in particular, reorganize `.sst` files on disk
- so, `Segment::take_snapshot` calls `tar::Builder::append_dir_all`
- `tar::Builder::append_dir_all` gets a list of files in segment's directory and starts reading and adding them to the archive one by one
- and while `tar::Builder::append_dir_all` is iterating through this list of files, RocksDB's background job deletes/renames one of the `.sst` files in the segment's directory and `tar::Builder::append_dir_all` fails with "file does not exist" error
This PR fix `Segment::take_snapshot` to use `rocksd::backup::BackupEngine` to "snapshot" RocksDB databases.
__TODO:__
- I've changed the way snapshot …
=> Fix segment snapshotting (#1321)

lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/local_shard_operations.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs
I have spotted a few places which do not require `async fn` and followed the call sites for cleanup.
=> Remove unecessary async declaration

lib/collection/src/shards/local_shard.rs
Tiny PR to avoid claiming twice the read lock on segments while computing the telemetry data.
=> Reuse segments read guard for telemetry data

src/consensus.rs, tests/consensus_tests/utils.py
Follow up on https://github.com/qdrant/qdrant/pull/1338
If the node is not able to recover consensus from other nodes after retries, it is better to simply fail to avoid having a zombie node.
=> Stop on fail consensus recovery

lib/collection/src/collection.rs, lib/collection/src/common/stoppable_task_async.rs, lib/collection/src/shards/transfer/transfer_tasks_pool.rs, lib/storage/src/content_manager/toc.rs
Before we were trying to abort transfer regardless of it's actual result in case if transfer task was cancelled, assuming that the consensus channel ordered proposals properly. But apparently this assumption does not hold.
So now, we explicitly check the result of transfer task in order to report proper result of transfer to the consensus.
=> do not abort transfer task if it was finished with success

lib/collection/src/collection.rs, lib/collection/src/shards/local_shard.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/storage/src/content_manager/snapshots/recover.rs
This PR removes a few blocking IO calls made on the Tokio runtime and makes blocking calls clearer where possible.
=> Remove some blocking IO calls on Tokio threads

docs/DEVELOPMENT.md, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/proto/collections_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/storage/src/content_manager/toc.rs, openapi/openapi-collections.ytt.yaml, openapi/tests/openapi_integration/test_alias.py, openapi/tests/openapi_integration/test_count.py, src/actix/api/collections_api.rs, src/common/collections.rs, src/schema_generator.rs, src/tonic/api/collections_api.rs
This PR adds a new API for listing existing collections aliases. 
- openapi docs generated
- openapi test
- gRPC docs
This change requires to update the clients to expose the new feature.
=> List aliases API (rest & gRPC)

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/snapshots_service.proto, lib/api/src/grpc/qdrant.rs, lib/storage/src/content_manager/snapshots/mod.rs, openapi/openapi-snapshots.ytt.yaml, openapi/tests/openapi_integration/test_snapshot.py, src/actix/api/snapshot_api.rs, src/tonic/api/snapshots_api.rs
This PR adds a new API to delete snapshots tackling https://github.com/qdrant/qdrant/issues/1360
Two new REST endpoints:
- `DELETE /collections/{collection_name}/snapshots/{snapshot_name}`
- `DELETE /snapshots/{snapshot_name}`
And two new gRPC endpoints for feature parity.
A new openapi test for snapshots has been introduced to validate the behavior.
The doc and and clients integration is to be done.
=> Delete snapshots API

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/update_handler.rs, lib/collection/src/wal.rs, lib/segment/src/segment.rs
The current process of snapshot creation might be slow, if shard is currently under optimization.
But instead of trying to save proper state of the segments, why don't we just fix all problems on the load?
This PR significantly simplifies process of snapshot creation, while also introducing additional checks for recovery and points updates:
- Deduplication process will remove outdated and redundant copies of points from the shard's segments
There is also an async removal of tmp files, I don't expect a significant speedup there, just nice-to-have optimization
=> Faster snapshot creation

lib/collection/src/collection.rs, lib/collection/src/recommendations.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/collection_test.rs, lib/collection/tests/common/mod.rs, lib/collection/tests/multi_vec_test.rs, lib/collection/tests/pagination_test.rs, lib/storage/src/content_manager/toc.rs
- Keep search runtime handle inside the collection, so `search` and `recommend` methods won't require explicit argument
=> keep search runtime handle inside the collection

lib/segment/src/index/hnsw_index/hnsw.rs
This PR names properly the Rayon thread performing the hnsw build.
This clarify the fact that this operation does not actually takes place on the optimizer runtime.
=> Name rayon hnsw threads for clarity

config/config.yaml, lib/collection/benches/batch_search_bench.rs, lib/collection/src/collection.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/common/mod.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, lib/storage/tests/alias_tests.rs, src/common/helpers.rs, src/consensus.rs, src/main.rs
This PR replaces the per-collection optimizer runtime with one global runtime, similar to what we do for the search runtime.
=> Collections share a single optimizer runtime

lib/collection/src/collection.rs, lib/collection/src/shards/local_shard.rs, lib/storage/src/content_manager/toc.rs, lib/storage/tests/alias_tests.rs, src/common/helpers.rs, src/consensus.rs, src/main.rs, src/tonic/mod.rs
THis PR merges the remaining Tokio runtimes into a single global one named `general`.
The remaining runtimes were:
- tonic
- tonic-internal
- toc
- consensus-rt
=> Merge remaining runtimes

lib/collection/src/shards/replica_set.rs
Extend `collection::shard::ShardReplicaSet::execute_read_operation` with "read consistency" support.
=> Extend `execute_read_operation` with "read consistency" support (#1373)

docs/redoc/master/openapi.json, lib/collection/src/collection.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/common/mod.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/dispatcher.rs, src/actix/api/cluster_api.rs, src/consensus.rs, src/migrations/single_to_cluster.rs, src/tonic/api/raft_api.rs
The problem:
We create collection in Partial/Dead state to prevent premature access to shards which are not created yet (like node might be down and we don't want to send requests there until node reports that collection is created)
But: shard activation is managed by consensus and we can lose the proposal is leader is lost. In this case some shards are never activated and collection create API times out. That happened in the integration tests couple of times. 
Solution: What is we create a special state of the shard called `initializing`, which means, that is it just created. No shard should have this state, as if local state is there, it is already initialized. We can use this property to report activation during the local state sync.
---- 
Pros:
- collection create API should not …
=> add init state to replica set

lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection.rs, lib/collection/src/shards/conversions.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/tests/collection_restore_test.rs, lib/collection/tests/collection_test.rs, lib/collection/tests/multi_vec_test.rs, lib/collection/tests/pagination_test.rs, lib/storage/src/content_manager/data_transfer.rs, lib/storage/src/content_manager/toc.rs, src/common/points.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs, tests/consensus_tests/test_triple_replication.py, tests/consensus_tests/test_two_follower_nodes_down.py, tests/consensus_tests/test_write_ordering.py, tests/consensus_tests/utils.py
Implements update forward according to write consistency.
The request is forwarded via the internal gRPC API without an explicit target `shard_id`  in order to be able to route the request to `update_from_client`.
=> Forward write request according to write consistency

lib/collection/src/shards/replica_set.rs
The PR https://github.com/qdrant/qdrant/pull/1405 should have been rebased after the merge of https://github.com/qdrant/qdrant/pull/1404.
A type renaming refactoring needs to be applied in a new test.
=> Fix dev branch after merge issue

config/config.yaml
Payload often consumes a lot of RAM, thus it might be reasonable to store it on disk by default.
=> Enable on disk payload option by default

lib/segment/src/types.rs
Users are struggling errors due to malformed point ids when upserting points in batch fashion.
The error does not mention the problematic input.
```
Json deserialize error: data did not match any variant of untagged enum ExtendedPointId at line 1 column 8926
```
Serde's untagged union is known for this issue.
I found the following post exposing an idea as a workaround when using only JSON https://users.rust-lang.org/t/serde-untagged-enum-ruins-precise-errors/54128
=> Implement Deserialize for ExtendedPointId to improve error reporting

lib/collection/src/optimizers_builder.rs, lib/segment/src/common/cpu.rs, lib/segment/src/common/mod.rs, lib/segment/src/index/hnsw_index/config.rs, src/common/helpers.rs, src/settings.rs
There are several things, which depend on CPU number:
- default number of segments
- number of workers
- default number of indexing threads 
Use `QDRANT_NUM_CPUS` to re-redefine number used CPUs.
Useful in container env, where available cpus != system cpus.
=> allow to overwrite max number of cpus with env variable

docs/grpc/docs.md, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/shards/conversions.rs, src/tonic/api/points_common.rs
Removes version compatibility code, used for https://github.com/qdrant/qdrant/pull/1249
Issue: https://github.com/qdrant/qdrant/issues/1248
NOTE: merge on major release
=> remove deprecate point ids param in gprc

lib/collection/src/common/stoppable_task.rs
Disable test for the release until we figure out the flakiness on Windows.
Tracked with https://github.com/qdrant/qdrant/issues/1442
Will need to be cherry-picked to master
=> Disable test_task_stop on Windows

docs/redoc/master/openapi.json, lib/storage/src/content_manager/consensus/consensus_wal.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, openapi/openapi-cluster.ytt.yaml, src/actix/api/cluster_api.rs, src/consensus.rs, tests/consensus_tests/test_collection_recovery.py, tools/generate_openapi_models.sh
- Utilized `RawNode::report_snapshot`
- Without `report_snapshot` call on the leader, the snapshot will, generally, be applied on the follower without any obvious errors, but any consensus operation after that simply won't work
- Make `apply_snapshot` error non-fatal, so that, e.g., an "outdated snapshot" error won't stop the entire consensus thread
Also made a few changes to be able to trigger `RawNode::request_snapshot`, some/all of which should be removed before merging.
__TODO:__
- It's not clear how to properly call `report_snapshot` in case some node requested multiple snapshots in a burst sequence.
- E.g., there's no way to report a _particular_ snapshot. I'd assume it's just always applied to the "last requested" one?
- Does this mean that some extra care have to be taken with …
=> Add `/cluster/recover` API endpoint

lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/operations/payload_ops.rs, lib/collection/tests/collection_restore_test.rs, lib/segment/src/common/utils.rs, lib/segment/src/index/index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs, lib/segment/src/payload_storage/on_disk_payload_storage.rs, lib/segment/src/payload_storage/payload_storage_base.rs, lib/segment/src/payload_storage/payload_storage_enum.rs, lib/segment/src/payload_storage/query_checker.rs, lib/segment/src/payload_storage/simple_payload_storage_impl.rs, lib/segment/src/types.rs, lib/segment/tests/exact_search_test.rs
This PR updates the payload JSON addressing infrastructure to support nested access through arrays.
E.g:
- `a.b.c[]`
- `a.b.c[1]` 
- `a.b.c[].e`
- `a.b.c[1].e`
This affects both payload key lookups and deletions.
This change is not propagated fully to the indexers for the time being to keep the PR small.
Previously a path lookup would return an `Option<&Value>`, now it returns something akin to `Vec<&Value>`.
To avoid creating a lot of Vec with a single element, this PR introduces the `JsonPathTarget` abstraction.
=> Access payload key through nested Array

config/config.yaml, lib/collection/src/collection.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, lib/storage/tests/alias_tests.rs, tests/consensus_tests/fixtures.py, tests/consensus_tests/test_listener_node.py, tests/consensus_tests/utils.py
- A new shard state for backup-oriented nodes
- If shard is in a listener state - it will accept write requests with wait=false
- Search requests are not sent to listener node
- There is a new values in config - `node_type`. If node type = Listener, add shards on this node will be requested to convert  into listening  shards
=> add listener shard state

lib/segment/src/payload_storage/condition_checker.rs, openapi/tests/openapi_integration/test_filter_values_count.py
I believe I found a bug in the way `values_count` is checked.
The `check` needs to be implemented for `ValuesCount` as the base implementation applies the check on each array element.
=> Fix condition check for values_count

lib/storage/src/content_manager/collection_meta_ops.rs
to avoid confusion with param name in collection_info api
=> allow to use optimizer_config rest api

lib/segment/src/index/hnsw_index/graph_layers_builder.rs
Fix warning while windows tests:
```
warning: function `parallel_graph_build` is never used
--> lib\segment\src\index\hnsw_index\graph_layers_builder.rs:452:8
|
452 |     fn parallel_graph_build<TMetric: Metric + Sync + Send, R>(
|        ^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
=> Fix windows warning in CI

lib/collection/src/shards/replica_set.rs, tests/consensus_tests/test_collection_recovery.py
This PR tackles the flaky test `consensus//test_collection_recovery.py`
This test fails quite often on our CI ([e.g,](https://github.com/qdrant/qdrant/actions/runs/4285965943/jobs/7464917615#step:10:140))
```
FAILED tests/consensus_tests/test_collection_recovery.py::test_collection_recovery - assert 0 > 0
```
It fails also pretty often locally for me.
My understanding is that the test expects the shard to be up to date once its remote shards are active.
However, it is possible that the local shards are not yet ready.
```
Local shards: [{'shard_id': 0, 'points_count': 0, 'state': 'Partial'}]
```
I propose to wait for both remote and local shards to be active before querying the number of points.
=> Wait for all shards to be active when testing collection recovery

lib/collection/src/shards/replica_set.rs
Fixes extensive requests in `execute_and_resolve_read_operation` in case if local shard is present.
This issue was significantly affecting performance in case of replication_factor > 1 due to looping queries.
=> Fix connections flood bug

docs/redoc/master/openapi.json, lib/collection/src/collection.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_config.rs, lib/collection/src/tests/snapshot_test.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/consensus/persistent.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/dispatcher.rs, openapi/openapi-snapshots.ytt.yaml, src/actix/api/snapshot_api.rs, src/actix/helpers.rs, src/main.rs, src/snapshots.rs
- Allows to recover snapshots, taken in distributed mode, on local deployment.
- Allows to recover snapshot even if collection does not exists
- Allows to use `wait=false` during recovery, API will also tolerate disconnections now
=> Fix recover snapshot peer

Dockerfile
Building the Docker image on M1 hardware currently fails, because there is no `gcc-multilib` installation candidate on arm64, as reported by https://github.com/qdrant/qdrant/issues/1514. The `gcc-multilib` package is required for cross compilation (arm64 on amd64) and was introduced in https://github.com/qdrant/qdrant/pull/1000.
This PR makes the `gcc-multilib` package optional, to only install it when it is available on the current architecture. This ensures builds on M1 succeed, while cross compilation is still possible om amd64.
This is probably not ideal, but may be a nice middle ground. What do you think?
=> Fix Docker builds on M1/amd64 by making gcc-multilib optional

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/types.rs
After experiments on slow disks I found out that 
final re-scoring actually significantly affects the search RPS:
E.g.:
| Setup                            | RPS    | Precision |
|----------------------------------|--------|-----------|
| 4.5Gb(full) mem                       | 600    | 0.99      |
| 4.5Gb(full) + quant + rescore     | 1000   | 0.989     |
| 2Gb mem, on disk                 | 2      | 0.99      |
| 2Gb mem, quant + rescore         | 30     | 0.989     |
| 2Gb mem, quant + no-rescore      | 1200   | 0.974     |
depending on the case, different scenarios might be preferable. So I propose to make re-scoring an optional search param.
=> Quantization re scoring param

tests/consensus_tests/test_peer_snapshot_bootstrap.py
Add a test for new peer bootstrap when all cluster nodes have truncated WAL.
=> Add `peer_snapshot_bootstrap` test

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shards/local_shard.rs, lib/segment/src/segment.rs
Enforce flush priority for appendable segments:
It is important to flush appendable segments first and non-appendable later, because on update we move data from non-appendable to appendable, and we want to make sure that data is moved before we flush delete flag on the source segment
=> ensure segment flushing order + extend logging

Cargo.lock, Cargo.toml, docs/redoc/master/openapi.json, openapi/openapi-service.ytt.yaml, src/actix/api/service_api.rs, src/common/metrics.rs, src/common/mod.rs, src/common/telemetry.rs, src/common/telemetry_ops/app_telemetry.rs, src/common/telemetry_ops/requests_telemetry.rs
Fixes #1494
This adds a `/metrics` endpoint to facilitate OpenTelemetry/Prometheus tools. This is currently based upon, but differs in format to, the `/telemetry` endpoint.
The current `TelemetryData` struct is used as source for this data. Later, this can be extended or implemented separately.
Here you see reporting to Prometheus in action with a dummy load as it is currently being worked on:
---
- Mention `/metrics` in `qdrant/docs`
=> Add `/metrics` endpoint for OpenTelemetry/Prometheus (#1494, #1541)

lib/collection/src/collection_manager/holders/segment_holder.rs
This PR is a workaround for https://github.com/qdrant/qdrant/issues/1573
I tried reproducing the issue with a similar setup
- 36M vectors
- memmap_threshold=250000
- toggling the indexing on and off
I was not able to get the same error, I have however some supporting data.
While running the tests, I would be logging the time spent to acquire and unwrap the segment as the last owner.
Most of the time I would get values around 100ms but from time to time, I'd get really high values.
The highest witnessed were 5954ms and 2414ms which are pretty close to the 10 sec max wait time.
For the time being, I propose to increase the max wait time to 1 minute to accommodate large segments.
=> Increase drop data timeout to accomodate larger segments

Cargo.lock, Cargo.toml, lib/storage/Cargo.toml, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, src/actix/api/cluster_api.rs, src/consensus.rs
We have been depending on a non released `raft-rs` version to enable updating Tonic and Prost https://github.com/qdrant/qdrant/pull/1285
A new version has been released containing our changes https://github.com/tikv/raft-rs/releases/tag/v0.7.0
This PR changes the dependency configuration to depend on the new version instead of a specific commit hash.
There is a change impacting us regarding requesting snapshots https://github.com/tikv/raft-rs/pull/499
=> Update to Raft-rs 0.7.0

Cargo.lock, Cargo.toml, docs/redoc/master/openapi.json, lib/collection/src/operations/snapshot_ops.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/errors.rs, openapi/openapi-snapshots.ytt.yaml, src/actix/api/snapshot_api.rs, src/actix/mod.rs, tests/consensus_tests/test_snapshot_upload.py
This PR is related to #1567
I added the upload functionality using _actix-multipart_ with as little changes as possible. I tried not to dive in too deep and make a bunch of changes in my first pull request without consulting the mentors first.
This solution is far from optimal. Off the top of my head, I think it can be improved by not having to write the snapshot file to disk and restore it from memory. This would require some changes in the recovery logic to make it work that way (didn't look thoroughly into that but I'm willing to, if it's suitable).
Also the use of a `tempfile` then persisting …
=>  add upload snapshot functionality using multipart request 

README.md, docs/DEVELOPMENT.md
After many trials to build and run Qdrant in my local machine and Gitpod, I preferred to add a guidance for how to prepare local development environment to build and run Qdrant.
I did test on below:
- My VM on KVM
```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
- Gitpod session
```shell
$  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```
=> doc: added steps to install Qdrant in local dev env

tests/consensus_tests/fixtures.py, tests/consensus_tests/test_cluster_rejoin.py, tests/consensus_tests/utils.py
This PR increases the timeout in the consensus rejoin cluster test following a failure on CI.
https://github.com/qdrant/qdrant/actions/runs/4501309023/jobs/7921564227?pr=1597
Checking the logs, it seems all nodes where making progress, I could not spot a clear issue.
Given that it is the first time this issue appears, I simply propose to raise the timeout for the `drop_collection` operations from 3 secs to 5 secs.
=> Increase timeout for rejoin cluster test

lib/segment/tests/payload_index_test.rs, lib/segment/tests/utils/mod.rs, lib/segment/tests/utils/scored_point_ties.rs
This PR tackles the flaky test described in https://github.com/qdrant/qdrant/issues/534
The root issue is that the current test assertion does not handle the case where points have identical scores but with different positions.
To fix the issue, this PR introduces test infrastructure to provide a deterministic sort of scored points by breaking ties on point id.
=> Handle ties scores in test assertions

lib/storage/src/content_manager/consensus_manager.rs
As it turned out, [blocking calls in async context is a much bigger deal, than one may think][tokio-blocking-bug]. Seems like we're hitting this bug, and this PR fixes it.
[tokio-blocking-bug]: https://github.com/tokio-rs/tokio/issues/4730
=> Wrap blocking `await_ready_for_timeout` call with `tokio::task::spawn_blocking`

openapi/tests/openapi_integration/test_service.py, src/actix/api/service_api.rs, src/common/metrics.rs, tests/basic_api_test.sh
Improves #1541 with suggestions from https://github.com/qdrant/qdrant/pull/1541#issuecomment-1468037878.
This improves upon the existing metrics system. It now collects/formats the metrics output more efficiently.
It now uses a whitelist for endpoints to report only the most significant ones: a selection of search, recommend and upsert endpoints:
```rust
const REST_ENDPOINT_WHITELIST: &[&str] = &[
"/collections/{name}/index",
"/collections/{name}/points",
"/collections/{name}/points/payload",
"/collections/{name}/points/recommend",
"/collections/{name}/points/recommend/batch",
"/collections/{name}/points/search",
"/collections/{name}/points/search/batch",
];
const GRPC_ENDPOINT_WHITELIST: &[&str] = &[
"/qdrant.Points/OverwritePayload",
"/qdrant.Points/Recommend", …
```
=> Improve metrics building performance, limit endpoints to whitelist

src/common/metrics.rs
This is a partial implementation of #1583. Should the base branch be master or dev?
New to the codebase, figured observability would touch a couple of points.
This PR implements an aggregated total of all vectors across collections for Prometheus on /metrics.  I only implemented it on detail level 1. More would need some refactoring to avoid duplication on the aggregate telemetry itself. Consider this WIP. Would propose to scope it to vector count only to keep the PR small.
Couple considerations:
* Conceptually, why is there a need for the aggregated telemetry? From the code it still looks to dive into the collections. Future performance?
* Would love to add proper tests; are the integration tests ok for this?
2. [x] Have you lint your code locally …
=> Add aggregated vector count to prometheus /metrics endpoint

lib/collection/src/telemetry.rs, src/actix/api/service_api.rs, src/common/metrics.rs, src/common/telemetry_ops/collections_telemetry.rs
This fixes an issue where vectors were not counted properly in the `/metrics` output introduced in <https://github.com/qdrant/qdrant/pull/1598>.
It now successfully outputs:
```bash
collections_vector_total 100028
```
=> Fix metrics vector count

src/tonic/mod.rs
Yesterday we merged a PR updating tonic to 0.9.0 https://github.com/qdrant/qdrant/pull/1636
I think we missed a potential issue with the breaking change mentioned in the release notes.
https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#v090-2023-03-31
```
Default decoding message limit set to 4MiB by default.
```
It is a breaking change because there used to be no limits.
This could be an issue for users previously pushing gRPC payload larger than 4MB and for our internal gRPC API.
This PR proposes to set the limit to:
- `settings.service.max_request_size_mb` for the external gRPC API
- `usize::MAX` for the internal gRPC API
=> Set max_decoding_message_size to larger value following tonic 0.9.0

lib/collection/src/operations/types.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/storage/src/content_manager/errors.rs
Currently, _any_ error during `ForwardProxyShard::update` (including error of _remote shard_) are treated as failure of the _local_ shard. This leads to local shard being (or, at best, _attempted_ to be) marked as dead if remote shard is faulty.
This PR attempts to fix this bug in the most trivial way.
=> Fix `ForwardProxyShard::update` error handling

src/tonic/mod.rs
Follow up on https://github.com/qdrant/qdrant/pull/1658
We decided to it would make more sense to not introduce any restriction on the gRPC payload size as it would be a breaking change in practice.
This PR gets us back to the previous behavior.
=> Remove decoding limit for external gRPC endpoints

lib/collection/src/shards/replica_set.rs
Found using [lockbud](https://github.com/BurtonQin/lockbud) 
Docs from [RwLock](https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html)
```
This lock uses a task-fair locking policy which avoids both reader and writer starvation.
This means that readers trying to acquire the lock will block even if the lock is unlocked when there are writers waiting to acquire the lock. 
Because of this, attempts to recursively acquire a read lock within a single thread may result in a deadlock.
```
Lockbud yields:
```
[2023-04-06T10:43:37Z WARN  lockbud::callbacks] [
{
"DoubleLock": {
"bug_kind": "DoubleLock",
"possibility": "Possibly",
"diagnosis": {
"first_lock_type": "ParkingLotRead(shards::replica_set::ReplicaSetState)",
"first_lock_span": "lib/collection/src/shards/replica_set.rs:197:9: …
```
=> Fix possible double read on replica_state

lib/segment/src/vector_storage/raw_scorer.rs
After last changes in https://github.com/qdrant/qdrant/pull/1561 this bug arppeared: https://github.com/qdrant/qdrant/issues/1670
After investigation, there is quickfix for this bug.
Possible steps to reproduce:
1. Create collection
2. Upload 100 vectors
3. Delete LAST(!) 50 vectors
4. Restart Qdrant
5. Search something
Possible reason:
Before https://github.com/qdrant/qdrant/pull/1561 size of vector storage and deleted flags was equal. After changes, deleted flags are built from rocksdb and deleted flags can have different capacity and size that vector storage.
7. [ ] Have you lint your code locally using ``cargo fmt`` command prior to submission?
8. [ ] Have you checked your code using ```cargo clippy``` command?
=> Fix search one day bug

lib/segment/src/vector_storage/quantized/scalar_quantized.rs, lib/segment/src/vector_storage/raw_scorer.rs
Use `check_point` method in raw scorer. It's potentional fix for bugs like https://github.com/qdrant/qdrant/issues/1670 and it reduces deletion logic duplication.
=> additional deleted checks in raw scorers

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/collection.rs, lib/collection/src/operations/shared_storage_config.rs, lib/collection/src/shards/collection_shard_distribution.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/src/wal.rs, lib/collection/tests/snapshot_recovery_test.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/types.rs, lib/storage/Cargo.toml
Use combination of Plunger + empty WAL to be able to make a snapshot without ever locking WAL
Plunger ensures that all changes (available at the point of snapshotting) will make into storage, so the WAL will not be required.
=> ability to save snapshot without locking wal

.github/workflows/integration-tests.yml, docs/DEVELOPMENT.md, tests/grpc_consistency_check.sh, tests/openapi_consistency_check.sh
_Discussed [here](https://github.com/qdrant/qdrant/pull/1665#issuecomment-1497309003)._
This adds a CI job to ensure generated OpenAPI and gRPC files are consistent with their sources.
This hopefully prevents issues in the future where OpenAPI or gRPC files are accidentally not updated.
For example, if OpenAPI files are not up-to-date with their sources it will error with:
```
+ diff -Zwa ./openapi/openapi-merged.yaml ./openapi/.repo.openapi-merged.yaml
+ diff -Zwa ./openapi/openapi-merged.json ./openapi/.repo.openapi-merged.json
3678c3678
<             "minimum": 0
---
>             "minimum": 5
3915c3915
<             "format": "uint",
---
>             "format": "double",
+ set +x
ERROR: Generated OpenAPI files are not consistent with files in this repository, see diff above.
ERROR: …
```
=> Add CI job to enforce generated OpenAPI and gRPC file consistency

Cargo.lock, Dockerfile, lib/api/Cargo.toml, lib/api/src/grpc/dynamic_channel_pool.rs, lib/api/src/grpc/dynamic_pool.rs, lib/api/src/grpc/mod.rs, lib/api/src/grpc/transport_channel_pool.rs, lib/collection/Cargo.toml, lib/collection/src/collection.rs, lib/collection/src/operations/shared_storage_config.rs, lib/collection/src/shards/collection_shard_distribution.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/src/wal.rs, lib/collection/tests/snapshot_recovery_test.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/types.rs, lib/storage/Cargo.toml, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, lib/storage/tests/alias_tests.rs, src/consensus.rs, src/settings.rs
Globally there are 2 types of reasons why high concurrency benchmarks break stuff:
- DDoS-effect - one external request creates multiple internal. The load affects even health-check requests (both - manual and http2-keepalive. Messed-up internal timings create a wave of failures - shard transfer slows everything down - new requests are failing on all nodes before the consensus is able to react. As the result - all nodes are marked as failed.
- Shard failure might create an inconsistency in data, if `weak` ordering is used. Inconsistency can break incoming stream of changes, unless stronger ordering pattern isn't used. More info: https://qdrant.tech/documentation/distributed_deployment/#write-ordering
---
This PR aimed to fix the first part of the problem: prevent peer failing even under …
=> Try to fix dying shards

config/config.yaml, src/actix/mod.rs, src/common/helpers.rs, src/settings.rs, src/tonic/mod.rs, tests/tls/test_tls.sh, tests/tls/tls_config.yaml
- Add capability to validate user client's certificate. This is used to ensure only authorized user can access the HTTPs API
- Fix broken TLS test due to change in https://github.com/qdrant/qdrant/pull/1593
=> Add user client certificate validation capabiltiy

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/api/build.rs, lib/api/src/grpc/mod.rs, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/Cargo.toml, lib/collection/src/operations/validation.rs, src/actix/mod.rs, src/tonic/api/collections_api.rs, src/tonic/api/collections_internal_api.rs, src/tonic/api/mod.rs, src/tonic/api/points_api.rs, src/tonic/api/points_internal_api.rs, src/tonic/api/raft_api.rs, src/tonic/api/snapshots_api.rs
Extends <https://github.com/qdrant/qdrant/pull/1463>.
This adds validation to gRPC request bodies. Both the external (public) and internal gRPC APIs are validated.
The external API now returns an  [`INVALID_ARGUMENT`](https://docs.rs/tonic/0.9.1/tonic/struct.Status.html#method.invalid_argument) error on validation failure with a message describing why validation failed.
For example:
```bash
$ docker run --rm --network=host -v /home/timvisee/git/qdrant/lib/api/src/grpc/proto:/proto fullstorydev/grpcurl -plaintext -import-path /proto -proto qdrant.proto -d '{
"collection_name": "",
"vectors_config": {
"params": {
"size": 0,
"distance": "Dot"
}
}
}' localhost:6334 qdrant.Collections/Create
ERROR:
Code: InvalidArgument
Message: Validation error in body: [collection_name: value "" invalid, …
```
=> Add validation to gRPC

lib/collection/src/collection_manager/segments_searcher.rs
This fixes a potential panic in `clamp` when a high `ef_limit` value is used when searching.
The usage of `clamp` was introduced in ([#1675](https://github.com/qdrant/qdrant/commit/b7c1ecfd5f75bba775ed031a8ab855298d72ab1d#diff-cb0e9997c84d55ebb0f87b7fe719a65fb2f66b1dcb1d003e99939df680b27307R333)) to simplify the logic, but it likely introduced this nasty side effect.
=> Fix potential panic in clamp function with high ef_limit value

lib/collection/src/operations/types.rs, openapi/tests/openapi_integration/test_basic_retrieve_api.py
Makes alias for `with_vector` parameter, to enable the plural form (`with_vectors`) in REST API requests. 
Solves #1554 
=> [REST] alias `with_vector` <-> `with_vectors`

src/consensus.rs, src/settings.rs
- added `message_timeout_ticks` parameter to the consensus config
- and changed default message timeout to __10__ ticks instead of 2
- 10 seems like a safe bet, as [by default re-election starts at `10 * heartbeat_tick` ticks][election-tick]
- and [default `heartbeat-tick` is 2 ticks][heartbeat-tick]
- (and here's [a min and max election tick][min-max-election-tick] for the reference)
- but we can revert it back to 2 to be safe
The parameter is pretty useful for debugging, I've been using it a lot in the last few weeks, so at this point I'd just add it to the config.
[election-tick]: https://github.com/tikv/raft-rs/blob/10c6e9db6792b85c81784e44fc278f895d5f0ab0/src/config.rs#L108
[heartbeat-tick]: https://github.com/tikv/raft-rs/blob/10c6e9db6792b85c81784e44fc278f895d5f0ab0/src/config.rs#L1 …
=> Add `message_timeout_ticks` parameter to consensus config

src/common/metrics.rs
This removes the `collections_{full,aggregated}_total` gauges from metrics. These were intended for telemetry, and are not useful for metrics.
More specifically, it removes these two:
```bash
collections_full_total 0
collections_aggregated_total 2
```
=> Remove collections_{full,aggregated}_total metric gauges

src/tonic/logging.rs, src/tonic/logging_middleware.rs, src/tonic/mod.rs
A common issue with the gRPC API is that is a blackbox in terms of error reporting.
Errors returned to the users are not logged in any way.
This PR adds a new Tower `LoggingMiddleware` for the internal and external gRPC APIs.
It was developed using [this example](https://github.com/hyperium/tonic/blob/master/examples/src/tower/server.rs) as reference.
E.g.
```
[2023-04-11T13:13:06.501Z ERROR qdrant::tonic::logging] gRPC /qdrant.Snapshots/Create failed with Internal error "Service internal error: Error while copy WAL \"./storage/snapshots_tmp/high-concurrency-17501009700520899966-2023-04-11-13-13-05.tmp/0\" No such file or directory (os error 2)" 0.311448
```
=> gRPC logging middleware

lib/collection/src/collection_manager/segments_searcher.rs
Fixes incorrect logic for choosing the effective ef_limit with poisson sampling when searching. This potentially improves search performance in some scenarios.
There was some confusion about what the effective `ef_limit` value should be for searching, this adds tests to ensure the logic for calculating it is correct. This showed a logic discrepancy which is now fixed.
Now, the lower limit is picked when `ef_limit` is larger than `limit`. This may result in a performance boost in some search configurations.
This table shows the difference for some input values. We used F1 before, this PR changes to F2:
*Via: https://docs.google.com/spreadsheets/d/16nJBXQ757tGjX0aOCSFNKuHiTYG2QtB2DQoVWb3enVo/edit*
2. [x] Have you lint your code locally using ``cargo …
=> Fix and test effective ef_limit with poisson sampling

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/segment/benches/vector_search.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/fixtures/payload_context_fixture.rs, lib/segment/src/id_tracker/id_tracker_base.rs, lib/segment/src/id_tracker/simple_id_tracker.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/hnsw_index/point_scorer.rs, lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/segment.rs, lib/segment/src/vector_storage/chunked_vectors.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/mmap_vectors.rs, lib/segment/src/vector_storage/mod.rs, lib/segment/src/vector_storage/quantized/quantized_vectors_base.rs, lib/segment/src/vector_storage/quantized/scalar_quantized.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
Part of <https://github.com/qdrant/qdrant/issues/1045>.
This implements logic in our storage bits to support optional named vectors in the future. I set a goal to keep things performant and relatively simple.
In a later PR I will expose this functionality in the external API so this can be used.
In short:
- Based upon earlier deleted flag bitvec implementation, but heavily improved
- Add bitvec with deleted flags in all storage types
- Use `BitSlice` everywhere to determine point/vector deletions, this unifies the deleted interface across all storage types, making stuff simpler
- In mmap segment, directly map `BitSlice` on top of a mmap file. So we don't need to load/store bitvecs, and we don't need multiple bitvecs, keeping things simple
- Add deleted vector support in raw scorer …
=> Add support for deleted vectors in segments

lib/segment/src/index/hnsw_index/graph_links.rs
Clippy got smarter and reports a new error.
```
error: type parameter goes unused in function definition
--> lib/segment/src/index/hnsw_index/graph_links.rs:605:23
|
605 |     fn test_save_load<A, B>(points_count: usize, max_levels_count: usize)
|                       ^^
|
= help: consider removing the parameter
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_type_parameters
= note: `-D clippy::extra-unused-type-parameters` implied by `-D warnings`
```
I seems the test was not actually cross checking implementation, the graph converter seems to be fixed.
=> fix Clippy 1.69 lint 'type parameter goes unused in function definition'

config/development.yaml, lib/collection/src/collection.rs, lib/collection/src/operations/shared_storage_config.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/mod.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs, lib/segment/src/common/file_operations.rs, lib/segment/src/common/version.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/storage/src/content_manager/alias_mapping.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, lib/storage/tests/alias_tests.rs, tests/consensus_tests/fixtures.py, tests/consensus_tests/test_dummy_shard.py
- added [`DummyShard`] shard variant, that simply returns an error on any operation
- if `LocalShard::load` fails with out-of-disk-space error, [`DummyShard` is loaded instead][dummy-shard-load],
which allows deleting the collection, but not much else
- also made [`LocalShard::load_from_wal`] to propagate an error (instead of panicking)
- and disabled shard transfer for `DummyShard`s
- changed `AliasPersistence::remove` and `AliasPersistence::remove_collection` to only update persisted file,
if some existing alias was actually removed
- `TableOfContent::delete_collection` calls `AliasPersistence::remove_collection`
- and `AliasPersistence::remove_collection` uses `atomicwrites` crate, which creates a copy
of the file and then moves it over the original
- but there may be no space on the …
=> Improve handling of out-of-disk-space errors during Qdrant startup

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/segment/benches/conditional_search.rs, lib/segment/src/common/mod.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/id_tracker/id_tracker_base.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/index/field_index/stat_tools.rs, lib/segment/src/index/hnsw_index/config.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/payload_index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/mmap_vectors.rs, lib/segment/src/vector_storage/quantized/scalar_quantized.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/segment/tests/disbalanced_vectors_test.rs, lib/segment/tests/exact_search_test.rs, lib/segment/tests/filtrable_hnsw_test.rs, lib/segment/tests/payload_index_test.rs, lib/segment/tests/segment_tests.rs, tests/consensus_tests/test_collection_shard_update.py
Continuation of <https://github.com/qdrant/qdrant/pull/1724>. Part of <https://github.com/qdrant/qdrant/issues/1045>.
This updates the query planner to make it aware of deleted points and vectors.
In short:
- estimates the number of deleted vectors in a vector storage instance
- makes cardinality calculations aware of deleted vectors
- for unfiltered HNSW searches it may fall back to a full scan if there are a lot of deleted vectors
This plays with query cardinality/estimations. I'm not entirely sure I implemented these changes correctly. I hope any incorrectness/problems come up with code review.
Note that this does not touch the optimizers. That will be done in a separate PR.
2. [x] Have you lint your code locally using ``cargo fmt`` command prior …
=> Make query planner aware of deleted points and vectors

lib/segment/src/common/utils.rs, openapi/tests/openapi_integration/test_nested_payload_indexing.py
Tackling issue #1783 
The root cause was that the JsonPath extractor did not handle arrays of scalar values.
Added unit test and integration tests.
=> Support Array of Scalars in JsonPath extractor

lib/segment/benches/conditional_search.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/payload_index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/query_estimator.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment.rs, lib/segment/tests/exact_search_test.rs, lib/segment/tests/filtrable_hnsw_test.rs, lib/segment/tests/payload_index_test.rs
Keep query cardinality abstraction separated from the concept of optional vectors.
There were an attempt to introduce the "available vertor" param into `estimate_cardinality`, but after some consideration I think it should be kept separately.
There is only one place, where we truly care about adjusting cardinality estimation to take removed vectors into account - the "query planner".
So instead of changing interface of `estimate_cardinality` and `query_points` we simply re-adjust estimation after it is computed in `estimate_cardinality`.
=> undo vector-related changes in estimate_cardinality

Cargo.lock, Cargo.toml, src/settings.rs
=> fix: use `#[sealed_test]` for tests that rely on `RUN_MODE` environment variable

Dockerfile, lib/collection/src/operations/shared_storage_config.rs, lib/collection/src/shards/replica_set.rs, lib/storage/src/types.rs, lib/storage/tests/alias_tests.rs, src/main.rs, src/startup.rs, tests/low-ram/low-ram.sh, tools/entrypoint.sh
Alternative to internal handling of memory issue
Instead of handling OOM inside qdrant binary, we can use an external script, that can run Qdrant in recover mode if qdrant failed during initialization.
There are following scenarios to consider:
- default mode - if no flags are specified, operate as usual, fail as usual, no recovery what-so-ever
- OOM/kill after initialization - not necessary require a recovery mode, so we just exit
- Error during initialization, but not OOM (e.g. SIGINT) - exit as is, no changes
- OOM/kill during initialization + recovery allowed by flag - only in this case we want to start a recovery mode.
Recovery mode will load all shards as dummy, and will report configured error message.
No regular checks or percentage of available memory required.
=> Oom fallback script

config/config.yaml, src/actix/certificate_helpers.rs, src/actix/mod.rs, src/settings.rs
- Use OpenSSL's `set_servername_callback` to implement certificate re-load for actix
- Caching the SSL context in memory so that we don't load certificates whenever we have a new connection. Instead, a TTL mechanism controls the re-load from disk
Idea comes from @PaulFurtado . Thanks for suggesting this change. 
Certificate reload is important to enable users to swap certificates while the server is running. This is particularly useful for HTTPS endpoints because usually it is handled by a certificate manager (like in Kubernetes), and the certificate have a very short TTL
=> Add support for TLS certificate rotation

.gitignore
Qdrant now creates a `.qdrant-initialized` file after initialization. We don't want to commit it.
=> Add .qdrant-initialized to .gitignore

lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/operations/point_ops.rs, lib/segment/src/common/mod.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/segment.rs, lib/storage/src/content_manager/consensus_manager.rs
Blocks <https://github.com/qdrant/qdrant/pull/1816> and <https://github.com/qdrant/qdrant/pull/1836>. Part of <https://github.com/qdrant/qdrant/issues/1045>.
Small improvements around optional named vectors. This lays the groundwork for future PRs like <https://github.com/qdrant/qdrant/pull/1816> and simplifies them.
=> General optional named vector improvements

.gitignore, config/config.yaml, docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/build.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/config_diff.rs, lib/collection/src/optimizers_builder.rs, openapi/tests/openapi_integration/test_validation.py, openapi/tests/openapi_integration/test_vector_config.py, openapi/tests/requirements-freeze.txt, openapi/tests/requirements.txt
Switching from `null` to `0` to signify *disable* on `indexing_threshold` and on `memmap_threshold`
follow-up to #1702: Previously we allowed `null` to *disable*, but the problem was that we cannot set these parameters to `null` using gRPC, we can only **not** set them, which is ambiguous for when the user wants to deliberately have the default or the disabled value. 
Using `0` fixes this problem.
2. [x] Have you formatted your code locally using ``cargo fmt`` command prior to submission?
=> Disable indexing and memmap with `0`

docs/grpc/docs.md, lib/api/build.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/proto/points_service.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/src/collection_manager/collection_updater.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/operation_effect.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/operations/vector_ops.rs, lib/collection/src/shards/conversions.rs, lib/collection/src/shards/remote_shard.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment.rs, lib/segment/tests/disbalanced_vectors_test.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs
Depends on <https://github.com/qdrant/qdrant/pull/1835>. Continuation of <https://github.com/qdrant/qdrant/pull/1758>. Part of <https://github.com/qdrant/qdrant/issues/1045>.
This PR adds a public and internal gRPC interface for updating and deleting optional named vectors.
Sorry for the PR size. There's a lot of layers to go through from the public interface to the internal functions. That makes it hard to shrink it further. Though big, the PR is quite simple. I'd be happy to walk through this in a call.
The basic interface consists of two actions:
https://github.com/qdrant/qdrant/blob/e0649929fc05410756fb2fdf3c851c608f4b1096/lib/api/src/grpc/proto/points.proto#L74-L88
I'd like to ask to take a look at the following with extra care:
- the public API design …
=> Add gRPC interface to update/delete optional named vectors

docs/redoc/master/openapi.json, lib/collection/src/operations/vector_ops.rs, lib/segment/src/data_types/vectors.rs, openapi/openapi-points.ytt.yaml, src/actix/api/update_api.rs, src/schema_generator.rs
Depends on <https://github.com/qdrant/qdrant/pull/1816>. Continuation of <https://github.com/qdrant/qdrant/pull/1816>. Part of <https://github.com/qdrant/qdrant/issues/1045>.
This adds the REST interface endpoints for updating and deleting optional named vectors.
Tests will be added in a separate PR.
I did some basic testing for this against the REST interface locally.
=> Add REST interface to update/delete optional named vectors

lib/collection/src/operations/vector_ops.rs, openapi/tests/openapi_integration/test_optional_vectors.py
Depends on <https://github.com/qdrant/qdrant/pull/1836>. Continuation of <https://github.com/qdrant/qdrant/pull/1836>. Part of <https://github.com/qdrant/qdrant/issues/1045>.
This adds some integration tests for the REST endpoints covering updating and deleting optional named vectors.
=> Add integration tests for REST update/delete optional named vectors

lib/collection/src/collection_manager/holders/segment_holder.rs
Follow up to https://github.com/qdrant/qdrant/pull/1595
It seems the value is still too low given a user report on Discord.
This PR proposes to bump the timeout value straight to 1h to hopefully unblock the situation and give us time to investigate.
=> increase drop segment timeout to 1h

lib/segment/src/common/mmap_type.rs
This fixes mmap alignment issues on Windows we had on <https://github.com/qdrant/qdrant/pull/1860> and <https://github.com/qdrant/qdrant/pull/1838>.
A round of applause for @Jesse-Bakker for taking the time to [figure](https://github.com/qdrant/qdrant/pull/1860#discussion_r1189037474) this out!
On Windows you _cannot_ open a mmap for an empty file. Then, instead of the API returning a null pointer (0x00000000), it returns the very next address (0x00000001). That explains why we were seeing off-by-one alignment errors.
This PR:
- adds an error case on Windows platforms to prevent this from happening; using an empty mmap
- enables alignment assertion again on all platforms
- extended tests to test this specific case
=> Fix mmap on Windows

Cargo.toml
Sets the `qdrant` binary by default when using `cargo run` to avoid writing the more verbose `cargo run --bin qdrant`
=> Build: `cargo run --bin qdrant` -> `cargo run`

Cargo.lock, Cargo.toml, src/wal_inspector.rs
This PR adds a new minimal binary that decodes and displays the content of a WAL folder.
It can be useful during investigation.
Usage:
`cargo run --bin wal_inspector storage/collections/test-collection/0/wal/ `
~~Opening as a Draft because it might be considered a bit hacky for the time being.~~
=> Add WAL inspector binary

lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs
Simple and mmap vectos storages include quantization files to their files. Added same behaviour to appendable mmap
=> add quantization files to appendable mmap files

lib/segment/src/common/mmap_type.rs, lib/segment/src/vector_storage/mmap_vectors.rs
Continuation of <https://github.com/qdrant/qdrant/pull/1885>.
This removes `mlock` for mmap all together to simplifying the interface a bit. If we'd ever need it again we can simply revert or re-implement.
=> Remove mlock from mmap

lib/collection/src/shards/remote_shard.rs
This PR removes the "new" decoding limits on the internal gRPC clients.
This is the client side follow up on https://github.com/qdrant/qdrant/pull/1659
The fix was tested locally with `coach`.
I have applied a similar fix to our Rust client a few weeks ago https://github.com/qdrant/rust-client/pull/40
=> Remove max message decoding limit on internal gRPC client

openapi/tests/openapi_integration/test_basic_retrieve_api.py, openapi/tests/openapi_integration/test_basic_retrieve_api_on_disk.py, openapi/tests/openapi_integration/test_basic_retrieve_multivec_api.py, openapi/tests/openapi_integration/test_count.py, openapi/tests/openapi_integration/test_euclid_dist.py, openapi/tests/openapi_integration/test_filter.py, openapi/tests/openapi_integration/test_filter_values_count.py, openapi/tests/openapi_integration/test_fts.py, openapi/tests/openapi_integration/test_multicollection_reco.py, openapi/tests/openapi_integration/test_optional_vectors.py, openapi/tests/openapi_integration/test_service.py, openapi/tests/openapi_integration/test_snapshot.py, openapi/tests/openapi_integration/test_vector_config.py
Improve the performance of tests by reusing the setup for every test in the same file (where it makes sense). Also refactor to use loop and timeout where a simple `sleep` was used
Locally, the integration test suite duration went from 32.64s to 18.23s, hence the ~45% speedup
=> CI: make integration tests 45% faster

docs/redoc/master/openapi.json, lib/collection/src/operations/vector_ops.rs, openapi/tests/openapi_integration/test_optional_vectors.py, src/common/points.rs, src/tonic/api/points_common.rs
This flattens the point selector field for the delete vectors REST endpoint. This makes point selection [consistent](https://qdrant.tech/documentation/points/#set-payload) with other endpoints.
Before:
```json
{
"point_selector": { "points": [1, 2] },
"vectors": ["image"]
}
```
After:
```json
{
"points": [1, 2],
"vectors": ["image"]
}
```
Or using a filter:
```json
{
"filter": {},
"vectors": ["image"]
}
```
We can still change this interface because we haven't released a version with it yet.
=> Simplify/flatten point selection in delete vectors REST endpoint

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/shards/local_shard.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/segment_constructor/simple_segment_constructor.rs, lib/segment/tests/exact_search_test.rs, lib/segment/tests/filtrable_hnsw_test.rs, lib/segment/tests/fixtures/segment.rs, lib/segment/tests/hnsw_quantized_search_test.rs, lib/segment/tests/payload_index_test.rs
Implements <https://github.com/qdrant/qdrant/issues/1890#issuecomment-1548159690>. This is a quick and dirty hotfix for <https://github.com/qdrant/qdrant/issues/1890>.
For the temp segment, this delays storing the segment version until payload indices have been converted. If this conversion somehow fails, loading the segment is skipped on restart because the segment version is missing.
Is this approach good enough or do we want something better? And does this fix the issue on your machine?
Relevant snippet: https://github.com/qdrant/qdrant/blob/13185ef47d30066619db0b44651b2906a9b23524/lib/collection/src/collection_manager/optimizers/segment_optimizer.rs#L398-L432
If this approach is okay, it definitely needs a bit of polishing. But I'd like an opinion on this first before wasting time on …
=> Hotfix: possible loss of payload index configuration

docs/redoc/master/openapi.json, lib/segment/src/types.rs
Apparently pydantic thinks it is very smart
this fails :facepalm:
=> reorder conditions

lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs, lib/segment/src/payload_storage/query_checker.rs
Extends <https://github.com/qdrant/qdrant/pull/1935>.
This replaces
```rust
get_external_id: Box<dyn Fn(PointOffsetType) -> Option<PointIdType> + 'a>,
```
with
```rust
id_tracker: Option<&IdTrackerSS>,
```
to remove the boxed closure. Instead we pass a reference to ID tracker.
=> Add optional ID tracker to check_payload, remove boxed closure

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/grouping/group_by.rs, lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/inverted_index.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/index/field_index/numeric_index.rs, lib/segment/src/index/field_index/stat_tools.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/payload_storage/condition_checker.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/mod.rs, openapi/tests/openapi_integration/test_group.py
- Fix for the payload selector: 
- search request doesn't support nested payload selectors, but `group_by` should
- New logic only pre-selects top-level key, which might be a subject for possible further improvements
- additional `must-not` condition for re-search requests doesn't work with multiple payload values per field. It excludes too much
- had to introduce a new `except` match condition, which fixes the problem.
- as a bonus: `except` condition also available outside the groups
- test for reproducing the problem also included
=> Fixes for group-by

openapi/tests/requirements-freeze.txt
Fixes https://github.com/qdrant/qdrant/pull/1910.
Update the `scarlette` dependency to `v0.27.0`. This mitigates a [vulnerability](https://github.com/qdrant/qdrant/security/dependabot/41).
Originally suggested by dependabot [here](https://github.com/qdrant/qdrant/pull/1910), but ported to `dev` because this is not a high priority issue in our codebase. It is not used in production/release code.
=> Bump starlette from 0.26.1 to 0.27.0 in /openapi/tests

.gitignore, src/settings.rs
Includes <https://github.com/qdrant/qdrant/pull/1971>.
This reworks loading and merging of configuration files.
I've discussed this extensively with @agourlay in a call.
We figured there were a few problems with the previous implementation, mainly:
- there were unnecessary hard errors (if config files didn't exist)
- the load/merge order of configuration was wrong, a user specified configuration would be overwritten by `production.yaml`.
With this change, the configuration is now loaded and merged in the following manner:
1. Embedded base config (always complete)
2. File `config/config.yaml`
3. File `config/{env}.yaml`
4. File `config/local.yaml`
5. Config provided with `--config-path` (if set)
6. Environment variables
All files (2-5) are optional. Any properties in later configs, …
=> Rework settings/configuration loading

lib/collection/src/config.rs, lib/collection/src/operations/types.rs, lib/segment/src/types.rs, lib/storage/src/types.rs, src/settings.rs
Use `const fn` for serde defaults where possible to allow compile time evaluation.
=> Use const fn where possible for serde defaults

docker-compose-gen.sh, lib/collection/src/operations/types.rs, tools/generate_docker_compose_cluster.sh
_Edited by @timvisee:_
This adds a script to generate a Docker compose configuration to easily start a small cluster in Docker.
I've been using this a few times, so I decided to make it ready to merge into our main repo.
Example usage:
```bash
./tools/generate_docker_compose_cluster.sh 5 > docker-compose.yaml
docker-compose up
```
=> Add script to generate `docker-compose.yaml` for Qdrant cluster

Cargo.lock, Cargo.toml, lib/api/Cargo.toml
A patch release bumping Qdrant to v1.2.1.
=> Bump version to v1.2.1

tests/tls/docker-compose.yaml, tests/tls/tls_config.yaml
This simplifies the config usage in our TLS test a bit to only keep the properties we need.
This is now possible since <https://github.com/qdrant/qdrant/pull/1972> is merged.
=> Simplify TLS test config

docs/grpc/docs.md, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs
The current documentation is incorrect when using the distributed mode.
Align documentation for `shard_number` field in gRPC to the one for REST.
=> Fix gRPC doc for shard_number

Cargo.lock, Cargo.toml, docs/DEVELOPMENT.md, src/main.rs, src/tracing.rs
Add an optional `tracing` support with basic `tokio-console` and `tracing` integration.
__TODO:__
- (otherwise, it compiles fine, but panics at runtime, which is extremely annoying)
=> Add optional `tracing` support

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/common/mmap_type.rs
We had a problem with mmap on Windows, where an empty file would give us an unaligned pointer. We [added](https://github.com/qdrant/qdrant/blob/137def66508b2b3ae36821b6890d8af2a0d70ba1/lib/segment/src/common/mmap_type.rs#L452-L457) a Windows specific edge case to resolve this.
I've upstreamed this logic into the `memmap2` crate in this PR: https://github.com/RazrFalcon/memmap2-rs/pull/79
This PR updates the crate and removes our edge case handling, since it is now done externally. :tada: 
Related: https://github.com/qdrant/qdrant/pull/1873
=> Update memmap2 to remove Windows specific edge case

Cargo.lock, docs/redoc/master/openapi.json, lib/collection/Cargo.toml, lib/collection/src/lib.rs, lib/collection/src/lookup.rs, lib/collection/src/lookup/mod.rs, lib/collection/src/lookup/types.rs, lib/collection/tests/lookup_test.rs, lib/segment/src/data_types/groups.rs, lib/segment/src/types.rs
Adds the internal mechanism for retrieving points from another collection given a list of PseudoIds
- create new PseudoId type from GroupId
- impl try_from PseudoId to PointIdType
- create lookup_ids function
- add tests
=> Lookup internals

lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/wal.rs, lib/segment/src/segment.rs
WAL operates in _segments_. When `Wal::prefix_truncate` is called (during `SerdeWal::ack`), WAL is not truncated _precisely_ up to the `until_index`, but up to the nearest segment with `last_index` that is less-or-equal than `until_index`.
Consider the pseudo-graphic illustration of the WAL that was truncated up to index 35:
```
| -------- | -------- | ===='++++ | ++++++++ | ++++++++ | ++++++++ |
10         20         30    35    40         50         60         70
```
- `'` marks the index 35 that has been truncated-to
- `---` marks segments 10-30 that has been physically deleted
- `+++` marks segments 35-70 that are still valid
- and `===` marks part of segment 30-34, that is still physically present on disk, but that is "logically" deleted
This PR extends `SerdeWal` type to track the …
=> Extend `SerdeWal` to better track the last truncated-to WAL index (#1815)

.gitignore, lib/api/src/grpc/validate.rs, src/actix/certificate_helpers.rs, src/actix/mod.rs, src/main.rs
This improves error logging for TLS loading errors and errors that occur while starting REST and gRPC servers.
For example, if the REST server can't start because the TLS certificate file is missing, this is now shown:
```
[2023-05-31T15:13:03.093Z ERROR qdrant] Error while starting REST server: TLS file could not be opened: ./tls/localhost.pem
```
Before it simply `eprintln`ed a raw `io::Error` with no context it was relating to starting the REST or gRPC server.
=> Log better TLS and REST/gRPC start errors

lib/storage/src/content_manager/consensus_manager.rs, tests/consensus_tests/test_cluster_operation_coalescing.py
Follow up on https://github.com/qdrant/qdrant/pull/2003
The broadcast channel does not require to be bounded with a magic number as we know that only a single ACK message per operation is generated.
=> Cluster operation coalescing channel requires only one message

lib/segment/src/index/field_index/geo_hash.rs, lib/segment/src/index/field_index/stat_tools.rs, lib/segment/src/index/key_encoding.rs, lib/segment/src/madvise.rs, lib/segment/src/segment.rs, lib/segment/src/utils/tar.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/storage/src/content_manager/snapshots/mod.rs, src/main.rs, src/snapshots.rs
Fixes warnings pointed out by `cargo doc` as well as some typos. The adjusted links were not clickable prior to this change. The `madvise(2)` change removes an ambiguity between the manual reference and the module name: prior to this change, it would link to the `madvise` module rather than to the manpage.
There are some more warnings which concern mentioning private items in docstrings of public items but I think they can be safely ignored as the libraries are not public.
=> Fix warnings pointed out by `cargo doc`

lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/graph_links.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/segment.rs
Added `prefault_mmap_pages` method to the `GraphLinksMmap` type (and propagated it all the way up to `Segment` type).
=> Add `prefault_mmap_pages` method to the `GraphLinksMmap` (#1791)

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/collection/src/wal.rs, lib/storage/Cargo.toml
There is a strange case, when we create snapshot, it produces empty WAL.
It seems that empty WAL computes `last_index` incorrectly (it assumes that WAL with offset is never empty).
This incorrect API should be fixed in WAL crate, as it is the original cause of the problem.
Still, it might be beneficial to use min/max in qdrant side, just to avoid unnecessary panic.
=> Fix wal clamp

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection.rs, lib/collection/src/grouping/builder.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/lookup/mod.rs, lib/collection/src/lookup/types.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/tests/integration/lookup_test.rs, lib/storage/src/content_manager/toc.rs, openapi/tests/openapi_integration/test_group.py
Exposes the lookup feature in the Groups API, in both REST and gRPC interfaces
Builds on top of #1996 
=> Lookup: expose feature to REST and gRPC interfaces

openapi/tests/requirements-freeze.txt, openapi/tests/requirements.txt, tests/openapi_integration_test.sh
Fixes https://github.com/qdrant/qdrant/pull/1942.
Update the `requests` dependency to `v2.31.0`. This mitigates a [vulnerability](https://github.com/qdrant/qdrant/security/dependabot/42).
Originally suggested by dependabot [here](https://github.com/qdrant/qdrant/pull/1942), but ported to `dev` because this is not a high priority issue in our codebase. It is not used in production/release code.
=> Bump requests from 2.28.1 to 2.31.0 in /openapi/tests

src/actix/mod.rs
This PR improves the error reporting for user missing the static directory serving the web UI.
1. only one error is displayed instead of one per actix runtime
2. the static file serving is not enabled if the static folder does not exist
e.g.
Before this PR
```
[2023-06-08T09:00:43.777Z ERROR actix_files::files] Specified path is not a directory: "./static"
[2023-06-08T09:00:43.793Z ERROR actix_files::files] Specified path is not a directory: "./static"
[2023-06-08T09:00:43.809Z ERROR actix_files::files] Specified path is not a directory: "./static"
[2023-06-08T09:00:43.827Z ERROR actix_files::files] Specified path is not a directory: "./static"
[2023-06-08T09:00:43.845Z ERROR actix_files::files] Specified path is not a directory: "./static"
[2023-06-08T09:00:43.862Z ERROR …
```
=> Better error reporting for missing static folder

lib/collection/src/collection_manager/segments_searcher.rs, lib/segment/benches/conditional_search.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/payload_index_base.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/query_estimator.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/segment.rs, lib/segment/tests/integration/batch_search_test.rs, lib/segment/tests/integration/main.rs, lib/segment/tests/integration/nested_filtering_test.rs, lib/segment/tests/integration/payload_index_test.rs
Current behavior:
If there is a batch request with multiple identical filtering conditions, executor tried to re-use filtering results.
The problem is, that filtering result is the iterator, so when the first results are prepared, the second request is left with empty iterator. Which results in empty search result for all sub-requests except for the first one.
This PR:
Replaces iterator with owned vector. Which is fine, because:
- it fixes the double usage of iterator
- In previous implementation "iterator" was, in fact, just collected vector in most cases anyway. And in other case potential collect of the vector is not the critical part of the execution.
=> Fix batch request with duplicated filter

lib/collection/src/shards/replica_set.rs, tests/consensus_tests/test_write_ordering.py
`WriteOrdering::Medium` and `WriteOrdering::Strong` were swapped 🤡
Original intention was:
- to make `WriteOrdering::Medium` to order writes through _some_ alive node
- which will make it always available, but may lead to some inconsistencies in some rare cases
- and `WriteOrdering::Strong` to always order through a _single_ node
- which will make writes unavailable, if that node is down, but should prevent any possible inconcistencies
Seems like something got mixed-up or miscommunicated during implementation, but luckily no one (but me) noticed. 😎
(Btw, we can, kinda, expect failures/users complaining after the fix, when `WriteOrdering::Strong` would start failing request.... 🥲)
2. [x] Have you formatted your code locally using `cargo fmt` command …
=> Fix `WriteOrdering::Medium` and `WriteOrdering::Strong` semantics

lib/storage/src/content_manager/toc.rs, src/actix/api/snapshot_api.rs
This PR fixes a bug happening during the upload of a snapshot.
```
curl -X POST 'http://localhost:6343/collections/bfb_stress/snapshots/upload'
-H 'Content-Type:multipart/form-data' 
-F 'snapshot=@bfb_stress-7064541537839969-2023-06-12-14-34-49.snapshot'
{"status":{"error":"Service internal error: Persist error: failed to persist temporary file: No such file or directory (os error 2)"},"time":0.019918391}
```
Persisting the snapshot locally fails if the the node is not aware of this collection because the snapshot directory for the collection does not exist. 
This folder is either created either when the collection is created or when applying a collection snapshot.
=> Create snapshot dir. during upload if it does not exist

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/vector_storage/async_io.rs, lib/segment/src/vector_storage/async_io_mock.rs, lib/segment/src/vector_storage/async_raw_scorer.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/mmap_vectors.rs, lib/segment/src/vector_storage/mod.rs, lib/segment/src/vector_storage/quantized/quantized_raw_scorer.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/tests/async_raw_scorer.rs, lib/segment/src/vector_storage/tests/mod.rs, lib/storage/src/types.rs, lib/storage/tests/integration/alias_tests.rs, src/main.rs
Based on @ffuugoo's overview and @timvisee's experiments:
It looks like io_uring is very promising for speeding-up the slow-disk deployments.
tokio implementation mounts on the current thread, so creating a uring runtime should be cheap enough, in case of network-mounted disk.
This PR introduces an AsyncRawScorer, which utilizes the uring for scoring points.
Pros:
- Uses same file layout as the MmapVectors, can be switched dynamically
- Can fallback to mmap if uring is not available
- Disk cache is shared between mmap and using
Limitations:
- Due to `RC` in tokio-uring File, we need to open vector files on each request. Hopefully, it is cheap
- Parallel reads only achieved for given list of points, e.g. on re-scroing of filtered selection, scoring nodes in HNSW, oversampling, e.t.c. 
- …
=> WIP: Async uring vector storage

lib/segment/src/vector_storage/async_raw_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_raw_scorer.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_vector_storage.rs
This PR changes the default state of deletion for points. Before, a point having no delete flag was considered available. This changes it to consider it as deleted.
Note that this doesn't change the default deletion state for vectors, just for points.
This improves a problematic situation that could occur when the ID tracker is flushed while storage is not. In that case we could have points in storage that don't have a corresponding point ID mapped. These leaked vectors caused issues.
More specifically, this fixes a bug where leaked vectors would reach the final stage in a segment producing the warnings below, while the scorers shouldn't consider the vectors at all.
```
...
[2023-06-12T14:20:03.582Z WARN  segment::segment] Point with internal ID 71851 not found in id tracker, skipping …
```
=> Assume points with no mapping/delete flag are deleted

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs
Extension to <https://github.com/qdrant/qdrant/pull/2061>.
This PR improves counting vectors in `SegmentInfo`.
Before we estimated the vector count based on the number of points. Now we actually count.
=> Improve counting vectors in `SegmentInfo`

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/shards/local_shard.rs, lib/segment/src/common/mmap_ops.rs
This PR adds a few calls to `Segment::prefault_mmap_pages`:
- on `Segment` load
- and after `Segment` optimization
=> Enable `Segment::prefault_mmap_pages` after load and optimization (#1791)

lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/index/field_index/numeric_index.rs, lib/segment/src/index/query_optimization/condition_converter.rs, lib/segment/tests/integration/payload_index_test.rs
- Make is_empty take advantage of the index when not empty.
- ~Make is_null take advantage of the index when not null~
For both scenarios it adds an overhead of checking both the index and the payload when it is actually empty/null, so these changes improve performance only when the negated condition is true.
=> Optimize `is_empty`

Cargo.lock, Cargo.toml, lib/api/src/grpc/transport_channel_pool.rs, src/tonic/mod.rs
Works on <https://github.com/qdrant/qdrant/issues/1907>.
This PR increases the limit for HTTP2 reset streams in our internal gRPC communication.
This is one of the steps we have to make in an attempt to minimize GOAWAY/ENHANCE_YOUR_CALM errors in internal cluster communication breaking cluster consensus. This likely doesn't solve it completely, but significantly minimizes the chance of it happening.
Future PRs will add to this fix, further minimizing the chance of this happening. See the future list of tasks below.
More info here: https://github.com/qdrant/qdrant/issues/1907#issuecomment-1564234664
- Add [`reset_stream_duration`](https://docs.rs/h2/latest/h2/server/struct.Builder.html#method.reset_stream_duration) property
- Decrease stream reset duration from 30 seconds to 5 (?)
- Remove …
=> Increase HTTP2 reset stream limit for internal gRPC

.github/workflows/integration-tests.yml
Change Github action setup to debug the following test https://github.com/qdrant/qdrant/actions/runs/5292158522/jobs/9578689729?pr=2083
This PR does two important things:
- set explicit shorter cancellation timeout
- enable pushing logs on cancellation
=> Cancel sooner consensus test and upload logs

lib/segment/src/vector_storage/memmap_vector_storage.rs
The `deleted.dat` is currently missing in memmap storage snapshots. This is problematic.
=> Fix deleted.dat missing in mmap storage snapshot

lib/segment/src/vector_storage/mmap_vectors.rs
Fixes the following warning on non-Linux platforms:
```
warning: field `uring_reader` is never read
--> lib\segment\src\vector_storage\mmap_vectors.rs:38:5
|
30 | pub struct MmapVectors {
|            ----------- field in this struct
...
38 |     uring_reader: Mutex<UringReader>,
|     ^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
=> Fix unused io_uring warning on non-Linux platforms

.gitignore, config/config.yaml, lib/collection/src/collection.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/integration/snapshot_recovery_test.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/index/field_index/full_text_index/tests/mod.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/map_index.rs, lib/segment/src/index/field_index/numeric_index.rs, lib/segment/src/index/hnsw_index/graph_links.rs, lib/segment/src/segment.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, lib/storage/tests/integration/alias_tests.rs
This PR is a proposal to solve issue 1905. It allows to use a tmp_path configuration to be used instead of the current storage. If not specified, it will use storage as default.
/claim #1905
=> Configurable location of temporary snapshot files

src/consensus.rs
This PR refactor consensus thread a bit, so that consensus thread:
- spawns an async worker for each peer, that sends messages to the peer sequentially, one-by-one
- and then forwards each message to the respective worker
- instead of spawning individual message-sending-tasks onto the runtime directly, without any synchronization/serialization between separate tasks/messages
__TODO:__
- ~~[ ] optimize `RaftMessageSender` to skip "outdated" heartbeat messages~~
- instead of sending every message one-by-one, we should do `try_recv` until we either get a non-heartbeat message (and then send it immediately and continue), or until we pulled all messages from the channel (and then we could only send the last heartbeat message pulled from the channel)
- ~~can~~ __have to__ be done in a separate …
=> Refactor consensus thread to send raft messages sequentially

lib/segment/src/common/mod.rs, lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs, lib/segment/src/common/rocksdb_wrapper.rs, lib/segment/src/id_tracker/simple_id_tracker.rs
fix flush ordering of the removed points during copy-on-write
=> delete points from id tracker on flush only

lib/collection/src/collection.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/src/tests/wal_recovery_test.rs, lib/collection/tests/integration/collection_restore_test.rs, lib/collection/tests/integration/collection_test.rs, lib/collection/tests/integration/grouping_test.rs, lib/collection/tests/integration/lookup_test.rs, lib/collection/tests/integration/multi_vec_test.rs, lib/collection/tests/integration/pagination_test.rs, lib/collection/tests/integration/snapshot_recovery_test.rs, lib/storage/src/content_manager/toc.rs
This PR removes the `before_drop` mechanism.
It was introduced as a workaround to shutdown collection at the time where we had one run per collection.
The remaining complexity is due to performing a asynchronous operations within the `Drop` which is synchronous.
A few important things:
- changing to `#[tokio::test(flavor = "multi_thread")]` is required in a few test to avoid deadlocks.
- it is not possible to spawn an async. task during `drop` as the &self reference would escape 
- previously before_drop was run in parallel for each shard in a pure async. fashion, I am not sure the new implementation is as efficient
=> Remove before_drop mechanism

tools/missed_cherry_picks.sh
This allows us to easily detect cherry-picks we missed from `dev` to `master` on our release branch.
For example:
```
$ ./tools/missed_cherry_picks.sh
286ca9f5e4230bed1a1c726cbc2d93b7b8aa0f25 0.11.0 cherry picks (#1174)
93a4499859b31cea94dbad0ee4df8b7aeea407a8 Update: unmaintained crate memmap -> memmap2 (#559) (#1160)
a0b6fa81b75c1695766c056650e3e8d8b6ab97c5 Consensus q n a (#1169)
017df525289fad13e129a58137fad028cc34ded4 Use less ram for id tracker (#1176)
383100ebb6e60328f7bf1aa93b80ecd6c82d4de1 remove suggesting changes in replications on replication factor change (#1177)
7916f01fa4abe5a03fe0ce011b1d788395f3bc3b Migrate from OpenSSL to Rustls (#1865)
8342288e1f2bc9b65d96d74c5946eb94a53acc6b Fix documentation links (#2000)
d67bf1ce3742e9b5d61dda2c4c3274686dfce5a7 Update memmap2 to …
```
=> Add script to list commits that have yet to be picked into master

lib/storage/src/content_manager/consensus_manager.rs
Playing with `lockbud` (again) I got the following warning regarding a possible deadlock in the consensus manager.
```json
[
{
"ConflictLock": {
"bug_kind": "ConflictLock",
"possibility": "Possibly",
"diagnosis": [
{
"first_lock_type": "ParkingLotRead(content_manager::consensus::persistent::Persistent)",
"first_lock_span": "lib/storage/src/content_manager/consensus_manager.rs:699:13: 699:23 (#0)",
"second_lock_type": "ParkingLotMutex(content_manager::consensus::consensus_wal::ConsensusOpWal)",
"second_lock_span": "lib/storage/src/content_manager/consensus_manager.rs:704:12: 704:27 (#0)",
"callchains": []
},
{
"first_lock_type": "ParkingLotMutex(content_manager::consensus::consensus_wal::ConsensusOpWal)",
"first_lock_span": "lib/storage/src/content_manager/consensus_manager.rs:716:27: …
```
=> Prevent deadlock in Consensus Manager

lib/collection/src/shards/mod.rs, lib/collection/src/shards/shard_versioning.rs, lib/storage/src/content_manager/toc.rs
related issue: https://github.com/qdrant/qdrant/issues/2158
What happened:
If there are multiple parallel requests to create the same collection - it might create problem of parallel writing to the same directory:
- collections HashMap only updated with ready-made collection
- It is required to write files to disk in order to create collection
- We can't move already created collection, as there are in-memory state which assumes correct path
As a result, multiple parallel requests triggered (deprecated) shards versioning logic.
Solution:
- Force create_collection API to be sequential with tokio Mutex
- Remove deprecated logic of shard versioning 
Possible alternatieves solutions:
- Associate mutex with collection names, so that we can create multiple collections in parallel
Decided to go …
=> add create-collection lock + remove shard versioning function

lib/segment/src/index/hnsw_index/hnsw.rs
Browsing the code I realized only `.unfiltered_plain` was being selected due to using the same `plain_search` bool as the line up. I guess this change was the intended behavior?
=> use correct condition to select duration measurer

lib/storage/src/content_manager/toc.rs, lib/storage/tests/integration/alias_tests.rs, src/consensus.rs, src/main.rs, src/tonic/mod.rs
As discussed in #1316 there is a segmentation fault when the application is exited. It happens because RocksDB relies on global static variables which are removed when `main()` is returned. Therefore, the application should ensure no ongoing RocksDB operations are in flight when exiting. This PR proposes one simple change that fixes the issue (to the best of my ability to test this non-deterministic issue).
Qdrant already does a lot to gather all background thread handles and join them at the end of `main()`. Unfortunately, `TableOfContent` which holds the `Runtime` cannot be easily dropped from the `main()` because it is behind `Arc`. `main()` drops `Arc`, but it just decrements the counter not doing anything to the `ToC` itself.
This PR moves ownership of all the `Runtime` back to …
=> TableOfContent now accepts Handle, not Runtime

lib/collection/src/collection_manager/segments_updater.rs, lib/collection/src/operations/types.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/segment.rs
Fixes: https://github.com/qdrant/qdrant/issues/2184
Introduces special type of internal error, which prevents panic and handled properly by sync API.
=> handle inconsistent vector storage in sync operation

lib/storage/src/content_manager/toc.rs, lib/storage/tests/integration/alias_tests.rs, src/consensus.rs, src/main.rs, src/tonic/mod.rs
This PR unfortunately reverts the great work done in https://github.com/qdrant/qdrant/pull/2096
This is necessary because shutting down an instance with collections currently yields the following logs:
```
[2023-07-03T09:44:12.144Z WARN  collection::shards::local_shard] Update workers failed with: Service internal error: task 395 was cancelled
[2023-07-03T09:44:12.148Z INFO  wal] segment creator shutting down
[2023-07-03T09:44:12.149Z WARN  collection::shards::local_shard] Error sending stop signal to update handler: channel closed
[2023-07-03T09:44:12.149Z WARN  collection::update_handler] Failed to stop flush worker as it is already stopped.
[2023-07-03T09:44:12.149Z WARN  collection::shards::local_shard] Update workers failed with: Service internal error: task 123 was cancelled …
```
=> Revert "TableOfContent now accepts Handle, not Runtime (#2096)"

src/consensus.rs
Fixes duplicate invocation missed in <https://github.com/qdrant/qdrant/pull/2191>.
=> Remove duplicate on_consensus_stopped call

lib/collection/src/collection_manager/fixtures.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/entry/entry_point.rs, lib/segment/src/fixtures/segment_fixtures.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/simple_segment_constructor.rs, lib/segment/tests/integration/batch_search_test.rs, lib/segment/tests/integration/disbalanced_vectors_test.rs, lib/segment/tests/integration/exact_search_test.rs, lib/segment/tests/integration/fail_recovery_test.rs, lib/segment/tests/integration/filtrable_hnsw_test.rs, lib/segment/tests/integration/fixtures/segment.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs, lib/segment/tests/integration/payload_index_test.rs, lib/segment/tests/integration/segment_builder_test.rs, lib/segment/tests/integration/segment_tests.rs, openapi/tests/openapi_integration/test_optional_vectors.py
This PR is related to issue https://github.com/qdrant/qdrant/issues/2202.
This PR adds missed `distance.preprocess` to `segment.update_vector`. Also, this PR optimizes preprocessing and avoids named vector map recreation.
It's not a full solution. Because users may have broke non-normalized vectors, it's important to add storage migration to next release. I propose to do it in custom codebooks feature with also requires storage migration.
=> Add missed vector preprocess

lib/collection/src/operations/validation.rs
This was introduced when developing the grouping feature, but is no longer necessary
=> remove unused "no_bracket_syntax" error code

src/actix/mod.rs
It is sometimes not straightforward to know which HTTP port is used when running several servers locally.
This small PR prints the HTTP server port at startup the same way it is done  for the gRPC server.
=> Log HTTP server port at startup

lib/api/build.rs, lib/api/src/grpc/qdrant.rs
Removes unused Serialize derives which _I think_ were used for validating before, but are not needed anymore
=> Remove unused Serialize derive in `build.rs`

lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/segment/src/id_tracker/simple_id_tracker.rs
While looking for an `unimplemented` error I found two call sites without messages.
This PR adds messages to make those explicit if they ever were to happen.
=> Add message to unimplemented!

lib/collection/src/common/stoppable_task.rs, lib/collection/src/tests/mod.rs, lib/collection/src/update_handler.rs
Fix live-lock during optimizers stop. The fix is kinda ugly and I'd like to further rework/improve it, but at least it should fix the lock issue for now.
=> Fix optimizers stop lock

lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/tests/integration/payload_index_test.rs
This PR fixes a bug appearing when trying to change the Schema type of an index payload key.
When trying to set a payload index key, the current implementation skips both index build and index config persistence if the payload key is already registered.
This is an issue because it silently creates inconsistent index data and configuration:
- the new type value is accepted in memory thus visible to the world
- the indexer is not triggered thus generating wrong point count
- the index configuration is not persisted thus it won't survive a restart creating inconsistent loaded data
This PR fixes the issue and still detects the no-op case when the key was already present AND the schema identical.
=> Fix set payload index to handle type change

.github/workflows/release-artifacts.yml
The macOS binary release job failed on `v1.3.0`, this attempts to fix that.
Failed job: https://github.com/qdrant/qdrant/actions/runs/5359388215/jobs/9722912379
This also changes the release trigger from `created` to `published` to also trigger when drafted releases are published.
=> Fix macOS binary release job

lib/collection/src/collection.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard_operations.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_trait.rs, src/common/helpers.rs
The current implementation of `scroll_by` at the collection level is performing potential heavy blocking I/O operation on the caller's Tokio runtime one segment at a time.
Scrolling can use a filter which can in turn require a full scan or an index traversal.
The caller's runtime is generally the actix runtime or the gRPC runtime which is not ideal because in a cooperative scheduling, tasks are supposed to yield often to play nicely with others.
This PR does two thing:
- run `read_filtered` on the search runtime
- execute segment read in parallel
I have added support for scrolling in BFB https://github.com/qdrant/bfb/pull/10
Using my local system with the following data setup
```bash
cargo run -r -- --segments 4 --num-vectors 1000000 --keywords 10000 --on-disk-payload --on-disk-vectors …
```
=> Non blocking Scroll and parallel segments runs

lib/collection/benches/batch_search_bench.rs
This is particularly useful for microbenchmarks since 1) this cost shouldn't affect benchmark results
2) memory allocations are the largest source of measurement noise
=> [bench] Reserve vector storage to avoid reallocs.

README.md
The LlamaIndex link in our README is broken. This changes it to the [proper](https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/QdrantIndexDemo.html) one.
I'll cherry-pick this into master once merged.
=> Fix LlamaIndex integration link in README

lib/collection/src/collection.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs
Fixes: https://github.com/qdrant/qdrant/issues/2247
Caused by: https://github.com/qdrant/qdrant/pull/2221
Reason: update runtime was used to do `spawn_blocking` in scroll requests, but update runtime only have capacity for one blocking task at a time. Therefore it got stuck (not a deadlock, but same effect)
=> use search runtime to do reads in shard transfer

tests/consensus_tests/downscale_cluster.py
Tiny PR adding a missing test assertion to the downscaling cluster test.
The absence of assertion created confusion when we changed the transfer API semantic in https://github.com/qdrant/qdrant/pull/2246
=> Add missing assertion to shard transfer test

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, lib/segment/src/common/utils.rs, lib/segment/src/index/field_index/histogram.rs
In Contributing document we suggest contributors use `cargo fmt` but we use `cargo +nightly fmt --all` in our `.rusty-hook.toml`. So better to align them.
Also fixed some clippy issues. But not all of them. Because one of the issues requires a deep look and I will fix it later.
=> Align the fmt command with `.rusty-hook.toml`

lib/collection/src/common/stoppable_task.rs
This improves the stoppable task test which was flaky. It loosens the test requirements a bit to make it less time sensitive. This also adds a test for 64 concurrent stoppable tasks.
We'll have to see if this consistently succeeds on CI, but can easily tweak this again if not.
=> Improve flaky stopable task test

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/build.rs, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/src/operations/validation.rs, lib/collection/tests/integration/collection_test.rs, lib/segment/src/index/field_index/full_text_index/inverted_index.rs, lib/segment/src/index/field_index/full_text_index/text_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/numeric_index.rs, lib/segment/src/index/query_estimator.rs, lib/segment/src/types.rs, lib/segment/tests/integration/payload_index_test.rs
This is one of a series of commits for the new feature Geo Filter by Polygon(https://github.com/qdrant/qdrant/issues/795). In this commit, a new proto interface called GeoPolygon is introduced, along with validation fn and conversion functions to/from internal struct GeoPolygon. Additionally, an integration test is included as part of this commit.
=> Add geo_polygon filter to proto interface, complete conversion fn, and add an integration test

openapi/tests/Dockerfile, openapi/tests/run_docker.sh
Apparently some dependencies don't build on alpine anymore
=> fix python scripts ci

lib/collection/src/common/stoppable_task.rs
Trying the fix the quite the annoying error on CI for MacOS
https://github.com/qdrant/qdrant/actions/runs/5573707401/jobs/10181358330#step:6:119
Following inspiration from https://github.com/qdrant/qdrant/pull/2261
```
failures:
---- common::stoppable_task::tests::test_task_stop stdout ----
thread 'common::stoppable_task::tests::test_task_stop' panicked at 'Stoppable task should have count between [5, 25], but it is 4', lib/collection/src/common/stoppable_task.rs:107:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
common::stoppable_task::tests::test_task_stop
```
=> Try to fix flaky test_task_stop

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/build.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/mod.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/collection_state.rs, lib/collection/src/operations/config_diff.rs, lib/collection/src/optimizers_builder.rs, lib/segment/src/types.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, openapi/tests/openapi_integration/test_collection_update.py
Tracking issue: <https://github.com/qdrant/qdrant/issues/2088>
Adds support for changing the HNSW configuration of an existing collection.
This now allows the update HNSW parameters through the [collection update](https://qdrant.tech/documentation/concepts/collections/#update-collection-parameters) endpoint. To update segments that already have an HNSW with the old parameters, a new configuration mismatch optimizer is added. The optimizer will pick these segments up and optimize them again with the new parameters.
Example API call:
```
PATCH /collections/{collection_name}
{
"hnsw_config": {
"m": 8,
"ef_construct": 50
}
}
```
This change can be very useful for users to experiment with different HNSW configurations, because it can now be changed at any time without recreating the whole …
=> Update collection: HNSW config

lib/segment/src/common/mod.rs, lib/segment/src/common/vector_utils.rs, lib/segment/src/index/hnsw_index/graph_links.rs, lib/segment/src/vector_storage/chunked_vectors.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs
This PR fixes usage of `try_reserve_exact` function in chunked vectors which leads to over-allocation.
Rust really should allow specifying param names during function calls.
This naming is very confusing, no wonder this happened.
Also renamed `try_reserve_exact` -> `try_reserve_size` for custom method to avoid mixing semantics.
=> fix usage of try_reserve_exact

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/segment/src/entry/entry_point.rs
Deduplication of points creates large HashMap<PointIdType, (SegmentId, SeqNumberType)> with points from all segments in shard. This map can be large and OOM was catched on laion dataset.
This PR is a reimplementation of deduplication with avoiding maps with points. Also, it can be more efficient because a point version is requested from the segment only when points with the same ID were found.
Unit test for deduplication is already presented.
2. [ ] Have you formatted your code locally using `cargo fmt` command prior to submission?
=> Dedup without large hashmap

lib/collection/src/optimizers_builder.rs, lib/collection/src/shards/local_shard.rs
Fixes https://github.com/qdrant/qdrant/issues/2317.
If qdrant is stopped while indexing, temp segment will not be removed. I propose to clear temp directory while local shard loading.
=> clear temp segments directory while shard loading

.gitignore
I'm going to close this PR https://github.com/qdrant/qdrant/pull/2172
Because we don't commit top-level dev files like `.idea` os `.vscode`. Also This PR is not compatible with Windows, without windows, devcontrainers don't achieve cross-platform development under docker. Also devcontainers as technology is raw and under beta.
But for users who actually uses devcontainers I propose to add devcontainers to gitignore to make more comfortable work under devcontainers
2. [ ] Have you formatted your code locally using `cargo fmt` command prior to submission?
=> add devcontainers to gitignore

docs/redoc/master/openapi.json, lib/collection/src/collection.rs, lib/collection/src/config.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, openapi/tests/openapi_integration/test_collection_update.py, openapi/tests/openapi_integration/test_collection_update_multivec.py
_Edited by @timvisee_
Fixes for <https://github.com/qdrant/qdrant/pull/2087>. Tracking issue: https://github.com/qdrant/qdrant/issues/2088
In short, this:
- adds integration test for multi vector config param updates (thanks @generall !)
- removes ability to update unnamed vector params from REST API
- add vector name validation to update collection endpoint
The core issue this fixes can be summarized like this:
- the REST API accepted both unnamed and named vector variants for updating vector parameters
- unnamed and named variants are untagged, and selected based on contents
- all parameters are optional and have default values
- unknown fields are allowed in the request object and simply ignored
Because of that, a request object can always be deserialized as both variants, because for …
=> Fix for updating vector-specific config params

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/build.rs, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/src/collection.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/config.rs, lib/collection/src/operations/config_diff.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/segment/src/types.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/conversions.rs, lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/toc.rs, openapi/tests/openapi_integration/test_collection_update.py, openapi/tests/openapi_integration/test_collection_update_multivec.py
Depends on <https://github.com/qdrant/qdrant/pull/2087>. Tracking issue: <https://github.com/qdrant/qdrant/issues/2088>
Adds support for changing the quantization configurations of an existing collection. This is implemented both for the collection and vector level.
Example API call to enable scalar quantization for all vectors:
```
PATCH /collections/{collection_name}
{
"quantization_config": {
"scalar": {
"type": "int8",
"quantile": 0.99,
"always_ram": true
}
}
}
```
Example API call to enable product quantization for `myvector`:
```
PATCH /collections/{collection_name}
{
"vectors": {
"myvector": {
"quantization_config": {
"product": {
"compression": "x16",
"always_ram": true
}
}
}
}
}
```
2. [x] Have you formatted your code locally using `cargo …
=> Update collection: quantization config

lib/storage/src/content_manager/consensus/persistent.rs, lib/storage/src/content_manager/errors.rs
`raft_state` file have a valuable information about consensus. It might be required to change some parameters for debug purposes.
It is much simpler to edit JSON. 
Serialization overhead considered negligible.
This PR will migrate `raft_state` into `raft_state.json`, while keeping backward compatibility with the original file
=> Migrate `raft_state` from cbor to JSON

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/config.rs, lib/collection/src/operations/config_diff.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/segment/src/types.rs, openapi/tests/openapi_integration/test_collection_update.py, openapi/tests/openapi_integration/test_collection_update_multivec.py
Depends on <https://github.com/qdrant/qdrant/pull/2090>. Tracking issue: <https://github.com/qdrant/qdrant/issues/2088>
Adds support for changing the `on_disk` and `on_disk_payload` flags of an existing collection.
Example API call to enable `on_disk` for `myvector`:
```
PATCH /collections/{collection_name}
{
"vectors": {
"myvector": {
"on_disk": true,
}
}
}
```
=> update collection: on_disk parameters

.codespellrc, src/consensus.rs
Continuation of #2115.
Heartbeat is the most basic message type in Raft. It's the message that carries only the "common metadata" without any payload. And any other message carries the same basic info as the heartbeat message.
Considering, that any message carries the same basic info, any later message "outdates"/"overwrites" any earlier heartbeat, so it's a reasonable optimization to try to skip sending "outdated" heartbeats if multiple pending messages have been pushed into `RaftMessageSender`'s queue (which may happen if, e.g., there were some network or general slowdown and `RaftMessageSender` "lagged behind" on processing the queue).
The rules for this are simple:
- `RaftMessageSender` picks a message to be sent from the queue _without awaiting_ (e.g., using `try_recv`)
- if the …
=> Skip outdated Raft heartbeats

lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs
Fix bug https://github.com/qdrant/qdrant/issues/2404
After changing `memmap_threshold` value, vector storage is going to be mmaped but without `on_disk` flag. Infinity loop appears in config mismatch optimizer. Vector storage is mmaped but no mention of `on_disk` flag in collection parameters being `false`. After segment optimization, vector storage is still mmaped but `on_disk` flag is still absent.
=> Fix infinite reindexing after mmap threshold patching

lib/storage/src/content_manager/snapshots/download.rs, openapi/tests/openapi_integration/test_snapshot.py
Fixes <https://github.com/qdrant/qdrant/issues/2412>.
Fixes incorrect `file://` URI handling in snapshot recovery logic. This now returns a proper HTTP 400 error when an invalid location is given.
Non existent path:
```json
curl -v -X PUT --header 'Content-Type: application/json' --data '{"location": "file:///whatever.snapshot"}' http://localhost:6333/collections/whatever/snapshots/recover
{"status":{"error":"Bad request: Snapshot file \"/whatever.snapshot\" does not exist"},"time":0.000361689}
curl -v -X PUT --header 'Content-Type: application/json' --data '{"location": "file://localhost/whatever.snapshot"}' http://localhost:6333/collections/whatever/snapshots/recover
{"status":{"error":"Bad request: Snapshot file \"/whatever.snapshot\" does not exist"},"time":0.000361689}
```
Invalid …
=> Fix incorrect file URI handling in snapshot recovery

src/actix/api_key.rs, src/actix/mod.rs
Fixes <https://github.com/qdrant/qdrant/issues/2401>.
This whitelists the root endpoint (`/`) to not require an API key.
It fixes the [readiness probe](https://github.com/qdrant/qdrant-helm/blob/3b360aec89573262ae4dfb4e45357a77816c8bee/templates/statefulset.yaml#L67-L83) in [our](https://github.com/qdrant/qdrant-helm/tree/main) helm chart when an API key is used.
As a bonus this enriches our internal interface a bit for whitelisting paths.
=> Whitelist root endpoint to not require API key

lib/segment/src/index/field_index/map_index.rs
Shared keyword strings was introduced in https://github.com/qdrant/qdrant/pull/2388.
Shared keywords are used to avoid string duplication in bitmap. But thanks to @generall advice, we can use this mechanism also for avoiding string duplications between different points. In this PR we are reusing equal strings and allocating memory actually for unique strings for the whole map index.
=> Share keyword strings between points

Cargo.lock, Cargo.toml, config/development.yaml, docs/DEVELOPMENT.md, src/consensus.rs, src/main.rs, src/startup.rs, src/tracing.rs
This PR replaces `env_logger` with `tracing`/`tracing-subscriber`/`tracing-log` as our `log` backend (and also removes half of the custom features added in #2187).
(Currently based on top of #2187. Would be rebased onto `dev` once #2187 is merged.)
__TODO:__
- There's practically no downside to leaving `tracing` optional in `lib/*` crates, so I crossed it out.
__Further Improvements:__
- Add API to change log-level/filters when Qdrant is already running (#2383)
- should be pretty trivial to do with [`tracing_subscriber::reload`]
- Add configuration parameter to [select "span events" to be printed][with-span-events]
- (and an API to change this in runtime)
- span events are rather verbose to enable them by default, but they are _extremely_ useful for debugging
- adding configuration …
=> Replace `env_logger` with `tracing`

docs/grpc/docs.md, lib/api/src/grpc/proto/qdrant.proto, lib/api/src/grpc/proto/qdrant_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/transfer/shard_transfer.rs, src/consensus.rs, src/tonic/mod.rs, tests/basic_grpc_test.sh, tests/basic_internal_grpc_test.sh, tests/integration-tests.sh
Tracking issue: https://github.com/qdrant/qdrant/issues/2432
This adds an internal gRPC call so a node can request the HTTP port of some other node.
This is one of the building blocks to achieve shard snapshot transfers.
```bash
$docker_grpcurl $QDRANT_HOST qdrant.QdrantInternal/GetHttpPort | jq
{
"port": 6333,
}
```
Should a user be able to configure a custom HTTP port for internal communication? Or should the user be able to disable this HTTP port for internal use all together? This may be useful for specialized cluster configurations where the HTTP is not forwarded, or bound to a different port.
_A: not needed right now_ …
=> Add internal gRPC call to request remote HTTP port

.github/workflows/rust-lint.yml, Cargo.lock, Cargo.toml, Dockerfile, src/actix/api/service_api.rs, src/common/mod.rs, src/common/stacktrace.rs, src/main.rs
This PR introduces a debug API, which returns stacktrace of all threads in Qdrant - `/stacktrace`.
This API have some limitations:
- it works only on Linux
- requires dynamically linked lib to work (libunwind8)
- the size of the stack is limited and I didn't find a way to configure it
Cause of those limitations, this API:
- disabled in OpenAPI on-purpose
- feature-flagged (but enabled in Docker by default)
Hopefully will be useful for further bug-hunting
=> Stacktrace API

config/config.yaml, config/development.yaml, config/production.yaml, src/settings.rs
It seems the `debug` flag is completely unused and I have no re-collection what it used to do.
This PR proposes to simply remove it.
=> Remove unused debug setting

tools/sync-web-ui.sh
Updates `sync-web-ui.sh` to remove the downloaded `dist-qdrant.zip` file after unzipping it, as it is not needed further and requires excluding it from git if not removed.
=> sync-web-ui.sh: Remove dist zip after unzipping it

lib/segment/tests/integration/hnsw_quantized_search_test.rs
Fixes https://github.com/qdrant/qdrant/issues/2486
I changed the check with the fact that quantization is not exact. Oversampling can produce a worse score because of a lack of quantization accuracy. Also changed random from seed for stability on CI.
=> fix flaky oversampling test

.github/dependabot.yml
The daily update of Rust dependencies is creating a bit too much churn for my taste.
I propose to set it up to once a week in order to decrease the noise during the week and possibly batch several updates together (clap, serde, anyhow etc...)
This might have to be pushed to master to take effect.
=> Weekly dependabot update for cargo

Cargo.lock
Everytime I build `dev` the cargo.lock file is changed to this.
Most likely an aftermath of https://github.com/qdrant/qdrant/pull/2489/files
Let's keep it stable.
=> Sync cargo.lock file for rustls-webpki

Cargo.lock, Cargo.toml, lib/api/build.rs, lib/api/src/grpc/mod.rs, src/tonic/mod.rs, tests/basic_grpc_test.sh
This registers a gRPC reflection service so that external tools (e.g. `grpcurl`, Postman, Insomnia) can inspect the API and provide nice tooling around listing, validating, and generating sample requests.
<details>
<summary> Example grpcurl output </summary>
```
❯ grpcurl --plaintext 127.0.0.1:6334 describe
qdrant.Collections is a service:
service Collections {
//Get cluster information for a collection
rpc CollectionClusterInfo ( .qdrant.CollectionClusterInfoRequest ) returns ( .qdrant.CollectionClusterInfoResponse );
//Create new collection with given parameters
rpc Create ( .qdrant.CreateCollection ) returns ( .qdrant.CollectionOperationResponse );
//Drop collection and all associated data
rpc Delete ( .qdrant.DeleteCollection ) returns ( .qdrant.CollectionOperationResponse );
//Get …
```
=> Add gRPC reflection server

lib/storage/src/content_manager/consensus/consensus_wal.rs
Fixes https://github.com/qdrant/qdrant/issues/1662
Analyzing the raft_state of a broken cluster shows that the consensus WALs diverged.
Using a [custom reader](https://github.com/qdrant/qdrant/pull/2244) I am able to see that the the last index for node0 is incorrect.
```
==========================
Entry ID:141
term:1
entry_type:0
data:"CollectionMeta(SetShardReplicaState(SetShardReplicaState { collection_name: \"test_collection\", shard_id: 0, peer_id: 3010363724257094, state: Active, from_state: Some(Initializing) }))"
==========================
Entry ID:142
term:1
entry_type:0
data:"CollectionMeta(DeleteCollection(DeleteCollectionOperation(\"test_collection\")))"
```
```
==========================
Entry ID:141
term:1
entry_type:0 …
```
=> Fix truncation of last element of consensus WAL

docs/redoc/master/openapi.json, lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs, lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs, lib/collection/src/collection_manager/optimizers/merge_optimizer.rs, lib/collection/src/collection_manager/optimizers/mod.rs, lib/collection/src/collection_manager/optimizers/segment_optimizer.rs, lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/telemetry.rs, lib/collection/src/tests/mod.rs, lib/collection/src/update_handler.rs
Report the current and historical optimizer status in telemetry. The status for the last 16 optimizations is kept. And statuses for ongoing or errored optimizations are always kept.
It gives us some insight of the optimization behavior in the of a remote instance. It hopefully helps us resolve issues where weird optimization loops are happening.
The implementation is rather simple. These _logs_ are not stored across restarts.
Here's an example snippet, the last optimization is at the top:
```json
{
"optimizations": {
"status": "ok",
"log": [
{
"name": "vacuum",
"segment_ids": [ 14390250694980796000 ],
"status": "optimizing",
"start_at": "2023-08-21T11:28:43.405555595Z",
"end_at": null
},
{
"name": "merge",
"segment_ids": [ 8162121629578494000, 14793682371326910000, 11018504688338340000 ], …
```
=> Report optimizer status and history in telemetry

Cargo.lock, Cargo.toml, src/actix/certificate_helpers.rs, src/actix/mod.rs
Supersedes <https://github.com/qdrant/qdrant/pull/2498>.
Bumps Rustls 0.20 and surrounding dependencies to all use Rustls 0.21.6. The old  version contains a vulnerability.
This switches actix-web from using feature `rustls` to `rustls-0_21` to force usage of Rustls 0.21 with the vulnerability fix. We should eventually switch back to the regular `rustls` feature once it gets the upgrade as well.
```bash
$ cargo tree | grep "rustls "
│   │   │   │   ├── tokio-rustls v0.24.1
│   │   │   │   │   ├── rustls v0.21.6
│   │   ├── tokio-rustls v0.24.1 (*)
│   ├── hyper-rustls v0.24.0
│   │   ├── rustls v0.21.6 (*)
│   │   └── tokio-rustls v0.24.1 (*)
│   ├── rustls v0.21.6 (*)
│   ├── tokio-rustls v0.24.1 (*)
├── rustls v0.21.6 (*)
```
=> Bump Rustls to 0.21.6 with surrounding dependencies

lib/collection/src/shards/mod.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs, lib/collection/src/update_handler.rs
Tracking issue: https://github.com/qdrant/qdrant/issues/2432
This adds a new shard proxy type, namely `QueueProxyShard`. Rather than forwarding updates correctly like `ForwardProxyShard` all updates are queued. The queued updates can be transferred to a remote when a shard transfer is finished.
It is implemented in a smart way. Rather than adding a queue of operations, the existing WAL is used. A property is added to the update handler to ensure the WAL never truncates the part that is still in use by the queue proxy shard.
The process of transferring queued updates happens in batches. This is lock-free, except for the last batch, to allow for un-queueing without missing updates.
The implementation is somewhat crude, but we can improve on it when other shard transfer bits finalize.
1. [x] …
=> Add shard queue proxy

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/common/stoppable_task.rs, lib/collection/src/update_handler.rs
Catch any panics happening during optimization and handle this situation.
Now, when an optimization task panics it is reported and the collection status is marked as `red`. Before, a collection hung as `yellow` indefinitely. Now:
In short, this now catches panics as they unwind in the optimization threads. When an optimization task is done, it is now explicitly joined upon to nicely clean them up. On joining, any panic that occurred is collected. These panics are then propagated through a panic handling callback. This new callback is attached to our stoppable task structure.
So a stoppable task may now define a panic callback to handle the panic status. These stoppable tasks are used for optimization. Our optimization tasks now define a panic callback to report it, registering the error …
=> Catch optimizer panics

lib/storage/src/content_manager/consensus/consensus_wal.rs, lib/storage/src/content_manager/consensus/persistent.rs, src/wal_inspector.rs
This PR adds support for the consensus WAL to the wal_inspector.
It comes in handy to debug diverging histories.
Example of output:
```
cargo run --bin wal_inspector -- ~/Downloads/qdrant_raft_issue_1662/storage_node0 consensus
Finished dev [unoptimized + debuginfo] target(s) in 0.25s
Running `target/debug/wal_inspector /home/agourlay/debug/storage_node0 consensus`
==========================
First entry: Some(Entry { entry_type: EntryNormal, term: 1, index: 1, data: [], context: [], sync_log: false })
Last entry: Some(Entry { entry_type: EntryNormal, term: 2, index: 142, data: [], context: [], sync_log: false })
Offset of first entry: Some(1)
==========================
Entry ID:1
term:1
entry_type:0
data:"[]"
==========================
Entry ID:2
term:1
entry_type:2
data:"[18, 11, 8, 2, …
```
=> Support consensus WAL format in wal_inspector

.github/workflows/integration-tests.yml, docs/redoc/master/openapi.json, lib/api/src/grpc/models.rs, lib/collection/Cargo.toml, lib/collection/src/collection.rs, lib/collection/src/common/file_utils.rs, lib/collection/src/common/mod.rs, lib/collection/src/operations/snapshot_ops.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/replica_set.rs, lib/storage/src/content_manager/errors.rs, lib/storage/src/content_manager/snapshots/download.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/content_manager/toc.rs, src/actix/api/snapshot_api.rs, src/actix/helpers.rs, tests/shard-snapshot-api.sh
Tracking issue: https://github.com/qdrant/qdrant/issues/2432
__TODO:__
- I think `upload_shard_snapshot` would fail, if you'd try to recover a shard, that is not _local_ on the node
- after _upload/download_, if shard is _local_ on the node
- or after recovery, if local shard is created on the node during recovery
- the logic for this is
- if local shard exists, then user can list/retry/delete uploaded/downloaded snapshot using the API
- and if local shard does not exist, then we remove failed snapshot automatically to prevent polluting temp/downloads directory
- `std::fs::rename`/`tokio::fs::rename` only works if source and destination paths are on the same file system
- __UPD:__ This is currently done for shard upload, but temporarily reversed for remote shard download …
=> Shard snapshot API

lib/collection/src/collection_manager/holders/segment_holder.rs, lib/collection/src/collection_manager/segments_updater.rs, lib/segment/src/segment.rs, openapi/tests/openapi_integration/test_delete_points.py
iThis fixes a data integrity issue where Qdrant could lose points, vectors and payload data on crash.
It is a two part problem: 1. losing points. 2. losing vectors.
Sometimes points (along with their vectors and payload) were lost. This has to do with copy-on-write operations on two segments happening between the flushing of these two segments. Here I explain it more in detail:
Qdrant has appendable (mutable) and non-appendable (immutable) segments. Imagine that we want to change a point in a non-appendable segment by updating its payload.
To do this, we have a copy-on-write mechanism. The point is deleted form segment **A** (non-appendable), the updated point is written to segment **B** (appendable). This normally works fine, but _can_ be problematic if Qdrant crashes.
Because of flush …
=> Fix missing points, vectors and payload

lib/storage/src/content_manager/mod.rs, lib/storage/src/content_manager/snapshots/download.rs, lib/storage/src/content_manager/snapshots/recover.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/content_manager/toc_components/mod.rs, lib/storage/src/content_manager/toc_components/toc_tmp_directories.rs, src/actix/api/snapshot_api.rs, src/actix/mod.rs, src/main.rs
Issue: https://github.com/qdrant/qdrant/issues/2533
Tracking: https://github.com/qdrant/qdrant/issues/2532
- Refactors temporary storage structure
- Enables temp storage cleanup on startup
- Refactors ToC  - move temp files-related functions into sub-modules
- Introduce usage of `tempfile` in the  `_do_recover_from_snapshot`
=> directories cleanup + refactoring

Cargo.lock, lib/api/Cargo.toml, lib/api/build.rs, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/types.rs, lib/common/Cargo.toml, lib/common/src/lib.rs, lib/common/src/validation.rs, openapi/tests/openapi_integration/helpers/collection_setup.py, openapi/tests/openapi_integration/test_limits.py
Fixes <https://github.com/qdrant/qdrant/issues/2268>, [CVE-2023-38975](https://github.com/advisories/GHSA-j4cw-vvxw-4jcv).
Limit the maximum number of vector dimensions to 65536.
=> Limit vector dimension to 65536

lib/collection/Cargo.toml, lib/collection/src/collection.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/tests/snapshot_test.rs, lib/segment/src/segment.rs
Tackles https://github.com/qdrant/qdrant/issues/2497
Relies on `tempfile` crate to automate cleanup.
=> Delete temp snapshot files on error

src/consensus.rs
This is the only test issuing logs by default.
It can be done manually if necessary with:
```bash
RUST_LOG=debug cargo test collection_creation_passes_consensus
```
Let's keep it quiet by default.
=> Do not always print logs during test

lib/segment/src/index/field_index/map_index/immutable_map_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/map_index/mutable_map_index.rs
Add immutable state for map index. This state should use RAM more efficiently because immutable map index don't need to have upserting functionality.
I attached RAM measurement tests as comments
=> Immutable map index

lib/segment/benches/hnsw_build_asymptotic.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/spaces/metric.rs, lib/segment/src/spaces/simple.rs, lib/segment/src/spaces/simple_avx.rs, lib/segment/src/spaces/simple_neon.rs, lib/segment/src/spaces/simple_sse.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs
Current behavior is that `Metric::preprocess` has a signature of 
```rust
fn preprocess(vector: &[VectorElementType]) -> Option<Vec<VectorElementType>> 
```
which means that it takes a slice, and (if needed) makes a copy and preprocesses it, returning a `Vec<_>` in the end. This behavior causes the cloning to be implicit within the function, allowing a possible optimization for when there is nothing to preprocess (e.g. when it outputs `None`).
In practice, however, since the function returns an optional `Vec<_>` instead of a slice, we always have to convert the input slice to a `Vec<_>` even if the preprocessing returned `None` to be able to use it further. 
This PR changes the signature to 
```rust
fn preprocess(vector: VectorType) -> VectorType
```
This forces us to do explicit cloning …
=> refactor: Make `preprocess()` own its vector argument

Cargo.toml, src/common/stacktrace.rs, src/main.rs
Non-linux users cannot run `cargo clippy --all-features` because `rstack-self` depends on either `libunwind` or `libdw`. Both backends are exclusively for linux, it appears, so it makes sense to also feature flag it like this.
=> Put `rstack-self` dependency behind linux flag

lib/segment/src/id_tracker/simple_id_tracker.rs
When the database is corrupted, id processing is a bit strange
The external_id removed here will be inserted repeatedly below
I think we should remove the replaced id, because duplicate data will not be used
=> fix: remove replaced id when db corrupted

docs/redoc/master/openapi.json, openapi/openapi-service.ytt.yaml, openapi/tests/openapi_integration/test_k8s_health.py, src/actix/api/service_api.rs, src/actix/mod.rs
Fixes <https://github.com/qdrant/qdrant/issues/2401>. Depends on <https://github.com/qdrant/qdrant/pull/2407>.
This implements health checking endpoints for Kubernetes, more specifically `healthz`, `livez` and `readyz`.
These are implemented in the most basic fashion at this time, simply returning HTTP 200 with `healthz check passed`. All three are whitelisted and always accessible regardless of whether an API key is configured.
Once merged, these can be properly incorporated into our [helm chart](https://github.com/qdrant/qdrant-helm).
=> Add healthz, livez and readyz endpoints for Kubernetes

openapi/.gitignore
We missed generating the OpenAPI definition for shard snapshots based on our template:
```bash
$ ./tools/generate_openapi_models.sh
```
=> Add generated OpenAPI definitions to .gitignore

Dockerfile
Fixes failing Docker builds on `master` due to cross compilation.
This:
- defines the proper `pkg-config` path, the `/usr/bin/` prefix was missing
- installs `pkg-config` for the target architecture
I have NOT tested the built ARM image on ARM hardware after this fix, it may be worth to give this a shot.
=> Fix `pkg-config` installation for cross compilation in Docker

lib/segment/tests/integration/segment_builder_test.rs
running `cargo nextest run --all` consistently made this test flake out.
Reason was because the time it took for the early cancellation was often a little more than the time it took the later cancellation.
These changes create 3 different segments for this test, instead of just 1:
1. Baseline - to know how much time it normally takes to execute
2. Early cancellation - to cancel almost as soon as it's requested
3. Later cancellation - to cancel a little later
Ensures both cancellations don't take more than 1/4 of the full build time
=> Fix flaky `test_building_cancellation`

lib/collection/src/collection.rs
This PR attempts to fix https://github.com/qdrant/qdrant/issues/2574
After a lot of trial and error running `test_snapshot_collection` on CI, I finally found something that appears to fix the test for good.
It seems that deleting manually a temporary file from its path, instead of relying on `drop` causes mysterious issues.
The test does two passes, the assumption is that the first pass interferes with the second
```rust
async fn test_snapshot_collection() {
init_logger();
_test_snapshot_collection(NodeType::Normal).await;
_test_snapshot_collection(NodeType::Listener).await;
}
```
Given that this removal is not strictly required, we can safely remove it.
=> Fix flaky snapshot creation test

.github/workflows/docker-image.yml
Run our Docker release job on our self-hosted GitHub Actions runner.
We want to change this before our next patch release, as we had trouble with this specific job before when it is executed on shared runners.
These tags match those from our runner:
=> Always run our Docker build CI job on our self hosted runner

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, tools/missed_cherry_picks.sh
A patch release bumping Qdrant to v1.5.1.
Most importantly, this fixes <https://github.com/qdrant/qdrant/pull/2641>.
=> Bump version to v1.5.1

lib/collection/src/collection.rs
context: https://github.com/qdrant/qdrant/issues/2574
The latest failure is located at 
```
thread 'tests::snapshot_test::test_snapshot_collection' panicked at 'called `Result::unwrap()` on an `Err` value: ServiceError { error: "File IO error: No such file or directory (os error 2)"
...
collection::collection::Collection::create_snapshot::{{closure}}::{{closure}}
at ./src/collection.rs:1594:13
```
This PR removes an unnecessary path clone hoping it helps resolving the issue.
=> Simplify snapshot creation

.github/workflows/docker-image.yml
Our Docker release job on CI is broken. It fails near the end: https://github.com/qdrant/qdrant/actions/runs/6161250399/job/16730823202
A `pull` step was missing near the bottom. Therefore the `-unprivileged` image was never pushed to [GitHub packages](https://github.com/qdrant/qdrant/pkgs/container/qdrant%2Fqdrant). This command has now been added.
I've also restructured the job a bit to clarify what is happening. I found it super confusing before.
=> Fix docker release job

lib/segment/src/index/hnsw_index/graph_links.rs
Small PR with two changes to the graph links.
- delete duplicate header construction
- size vector of levels appropriately
=> Misc. improvements to GraphLinks

docs/grpc/docs.md, lib/api/src/grpc/proto/qdrant_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/types.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/toc.rs, src/tonic/mod.rs
Depends on <https://github.com/qdrant/qdrant/pull/2406>. Tracking issue: https://github.com/qdrant/qdrant/issues/2432
This adds a method for waiting on all other peers to reach a given commit. It can be used to guarantee a node reached a certain consensus state.
This is implemented in an internal gRPC call to a node, in which you specify what commit/term to wait on.
The current implementation is naive, as a spin lock is used to wait for the specified commit. It can be improved upon in the future. To cancel, you can drop the gRPC request.
All in all, this is how it is used:
```rust
toc.await_commit_on_all_peers(commit, term, Duration::from_secs(10)).await;
```
Once merged, we can eventually integrate this in various parts of the code base where such synchronization is useful.
1. [x] Does …
=> Add method to wait for commit/term on other peers

lib/common/Cargo.toml
Common crate uses serde device macro. This PR adds derive feature flag.
Example of failure because of a feature missing:
In https://github.com/qdrant/qdrant/pull/2318 you cannot run test `cargo test -p sparse` because of compilation error: derive macro not defined.
=> Serde derive for common crate

.config/nextest.toml, .github/ISSUE_TEMPLATE/flaky_test.md, .github/workflows/rust-lint.yml, .github/workflows/rust.yml
Our current CI test scheme uses the integrated `cargo test` tool for running tests, but sometimes tests begin to flake out, which makes us retry the workflow run to make sure it wasn't our fault. Arguably this makes us pay more attention to flaky tests, but it becomes a distraction when doing unrelated work.
Recently I found out about [`nextest`](https://nexte.st/book), and while we don't need a lot of its features, it does have a couple of them that may benefit us. For instance, it allows retries with backoff, test timeouts, and test reporting (using junit format). 
- adds `nextest` as the test runner on GH Actions (for Rust only, obviously).
- enable retries with exponential backoff
- automate creating issues for flaky tests.
=> CI: use nextest for running rust tests

Cargo.lock, Cargo.toml, src/greeting.rs
Removes the `atty` dependency. Switch to [`IsTerminal::is_terminal()`](https://doc.rust-lang.org/std/io/trait.IsTerminal.html#tymethod.is_terminal) instead.
`atty` contains an unfixed vulnerability on Windows: https://github.com/advisories/GHSA-g98v-hv3f-hcfr
Fixes security alert (private): https://github.com/qdrant/qdrant/security/dependabot/44
=> Remove atty dependency, use stdlib method for this

Cargo.lock
Bumps the `spin` dependency to the latest version.
`spin >= 0.9.3, < 0.9.8` contains a vulnerability: https://github.com/advisories/GHSA-2qv5-7mw5-j3cg
Fixes security alert (private): https://github.com/qdrant/qdrant/security/dependabot/37
=> Bump spin to 0.9.8

lib/collection/src/collection.rs, lib/collection/src/shards/shard_holder.rs
Tracking issue <https://github.com/qdrant/qdrant/issues/2432>.
The shard snapshot functions and the logic around it are currently placed in `Collection`. Instead, these should be placed into `ShardHolder`. This PR is a refactoring effort to move the functions.
Refactoring is desired because of the shard snapshot transfer feature (<https://github.com/qdrant/qdrant/issues/2432>). In the logic for transferring, we don't have access to `Collection`, but do have access to `ShardHolder` (<https://github.com/qdrant/qdrant/pull/2467>).
I've kept some shard snapshot functions as transient in `Collection`, because they still have some usages else where. They now forward the call to `ShardSnapshot`. Now, this is a bit messy. Maybe this is a good place to open some discussion on it.
=> Extract shard snapshot logic from collection into shard holder

.github/ISSUE_TEMPLATE/flaky_test.md, .github/workflows/rust.yml
Following up on #2677, this tags the PR number in the issue description to create a reference so that PR author can see more clearly when a test is flaking on their PR. 
As a side improvement, I've separated the build and test stages so we can have better metrics in build and run times
=> CI: reference PR number in flaky test issue creation

lib/collection/src/shards/local_shard.rs
In 90127771817ef9cb7faa75d7a5b4bfcccb0f8f67 (<https://github.com/qdrant/qdrant/pull/2528#issuecomment-1699556098>) we removed a level of temporary snapshot directories. This would produce shorter paths on Windows, preventing us from reaching the path length limit.
Around the time we implemented this change, weird IO errors started popping up. Even after extensive investigation the root cause wasn't found. @agourlay and I have a suspicion that this change introduced the problem.
Related issues:
- https://github.com/qdrant/qdrant/issues/2574
- https://github.com/qdrant/qdrant/issues/2678
This reverts the linked commit. After merging we'll be able to see if the issue pops up again. Then we can investigate further.
=> Revert reducing depth of temporary snapshot directories

lib/collection/src/collection.rs
The clone() call for 'operation' in the update_from_peer function appears to be redundant and has been removed.
=> Refactor: Remove unnecessary clone() call for 'operation' in update_from_peer function

lib/segment/tests/integration/segment_builder_test.rs
Fixes <https://github.com/qdrant/qdrant/issues/2695>.
Similar to <https://github.com/qdrant/qdrant/pull/2682>, but with 5k points as 2k was not large enough.
The `test_building_cancellation` test flaky. It depends on timings which are currently too close together causing false negatives.
This changes the delays to be in relation to baseline, and using an acceptable stopping threshold
=> Fix `test_building_cancellation` flakiness with different delays

lib/segment/src/common/rocksdb_wrapper.rs
This PR sets RocksDB to delete obsolete files more aggressively.
We have observed that RocksDB storage directories tend to be full of `LOG.old.*` files which start representing a significant amount of space in setup with a large number of collections.
We have already configured RocksDB to keep at most 2 files but the cleanup frequency is set to 6h by default.
This PR proposes to lower the cleaning threshold explicitly to 30 minutes to free disk space more aggressively without impacting the performance.
Reference: https://github.com/facebook/rocksdb/issues/2166
=> RocksDB deletes obsolete file more aggressively

lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/mod.rs, lib/segment/tests/integration/payload_index_test.rs
Fix for https://github.com/qdrant/qdrant/issues/2707
When calculating the cardinality estimation for the any matcher, we actually forgot to set primary clauses for it.
This means the condition was never used upstream to restrict to working set of the query resulting into a full scan.
=> Fix cardinality estimation for Any matcher

lib/segment/tests/integration/segment_builder_test.rs
Fixes #2711 that has reappeared again. This time we increase the acceptable stopping delay from 400 to 600ms.
I analyzed the code that it is testing and found no possible bug, other than the checking of stop boolean uses `Ordering::Relaxed`, but I don't think we should change that for performance reasons.
=> fix `test_building_cancellation` flakiness with higher acceptable stopping delay

.config/nextest.toml, .github/ISSUE_TEMPLATE/flaky_test.md, .github/workflows/rust.yml
- ~restrict to only create automatic issues on PRs of authors of the org, or on dev/main.~ Edit: Don't fail the workflow if the issue posting/update fails. This may happen when an already open issue of a test flakes again, and tries to update with the credentials of an external contributor.
- modify link to failed job, currently this only applies to the issue reporting job, because it's hard to link them to the actual flaky failure run, but it already improves it.
- add last flaky failure date.
- reduce retries to only 2. Having 3 tries in total feels more than enough.
=> CI: improve automatic issue creation

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/recommendations.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/tests/integration/grouping_test.rs, lib/segment/src/data_types/vectors.rs, openapi/tests/openapi_integration/test_recommend.py, src/tonic/api/points_common.rs
Needs: #2661 
- Exposes new recommendation scorer via `RecommendStrategy` parameter
- In both gRPC and REST
- New scorer is routed to a `CoreSearchRequest`
- There is a little performance hit on current implementation when sending batches of alternating recommendation strategies (i.e. `[avg, scorer, avg, scorer, avg, ...]`). But it will go away when we can convert normal search requests into CoreSearchRequest too.
- Support for raw input vectors in recommend (instead of just IDs)
=> Expose new recommend scorer via recommend strategy

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/types.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs
Issue https://github.com/qdrant/qdrant/issues/2624
For binary quantization, we want to rescore search results by default. Because without rescoring plain search result will be missed, the reason is in large difference between original and quantized scores.
On the other hand, we want to disable rescoring by default. Because of performance reasons.
As a possible solution, this PR introduces an `Auto` rescoring mode which enables rescoring for binary quantization and disables for another kind.
=> Search rescoring modes

docs/redoc/master/openapi.json, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/recommendations.rs, src/tonic/api/points_common.rs
Allow `strategy: null` in reco REST API
=> nullable recommendation strategy

Dockerfile
Happened to need an unprivileged Docker container to test some permissions-related stuff... and discovered we weren't building it right all this time and container was not working properly! 🤦‍♀️
This PR fixes unprivileged build. (And makes some cosmetic changes to the Dockerfile.)
The core of the issue is:
- Docker uses plain `sh` when building images
- there's no `[[` built-in in `sh`
- and, as far as I can tell, there's no `[[` binary in the base Debian image that we are using for the final stage of the build
- and so the `if [[ "$USER_ID" != "0" ]]; then ...` check _always_ fails
- but because `[[` command fails as part of `if` statement, it is not considered "fatal" and does not fail image build
- and the way Docker displays command output during container build makes it practically …
=> Fix unprivileged Docker container build

lib/collection/src/collection_manager/holders/segment_holder.rs
Our lock acquiring mechanism in `aloha_random_write` seems to introduce a deadlock, and is therefore problematic.
Replacing the last bit, that randomly tried to lock any appendable segment with exponential timeout, with a call that tries to lock just one random appendable segment forever, fixes the problem in our test case.
Sadly, we're still short an explanation on what the exact problem is here.
More details: https://github.com/qdrant/qdrant/pull/2733#issuecomment-1737214030
=> Simplify aloha random write, after first try, lock on one random forever

lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard.rs, lib/collection/src/shards/local_shard_operations.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard.rs, lib/collection/src/shards/update_tracker.rs, tests/consensus_tests/test_collection_shard_update.py
Asynchronously watch for the start of local update operation and fan-out to one additional shard (if there's one) if local update operation started _and local read operation still pending_.
Resolves #2717.
__TODO:__
=> Implement dynamic read operation fan out on local update (#2717, #2728)

lib/collection/src/shards/replica_set.rs, tests/consensus_tests/test_collection_shard_update.py
- Fix potentially flaky `test_collection_shard_update`
- Replace `join_all` with `FuturesUnordered` in `ShardReplicaSet::update`
- Also made some cosmetic changes in `replica_set.rs`
=> Minor fixes for dynamic fan out PR (#2741, #2728)

docs/redoc/master/openapi.json, lib/collection/src/config.rs
Do not serialize fan-out if it is default.
Helps better backward compatibility with existing clients
=> improve compatibility with existing clients

lib/segment/src/index/field_index/binary_index.rs, lib/segment/src/index/query_optimization/condition_converter.rs
Fixes #2743 
I missed to use the binary index when doing match by value 🤦 
The issue uses count API to get the unwanted behavior because `exact` defaults to `true`, with this fix it gets 1 or 2 orders of magnitude faster.
I checked with `exact=false` and it can be 4 orders of magnitude faster (works correctly without this fix)
=> fix: Include binary index on match value

lib/collection/src/collection.rs, lib/collection/src/shards/remote_shard.rs, lib/storage/src/content_manager/toc.rs, tests/consensus_tests/test_write_ordering.py
Fixes https://github.com/qdrant/qdrant/issues/2751
Main change: always specify shard selection if the request was made from the remote shard structure.
=> only forward update from shard to another shard

lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/operations/mod.rs, lib/collection/src/operations/point_ops.rs, lib/collection/src/operations/vector_ops.rs, lib/segment/src/index/field_index/geo_index.rs, lib/storage/src/content_manager/consensus_manager.rs, src/common/telemetry_ops/requests_telemetry.rs
Rust 1.73 is around the corner, it is time to fix proactively new Clippy lints to not block our CI.
Only one lint was triggered this time https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_or_default
=> Fix Clippy lints 1.73

Cargo.lock, lib/common/io/src/file_operations.rs, lib/common/memory/src/mmap_ops.rs, lib/sparse/Cargo.toml, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
This PR adds memmap persistence for the sparse vector index.
The idea is to persist the flatten index `Vec<PostingList>` as a memmap file.
which is
`Vec<Vec<PostingElement>>`
which is
`Vec<Vec<(u32, f32, f32)>>`
There is an extra file header saved as JSON containing the total number of posting lists in the file.
Its presence informs us if the index data is well formed.
The index data itself is prefixed by a series of  header for deserialization purpose containing the offsets of each posting list.
Example for `n` posting lists.
`index.data` = `n * [posting header] | n * [posting index data]`
Retrieving a posting list by id means:
1. retrieve header information (based on the fixed length of header
2. get offsets from header to get posting list as a slice
=> Sparse index persistence

lib/collection/src/operations/shared_storage_config.rs, lib/collection/src/shards/replica_set.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/tests/integration/collection_test.rs, lib/storage/src/content_manager/toc.rs, lib/storage/src/types.rs, src/main.rs
Fixes <https://github.com/qdrant/qdrant/issues/2731>.
Fix a local shard in non-distributed deployment being stuck in `Initializing` bricking a collection on reboot. This could occur if Qdrant crashes while a collection is created. This now updates the local shard state from `Initializing` to `Active` on load.
When this happens, the following warning is logged:
```
WARN collection::shards::shard_holder: Local shard test:0 stuck in Initializing state, changing to Active
```
Tested this situation manually by adding a panic [here](https://github.com/qdrant/qdrant/blob/252c1026c6d726ea737fbc620720bfa56bc5e461/lib/collection/src/collection.rs#L159). Then create a collection, restart Qdrant and fetch the collection info.
Added a unit test for this. It simulates this situation by setting the …
=> Change local shard stuck in Initializing to Active on load

docs/redoc/master/openapi.json, lib/storage/src/content_manager/collection_meta_ops.rs
Updates the description of the vector parameters map in the update collection REST call. This changes our OpenAPI specification, but only modifies the description.
Here, users must provide a map of named vectors. Therefore, the current description is wrong. It was also confusing how to update parameters in a collection with a single unnamed vector.
This changes the description from:
> Vector data parameters to update. It is possible to provide one config for single vector mode and list of configs for multiple vectors mode.
to:
> Map of vector data parameters to update for each named vector. To update parameters in a collection having a single unnamed vector, use an empty string as name.
The description is presented here (`vectors` field): …
=> Improve description of vector parameters in update collection REST call

docs/redoc/master/openapi.json, lib/api/src/grpc/conversions.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/types.rs, lib/segment/tests/integration/payload_index_test.rs, openapi/tests/openapi_integration/test_geo_filter.py
In https://github.com/qdrant/qdrant/pull/2315 we made the `interiors` field of geo polygons effectively optional by performing the validation in a shadow type.
We have tests showing that it works fine **but** we forgot to propagate the change to the type which provided the JSON schema.
Issue discovered while updating the Python client https://github.com/qdrant/qdrant-client/pull/325
=> Make GeoPolygon interiors optional

lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
New code failing against Clippy on Rust 1.73
Discovered in https://github.com/qdrant/qdrant/pull/2666#discussion_r1347623278
```
error: incorrect implementation of `partial_cmp` on an `Ord` type
--> lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs:86:1
|
86 | /  impl<T: PartialEq + PartialOrd + Encodable> PartialOrd for NumericIndexKey<T> {
87 | |      fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
| | _______________________________________________________________________-
88 | ||         Some(match self.key.cmp_encoded(&other.key) {
89 | ||             std::cmp::Ordering::Equal => self.idx.cmp(&other.idx),
90 | ||             ord => ord,
91 | ||         })
92 | ||     }
| ||_____- help: change this to: `{ Some(self.cmp(other)) }`
93 | |  } …
```
=> Fix Clippy 1.73 for consistent Ord impl in NumericIndex

docs/grpc/docs.md, lib/api/src/grpc/grpc.health.v1.rs, lib/api/src/grpc/mod.rs, lib/api/src/grpc/proto/health_check.proto, lib/api/src/grpc/proto/qdrant.proto, src/tonic/mod.rs, tests/basic_grpc_test.sh
Added health check implementation according to #2614 
I added only the method `Check` that always returns `Serving`. Currently the other method `Watch` is omitted as it looks like it would need some additional packages `tokio_stream`. If it needs some further changes, please let me know and I can take care of it.
=> add grpc compliant health check

lib/segment/src/common/utils.rs, lib/segment/src/types.rs, openapi/tests/openapi_integration/test_payload_selector.py
Context: #2336 
This PR adds support for `JsonPath` in payload selector to enable users to fetch exactly when they need.
This was implemented using our existing `JsonPath` infrastructure plus a new method for inserting at a given path.
The new feature is covered with unit and integration tests.
=> Allow JsonPath for PayloadSelector

lib/api/src/grpc/grpc.health.v1.rs, lib/api/src/grpc/mod.rs
The auto generated file keeps on being reformatted locally.
We usually tag those with `#[rustfmt::skip]`
=> Fix formatting of new gRPC health check

Cargo.lock, Cargo.toml, docs/redoc/default_version.js, docs/redoc/index.html, lib/api/Cargo.toml, tools/missed_cherry_picks.sh
A feature release bumping Qdrant to v1.6.0.
=> Bump version to 1.6.0

lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/tests/integration/filtrable_hnsw_test.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs
Fix of bug https://github.com/qdrant/qdrant/issues/2787
There was no oversampling and rescoring for filtered HNSW search with small cardinality conditions.
The fix includes a refactor with re-usage of quantization parameters processing, raw scorer construction, etc. It's the same business logic between large and small cardinality cases.
PR contains additional tests wich include not only bug cases but also quantized search tests for small cardinality cases.
=> fix rescoring for small cardinality case

Dockerfile
Reverts qdrant/qdrant#2781
New rust version causes 
```
(signal: 11, SIGSEGV: invalid memory reference)
```
during compilation in docker
=> Revert "Bump lukemathwalker/cargo-chef from latest-rust-1.72.1 to latest-rust-1.73.0"

lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/segment.rs, lib/segment/src/segment_constructor/segment_builder.rs, lib/segment/src/segment_constructor/segment_constructor_base.rs, lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/mmap_vectors.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/tests/reco_query_scorer.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/segment/tests/integration/batch_search_test.rs, lib/segment/tests/integration/exact_search_test.rs, lib/segment/tests/integration/filtrable_hnsw_test.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs
Currently, quantized data is a part of `VectorStorage`. However, vector storage does not use any information from quantized data and just provides access to quantized data to the higher-level logic. It makes `VectorStorage` trait overcomplicated. And if sparse vectors are integrated as a new variant of vector storage enum, it will make an integration difficulties.
So in this PR I propose to separate vector storage and quantized data as separate entities. It makes code simpler to read and support. Nice bonus, in this PR more lines were deleted than added =)
=> Quantization storage as separate entity

tests/openapi_integration_test.sh
The OpenAPI integration test image that is built through `docker buildx` should be tagged so it is added to the Docker engine on the host system.
If we don't tag this image the integration test might fail with:
```bash
$ tests/openapi_integration_test.sh
++ dirname tests/openapi_integration_test.sh
+ cd tests/../
+ cp docs/redoc/master/openapi.json openapi/tests/openapi.json
++ docker buildx build --load -q ./openapi/tests
+ docker run --rm --network=host -e OPENAPI_FILE=openapi.json -v /home/timvisee/git/qdrant/openapi/tests:/code sha256:4c9144e7590aca012178585a317494023f862cbf96bbe7b7261f9d590c42a795 sh -c /code/run_docker.sh
docker: Error response from daemon: No such image: sha256:4c9144e7590aca012178585a317494023f862cbf96bbe7b7261f9d590c42a795.
See 'docker run --help'.
```
Also adds …
=> Tag OpenAPI integration test image, run in interactive mode

lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/tests/integration/payload_index_test.rs
Fixes https://github.com/qdrant/qdrant/issues/2800
Actually, there are 2 problems related to empty condition.
- previously it was estimated with `estimate_should`, which doesn't work well with empty conditions
- parsing of empty lists didn't preserve correct typing
Solution to both: explicitly check for empty condition in all cases
=> optimize usage of the match-any filter in case it is empty

lib/segment/src/vector_storage/quantized/mod.rs, lib/segment/src/vector_storage/quantized/quantized_discovery_query_scorer.rs, lib/segment/src/vector_storage/query/discovery_query.rs, lib/segment/src/vector_storage/query/mod.rs, lib/segment/src/vector_storage/query_scorer/discovery_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/mod.rs
Complete feature tracked by #2790 
Adds a new scorer for discovery api. How it works:
- Combines rank (with respect to pairs) with similarity to a target.
- Rank is determined by a round number. If the candidate is closer to the positive side of a pair, it is +1, else it is -1. Final rank is the sum of these interactions with all pairs.
- Rank has higher priority, and increases in steps of 1. We need to make the score component to fit in the range (0, 1), so that we can just sum rank + score as the final output of this scorer. We chose to use a sigmoid function approximation to do this. …
=> Add discovery query scorer

lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/query_scorer/discovery_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs, lib/segment/src/vector_storage/query_scorer/reco_query_scorer.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs
Sparse vector integration step.
Sparse vector data will be integrated as a `VectorStorageEnum` variant. And because sparse vectors aren't just `Vec<f32>`, we are going to change `get_vector` signature of `VectorStorage` trait. It will return some `enum` with sparse and dense variants. To avoid additional conversion of such `enum` in scorers, this PR introduced `DenseVectorStorage` trait with an explicit dense vector getter for scorers.
=> Dense vector storage

lib/api/build.rs, lib/api/src/grpc/qdrant.rs, lib/api/src/grpc/validate.rs, lib/collection/src/operations/cluster_ops.rs, lib/collection/src/operations/validation.rs, lib/common/common/src/validation.rs, tests/consensus_tests/test_collection_shard_transfer.py
Fixes https://github.com/qdrant/qdrant/issues/2805
Before, we could send a shard to the same node as it came from by using the same _from_ and _to_ peer ID. This brought Qdrant into a weird state.
This PR prevents this by blocking this at the validation level. Now the source and target address must be different in both REST and gRPC.
The following validation error is now returned:
```
Validation error in JSON body: [move_shard.to_peer_id: cannot move shard to itself, "to_peer_id" must be different than 0 in "from_peer_id"]
```
=> Block shard transfer to itself with validation

Cargo.lock, lib/collection/Cargo.toml, lib/common/common/Cargo.toml, lib/segment/Cargo.toml
Bump `ordered-float` dependency to 4.1.1 to include the following optimization: https://github.com/reem/rust-ordered-float/pull/144
Thanks @agourlay for finding this!
=> Update ordered float to 4.1.1

Cargo.lock, lib/sparse/Cargo.toml, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
Enable adding new records to the sparse index in RAM.
A fair amount of complexity is due to the `max_next_weight` flag propagation.
=> Upsert operation on Sparse RAM index

lib/segment/src/index/mod.rs, lib/segment/src/index/sparse_index/mod.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/mod.rs, lib/sparse/src/index/search_context.rs
This PR continues the work to integrate the sparse vector index in the segment crate.
It introduces a new index `SparseVectorIndex<T: InvertedIndex>` following the structure of the HNSW index.
To do so the `InvertedIndex` was refactored from an enum. into a trait.
Some of the changes from https://github.com/qdrant/qdrant/pull/2779 were also backported.
- search cancellation
- trivial implementations for the future `VectorIndex` impl.
- search helper to hide the search context
In a future PR we will be able to fully implement `VectorIndex` and introduce two new index variants.
```rust
SparseRam(SparseVectorIndex<InvertedIndexRam>),
SparseMmap(SparseVectorIndex<InvertedIndexMmap>),
```
=> Sparse vector index integration

lib/api/src/grpc/proto/shard_snapshots_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/snapshot_ops.rs, lib/storage/src/content_manager/snapshots/recover.rs, src/common/snapshots.rs
Add `ShardTransfer` snapshot priority and expose it in internal shard snapshot gRPC API.
The implementation is a little bit "tricky":
- instead of introducing an additional `ShardSnapshotPriority` type to `Collection` crate
- I simply added `ShardTransfer` variant to the existing `SnapshotPriority` type
- and excluded it from public HTTP API with `#[serde(skip)]`
- this way it should be excluded from OpenAPI schema
- and won't be deserialized by the API if user tries to pass it in the request
- and we only use snapshot priority in *internal **shard** snapshot gRPC API*, so no issues with gRPC API as well
- though, I can refactor it to be more explicit if requested
This PR is currently based on #2825. It will be rebased onto `dev` once #2825 is merged.
(This is required for the #2432.)
1. …
=> Add `ShardTransfer` snapshot priority

lib/segment/benches/vector_search.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/segment.rs, lib/segment/src/vector_storage/appendable_mmap_vector_storage.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/simple_vector_storage.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs, lib/segment/src/vector_storage/tests/utils.rs, lib/segment/src/vector_storage/vector_storage_base.rs
This PR introduces common type of vector and vector reference:
```
pub enum Vector {
Dense(VectorType),
Sparse(SparseVector),
}
pub enum VectorRef<'a> {
Dense(&'a [VectorElementType]),
Sparse(&'a SparseVector),
}
```
This common vector type is a part of sparse vector index integration. While this PR, `Vector` was integrated to the `VectorStorage` trait. It unblocks https://github.com/qdrant/qdrant/pull/2806
Currently, `Vector` allows converting directly to dense vector type with panic. Because error propagation is out of scope here. Also out of scope the renaming `VectorType` -> `DenseVector`
3. [ ] Have you checked your code using `cargo clippy …
=> Use enum vector type in vector storage

lib/common/common/src/lib.rs, lib/common/common/src/math.rs, lib/segment/src/common/mod.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/async_raw_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/query/context_query.rs, lib/segment/src/vector_storage/query/discovery_query.rs, lib/segment/src/vector_storage/query/mod.rs, lib/segment/src/vector_storage/query/reco_query.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs
Adds a new type of query: `ContextQuery`. It only uses pairs to guide the search towards what could be the "best" zone, which would be where the most positive areas would overlap.
The algorithm is inspired by the triplet loss function used in deep learning:
```rust 
let positive = similarity(&self.positive);
let negative = similarity(&self.negative);
let difference = positive - negative - MARGIN;
min(difference, 0.0)
```
If a point and its neighbors are already on a "best" zone, this algorithm won't be helpful to keep guiding the search, because all scores would yield 0.0, so it should end there.
Also adds this new query as new variant: `QueryVector::Context`
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior …
=> Add discovery context scorer

.github/workflows/rust.yml, lib/segment/src/vector_storage/query/context_query.rs
Running `cargo test --all` currently yield the following error.
```
---- lib/segment/src/vector_storage/query/context_query.rs - vector_storage::query::context_query::DiscoveryPair<T>::loss_by (line 13) stdout ----
error: unknown start of token: \u{2502}
--> lib/segment/src/vector_storage/query/context_query.rs:14:1
|
3 | │
| ^
```
~~It does not happen on CI because we do not use `--all` but `--workspace`.~~ see https://github.com/qdrant/qdrant/pull/2856#issuecomment-1772350386
It seems the root cause is the way rustc interpret comments https://github.com/rust-lang/rust/issues/64162
This PR inserts some text to remove the completely empty line to please rustc.
=> Fix cargo test doc

Cargo.lock, Cargo.toml, src/actix/api_key.rs, src/tonic/api_key.rs
Fixes <https://github.com/qdrant/qdrant/issues/2845>.
Add support for using a `Authorization: Bearer my_token` header for API-key authentication. Our authentication logic will try to fall back to this header if no `Api-key` header is provided. This is implemented for both our REST and gRPC API.
More specifically, this does not implement additional authorization endpoints which is common with Bearer to generate unique tokens. Instead this accepts the user defined API-key directly.
A malformed Authorization Bearer header is currently simply ignored.
Similar to <https://github.com/qdrant/qdrant/pull/2007> but using a standardized approach.
3. [x] …
=> Support API-token authentication through Http Authorization Bearer header

lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, lib/storage/src/content_manager/toc/mod.rs, lib/storage/src/content_manager/toc/transfer.rs, lib/storage/src/dispatcher.rs, src/consensus.rs, src/main.rs
Merges into https://github.com/qdrant/qdrant/pull/2467.
Adds a consensus interface as trait to be passed into shard transfer. This gives the shard transfer logic access to consensus operations through specialized functions. This is required for shard snapshot transfer.
This PR simply defines the interface (trait) and brings it from our table of contents up to our shard transfer logic. For this I've repurposed `Dispatcher` as it gives access to the consensus proposal channel and the current consensus state.
The implementation is a bit hacky, but it seems to be the best we can do. I've attempted some big refactoring operations but these failed. The other option to achieve this is to merge `storage` and `collection` together, which I …
=> Add consensus interface to shard transfer, repurpose dispatcher

lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/index/hnsw_index/entry_points.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/hnsw_index/mod.rs, lib/segment/src/index/hnsw_index/tests/mod.rs, lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs
This PR contains several fixes for the HNSW parallel index building process
related to: https://discord.com/channels/907569970500743200/1164130123868557392
> We have been bnechmarking recall@1 of qdrant HNSW index using 60K, 100K and 1M 1024-dimensional embeddings.
Within each benchmarking process we have been waiting for collection status to turn 'green' before running the search.
After comparing the results for different HNSW parameters (M, ef_construct, ef_search), we have discovered that the parameter 'M' works in a very unexpected way (the lower the better).
We have reproduced the same experiment for FAISS HNSW index and got the expected results for 'M' (the higher the better) with higher recall@1 values.
Shortly after, we have discovered that the problem with qdrant HNSW recall was …
=> Hnsw parallel build accuracy

lib/collection/src/operations/types.rs, lib/segment/src/common/mod.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/async_raw_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/query/context_query.rs, lib/segment/src/vector_storage/query/discovery_query.rs, lib/segment/src/vector_storage/query/reco_query.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs
This PR is a part of sparse vector index integration.
This PR continues `Vector` type integration. Here all variants of `QueryVector` use `Vector` instead of `VectorType`.
=> Propagate vector type into QueryVector

lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment.rs
This PR is a part of Sparse Vector index integration. The inverted index can be updated in runtime that's why we have to provide update mechanism for the vector index when possible.
HNSW index cannot be updated and returns error, in non-appendable segment update should never be called. Plain index does nothing.
=> Vector index update function

lib/collection/src/common/fetch_vectors.rs, lib/collection/src/common/mod.rs, lib/collection/src/recommendations.rs
Tracked by #2790 
In order to avoid code duplication, since we are also going to use examples in discovery api. I set up to extract the batched vector fetching logic from `recommendations.rs`.
I put the extracted logic in `collection/src/common/fetch_vector.rs`, but I'm open to suggestions if there is a better place for that to be.
=> refactor: Extract vector fetching logic from `recommendations.rs`

lib/collection/src/save_on_disk.rs, lib/collection/src/shards/channel_service.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/toc/mod.rs, lib/storage/src/content_manager/toc/transfer.rs, src/tonic/mod.rs
Merges into https://github.com/qdrant/qdrant/pull/2467.
Adds a call to the shard snapshot transfer logic to synchronize all peers with the consensus state of the current node. It is one of the required synchronization steps for shard snapshot transfer.
More specifically, this synchronization will happen right before the shard snapshot transfer is finalized. We do that to make sure all nodes have at least reached the `Partial` state for the shard. That way we are sure that all nodes will include the shard for operations. This logic awaits on all nodes explicitly and falls back to a 10 second timeout on failure. This timeout matches the consensus timeout.
It also:
- moves methods for awaiting a consensus commit from ToC into the …
=> Synchronize consensus across all nodes for shard snapshot transfer

lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, lib/storage/src/content_manager/toc/transfer.rs
Merges into https://github.com/qdrant/qdrant/pull/2467.
The three most important things this PR does are:
- When starting a shard transfer, set the target shard into `PartialSnapshot`.
- Add `ShardTransferOperations::SnapshotRecovered` operation to consensus
We propose this operation to consensus after the shard has been recovered on the remote. The consensus operation ensures the transfer is still active, and sets the shard from `PartialSnapshot` into `Partial`.
This operation is confirmed and retried up to 3 times if consensus rejected it.
- Consensus is synchronized explicitly on all nodes to ensure all reached the `Partial` state
This finalizes the steps required for setting `PartialSnapshot` and `Partial` states, and …
=> Set `(Partial)Snapshot` states for shard snapshot transfer through consensus

lib/segment/src/vector_storage/bitvec.rs, lib/segment/src/vector_storage/mod.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/tests/mod.rs, lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/sparse/src/common/sparse_vector.rs, lib/sparse/src/index/posting_list.rs
A simple storage for sparse vectors which persist original vector in RocksDB.
The implementation is a port of `SimpleVectorStorage` and some common code has been extracted.
=> Simple sparse vector storage

lib/api/build.rs, lib/api/src/grpc/proto/collections_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/mod.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/shard_transfer.rs, src/tonic/api/collections_internal_api.rs
Depends on https://github.com/qdrant/qdrant/pull/2467, https://github.com/qdrant/qdrant/pull/2881.
This improves what synchronizations are made for shard snapshot transfer. This now synchronizes to just the bare minimum to potentially improve the shard transfer time if one of the nodes is slow to respond.
The PR adds a `WaitForShardState` gRPC call to allow waiting for a remote shard to reach a specific state.
Synchronization is changed in the following way. Before we synchronized consensus right after proposing to switch the remote shard to `Partial` state. That way all nodes have reached the `Partial` state and the queue proxy could transfer all its updates to the remote.
With this PR we only wait for the remote shard to reach …
=> Improve shard snapshot transfer replica set state synchronization

lib/collection/src/shards/transfer/shard_transfer.rs
Depends on https://github.com/qdrant/qdrant/pull/2881.
The shard snapshot transfer feature creates a _temporary_ snapshot used for recovery on a remote peer. When recovery is done, this file is left behind.
This makes sure to delete the created snapshot after the snapshot is recovered or if recovering failed.
Similar to <https://github.com/qdrant/qdrant/pull/2846>, but for the sending side of things.
=> Clean up temporary snapshot after shard snapshot transfer

lib/segment/src/index/hnsw_index/build_condition_checker.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/struct_payload_index.rs, lib/segment/src/index/visited_pool.rs
This PR introduces automatically returning the visited list to the visited pool.
It's safer because currently developer has to return the list back manually when we stop usage of it.
I made this change because I want to try to fix this TODO:
https://github.com/qdrant/qdrant/blob/e686e71b9f514e9f8723c29591003f87b495ae87/lib/segment/src/index/struct_payload_index.rs#L416
If I'm going to add an iterator over filtered points, I have to have some mechanism for returning the visited list by the iterator end or drop.
=> Return visited list by drop

lib/segment/tests/integration/filtrable_hnsw_test.rs, lib/segment/tests/integration/hnsw_discover_test.rs
If we increase the search `ef` value for `Discovery` and `RecommendBestScore` we immediately get much more precise results. 
As an added benefit, this should also fix #2883
=> fix and increase precision on filtered hnsw tests

lib/api/src/grpc/validate.rs, tests/basic_grpc_test.sh
Fixes https://github.com/qdrant/qdrant/issues/2880.
Our custom validation handling on gRPC, done through `ValidateExt`, can panic when validating lists. This happens when there is more than one item having validation errors.
Sadly, the `validator` [type](https://docs.rs/validator/0.16.1/validator/struct.ValidationErrors.html) holding field errors is limited. We cannot use the item index at runtime because field names must be static string slices. Nor can we merge multiple errors into the same field name.
To mitigate panics and satisfy the limitation this PR now returns on the first error it comes across when validating list types in gRPC.
3. [x] …
=> Fix gRPC validation panic on list with multiple failing items

lib/sparse/src/common/sparse_vector.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/search_context.rs
This PR renames the sparse vector field `weights` to `values`.
Rational:
- weights is kinda SPLADE/ML specific
- weights is more prone to typos
- values is a more general and already used by other systems
=> Rename sparse vector values

lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/shard_transfer.rs
Improves logging for the logic that is driving shard transfers. Contains no logic changes.
This logs steps in both streaming records and snapshot transfer methods. This should help debugging remote machines by giving us a better idea of what stage a transfer is in. We could benefit from this if users would enable debug/trace logging.
=> Improve logging for shard transfers

lib/collection/src/shards/queue_proxy_shard.rs
An unused import and implementation in release builds slipped through when <https://github.com/qdrant/qdrant/pull/2467> was merged.
This fixes:
```rust
warning: unused import: `std::thread`
--> lib/collection/src/shards/queue_proxy_shard.rs:4:5
|
4 | use std::thread;
|     ^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: method `is_finalized` is never used
--> lib/collection/src/shards/queue_proxy_shard.rs:109:8
|
53  | impl QueueProxyShard {
| -------------------- method in this implementation
...
109 |     fn is_finalized(&self) -> bool {
|        ^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
2. [x] Have you formatted your code locally using `cargo …
=> Fix unused import and implementation in release builds

lib/api/src/grpc/transport_channel_pool.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/channel_service.rs, lib/collection/src/shards/remote_shard.rs, lib/storage/src/content_manager/toc/mod.rs
**Note**: This should only affect the inter-node channels.
- Removes the intermediate timeout implementation that was working separately from the request and channel timeouts.
- Now the channel timeout is set to a hard 1 hour (not configurable)
- All the individual requests now pass through an interceptor, which checks if they already have a timeout set, and if not, they set it to the `grpc_timeout_ms` from settings.
=> Refactor `with_channel_timeout`

lib/segment/benches/hnsw_build_asymptotic.rs, lib/segment/benches/hnsw_build_graph.rs, lib/segment/benches/hnsw_search_graph.rs, lib/segment/benches/vector_search.rs, lib/segment/src/fixtures/index_fixtures.rs, lib/segment/src/index/hnsw_index/graph_layers.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/hnsw_index/tests/mod.rs, lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/vector_index_base.rs, lib/segment/src/segment.rs, lib/segment/src/vector_storage/memmap_vector_storage.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/quantized/quantized_vectors.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/tests/async_raw_scorer.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs, lib/segment/src/vector_storage/tests/test_appendable_vector_storage.rs, lib/segment/tests/integration/batch_search_test.rs, lib/segment/tests/integration/exact_search_test.rs, lib/segment/tests/integration/filtrable_hnsw_test.rs, lib/segment/tests/integration/hnsw_discover_test.rs, lib/segment/tests/integration/hnsw_quantized_search_test.rs
Sparse vector index integration step.
This is a preparation step before removing temporary Sparse-Dense conversion:
https://github.com/qdrant/qdrant/blob/dev/lib/segment/src/data_types/vectors.rs#L36
To remove this conversion, raw scorer constructor should return `Result` with scorer
=> Raw scorer with operation result

lib/api/src/grpc/transport_channel_pool.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/transfer/shard_transfer.rs
Depends on <https://github.com/qdrant/qdrant/pull/2771>.
Before, the shard snapshot transfer recovery process could only take 60 seconds because a global gRPC timeout enforced this.
This change allows the snapshot transferring and recovery process to take much longer. Now it allows to take up to 24 hours useful for very large snapshots with slow connections.
This number is arbitrary, though it would allow transferring 100GB over a 10Mbps link (taking ~22 hours).
=> Use long timeout for shard snapshot recovery process

lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/mod.rs, lib/segment/src/vector_storage/raw_scorer.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/sparse_raw_scorer.rs, lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs, lib/segment/src/vector_storage/vector_storage_base.rs, lib/sparse/src/common/sparse_vector.rs
This PR introduces a `RawScorer` for sparse vector so that we can fallback to payload index scan in case of low filter cardinality estimation.
=> Raw scorer for sparse vectors

Cargo.lock, lib/sparse/Cargo.toml, lib/sparse/src/index/search_context.rs
While testing the index integration in https://github.com/qdrant/qdrant/pull/2900 I realized that the sparse search can under fetch and that it is fine.
By under-fetch I mean not retrieving all possible points in the index for large values of `top`.
This happens because only the indices of the sparse query vectors are considered during the search.
Therefore, none of the points **without an intersection** of dimensions with the query vector will ever be retrieved.
This PR makes this behavior clearer by adding two unit tests for the underlying cursor manipulation infrastructure.
=> Document and test underfetching with sparse vectors

Cargo.lock, lib/collection/src/shards/local_shard_operations.rs, lib/segment/Cargo.toml, lib/segment/src/vector_storage/query/reco_query.rs, lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs, openapi/tests/openapi_integration/test_recommend.py
Reported in Discord:
https://discord.com/channels/907569970500743200/1168571201828946022
In short, using only one negative example would yield the same results as using only the same point but as a positive example when dealing with euclidean distance.
Why was this?
Euclidean distances are negated during search, so that the logic for keeping best candidates always considers higher is better for scores. For positive examples, our formula is basically pass-through, since it just chooses the similarity score without extra modifications. However, when choosing a similarity from a negative example, the choice was to square it and negate it, e.g. `-(max_negative * max_negative)`.
With this report we discovered that this formula fails to invert the order of candidates when their similarities are …
=> Fix recommend `best_score` formula

Cargo.lock, lib/collection/Cargo.toml, lib/collection/src/common/stoppable_task_async.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/collection/src/shards/transfer/transfer_tasks_pool.rs
Adds simple cancellation checks between each shard snapshot transfer step. This allows stopping half way through the shard transfer.
For this I've used [`CancellationToken`](https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html) rather than an atomic boolean. It is similar to <https://github.com/qdrant/qdrant/pull/2870>, which seems to be the way forward.
I've also refactored `StoppableAsyncTaskHandle` into `CancellableAsyncTaskHandle` to make use of `CancellationToken`.
This PR implements cancellation checking in just a basic way. The <ins>create snapshot</ins>, <ins>transfer/recover snapshot</ins> and <ins>transfer queue</ins> operations are currently not canceled in the middle by itself. Instead, each …
=> Simple cancellation in shard snapshot transfer

lib/segment/src/vector_storage/raw_scorer.rs
Only a documentation PR, updates the `RawScorer` composition diagram for taking into account the recently added `Query` trait
=> doc: update `RawScorer` composition diagram

docs/redoc/master/openapi.json, lib/segment/src/fixtures/payload_fixtures.rs, lib/segment/src/index/hnsw_index/hnsw.rs, lib/segment/src/index/mod.rs, lib/segment/src/index/plain_payload_index.rs, lib/segment/src/index/sparse_index/mod.rs, lib/segment/src/index/sparse_index/sparse_search_telemetry.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/telemetry.rs, lib/segment/src/vector_storage/mod.rs, lib/segment/src/vector_storage/sparse_raw_scorer.rs, lib/segment/tests/integration/main.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/Cargo.toml, lib/sparse/src/common/mod.rs, lib/sparse/src/common/sparse_vector_fixture.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs, lib/sparse/src/index/mod.rs, lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
This PR adds an implementation of `VectorIndex` for the sparse vector index.
Handles:
- deleted points
- query filter
- search telemetry
Includes new unit tests to make sure everything is working.
=> SparseVectorIndex implements VectorIndex

Dockerfile
... in unprivileged mode to avoid Docker named volumes being owned by the root user.
Currently, with this `docker-compose.yaml` file:
``` yaml
---
version: "3.8"
name: test
services:
qdrant:
image: qdrant/qdrant:v1.6.1-unprivileged
volumes:
- qdrant:/qdrant/storage/
volumes:
qdrant:
```
`docker compose up` fails:
```
...
test-qdrant-1  | 2023-11-02T20:24:57.189168Z  INFO storage::content_manager::consensus::persistent: Initializing new raft state at ./storage/raft_state.json
test-qdrant-1  | Error: Service internal error: Failed to write file: Permission denied (os error 13) at path "/qdrant/./storage/.atomicwriteZEuaWn"
test-qdrant-1 exited with code 1
```
If we change the container command to `ls -al` we see that the target of the Docker named volume is owned by the root user:
``` …
```
=> Precreate and chown `snapshots` and `storage` dirs

lib/segment/src/index/field_index/field_index_base.rs, lib/segment/src/index/field_index/numeric_index/tests.rs
Currently, if we insert new value in payload index with `add_point`, it only clears existing data if the new value is "parsable" (compatible with the index). 
But in reality, it can be any value, e.g. "null". That would mean that old value should still be removed from index even if the new one is not indexable.
Simple way to reproduce problem:
```
POST collections/benchmark/points/payload
{
"points": [1,2,3],
"payload": {
"c": null
}
}
```
=> Int indexing

lib/segment/src/index/hnsw_index/graph_layers_builder.rs
This PR changes `Vec::new` + `reserve(n)` to `Vec::with_capacity(n)`.
It should be more efficient.
Found via Clippy on Beta channel https://rust-lang.github.io/rust-clippy/master/index.html#/reserve_after_initialization
=> Improve sizing in GraphLayersBuilder

Cargo.lock
This PR updates 4 yanked crates reported by `cargo audit`.
Updated via `cargo update -p $crate-name`
=> Update yanked deps

docs/redoc/master/openapi.json, lib/collection/src/operations/cluster_ops.rs
It looks like `#[serde(default)]` is not required, and API works without it just fine
=> remove serde(default)

lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/tests.rs
Prevent a divide by zero panic in production if `self.get_max_values_per_point()` ends up being zero.
I'm unsure if the above function is ever expected to return zero, but I'll ask @IvanPleshkov to investigate that as he has a better understanding of these internals. Even if it should never return zero, I suggest to merge this first anyway because it's a good way to prevent a panic if something similar happens in the future.
Fixes the following panic:
```rust
2023-11-04T01:45:17.548852Z ERROR qdrant::startup: Panic occurred in file lib/segment/src/index/field_index/numeric_index/mod.rs at line 197: attempt to divide by zero    
2023-11-04T01:45:17.549736Z ERROR qdrant::startup: Panic backtrace: 
0: qdrant::startup::setup_panic_hook::{{closure}}
1: <alloc::boxed::Box<F,A> as …
```
=> Fix divide by zero panic, fall back to 0

lib/sparse/src/index/search_context.rs
I found a low hanging fruit while benching the sparse index search.
Using an unstable sort for the posting list yields large improvements on my local benchmarks.
e.g. rolling back to stable sort
```
sparse-vector-search-group/sparse-index-search
time:   [2.1994 ms 2.2515 ms 2.3023 ms]
change: [+29.512% +34.146% +39.613%] (p = 0.00 < 0.05)
Performance has regressed.
```
=> Faster search in sparse inverted index with unstable sort

lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/update_handler.rs
This transforms the `max_ack_version` parameter in the update handler from a shared mutex into a shared atomic.
It is required for safe shard snapshot transfer cancellation. For safety, it cannot rely on `async`/`await` which was used for locking, and a synchronous lock would block the runtime. An atomic parameter solves the issue.
As a bonus this removes some locking steps across our code base, and removes the `async` marker from some methods.
=> Transform `max_ack_version` from mutex into atomic

lib/api/src/grpc/proto/collections.proto, lib/api/src/grpc/proto/collections_internal_service.proto, lib/api/src/grpc/proto/collections_service.proto, lib/api/src/grpc/proto/health_check.proto, lib/api/src/grpc/proto/json_with_int.proto, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/proto/points_service.proto, lib/api/src/grpc/proto/qdrant.proto, lib/api/src/grpc/proto/qdrant_internal_service.proto, lib/api/src/grpc/proto/raft_service.proto, lib/api/src/grpc/proto/shard_snapshots_service.proto, lib/api/src/grpc/proto/snapshots_service.proto
This commit adds the csharp_namespace option to proto files, allowing the C# gRPC client generated from the protos to be generated with the namespace used in the official .NET client, without needing to patch the values in.
Closes qdrant/qdrant-dotnet#3
=> Add csharp_namespace option to protos

lib/segment/Cargo.toml, lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/mod.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs
This PR adds the benchmark infrastructure for sparse vector search.
e.g
This enables to optimize the underlying implementation (e.g https://github.com/qdrant/qdrant/pull/2937) and size properly the filter based search heuristic in the future.
To make this possible, some fixture files were refactored and extracted into the segments crate lib code,
=> Sparse vector search benchmarks

lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/common/cancel/src/blocking.rs, lib/common/cancel/src/future.rs
Depends on <https://github.com/qdrant/qdrant/pull/2907>.
In the shard snapshot transfer logic we use `queue_proxy_into_forward_proxy()` method to safely transform one shard type into the other. This method could have a long runtime, for example, when a lot of updates have to be transferred to a remote.
This PR adds support for cancelling this process early through a `CancellationToken`. Not removing the queue proxy here on cancellation is fine because our shard transfer retry logic does this for us on (cancellation) failure.
This also defines cancellation safety in some function comments.
2. [ ] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to …
=> Support cancellation in queue proxy to forward proxy method

lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/sparse_index/sparse_search_telemetry.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/common/sparse_vector_fixture.rs, lib/sparse/src/index/posting_list.rs
This PR introduces benchmarks for various access pattern on the sparse index vector.
The idea is to gather data to find the sweet spot for a potential fallback to plain & payload search.
Run it yourself with:
`cargo bench -p segment --bench sparse_index_search`
The current parameters are:
- 50k points
- sparse vector query with 200 values
- top 10
- with and without filter
- with and without payload index
- `inverted-index`: sparse search without filter
- `inverted-index-filtered-payload-index`: sparse search with filter on indexed payload key
- `inverted-index-filtered-payload-plain`: sparse search with filter on non-indexed payload key
- `payload-index`: plain search using filter on indexed payload key
- `plain-storage`: plain search using filter on non-indexed payload key
While playing …
=> Benchmark sparse filter plain search

lib/segment/src/common/vector_utils.rs, lib/segment/src/vector_storage/chunked_vectors.rs
Fixes the `try_set_capacity{,_exact}` functions. Our logic was wrong.
The [`reserve`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve) function does not reserve additional capacity, but it reserves capacity to fix an additional extra items over `len`.
I've added some unit tests to confirm the change is correct.
=> Fix `try_set_capacity` functions

openapi/tests/openapi_integration/test_discovery.py
Since context part of discover search moves in integer steps, it is not a guarantee that same order (and scores) will be the result of using two different contexts and same target. 
So, this assertion shouldn't be here.
=> fix `test_discover_same_target`

lib/segment/src/index/field_index/full_text_index/inverted_index.rs, lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/map_index/mutable_map_index.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/hnsw_index/graph_layers_builder.rs, lib/segment/src/index/hnsw_index/point_scorer.rs, lib/segment/src/vector_storage/chunked_vectors.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs
I looked into the way we use `reserve{,_exact}` in our code base in <https://github.com/qdrant/qdrant/pull/2960>. This are some other changes with micro optimizations I made next to that. Nothing super significant, but I guess nice to haves.
All business logic is unchanged.
=> Some micro optimizations in reserve/resize usage

.github/workflows/integration-tests.yml, lib/storage/src/content_manager/snapshots/download.rs, lib/storage/src/content_manager/snapshots/recover.rs, src/actix/api/snapshot_api.rs, src/actix/certificate_helpers.rs, src/actix/helpers.rs, src/actix/mod.rs, src/common/http_client.rs, src/common/mod.rs, src/common/snapshots.rs, src/tonic/api/snapshots_api.rs, src/tonic/mod.rs, tests/tls/test_tls_snapshot_shard_transfer.sh
Required for #2432.
During snapshot shard transfer, the __recipient__ of the transfer downloads a shard snapshot from __sender__ of the transfer using shard snapshot HTTP API (because there's no standard support for file downloads in gRPC).
It is possible to enable HTTPS for HTTP API, but required TLS certificates are not _yet_ propagated to the HTTP client that is used to download shard snapshot, so snapshot shard transfer fails if HTTPS is enabled.
This PR fixes this by initializing HTTP client with all required TLS magic.
=> Add custom TLS certificate support for remote snapshot downloads to snapshot recover APIs

lib/collection/src/collection/shard_transfer.rs, lib/collection/src/shards/channel_service.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/shard_transfer.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/shards/transfer/mod.rs, lib/collection/src/shards/transfer/shard_transfer.rs, lib/common/cancel/src/blocking.rs, lib/common/cancel/src/future.rs, lib/storage/src/content_manager/toc/mod.rs, src/tonic/api/collections_internal_api.rs
Tracked in #2432.
This PR continues the work in #2918 and makes most of the shard transfer methods and functions cancel safe.
There are a bunch of `TODO`s added by this PR, but I think they should be left as-is for now, and can be worked on in the following PRs.
=> Improve abort/cancellation support for shard transfer

docs/grpc/docs.md, docs/redoc/master/openapi.json, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/collection/mod.rs, lib/collection/src/collection/payload_index_schema.rs, lib/collection/src/collection/point_ops.rs, lib/collection/src/collection/sharding_keys.rs, lib/collection/src/collection/snapshots.rs, lib/collection/src/collection/state_management.rs, lib/collection/src/collection_state.rs, lib/collection/src/operations/types.rs, lib/collection/src/shards/local_shard_operations.rs, lib/storage/src/content_manager/collection_meta_ops.rs, lib/storage/src/content_manager/consensus_manager.rs, lib/storage/src/content_manager/toc/collection_meta_ops.rs, src/actix/api/update_api.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs, src/tonic/mod.rs
Tracking: https://github.com/qdrant/qdrant/issues/2807
Creation of new shards requires initializing a proper payload index initialization.
In current storage organization, we don't have centralized storage for payload index information, which makes synchronization of payload index info problematic. 
This PR initiates a transition into the direction of the collection-level payload index storage.
It introduces:
- Storage of payload index info inside Collection structure
- Consensus-level operations to create and delete payload field index
- Migration for the API from collection level to consensus level
There are, however, some compromises, I had to make:
- Collection-level operation is still required to guarantee equivalent behavior with `wait=True` and returned sequence number in the …
=> Shard key index consistency

lib/collection/benches/batch_search_bench.rs, lib/collection/src/collection/search.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/recommendations.rs, lib/collection/src/shards/dummy_shard.rs, lib/collection/src/shards/forward_proxy_shard.rs, lib/collection/src/shards/local_shard_operations.rs, lib/collection/src/shards/proxy_shard.rs, lib/collection/src/shards/queue_proxy_shard.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/read_ops.rs, lib/collection/src/shards/shard_trait.rs, lib/collection/tests/integration/collection_test.rs, lib/collection/tests/integration/grouping_test.rs, lib/collection/tests/integration/multi_vec_test.rs, lib/collection/tests/integration/pagination_test.rs, lib/collection/tests/integration/snapshot_recovery_test.rs, lib/storage/src/content_manager/toc/point_ops.rs, src/actix/api/search_api.rs, src/common/points.rs, src/tonic/api/points_api.rs, src/tonic/api/points_common.rs, src/tonic/api/points_internal_api.rs
Last version introduced duplicated search methods for the purposes of the migration to a unified internal API for extendable modes of the search.
This PR removed duplication and completely switches search into the new version of internal API.
This change is required, as custom sharding requires a significant change in those search methods and duplication expected changes seemed unpractical.
Compatibility notes: this change makes migration from versions <=1.5 directly to >=1.7   (skipping 1.6.x) potentially error-prone. In particular: search requests between two nodes with too different versions in cluster mode will fail. This, however, doesn't violate the contract of supporting backward compatibility & migration compatibility for one minor version.
=> Remove deprecated search methods

src/consensus.rs
I haven't check that it have any effect on misfire of `sync_local_state`, but it looks safer to have this condition rather than not have.
=> check that there are no pending operations, before syncing local state

lib/collection/src/collection_manager/fixtures.rs, lib/collection/src/collection_manager/holders/proxy_segment.rs, lib/collection/src/collection_manager/segments_searcher.rs, lib/collection/src/operations/point_ops.rs, lib/collection/tests/integration/multi_vec_test.rs, lib/segment/src/common/mod.rs, lib/segment/src/common/utils.rs, lib/segment/src/data_types/named_vectors.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/fixtures/segment_fixtures.rs, lib/segment/src/segment.rs
Sparse vector index integration step. Propagate `Vector` type with sparse vector into `NamedVectors` struct.
=> Integrate vector into NamedVectors struct

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/storage/Cargo.toml
This PR bumps our WAL dependency to its latest version.
The motivation is to tackle this security alert https://github.com/qdrant/qdrant/security/dependabot/56
It happens because the current WAL pulls an outdated `rustix` version via `fs4` 0.6.
The latest WAL version already contains an update to `fs4` 0.7.
=> Bump WAL for security issue in outdated rustix

lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs, lib/sparse/src/index/inverted_index/mod.rs
This PR fixes the indexed vector count for the sparse vector index.
The are two bugs:
- empty sparse RAM index would report a size of 1 instead of 0
- loading a non empty memmap index would report a size of zero
The logic for keeping track of the number of indexed points has been pushed lower into the `InvertedIndex` trait to enable different implementations.
=> Fix vector count in sparse index

lib/segment/benches/sparse_index_search.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/index/sparse_index/mod.rs, lib/segment/src/index/sparse_index/sparse_index_config.rs, lib/segment/src/index/sparse_index/sparse_search_telemetry.rs, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/src/vector_storage/sparse_raw_scorer.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/common/sparse_vector.rs, lib/sparse/src/common/sparse_vector_fixture.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs
This PR adds a simple fallback to filtered search based on the cardinality estimated.
The fallback is done using a simplified version of the heuristic done for HNSW.
While writing tests to assert the equivalence of the results between inverted index and plain search, I noticed two issues.
1 - The inverted index does not handle negative weights whereas plain search does.
Negative weights do not interact well with pruning, I will propose a fix in a different PR
2 - The plain search is returning more vector than the inverted index
It happens for the vectors which have no intersections with the query vector in dimension.
The sparse inverted index never returns those, because those posting lists are not explored.
Whereas the plain search returns those and scores them zero.
The proposed …
=> Add possible fallback to plain search for sparse vectors

lib/segment/Cargo.toml, lib/segment/benches/sparse_index_build.rs, lib/sparse/src/index/inverted_index/inverted_index_mmap.rs, lib/sparse/src/index/posting_list.rs
This PR adds benchmark for building the sparse index vector.
The takeaway is that:
- building the inverted index via repeated upsert operations is very fast 
- the binary search is the most expensive operation (annotated in source code)
- converting to mmap is very fast
- found a bug in computing vector count for mmap which I will fix in a next PR
=> Benchmark sparse index build

Cargo.lock
Fixes <https://github.com/qdrant/qdrant/pull/2988>.
Covers security alerts:
- https://github.com/qdrant/qdrant/security/dependabot/53
- https://github.com/qdrant/qdrant/security/dependabot/54
- https://github.com/qdrant/qdrant/security/dependabot/55
- https://github.com/qdrant/qdrant/security/dependabot/56
We still have `rustix >= 0.37.0, < 0.37.25` usages in our `dev` branch which is marked as vulnerable. This bumps them to 0.37.27 to fix it, making the above PR obsolete once we cherry-pick into `master`.
We had:
```bash
$ cargo tree | grep rustix
│   │   └── rustix v0.38.21
│   │   │   └── rustix v0.37.19
│   │   │   ├── rustix v0.37.19 (*)
│   │   │   └── rustix v0.36.13
│       │   └── rustix v0.38.21 (*)
│       ├── rustix v0.38.21 (*)
```
2. …
=> Bump rustix 0.37.x to 0.37.27 to fix vulnerability

Cargo.lock
From `cargo audit`
```
Crate:     atty
Version:   0.2.14
Warning:   unsound
Title:     Potential unaligned read
Date:      2021-07-04
ID:        RUSTSEC-2021-0145
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0145
Dependency tree:
atty 0.2.14
└── inferno 0.11.13
└── pprof 0.12.1
├── segment 0.6.0
│   ├── storage 0.2.0
│   │   └── qdrant 0.11.1
│   ├── qdrant 0.11.1
│   ├── collection 0.4.2
│   │   ├── storage 0.2.0
│   │   └── qdrant 0.11.1
│   └── api 0.11.1
│       ├── storage 0.2.0
│       ├── qdrant 0.11.1
│       └── collection 0.4.2
└── collection 0.4.2
```
It is only a dev dependency but we should strive for zero warnings anyway.
Fixed with `cargo update inferno`
=> Update inferno to remove vulnerability on atty

tests/consensus_tests/test_shard_snapshot_transfer.py, tests/consensus_tests/test_shard_snapshot_transfer_cancel.py
- Fixes <https://github.com/qdrant/qdrant/issues/3006>:
Have bigger dataset and shorter cancel time to make it less likely for the transfer to complete before it is being cancelled.
- Fixes <https://github.com/qdrant/qdrant/issues/3007>:
Throttle updates 10 times harder, may still have been too much on a slow CI server.
- Fixes <https://github.com/qdrant/qdrant/issues/3008>:
I suspect that some points still had to propagate through the cluster, it now sleeps 1 second to give it some time.
This attempts to fix the above three tests. They were already working fine in previous runs for me. We'll have to see how these function on CI and potentially improve them further if issues still arise.
As a bonus I've added an additional test …
=> Attempt to fix flaky shard snapshot transfer tests

lib/sparse/src/index/posting_list.rs, lib/sparse/src/index/search_context.rs
This PR improves the sparse index pruning algorithm on several aspects.
- clearer implementation that makes each case explicit
- fixed two bugs related strict equality and wrong usage of `max_next_score`
- improved performance by replacing the posting lists sort by pushing the longest to the front.
Future work:
- support negative weights
- trigger pruning only if it makes sense
=> Improve sparse index pruning

tests/consensus_tests/test_shard_snapshot_transfer_cancel.py
Right after merging <https://github.com/qdrant/qdrant/pull/3009>, it [failed](https://github.com/qdrant/qdrant/actions/runs/6875240092/job/18698432683) again.
This removes the timeout of 0.2 seconds and cancels right away.
If this still ends up being problematic I'll remove the test.
=> Cancel shard snapshot transfer test right away

lib/collection/src/common/fetch_vectors.rs, lib/collection/src/discovery.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/types.rs, lib/collection/src/recommendations.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/async_raw_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_custom_query_scorer.rs, lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs, lib/segment/src/vector_storage/query/context_query.rs, lib/segment/src/vector_storage/query/discovery_query.rs, lib/segment/src/vector_storage/query/mod.rs, lib/segment/src/vector_storage/query/reco_query.rs, lib/segment/src/vector_storage/query_scorer/custom_query_scorer.rs, lib/segment/src/vector_storage/raw_scorer.rs
Next cherry-pick from the magic branch with sparse vector experiments https://github.com/qdrant/qdrant/pull/2802
In this PR introduces `Vector` type in query types (context, discovery, ect). Also it removes temporary conversion from `Vector` into `Vec<f32>`.
=> integrate sparse vectors into queries

lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/common/sparse_vector_fixture.rs, lib/sparse/src/index/search_context.rs
This PR deactivates at runtime the pruning of the sparse index for queries containing negative values.
A small reminder, the pruning is an optimization that should not affect correctness.
This is necessary because the pruning mechanism is designed to track the max value in each posting list in order find a cutoff points.
However, the multiplication of two negative numbers can create large positive values that the max value tracked did not account for.
For this reason, having the pruning enabled for negative query values generates bad pruning choices.
I tried tracking instead the max absolute value but it causes more problems during scoring.
The bottom line is that:
- we support negative and positive values in index and queries
- queries with negative values might be slower on indexes with …
=> Deactivate sparse index pruning for negative query vectors

lib/collection/src/collection/collection_ops.rs, lib/collection/src/collection/point_ops.rs, lib/collection/src/collection/search.rs, lib/collection/src/shards/shard_holder.rs
Tracking: https://github.com/qdrant/qdrant/issues/2807
If shard key is available, changes in this PR will propagate them into the response
=> fill read response with shard_key

lib/storage/src/content_manager/toc/transfer.rs
The attribute is obsolete for this trait implementation, as it doesn't implement any `async` functions.
=> Trait implementation does not require async-trait attribute

Dockerfile
Fixes <https://github.com/qdrant/qdrant/issues/2819>.
Rust [v1.74.0 ](https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html) was released today.
This bumps our project to use it, which also unblocks other pending changes.
We [skipped](https://github.com/qdrant/qdrant/pull/2794) version 1.73.x as it caused a segfault during compilation (<https://github.com/rust-lang/rust/issues/116668>). This has been tackled in v1.74.0 by updating the LLVM backend to v17.0.4 <https://github.com/rust-lang/rust/pull/117436>. I've confirmed that this Rust release includes the updated LLVM update:
```bash
$ rustc --version --verbose
rustc 1.74.0 (79e9716c9 2023-11-13)
LLVM version: 17.0.4
```
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` …
=> Bump Rust to v1.74.0

lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/vector_storage/chunked_vectors.rs, lib/segment/src/vector_storage/dynamic_mmap_flags.rs, lib/segment/src/vector_storage/mmap_vectors.rs, lib/segment/src/vector_storage/mod.rs
Depends on <https://github.com/qdrant/qdrant/pull/3032>.
Rust 1.73 stabilized [`div_ceil`](https://doc.rust-lang.org/std/primitive.usize.html#method.div_ceil). We can now use that instead of our own implementation.
=> Use stabilized `div_ceil` from from `std`

lib/segment/src/common/rocksdb_wrapper.rs
context: deployments with large number of collections are full of log files
This PR configures RocksDB to remove more aggressively its log files.
The changes are:
- limit the number log files kept to 1
- instruct RocksDB to reuse the log file by overwriting it
- increase the cleanup frequency of all RocksDB related files
=> Delete RocksDB files more aggressively

docs/grpc/docs.md, lib/api/src/grpc/proto/points.proto, lib/api/src/grpc/proto/points_internal_service.proto, lib/api/src/grpc/qdrant.rs, lib/collection/src/operations/conversions.rs
- Renames `context_pairs` to `context` in grpc to match the rest counterpart
- Also adds `TargetVector` with a  `oneof` to future-proof target in grpc
=> Discovery API: Rename `context_pairs` -> `context` in grpc

lib/segment/benches/sparse_index_build.rs, lib/segment/src/fixtures/sparse_fixtures.rs, lib/segment/src/vector_storage/simple_sparse_vector_storage.rs, lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs
Sparse vectors are hardcoded to work with dot product for the moment. 
We can cleanup the simple sparse storage implementation to not care about it.
=> Remove distance from sparse storage

Cargo.lock, Cargo.toml
Supersedes <https://github.com/qdrant/qdrant/pull/3000>.
- Bumps `tracing-log` to 0.2.0
- Bumps `tracing-subscriber` to 0.3.18
=> Bump tracing-log to 0.2.0

Cargo.lock, Cargo.toml, docs/redoc/master/openapi.json, src/schema_generator.rs
I noticed those definitions were missing when generating the Python client.
=> Register Sparse JSON schema

Cargo.lock, Cargo.toml, lib/collection/Cargo.toml, lib/storage/Cargo.toml
Update to the latest version of the WAL which contains a significance performance improvement to the crc computation.
see https://github.com/qdrant/wal/pull/66
=> Update WAL to use crc32c

lib/segment/src/vector_storage/sparse_raw_scorer.rs, lib/sparse/src/common/sparse_vector.rs
This PR merges the overlapping check with the scoring for sparse vector.
The overlap check was introduced to make sure the plain search and the index search are returning the same elements.
However this check adds a non negligible overhead and looks a lot like scoring.
This PR merges the function to restore previous performance and to keep the code less duplicated.
```
sparse-vector-search-group/plain-storage
time:   [101.01 ms 101.22 ms 101.41 ms]
change: [-9.5036% -9.2767% -9.0607%] (p = 0.00 < 0.05)
```
=> Merge scoring and overlap check for sparse vector

lib/segment/benches/sparse_index_search.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/common/sparse_vector_fixture.rs, lib/sparse/src/index/search_context.rs
This PR introduces a simple heuristic to drastically decrease the number of pruning operations during sparse vector search.
Instead of trying to prune on all search candidates, we only try to prune when the worst best score changes.
This is a good signal that we should try pruning again as the eviction threshold increased.
This increases performance significantly on our synthetic benchmark.
```
sparse_vector size = 196
sparse-vector-search-group/inverted-index
time:   [15.326 ms 15.374 ms 15.422 ms]
change: [-42.208% -41.984% -41.762%] (p = 0.00 < 0.05)
```
=> Better heuristic for sparse vector pruning

Cargo.lock, lib/segment/Cargo.toml, lib/segment/src/index/visited_pool.rs
We observe a significant degradation in tail latencies when there are more than 16 concurrent searches. Profiling reveals that the culprit is the visited list allocation under the exclusive lock. This PR is a proposal to increase the maximum visited-list pool size from 16 to 128. This is a reasonable maximum based on logical core count available on modern server processors suitable for the most extreme cases when a single segment is being searched by all hardware threads.
We have benchmarked this change and observe an ~80-90% reduction in 99th, 99.9th, and 99.99th percentile latencies under 27 concurrent searches. The benchmarked collection consists of 5 indexed segments of 2M points each.
Prior to the change:
```
p50: 19ms
p90: 23ms
p99: 221ms
p999: 295ms
p9999: 330ms
```
After:
```
p50: …
```
=> Increased maximum visited-list pool size to 128

Cargo.lock, Cargo.toml, lib/api/Cargo.toml, lib/api/src/grpc/conversions.rs, lib/collection/Cargo.toml, lib/collection/src/operations/consistency_params.rs, lib/collection/src/operations/conversions.rs, lib/collection/src/operations/snapshot_ops.rs, lib/storage/Cargo.toml
- https://github.com/hyperium/tonic/pull/1401 has been merged, so we should be able to bump tonic and prost versions now. 
- `from_32` was deprecated in favor of `TryFrom::try_from`, so that's the other source of changes here.
=> chore: bump to tonic 0.10.2 and prost to 0.12.2

docs/redoc/master/openapi.json, lib/segment/src/index/sparse_index/sparse_vector_index.rs, lib/segment/tests/integration/sparse_vector_index_search_tests.rs, lib/sparse/src/common/sparse_vector.rs, lib/sparse/src/index/inverted_index/inverted_index_ram.rs
This PR removes the validation that a sparse vector must be non-empty.
The rational is that it is overly restrictive given that:
- embeddings might generate such vectors
- users might want to only attach payload to a sparse vector
Instead of forcing more work onto the user, we decided to loosen up that constraint.
Empty sparse vectors cannot be indexed but can be found in storage through the scrolling API.
=> Accept empty sparse vectors

src/tracing.rs
Fix `NO_COLOR` (and others) not disabling colored log levels in stdout.
Before:
After:
Report: https://discord.com/channels/907569970500743200/1175945733787107489/1176513151387320392
=> Only use ANSI in logging if we should colorize

lib/collection/src/collection/mod.rs, lib/collection/src/collection/shard_transfer.rs, lib/collection/src/collection/sharding_keys.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/update.rs, lib/collection/src/shards/shard_holder.rs, lib/collection/src/tests/snapshot_test.rs, lib/collection/tests/integration/common/mod.rs, lib/collection/tests/integration/snapshot_recovery_test.rs, lib/storage/src/content_manager/toc/collection_container.rs, lib/storage/src/content_manager/toc/create_collection.rs, lib/storage/src/content_manager/toc/mod.rs
`sync_local_state` is called on every consensus tick (which is 100 ms by default). Under certain conditions, this may cause a cluster node to spam `SetShardReplicaState(Dead)` consensus proposals (that would ultimately be rejected) every 100 ms.
This PR extends `sync_local_state` to also abort shard transfer (if one exists) along with `SetShardReplicaState(Dead)` notification, which (once propagated through consensus and applied on this node) would partially/temporarily disable `SetShardReplicaState(Dead)` spam. (And further improvements in #3013 and #3026 makes this a complete/permanent fix for `SetShardReplicaState(Dead)` spam.)
Resolves #2975.
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to …
=> Abort shard transfer during `sync_local_state`, if transfer-er node failed (#2975)

lib/collection/src/grouping/builder.rs, lib/collection/src/grouping/group_by.rs, lib/collection/src/grouping/types.rs, lib/collection/src/recommendations.rs, lib/collection/tests/integration/grouping_test.rs
Refactors group-by to insert a `CoreGroupRequest` item in the pipeline between interface and execution, so that vectors are only fetched at the beginning of each group-by.
This also sets up for creating a `discover/groups` endpoint easier.
=> Refactor group-by to fetch vectors only once

lib/collection/src/shards/replica_set/update.rs
There's currently a slight consistency "gap" in how we handle updates:
- `Partial` nodes _have to_ be able to accept and apply update requests (from the user and other nodes)
- this is required for the correctness/consistency of shard transfers
- there's a valid scenario, when all available replicas of a shard are in `Partial` state, and the last `Active` replica is _practically_ dead
- it can be trivially reproduced:
- cluster of 3 nodes
- collection with replication factor 2
- initiate shard transfer from one replica to another
- kill transfer-sender replica in the middle of shard transfer
- you now have a single available `Partial` node, and the only `Active` node is dead
- similar condition can happen in production
- in this case, the user can send an update to the `Partial` node that …
=> Report update error, if update was not applied to at least one active replica (#2976)

lib/collection/src/collection/mod.rs, lib/collection/src/shards/remote_shard.rs, lib/collection/src/shards/replica_set/mod.rs
This PR adds explicit "health check" before requesting shard transfer, to see if the other node is _available_. 
It is possible for the cluster to be in a state, when the last `Active` node is offline/unavailable, and without this check `Dead` node may request shard transfer (and switch into `Partial`) a bit too soon, which may then enable a bunch of other issues (e.g., #2975/#3012 and #2976/#3013).
Resolves #2977. Currently based on #3013, will be rebased on `dev` once it's merged.
=> Add a health check before starting shard transfer during `sync_local_state` (#2977)

lib/collection/src/collection/mod.rs, lib/collection/src/shards/replica_set/locally_disabled_peers.rs, lib/collection/src/shards/replica_set/mod.rs, lib/collection/src/shards/replica_set/snapshots.rs, lib/collection/src/shards/replica_set/update.rs
This PR adds a "backoff" when synchronizing local state to consensus during `sync_local_state`.
This should not be necessary after changes in #3012/#3013/#3026 but still seems "nice to have".
Currently based on #3026, will be rebased on `dev` once it's merged.
=> Add backoff when syncing locally disabled peers state to consensus

tools/clean-old-rocksdb-logs.sh
This script wipes old and obsolete RocksDB log files from disk. This is very useful to clean up disk space in case of a Qdrant crash loop, in which case tens of thousands of these may be created. We've used it in cloud before. Placing it here just makes it easily accessible.
More specifically, this keeps the 2 most recent old and obsolete log files and deletes other ones. The number of files to keep can be tweaked.
Usage, dry run for testing its effects:
```bash
$ cd ./storage
$ ../tools/clean-old-rocksdb-logs.sh
This script removes old and obsolete log files to clean up disk space.
It is potentionally dangerous. Always make sure you have a backup before running this.
Qdrant must be stopped before running this script.
Dry run? [y/n]: y
Cleaning collection: collections/benchmark
Cleaning …
```
=> Add tool script to clean old RocksDB log files from disk

src/main.rs
When migrating from local -> distributed,
qdrant should explicitly fill consensus WAL with missing operations, so they could be replicated to other collection.
It appears, that in current implementation the migration requires one extra parallel thread of execution.
If we try to run migration of low CPU machine (<=2 CPU), the allocated thread pool doesn't have enough processes to execute the operation, which results in stuck consensus:
```
"raft_info": {
"term": 0,
"commit": 0,
"pending_operations": 0,
"leader": null,
"role": null,
"is_voter": true
}
```
This PR changes `spawn` into `block_on` for migration process, which should prevent over-usage of threads.
An alternative could be to allocate +1 thread minimum by default or use different runtime.
But the current option looks the …
=> spare one extra worker by replacing spawn with block_on

lib/segment/src/index/field_index/geo_index.rs, lib/segment/src/index/field_index/map_index/mod.rs, lib/segment/src/index/field_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mod.rs, lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs, lib/segment/src/index/field_index/numeric_index/tests.rs
I took a deeper look into the `max_values_per_point` field of index types and what the purpose of it is.
This PR:
- defaults `max_values_per_point` to `0` rather than `1`
- fixes potential divide by zero panic for the geo index if it contained no items
- adds some unit tests to ensure indexes work properly if it doesn't contain points
- shortcuts cardinality estimation if `max_values_per_point` is `0`
=> Default `max_values_per_point` to zero, add tests

lib/segment/src/common/rocksdb_wrapper.rs
Related issue: https://github.com/qdrant/qdrant/issues/3090
WAL consistency docs: https://github.com/facebook/rocksdb/wiki/WAL-Recovery-Modes
Reasoning:
In Qdrant, we rely on shard-level WAL for replaying records, rocksd's internal WAL is ignored on all internal insert operations anyway, so it looks safe to use `kTolerateCorruptedTailRecords` option in our case
=> Tolerate rocksdb tail wal errors

lib/segment/src/common/rocksdb_wrapper.rs
During investigating this error:
Found a possible scenario of how to break flush thread and reproduce this error.
Intro:
We have an async segment flushing operation. This async operation captures references to the DB object and the name of the column family it should use for the index. 
see https://github.com/qdrant/qdrant/blob/591a7e7c7f6b3427603a2a87f517e1452a7d9c44/lib/segment/src/common/rocksdb_wrapper.rs#L166
If user or some other operation removes the index after flusher closure is created, but before it executed, it is possible that during the flusher execution it will try to flush non-existing CF.
This PR:
demotes error of not-found-cf into warning, cause it looks like a valid situation to have.
Addressed Concerns:
- Demoting the error should not create unpredictable behavior, as …
=> Demote column family not found during flush

lib/storage/src/content_manager/shard_distribution.rs
Currently, the order of peers is always consistent when generating shard distributions.
If the number of shards is a multiple of the number of peers, this is fine. But for example, if you have less shards than the number of peers things get problematic. In that case, all shards (across different collections) always end up on the  same nodes, leaving other nodes uninhabited.
For example, if you have 3 nodes (peer 111, 222, 333) and you create 4 collections on it all with two shards, the shard distributions will end up being:
- 1: 111, 222
- 2: 111, 222
- 3: 111, 222
- 4: 111, 222
That is because the second level of ordering for placement is based on the peer ID, always preferring lower peer IDs. In the above case, peer 333 will remain uninhabited.
To fix this I've added a randomized `bias` …
=> Randomize peer order for shard placements

lib/segment/src/segment.rs
Fixing bug found while testing sparse vector search using `with_vector`.
```
2023-11-29T13:42:02.017828Z  INFO actix_web::middleware::logger: 127.0.0.1 "PUT /collections/congruence_test_collection/points?wait=true HTTP/1.1" 200 91 "-" "python-httpx/0.16.1" 0.006373    
2023-11-29T13:42:02.325569Z ERROR qdrant::startup: Panic backtrace: 
0: qdrant::startup::setup_panic_hook::{{closure}}
at ./src/startup.rs:19:25
1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
2: std::panicking::rust_panic_with_hook
at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13
3: std::panicking::begin_panic_handler::{{closure}}
at …
```
=> Fix sparse vector search with_vector

lib/collection/src/operations/types.rs, lib/collection/src/tests/sparse_vectors_validation_tests.rs, lib/common/common/src/validation.rs, lib/segment/src/data_types/vectors.rs, lib/segment/src/vector_storage/query/context_query.rs, lib/segment/src/vector_storage/query/discovery_query.rs, lib/segment/src/vector_storage/query/reco_query.rs
I have added unnecessary validations in this PR: https://github.com/qdrant/qdrant/pull/3111 
Rollback validation for QueryEnum (and their fields down to discovery, ect) because it's not a part of REST API. It also simplifies some other validations.
=> Remove unnecessary validations for QueryEnum

Cargo.lock
The ahash dependency is using version 0.7.6, which was yanked. This PR updates it to the next version, 0.7.7.
=> Bump yanked dependency: ahash v0.7.6

lib/storage/src/content_manager/toc/collection_meta_ops.rs
We have debug log messages for creating, updating and deleting collections. This promotes them from debug to info.
I think these are important markers, and may function as some form of audit log to discover "hey this collection was indeed deleted". I've seen a few users now where it was unclear to them if a collection had been deleted through Qdrant.
The only concern is that they may introduce some noise if a user is creating/deleting a lot of collections. But we generally recommend against this anyway: https://qdrant.tech/documentation/guides/multiple-partitions/
3. [x] Have you checked your code using `cargo clippy --all --all-features` …
=> Promote collection create/update/delete debug messages to info

lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
The indexer optimizer decides if a segment should be rebuilt based on the vector sizes in bytes computed from the vector dimension.
The current implementation for sparse vectors returns zero which prevents the optimizer from running.
This PR proposes a simple scheme to compute an estimation based on the average size of sparse vectors.
- a segment rebuild all its indices regardless of the named vector triggering the rebuild 
- a.k.a rebuild HNSW because of sparse changes
- the current size estimations in the optimizer are not counting number of of actual vectors per named vectors
- mix setup dense & sparse will not trigger rebuild with high precision
=> Estimate sparse vector dimension for optimizer
