qdrant/qdrant

lib/collection/src/collection_manager/segments_searcher.rs

In the segments searcher retrieve logic we loop over points and keep their latest version.
This PR improves it by only hashing/looking up once, rather than three times. For this we use the entry API.
Note that this doesn't fix bad behavior, and it's just low hanging fruit in terms of performance improvement.

Hash/lookup point version only once, not 3 times

---

.github/workflows/integration-tests.yml
lib/collection/src/common/snapshots_manager.rs
lib/collection/src/operations/snapshot_storage_ops.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/common/common/src/lib.rs
lib/common/common/src/tempfile_ext.rs
lib/storage/src/content_manager/snapshots/download.rs
lib/storage/src/content_manager/snapshots/recover.rs
src/actix/api/snapshot_api.rs
src/common/snapshots.rs
tests/shard-snapshot-api.sh

It turned out that some shard snapshot operations (implemented in #4150) are buggy:
- [List all snapshots (shard)](https://api.qdrant.tech/api-reference/snapshots/list-shard-snapshots) always return an empty list (`[]`).
- [Recover from a snapshot (shard)](https://api.qdrant.tech/api-reference/snapshots/recover-shard-from-snapshot) and [Delete a snapshot (shard)](https://api.qdrant.tech/api-reference/snapshots/delete-shard-snapshot) fail.
It seems these bugs went unnoticed because the test [shard-snapshot-api.sh] is also buggy: it enables s3 in the config file, but it doesn't restart qdrant after that. As a result, this integration test doesn't test s3 scenario, but rather tests the local scenario twice.
[shard-snapshot-api.sh]: https://github.com/qdrant/qdrant/blob/9c20e9e27960228019b4606 …

Fix shard snapshot operations for s3

---

lib/sparse/src/index/inverted_index/inverted_index_ram.rs

It might be technically possible, that during insertion of spare vectors, the operation is interrupted and data is only persisted in vector storage but not vector index.
In this case on the attempt to overwrite this vector, we might try to delete from posting list which doesn't exist. 
This is rare but possible situation will lead to panic in the current version.
This PR allows to ignore deleting from non-existing posting list, but still keeps the debug assert for simpler debugging in a case.
related: https://github.com/qdrant/qdrant/issues/5231

do not fail if posting list does not exist on deletion

---

lib/segment/src/common/operation_error.rs
lib/segment/src/common/rocksdb_wrapper.rs
lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs

On a `perf` optimized build.
The problem is that we are capturing backtraces at a high frequency when trying to fetch non existent sparse vectors from RocksDB.
The proposed fix is to have a specialised function for getting optional value from RocksDB.
`./bfb --vectors-per-point 0 --sparse-vectors-per-point 1  --sparse-vectors 0.3 --num-vectors 100000`
- before: upload 28s
- after: upload 22s

[perf] Do not capture backtrace on get_sparse_vector_opt

---

Cargo.lock
lib/sparse/Cargo.toml
lib/sparse/src/index/inverted_index/inverted_index_ram.rs

Downgrade asserts which were introduced in https://github.com/qdrant/qdrant/pull/5232/files
Those are triggered if a sparse vector was persisted into storage, but was not persisted into inverted index.
This situation [can actually happen](https://github.com/qdrant/crasher/actions/runs/11347761734) after a crash therefore we should not halt the program.

Downgrade asserts into logs for sparse vector inconsistencies

---

lib/collection/src/collection_manager/optimizers/vacuum_optimizer.rs

We don't need the segment reference, so we remove it.
This is good because it removes carrying the segment reference over the life time of the segment holder.

Omit segment reference in worst segment return of vacuum optimizer

---

lib/collection/src/common/file_utils.rs
lib/collection/src/common/snapshots_manager.rs

Continuation of #5227.
This PR fixes the following bug: when s3 storage is used, a leftover temporary file appears after creating a shard snapshot.
```console
$ ls snapshots/tmp/                                                  
upload
$ curl -X POST http://localhost:6333/collections/q/shards/0/snapshots
{"result":{"name":"q-shard-0-2024-10-14-23-03-54.snapshot","creation_time":"2024-10-14T23:03:55","size":425984},"status":"ok","time":0.863852705}
$ ls snapshots/tmp/                                                  
q-shard-0-2024-10-14-23-03-54.snapshot-38We4I.tar  upload
```
Additionally, this PR makes the local (non-s3) case more robust: temporary files now getting cleaned up in case of an error.

Clean up temporary snapshot files

---

lib/storage/src/content_manager/consensus/consensus_wal.rs
lib/storage/src/content_manager/consensus_manager.rs
src/consensus.rs
src/settings.rs

Based on top of #5217.
This PR adds optional Raft WAL compaction. There's now a `compact_wal_entries` parameter in consensus config, that if set to a non-zero value, enables consensus WAL compaction every time it grows to N **committed/applied** entries. WAL is also compacted when Qdrant restarts (still following `compact_wal_entries` parameter).

Compact consensus WAL

---

lib/collection/src/collection_manager/segments_updater.rs

similar: https://github.com/qdrant/qdrant/pull/5219
While doing jemalloc profiling I found out that we are eagerly generating backtraces during points updates.

Fix eager backtrace generation

---

lib/collection/src/shards/channel_service.rs
lib/collection/src/shards/transfer/driver.rs
lib/collection/src/shards/transfer/snapshot.rs

This PR lets the shard snapshot transfer process to use the new streaming snapshot endpoint.
Additionally, it adds a `debug_assert` to catch shard transfer errors during integration tests.

Transfer shard snapshots using streaming endpoint

---

lib/api/src/grpc/conversions.rs
lib/collection/src/collection/sharding_keys.rs
lib/collection/src/config.rs
lib/collection/src/operations/types.rs
lib/common/common/src/ext.rs
lib/common/common/src/lib.rs
src/tracing/config.rs
src/tracing/default.rs
src/tracing/on_disk.rs

Continues with the philosophy of <https://github.com/qdrant/qdrant/pull/5254>.
This makes some [`or`](https://doc.rust-lang.org/std/option/enum.Option.html#method.or)s more lazy.
It also replaces some aggressive [`take`](https://doc.rust-lang.org/std/option/enum.Option.html#method.take)-out-and-put-back-in's with a new `replace_if_some` helper.

Make some or's more lazy

---

lib/segment/src/index/field_index/histogram.rs

There is even an assert for it underneath :broom:

Remove forgotten eprintln

---

lib/storage/src/content_manager/consensus/consensus_wal.rs
lib/storage/src/content_manager/consensus_manager.rs
src/consensus.rs
src/settings.rs
src/wal_inspector.rs

While working on WAL compaction I've refactored `ConsensusOpWal` (cause it was too confusing to work with) and decided to split it into separate PR. The behavior after refactoring should be exactly the same, just with (hopefully 🤞) cleaner code and some trivial optimizations.

Refactor `ConsensusOpWal`

---

lib/storage/src/content_manager/consensus/consensus_wal.rs

Fix the following warning on non-debug builds:
```
warning: unused variable: `new_entry_wal_index`
--> lib/storage/src/content_manager/consensus/consensus_wal.rs:230:17
|
230 |             let new_entry_wal_index = self.wal.append(&buf)?;
|                 ^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_new_entry_wal_index`
|
= note: `#[warn(unused_variables)]` on by default
warning: `storage` (lib) generated 1 warning
```
This slipped through in <https://github.com/qdrant/qdrant/pull/5217>.

Fix warning in ConsensusOpWal on non-debug builds

---

lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/replica_set/shard_transfer.rs
lib/collection/src/shards/shard.rs
lib/collection/src/shards/transfer/wal_delta.rs
lib/collection/src/wal_delta.rs

Fix a critical problem in WAL delta transfers which can cause missing updates, resulting in data inconsistencies.
First of all, during a WAL delta transfer, the target replica switches between these states:
1. Active: _regular behavior, before transfer_
2. Recovery: _get queued updates from transfer source, skip other updates_
3. Partial: _get last queued updates from transfer source, get all updates from other replicas_
4. Active: _regular behavior, after transfer_
The problem was in how different delta resolutions were handled. If the target shard was outdated and we resolved a diff, then everything was fine. If the target shard was already up-to-date and we resolved an empty diff, then problems occurred.
Imagine the target shard was up-to-date and we resolved an empty diff. In this …

Fix data race in WAL delta transfer causing inconsistencies

---

Cargo.toml

The `cargo.lock` already contains this version but the `cargo.toml` has not been updated.

Bump rustls-pki-types-1.10

---

lib/api/src/rest/validate.rs
src/common/inference/query_requests_rest.rs
src/common/inference/service.rs
src/common/inference/update_requests.rs

Requests like that:
```
POST /collections/sparse_charts/points/query
{
"query": {
"object": "hello red planet mars",
"model": "qdrant/bm25"
},
"using": "keywords"
}
```
will use 'query' mode when possible, for example in BM25

Inference Service, query requests (rest)

---

Cargo.lock
lib/storage/Cargo.toml
lib/storage/src/content_manager/snapshots/download.rs
lib/storage/src/content_manager/snapshots/recover.rs
lib/storage/src/content_manager/toc/temp_directories.rs
tests/shard-snapshot-api.sh

Fixup for #5227.
---
The PR #5227 introduced a new flaky CI failure ([example log](https://github.com/qdrant/qdrant/actions/runs/11459823247/job/31885178996?pr=5261)).
```
Failed to remove downloaded shards snapshot after recovery: No such file or directory (os error 2) at path "./snapshots/tmp/downloaded.snapshot"
curl: (22) The requested URL returned error: 500
2024-10-22T12:20:24.818833Z ERROR qdrant::actix::helpers: Error processing request: Service internal error: Can't restore snapshot in local mode with missing data at shard: /home/runner/work/qdrant/qdrant/./snapshots/tmp/test-collection-shard-0-downloaded.snapshotdjoHHc
2024-10-22T12:20:24.819113Z  INFO actix_web::middleware::logger: 127.0.0.1 "PUT /collections/test-collection/shards/0/snapshots/recover HTTP/1.1" 500 228 "-" …
```

download_file: use tempfile::Builder to avoid name collisions

---

lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs

Fix a data race where switching a replica to Recovery state may cause it to respond with stale data, even if wait=true is used on updates. Shortly after the inconsistency goes away. This affects both WAL delta and snapshot transfers.
The key element here is that consensus events are not applied on all nodes at exactly the same time. We normally take this in consideration but forgot an edge case.
To explain the problem, lets look at the following time table:
| Time | Consensus                     | Node 1 (n1)                   | Node 2 (n2)                    |
|-----:|-------------------------------|-------------------------------|--------------------------------|
| 1    | start transfer (n1->n2)       | start transfer (n1->n2)       |                                |
|      | …

Fix data race in replica state switching causing inconsistencies

---

lib/segment/src/common/operation_error.rs
lib/segment/src/index/sparse_index/sparse_vector_index.rs

The sparse vector index is created if it does not exist when trying to open it.
When the data path does not exist, an error regarding mismatched version is created,
The failure is not exceptional and does not require an expensive backtrace which is not returned to the user.

[perf] No backtrace on sparse vector index version mismatch

---

Cargo.toml

With this feature, both Rust code and linked C/C++ code will use jemalloc for memory allocation.
This would explain why the memory reported by jemalloc was too low, because it is missing RocksDB related allocations.
I can see the impact of this change in Heaptrack which seems unable to track Jemalloc allocations.
Before this change I see only RocksDB allocations and after I see nothing :)

Use Jemalloc unprefixed_malloc_on_supported_platform

---

Cargo.lock
Cargo.toml
docs/redoc/master/openapi.json
src/common/metrics.rs
src/common/telemetry.rs
src/common/telemetry_ops/memory_telemetry.rs
src/common/telemetry_ops/mod.rs

This PR adds the internal metric values from Jemalloc to our Prometheus metrics and telemetry.
e.g.
```
memory_active 31473664
memory_allocated 26469784
memory_metadata 9560160
memory_resident 43413504
memory_retained 53940224
```
With those numbers we will be able to track precisely memory fragmentation.
```
Fragmentation = (Active Memory − Allocated Memory​) / Active Memory
Fragmentation = (31473664 − 26469784) ​/ 31473664 ≈ 0.159
```

Report memory usage in metrics & telemetry

---

docs/redoc/master/openapi.json
lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/segment/src/fixtures/index_fixtures.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/plain_payload_index.rs
lib/segment/src/segment/entry.rs
lib/segment/src/telemetry.rs
lib/segment/src/types.rs
lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs

We need this to aggregate the size of replicas for CM.

Track vector storage usage in bytes for each of the segments

---

lib/collection/src/collection/distance_matrix.rs

It is not needed to build a merged filter using the client's filter when selecting by point ids.
We have already applied this filter to select the point ids.
This PR also adds a TODO for the next possible optimization.

Distance matrix does not need to use client's filter when looking up by ids

---

lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/transfer/wal_delta.rs

Improvement on <https://github.com/qdrant/qdrant/pull/5271>.
If we resolve an empty WAL delta we still create a queue proxy to transmit new updates.
The queue proxy expects the version to start sending updates from. Before this PR we gave it our last version, which means the last operation would be sent a second time.
This is not necessary and we can bump the version to only transmit new updates.
I've tested this change locally on 1000 WAL delta transfers.

Fix off by one in WAL delta causing operation to be sent twice

---

lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/visited_pool.rs

This PR optimizes `VisitedList` by switching counters from `usize` to `u8` (and memset them every 256 iterations). Surprisingly, this change improves not only the memory usage, but also the search/build performance.
```console
$ cargo bench -p segment --bench hnsw_search_graph # old
hnsw-index-search-group/hnsw_search
time:   [634.32 µs 640.56 µs 646.44 µs]
…
$ cargo bench -p segment --bench hnsw_search_graph # new
hnsw-index-search-group/hnsw_search
time:   [596.08 µs 601.57 µs 606.93 µs]
```
Large graphs are also improved. Graph build time (dim=4, npoints=10_000_000): 892s → 640s.

VisitedList: Vec<usize> -> Vec<u8>

---

tests/basic_api_test.sh
tests/basic_grpc_test.sh
tests/basic_multivector_grpc_test.sh
tests/basic_query_grpc_test.sh
tests/basic_sparse_grpc_test.sh
tests/basic_sparse_test.sh
tests/openapi/conftest.py
tests/openapi/helpers/helpers.py
tests/openapi/helpers/settings.py
tests/openapi/test_multi_vector.py
tests/openapi/test_multi_vector_uint8.py
tests/openapi/test_multi_vector_unnamed.py
tests/openapi/test_query.py
tests/openapi/test_shard_snapshot.py
tests/openapi/test_snapshot.py

* `QDRANT_HOST` variable is used by all openapi tests, removed its copies from  `test_multi_vector_uint8.py`, `test_multi_vector_unnamed.py`, `test_query.py`,  `test_shard_snapshot.py`, and `test_snapshot.py`
* Added optional `QDRANT_HOST_HEADERS` env variable to set custom HTTP headers  in order to reach Qdrant instance behind a reverse proxy. The content of the  variable is JSON payload, e.g. `{"host": "qdrant.local"}`
* Adapted `./tests/basic_*.sh` scripts to be aware of `QDRANT_HOST_HEADERS` env variable

Enable running integration tests against non-localhost available instance

---

tests/openapi/helpers/helpers.py

If `wait=true` param is not set for delete vector API calls, a test asserting later that data are gone can become flaky, because at the assertion time the data could be still there.
The following files contain such tests at the moment:
* `test_multi_vector_uint8.py`
* `test_multi_vector.py`
* `test_multi_vector_unnamed.py`
* `test_optional_vectors.py`
In order to fix these and prevent the flakiness of future test, `request_with_validation` helper adds `wait=true` param, if it is not set for delete vector calls.

Add wait=true in openapi test for all point delete calls transparently

---

lib/segment/src/index/field_index/map_index/immutable_map_index.rs
tests/openapi/test_filtered_delete.py

Fix a problem where the immutable map index is mishandling point deletions. This was introduced in <https://github.com/qdrant/qdrant/pull/5072>.
The problem is that while deleting points, the index of a subslice is used. We should use the global index on the container instead.

Fix immutable map index mishandling point deletions

---

lib/collection/src/collection/mod.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/shards/replica_set/locally_disabled_peers.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/tests/points_dedup.rs
lib/collection/src/tests/snapshot_test.rs
lib/collection/tests/integration/common/mod.rs
lib/storage/src/content_manager/toc/collection_container.rs
lib/storage/src/content_manager/toc/create_collection.rs
lib/storage/src/content_manager/toc/mod.rs

We kill other replicas too eagerly if we think there's a problem.
We mark a replica as Dead if we get an error while sending an update to it (such as a precondition failure) and we think the replica is Active. The idea here is that Active replicas should never give errors.
The key thing here is that peers might be slightly out of sync, meaning that consensus operations are not applied at exactly the same time across a fleet.
So while we think we get an error on an Active replica, the actual replica might already be in Recovery state. In that case we expect to get an error back and should not escalate to killing the replica like we do now.
To solve this we now send the current state we expect to consensus when killing a replica. If it is in that state, we still mark it as dead. If it is …

Fix killing replicas too earily on state switches

---

Cargo.toml

Recommended by jemalloc author https://github.com/jemalloc/jemalloc/issues/956#issuecomment-316224733
It seems to decrease even more the memory usage on my tests.
- sparse: http://78.47.239.240:3000/d/41-6HeeVz/continuous-benchmarks?orgId=1&var-table=benchmark_manual&var-dataset=msmarco-sparse-100K&var-branch_a=ghcr%2Fjemalloc-background-threads&var-branch_b=ghcr%2Fdev
- laion: http://78.47.239.240:3000/d/41-6HeeVz/continuous-benchmarks?orgId=1&var-table=benchmark_manual&var-dataset=laion-small-clip&var-branch_a=ghcr%2Fjemalloc-background-threads&var-branch_b=ghcr%2Fdev
- h-and-m-2048-angular-filters: http://78.47.239.240:3000/d/41-6HeeVz/continuous-benchmarks?orgId=1&var-table=benchmark_manual&var-dataset=h-and-m-2048-angular-filters&var-branch_a=ghcr%2Fjemalloc-background-threads&var-bra …

Enable jemalloc background threads

---

lib/api/src/conversions/inference.rs
lib/api/src/rest/schema.rs
src/common/inference/batch_processing.rs
src/common/inference/infer_processing.rs
src/common/inference/mod.rs
src/common/inference/query_requests_rest.rs
src/common/inference/service.rs
src/common/inference/update_requests.rs
src/common/points.rs
src/main.rs
src/tonic/api/points_common.rs

- Add BatchProcessor and BatchConverter for efficient vector processing
- Consolidate inference request handling into batches
- Remove individual inference calls in favor of batched operations
- Reduce logging verbosity and remove redundant error handling
Query to try:
```http
PUT collections/sparse_charts/points?wait=true
{
"points": [
{
"id": "76874cce-1fb9-4e16-9b0b-f085ac06ed61",
"vector": {
"keywords": {
"object": "hello red planet mars",
"model": "qdrant/bm25"
}
},
"payload": {
"title": "Mars"
}
},
{
"id": "76874cce-1fb9-4e16-9b0b-f085ac06ed62",
"vector": {
"keywords": {
"object": "greetings blue planet earth",
"model": "qdrant/bm25"
}
},
"payload": {
"title": "Earth"
}
},
{
"id": "76874cce-1fb9-4e16-9b0b-f085ac06ed63",
"vector": {
"keywords": {
"object": "welcome green planet …
```

Inference Service, query requests (batch processing)

---

lib/storage/src/content_manager/consensus/persistent.rs
lib/storage/src/content_manager/consensus_manager.rs
lib/storage/src/content_manager/toc/transfer.rs

When synchronizing the consensus commit and peer we were waiting on the wrong commit value.
We waited on the commit in hard state, but we should wait on the last applied entry instead. The last applied entry better reflects what collection metadata we're actually seeing, while the hard state commit might be somewhere in the future.

Fix consensus sync peers waiting on wrong value

---

lib/collection/src/wal_delta.rs

Extends experiment in <https://github.com/qdrant/qdrant/pull/5349>.
Don't just ignore the clock tag in partial state, but also prevent writing it in the WAL.
Otherwise we'll still bump our last seen clocks with the tags replayed from the WAL.

Experiment: also don't write clock tags to WAL in partial state

---

tests/openapi/helpers/collection_setup.py
tests/poetry.lock
tests/pyproject.toml

Although test logic passes the assertions, the test might fail if during the teardown the created collection is not deleted,
because the client could not reach the database due to networking issue.
In order to make test executions more robust, collection deletes are retried in case of networking issues.

Retry collection delete in test teardown

---

lib/collection/benches/batch_query_bench.rs
lib/collection/benches/batch_search_bench.rs
lib/collection/src/shards/dummy_shard.rs
lib/collection/src/shards/forward_proxy_shard.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/local_shard/shard_ops.rs
lib/collection/src/shards/proxy_shard.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/remote_shard.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/shard.rs
lib/collection/src/shards/shard_trait.rs
lib/collection/src/tests/fix_payload_indices.rs
lib/collection/src/tests/payload.rs
lib/collection/src/tests/shard_query.rs
lib/collection/src/tests/wal_recovery_test.rs
lib/collection/src/wal_delta.rs

Extend experiment in <https://github.com/qdrant/qdrant/pull/5352>.
We should also ignore clock tags in initializing state. Initializing state basically behaves the same as partial, we send operations to it and we accept them.
Along with that we now propagate a boolean defining whether to ignore clock tags. It uses the current replica set state for the update as source.
It replaces the atomic boolean which was externally set to achieve the same. The old implementation did not properly update the boolean in some cases, because there are multiple ways to update the reflected replica set state. The new implementation does not have this problem.
3. …

Experiment: disable clocks in initializing state, propagate ignore flag

---

lib/api/src/grpc/conversions.rs
lib/collection/src/shards/remote_shard.rs
lib/common/common/src/counter/hardware_accumulator.rs
lib/common/common/src/counter/hardware_counter.rs

Depends on #5369 
Note: only implemented for search, count and query operations for now.

Forwarding hardware counter in distributed setup

---

tests/consensus_tests/test_shard_wal_delta_transfer.py

This consistency check is specialized to find discrepancy in point ids.
There are two problems:
- Python issue not accessing dictionary element properly `x.id` which fails, should be `x['id']`
- When the point ids are the same but the payloads are different, the error message is not helpful
This PR fixes the syntax issue and reuse the logic from another test to build a diff of the content.

Fix consistency check in test

---

lib/segment/src/vector_storage/chunked_mmap_vectors.rs
lib/segment/src/vector_storage/chunked_vector_storage.rs
lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/in_ram_persisted_vectors.rs

After the change in #5188 default vector storage is now mmap. This leads to the (undesirable) change of default behavior of quantization storage: instead of being loaded in RAM, it is not loaded on-disk by default, which leads to several undesirable consequences:
- Creation of the quantized vectors with default original vector configuration leads to unexpected performance degradation
- Quantized and original vectors start to compete for RAM, if disk cache is not large enough, so default configuration will degrade in performance and it is hard to diagnose in real life scenario.
Temporary workaround: always specify `always_ram` explicitly.

Update is_on_disk to restore original default behavior of quantization 

---

lib/segment/benches/sparse_index_search.rs
lib/segment/src/index/sparse_index/sparse_vector_index.rs

Sparse vectors indices are remapped and sorted by internal indices right before the search.
Therefore it is not necessary to sort the initial sparse vector.
Running with CI benchmark does not show any improvement sadly.

Do not sort sparse vector before remapping it

---

Cargo.lock

My `Cargo.lock` gets changed on every build. Probably due to a merge conflict with <https://github.com/qdrant/qdrant/pull/5357> PR.

Bump Cargo.lock

---

src/common/health.rs

Similar to <https://github.com/qdrant/qdrant/pull/5350>.
Our `/readyz` will wait for the node to reach the highest Raft commit reported by other peers.
The implementation is wrong. It only waits for that commit to be received, it does not wait for that commit to actually be applied.

In /readyz, wait for Raft commit to be actually applied

---

lib/collection/src/collection/shard_transfer.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/shards/shard_holder/resharding.rs

In <https://github.com/qdrant/qdrant/pull/5349> we added an await in `set_replica_state` and made the function async.
In <https://github.com/qdrant/qdrant/pull/5372> we removed all awaits from the function again.
I forgot to remove the `async` flag from the function, as it's now not needed anymore. This PR makes the change.

Experiment: set_replica_state does not need to be async

---

lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/transfer/stream_records.rs

Replacement for <https://github.com/qdrant/qdrant/pull/5370>.
At the end of some transfers - such as stream records - we bump the cutoff point on the receiving node to the latest clocks of the sender. The idea is that it prevents the node from providing a WAL delta with operations that may not be ordered correctly in it's WAL.
Bumping the cutoff point also bumps the newest seen clocks. I believe this can be problematic in our current implementation causing the node to reject operations it did not receive yet. The sender may have different clocks than the receiver due to the distributed nature of it. So, if we bump the cutoff point on some node with newer clocks than it already has, it may reject operations that are still incoming.
In other words: **we might bump the clocks on the receiver …

Experiment: in stream records, set cutoff to latest clocks receiver is guaranteed to have

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.12.2-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5213>.

Bump dev version to 1.12.2-dev

---

lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/segment/mod.rs

This PR removes unnecessary usage of `Option` in `GraphLinksMmap`. It was required because this field was under `#[serde(skip)]`.
Before this PR:
- `GraphLinksMmap::mmap` is `Option<Arc<Mmap>>`.
- The trait `GraphLinks` requires implementing `Default`.
- `struct GraphLayers` implements `Serialize`/`Deserealize`, but skips some fields using `#[serde(skip)]`.
After this PR:
- `GraphLinksMmap::mmap` is `Arc<Mmap>`.
- The trait `GraphLinks` no longer requires implementing `Default`.
- Serializable fields of `GraphLayers` are moved into `GraphLayerData`.

GraphLinksMmap: remove Option

---

src/common/health.rs

What we had in place seems overly complicated for what it tries to achieve, and may send a lot of extra unnecessary requests while catching up.
This simplifies the check.

Simplify logic in /readyz for checking if we have just one peer

---

lib/segment/src/index/visited_pool.rs

```console
$ cargo bench -p segment --bench hnsw_search_graph # old
hnsw-index-search-group/hnsw_search
time:   [386.29 µs 388.57 µs 391.12 µs]
$ cargo bench -p segment --bench hnsw_search_graph # new
hnsw-index-search-group/hnsw_search
time:   [360.82 µs 363.07 µs 365.57 µs]
change: [-7.0677% -5.5386% -3.9408%] (p = 0.00 < 0.05)
Performance has improved.     
```

Optimize VisitedList counter reset

---

lib/segment/src/id_tracker/simple_id_tracker.rs

This PR fixes the simple id mapper to only persist inserts to mapping on explicit flush.
This is not currently the case because the persistence is handled by RocksDB which persist inserts freely.
This is important because our flushing sequence is:
- id mappings
- vectors
- payloads 
- id versions
Upon restart, the WAL is replayed and operations for which the sequence number are less or equal than the point versions are discarded.
The version of point is resolved like this.
```rust
id_tracker
.internal_id(point_id)
.and_then(|internal_id| id_tracker.internal_version(internal_id))
```
First we fetch the `internal_id` which query the mapping and then follow through by looking up the `version`.
In the current setup this can return invalid version which have not been flushed during WAL replay. …

ID mapping should only be saved on flush

---

lib/collection/src/collection/mod.rs
lib/collection/src/collection/snapshots.rs
lib/collection/src/common/snapshots_manager.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/resharding/stage_migrate_points.rs
lib/collection/src/shards/shard.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/update_handler.rs
lib/storage/src/content_manager/collections_ops.rs
lib/storage/src/content_manager/snapshots/mod.rs
lib/storage/src/content_manager/toc/collection_container.rs
lib/storage/src/content_manager/toc/collection_meta_ops.rs
lib/storage/src/content_manager/toc/create_collection.rs
lib/storage/src/content_manager/toc/mod.rs
lib/storage/src/dispatcher.rs
src/actix/api/service_api.rs
src/actix/api/snapshot_api.rs
src/common/health.rs
src/common/inference/query_requests_grpc.rs
src/tonic/api/points_common.rs

Remove all unnecessary `async/await` definitions which I found with the pedantic mode of Clippy.
An additional clippy pass was necessary afterwards as removing async triggered further simplifications.

No useless async

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Patch release of Qdrant 1.12.2.
This contains some critical fixes, most notably:
- https://github.com/qdrant/qdrant/pull/5346
- https://github.com/qdrant/qdrant/pull/5211

Bump version to 1.12.2

---

lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_chunks_reader.rs
lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_list.rs
lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_visitor.rs
lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/posting_list.rs
lib/segment/src/index/field_index/full_text_index/postings_iterator.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/payload_storage/simple_payload_storage.rs
lib/segment/src/payload_storage/simple_payload_storage_impl.rs

This PR changes a bunch of functions to accept `PointOffsetType` by value instead of by reference.
Passed as value `PointOffsetType` is taking 4 bytes (u32).
Passed as a reference on a 64bits system, it takes 8 bytes to pass an address.
Discovered with Clippy pedantic lints.
```
warning: this argument (4 byte) is passed by reference, but would be more efficient if passed by value (limit: 8 byte)
```

Do not pass PointOffsetType by reference

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.12.3-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5392>.

Bump dev version to 1.12.3-dev

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/conversions/inference.rs
lib/api/src/grpc/proto/points.proto
lib/api/src/grpc/qdrant.rs
lib/api/src/rest/schema.rs
src/common/inference/batch_processing.rs
src/common/inference/batch_processing_grpc.rs
src/common/inference/service.rs

Just str type is not enough for local inference, since it does not cover all the types we'd like to support in local inference. This PR changes Image.image type to Value in order to support any value.
The decision to make it any was taken due to the desire to support objects which are not supported in openapi schema (e.g. `PIL.Image`

update Image.image type to Value instead of string

---

Cargo.lock
Cargo.toml

We can align our `fs4` versions and stop compiling an old one.
ref https://github.com/qdrant/wal/pull/78

Bump wal f42e853

---

lib/storage/src/content_manager/consensus/persistent.rs

Only show the following warning if the peer address actually changed.
```
```
Until now it's not entirely clear in what situation this message would show up.

Demote peer added with same adress to debug

---

config/config.yaml
docs/redoc/master/openapi.json
lib/collection/src/config.rs
lib/collection/src/operations/config_diff.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/collection_meta_ops.rs
lib/storage/src/types.rs

We currently have our code to interpret a missing `on_disk_payload` as `false`, but it does not usually get exercised because the default config file for storage sets it to true:
https://github.com/qdrant/qdrant/blob/dev/config/config.yaml#L36
This PR:
- makes the default `on_disk_payload` to `true`, to match the default config value
- changes the default `PayloadStorageType` to `OnDisk`
- removes duplicate `default_on_disk_payload` implementation

Make `default_on_disk_payload` consistent with config file

---

lib/segment/src/index/visited_pool.rs

Fixup for #5336. In #5336, I made an assumption that the `num_points` provided to `VisitedPool::get()` is always accurate and removed bounds check from `VisitedListHandle::check_and_update_visited`.
```rust
let mut visited_list = visited_pool.get(num_points);
visited_list.check_and_update_visited(point_id); // assumption: point_id < num_points
```
But it seems that it's not true. Chaos testing shows that it crashes in the following code:
https://github.com/qdrant/qdrant/blob/ac54ad4074cc0240bb2e01f91804e857d720b756/lib/segment/src/index/struct_payload_index.rs#L381-L399
Perhaps the offending ids could come from `PrimaryCondition::Ids`/WAL/field_index? This PR restores the check.

Fixup for VisitedListHandle::check_and_update_visited

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Patch release of Qdrant 1.12.3, follows the pattern of <https://github.com/qdrant/qdrant/pull/5404>.
This includes a critical patch causing panics during search: https://github.com/qdrant/qdrant/pull/5427

Bump version to 1.12.3

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.12.4-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5407>.

Bump dev version to 1.12.4-dev

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/proto/points.proto
lib/api/src/grpc/qdrant.rs
lib/api/src/rest/schema.rs
src/common/inference/batch_processing.rs
src/common/inference/batch_processing_grpc.rs
src/common/inference/service.rs

We currently don't have interfaces which allow to omit model name in inference structures.
There was an idea of having this field optional for web-ui, however, it has been rejected, since model name can be substituted in web-ui on.

Make model name field mandatory in inference structures

---

Cargo.lock
Cargo.toml
lib/collection/Cargo.toml
lib/collection/src/collection/search.rs
lib/collection/src/collection_manager/search_result_aggregator.rs
lib/collection/src/collection_manager/segments_searcher.rs
lib/segment/Cargo.toml

On large result sets, the SIP hasher shows up in profiling when combining search results from different segments & shards.
This PR replaces the default hasher with `Ahash` which is more efficient on smaller input like ids.
After the change, hashing does not appear in profiling anymore.

Leverage ahash in search results

---

lib/collection/src/config.rs
lib/collection/src/operations/conversions.rs
lib/storage/src/content_manager/toc/create_collection.rs
lib/storage/src/types.rs
lib/storage/tests/integration/alias_tests.rs

Adds a temporary `storage.on_disk_payload_uses_mmap` setting to enable the use of the new mmap storage before actually integrating it as a default storage.

[mmap payload storage] Add hidden config to use mmap storage

---

Cargo.lock
docs/redoc/master/openapi.json
lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/collection/src/config.rs
lib/collection/src/operations/conversions.rs
lib/collection/src/shards/local_shard/mod.rs
lib/common/common/src/cpu.rs
lib/segment/Cargo.toml
lib/segment/src/index/query_optimization/payload_provider.rs
lib/segment/src/payload_storage/mmap_payload_storage.rs
lib/segment/src/payload_storage/mod.rs
lib/segment/src/payload_storage/payload_storage_enum.rs
lib/segment/src/payload_storage/query_checker.rs
lib/segment/src/payload_storage/tests.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/toc/create_collection.rs
lib/storage/src/types.rs
lib/storage/tests/integration/alias_tests.rs

Adds the integration necessary to be able to load and use a segment with mmap storage, but never actually creates it. 
The intention is so that we can release a patch version which can handle a rollback from a newer minor version, e.g. to let `1.13.0` able to be rolled back into `1.12.3`, if the new storage turns out to be buggy.
Also centralizes the `on_disk_payload` translation into `PayloadStorageType` so that it becomes easier to update in the future.
Just for reference, [this](https://github.com/qdrant/qdrant/blob/d5b7f22748b2784956fd6df4ba70394c05b3649c/lib/segment/src/segment_constructor/segment_constructor_base.rs#L690-L692) is where the segment config is read. This PR makes it able to handle the `PayloadStorageType::Mmap` variant.
**Note**: Thanks to #5190 (@agourlay) from which …

Backward compatibility for mmap payload storage

---

lib/collection/src/wal_delta.rs

I believe we accidentally left the TODO behind and it does not have a real purpose anymore.
As far as I understand it had to do with a suggested change for when we'd accept all clocks no matter their tick value during the implementation phase.
This is where it first appeared: https://github.com/qdrant/qdrant/commit/42b80f454346b39c2fba09e38c8c6c8e578080c6#diff-4c0b7eece99d62a4a61db5090e46cc181bacb1c0b4211c84fb5210fe34154416R33-R38

Remove leftover TODO

---

docs/redoc/master/openapi.json
lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/segment/src/fixtures/index_fixtures.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/plain_payload_index.rs
lib/segment/src/segment/entry.rs
lib/segment/src/types.rs
lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs

Current calculation of the `vectors_size_bytes` have some problems:
- It accumulates same vectors multiple times, if proxy segment is used
- It suffers from vectors not explicitly marked as deleted, even if the point is deleted
This PR fixes those shortcomings by changing the way we compute vector size:
1. We compute average size of all vectors
2. We estimate segment size by multiplying number of **points** to the average
3. We do not take temp segments into account
This PR also contains renaming for `size_in_bytes` -> `size_of_available_vectors_in_bytes` so the name is more explicit
+ bonus, PR makes sparse vector storage compute only size of available points.

use more stable computation of vectors_size_bytes + refactoring

---

lib/collection/src/shards/transfer/resharding_stream_records.rs

Same as <https://github.com/qdrant/qdrant/pull/5414>, but in the stream records logic specialized for resharding.

In resharding stream records, set earlier cutoff point

---

lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs

Depends on #5374.
In this PR:
1. The common logic of `GraphLinksRam` and `GraphLinksMmap` extracted into `GraphLinksView`. Now both implementations just merely provide the storage (`Vec<u8>` or `Mmap`), and all the logic operates on `&[u8]`.
2. Removed a bunch of methods from `GraphLinks` which expose implementation details.
3. The method `GraphLinks::links()` is changed to return an iterator instead of a slice. This change would allow implementations to iterate over compressed values.
The idea for 2 and 3 is taken from the branch https://github.com/qdrant/qdrant/tree/try-to-compress-hnsw-links by @IvanPleshkov.

Introduce GraphLinksRef

---

lib/collection/src/operations/query_enum.rs
lib/collection/src/operations/types.rs
lib/collection/src/operations/universal_query/planned_query.rs
lib/collection/src/shards/local_shard/query.rs
lib/segment/src/index/hnsw_index/hnsw.rs

This PR contains 2 improvement, which when combined, make usage of the colpali models a bit less miserable.
1. Propagate search parameters to re-scoring search.
Previously, if we were using re-scoring (query + prefetch), the re-scoring request was used with empty param, assuming that since we had fixed list of elements to re-score, we would always do a full-scan. 
This is, however, not true for ColPali vectors, where only ~20 vectors overwhelm  full-scan threshold and force us to use HNSW (which is not efficient at this stage)
Additionally, empty parameter forced us to ignore quantization, while sometimes it might be useful. Now params from the query are fully propagated.
2. Detection if the HNSW is disabled. 
Since ColPali vectors are enormous, building HNSW for them barely makes sense. …

Fixes for rescoring param usage and HNSW

---

lib/storage/src/content_manager/toc/collection_meta_ops.rs

Fixes https://github.com/qdrant/qdrant/issues/4568
Based on suggestion https://github.com/qdrant/qdrant/pull/4788#issuecomment-2468444870, we just not use the collection-name in the folder struct of the collections to be deleted; which prevents us in getting into risks of too-long-file-name error.

Fix the file name too long error during collection deletion

---

lib/segment/src/index/field_index/binary_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/field_index/mod.rs
lib/segment/src/index/field_index/numeric_index/mod.rs
lib/segment/src/index/query_estimator.rs
lib/segment/tests/integration/payload_index_test.rs

We are using too much memory to represent non `FieldCondition` variant.
https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
```console
error: large size difference between variants
--> lib/segment/src/index/field_index/mod.rs:28:1
|
28 | / pub enum PrimaryCondition {
29 | |     Condition(FieldCondition),
| |     ------------------------- the largest variant contains at least 368 bytes
30 | |     IsEmpty(IsEmptyCondition),
| |     ------------------------- the second-largest variant contains at least 48 bytes
31 | |     IsNull(IsNullCondition),
32 | |     Ids(HashSet<PointOffsetType>),
33 | |     HasVector(String),
34 | | }
| |_^ the entire enum is at least 368 bytes
|
= help: for further information visit …
```

Fix clippy large variant for filter condition

---

lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs

I do not think we need to make an exception here for sizing the `FullTextIndex` enum.
```console
error: large size difference between variants
--> lib/segment/src/index/field_index/full_text_index/text_index.rs:28:1
|
28 | / pub enum FullTextIndex {
29 | |     Mutable(MutableFullTextIndex),
| |     ----------------------------- the second-largest variant contains at least 0 bytes
30 | |     Immutable(ImmutableFullTextIndex),
31 | |     Mmap(MmapFullTextIndex),
| |     ----------------------- the largest variant contains at least 352 bytes
32 | | }
| |_^ the entire enum is at least 0 bytes
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
= note: `-D clippy::large-enum-variant` implied by `-D warnings`
= help: to override …
```

Fix large variant for fulltext index

---

src/consensus.rs

In the steady state, there is no consensus error so we should not pay any price for successful sent messages.
Returning `Ok(())` should be as cheap as possible and not 304 bytes.
```console
error: the `Err`-variant returned from this function is very large
--> src/consensus.rs:1139:53
|
1139 |     pub fn send(&mut self, message: RaftMessage) -> RaftMessageSenderResult<()> {
|                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 304 bytes
|
= help: try reducing the size of `tokio::sync::mpsc::error::TrySendError<(usize, raft::prelude::Message)>`, for example by boxing large elements or replacing it with `Box<tokio::sync::mpsc::error::TrySendError<(usize, raft::prelude::Message)>>`
= help: for further information visit …
```

Fix large result size in consensus loop

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

```
* https://github.com/qdrant/qdrant/pull/5440 - :sparkles: Optimize mmap sequential access for full-scan segments and reading of large vectors
* https://github.com/qdrant/qdrant/pull/5428 - Leverage ahash in search results
* https://github.com/qdrant/qdrant/pull/5414 - Improvements for update clocks to improve updates consistency
* https://github.com/qdrant/qdrant/pull/5448 - Sync consensus at the end of stream records transfer
* https://github.com/qdrant/qdrant/pull/5378 - Introduce a unique identifier for collections for easier consensus snapshots resolution
* https://github.com/qdrant/qdrant/pull/5457 - :sparkles: Fixes for rescoring param usage and usage of disabled HNSW
* https://github.com/qdrant/qdrant/pull/5439 - Fix the file name too long error during collection deletion
```

bump version to v1.12.4

---

lib/collection/src/operations/mod.rs
lib/collection/src/operations/payload_ops.rs
lib/collection/src/operations/point_ops.rs
lib/collection/src/operations/vector_ops.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/shard_holder/resharding.rs

An operation may be rejected on a replica in `Recovery` state if no `force` flag is provided.
This now shows a debug message when that happens.
For rejections caused by old clocks we already have a warning and automatic retry in place here: https://github.com/qdrant/qdrant/blob/d6f266a4ddbf3f57a3d308b6dce1fed83b867917/lib/collection/src/shards/replica_set/update.rs#L175-L178
I expect this debug message to be a bit noisy if a lot of replica state changes are happening. Let's see how it behaves and revert if needed. This will at least allow us to detect rejections on chaos testing for the time being.

Log debug message on operation rejection for missing force flag

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.12.5-dev`.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5432>.

Bump dev version to 1.12.5-dev

---

lib/collection/src/collection/shard_transfer.rs
lib/storage/src/content_manager/toc/mod.rs
src/main.rs

Instead of just cancelling the outgoing shard transfers on start, also cancel the incoming transfers.
Automatic shard recovery will follow after cancelling the transfer to bring it back into active state.

Cancel all related shard transfers on start

---

Cargo.toml

This PR prevents the `wal_inspector` binary to be built by default, it is now hidden behind the existing `service_debug` feature.
Why?
- The binary is used very rarely.
- It is rather large `979M wal_inspector-e63716334eafa7cb`.
- It takes a significant amount of time to build.
The `service_debug` feature is used in our integration tests so we should be able to catch a breakage early.

Do not build wal_inspector by default

---

lib/common/common/src/counter/hardware_accumulator.rs
lib/common/common/src/counter/hardware_counter.rs

Nested panics caused by `HardwareCounterCell::drop()` abort the program which is inconvenient when debugging failed tests.
To avoid this, this PR adds a check suggested in the Rust docs: https://doc.rust-lang.org/std/ops/trait.Drop.html#panics.

HardwareCounterCell::drop: avoid nested panic

---

Cargo.toml
tools/generate_openapi_models.sh

Follow up on https://github.com/qdrant/qdrant/pull/5479.
Same reasoning, that binary is even larger `1010M schema_generator-a1b487c3b49c0bdd`
It is only used through `tools/generate_openapi_models.sh` where it is enabled explicitly.

Do not build schema_generator by default

---

lib/collection/src/collection/search.rs
lib/collection/src/collection_manager/search_result_aggregator.rs
lib/collection/src/collection_manager/tests/test_search_aggregation.rs
lib/common/common/src/fixed_length_priority_queue.rs
tests/openapi/test_query.py

Fixes <https://github.com/qdrant/qdrant/issues/5483>
[Here](https://github.com/qdrant/qdrant/pull/5428/files#diff-9a15df0820bef38d5804ec1676101484e170367b109289cb02410109db341d2aR17) we started to preallocate memory in the search result aggregator based on the user provided limit. If a user provides a huge limit it will panic due to an allocation failure.
This PR fixes the problem by limiting the size of preallocating to one million items, exactly like `FixedLengthPriorityQueue` does. I'm not entirely sure if one million is reasonable here, and it might be too big. Lets discuss here what we think may be reasonable.
I've also fixed a limit overflow in `FixedLengthPriorityQueue` if a `limit` of `u64::MAX` is given, and an overflow in search.

Fix panic on query with huge limit

---

lib/collection/src/collection/distance_matrix.rs

Computing the distance matrix requires several stages of querying.
The timeout should be updated mid-way to reflect the time already elapsed.

Improve timeout in distance matrix

---

lib/collection/src/collection_manager/holders/proxy_segment.rs

Remove last flushed version from proxy segment, we don't seem to use it.

Remove last flushed version from proxy segment

---

lib/blob_store/benches/real_data_bench.rs
lib/blob_store/src/bitmask/gaps.rs
lib/blob_store/src/bitmask/mod.rs
lib/blob_store/src/blob_store.rs
lib/blob_store/src/tracker.rs

Introduces a new feature to compute the storage size of the blobstore.
It targets only the values stored on the behalf of the users, it does not include our technical metadata (gaps, bitmask ...).
The computation leverages the region gaps to fast path empty and full regions.
The benchmarks show that handles 5GB of data in 500us.
```console
cargo bench -p blob_store --bench real_data_bench
compute storage size    
time:   [5.3589 µs 5.3737 µs 5.3895 µs]
read real payload
time:   [638.35 ms 639.51 ms 641.02 ms]
upsert real payload
time:   [1.3302 s 1.3809 s 1.4324 s]
compute storage size (large storage) <--- 5GB
time:   [497.03 µs 498.55 µs 499.94 µs]
read real payload (large storage)
time:   [613.18 ms 615.96 ms 619.53 ms]
```
I refactored the benchmark to draw the attention on the size of …

Compute storage size for blobstore

---

lib/collection/src/shards/remote_shard.rs

Some queries require to perform several I/O action in a sequence before responding to the client.
Between each action, we decrease the timeout in order to track precisely the elapsed time to honor the timeout input from the client.
This logic triggers two different failure modes for the remote shard when:
- the timeout is zero:
-  the remote shard does not accept timeout=0 as input
- the timeout is between 0 and 1 sec
- given that the value is floored, it triggers the previous case as well
This PR proposes to:
- gate the access to remote shard with non zero timeout to shortcut the query processing
- round up the timeout value to the next greater integer. 
- e.g `0.5 sec` would become `1 sec` instead of timing out
- unify our timeout param. value with the one used for the `gRPC` connection …

Improve timeout handling in remote shards

---

lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs

In the vector storages, we usually have a `deleted_bitvec` which marks the vectors as deleted. 
However, there was a shortcut, which would skip marking as deleted, if the point offset exceeded the current length of the storage. This is incorrect and should be only applied when setting `deleted=false`.
This PR fixes those cases and adds (modifies) a test which would fail on `dev` branch, but now passes

[vector storages] Don't skip marking as deleted

---

lib/collection/src/collection/point_ops.rs

Experimenting with streaming processing of results from shards.
- do not wait for all shards before processing points
- do not allocate all results eagerly
- pre-allocate result set

Retrieve points by streaming shard results

---

lib/collection/src/collection/facet.rs
lib/segment/src/data_types/facets.rs

Similar to https://github.com/qdrant/qdrant/pull/5505 but for facets.
Do not wait for all shards to start aggregating results as soon as available.
- Do not wait idle for slow shards.
- Use less memory by avoiding to hold all responses in memory at once.

Compute facets by streaming shard results

---

lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs
lib/segment/src/common/rocksdb_wrapper.rs
lib/segment/src/payload_storage/payload_storage_enum.rs
lib/segment/src/payload_storage/simple_payload_storage.rs

Introduces a new feature to retrieve the RocksDB storage size of a given column family.
I tried various approach before settling on this one, it seems to give a good proxy for what is being persisted.
This function is introduced mostly for consistency sake as we want to support this feature on the payload storage trait.
It is unlikely that it will be used meaningfully in practice.

Expose storage size of RocksDB payload storage

---

lib/common/common/Cargo.toml
lib/common/common/benches/bitpacking.rs
lib/common/common/src/bitpacking.rs
lib/common/common/src/lib.rs

This PR adds a new module `common::bitpacking` with two structs: `BitPacker` and `BitUnpacker`. They would be used for the HNSW graph links compression in subsequent PRs.
Comparison with other implementations:
- [`bitpacking`](https://docs.rs/bitpacking/latest/bitpacking/): it's fast, SIMD-optimized, but application is limited: blocks should be of size of 32/128/256 integers, all stored integers within a block should have the same bitsize.
- [`bitstream_io`](https://docs.rs/bitstream-io/latest/bitstream_io/): the idea is somewhat similar to this PR, but this crate resulted to be slower for links compression/in-memory use-case.
- [`tantivy_bitpacker`](https://docs.rs/tantivy-bitpacker/latest/tantivy_bitpacker/): optimized for a random access reads within a packed array.
The most important …

Add common::bitpacking

---

lib/segment/src/index/hnsw_index/graph_layers.rs

This PR drops the support for reading/converting of the old `graph.bin` file format used before Qdrant 0.8.4.
This old format stores everything in a single `graph.bin` file while newer versions of qdrant store the graph in two files, `graph.bin`+`links.bin`.

Drop `GraphLayersBackwardCompatibility`

---

lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs

This PR slightly updates the `GraphLinks` trait:
- Removed: `fn links()`; it was `iter()`-like, i.e. returns an iterator.
- Added instead: `fn for_each_link()`; it's `for_each()`-like, i.e. takes a closure.
- Also, added `#[cfg(test)] fn links_vec()`; returns a vector. Obliviously, it's slow, but it used only in tests.
The reason is that it would be easier for a compiler to generate inline-able code. (and the the subsequent PRs depend on this change)

GraphLinks::for_each_link

---

Cargo.lock
Cargo.toml
lib/gpu/src/descriptor_set.rs
lib/gpu/src/descriptor_set_layout.rs
lib/gpu/src/device.rs
lib/quantization/src/encoded_vectors_binary.rs
lib/quantization/src/encoded_vectors_pq.rs
lib/quantization/src/encoded_vectors_u8.rs
lib/segment/Cargo.toml
lib/segment/src/common/operation_error.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/gpu_multivectors.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/gpu_quantization.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/gpu/shader_builder.rs
lib/segment/src/index/hnsw_index/gpu/shaders/common.comp
lib/segment/src/index/hnsw_index/gpu/shaders/extensions.comp
lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_vector_storage.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage_bq.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage_dense.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage_f16.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage_f32.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage_pq.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage_sq.comp
lib/segment/src/index/hnsw_index/gpu/shaders/vector_storage_u8.comp
lib/segment/src/index/hnsw_index/mod.rs
lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

This PR introduced GPU storing and scoring of vectors. It supports dense vectors with `f32, f16, u8` type, SQ/BQ/PQ + multivectors for all types and quantization.
I marker in the comments all pieces of changes that are not under GPU-feature.

Gpu vectors

---

docs/redoc/master/openapi.json
lib/collection/src/collection/mod.rs
lib/collection/src/collection/resharding.rs
lib/collection/src/collection/sharding_keys.rs
lib/collection/src/collection/state_management.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/shards/telemetry.rs
src/common/collections.rs

Expose shard keys for each shard in telemetry. This is necessary for resharding.
Rather than listing the key mapping, this lists the assigned key in each shard instead. I think that is a better interface to work with. Because of it I've copied the shard key into the replica set struct.
See `"key": "test"`:
```json
{
"collections": {
"number_of_collections": 1,
"collections": [
{
"id": "benchmark",
"init_time_ms": 800,
"config": { ... },
"shards": [
{
"id": 1,
"key": "test",
"local": { ... },
"remote": [],
"replicate_states": {
"6469369128247073": "Active"
}
}
],
"transfers": [],
"resharding": []
}
]
}
}
```
3. [x] Have you checked your code …

Expose shard keys in telemetry

---

lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/collection_manager/tests/mod.rs

Potential fix for <https://github.com/qdrant/qdrant/pull/5527>
Points can be in multiple segments having different versions. We must only apply the operation to the latest version of a point, otherwise our copy on write mechanism may repurpose old point data.
Using the latest point data is very important, because the copy on write operation will bump the version number. If old point data was used, we'll not be able to tell that anymore.
This problem can appear when applying an operation that depends on the current point data (such as set payload), while having a point in multiple segments. Having a point in multiple segments may happen because of optimizations and segment proxies.
2. [x] Have you formatted your code locally using `cargo +nightly fmt …

Fix apply points mixing point versions, only apply operation to latest

---

lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/simple_segment_constructor.rs
lib/segment/tests/integration/segment_builder_test.rs

Fix the path for the mmap payload storage in the segment builder.
Currently the storage is built at the level of `segments` and is not propagated properly.
We did not discover the issue earlier because we create the storage folder if it does not exist on load.
I added a simple making sure we do not add the folder at the wrong spot.

Fix path to new payload storage for optimized segments

---

lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs
lib/segment/src/common/rocksdb_wrapper.rs
lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs
lib/segment/src/payload_storage/mmap_payload_storage.rs
lib/segment/src/payload_storage/on_disk_payload_storage.rs
lib/segment/src/payload_storage/payload_storage_base.rs
lib/segment/src/payload_storage/payload_storage_enum.rs
lib/segment/src/payload_storage/simple_payload_storage.rs
lib/segment/src/payload_storage/simple_payload_storage_impl.rs
lib/segment/src/payload_storage/tests.rs

This PR adds `get_storage_size_bytes` to the payload storage trait for us to leverage later on the serverless infra.

Add retrieving storage size to payload storage trait

---

lib/segment/benches/sparse_index_build.rs
lib/segment/src/fixtures/sparse_fixtures.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/src/vector_storage/mod.rs
lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
lib/segment/src/vector_storage/sparse/mod.rs
lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs

Purely a restructuring PR. Now with the new mmap sparse vector storage, we have two implementations that should live in its own module.
Follows the same pattern as the dense vectors storages.

Restructure sparse storages module

---

lib/segment/src/index/hnsw_index/graph_links.rs

This PR refactors `GraphLinksConverter` in preparation for adding support for compressing.
- `GraphLinksFileHeader` is split into `GraphLinksFileHeader` (on-disk representation) and `GraphLinksFileInfo` (in-memory, all offsets are calculated).
- Replaced usages of `mmap_ops::transmute_from_u8_to_slice` with equivalents from the `transmute` crate (as I find it to be more sound).
- Now, it serializes into `impl Write` sequentially rather than into `&mut [u8]`.
- The serialization code now looks much simpler. It will extended later to support writing in a compressed format.

Refactor `GraphLinksConverter`

---

lib/api/src/conversions/vectors.rs
lib/api/src/grpc/conversions.rs
lib/collection/src/operations/conversions.rs
tests/basic_sparse_grpc_test.sh

Always return the precise validation error for sparse vectors.

Return complete error for sparse vector validation

---

lib/collection/src/collection_manager/holders/proxy_segment.rs

In case of a proxy segment, the functions that return available point IDs may include duplicates. That's especially true when the write segment is shared across multiple proxies.
In some places we derive point count based on the returned list, which would double count any duplicates.
I think it's best to deduplicate to prevent this from happening.

Deduplicate point IDs returned from proxy segment

---

lib/segment/src/segment_constructor/segment_builder.rs

What lessons should we learn from this bug?
- Do test coverage?
- Rely more on the pattern matching and force compiler to make sure all fields are used?
- Do not access fields of the structure directly?

it is easy if you know where to look

---

lib/api/src/rest/schema.rs

Previously: 
`"Format error in JSON body: data did not match any variant of untagged enum QueryInterface at line 1 column 16"`
Now:
`"Format error in JSON body: Expected some form of vector, id, or a type of query at line 1 column 16"`
I did try to use `strum` crate to list the exact variants that are allowed, but `#[serde(expecting = "...")]` only allows string literals, so even when I could construct a `const &str` which was descriptive enough, I could not use it without reimplementing `Deserialize` for the type.

Better `QueryInterface` untagged enum message

---

lib/segment/src/segment/facet.rs

Adjust the approximate facet interface to prevent a division by zero.
If a segment is empty, this will become infinite:
```rust
let percentage_filtered = filter_cardinality.exp as f64 / available_points as f64;
```
After which this is incorrectly (?) false:
```rust
let use_iterative_approach = percentage_filtered < 0.3;
```
I've adjusted this function to simply shortcut if the segment is empty. In that case there are no facet values to consider anyway. That also prevents the above problem.

Fix division by zero in approximate facet API, shortcut instead

---

lib/collection/src/collection_manager/holders/proxy_segment.rs

Here we check if a point is in the wrapped segment. But we actually do it twice.
The first checks if the point is there, the second gets the point version. Getting just the point version achieves the same as it'll be `None` if the point does not exist.

Remove redundant check if point is in wrapped segment

---

docs/redoc/master/openapi.json
lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/segment/src/segment/entry.rs
lib/segment/src/telemetry.rs
lib/segment/src/types.rs

Adding the payload storage size at the segment info makes it visible in the telemetry.
Tested manually
e.g.
- empty segment
```json
"num_vectors": 0,
"num_points": 0,
"num_indexed_vectors": 0,
"num_deleted_vectors": 0,
"vectors_size_bytes": 0,
"payloads_size_bytes": 0,
"ram_usage_bytes": 0,
"disk_usage_bytes": 0,
```
- non empty
```json
"num_vectors": 6,
"num_points": 6,
"num_indexed_vectors": 0,
"num_deleted_vectors": 0,
"vectors_size_bytes": 96,
"payloads_size_bytes": 1183,
"ram_usage_bytes": 0,
"disk_usage_bytes": 0,
```

Expose payload storage size in segment info

---

lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/local_shard/shard_ops.rs
lib/common/common/src/lib.rs
lib/common/common/src/rate_limiting.rs

This PR adds rate limiting to read and write operations on the local shard.
The rate limiters use the token based algorithm to allow burst of requests.
In case of exceeded capacity, we return the newly introduced error in https://github.com/qdrant/qdrant/pull/5538
The rate limiters will be initialized properly from configuration in a future PR.

Rate limit local shard operations

---

Cargo.toml
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/segment/segment_ops.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
src/common/health.rs
src/consensus.rs

This PR fixes and enforces clippy [needless_pass_by_ref_mut](https://rust-lang.github.io/rust-clippy/master/index.html#needless_pass_by_ref_mut)

Enforce clippy needless_pass_by_ref_mut

---

lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/collection/src/collection_manager/tests/mod.rs

At the end of segment optimization, we apply all proxied point deletes to the optimized segment.
When applying these deletes we reused the current segment version on those operations before. The segment likely considers that version to already be persisted. Subsequent flushes will not write the deletes to disk because of it, the segment thinks there are no new changes.
I've changed this to apply the deletes with the operation version that caused the delete to happen. Those will bump the segment version and ensure proper flushing.
I've added a debug assertion to ensure the delete versions are always newer than the segment version. …

In proxy segment, apply proxied point delete with its operation version

---

lib/api/src/rest/schema.rs
lib/segment/src/types.rs

Following the change done in #5546, this PR adds the same kind of messages to other untagged enums.
Additionally, it aliases `with_vectors` and `with_vector` in the query interface. We have documentation referencing both names, and it is easy to solve here.

Friendlier untagged enum errors

---

lib/collection/src/collection_manager/holders/segment_holder.rs

Fix a bug in point deduplication that caused mishandling of point versions.
The 'last point version' was not properly cleared when moving to the next point ID, meaning irrelevant point versions from the previous point leaked into the current one. Because of this it was possible we deleted newer point versions rather than old ones.
I've added two unit tests:
- the first tests this specific problem
- the second inserts random points into segments and asserts we always keep the highest point version

Fix point deduplication

---

Cargo.lock
docs/redoc/master/openapi.json
lib/common/common/src/cpu.rs
lib/gpu/src/device.rs
lib/segment/Cargo.toml
lib/segment/benches/multi_vector_search.rs
lib/segment/src/index/hnsw_index/gpu/batched_points.rs
lib/segment/src/index/hnsw_index/gpu/gpu_devices_manager.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/mod.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/tests/integration/batch_search_test.rs
lib/segment/tests/integration/byte_storage_hnsw_test.rs
lib/segment/tests/integration/byte_storage_quantization_test.rs
lib/segment/tests/integration/filtrable_hnsw_test.rs
lib/segment/tests/integration/gpu_hnsw_test.rs
lib/segment/tests/integration/hnsw_discover_test.rs
lib/segment/tests/integration/hnsw_quantized_search_test.rs
lib/segment/tests/integration/main.rs
lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
lib/segment/tests/integration/multivector_hnsw_test.rs
lib/segment/tests/integration/multivector_quantization_test.rs
src/common/telemetry_ops/app_telemetry.rs
src/main.rs
src/settings.rs

Integrate GPU HNSW into segment.
This PR contains:
1. Run GPU indexation in `hnsw.rs`. Main and filtered graph is indexed by GPU. If gpu error occurs, error is logged and construction is continued by CPU.
2. Unit test of filtered HNSW
3. Segment builder creates GPU device and provide it into HNSW. In the future we need to move this logic up to optimizer and define GPU permits. Changes in segment builder are temporary.
4. Telemetry with enabled feature and created devices.
5. QDrant GPU settings.

GPU HNSW integration

---

lib/collection/src/collection_manager/holders/segment_holder.rs

Fix a problem where we could potentially miss flushing deletes on segments wrapped in a proxy.
Imagine the following events:
- flush proxy A
- reinsert point into proxy A
- flush proxy B
If proxy A and B share the same write segment, this write segment will be updated even though proxy B is yet to be flushed. The write segment affects the segment version of the proxy, so the version of proxy B is bumped even though it's still pending flush. We normally don't expect this to happen as we hold a read lock on proxy B.
Also, in our flush logic we normally acknowledge the highest version we've seen to the write ahead log.
If we add versions to the above actions, the problem becomes visible:
- flush proxy A (version 10)
- reinsert point into proxy A (version 11)
- flush proxy B (version 11)
We …

Fix missing flush on proxy segment if sharing write segment

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/conversions.rs
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/collection/collection_ops.rs
lib/collection/src/operations/types.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/shards/dummy_shard.rs
lib/collection/src/shards/forward_proxy_shard.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/proxy_shard.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/shard.rs
lib/common/common/src/rate_limiting.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/conversions.rs
tests/openapi/test_strictmode.py

This PR enables rate limiting through strict mode for read and write requests.
Integration tests are present to validate the limit kicks in with the correct error message.
I validated the precision of the limit with an end to end example for 1000 search req/s.
```http
PUT collections/benchmark
{
"vectors": {
"size": 4,
"distance": "Dot"
},
"strict_mode_config": {
"enabled": true,
"read_rate_limit_per_sec": 1000
}
}
```
Shoot with [oha](https://github.com/hatoo/oha) with 10 concurrent workers for 1 minutes
```bash
oha -m POST  \
-d "{ \"vector\": [0.2, 0.1, 0.9, 0.7], \"limit\": 4 }" \
-T application/json \
-A application/json  \
-z 1m \
-c 10 \
http://127.0.0.1:6333/collections/benchmark/points/search
```
Expected results `1000 rps * 60s = 60k` valid responses per minute.
```
Status code …
```

Rate limiting for shard operations

---

lib/collection/src/operations/conversions.rs

The gRPC interface for creating a new shard key appeared to be broken. Internally it would replace the specified replication factor with the specified number of shards.

Fix broken replication factor in gRPC create shard key

---

lib/collection/src/collection_manager/holders/segment_holder.rs

use tracing instead of debug to make it less noisy
WIP: merge after we confirm it is no longer needed for debugging

Downgrade flush logging

---

lib/collection/src/collection_manager/holders/segment_holder.rs

We added point deduplication logging in <https://github.com/qdrant/qdrant/pull/5577> for evaluating chaos testing. Now we want to demote these logs because they're quite noisy with normal usage.
Originally planned in <https://github.com/qdrant/qdrant/pull/5586> and mentioned again in <https://github.com/qdrant/qdrant/pull/5590#discussion_r1874073972>.

Demote point deduplication logging from debug to trace

---

README.md

The gRPC API documentation on the website (https://qdrant.tech/documentation/interfaces/#grpc-interface) has been updated, but the README.md still points to the old address, causing trouble for those searching for it.
This PR only makes a cosmetic change that do not affect functionality.

Docs: Update the link of gRPC API documentation in README.md

---

lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/collection/src/collection_manager/tests/mod.rs

Same as <https://github.com/qdrant/qdrant/pull/5573>, but for the proxied index changes as described [here](https://github.com/qdrant/qdrant/pull/5573#discussion_r1867551360).
Index changes must be applied in order of their version, because low version changes will be rejected after a high version change. I've added a new struct holding all our index changes that ensures the changes are applied in correct order.
These changes are now also applied before point deletions. Point deletions also bump the segment version, so a point delete with a high version will reject an index change with a lower version if applied after.
3. [x] Have you checked …

 In proxy segment, apply proxied index changes with its operation version

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Release PR for Qdrant 1.12.5.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5461/>.

Bump version to v1.12.5

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.12.6-dev` after publishing <https://github.com/qdrant/qdrant/pull/5611>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5476>.

Bump dev version to 1.12.6-dev

---

lib/segment/src/vector_storage/chunked_mmap_vectors.rs

Save chunked mmap config atomically.
Just flush is not enough because it doesn't guarantee presence on disk. This situation was caught on a real cluster.
Also, this file can be generated from another config. Do it if loading fails.

Atomic save chunked mmap config

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/build.rs
lib/api/src/grpc/conversions.rs
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/shards/local_shard/mod.rs
lib/common/common/src/rate_limiting.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/conversions.rs
tests/openapi/test_strictmode.py

Adjust rate limiter to make it work on a per minute basis.
The main goal is to enable larger burst values.
I took this opportunity to add the missing API validation.
Double checked again with end to end testing for 1000 req/minute
```http
PUT collections/benchmark
{
"vectors": {
"size": 4,
"distance": "Dot"
},
"strict_mode_config": {
"enabled": true,
"read_rate_limit": 1000
}
}
```
Shoot with [oha](https://github.com/hatoo/oha) with 10 concurrent workers for 10 minutes
```bash
oha -m POST  \
-d "{ \"vector\": [0.2, 0.1, 0.9, 0.7], \"limit\": 4 }" \
-T application/json \
-A application/json  \
-z 10m \
-c 10 \
http://127.0.0.1:6333/collections/benchmark/points/search
```
```Status code distribution:
[429] 1641485 responses
[200] 10108 responses
```

Rate limit requests per minute

---

lib/segment/benches/hnsw_build_asymptotic.rs
lib/segment/benches/hnsw_search_graph.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/mod.rs
lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs

This PR performs some integration work required for HNSW links compression.
- `GraphLinksConverter::new()` now takes `m: usize` and `compression: bool`. It is assumed that compression algorithm might sort the first `m`/`2*m` links for each node.
- This PR doesn't include the compression algorithm, so these parameters are ignored for now.
- Some unit tests are updated to test both compressed and uncompressed implementations.
- A new undocumented environment var is added: `__QDRANT_COMPRESSED_LINKS`. When set, it will enable creation of compressed graphs for testing/debugging purposes. By default it's disabled.
Assumption: `m0 == 2*m`.
Depends on #5486, ignore the first commit during review.

GraphLinksConverter: take `m` and `compressed` arguments

---

Cargo.lock
Cargo.toml
lib/common/common/src/mmap_hashmap.rs
lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_common.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
lib/segment/src/index/field_index/mmap_point_to_values.rs
lib/segment/src/index/hnsw_index/graph_links.rs

This PR bumps usage of `zerocopy` from `0.7` to `0.8`.
It's brings some incompatible changes to the API, but the new API neatly simplifies the code that reads items/slices in a sequential manner. Check the updated `MmapPostings::get_reader()`.
A list of changes and migration guide is listed here: https://github.com/google/zerocopy/discussions/1680.

zerocopy: 0.7 -> 0.8

---

lib/storage/src/content_manager/toc/point_ops.rs
src/actix/api/query_api.rs
src/actix/api/update_api.rs
src/actix/auth.rs
src/common/auth/claims.rs
src/common/auth/jwt_parser.rs
src/common/auth/mod.rs
src/common/inference/infer_processing.rs
src/common/inference/mod.rs
src/common/inference/query_requests_grpc.rs
src/common/inference/query_requests_rest.rs
src/common/inference/service.rs
src/common/inference/update_requests.rs
src/common/points.rs
src/tonic/api/points_api.rs
src/tonic/api/points_common.rs
src/tonic/api/points_internal_api.rs
src/tonic/auth.rs

This change enables dynamic token propagation from API requests to the inference service. 
Key changes:
- Add InferenceToken type to hold API tokens from requests
- Modify auth middleware to extract and propagate tokens from request headers 
- Update inference service to accept tokens per-request (when possible)
- Remove requirement for token in config (now optional)
- Thread token through query and update operations
- Fall back to config token if request token is not provided
The main goal is to allow per-request inference tracking with the user specific token rather than using a single global token. 
Technical details:
- Inference token is extracted during auth and stored in request extensions
- Token is propagated through all operations that need inference (queries, updates, etc)
- …

Pass inference API token from request to inference service

---

lib/collection/src/operations/types.rs

I forgot to handle properly the Tonic rate limiting error (introduced in https://github.com/qdrant/qdrant/pull/5538) because of the match all approach.
This PR fixes the missing error handling and switch to an exhaustive match to avoid this kind of error in the future.

Fix handling of rate limiting error for CollectionError

---

docs/redoc/master/openapi.json
lib/storage/src/content_manager/toc/mod.rs
src/actix/api/service_api.rs
src/common/metrics.rs
src/common/telemetry.rs
src/common/telemetry_ops/cluster_telemetry.rs
src/common/telemetry_ops/hardware.rs
src/common/telemetry_ops/memory_telemetry.rs
src/common/telemetry_ops/requests_telemetry.rs
tests/consensus_tests/auth_tests/test_jwt_access.py

- **WIP: per-collection telemetry permissions**
- **upd telemetry**
Always answer something on `GET /telemetry` request. The difference now is that info inside telemetry will be filtered based on the JWT permissions.
Any form of global access can read everything
Collection level-access can only read related collections (collection stats + hardware usage), but can't read:
- requests data
- cluster info
- memory info
Collection level access with payload can't read collection info and hardware counters.

Allow telemetry endpoint for JWT-limited requests

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/conversions.rs
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/collection/mod.rs
lib/collection/src/common/local_data_stats.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/operations/verification/update.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/conversions.rs
tests/openapi/test_strictmode.py

Validate the payload storage size when using the strict mode the same way it was done for `max_collection_vector_size_bytes`.

Strict mode for payload storage

---

lib/segment/src/data_types/facets.rs
lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
lib/segment/src/index/field_index/bool_index/mod.rs
lib/segment/src/index/field_index/bool_index/simple_bool_index.rs
lib/segment/src/index/field_index/facet_index.rs
lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/struct_payload_index.rs
lib/segment/src/segment/facet.rs

Refactors the faceting infrastructure to make all facet-enabled indices implement the same trait.
This also fixes a bug introduced in #5571 ([failed test run](https://github.com/qdrant/qdrant-client/actions/runs/12373060583/job/34533583784?pr=866)) which would iterate over the whole index, instead of just a single point's values

Introduce facet index trait

---

Cargo.lock
lib/common/common/Cargo.toml
lib/common/common/benches/bitpacking.rs
lib/common/common/src/bitpacking.rs
lib/common/common/src/bitpacking_links.rs
lib/common/common/src/lib.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_links.rs

This PR add HNSW graph links compression implementation, both for reading and writing.
The integration is added in #5489: it's disabled by default unless `__QDRANT_COMPRESSED_LINKS` is set.
~Depends on #5486, #5487, #5489, #5490, #5491. Ignore all but the last commit during the review.~

Implement links compression

---

lib/segment/src/fixtures/index_fixtures.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/plain_vector_index.rs
lib/segment/src/index/sparse_index/sparse_vector_index.rs
lib/segment/src/index/vector_index_base.rs
lib/segment/src/segment/entry.rs
lib/segment/src/segment/mod.rs
lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs
lib/sparse/src/common/sparse_vector.rs
lib/sparse/src/index/inverted_index/inverted_index_compressed_immutable_ram.rs
lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs
lib/sparse/src/index/inverted_index/inverted_index_immutable_ram.rs
lib/sparse/src/index/inverted_index/inverted_index_mmap.rs
lib/sparse/src/index/inverted_index/inverted_index_ram.rs
lib/sparse/src/index/inverted_index/inverted_index_ram_builder.rs
lib/sparse/src/index/inverted_index/mod.rs
lib/sparse/src/index/loaders.rs

In #5533 we realized that calculating `total_sparse_vectors_size` on load was inevitable, but we don't want it, reason is:
- to compute it on load, we need to scan the whole storage, which we want to avoid for a mmap storage.
- if we put it in a mmapped file, replayed operations are not idempotent, which leads to a counter which we can't trust.
To solve this, we add `VectorIndex::size_of_searchable_vectors_in_bytes` as a primary source for `VectorStorage::size_of_available_vectors_in_bytes`. All indices have access to the vector storage, so it is easy to use the storage as a fallback if the index does not know it.
Regarding the precision of making this number come from the sparse index, a mutable segment will return an up-to-date number. For the immutable counterpart, we will rely on the …

Prefer vector index for `size_of_available_vectors_in_bytes`

---

lib/blob_store/src/tracker.rs
lib/common/memory/src/mmap_type.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs
tests/storage-compat/storage-compatibility.sh

Addresses https://github.com/qdrant/qdrant/pull/5454#pullrequestreview-2465392680
We want mmap storages to not waste any extra time loading, so this PR refactors `MmapSparseVectorStorage` to get rid of loading and use `DynamicMmapFlags` for deleted flags

Fast loading of mmap sparse storage

---

Cargo.lock
Cargo.toml
lib/segment/benches/hnsw_search_graph.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_links.rs

Depends on #5492. Review only the last two commits.
This PR updates `hnsw_search_graph` benchmark to make it convenient to benchmark changes in the compression implementation.
- Uncompressed HNSW links are cached and preserved across benchmark runs, so you don't have to wait each time you run the benchmark.
- Cache file name: `target/tmp/segment/hnsw_search_graph/1000000-64-16-100-true-Cosine.links`.
- Since HNSW parameters are part of the file name, the index is properly invalidated if you change them.
- Caveat: the vectors are not saved. So the results will be garbage if you change the vectors generation code or seed without manually cleaning the cache. Tho I believe that it will be changed rarely (or never).
- HNSW is built in parallel and the progress is shown using `indicatif` crate. …

Update hnsw_search_graph benchmark

---

lib/storage/src/content_manager/toc/create_collection.rs
lib/storage/src/content_manager/toc/mod.rs
lib/storage/src/content_manager/toc/snapshots.rs
tests/consensus_tests/test_snapshot_recovery.py

Fixes: https://github.com/qdrant/qdrant/issues/5558 
We delay the snapshots path creation (directories and path) when the snapshot api is invoked. We however derive the snapshot path early in the collection creation flow to store a reference of it to be used across other collection API such as listing collection, shard snapshot transfer etc. 
Listing a collection snapshot in absence of the  snapshot path still works since [absence of a directory is returned as an OK of empty Vec](https://github.com/qdrant/qdrant/blob/dev/lib/collection/src/common/snapshots_manager.rs#L241) (which makes sense).

Create snapshots path of collection upon trigger of snapshot api

---

src/tonic/api/raft_api.rs
src/tonic/mod.rs

This PR forces the usage of TLS when a node is joining a cluster but no URL is provided.
In that case we build manually a peer URI which will be used by raft.rs as peer address.
The following patch makes sure that we use `https` in the peer address if a TLS server config is set up.

Use TLS when registering node with TLS server config

---

docs/redoc/master/openapi.json
lib/collection/src/collection/mod.rs
lib/collection/src/common/collection_size_stats.rs
lib/collection/src/common/mod.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/operations/verification/update.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/collection_verification.rs
src/tonic/api/points_internal_api.rs
src/tonic/verification.rs
tests/consensus_tests/fixtures.py
tests/consensus_tests/test_strict_mode.py
tests/consensus_tests/utils.py

Depends on #5588
Allows limiting collection size (vector and payload storage separately) in distributed setups with strict mode.

[Strict Mode] Max collection size in distributed setup

---

lib/collection/src/collection/collection_ops.rs
lib/collection/src/shards/forward_proxy_shard.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/local_shard/shard_ops.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/resharding/stage_migrate_points.rs
lib/collection/src/shards/resharding/stage_propagate_deletes.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/common/common/src/rate_limiting.rs
tests/consensus_tests/test_shard_transfer_rate_limiting.py
tests/consensus_tests/utils.py
tests/openapi/test_strictmode.py

This PR ensures that we do not rate limit internal update operations used during transfers.
This is achieved by lifting the write rate limiter up from local shard to the replica set.
This new location has access to the replica state to decide whether the update should be rate limited.
I have added an integration tests to demonstrate that a shard can be transferred when the write limiting budget is used up.
Interestingly I found a couple of spots where read requests involved in shard transfers are wrongly rate limited.
I have annotated those for a future PR.

Fix rate limiting of internal update operations

---

Cargo.lock

Fixes current `dev` builds:
```bash
error: failed to select a version for the requirement `tracing-serde = "^0.2.0"`
candidate versions found which didn't match: 0.1.3, 0.1.2, 0.1.1, ...
location searched: crates.io index
required by package `tracing-subscriber v0.3.19`
... which satisfies dependency `tracing-subscriber = "^0.3"` (locked to 0.3.19) of package `qdrant v1.12.6-dev (/home/timvisee/git/qdrant)`
```
Used:
```bash
cargo update tracing-subscriber tracing-serde
```

Bump tracing-serde to 0.2.0

---

lib/collection/src/operations/types.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/local_shard/shard_ops.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs
lib/common/common/src/rate_limiting.rs

This PR makes the read rate limiter consume more tokens in case of batched search.
Exactly 1 token per batched request.
This prevents users from sending very large requests without really impacting the request budget.
A similar PR can be applied later to the updates with a similar logic.

Read rate limiter handles batched search requests

---

Cargo.lock
lib/segment/Cargo.toml
lib/segment/benches/hnsw_build_asymptotic.rs
lib/segment/benches/hnsw_search_graph.rs
lib/segment/benches/multi_vector_search.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/mod.rs
lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs
lib/segment/src/index/vector_index_base.rs
lib/segment/src/segment/mod.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/tests/integration/batch_search_test.rs
lib/segment/tests/integration/byte_storage_hnsw_test.rs
lib/segment/tests/integration/byte_storage_quantization_test.rs
lib/segment/tests/integration/exact_search_test.rs
lib/segment/tests/integration/filtrable_hnsw_test.rs
lib/segment/tests/integration/gpu_hnsw_test.rs
lib/segment/tests/integration/hnsw_discover_test.rs
lib/segment/tests/integration/hnsw_quantized_search_test.rs
lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
lib/segment/tests/integration/multivector_hnsw_test.rs
lib/segment/tests/integration/multivector_quantization_test.rs

~Depends on #5666 and #5492. Read only the last commit during the review.~
This PR improves the performance of graph links by merging `impl GraphLinks`, `struct GraphLinksRam` and `struct GraphLinksMmap` into a single `struct GraphLinks`.
The new structure is self-referential (using [`self_cell`](https://docs.rs/self_cell/1.1.0) crate), and contains `GraphLinksView` with precalculated slices.
Enum dispatching is not required: once `GraphLinksView` is created during loading, it doesn't care about the underlying storage type.
At a high level, the new structure looks like this:
```rust
self_cell::self_cell! {
pub struct GraphLinks {
owner: GraphLinksEnum,     // owns the data
#[covariant]
dependent: GraphLinksView, // slice references to the data
}
}
enum GraphLinksEnum {
Ram(Vec<u8>), …
```

GraphLinks: replace trait with enum

---

docs/grpc/docs.md
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/collection/collection_ops.rs
lib/collection/src/collection/mod.rs
lib/collection/src/collection/shard_transfer.rs
lib/collection/src/operations/conversions.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/resharding/stage_migrate_points.rs
lib/collection/src/shards/shard_holder/resharding.rs
lib/collection/src/shards/transfer/helpers.rs
lib/storage/src/content_manager/data_transfer.rs
lib/storage/src/content_manager/snapshots/recover.rs
lib/storage/src/content_manager/toc/collection_meta_ops.rs
src/common/collections.rs
src/common/snapshots.rs

This PR adds `ReshardingScaleDown` replica state (might be renamed into something more sane before merge) and aborts resharding when switching from `ReshardingScaleDown` into `Dead`.
`ReshardingScaleDown` is treated equivalent to `Active` state in most places, because `ReshardingScaleDown` state is sort of a "superset" of `Active` state: `ReshardingScaleDown` replica contains all the same points (and some *additional* points on top) and serves all read and write requests the same way as an `Active` replica.

Abort scale-down resharding on update error

---

Cargo.lock
lib/common/common/Cargo.toml
lib/common/common/benches/bitpacking.rs
lib/common/common/benches/bitpacking_tango.rs
lib/common/common/build.rs
lib/common/common/src/bitpacking.rs
lib/common/common/src/bitpacking_links.rs
lib/common/common/src/lib.rs
lib/common/common/src/num_traits.rs

Depends on #5688 (for benchmarks).
This PR makes `bitpacking` generic to support not only `u32` but also `u64`.
This change makes benchmarks a bit faster. I can pinpoint particular changes in the code that caused it, but I'm not sure why.
```console
$ cargo bench -p common --bench bitpacking_tango -- compare tmp/prev -t 2
bitpacking/read                                    [  38.1 ns ...  36.8 ns ]      -3.29%*
bitpacking/write                                   [  43.4 ns ...  43.2 ns ]      -0.51%
bitpacking_links/read                              [ 349.3 ns ... 341.9 ns ]      -2.12%*
```

bitpacking: make generic

---

docs/DEVELOPMENT.md

This PR adds a `tango` variant of the `bitpacking` benchmark. The logic is identical to the existing `criterion` benchmark.
Unlike `criterion`, `tango` runs two versions of the benchmark at once. So, background system load, CPU temperature, throttling and scaling mechanisms affect both versions equally, making it easier to compare e.g. performance of two commits.
https://www.bazhenov.me/posts/paired-benchmarking/

bitpacking: add tango benchmark

---

src/tracing/config.rs
src/tracing/default.rs
src/tracing/handle.rs
src/tracing/mod.rs
src/tracing/on_disk.rs
src/tracing/test.rs

Basically, subject: simplify JSON logger setup code and copy JSON support to on-disk logger.

Cleanup JSON logger impl and add JSON support to on-disk logger

---

lib/api/src/grpc/conversions.rs

Fixes <https://github.com/qdrant/rust-client/issues/205>
Filter out empty gRPC filter conditions, rather than throwing an error. This was very easily triggered with `Condition::default()` in our Rust client.
Filtering out the condition so it is a 'match all' is probably better and is what users might expect from it.

Filter out empty filter conditions from gRPC

---

Cargo.lock
lib/common/common/Cargo.toml
lib/common/common/benches/bitpacking.rs
lib/common/common/benches/bitpacking_tango.rs
lib/common/common/src/bitpacking_ordered.rs
lib/common/common/src/lib.rs
lib/segment/src/index/hnsw_index/graph_links.rs

In this PR:
- Added a new module `common::bitpacking_ordered`. It compresses ordered `u64` arrays, and allows for fast random reads within the compressed data.
- The new module is used to compress offsets in `links.bin` file.
| Dataset                        | Uncompressed   | Compressed links<br>(current dev) | Compressed links and<br> offsets (this PR) |
| ------------------------------ | -------------- | --------------------------------- | ------------------------------------------ |
| deep-image-96-angular          | 1115M (155.7%) | 716M (100%)                       | 633M (88.4%)                               |
| dbpedia-openai-1M-1536-angular | 116M (184.1%)  | 63M (100%)                        | 55M (87.3%)                                |
| glove-100-angular              | 149M …

Compress offsets in `links.bin`

---

docs/redoc/master/openapi.json
lib/collection/src/shards/replica_set/mod.rs

Expose the `PartialSnapshot` replica state, so that clients don't crash on old Qdrant versions that still expose this state.

Expose the PartialSnapshot replica state

---

Cargo.lock
Cargo.toml

We only need to parse `yaml` files therefore we can avoid all the dependencies required for other formats.
https://docs.rs/crate/config/0.15.4/features

Disable default-feature for config crate

---

Cargo.lock
Cargo.toml
lib/blob_store/Cargo.toml
lib/collection/Cargo.toml
lib/gpu/Cargo.toml
lib/segment/Cargo.toml

This PR refactor our rstest integration
- promote dependency to workspace
- remove [default features](https://docs.rs/crate/rstest/latest/features#crate-name)
- bump version [0.24.0](https://github.com/la10736/rstest/releases/tag/v0.24.0)

Refactor rstest usage

---

.github/workflows/integration-tests.yml
tests/integration-tests.sh

Configure `pytest` to report  the top 10 slowest tests for openapi and consensus tests.
The goal is to keep an eye on the run time to find possible improvements.
```
============================= slowest 10 durations ==============================
46.81s call     tests/openapi/test_strictmode.py::test_strict_mode_max_collection_payload_size_upsert
46.53s call     tests/openapi/test_strictmode.py::test_strict_mode_max_collection_payload_size_upsert_batch
6.50s setup    tests/openapi/test_filtered_delete.py::test_delete_by_payload_filter[True]
5.16s setup    tests/openapi/test_filtered_delete.py::test_delete_by_payload_filter[False]
2.67s teardown tests/openapi/test_payload_indexing.py::test_payload_schemas
2.30s call     tests/openapi/test_payload_indexing.py::test_payload_schemas
2.24s …
```

Track slow pytest integration tests

---

Cargo.lock
Cargo.toml
lib/common/issues/Cargo.toml
lib/segment/Cargo.toml
lib/storage/Cargo.toml

Update and standardize the http crate [version](https://github.com/hyperium/http/blob/master/CHANGELOG.md).

Standardize http crate version

---

.github/workflows/integration-tests.yml

It looks like the default poetry version installed changed over the weekend which breaks our CI.
```
You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.
Installing Poetry (2.0.0)
Installing Poetry (2.0.0): Creating environment
Installing Poetry (2.0.0): Installing Poetry
Installing Poetry (2.0.0): Creating script
Installing Poetry (2.0.0): Done
Poetry (2.0.0) is installed now. Great!
You can test that everything is set up by executing:
`poetry --version`
Warning: [tool.poetry.name] is deprecated. Use [project.name] instead.
Error: Process completed with exit code 1.
```
This PR proposes to fix the version of poetry to restore the previous behavior.

Fix poetry version in CI

---

README.md

Fixes <https://github.com/qdrant/qdrant/issues/5731>
fix : correct broken newsletter link
Wrong hyperlink to newsletter in README

Newsletter redirect link broken

---

lib/common/issues/src/dashboard.rs

Rust 1.84 lands on [January 9th](https://releases.rs/docs/1.84.0/)
Lucky for us there is only a tiny Clippy violation this time around.

Fix clippy 1.84

---

docs/redoc/master/openapi.json
lib/collection/src/operations/cluster_ops.rs
lib/collection/src/operations/types.rs
lib/collection/src/shards/resharding/mod.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/shards/shard_holder/resharding.rs
src/common/collections.rs

Add a UUID to resharding operations so we can uniquely identify them in cluster manager.
This is needed to prevent conflicts with reusing state when a collection is recreated.

Resharding: add UUID to resharding operation

---

lib/segment/benches/hnsw_build_asymptotic.rs
lib/segment/benches/hnsw_search_graph.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/mod.rs
lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs

This is an alternative implementation of #5704.
Changes compared to #5704:
- Instead of dealing with link filenames inside of `HNSWIndex`, encapsulate this logic into `GraphLayers`.
- Replace boolean logic with a new enum `GraphLinksFormat`.

Separate file for compressed links; variant 2

---

lib/blob_store/src/blob_store.rs
lib/blob_store/src/config.rs
lib/common/common/src/delta_pack.rs
lib/common/common/src/lib.rs
lib/segment/Cargo.toml
lib/segment/benches/sparse_vector_storage.rs
lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
lib/segment/src/vector_storage/sparse/mod.rs
lib/segment/src/vector_storage/sparse/stored_sparse_vectors.rs
lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs
lib/sparse/src/common/sparse_vector.rs
lib/sparse/src/common/types.rs
tests/storage-compat/storage-compatibility.sh

Eventually we want to allow 64bit `DimId` for sparse vectors. This is one of the steps towards.

use 64-bit dim-id for storing sparse vectors

---

lib/segment/src/index/hnsw_index/gpu/shaders/shared_buffer.comp

Fix bitonic sort bug. No test is required, this bug was found on GPU CI on an emulated GPU device:
https://github.com/qdrant/qdrant/actions/runs/12658322098/job/35274994845

Fix GPU sorting bug for low-end devices

---

.github/workflows/dev-docker-image-build-gpu.yml
.github/workflows/docker-image.yml
.github/workflows/rust-gpu.yml

This PR adds GPU into qdrant CI. It includes:
1. Run GPU unit tests. Trigger conditions: manual or merge into master
2. Build and push image into ghcr. Triggered manually only
3. Publish GPU images while release process
GPU images have tags with `-gpu-nvidia` or `-gpu-amd` postfix. Only x64, no arm because GPU image bases don't have arm builds. No unprivileged images for now.
Unit tests were processed using the LLVMPipe - Vulkan driver, which uses CPU to emulate compiled SPIR-V shaders. Tests pass
https://github.com/qdrant/qdrant/actions/runs/12668441957/job/35303874213?pr=5752

Add GPU into github workflows

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Release PR for Qdrant 1.12.6
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5611>.

Bump version to 1.12.6

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.12.7-dev` after publishing <https://github.com/qdrant/qdrant/pull/5759>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5612>.

Bump dev version to 1.12.7-dev

---

src/common/telemetry_ops/memory_telemetry.rs

Spotted on CI.
```
warning: unused import: `AccessRequirements`
--> src\common\telemetry_ops\memory_telemetry.rs:4:29
|
4 | use storage::rbac::{Access, AccessRequirements};
|                             ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```

Fix Clippy unused import on Windows

---

Cargo.lock
Cargo.toml
lib/collection/src/common/snapshots_manager.rs
lib/collection/src/operations/shared_storage_config.rs
lib/storage/src/types.rs

This PR updates to config [0.15.4](https://github.com/rust-cli/config-rs/blob/main/CHANGELOG.md#change-log)
The most important changes is that the configuration keys are now case sensitive.
We are only impacted for the `SnapshotsStorageConfig` where our default configuration uses lower case.
The solution is to apply `#[serde(rename_all = "lowercase")]` to the enum as usual.

Update config 0.15.4

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/conversions.rs
lib/api/src/grpc/proto/points.proto
lib/api/src/grpc/qdrant.rs
lib/api/src/rest/models.rs
lib/collection/src/shards/remote_shard.rs
lib/common/common/src/counter/hardware_accumulator.rs
lib/common/common/src/counter/hardware_counter.rs
lib/storage/src/content_manager/toc/mod.rs
lib/storage/src/content_manager/toc/request_hw_counter.rs
src/common/metrics.rs

Adds two new metrics (`io_read` and `io_write`) to hardware counter types and Telemetry

IO metrics in hw counter types

---

tests/storage-compat/storage-compatibility.sh

We want to make sure that we are compatible with the latest minor version and previous patch.
`v1.12.6-rocksdb+blob_store-pre_release` did not contain proper blob store data as the script did not activate the feature properly.
I fixed this in a new archive and also documented how to do it.
I validated that the archive uses the new blob store for payload storage and sparse vector storage.

Update storage compat 1.11 & 1.12

---

lib/collection/src/config.rs
lib/collection/src/operations/conversions.rs
lib/collection/src/operations/types.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/toc/create_collection.rs
lib/storage/src/types.rs
lib/storage/tests/integration/alias_tests.rs

Prepare for the release of Qdrant 1.13 and enable the mmap storage for sparse vectors using blob store by default. This allows us to test it on chaos testing for some time.

Enable mmap storage using blob store for sparse vectors by default

---

lib/collection/src/shards/replica_set/mod.rs
tests/consensus_tests/test_resharding.py

This attempts to fix a count assertion in a resharding test ([ref](https://github.com/qdrant/qdrant/actions/runs/12744537238/job/35516646241?pr=5757#step:11:129)).
It does two things:
1. when deleting points to clean up, wait on the operation to complete
2. use exact point counts in tests
I was not able to reproduce this problem locally, so I'm depending on CI here to tell us if something is still off.

Resharding: wait on clean up deletes, exact counting in tests

---

Dockerfile

Those deps were introduced in https://github.com/qdrant/qdrant/pull/5765/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557.
But then partially reverted in https://github.com/qdrant/qdrant/pull/5768/files
The docker part was missing.

Remove unecessary docker build dependency

---

tests/openapi/test_strictmode.py

Tackles https://github.com/qdrant/qdrant/issues/5669
Now that the mmap blob store is the default payload storage we can refactor the tests to not wait anymore for compaction.
I took care of the consensus tests already in https://github.com/qdrant/qdrant/pull/5783/commits/7823ebe941e62b127ba04da76c632684e7d75495

Migrate strict mode payload test for mmap

---

docs/grpc/docs.md
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/operations/conversions.rs

The gRPC API did not expose what direction we were resharding into.

Resharding: expose direction in gRPC API

---

tests/consensus_tests/test_resharding.py

Add a CI test for <https://github.com/qdrant/qdrant/pull/5792>.
This test covers the specific scenario where aborting resharding when we already have extra replicas previously failed.
~Note: this PR fails until <https://github.com/qdrant/qdrant/pull/5792> is merged and rebased upon.~

Resharding: add test for abort resharding fix

---

lib/storage/src/content_manager/consensus/persistent.rs
lib/storage/src/content_manager/consensus_manager.rs

Currently, if we continuously add and remove peers to the cluster, `raft_metadata.json` will keep growing. This PR fixes it.

Remove peer metadata from Raft state, when removing peer

---

lib/api/build.rs
lib/api/src/grpc/qdrant.rs

Fixes <https://github.com/qdrant/qdrant/issues/5807>.
The deleted threshold validation in our gRPC interface was incorrect. It should allow a range of [0.0, 1.0].
The REST interface was already set up correctly.

Fix gRPC deleted threshold validation 

---

lib/storage/src/content_manager/collection_meta_ops.rs
lib/storage/src/content_manager/conversions.rs
lib/storage/src/content_manager/snapshots/recover.rs
lib/storage/tests/integration/alias_tests.rs
src/actix/api/collections_api.rs
src/consensus.rs
src/migrations/single_to_cluster.rs
tests/openapi/test_sparse_vector_persistence.py

Tackling https://github.com/qdrant/qdrant/issues/3184
The new validation kicks in for both REST and gRPC.

API validation for unique dense and sparse vector names

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.13.1-dev` after publishing <https://github.com/qdrant/qdrant/pull/5814>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5760>.

Bump dev version to 1.13.1-dev

---

lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/graph_links/header.rs
lib/segment/src/index/hnsw_index/graph_links/serializer.rs
lib/segment/src/index/hnsw_index/graph_links/view.rs

This PR splits and cleans-up `graph_links.rs`. Full list of changes:
- Rename `GraphLinksConverter` to `GraphLinksSerializer`.
- Extract some structs from `graph_links.rs` into separate files:
- (33 lines) `graph_links/header.rs`: `HeaderPlain` and `HeaderCompressed`.
- (225 lines) `graph_links/serializer.rs`: for `GraphLinksSerializer`.
- (171 lines) `graph_links/view.rs`: `GraphLinksView`.
- (332 lines) `graph_links.rs`: `GraphLinks`, `GraphLinksEnum`, tests.
- In `header.rs`, remove `HeaderCompressed::version` doc comment about `HEADER_VERSION_COMPRESSED` as being outdated after merging #5749.
- Add doc comment to `GraphLinksView`.
- In `view.rs`/`GraphLinksView`, move some associated functions to the module level:
- `read_level_offsets`
- `get_slice`
- `error_unsufficent_size`

Rearrange graph_links.rs

---

lib/collection/src/collection/clean.rs
lib/collection/src/operations/verification/mod.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/sparse_index/mod.rs
lib/segment/src/vector_storage/async_io_mock.rs
lib/sparse/benches/prof.rs
lib/sparse/src/index/inverted_index/inverted_index_compressed_immutable_ram.rs
lib/sparse/src/index/mod.rs
lib/sparse/src/index/search_context.rs
lib/storage/src/content_manager/toc/collection_container.rs
src/actix/helpers.rs
src/actix/mod.rs
src/common/health.rs
src/common/inference/mod.rs
src/common/mod.rs
src/common/stacktrace.rs
src/common/telemetry_ops/requests_telemetry.rs
src/schema_generator.rs
src/settings.rs
src/tracing/mod.rs

This PR
- replaces multiple `#[allow(dead_code)]` in the main `qdrant` crate with a single module-level annotation in `schema_generator.rs`
- removes `#[allow(dead_code)]` annotations, that are not required anymore
- and in a few places it replaces `#[allow(dead_code)]` annotations on unused structure fields with `_` prefix

Cleanup `#[allow(dead_code)]` annotations

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/conversions.rs
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/qdrant.rs
lib/api/src/rest/schema.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/operations/verification/update.rs
lib/segment/src/data_types/tiny_map.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/conversions.rs
tests/openapi/helpers/collection_setup.py
tests/openapi/test_strictmode.py

This PR adds a strict mode to multivector in order to bound the maximum number of vector a multivector can have.
The validation is triggered when inserting or updating points.
A new field is added to the strict mode to associate a multivector config to a named vector.
e.g.
```json
{
"enabled": true,
"multivector_config": {
"dense-multi": {
"max_vectors": 5
}
}
}
```
I used a configuration object to enable adding new constraints in the future.

Strict mode multivector

---

lib/collection/src/collection/snapshots.rs
lib/collection/src/collection/state_management.rs
lib/collection/src/collection_state.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/shards/shard_holder/shard_mapping.rs
lib/collection/src/shards/transfer/helpers.rs
tests/consensus_tests/test_custom_sharding.py

Our shard key mapping storage for [user defined sharding](https://qdrant.tech/documentation/guides/distributed_deployment/#user-defined-sharding) appears to be broken.
We support two types of custom shard keys, a string and a number. The shard key numbers are not persisted properly and are converted into shard key strings on load. This breaks user defined sharding because the strings and numbers are not interchangeable.
This changes the format in which we persist shard keys to fix this very problem. The new format uses better typing, so that numbers and strings can properly be distinguished.
More specifically, we now have two formats:
- The `Old` format is the original format from when shard key mappings were implemented
- The `New` format is a more robust, properly persisting shard key …

Fix broken shard key mapping storage, keep shard key numbers

---

lib/common/memory/src/mmap_ops.rs
lib/segment/src/vector_storage/dense/dynamic_mmap_flags.rs
lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
lib/segment/src/vector_storage/quantized/quantized_mmap_storage.rs
lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs

As I was auditing the options combinations, I noticed that all `OpenOptions` flags are [false when creating the struct](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.new), so there is no need to specify them explicitly.

Remove setting OpenOptions flags to false

---

lib/blob_store/src/blob_store.rs

We have a precise flushing sequence to ensure the consistency of the various data we managed.
Deciding to flush on drop could break this in unexpected ways.
This PR proposes to remove this implementation.

No flush on Drop for Blobstore

---

lib/common/memory/src/mmap_type.rs
lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs

Discovered when running crasher 🔥 
The problem arose when trying to convert an empty `ImmutableInvertedIndex` into a `MmapInvertedIndex`, which would create zero-sized files.
There seems to be no problem mmapping them, but, when we try to `msync` during flushing, it panics with an [`EINVAL` error](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/msync.2.html#//apple_ref/doc/man/2/msync).
I have done a simple fix where we just don't flush when the file length is zero.

Avoid flushing a zero-sized mmapped file

---

lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs

Another crasher failure fix:
```log
2025-01-21T16:05:15.084473Z ERROR qdrant::startup: Panic occurred in file lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs at line 163: index out of bounds: the len is 1559 but the index is 1592
[...]
2025-01-21T16:05:15.887828Z ERROR qdrant::startup: Panic occurred in file /Users/luis/personal/Qdrant/qdrant/lib/collection/src/shards/replica_set/mod.rs at line 301: Failed to load local shard "./storage/collections/workload-crasher/0": Service internal error: Failed to join task that removes duplicate points from segment: task 33 panicked with message "index out of bounds: the len is 1559 but the index is 1592"
```
We missed to consider that the `deleted_points` bitslice can be bigger than `point_to_tokens_count`, so this …

Safe bounds for `point_to_tokens_count`

---

.codespellrc
.github/workflows/codespell.yml

This PR updates codespell config.
Primary change:
- added new word `ABD` to fix this recent error ([GitHub actions log](https://github.com/qdrant/qdrant/actions/runs/12901056521/job/35972529860?pr=5820)):
```
Error: ./lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs:46: ABD ==> AND, BAD
```
Nice-to haves in this PR:
- Entries are split into multiple lines and reorganized for easier maintaining. Redundant entries removed.
- Added some entries from `.gitignore` (like `static`,`target`, etc), so it's now properly runnable locally using the [`codespell`](https://github.com/codespell-project/codespell) command.
- Removed options from `.github/workflows/codespell.yml`. Let `.codespellrc` be the single source of truth.
(not in this PR) Ideally, we'd move/convert `.codespellrc` to …

Update codespell config

---

Cargo.lock
Cargo.toml
lib/collection/src/collection_manager/search_result_aggregator.rs
lib/common/common/Cargo.toml
lib/common/common/src/fixed_length_priority_queue.rs
lib/segment/src/index/hnsw_index/entry_points.rs
lib/segment/src/index/hnsw_index/gpu/gpu_heap_tests.rs
lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs
lib/segment/src/spaces/tools.rs
lib/segment/src/vector_storage/async_raw_scorer.rs
lib/segment/src/vector_storage/raw_scorer.rs

`FixedLengthPriorityQueue` API is confusing. Some iterators/conversions are ordered, some are not. Furthermore, these two implementations of `IntoIterator` contradict each other.
```rust
// unordered
impl<'a, T: Ord> IntoIterator for &'a FixedLengthPriorityQueue<T> { … }
// ordered
impl<T: Ord> IntoIterator for FixedLengthPriorityQueue<T> { … }
```
Giving that they are called implicitly, it makes things confusing:
```rust
let mut q = FixedLengthPriorityQueue::new(5);
for i in (0..5).rev() {
q.push(i);
}
let mut a1 = Vec::new();
for &i in &q { // unordered
a1.push(i);
}
let mut a2 = Vec::new();
for i in q { // ordered
a2.push(i);
}
assert_eq!(a1, a2); // panic: [2, 4, 3, 1, 0] != [4, 3, 2, 1, 0]
```
This PR makes API more explicit:
- Implementations of `IntoIterator` are removed in favor …

FixedLengthPriorityQueue: explicit sorted/unsorted methods

---

lib/common/common/src/lib.rs
lib/common/common/src/small_uint.rs
lib/segment/src/id_tracker/immutable_id_tracker.rs
lib/segment/src/id_tracker/in_memory_id_tracker.rs
lib/segment/src/id_tracker/mod.rs
lib/segment/src/id_tracker/point_mappings.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/types.rs

This PR optimizes RAM usage of `SegmentBuilder::update()`. Two primary ideas: k-way merge and structure packing.
We have a list of segments and we want to deduplicate point IDs within them. Previously we were using a huge `HashMap` for that. This required a lot of temporary memory.
But! Our `IdTracker`s let us iterate over IDs in a sorted order. By applying a k-way merge algorithm (which is kindly provided by `itertools`) we can iterate and deduplicate points across all segments in a single pass.
The size of the `ExtendedPointId` enum is 24 which is excessive given that `Uuid` is 16 bytes long. The reason is the 8-byte alignment of `u64`.
By replacing `u64` with `[u8; 8]` (which doesn't require alignment), we can reduce the size of `ExtendedPointId` to 17 bytes. I've used …

Optimize `merged_points` computation in `SegmentBuilder::update()`

---

lib/gpu/Cargo.toml
lib/gpu/src/context.rs
lib/gpu/src/debug_messenger.rs
lib/gpu/src/device.rs
lib/gpu/src/instance.rs
lib/gpu/src/lib.rs
lib/gpu/src/pipeline.rs

This PR enables our default set of lints for the `gpu` crate and fixes them.
Fixes are performed automatically using the following command:
```console
cargo clippy -p gpu --all-features --all-targets
```
---
For the reference, a command to find crates without lints enabled:
```console
find -name Cargo.toml | xargs grep -L '^workspace = true$'
```
(currently only `gpu` is missing)

Enable workspace lints for `gpu`

---

lib/segment/src/index/hnsw_index/gpu/gpu_links.rs
lib/segment/src/index/hnsw_index/gpu/shaders/run_insert_vector.comp
lib/segment/src/index/hnsw_index/gpu/shaders/search_context.comp

Fix https://github.com/qdrant/qdrant/issues/5834
It's a quick fix which includes additional sync in shaders and results filtering.
It's not a proper solution but it fixes panic.

Filter broken gpu links

---

Cargo.toml
lib/api/src/conversions/vectors.rs
lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/collection_manager/probabilistic_segment_search_sampling.rs
lib/collection/src/collection_manager/segments_searcher.rs
lib/collection/src/operations/point_ops.rs
lib/collection/src/operations/snapshot_storage_ops.rs
lib/collection/src/operations/universal_query/collection_query.rs
lib/collection/src/operations/universal_query/mod.rs
lib/collection/src/shards/replica_set/clock_set.rs
lib/collection/src/shards/resolve.rs
lib/common/common/src/counter/counter_cell.rs
lib/common/memory/src/mmap_type.rs
lib/common/memory/src/mmap_type_readonly.rs
lib/segment/src/common/macros.rs
lib/segment/src/common/reciprocal_rank_fusion.rs
lib/segment/src/common/score_fusion.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
lib/segment/src/json_path/mod.rs
lib/segment/src/vector_storage/query_scorer/mod.rs
lib/sparse/src/index/compressed_posting_list.rs

Consider this review comment: https://github.com/qdrant/qdrant/pull/5820#discussion_r1924021890
These type of mistakes could be caught automatically by running `cargo doc`.
And, in fact, we have a few outdated references.
This PR fixes all issues found by running this command:
```bash
cargo doc --no-deps --document-private-items --workspace --all-features
```
Tho, this approach doesn't catch all possible errors:
- ```rust
/// Only identifiers marked as links [`LikeThis`] or [LikeThis] are checked,
/// but not `LikeThis` or LikeThis without brackets.
```
- `cargo doc` doesn't check comments in benchmark and tests.
- Only `/// doc comments` are checked, but not `// regular comments`.
Not adding it to CI yet as it could negatively affect CI times, it needs measurements.

Fix cargo doc warnings

---

lib/collection/src/operations/types.rs
lib/common/io/src/file_operations.rs
lib/segment/src/common/operation_error.rs

This PR
- removes unused error variant from `OperationError` in `segment` crate
- removes an error variant from `common::io::file_operations::Error` type and tweaks error conversions
It's just some small things I've noticed while reading `segment` crate code.

Cleanup some error types and conversions

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Release PR for Qdrant 1.13.1.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5759>.

Bump version to v1.13.1

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.13.2-dev` after publishing <https://github.com/qdrant/qdrant/pull/5864>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5815>.

Bump dev version to 1.13.2-dev

---

docs/redoc/master/openapi.json
lib/segment/src/types.rs

No more warning.
```
validating openapi-merged.yaml...
openapi-merged.yaml: validated in 300ms
Woohoo! Your OpenAPI definition is valid.
```

Use deny_unknown_fields

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/conversions.rs
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/operations/verification/update.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/conversions.rs
tests/openapi/test_strictmode.py

New sparse_config field in StrictModeConfig that allows setting maximum length constraints for sparse vectors
Each named sparse vector can have its own max_length limit.
The system will validate that both indices and values arrays in sparse vectors don't exceed the configured limit
Validation occurs during point insertion and update operations.
Attempts to insert or update sparse vectors exceeding the configured length limit will result in an error.

Strict mode sparsevector

---

lib/segment/benches/multi_vector_search.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/tests/integration/batch_search_test.rs
lib/segment/tests/integration/byte_storage_hnsw_test.rs
lib/segment/tests/integration/byte_storage_quantization_test.rs
lib/segment/tests/integration/exact_search_test.rs
lib/segment/tests/integration/filtrable_hnsw_test.rs
lib/segment/tests/integration/gpu_hnsw_test.rs
lib/segment/tests/integration/hnsw_discover_test.rs
lib/segment/tests/integration/hnsw_quantized_search_test.rs
lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
lib/segment/tests/integration/multivector_hnsw_test.rs
lib/segment/tests/integration/multivector_quantization_test.rs

Currently, `HNSWIndex::open()` is responsible for both opening and building the index.
Some of the `open()` parameters are relevant only for the building process, but callers still have to provide them.
Pending PR #5835 adds yet additional build-only parameter to the pile, so we decided to split it into two methods: `open()` and `build()`.
https://github.com/qdrant/qdrant/pull/5835#discussion_r1924136245
In this PR:
1. `HNSWIndex::open()` is split into `HNSWIndex::open()` and `HNSWIndex::build()`.
2. The former is read-only and the latter writes the index.
3. The changes in the API are illustrated by the following command that was used to automatically rewrite call sites:
```shell
ast-grep run -i --pattern '
HNSWIndex::open(HnswIndexOpenArgs {
path: $A,
id_tracker: $B,
vector_storage: $C, …
```

Split HNSWIndex::open and HNSWIndex::build

---

shell.nix

This PR updates `shell.nix` to let Qdrand find `libvulkan.so.1`.
Tested only on NixOS. Not sure how it would affect nix without NixOS on Linux/macOS/Windows.

shell.nix: add vulkan-loader to LD_LIBRARY_PATH

---

lib/segment/benches/multi_vector_search.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/tests/integration/batch_search_test.rs
lib/segment/tests/integration/byte_storage_hnsw_test.rs
lib/segment/tests/integration/byte_storage_quantization_test.rs
lib/segment/tests/integration/exact_search_test.rs
lib/segment/tests/integration/filtrable_hnsw_test.rs
lib/segment/tests/integration/gpu_hnsw_test.rs
lib/segment/tests/integration/hnsw_discover_test.rs
lib/segment/tests/integration/hnsw_quantized_search_test.rs
lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
lib/segment/tests/integration/multivector_hnsw_test.rs
lib/segment/tests/integration/multivector_quantization_test.rs

This PR lets segment builder to pass `old_indices` to `HNSWIndex::new`.
In subsequent PRs these indices would be used for incremental index building.

Pass `old_indices` to `HNSWIndex::new`

---

Cargo.lock
Cargo.toml

Itertools 0.14.0 has been out for a month but for some reason Dependabot is not picking it up.
https://github.com/rust-itertools/itertools/blob/master/CHANGELOG.md#0140

Bump itertools 0.14

---

lib/blob_store/src/bitmask/gaps.rs
lib/blob_store/src/bitmask/mod.rs
lib/blob_store/src/blob_store.rs

There was a case, where we were missing to scan a section of the gaps to find a spot to write. 
Even when having enough space in the last region + next to last region, the logic was exiting earlier and causing a panic because there were "allegedly" no more pages even after giving the opportunity to create them.
This PR rewrites the logic and fixes it by ensuring all cases are covered before responding that there is no gap large enough. Now it does one pass with the minimum amount of regions, and another one with the maximum if needed.

Fix gap finding logic

---

lib/gpu/src/basic_test.rs
lib/gpu/src/device.rs
lib/gpu/src/instance.rs
lib/segment/src/index/hnsw_index/gpu/gpu_devices_manager.rs
lib/segment/src/index/hnsw_index/gpu/gpu_graph_builder.rs
lib/segment/src/index/hnsw_index/gpu/gpu_heap_tests.rs
lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
lib/segment/src/index/hnsw_index/gpu/gpu_level_builder.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
lib/segment/tests/integration/gpu_hnsw_test.rs

Fix https://github.com/qdrant/qdrant/issues/5872
If GPU does not support f16, use f32 instead.
This PR includes:
1. Fix the bug. Convert all `f16` into `f32` when GPU does not support `f16`.
2. Provide `skip_half_precision` to force disabled halfs in tests.
3. Unit test for this case.
4. Fix printing of missed GPU features.
5. Builder for `gpu::Instance` cause there are too many optional parameters.
GPU CI: https://github.com/qdrant/qdrant/actions/runs/12999767731

Support gpu devices without half float

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Release PR for Qdrant 1.13.2.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5864>.

Bump version to 1.13.2

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to `1.13.3-dev` after publishing <https://github.com/qdrant/qdrant/pull/5893>.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5867>.

Bump dev  version to 1.13.3-dev

---

Cargo.toml
src/consensus.rs
tests/consensus_tests/utils.py

This PR fixes two non-critical performance bugs in consensus loop:
<details>
<summary>Node that receives constant stream of consensus updates will trigger excessive Raft elections</summary>
Our consensus loop is structured in the following way:
- [take messages from Raft message queue, and propagate them into Raft node][advance-node]
- [tick node _as many times as necessary_ since last tick][tick]
- [process `on_ready`][process-on-ready]
There's a corner case with this loop structure:
1. Imagine we have a node that receives a constant stream of updates. E.g., it's a new node, or it was offline and needs to catch up with the cluster.
2. Such node receives a constant stream of updates from the leader, so on each iteration of consensus loop we would propagate a full batch of messages to Raft …

Optimize consensus loop

---

lib/collection/src/shards/local_shard/shard_ops.rs

The existing read rate limiter for the query API only accounted for the number of queries per batch.
However, it did not account for the content of each single query whose prefetches are extended into a series of search and scroll.

Rate limit prefetches in query API

---

lib/collection/src/collection_manager/search_result_aggregator.rs

same motivation as https://github.com/qdrant/qdrant/pulls?q=is:pr%20is:closed
we have a `debug_assert` to catch this in test but we can go further by never creating the synthetic version

search filters out points without version to honor flushing sequence

---

lib/storage/src/content_manager/consensus_manager.rs

This PR should fix current issue we see on chaos-testing. Seems like Raft needs to be able to access the last committed (i.e., "applied") entry. My bad, documentation on compaction is not stellar. ¯\\\_(ツ)\_/¯

Compact Raft WAL until last *applied* entry, not until first *unapplied*

---

Cargo.toml
src/main.rs

Fixes <https://github.com/qdrant/qdrant/issues/5880>
This allows you to start Qdrant in cluster mode without any CLI arguments, like:
```bash
QDRANT__CLUSTER__ENABLED=true QDRANT_URI=https://localhost:6335/ ./qdrant
```

Allow to set peer and boostrap URI through environment variable

---

lib/storage/src/content_manager/consensus_manager.rs

Fix for new subtraction overflow in <https://github.com/qdrant/qdrant/pull/5900>.
Without this fix I get the following text failure in <https://github.com/qdrant/qdrant/pull/5903> when consensus snapshots are enabled:
```
2025-01-29T15:55:15.176888Z ERROR qdrant::startup: Panic occurred in file /home/timvisee/git/qdrant/lib/storage/src/content_manager/consensus_manager.rs at line 791: attempt to subtract with overflow
```
3. [x] Have you checked your code using `cargo clippy --all --all-features` command

Fix subtract overflow when counting consensus compact entries

---

lib/collection/src/collection/point_ops.rs
lib/collection/src/common/fetch_vectors.rs

When running a query request per vector value such as
```http
POST collections/benchmark/points/query
{
"query": [
0.2,
0.1,
0.9,
0.4
],
"using": "dense",
"limit": 4
}
```
we first try to find referenced vectors that need to be resolved.
In that case they are none.
However the implementation still generated a retrieve request for empty list for `ids`.
I discovered this while testing the rate limiter against the query endpoint which would mysteriously consume twice the amount of token per request.
The fix is two fold:
- for the query API, do not generate empty retrieve request
- for the collection API, shortcut all empty retrieve request to cover other potential misuses
The effects are:
- fixing read rate limiters
- increase performance of query per value by removing unnecessary segment …

Fix query per vector to not generate an empty retrieve request

---

docs/redoc/master/openapi.json
openapi/openapi-main.ytt.yaml

We've deprecated search, recommendation and discovery endpoints in favour of query endpoint, however, these endpoints have no difference in documentation and might cause ambiguity for the users.
In this PR I changed .ytt files and added `deprecated: true` for the corresponding endpoints to strike them through in the docs

deprecate old search api endpoints

---

lib/segment/src/id_tracker/simple_id_tracker.rs
lib/segment/src/segment/segment_ops.rs

The feature `data-consistency-check` enables an optional data consistency check after the WAL run.
It validates that segments are consistent on their own which can be overly restrictive because a shard can still be consistent after merging points from underlying segments.
This patch ignores the check for a particular case involving unflushed points behind resurrected by the WAL replay.

Relax consistency check for WAL replay

---

lib/collection/src/collection_manager/fixtures.rs
lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
lib/segment/benches/segment_info.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs
lib/segment/src/segment/tests.rs
lib/segment/src/segment_constructor/simple_segment_constructor.rs
lib/segment/tests/integration/batch_search_test.rs
lib/segment/tests/integration/byte_storage_hnsw_test.rs
lib/segment/tests/integration/disbalanced_vectors_test.rs
lib/segment/tests/integration/exact_search_test.rs
lib/segment/tests/integration/filtrable_hnsw_test.rs
lib/segment/tests/integration/gpu_hnsw_test.rs
lib/segment/tests/integration/hnsw_discover_test.rs
lib/segment/tests/integration/hnsw_quantized_search_test.rs
lib/segment/tests/integration/multivector_hnsw_test.rs
lib/segment/tests/integration/payload_index_test.rs
lib/segment/tests/integration/segment_on_disk_snapshot.rs

This PR removes a bit of boilerplate from our tests by replacing code like this:
```rust
let config = SegmentConfig {
vector_data: HashMap::from([(
DEFAULT_VECTOR_NAME.to_owned(),
VectorDataConfig {
size: dim,
distance: Distance::Dot,
storage_type: VectorStorageType::Memory,
index: Indexes::Plain {},
quantization_config: None,
multivector_config: None,
datatype: None,
},
)]),
sparse_vector_data: Default::default(),
payload_storage_type: Default::default(),
};
let mut segment = build_segment(dir.path(), &config, true).unwrap();
```
… with code line this:
```rust
let mut segment = build_simple_segment(dir.path(), dim, Distance::Dot).unwrap();
```
---
The second commit is performed automatically using the following `ast-grep` rules:
<details><summary><code>make_rules.py</code></summary> …

Use `simple_segment_constructor`

---

Cargo.lock
lib/common/common/Cargo.toml
lib/common/common/benches/bitpacking.rs
lib/common/common/benches/bitpacking_tango.rs
lib/common/common/src/bitpacking.rs
lib/common/common/src/bitpacking_links.rs
lib/common/common/src/iterator_ext/mod.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/graph_links/view.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs

Initially, a simple interface of `for_each_packed_link()` was enough for a search use case. However, it's not convenient for other cases (e.g. incremental HNSW); a proper `Iterator` is more convenient.
This PR replaces `fn for_each_packed_link()` with `fn iterate_packed_links()` which returns an `Iterator`.
<table><th>Old<th>New<tr><td>
```rust
pub fn for_each_packed_link(
links: &[u8],
bits_per_unsorted: u8,
sorted_count: usize,
mut f: impl FnMut(u32),
) {                               
```
<td>
```rust
pub fn iterate_packed_links(
links: &[u8],
bits_per_unsorted: u8,
sorted_count: usize,
) -> PackedLinksIterator {        
```
</table>
A special care is taken to make the performance not worse by overriding the provided method `Iterator::fold()` instead of relying just on …

Turn for_each_packed_link into iterator

---

.github/workflows/coverage.yml

Coverage action didn't get scheduled or show up in https://github.com/qdrant/qdrant/actions because it's not part of master yet. I think triggering it once from dev branch should bring it there. Don't want to wait for next release

Temporarily run code coverage on merging to dev

---

.github/workflows/integration-tests.yml
.github/workflows/release-artifacts.yml
.github/workflows/rust-gpu.yml
.github/workflows/rust.yml

Without --locked, Cargo will:
1. Use the Cargo.lock file if it exists
2. Update the lock file if necessary to resolve dependencies
3. Create a new lock file if one doesn't exist
With --locked, Cargo will:
1. Use the exact versions specified in the existing Cargo.lock file
2. Fail if the lock file is missing
3. Fail if any changes to the lock file are required
The main difference is that --locked prevents any modifications to the lock file, ensuring deterministic builds, which is particularly useful in CI environments.
Without --locked, Cargo may update the lock file if needed, but it will still use the lock file as a starting point for dependency resolution.

Use cargo --locked on CI for reproducible builds

---

lib/segment/src/fixtures/index_fixtures.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs

This fixes a bug that happened when updating a mmap sparse vector storage is cancelled. 
An invariant was broken when handling the `stopped` flag. All other implementations stop midway and return `OperationError::Cancelled`, but this implementation just stopped iterating, and returned a partial updated range. 
This caused the range check to fail, don't handle cancellation nicely, and send a service error back all the way to the user.

[mmap sparse vector storage] return cancelled error if stopped

---

config/config.yaml

Fixes <https://github.com/qdrant/landing_page/pull/1448>
Add docs for <https://github.com/qdrant/qdrant/pull/5602>
Add the logging format property to the configuration file by default.

Add default log format properties to configuration file

---

config/config.yaml
src/settings.rs

Depends on <https://github.com/qdrant/qdrant/pull/5905>
Enable compaction of consensus operations by default. This imposes two key benefits:
- joining peers don't have to replay a huge amount of operations and can get up to speed quickly through a consensus snapshot
- more robust consensus because consensus snapshots provides a fixed state as new starting point
We should confirm if <https://github.com/qdrant/qdrant/pull/5900> fixes the current ongoing consensus problems in chaos testing before merging this PR.
I used 128 instead of 100 because it is a nice round number :smiley: …

Enable consensus compaction by default

---

src/actix/mod.rs
tests/basic_api_test.sh

This PR adds an actix middleware that remove double slashes from API requests.
This should fix #5826 and also as an addition, help avoid path traversal attacks

Add NormalizePath middleware to cleanup url

---

lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/collection_manager/segments_updater.rs
lib/collection/src/collection_manager/tests/mod.rs

Fix a critical problem which could result in us reviving (partial) already deleted points.
A point may exist in multiple segments, having multiple versions. This is normal behavior and can happen due to a myriad of reasons.
Normally, point operations are only [applied](https://github.com/qdrant/qdrant/blob/997ef849ae983282e7bbf804c8aba702c47da6bb/lib/collection/src/collection_manager/holders/segment_holder.rs#L487-L511) to the latest point version. This is done on [purpose](https://github.com/qdrant/qdrant/blob/997ef849ae983282e7bbf804c8aba702c47da6bb/lib/collection/src/collection_manager/holders/segment_holder.rs#L464-L466), so that any copy-on-write operation always uses the latest point data as source.
The problem is in deleting points though. If we only delete the latest point …

Apply point deletions to all point versions

---

lib/collection/src/operations/types.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/replica_set/mod.rs
lib/common/common/src/rate_limiting.rs
lib/storage/src/content_manager/errors.rs
src/actix/helpers.rs
tests/consensus_tests/test_shard_transfer_rate_limiting.py
tests/openapi/test_strictmode.py

The rate limiter now computes a `retry-after` field in its error to feed to the `Retry-After` HTTP header.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

Retry-After on rate limiter hit for REST API

---

lib/segment/src/common/rocksdb_buffered_update_wrapper.rs

The two mutexes are always acquired together so they can be merged.

Optimize RocksDB buffered wrapper with single Mutex

---

lib/segment/src/entry/entry_point.rs
lib/segment/src/fixtures/payload_context_fixture.rs
lib/segment/src/id_tracker/id_tracker_base.rs

Our ID tracker fixture used in tests does not match the point delete behavior of our regular ID trackers.
All our real ID trackers internally use the same point mappings object. This point mapping structure ignores deleted points by [explicitly](https://github.com/qdrant/qdrant/blob/9d56dcfa7a87863a2f2fc511a847bd0f06a2c09e/lib/segment/src/id_tracker/point_mappings.rs#L71) checking for deletion, or by [dropping](https://github.com/qdrant/qdrant/blob/9d56dcfa7a87863a2f2fc511a847bd0f06a2c09e/lib/segment/src/id_tracker/point_mappings.rs#L80-L93) a mapping on point delete. All [getters](https://github.com/qdrant/qdrant/blob/9d56dcfa7a87863a2f2fc511a847bd0f06a2c09e/lib/segment/src/id_tracker/simple_id_tracker.rs#L257-L263) [rely](https://github.com/qdrant/qdrant/blob/9d56dcfa7a87863a2f2fc511a847 …

In ID tracker fixture, exclude deleted points

---

src/actix/api/update_api.rs
src/tonic/api/points_internal_api.rs

Some trivial tweaks to update API to slash a few lines of boilerplate:
- simplify `wait` and `ordering` query parameters deserialization in REST API
- this does not affect OpenAPI spec, because these parameters are *explicitly* described there
- use `common::inference::extract_token` in internal gRPC API
- (as far as I can tell, it's *exactly* the same, as a copy-pasted snippet that was used in internal gRPC API before)
- destructure `UpdateVectorsInternal`/`DeleteVectorsInternal` requests instead of accessing fields individually
- add generic `extract_internal_request` helper …

Tiny refactoring to reduce some boilerplate in update API

---

lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/collection_manager/segments_updater.rs
lib/collection/src/collection_manager/tests/mod.rs
lib/segment/src/segment/segment_ops.rs

Continuation after <https://github.com/qdrant/qdrant/pull/5956> as suggested by <https://github.com/qdrant/qdrant/pull/5956#issuecomment-2645360891>.
An initial implementation for always deleting older point versions when an operation is applied. It cleans up duplicate points and prevents users retrieving old point data.
This is a first iteration, and I'm not super happy with the implementation yet. However, it is good enough to be included in a patch release.
This PR has the following properties:
- does not delete other point instances having the same version
- deletes old points with their existing version
In a future PR I'd like to change these properties to:
- do delete other point instances having the same version, keeping just one instance
- delete old point versions with the …

Always delete old point versions when applying point operation

---

src/consensus.rs

I do not understand why the current code has never failed on large RaftMessages.
```rust
/// Encodes the message to a buffer.
///
/// An error will be returned if the buffer does not have sufficient capacity.
fn encode<B>(&self, buf: &mut B) -> Result<(), EncodeError>
where
B: BufMut,
Self: Sized,
{
let required = self.encoded_len();
let remaining = buf.remaining_mut();
if required > buf.remaining_mut() {
return Err(EncodeError::new(required, remaining));
}
self.encode_raw(buf);
Ok(())
}
/// Encodes the message to a newly allocated buffer.
fn encode_to_vec(&self) -> Vec<u8>
where
Self: Sized,
{
let mut buf = Vec::with_capacity(self.encoded_len());
self.encode_raw(&mut buf);
buf
}
```

Properly size Raft message buffer

---

src/actix/api/update_api.rs
src/common/update.rs
src/tonic/api/update_common.rs

Similar to #5968, but for `UpdateParams`. Moves `UpdateParams` to `common::update` and use it to easier propagate `wait` and `ordering` parameters around.

Move `UpdateParams` structure to `common::update` module

---

.github/workflows/coverage.yml

This reverts <https://github.com/qdrant/qdrant/pull/5911> because coverage tests now run on a schedule: https://github.com/qdrant/qdrant/actions/workflows/coverage.yml

Revert coverage test when merging into dev

---

lib/sparse/src/index/inverted_index/inverted_index_ram_builder.rs

Sparse vectors was causing OOM on chaos testing and it was not clear what's happening because of not having relevant logs. 
I propose to log it on a debug level similar to how we log `building HNSW for 11806 vectors with 1 CPUs`

Sparse vectors log

---

lib/collection/src/shards/replica_set/update.rs
tests/consensus_tests/test_shard_stream_transfer.py

A replica that is receiving a shard transfer, might not have all points yet. A replica could have missed a bunch of insertions, which might be the reason why the shard transfer is ongoing - to recover the replica.
Our replica deactivation logic was a bit to eager, immediately marking a replica as dead if a point is not found.
Marking as dead cascades into other problems. If we mark the target shard of a transfer as dead, the transfer is immediately aborted. If we have a continuous stream of operations modifying points that aren't there yet, the transfer will never progress because it constantly gets aborted. It is exactly the scenario we've been seeing in a real cluster.
This PR relaxes the condition. It accepts a missing point error while the replica is undergoing recovery. We should …

Do not deactivate partial/recovery replica on missing point

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Release PR for Qdrant 1.13.3.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5970>.

Bump version to 1.13.4

---

lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/segment/src/data_types/mod.rs
lib/segment/src/data_types/segment_manifest.rs
lib/segment/src/entry/entry_point.rs
lib/segment/src/entry/mod.rs
lib/segment/src/entry/partial_snapshot_entry.rs
lib/segment/src/id_tracker/id_tracker_base.rs
lib/segment/src/index/payload_index_base.rs
lib/segment/src/index/vector_index_base.rs
lib/segment/src/payload_storage/payload_storage_base.rs
lib/segment/src/segment/entry.rs
lib/segment/src/segment/mod.rs
lib/segment/src/segment/partial_snapshot.rs
lib/segment/src/segment/partial_snapshots.rs
lib/segment/src/segment/snapshot.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs
lib/segment/src/vector_storage/vector_storage_base.rs

This PR prototypes `Segment::take_partial_snapshot` implementation and `SegmentManifest` (structure that is used to calculate which files to include into partial snapshot) format.

Prototype partial segment snapshots and `SegmentManifest` format

---

.github/codecov.yml

Avoid marking branch as failures if coverage is above 50%. Current is `55.26%` (only with unit tests)
Have triggered a run to see results: https://github.com/qdrant/qdrant/actions/runs/13386901276/job/37385582869

Add codecov threshold

---

config/development.yaml
src/actix/certificate_helpers.rs
src/common/helpers.rs
src/common/http_client.rs
src/settings.rs

I have a single node hybrid cloud cluster. I configured TLS directly in the DB (no P2P TLS) which sets this:
```
service:
enable_tls: true
tls:
cert: ./tls/cert.pem
key: ./tls/key.pem
```  
This works correctly when connecting to Qdrant.
But when I try to load a snapshots from a remote HTTP location:
```
PUT /collections/midjourney/snapshots/recover
{
"location": "http://snapshots.qdrant.io/midlib.snapshot"
}
```
I get the following error returned from Qdrant
```
{
"error": "Service internal error: failed to initialize HTTP(S) client: failed to read HTTPS client CA certificate file ./tls/cacert.pem: No such file or directory (os error 2)"
}
```
Why is a ./tls/cacert.pem mandatory for this operation?
---
Resolution:
Indeed, `./tls/cacert.pem` is not required. Not our config file can accept …

Ca cert for snapshots

---

tests/consensus_tests/test_consensus_compaction.py

Add naive consensus compaction test.
Additionally, this asserts cluster metadata is properly compacted/snapshotted as implemented in <https://github.com/qdrant/qdrant/pull/6014>.
It succeeds now, and does indeed fail before metadata was properly compacted (<https://github.com/qdrant/qdrant/pull/6014>).

Add a basic consensus compaction test, also assert cluster metadata

---

lib/api/src/grpc/conversions.rs
lib/storage/src/content_manager/conversions.rs

We mixed up read/write rate limit values in two places.

Fix mix ups in read/write rate limit settings

---

src/consensus.rs

Improves logging a bit by logging the consensus snapshot metadata. Note that this shouldn't be confused with cluster metadata. 
This looks like this and tells us about the commit/term and votes/learners at which consensus snapshot was created:
```
2025-02-20T09:46:02.606475Z DEBUG qdrant::consensus: Applying snapshot SnapshotMetadata { conf_state: Some(ConfState { voters: [7781753388964844], learners: [1922819182303582], voters_outgoing: [], learners_next: [], auto_leave: false }), index: 15, term: 1 }) }
```

Log consensus snapshot metadata when applying

---

lib/segment/src/id_tracker/compressed/versions_store.rs

This was newly introduced in <https://github.com/qdrant/qdrant/pull/6022> after <https://github.com/qdrant/qdrant/pull/6011> was already merged.
Fixes CI job:
- https://github.com/qdrant/qdrant/actions/runs/13441529560/job/37556915657

Resolve clippy warnings for Rust 1.85 on dev

---

lib/segment/src/id_tracker/compressed/versions_store.rs
lib/segment/src/id_tracker/immutable_id_tracker.rs

In the new compressed version store (<https://github.com/qdrant/qdrant/pull/6022>), use a `u32` based index instead of `usize`.
There are two reasons for this:
- the structure does not support higher indices, so lets prevent misuse by the type system
- the point offset we usually pass to it is `u32` already
Based on [this](https://github.com/qdrant/qdrant/pull/6022#discussion_r1963230617) comment.

Use u32 index in compressed version store, doesn't support bigger values

---

lib/api/src/rest/schema.rs
lib/collection/src/operations/universal_query/collection_query.rs
lib/collection/src/operations/universal_query/formula.rs
lib/collection/src/operations/universal_query/mod.rs
lib/collection/src/operations/universal_query/shard_query.rs
lib/segment/src/index/query_optimization/rescore_formula/formula_scorer.rs
lib/segment/src/index/query_optimization/rescore_formula/parsed_formula.rs

Builds on top of #5980 
I know, lots line changes, but it is usual with all the conversions between query structures.
This PR introduces:
- REST and internal converging types (e.g. `FormulaInternal`)
- conversions for `rest -> internal -> parsed`

[score boosting] create query structures and parse them

---

lib/segment/src/id_tracker/compressed/compressed_point_mappings.rs
lib/segment/src/id_tracker/point_mappings.rs
lib/segment/src/index/field_index/facet_index.rs
lib/segment/src/index/field_index/map_index/mmap_map_index.rs
lib/segment/src/segment/facet.rs
lib/segment/tests/integration/payload_index_test.rs

This flaky test didn't get enough love for a looong time, sorry. 
There was a bug hidden in the map mmap index, which didn't consider the deleted bitslice when iterating over the point offsets of each value.
This fixes it and improves the tests.

Fix flaky `test_keyword_facet` test

---

docs/redoc/master/openapi.json
lib/api/src/rest/schema.rs
lib/api/src/rest/validate.rs
lib/collection/src/operations/universal_query/collection_query.rs
lib/collection/src/operations/universal_query/formula.rs
lib/collection/src/operations/universal_query/planned_query.rs
lib/collection/src/operations/universal_query/shard_query.rs
lib/collection/src/shards/local_shard/formula_rescore.rs
lib/collection/src/shards/local_shard/query.rs
lib/segment/src/data_types/query_context.rs
src/common/inference/batch_processing.rs
src/common/inference/query_requests_rest.rs

Connects the score boosting structures to Query API.
It denies to use this method for base queries (leaf prefetches), and includes validation for defaults.

[score boosting] Connect formula to query

---

lib/segment/src/index/hnsw_index/gpu/shaders/links.comp
lib/segment/src/index/hnsw_index/gpu/shaders/run_greedy_search.comp
lib/segment/src/index/hnsw_index/gpu/shaders/run_insert_vector.comp
lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_candidates_heap.comp
lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_heuristic.comp
lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_hnsw_search.comp
lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_nearest_heap.comp
lib/segment/src/index/hnsw_index/gpu/shaders/tests/test_vector_storage.comp
lib/segment/src/index/hnsw_index/gpu/shaders/visited_flags.comp

This fixes #5834 for NVIDIA cards.
The steps from #5834 works, but the following command catches the issue faster:
```shell
bfb -n 2000000 -d 4 --max-segment-size 200000 --indexing-threshold 1 --hnsw-m 4 --hnsw-ef-construct 8
```
Qdrant output:
```
WARN segment::index::hnsw_index::gpu::gpu_links: Incorrect links on level 2 were found. Amount of incorrect links: 1, zeroes: 1    
WARN segment::index::hnsw_index::gpu::gpu_links: Incorrect links on level 3 were found. Amount of incorrect links: 1, zeroes: 1    
WARN segment::index::hnsw_index::gpu::gpu_links: Incorrect links on level 3 were found. Amount of incorrect links: 1, zeroes: 1    
WARN segment::index::hnsw_index::gpu::gpu_links: Incorrect links on level 1 were found. Amount of incorrect links: 1, zeroes: 1  
```
Code in question: …

gpu: add coherent qualifier

---

Cargo.lock
Cargo.toml
lib/common/common/src/types.rs
lib/common/memory/src/mmap_ops.rs
lib/gpu/Cargo.toml
lib/gpu/src/basic_test.rs
lib/gpu/src/buffer.rs
lib/segment/Cargo.toml
lib/segment/src/data_types/primitive.rs
lib/segment/src/index/hnsw_index/gpu/gpu_heap_tests.rs
lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
lib/segment/src/index/hnsw_index/gpu/gpu_links.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/gpu_multivectors.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/gpu_quantization.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
lib/segment/src/index/hnsw_index/gpu/gpu_visited_flags.rs

In this PR transmutes in the GPU-related code are replaced with the usage of `zerocopy`. See https://github.com/qdrant/qdrant/pull/5297/files/be387be795977cfe99fabe77694ba31c66226f32#r1836929158.
Note: `half::f16` is not compatible with the latest version of `zerocopy`, so `bytemuck` is used to convert it to `&[u8]`.
Also, since every usage of `download_slice()` was used to write into a newly allocated vector, I've introduced `download_vec()` to make usage a bit more convenient.

gpu: zerocopy instead of transmute

---

lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/segment/src/data_types/segment_manifest.rs
lib/segment/src/entry/partial_snapshot_entry.rs
lib/segment/src/segment/partial_snapshot.rs

Based on #5928. Changes `SegmentEntry::take_partial_snapshot` (and related methods) signature and implementation a bit, to support `ProxySegment`s.

Extend partial segment snapshot to support `ProxySegment`s

---

Cargo.lock
lib/segment/Cargo.toml
lib/segment/tests/integration/payload_index_test.rs

This improves the execution speed of the module from around 20 secs down to 7.5 secs, at least with nextest. Command:
```shell
cargo nextest run  -p segment --test integration payload_index_test
```
- Refactors to run all tests within a single one to reuse the fixture
- Each test returns an `anyhow::Result` with an error stating the place of error, as what `assert!()` would do
- Runs the tests in parallel
- Reduces the amount of attempts for each test. And makes each attempt different in the case of geo filters (we were repeating the same request for 100 times 😱)

Reuse fixture in payload index test

---

lib/collection/src/collection/snapshots.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/mod.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/shard_holder/mod.rs
tests/consensus_tests/test_failed_snapshot_recovery.py
tests/consensus_tests/utils.py

Alternative to https://github.com/qdrant/qdrant/pull/6020
This PR makes sure that a failed snapshot restore does not prevent the service from restarting.
This is achieved by performing two things:
- keeping the shard's folder inner configuration in case of failed recovery, instead of deleting it completely
- making the restore process crash safe using a flag file
Not deleting the shard folder pleases the `ShardHolder`  which expects one folder per shard.
Without a WAL found for the shard, it is turned into a `DummyShard` at load time.
```
ERROR collection::shards::replica_set: Failed to load local shard "./storage/collections/test_collection/0", initializing "dummy" shard instead: Service internal error: Wal error: Can't init WAL: Os { code: 2, kind: NotFound, message: "No such file or …
```

Keep initial shard configuration on failed restore

---

lib/gpu/src/basic_test.rs
lib/gpu/src/context.rs
lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
lib/segment/src/index/hnsw_index/gpu/gpu_links.rs
lib/segment/src/index/hnsw_index/gpu/gpu_visited_flags.rs

This PR adds a vulkan memory barrier. Memory barrier is a sync primitive that adds guarantees about execution order. After this barrier, all changes must be available for downloading without race conditions or unflushed caches.

Gpu add memory barriers

---

tests/consensus_tests/test_failed_snapshot_recovery.py

On a fast execution, the `Partial` state can be observed.
```
local_shards = get_local_shards(peer_api_uris[-1])
assert len(local_shards) == 1
assert local_shards[0]["shard_id"] == 0
>       assert local_shards[0]["state"] == "Active"
E       AssertionError: assert 'Partial' == 'Active'
E         - Active
E         + Partial
tests/consensus_tests/test_failed_snapshot_recovery.py:192: AssertionError
```
The fix is to wait for the `Active` replica status before asserting,

Fix flaky test failed_snapshot_recovery

---

lib/api/src/grpc/conversions.rs

This PR migrates the file `grpc/conversions.rs` to deconstruct the input systematically.
This is desirable to make sure we will not forget new fields in the future like we did in the past :)
By doing so, I found a couple places where some fields were not used.
Future PRs will tackle the remaining grpc and rest conversion files.

Struct deconstruction in gRPC conversions

---

lib/api/src/grpc/conversions.rs
lib/api/src/grpc/mod.rs
lib/api/src/grpc/proto/points_internal_service.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/operations/universal_query/formula.rs
lib/collection/src/operations/universal_query/shard_query.rs
lib/segment/src/index/query_optimization/rescore_formula/parsed_formula.rs

Adds the formula query to the internal gRPC API, as well as the necessary conversions.
I decided to convert from `ParsedFormula` to `grpc::Formula` by "unparsing" the structure, rather than adding a parsed equivalent in the internal interface surface to avoid leaking the parsing implementation.

[score boosting] Add formula to internal gRPC API

---

lib/collection/src/shards/transfer/resharding_stream_records.rs
lib/collection/src/shards/transfer/stream_records.rs
lib/collection/src/shards/transfer/transfer_tasks_pool.rs

The exact count at the start of stream records transfers may be expensive, and can time out.
As a side effect our transfer ETA estimation might be a bit off. But that's totally worth it versus potentially timing out instead.

Don't do exact point count at start of shard transfers

---

lib/collection/src/shards/local_shard/mod.rs

Simple extension to <https://github.com/qdrant/qdrant/pull/6032>.
Also ignore hidden segments when recovering them from a shard snapshot.
This is not strictly necessary. But I felt it's nice to keep both (loading segments, and recovering segments) in sync.

Ignore hidden files while restoring shard segments from snapshot

---

lib/collection/src/operations/types.rs
lib/common/common/src/rate_limiting.rs
lib/storage/src/content_manager/conversions.rs
tests/consensus_tests/test_strict_mode.py
tests/consensus_tests/utils.py

Follow up to https://github.com/qdrant/qdrant/pull/5917 for the gRPC API.
The `retry-after` header is passed using the standard gRPC [metadata structure](https://grpc.io/docs/guides/metadata/).
The value can easily be extracted my clients. (e.g. Rust [client](https://github.com/qdrant/rust-client/pull/212))
This PR makes sure that the `retry-after` header is properly propagated during inter node communication.
There is a test to validate the end to end error propagation when querying an empty node.

Add retry-after header for gRPC

---

lib/collection/src/collection/clean.rs
lib/collection/src/shards/shard_holder/resharding.rs

Optimize the background task that takes care of cleaning up shards, specifically deleting points from it that don't belong in it anymore.
This change makes the cleanup process a lot faster, which means it'll complete in less wall clock time.
The primary change is about how we select what points to delete. Before, we used a hash ring filter during the scroll request to only scroll points that don't belong into the shard anymore. Now, we simply scroll all point IDs and filter  the list after the scroll request. The key thing here is that the hash ring check is very expensive. Before, the hash ring check was done a lot more often across all segments in the shard. Now we only check each point ID once.
To summarize, this PR does two things:
1. move hash ring check outside of scroll operation …

Optimize cleanup of shards, used in resharding

---

src/main.rs

The function `remove_started_file_indicator` outputs a WARN log when it cannot delete the start init flag.
However this log would never be visible because the function is called before the logging infrastructure is set up.

Fix logging for remove_started_file_indicator

---

lib/collection/src/hash_ring.rs
lib/collection/src/shards/forward_proxy_shard.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/replica_set/shard_transfer.rs
lib/collection/src/shards/transfer/resharding_stream_records.rs
lib/collection/src/shards/transfer/stream_records.rs
lib/collection/src/shards/transfer/transfer_tasks_pool.rs

Extension of <https://github.com/qdrant/qdrant/pull/6074>
Improve tracking of records to transfer in shard transfers, specifically for stream records and resharding stream records transfer.
The main two improvements are:
- count records actually being transferred, not batch size
- in case of resharding, estimate number of records to transfer based on resharding fraction
For example, if we're resharding from one to two shards, a resharding transfer will only transfer ~50% of the records, not all of them.
The current resharding implementation still filters points with the hash ring after scrolling, not during scrolling itself. Using the hash ring filter during scrolling itself is very expensive and makes the transfer **significantly** slower, bumping transfer time from 28 to 500 seconds. …

Improve shard transfer tracker, show fraction in case of resharding

---

lib/collection/src/operations/universal_query/formula.rs
lib/segment/src/index/query_optimization/rescore_formula/value_retriever.rs
lib/segment/src/json_path/mod.rs

Tests were set up to assert this behavior, but an off-by-one error wasn't running this specific case 🤦‍♂️
This PR fixes it by checking if the payload key has a wildcard index `[]`. If it doesn't and it is an array, it reads the first element.

[score boosting] extract first element of arrays

---

lib/api/src/grpc/conversions.rs
lib/collection/src/operations/types.rs
lib/segment/src/common/operation_error.rs
lib/segment/src/index/query_optimization/rescore_formula/formula_scorer.rs
lib/segment/src/index/query_optimization/rescore_formula/parsed_formula.rs

We decided to only handle finite numbers in the formula evaluation. 
With these changes, we now return a new bad request error when the evaluation leads to infinite or NaN.
Test cases were added to assert the errors

[score boosting] Only accept finite numbers

---

lib/segment/src/types.rs

Simplify hashing implementation for `StrictModeConfig` so we do not need to create synthetic tuples to bypass the compiler limitation.

Simplify StrictModeConfig hashing

---

lib/collection/src/operations/config_diff.rs

Seems like an oversight from the recent migration to struct deconstruction.

Use Struct deconstruction in config diffs

---

lib/api/src/rest/models.rs
lib/collection/src/collection_manager/optimizers/mod.rs
lib/collection/src/operations/types.rs
lib/collection/src/shards/telemetry.rs
lib/collection/src/telemetry.rs
lib/segment/src/common/operation_time_statistics.rs
lib/segment/src/types.rs
lib/storage/src/types.rs
src/common/telemetry_ops/cluster_telemetry.rs
src/common/telemetry_ops/collections_telemetry.rs
src/common/telemetry_ops/hardware.rs

I've audited all `Anonymize` implementations and added a few missing anonymizations:
- Vector names inside `CollectionConfigInternal::{params, strict_mode_config}`.
- String shard keys.
Also, in this PR, I've added a few no-op `Anonymize` implementations. The reasoning is explained below.
In our codebase, we just call `.clone()` for structures that do not require anonymization, like this:
```rust
struct Foo {
some_structure: SomeStructure,
…
}
impl Anonymize for Foo {
fn anonymize(&self) -> Self {
Self {
some_structure: self.some_structure.clone(), // !
…
}
}
}
```
However, even if we don't need to anonymize the contents of `SomeStructure` right now, it is possible that we could add some sensitive field in the future. Such additions could be slip by unnoticed during code review.
A better …

Anonymize ShardKey in ReplicaSetTelemetry

---

lib/segment/src/index/query_optimization/rescore_formula/formula_scorer.rs

small fix for the way the division default is used.
`by_zero_default` is the default result, not denominator

[score boosting] fix `by_zero_default` evaluation

---

lib/common/common/src/iterator_ext/mod.rs
lib/common/common/src/iterator_ext/on_final_count.rs

This PR adds an iterator adapter to make hardware usage counting easier when we are measuring iterators.
This adapter plugs in easily to an iterator. When the iterator gets dropped, it will execute the callback to do something with the final number of iterations the iterator was used for.
For example:
```rust
index.value_to_points.get_iter(value).on_final_count(|nexts| {
hw_counter
.payload_index_io_read_counter()
.incr_delta(nexts * size_of::<PointOffsetType>)
});
```
I am not sure about the name, though. Feel free to propose another one :)

`OnFinalCount` iterator adapter

---

docs/redoc/master/openapi.json
lib/api/src/grpc/conversions.rs
lib/collection/src/collection/mod.rs
lib/collection/src/config.rs
lib/collection/src/operations/conversions.rs
lib/collection/src/operations/types.rs
lib/collection/src/telemetry.rs
lib/segment/src/types.rs

Separate the whole struct tree of `StrictModeConfig` used in the `CollectionInfo` in order to enable the Python REST client to to tag those types as accepting extra keys during deserialization.
This is required to keep the [backward compatibility](https://github.com/qdrant/qdrant-client/issues/906) between the Python client 1.13.2 and the upcoming 1.14.0 version.
We have used a similar pattern in the past for `OptimizerConfig` and `OptimizerConfigDiff` for the same issue.
As a final test I validated that the new output classes are tagged properly in the [client generation](https://github.com/qdrant/qdrant-client/pull/916)

Separate StrictModeConfig output structure

---

lib/collection/src/collection/clean.rs
lib/collection/src/shards/forward_proxy_shard.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/local_shard/shard_ops.rs
lib/common/common/src/counter/hardware_accumulator.rs
tests/consensus_tests/test_shard_transfer_rate_limiting.py
tests/consensus_tests/utils.py

Do not apply read rate limit to scroll operation issued for shard transfers.
The fix relies on leveraging the work done by tagging internal operations with disposable hardware measurements.
Now all operations with disposable hardware measurements by-pass the read rate limiter.

Do not rate limit scroll operations for shard transfers

---

Cargo.lock

Replacing https://github.com/qdrant/qdrant/pull/6122 for `dev`

Bump Ring 0.17.13

---

lib/collection/src/collection/clean.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs

This PR removes the check for write rate limits when cleaning up a shard after resharding.
It relies on detecting a disposable hardware counter like in https://github.com/qdrant/qdrant/pull/6118

Do not rate limit resharding shard cleaning

---

Cargo.toml
lib/common/io/Cargo.toml
lib/segment/Cargo.toml
lib/sparse/Cargo.toml

The crate bincode 2.0 seems slower in the benchmark in https://github.com/qdrant/qdrant/pull/6134
This PR promotes the version at the workspace level and add a comment explaining why we do not upgrade.

Move Bincode to workspace and comment version lock

---

lib/segment/src/id_tracker/immutable_id_tracker.rs

The immutable ID tracker congruence test had two assertions comparing the same value.

Fix incorrect assertions in immutable ID tracker test

---

lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs

There are two reasons for unifying the implementation:
- the function with eager cost evaluation is never used directly
- the lazy function duplicates the guarding logic

Write rate limit cost always lazy

---

Cargo.lock
lib/common/common/Cargo.toml
lib/common/common/src/ext.rs
lib/segment/src/common/mmap_bitslice_buffered_update_wrapper.rs
lib/segment/src/id_tracker/id_tracker_base.rs
lib/segment/src/id_tracker/immutable_id_tracker.rs
lib/segment/src/index/field_index/bool_index/simple_bool_index.rs
lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/segment/formula_rescore.rs
lib/segment/src/vector_storage/async_raw_scorer.rs
lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/raw_scorer.rs
lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs

The `BitSlice::get()` method returns [`BitRef`] which requires additional gymnastics to convert it to `bool` to the point that `rustfmt` splits such long method call chains into multiple lines.
This PR adds `BitSliceExt::get_bit()`, making code working with it less bulky.
[`BitRef`]: https://docs.rs/bitvec/1.0.1/bitvec/ptr/struct.BitRef.html
The following queries were used to find usages to replace:
```shell
ast-grep -p '$_.get($_).as_deref().copied()'
ast-grep -p '$_.get($_).map(|$_| *$_)'
```

Add BitSliceExt::get_bit

---

Cargo.lock
Cargo.toml

The update contains an alleged performance improvements which I want to bench.
https://github.com/reem/rust-ordered-float/releases/tag/v5.0.0
There is a slight improvement in indexing time.
| Name                  | ghcr/dev       | ghcr/ordered-float-5       | Result     |
| --------------------- | ------------ | ------------ | ------------ |
| collection_load_time  | NULL | NULL | equal |
| rps                   | 235.57610090310894 | 233.89456816516474 | ghcr/dev > ghcr/ordered-float-5 by 1.68153273794420 (.71379597993932520800% greater) |
| mean_precisions       | 0.9648040000000001 | 0.9646520000000001 | ghcr/dev > ghcr/ordered-float-5 by .0001520000000000 (.01575449521353559700% greater) |
| p95_time              | 0.03742185626178975 | 0.03694567233324047 | ghcr/dev > …

Bump ordered-float 5.0

---

lib/segment/src/id_tracker/mod.rs
lib/segment/src/id_tracker/mutable_id_tracker.rs

Add initial implementation of mutable ID tracker. It's in-memory and persisted on disk. The key selling point is that it does not rely on RocksDB, but on simple files.
The idea is simple: the ID tracker holds a list of mappings and a list of point versions. All changes are simply appended to a file on disk. When loading from disk we scroll through the whole file and deduplicate in memory so that only the last mappings are kept.
Obviously, this structure can grow forever if we're not careful. That's why it relies on Qdrant's optimizers. Once the ID tracker collects too many changes, the optimizer will pick it up and create a new ID tracker. The new ID tracker will start from scratch, dropping all the garbage we had collected along …

Mutable in-memory ID tracker without RocksDB

---

src/main.rs

Follows our convention to log optional services being enabled at startup to help debugging.

Log hardware reporting enabled at startup

---

lib/segment/src/id_tracker/compressed/compressed_point_mappings.rs
lib/segment/src/id_tracker/immutable_id_tracker.rs
lib/segment/src/id_tracker/mutable_id_tracker.rs
lib/segment/src/id_tracker/point_mappings.rs

Depends on: <https://github.com/qdrant/qdrant/pull/6150>
Add mutable ID tracker tests, ported from [immutable ID tracker](https://github.com/qdrant/qdrant/blob/6a52a8728d9e778c2ba4737368b83ae2c5646ee0/lib/segment/src/id_tracker/immutable_id_tracker.rs#L512).

Add mutable ID tracker tests

---

lib/collection/src/collection_manager/holders/proxy_segment.rs
lib/collection/src/collection_manager/segments_searcher.rs
lib/segment/src/entry/entry_point.rs
lib/segment/src/segment/entry.rs
lib/segment/src/segment/formula_rescore.rs

The signature for `rescore_with_formula` included a deleted bitslice only because the proxy segment would introduce it to handle the write and wrapped results. 
In this PR, we remove the abstraction leak, and handle the logic to prefer write results only within the proxy segment.

[score boosting] fix proxy segment leakage

---

lib/segment/src/id_tracker/mutable_id_tracker.rs

Depends on: <https://github.com/qdrant/qdrant/pull/6166>
Implement the new storage for point versions.
This changes the mapping of versions from external ID to version to internal ID to version.
Points are kept in memory for fast access. On load we read the full list of versions. On flush we store we write all changed versions directly to the versions file.
Writing changes is optimized to properly buffer all writes. This has a great effect if writing a big batch of versions, to use a lot less intermediate syscalls.
In terms of the file format, the file on disk is just a contiguous list of version numbers similar to an array.
2. [x] Have you formatted your code locally using `cargo +nightly …

Mutable ID tracker: implement storage for point versions

---

lib/segment/src/common/operation_error.rs
lib/segment/src/index/query_optimization/rescore_formula/formula_scorer.rs
tests/openapi/test_query_formula.py

Changes the behavior to not use a silent 0.0 if the payload nor the defaults have a valid type.
This will error if the payload is not an expected value, even if the defined default is.

[score boosting] Error on unexpected type

---

lib/collection/src/shards/shard_holder/shard_mapping.rs
lib/common/common/src/flags.rs
src/main.rs

Two minor suggestions for global feature flags in #6194:
- Private static Flags to have better control of initialization
- Public function for accessing global flags with fallback to default values to prevent unwrapping everywhere
This is just a suggestion and I'm happy to discuss or discard if not needed!

Suggestions for global feature flags

---

lib/segment/src/id_tracker/mutable_id_tracker.rs

Depends on: <https://github.com/qdrant/qdrant/pull/6169>
If the last entry in the mappings file is partial, truncate the file.
It can happen if we crash during flush. We must truncate the file so that newly appended mappings don't get corrupted.
I don't particularly like the implementation, but the tools here are a bit limited. An alternative approach would require to load the full file in memory, or it would require to read over the file twice, which is why I implemented the current approach instead.

Mutable ID tracker: truncate mappings file if last entry is partial

---

config/development.yaml
lib/collection/src/shards/shard_holder/shard_mapping.rs
lib/common/common/src/flags.rs
lib/common/common/src/lib.rs
src/main.rs
src/settings.rs

First iteration of a structure for configuring feature flags.
This allows us to explicitly set some flags during testing to enable new and upcoming features. It helps us test the features before releasing them, without having to change source code. I'd like to unify the interface for this. It's intentionally kept very simple.
For now this includes just one flag. I'd like to add a flag for using the [new immutable ID tracker](https://github.com/qdrant/qdrant/pull/6174) once merged.
In debug builds, all flags are enabled by default (as per `config/development.yaml`). In chaos testing we'll probably enable all features by setting the appropriate environment variables.
I chose to use this global structure because it turns out to be extremely cumbersome to propagate the flags to all places we …

Add global feature flags

---

config/development.yaml
lib/common/common/src/flags.rs
lib/segment/src/id_tracker/id_tracker_base.rs
lib/segment/src/id_tracker/mutable_id_tracker.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs

Depends on: <https://github.com/qdrant/qdrant/pull/6173>
Add support for the new mutable ID tracker.
It is currently locked behind a feature flag, only enabled in development builds. In the next Qdrant release the new tracker will enabled globally.
- Feature flag disabled _(default in production build)_
RocksDB based tracker is used by default, unless new mappings are stored on disk
- Feature flag enabled _(default in development build)_
New tracker is used by default, unless there are RocksDB mappings on disk
Set `QDRANT__FEATURE_FLAGS__USE_MUTABLE_ID_TRACKER_WITHOUT_ROCKSDB=true` to prematurely enable the new ID tracker.
2. [x] Have you formatted your code locally using `cargo +nightly fmt …

Mutable ID tracker integration

---

config/development.yaml
lib/collection/src/collection/snapshots.rs
lib/collection/src/shards/shard_holder/shard_mapping.rs

Fix snapshot restore with new shard key format introduced in <https://github.com/qdrant/qdrant/pull/5838>.
The new shard key storage format is now enabled by default in development builds through a feature flag.

Fix snapshot restore with new shard key format

---

lib/segment/src/id_tracker/mutable_id_tracker.rs

Tracked in: #6157
Show a warning if the number of internal point mappings does not match with the number of versions. Their counts should normally be equal.
If a crash happens during flush, new versions may only be partially written or not at all. In such case we can expect the list of versions to be shorter.
This shows a warning to make us aware of this having happened, potentially allowing is to debug better. Under normal circumstances, the WAL should always recover this situation.

Mutable ID tracker: show warning if mapping and versions count mismatch

---

lib/collection/src/collection/mod.rs
lib/collection/src/collection/state_management.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/shards/shard_holder/shard_mapping.rs
lib/collection/src/tests/points_dedup.rs
lib/collection/src/tests/snapshot_test.rs
lib/collection/tests/integration/common/mod.rs
lib/collection/tests/integration/snapshot_recovery_test.rs
lib/storage/src/content_manager/toc/collection_container.rs
lib/storage/src/content_manager/toc/create_collection.rs

Similar to <https://github.com/qdrant/qdrant/pull/6210>.
Shard key mappings were not applied properly in some places when using a consensus snapshot. This fixes the issue.
Some key places that were forgotten:
- we have two fields for shard key mappings, one being the inverse - we only updated one of those fields
- replica sets also have a shard key field, we did not set it at all
- shard key mappings are sometimes known during collection creation, set it right away
A proper test for this is implemented in <https://github.com/qdrant/qdrant/pull/6213>.

Fix consensus snapshot not applying shard key mappings

---

lib/collection/src/operations/cluster_ops.rs

In user-defined shard key creation we have a [field](https://api.qdrant.tech/api-reference/distributed/create-shard-key#request.body.shards_number) called `shards_number`. In [other](https://api.qdrant.tech/api-reference/collections/create-collection#request.body.shard_number) places this field is called `shard_number`.
This adds an alias to support both flavors in shard key creation, because I've been rather confused by this for a bit.

Alias shards_number to shard_number in shard key creation

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to 1.13.6-dev for the Qdrant 1.13.5 patch release.
Follows the pattern of https://github.com/qdrant/qdrant/pull/5996.

Bump dev version to 1.13.6-dev

---

src/actix/auth.rs
src/common/inference/mod.rs
src/tonic/auth.rs

Previously qdrant middleware converted JWT InferenceToken into `"None"`m which we overlooked

remove failty to_string conversion for InferenceToken

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

Release PR for Qdrant 1.13.5.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/5995>.

Bump version to 1.13.5

---

config/development.yaml
lib/common/common/src/flags.rs
src/main.rs

Extends <https://github.com/qdrant/qdrant/pull/6194>
This extends feature flags a bit, adding two useful improvements:
1. add magic `all` flag that enables everything
2. if any feature flags are set, log them on start
The `all` flag is especially useful on chaos testing to always enable the feature flags we set up. This prevents us from constantly having to bump environment variables for new flags we add. It also keeps our development configuration file a bit cleaner.
The log entry for enabled feature flags is rather basic and looks like this:
```log
2025-03-21T15:53:59.394753Z DEBUG qdrant: Feature flags: FeatureFlags { all: true, use_new_shard_key_mapping_format: true, use_mutable_id_tracker_without_rocksdb: true }
```
I've again tried to keep this as simple as possible.
1. [x] Does …

Add `all` feature flag, report enabled flags on start

---

lib/common/common/src/flags.rs

If you pass:
```yaml
feature_flags:
use_new_shard_key_mapping_format: true
use_mutable_id_tracker_without_rocksdb: true
payload_index_skip_rocksdb: true
```
Qdrant throws error because `all` field is not passed. 
```
Error: missing field `all` for key `feature_flags`
```
We should add a fallback for it (false) so other vars can be set independently. This was detected by chaos testing.

Add fallback for missing all feature_flag

---

Cargo.lock
lib/common/common/Cargo.toml
lib/common/common/src/flags.rs

This simple test ensures that <https://github.com/qdrant/qdrant/pull/6234> cannot happen again.

Add test to ensure we don't panic if flags are undefined

---

lib/collection/src/collection/snapshots.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/shard_holder/mod.rs

We introduced shard initailizing flag to clean dirty snapshots after a failed shard snapshot recovery (for example: files missing after move/rename step in shard snapshot recovery due to node crash)
However, there are 2 functions that call `ShardHolder::recover_local_shard_from()` and we were creating/deleting this flag in only one of them which led to panics in chaos testing. This PR makes Qdrant use the snapshot flag in both places by making it a part of `ShardHolder::recover_local_shard_from` so Qdrant cleans up the dirty shard on its own.
More context of this can be found in https://github.com/qdrant/qdrant/pull/6199#issuecomment-2743350845

Properly use shard snapshot initializing flag while recovering

---

tests/storage-compat/populate_db.py

Add more payload types to the storage compatibility generator:
- UUID
- datetime
- more variation with `on_disk`
I will regenerate the test snapshot in a next PR.

Add more payload types to storage compat. tests

---

tests/storage-compat/storage-compatibility.sh

I have generated the test data for `v1.13.5` based on the docker image released and uploaded the storage to our Google bucket.

Generate data for v1.13.5 in storage compat. tests

---

lib/collection/src/hash_ring.rs
lib/collection/src/shards/transfer/resharding_stream_records.rs

Fixes incorrect implementation in <https://github.com/qdrant/qdrant/pull/6084>.
The function to calculate the fraction of points transferred during a resharding transfer was incorrect. For resharding up it gave us the wrong result.
For resharding up, the returned fraction was for the total number of points in the collection, not a fraction for the number of points in the current shard like the function describes.
Long story short, this fixed the fraction calculation. The documentation with examples has been updated as well.
In practice this fixes our point count estimate in shard transfers. It's not critical, but helpful to do proper transfer estimations.
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to …

Fix incorrect resharding transfer fraction for points to transfer

---

lib/collection/src/collection/point_ops.rs
lib/collection/src/shards/local_shard/scroll.rs
lib/collection/src/shards/local_shard/shard_ops.rs
lib/collection/src/shards/remote_shard.rs
lib/collection/src/tests/points_dedup.rs
lib/collection/tests/integration/collection_test.rs
lib/segment/src/data_types/order_by.rs

Initially, we started inserting the order_by value in the payload. Since version 1.11 we can already deprecate this behavior because now we have a dedicated field in the point struct.
This PR removes the legacy code which inserted and removed the order_by value in the payload.

[order_by] Deprecate using `order_value` from payload, dedup by `(order_value, id)` tuple

---

.github/workflows/coverage.yml

Github schedules the coverage report cron via `master` branch. Although, we checkout the code of `dev` branch and push the coverage for `dev` branch, codecov action labels it as coming from the `master` branchi instead. This PR should fix the issue.

Coverage override branch

---

lib/segment/src/id_tracker/mutable_id_tracker.rs

An improvement to how we flush versions in the new mutable ID tracker.
With this PR we now check the required size for the versions file. If it isn't large enough to write new versions, we immediately grow it to allocate all required space with one syscall.
Previously, we just wrote new versions to the end of the file directly to automatically grow it. While that is fine, it can cause a lot of file re-allocations to progressively grow it in steps when writing new versions.
This now prevents that, and optimizes for that scenario.
In numbers, if we insert 10k new points, this reduces reallocating the file from 10 times to just once.
2. [x] Have you formatted your code locally using `cargo …

Mutable ID tracker: improve version flushing, grow file in one shot

---

lib/collection/src/collection/query.rs
lib/collection/src/collection/search.rs

Implements [this](https://github.com/qdrant/qdrant/blob/fbf1ce4d1725a9ef3de183be83eddafe6c03ac27/lib/collection/src/collection/search.rs#L62-L142) which we have in search, also for our query API.
If having a large number of shards or a large offset, prevent transferring a huge amount of payloads across the network within the cluster. Instead, defer reading vectors and payloads to a second step to greatly improve search performance.

Optimize vector/payload reads in large query batches, defer reads

---

lib/collection/src/operations/universal_query/planned_query.rs
lib/collection/src/shards/local_shard/formula_rescore.rs
lib/collection/src/shards/local_shard/query.rs
lib/segment/src/data_types/query_context.rs
lib/segment/src/segment/entry.rs

Changes the structure of the planned query to make sure we fetch payloads and vectors only at the last step before returning the results from a shard.
This improvement makes sure that the impact of fetching many large payloads is mitigated.
For instance, before this change, a single search of limit 100 in 500 segments would mean that 50,000 payloads would be fetched, while we only needed 100 of them

[query] Optimize fetching payloads/vectors at local shard

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Release PR or Qdrant 1.13.6.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/6223>.

Bump version to 1.13.6

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to 1.13.7-dev for the [Qdrant 1.13.6](https://github.com/qdrant/qdrant/pull/6277) patch release.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/6219>.

Bump dev version to 1.13.7-dev

---

lib/collection/src/collection/clean.rs
lib/collection/src/collection/snapshots.rs
lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/collection/src/grouping/aggregator.rs
lib/collection/src/operations/snapshot_storage_ops.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/transfer/mod.rs
lib/common/memory/src/mmap_type.rs
lib/gridstore/src/gridstore.rs
lib/segment/src/index/vector_index_base.rs
lib/segment/src/segment/segment_ops.rs
lib/storage/src/content_manager/consensus_manager.rs

Rust [1.86.0](https://releases.rs/docs/1.86.0/) will be out in two days (3 April, 2025).
There is nothing controversial in the fixes IMHO.

Fixes for Clippy 1.86

---

lib/collection/src/collection_manager/collection_updater.rs
lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/shards/local_shard/scroll.rs
lib/storage/src/content_manager/snapshots/recover.rs
lib/storage/src/content_manager/toc/mod.rs

This PR fixes rare but possible loss of points in scroll results:
due to 2-stage search+retrieve approach in scroll, we can't guarantee that points retrieved on the first stage will be available and/or unchanged on the second stage. This might create a problem of either returning changed payload, which doesn't satisfy filters anymore, or compromise number of returned points.
It is especially critical for scroll request, which relies on number of returned points to generate a "next_page" offset, and is used in internal operations like shard streaming.
What I have tried and didn't work:
- use segments lock and https://amanieu.github.io/parking_lot/parking_lot/struct.RwLock.html#method.read_recursive - didn't work because it would require to have sync locks which live between await blocks.
- …

Scroll lock: make sure no segments are modified between scroll and retrieve

---

lib/collection/src/shards/replica_set/snapshots.rs

Found this mistake while working on https://github.com/qdrant/qdrant/pull/6293. 
This `has_other_active_peers` needed a negation (`!`). So far, we kept the replica as `Active` despite loading as dummy shard and having other "real" replicas.

Mark dummy shard as dead after snapshot restore failure

---

lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/shards/dummy_shard.rs
lib/collection/src/shards/forward_proxy_shard.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/proxy_shard.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/shard.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/segment/src/data_types/segment_manifest.rs
lib/segment/src/segment/mod.rs
lib/segment/src/segment/segment_ops.rs
lib/segment/src/segment/snapshot.rs

This PR extends `ShardReplicaSet::restore_local_replica_from` to support *partial* snapshot recovery.
APIs to create and recover partial snapshots and integration tests will be added in a follow-up PRs.

Implement partial snapshot recovery

---

lib/common/common/src/counter/conditioned_counter.rs
lib/common/common/src/counter/hardware_accumulator.rs
lib/common/common/src/counter/hardware_counter.rs
lib/common/common/src/counter/hardware_data.rs
lib/common/common/src/counter/mod.rs

Adds a new wrapper for `HwCounterCell` that allows conditioned counting.
This is needed in places where we can't use a multiplier of 0 to disable counting, like mmap bool index.
An example of how this can be used can be found in #6296.

Add ConditionedCounter

---

tools/smaps-view.py

A tool which can be used to see mmaps disk cache inside running qdrant process.
```
Usage examples:
python measure.py $(pidof qdrant) '.*/vector_index/.*'
python measure.py $(pidof qdrant) '.*/vector_storage/.*' -v
Example output:
Cache percentages for pattern '.vector_storage.*':
r--s: 0.00%
rw-s: 0.06%
```

Add a tool to view percentage of mmaps cache

---

lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/replica_set/shard_transfer.rs
lib/collection/src/shards/shard.rs
lib/collection/src/update_handler.rs
lib/collection/src/wal_delta.rs

Migrates the WAL lock from a sync parking lot mutex to an async tokio mutex.
The mutex is almost exclusively used in async context. I therefore suggest to make it an async mutex, so that we don't run into the constant issue of trying to hold this lock across await points.
This is the first step in a bigger attempt to more clearly define the boundary between our sync (segments) and async (the rest) code. Currently, this boundary is very vague because we constantly mix up the two flavors, which creates constant problems. I'd like to clean up this technical dept a bit.
Contains no logic changes. Purely mechanical to change the mutex type.
3. [x] …

Migrate WAL mutex from parking lot to tokio

---

lib/collection/src/operations/verification/mod.rs
lib/collection/src/operations/verification/operation_rate_cost.rs
lib/collection/src/shards/local_shard/shard_ops.rs
lib/common/common/src/rate_limiting.rs
tests/openapi/test_strictmode.py

This PR adds rate limiting for the recommendation API (old & query) where the number of examples is used to price the query.

Rate limit recommendation based on number of examples

---

lib/collection/src/operations/universal_query/shard_query.rs
lib/segment/benches/multi_vector_search.rs
lib/segment/src/vector_storage/query_scorer/mod.rs
tests/openapi/test_multi_vector.py

This PR documents the discrepancy for multivector scoring using Euclidean distance reported in https://github.com/qdrant/qdrant/issues/6294
I tried to fix it but the resulting [PR](https://github.com/qdrant/qdrant/pull/6298) is not [convincing](https://github.com/qdrant/qdrant/pull/6298#issuecomment-2776017334).
The most reasonable way forward is to adapt the local mode to use the same scoring as in core.
This PR makes sure that the knowledge from this investigation is captured.

Document Multivector Euclidean scoring discrepancy

---

lib/collection/src/operations/verification/query.rs
src/actix/api/query_api.rs

I noticed there was duplication in the implementation of `StrictModeVerification` trait for query request types.
We already have a converging type for rest and grpc for query requests, so we can implement the trait only for this converging type.
By unifying, this also fixes a hole where we were not checking the prefetches when using the grpc interface.

Only implement verification for `CollectionQuery` types

---

.github/workflows/rust-lint.yml

Fixing lint CI step
```
Run sudo apt-get install clang libunwind-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
liblzma-dev
Suggested packages:
liblzma-doc
The following NEW packages will be installed:
clang liblzma-dev libunwind-dev
0 upgraded, 3 newly installed, 0 to remove and 116 not upgraded.
Need to get 2088 kB of archives.
After this operation, 7007 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu noble/universe amd64 clang amd64 1:18.0-59~exp2 [5846 B]
Ign:3 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 liblzma-dev amd64 5.6.1+really5.4.5-1build0.1
Get:4 …
```

Fixing failing CI due to missing liblzma

---

lib/collection/src/shards/local_shard/shard_ops.rs
tests/openapi/test_strictmode.py

Large retrieve operation should consume more tokens in the rate limiter.

Rate limit retrieve based on number of ids

---

lib/collection/src/operations/verification/mod.rs
lib/collection/src/operations/verification/operation_rate_cost.rs
lib/collection/src/shards/local_shard/shard_ops.rs
tests/openapi/test_strictmode.py

This PR changes the read rate limiter to charge request additionally based on the number of filters they contain.
The main principle is that a user should not be send a lot of expensive queries over a long period of time.

Read rate limiter charge per filter condition

---

.github/workflows/coverage.yml

Unfortuantely https://github.com/qdrant/qdrant/pull/6262 didn't fix the codecov `dev` branch missing issue. I dug a little deeper and found that it's because Codecov action might not be able to access to rest of the commits when using `actions/checkout` since default cloning depth is 1. This means it doesn't attach the commit to the (dev) branch. I think this should fix the problem.

Fix codecov branch issue

---

lib/collection/src/operations/types.rs
lib/segment/benches/hnsw_build_asymptotic.rs
lib/segment/benches/hnsw_search_graph.rs
lib/segment/benches/scorer_mmap.rs
lib/segment/benches/vector_search.rs
lib/segment/src/common/operation_error.rs
lib/segment/src/fixtures/index_fixtures.rs
lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs
lib/segment/src/index/plain_vector_index.rs
lib/segment/src/index/sparse_index/sparse_vector_index.rs
lib/segment/src/vector_storage/async_raw_scorer.rs
lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs
lib/segment/src/vector_storage/raw_scorer.rs
lib/segment/src/vector_storage/tests/async_raw_scorer.rs
lib/segment/src/vector_storage/tests/custom_query_scorer_equivalency.rs
lib/segment/src/vector_storage/tests/test_appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_sparse_vector_storage.rs

Depends on #6299 as it touches the same benchmark. Ignore first commit during the review.
This PR removes `is_stopped` flag from `RawScorer` as suggested in https://github.com/qdrant/qdrant/pull/6245#issuecomment-2751183795. Instead, it is passed to search functions explicitly.

Remove is_stopped from RawScorer 

---

Cargo.lock
lib/common/common/src/flags.rs
lib/segment/Cargo.toml
lib/segment/benches/multi_vector_search.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/tests/test_graph_connectivity.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/tests/integration/batch_search_test.rs
lib/segment/tests/integration/byte_storage_hnsw_test.rs
lib/segment/tests/integration/byte_storage_quantization_test.rs
lib/segment/tests/integration/exact_search_test.rs
lib/segment/tests/integration/filtrable_hnsw_test.rs
lib/segment/tests/integration/gpu_hnsw_test.rs
lib/segment/tests/integration/hnsw_discover_test.rs
lib/segment/tests/integration/hnsw_incremental_build.rs
lib/segment/tests/integration/hnsw_quantized_search_test.rs
lib/segment/tests/integration/main.rs
lib/segment/tests/integration/multivector_filtrable_hnsw_test.rs
lib/segment/tests/integration/multivector_hnsw_test.rs
lib/segment/tests/integration/multivector_quantization_test.rs

This PR implements incremental HNSW building for the append-only case.
A new feature flag is added, `incremental_hnsw_building`, disabled by default.
When enabled, it will try to reuse old graph as a starting point for building the new graph. When reusing, point levels and old graph links are copied as-is (but with reassigned IDs) before the regular HNSW point insertion process starts.
What is not supported as of now:
- GPU building. Only point levels are copied.
- Point/vector removal/overwriting. If a point or vector is removed, the old graph is discarded. Same if vector value is changed.
When old index is reused, the following log messages are printed:
```
DEBUG segment::index::hnsw_index::hnsw: building HNSW for 518500 vectors with 8 CPUs
DEBUG segment::index::hnsw_index::hnsw: …
```

Incremental HNSW index building: append-only case 

---

lib/collection/src/operations/verification/matrix.rs
tests/openapi/test_strictmode.py

Similar to https://github.com/qdrant/qdrant/pull/6353
For the distance matrix API with fetch limit elements per sample to return a sparse matrix.

Fix strict mode query limit for distance matrix API

---

lib/collection/src/operations/universal_query/planned_query.rs
lib/common/memory/src/madvise.rs
tests/openapi/test_query_full.py

One overlooked quirk when developing prefetches is that we should not propagate the main query offset into them. 
In general terms, offsets are not compatible with prefetches. Let's look at one example:
Imagine we have a vector search prefetch (limit=5), and an order_by main query (limit=3). For simplicity, let's assume letters are point IDs, and numbers are the order_by values
```
with offset 0
prefetch candidates: [a: 5, b: 8, c: 3, d: 9, e: 2]
main query ordering: [e: 2, c: 3, a: 5, b: 8, d: 9]
main query results:  [e: 2, c: 3, a: 5]
----------------------------------------
with offset 3 (propagated)
prefetch candidates: [a: 5, b: 8, c: 3, d: 9, e: 2, f: 6, g: 1, h: 4]
main query ordering: [g: 1, e: 2, c: 3, h: 4, a: 5, f: 6, b: 8, d: 9]
main query results:  [h: 4, a: 5, f: 6] 
```
As …

[query api] don't propagate offset into prefetches

---

lib/collection/src/shards/local_shard/scroll.rs
lib/collection/src/shards/local_shard/search.rs
lib/collection/src/shards/local_shard/shard_ops.rs

A batch query request - consisting of many queries - is only parallelized over segments in a collection. If you have just one segment, the full batch is processed on a single system thread. Depending on your use case there may be a lot of wasted resources here.
I don't this is unlikely to happen in practice. We sometimes recommend to have one (or very few) segments to speed up overall searches. Our Python client is not concurrent by default as it's commonly single threaded. This set up would only ever be fast if a user explicitly sends multiple concurrent requests from the client.
In this PR I try to parallelize large query batches to make better use of the available resources. Ideally it speeds up batch queries when using a single client.
The idea is simple: chunk a large batch of …

Parallelize large segment search batches

---

lib/common/common/src/flags.rs
src/main.rs

Follow-up for #6325. This PR sets `incremental_hnsw_building` by default.
In this PR, `#[derive(Default)]` for `FeatureFlags` is replaced with manual `impl Default` that sets the said flag. Tests are updated to make sure that `Default`, `Deserealize` and `.is_default()` are still in sync.

Enable incremental_hnsw_building default

---

lib/segment/src/common/mmap_bitslice_buffered_update_wrapper.rs
lib/segment/src/common/mmap_slice_buffered_update_wrapper.rs
lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs
lib/segment/src/common/rocksdb_buffered_update_wrapper.rs

It looks like we had a broken flush procedure in all db wrappers.
Old logic does the following:
- accumulate updates in tmp structure in ram
- On flush - move tmp structure in flush thread
- Write changes from tmp structure to disk
But, what if we read from the structure in the moment after flush thread created, but before it is actually written - we can have inconsistent results.
This PR: makes a copy of changes for the thread and only removes pending updates if they are persisted.

Fix update wrapper

---

Cargo.lock
lib/gridstore/Cargo.toml
lib/gridstore/src/tracker.rs
lib/segment/Cargo.toml
lib/segment/benches/mmap_bitslice_buffered_update_wrapper.rs
lib/segment/src/common/mmap_bitslice_buffered_update_wrapper.rs
lib/segment/src/common/mmap_slice_buffered_update_wrapper.rs
lib/segment/src/common/rocksdb_buffered_delete_wrapper.rs
lib/segment/src/common/rocksdb_buffered_update_wrapper.rs
lib/segment/src/common/score_fusion.rs
lib/segment/src/payload_storage/in_memory_payload_storage.rs
lib/segment/src/payload_storage/in_memory_payload_storage_impl.rs
lib/segment/src/payload_storage/mmap_payload_storage.rs
lib/segment/src/payload_storage/on_disk_payload_storage.rs
lib/segment/src/payload_storage/payload_storage_base.rs
lib/segment/src/payload_storage/payload_storage_enum.rs
lib/segment/src/payload_storage/simple_payload_storage.rs
lib/segment/src/payload_storage/simple_payload_storage_impl.rs

A very simple change - replace the standard [`HashMap`](https://doc.rust-lang.org/std/collections/struct.HashMap.html) with [`AHashMap`](https://docs.rs/ahash/latest/ahash/struct.AHashMap.html). Or more specifically, hash using [`ahash`](https://docs.rs/ahash).
It changes the hashmap in the mmap/rocksdb update buffer types where it lists changes pending flush. Its also applied to some surrounding types/functions. There are more places we can benefit from this, but lets take it step by step.
Ahash is much faster, at least on small numeric keys like we're using in many places. Here's a generic benchmark of <ins>sip13</ins> (used by standard HashMap) versus <ins>ahash</ins>:
<small>[source](https://github.com/tkaitchuck/aHash/blob/7d5c661a74b12d5bc5448b0b83fdb429190db1a3/README.md#comparison- …

Speed up pending changes lookups using ahash

---

lib/collection/src/collection/clean.rs
lib/collection/src/collection/mod.rs
lib/collection/src/collection/point_ops.rs
lib/collection/src/collection/sharding_keys.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/shard_holder/resharding.rs
lib/collection/src/tests/points_dedup.rs

Fixes on top of <https://github.com/qdrant/qdrant/pull/6364>
The main things this solves is:
- if resharding abort fails, don't forget to mark replica as dead
- if aborting resharding, don't forget to also cancel related shard transfers
- first mark replica as dead, then abort resharding
- no more replica state blinking, don't mark as active first and then dead
- actually delete points in replica even if in dead state

Abort resharding after marking as dead

---

lib/collection/src/collection/clean.rs
lib/collection/src/collection/mod.rs
lib/collection/src/collection/point_ops.rs
lib/collection/src/collection/sharding_keys.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/update.rs
lib/collection/src/shards/shard_holder/resharding.rs
lib/collection/src/tests/points_dedup.rs

Nodes can go down while resharding and we found an edge case where it can cause problems. 
Whenever a node goes down, the leader detects this (on next update request) because of `sync_local_state()`, and it notifies other peers by appending 
```
CollectionMeta(SetShardReplicaState(SetShardReplicaState { collection_name: "benchmark", shard_id: 0, peer_id: XYZ, state: Dead, from_state: None }))
```
to the consensus WAL. Now all online nodes are expected to apply this operation locally and **try** to mark the resharding replica as `Dead`. 
However, this logic to mark `Resharding/ReshardingScaleDown` state replicas as `Dead` behaves like this:
- If node that went down was the main resharding replica (`resharding_state.peer_id =  peer_that_went_down`), we abort resharding (this …

Abort resharding if any Resharding replica is to be marked dead

---

lib/collection/src/collection/mod.rs
lib/collection/src/collection/shard_transfer.rs
lib/collection/src/shards/dummy_shard.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/shard_holder/mod.rs
tests/consensus_tests/test_failed_snapshot_recovery.py
tests/consensus_tests/utils.py

Fixes the bug demonstrated in https://github.com/qdrant/qdrant/pull/6292
TODO:
- ~Try to load shards even if they are dirty instead of directly recreating as empty shard - especially important when we have 0 replicas?~ Not desirable anymore.

Recover dirty shards using other replicas when marked Dead

---

tests/consensus_tests/test_failed_snapshot_recovery.py

Try fixing the flakiness in test introduced by https://github.com/qdrant/qdrant/pull/6364. 
Somehow the bug didn't reproduce for me except once. It happened at [this](https://github.com/qdrant/qdrant/pull/6397/files#diff-c03f565135518d69bd66fe24214e6005ba3c6102155d72790d6ba8bfe25a7c02R312) line where it returns 0 shards.

Fix flaky test with dirty shards

---

docs/redoc/master/openapi.json
lib/collection/src/collection/mod.rs
lib/collection/src/telemetry.rs

This makes the collection telemetry to not include `"shards"`, `"transfers"`, and `"resharding"` fields when details level is  < 3

[#6390] skip serializing shard details in Level2

---

docs/redoc/master/openapi.json
lib/collection/src/collection/mod.rs
lib/collection/src/shards/dummy_shard.rs
lib/collection/src/shards/forward_proxy_shard.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/shards/local_shard/telemetry.rs
lib/collection/src/shards/proxy_shard.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/telemetry.rs
lib/collection/src/shards/shard.rs
lib/collection/src/shards/telemetry.rs
lib/collection/src/telemetry.rs
lib/common/common/src/types.rs
lib/segment/src/common/anonymize.rs
lib/segment/src/common/operation_time_statistics.rs
lib/segment/src/types.rs
lib/storage/src/content_manager/toc/mod.rs
src/actix/api/service_api.rs
src/common/metrics.rs
src/common/telemetry_ops/collections_telemetry.rs
tests/openapi/test_service.py

Main idea: for automated tools like Cluster Manager it should be enough to work with level-3. Level-4 is quite expensive in terms of request size and should only be required for in-depth performance debug 
- allow shard states in anonymize telemetry (with hashed peer ids)
- split shard and segments detail levels
--- 
- Make sure cluster manager can use Level3 of telemetry

Telemetry improvements

---

Cargo.toml

With removed likes panic backtrace looks like this:
```
2025-04-20T09:59:04.898821Z ERROR qdrant::startup: Panic backtrace: 
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>
9: <unknown>
10: <unknown>
11: <unknown>
12: <unknown>
13: <unknown>
14: <unknown>
15: <unknown>
16: <unknown>
17: <unknown>
18: <unknown>
19: <unknown>
20: <unknown>
21: <unknown>
22: <unknown>
23: <unknown>
24: <unknown>
25: <unknown>
26: <unknown>
27: <unknown>
28: <unknown>
29: <unknown>
30: <unknown>
31: <unknown>
32: <unknown>
33: <unknown>
34: <unknown>
35: <unknown>
36: <unknown>
37: <unknown>
38: <unknown>
39: <unknown>
40: <unknown>
```

rollback disabling of debug symbols

---

lib/common/common/src/flags.rs
lib/segment/src/common/rocksdb_wrapper.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs

Note: this must only be merged as part of the Qdrant 1.14 release!
Enable the new [mutable ID tracker](https://github.com/qdrant/qdrant/issues/6157) by default, and remove the now obsolete feature flag for it.
This will now use the new mutable ID tracker using custom storage in new mutable segments. It replaces the old RocksDB based mutable ID tracker.

Qdrant 1.14: enable mutable ID tracker by default

---

lib/collection/src/shards/shard_holder/shard_mapping.rs
lib/common/common/src/flags.rs

Note: this must only be merged as part of the Qdrant 1.14 release!
Enable <https://github.com/qdrant/qdrant/pull/5838> by default, to utilize the new shard key format.

Qdrant 1.14: enable new shard key format by default

---

Cargo.lock
Cargo.toml
docs/redoc/default_version.js
docs/redoc/index.html
docs/redoc/v1.14.x/openapi.json
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

```
* https://github.com/qdrant/qdrant/milestone/23 - Allow server-side score boosting with user-defined formula. See [Documentation](.............)
* https://github.com/qdrant/qdrant/pull/6256 - New `sum_scores` recommendation strategy. Useful for implementing relevance feedback. See [Documentation](..........)
* https://github.com/qdrant/qdrant/pull/6325 - Incremental HNSW building. Segment optimized will partially re-use existing HNSW graph on merging segments.
* https://github.com/qdrant/qdrant/pull/6323, https://github.com/qdrant/qdrant/pull/6396 - Improve eviction strategy for unused disk cache
* https://github.com/qdrant/qdrant/pull/6303 - Minor optimizations for memory allocations
* https://github.com/qdrant/qdrant/pull/6385 - Minor internal optimizations
* …
```

bump v1.14.0

---

lib/collection/src/operations/universal_query/planned_query.rs

In our queries, we cut the offset off results at collection level. At shard level we should still adjust the limit so that there's enough results left when we cut the offset.

Also use limit+offset with prefetches, we cut offset at collection level

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to 1.14.1-dev for the [Qdrant 1.14.0](https://github.com/qdrant/qdrant/pull/6404) release.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/6278>.

Bump dev version to 1.14.1-dev

---

lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/tests/mod.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/query_optimization/condition_converter/match_converter.rs

Main change is
```diff
pub struct ParsedQuery {
-    pub tokens: Vec<Option<TokenId>>,
+    pub tokens: Vec<TokenId>,
}
```
The reason for this PR is because in text matching we require that the entirety of tokens need to be present in the document. 
When parsing the query, an unseen token would return `None`. If we haven't seen such a token it means it is not in the segment, so we should return early.
This change also simplifies handling of the tokens, since before, we needed to check that no tokens were `None` during every evaluation, and then unwrapping. We no longer need to deal with this if we move the check to the shape of the parsed query.

[full-text index] return earlier in text query parsing

---

lib/collection/src/operations/query_enum.rs
lib/collection/src/operations/verification/operation_rate_cost.rs
lib/segment/src/data_types/vectors.rs
tests/consensus_tests/test_strict_mode.py
tests/consensus_tests/test_triple_replication.py
tests/openapi/helpers/collection_setup.py
tests/openapi/test_strictmode.py

Considers the size of multivectors and total amount of examples in special queries like recommend, discover, etc. in the cost of a single core_search. 
This effectively limits requests that would be too expensive according to the rate-limiter setting.

[rate limits] consider length of multivectors for query cost

---

lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/posting_list.rs

Builds on top of #6264 
I think this is an unnecessary wrapping into `Option`, if a posting list is empty, let it just be an empty `PostingList`.
`Option<PostingList>` and `PostingList` both use 24 bytes, even when the option is `None`.
Main change is this:
```diff
pub struct MutableInvertedIndex {
-    pub(in crate::index::field_index::full_text_index) postings: Vec<Option<PostingList>>,
+    pub(in crate::index::field_index::full_text_index) postings: Vec<PostingList>,
pub(in crate::index::field_index::full_text_index) vocab: HashMap<String, TokenId>,
pub(in crate::index::field_index::full_text_index) point_to_docs: Vec<Option<Document>>,
pub(in crate::index::field_index::full_text_index) points_count: usize,
}
```

[mutable text index] No need to wrap vec in option

---

lib/segment/src/types.rs

Applies <https://github.com/qdrant/qdrant/pull/6420#discussion_r2056145876>, which I forgot in <https://github.com/qdrant/qdrant/pull/6420>.
Thought I had applied the review suggestions before merging, but I now discovered I didn't properly push.

Use smol string as shard key - review suggestions

---

Cargo.lock
lib/segment/Cargo.toml
lib/segment/src/common/anonymize.rs
lib/segment/src/types.rs

In <https://github.com/qdrant/qdrant/pull/6420> I implemented usage of `SmolStr` for shard keys.
[Here](https://github.com/qdrant/qdrant/pull/6420#issuecomment-2824510509) a different string type is suggested: `ecow`'s `EcoString`
A fresh benchmark convinces me:
<small>([source](https://github.com/rosetta-rs/string-rosetta-rs))</small>
We probably want to fully replace SmolStr at some point, but there are some blockers for that. I'll put it on my list of tasks because it's not high priority.

Use ecow strings for shard keys

---

tests/openapi/test_query_formula.py

The test is flaky on slow machines.
```
FAILED tests/openapi/test_query_formula.py::test_formula[True-formula0-<lambda>] - AssertionError: {'status': {'error': 'Wrong input: Expected number value for price in the payload and/or in the formula defaults. Error: Value is not a number'}, 'time': 0.002502803}
```
We need to make sure the payload index has been built.

Fix flaky test formula

---

Cargo.lock
lib/segment/Cargo.toml
lib/segment/src/index/field_index/geo_hash.rs
lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/types.rs

Continuation after <https://github.com/qdrant/qdrant/pull/6426>, using the same benchmark as argument.
Required <https://github.com/typst/ecow/pull/48> to be merged and released.
As a bonus, this removes a bunch of intermediate strings by formatting directly.

Fully replace SmolStr with ecow string

---

Cargo.lock
Cargo.toml
lib/collection/Cargo.toml
lib/gridstore/Cargo.toml
lib/gridstore/src/gridstore.rs
lib/gridstore/src/tracker.rs
lib/segment/Cargo.toml

This PR fixes one thing we overlooked in gridstore.
Pending updates only stored the last place where a value is. So, when flushing, we would only free the previous _stored_ value. If multiple updates happened in between flushes, we'd end up with storage that is never marked as free.
With these changes, now we keep track of *all* the places that values have been written in between flushes, so that we only keep the latest one, and are able to mark all the previous places as free.
For testing, I modified one test, so that it failed without the changes, and also did manual validation by making sure that 
```bash
bfb -n 5000000 --max-id 10 -d 128 --float-payloads true --segments 1 --on-disk-payload --text-payloads --text-payload-length 100 --skip-field-indices
```
doesn't grow the size of …

Reuse space more in gridstore

---

.github/workflows/rust.yml

This step often fails for Linux with
```
Run cargo build --tests --workspace --locked
cargo build --tests --workspace --locked
shell: /usr/bin/bash -e {0}
env:
CARGO_TERM_COLOR: always
CARGO_HOME: /home/runner/.cargo
CARGO_INCREMENTAL: 0
CACHE_ON_FAILURE: false
Updating crates.io index
Compiling memory v0.0.0 (/home/runner/work/qdrant/qdrant/lib/common/memory)
Compiling common v0.0.0 (/home/runner/work/qdrant/qdrant/lib/common/common)
Compiling io v0.0.0 (/home/runner/work/qdrant/qdrant/lib/common/io)
Compiling dataset v0.0.0 (/home/runner/work/qdrant/qdrant/lib/common/dataset)
Compiling quantization v0.1.0 (/home/runner/work/qdrant/qdrant/lib/quantization)
Compiling segment v0.6.0 (/home/runner/work/qdrant/qdrant/lib/segment)
Compiling gpu v0.1.0 (/home/runner/work/qdrant/qdrant/lib/gpu) …
```

Use mold for building tests

---

tests/openapi/helpers/helpers.py

We had recently a weird integration error that was difficult to diagnose when running the `openapi` tests.
This PR backports some of the debug logging that helped to resolve the problem in order to move faster next time.

Log context of openapi validation crash

---

lib/segment/src/segment/mod.rs
lib/segment/src/segment/snapshot.rs
lib/segment/src/segment_constructor/mod.rs
lib/segment/src/segment_constructor/rocksdb_builder.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs

Basically, subject. Currently, we always initialize RocksDB when creating a segment, even if it's later completely unused by any structure in the segment. This PR makes the field optional and tweaks segment initialization, so that we only open it if it's required.

Only initialize segment RocksDB if it's used by the segment

---

.github/workflows/integration-tests.yml
lib/collection/src/collection/shard_transfer.rs
tests/consensus_tests/fixtures.py
tests/consensus_tests/test_failed_snapshot_recovery.py
tests/consensus_tests/utils.py

Reproduce and fix the flakiness with shard flag existing after recovery.
```
=========================== short test summary info ============================
FAILED tests/consensus_tests/test_failed_snapshot_recovery.py::test_dirty_shard_handling_with_active_replicas[stream_records] - AssertionError: assert not True
+  where True = <function exists at 0x7f3fd39eb600>('/tmp/pytest-of-runner/pytest-1/test_dirty_shard_handling_with1/peer2/storage/collections/test_collection/shard_0.initializing')
+    where <function exists at 0x7f3fd39eb600> = <module 'posixpath' (frozen)>.exists
+      where <module 'posixpath' (frozen)> = os.path
======= 1 failed, 205 passed, 2 skipped, 1 warning in 651.74s (0:10:51) ========
```
The flaky test file [ran 50+ times over …

Fix snapshot test flakiness

---

lib/api/build.rs
lib/api/src/grpc/mod.rs
lib/api/src/grpc/ops.rs
lib/api/src/grpc/proto/points_internal_service.proto
lib/api/src/grpc/qdrant.rs
lib/api/src/grpc/validate.rs
lib/collection/src/shards/queue_proxy_shard.rs
lib/collection/src/shards/remote_shard.rs
src/tonic/api/points_internal_api.rs

Speed-up wal-delta transfer.
---
ToDo:

Faster wal-delta transfer

---

lib/gridstore/Cargo.toml
lib/gridstore/benches/flush_bench.rs
lib/gridstore/src/bitmask/mod.rs
lib/gridstore/src/gridstore.rs

Found this TODO while inspecting the code, I don't have great numbers to share, but when profiling the `bustle_bench`, the flamegraph proved that flushing takes less time when there are lots of updates.
Before:
After:

[minor opt] update region gaps in batch when flushing

---

lib/gridstore/benches/flush_bench.rs

CI is currently broken with
```
error: variables can be used directly in the `format!` string
--> lib/gridstore/benches/flush_bench.rs:13:26
|
13 |         let bench_name = format!("flush after {} sequential writes", unflushed_updates);
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
= note: `-D clippy::uninlined-format-args` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::uninlined_format_args)]`
help: change this to
|
13 -         let bench_name = format!("flush after {} sequential writes", unflushed_updates);
13 +         let bench_name = format!("flush after {unflushed_updates} sequential …
```

Fix CI clippy lint for flush_bench

---

Cargo.toml
lib/segment/src/index/field_index/geo_hash.rs
lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs

Implements <https://github.com/qdrant/qdrant/pull/6427#discussion_r2059349873>.
Use byte strings in and around geo hashes. This accidentally turned into a bit of yak shaving, but I think it's worth it.
Also applies <https://github.com/qdrant/qdrant/pull/6427#discussion_r2059222412>.

Use byte strings for geohash

---

tests/consensus_tests/test_failed_snapshot_recovery.py

Resolve https://github.com/qdrant/qdrant/issues/6467
We basically changed 1 one of the points and hence final results often changed. Now we upsert that with `offset=10000` so it doesn't affect the existing results (scroll returns 10 points by default, it's almost impossible that it will get point ID = 10k in those first 10 results).

Fix point comparison in test

---

lib/common/common/src/rate_limiting.rs

Fixing https://github.com/qdrant/qdrant/issues/5850
There is no need for a high precision comparison here.

Fix flaky test rate limiter

---

lib/collection/src/collection/payload_index_schema.rs
lib/collection/src/operations/verification/mod.rs
lib/collection/src/operations/verification/query.rs
lib/collection/src/operations/verification/search.rs
lib/segment/src/types.rs
tests/openapi/test_strictmode.py

Fix strict mode for grouping APIs to make sure `unindexed_filtering_retrieve` applies to the field grouped on.

Fix strict mode unindexed group_by path

---

.config/nextest.toml

Having up to 2 retries makes a total of 3 runs for a flaky test.
This is too generous.
This PR gives only one additional chance to a flaky test to succeed.

Decrease retry count on flaky test

---

.github/workflows/rust-gpu.yml
.github/workflows/rust-lint.yml

Fixes <https://github.com/qdrant/qdrant/issues/6312>.
Reverts <https://github.com/qdrant/qdrant/pull/6306> since upgrading `shaderc` in <https://github.com/qdrant/qdrant/pull/6483>.
Additional GPU test: :green_circle:  https://github.com/qdrant/qdrant/actions/runs/14833137285

Revert Downgrade cmake 3.x

---

lib/collection/src/operations/verification/query.rs
tests/openapi/test_strictmode.py

This PR implements fully the strict mode for `search_allow_exact` to make sure no search query can be issued against a disabled HNSW index.
The check takes into account the presence of prefetches to still allow the rescoring use case anyway.

Strict mode detects full scan on query

---

lib/collection/src/operations/shared_storage_config.rs
lib/collection/src/shards/local_shard/search.rs
lib/common/common/src/defaults.rs
lib/storage/src/types.rs
src/common/helpers.rs

Fixes <https://github.com/qdrant/qdrant/issues/6423> regression
Extension of <https://github.com/qdrant/qdrant/pull/6326>
While the condition change is not perfect, it does help significantly with the issue as described above.
This just prevents batching for a specific case that is known to perform bad: when having a high number of segments versus search threads.

Don't batch queries if having more segments than search threads

---

lib/api/build.rs
lib/api/src/grpc/qdrant.rs
lib/api/src/grpc/validate.rs
lib/segment/src/data_types/index.rs
lib/segment/src/types.rs
src/common/update.rs
tests/openapi/test_payload_indexing.py

Add API validation for `IntegerIndexParams` to prevent users from creating integer indexes which do not support `lookup` nor `range` to avoid bad performance.

Validate IntegerIndexParams

---

tests/consensus_tests/test_recovery_mode.py

Add an integration test for recovery mode where the dummy shard created by recovery mode remains in Active state but with 0 points. If an update comes in we expect the replica to get marked Dead but never initiate a transfer to restore the Dead replica.

Add a test for recovery mode

---

lib/common/common/Cargo.toml
lib/common/common/benches/hw_counter.rs
lib/common/common/src/counter/conditioned_counter.rs
lib/common/common/src/counter/hardware_counter.rs
lib/common/common/src/counter/hardware_data.rs

Improve performance of `HardwareCounterCell::disposable()` by 72x.
Since disposable HwCounterCells have to be passed to unmeasured functions, even in hot-paths, performance
is critical.
Dev:
```
Disposable Hw Cell      time:   [170.26 ns 170.48 ns 170.77 ns]
```
This PR:
```
Disposable Hw Cell      time:   [2.3429 ns 2.3600 ns 2.3769 ns]
change: [-98.609% -98.601% -98.594%] (p = 0.00 < 0.05)
```

HardwareCounterCell::disposable() Performance Improvement

---

lib/segment/src/fixtures/index_fixtures.rs
lib/segment/src/segment_constructor/batched_reader.rs
lib/segment/src/vector_storage/chunked_mmap_vectors.rs
lib/segment/src/vector_storage/chunked_vector_storage.rs
lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/in_ram_persisted_vectors.rs
lib/segment/src/vector_storage/multi_dense/appendable_mmap_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs

Depends on #6487
Improves optimization when copying points from different segments into a new one.
Benchmark:
**On the same machine** with storage on a Hetzner Network Disk (5M points, 20=>10 segments, vectors on disk)
Dev: 200s
PR: 3s
**SSH-FS mounted** Hetzner Network Disk (100k points, 10=>5 segments, vectors on disk)
Dev: ~450s
PR: 240s

Make reads sequential in BatchedVectorReader

---

lib/common/common/src/budget.rs

Our `test_cancel_optimization` test is flaky. It fails on high CPU systems.
```bash
$ QDRANT_NUM_CPUS=24 cargo test -p collection -- test_cancel_optimization
---- tests::test_cancel_optimization stdout ----
actual_optimization_duration = 114 ms
thread 'tests::test_cancel_optimization' panicked at lib/collection/src/tests/mod.rs:210:9:
assertion `left == right` failed
left: 2
right: 3
```
The reason is asymmetric utilization of IO and CPU budget (implemented in <https://github.com/qdrant/qdrant/pull/6015>). On 24 CPUs, the previous implementation allowed 2 concurrent IO tasks while it allowed 3 concurrent CPU tasks.
This adjusts the permit selection to make it symmetric.
If we don't like this, the alternative would be to adjust the test. Change …

Fix flaky test: prevent asymmetric utilization IO/CPU utilization

---

lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
lib/segment/src/index/hnsw_index/gpu/gpu_links.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/links_container.rs
lib/segment/src/index/hnsw_index/mod.rs

This PR optimizes heuristic computation.
When building the HNSW graph (particularly when adding incoming links), the following loop pattern happen:
A few links are added to the container, then this container is pruned using the heuristic and the loop starts again.
Illustrated by pseudo code:
```
links += new_points
links = heuristic(links)
links += new_points
links = heuristic(links)
…
```
Running the heuristic requires `O(n*n)` vector comparisons, thus this part of the code could take a significant percentage of the graph building time.
However, some vector comparisons could be avoided if part of the input has already been processed by the heuristic.
This PR implements this optimization by introducing a new struct `LinksContainer` that tracks the number of points that are processed by …

Heuristic optimization

---

lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_chunks_reader.rs
lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_posting_list.rs
lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/tests/mod.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/field_index/map_index/mmap_map_index.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/plain_payload_index.rs
lib/segment/src/index/struct_payload_index.rs

Depends on <https://github.com/qdrant/qdrant/pull/6444>.
Add in-memory payload index for full text using mmap as storage.
Loading the in-memory full text payload index from mmap is **33x faster** than from RocksDB, as shown in this simple benchmark:
- `bfb --text-payloads --text-payload-length 40 -n 500000 -d1 --indexing-threshold 100`:
- Old RocksDB based index: 2.4s, 2.5s, 2.5s, 2.6s = avg 2.5s
- New mmap based index: 77.2ms, 75.1ms, 77.2ms, 74.7ms = avg 0.076s (33x faster!)
- `bfb --text-payloads --text-payload-length 100 --text-payload-vocabulary 50000 -n 500000 -d1 --indexing-threshold 100`:
- Old RocksDB based index: 6.6s, 6.6s, 6.7s, 6.6s = avg 6.6s
- New mmap based index: 202.8ms, 200.6ms, 211.2ms, 201.8ms = avg 0.2s (33x faster!)
2. [x] …

Add in-memory payload index on mmap storage (full text)

---

lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs
lib/common/common/src/tar_ext.rs
lib/common/common/src/validation.rs
lib/quantization/src/encoded_storage.rs
lib/segment/src/common/operation_time_statistics.rs
lib/segment/src/compat.rs
lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
lib/segment/src/index/field_index/histogram.rs
lib/segment/src/index/field_index/map_index/immutable_map_index.rs
lib/segment/src/payload_storage/mmap_payload_storage.rs
lib/segment/src/vector_storage/chunked_vectors.rs
lib/segment/src/vector_storage/quantized/quantized_mmap_storage.rs
src/actix/mod.rs
src/common/helpers.rs
src/common/http_client.rs
src/settings.rs

Rust [1.87](https://releases.rs/docs/1.87.0/) is coming out soon.
A lot of Clippy lints are being triggered.
I propose to manage those in several PRs for better clarity.
This first PR is the result of `clippy --fix` to get get started.

Clippy 1.87 autofix

---

lib/collection/src/save_on_disk.rs
lib/common/common/src/mmap_hashmap.rs
lib/common/io/src/file_operations.rs
lib/segment/src/id_tracker/immutable_id_tracker.rs
lib/segment/src/id_tracker/mutable_id_tracker.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
lib/segment/src/index/hnsw_index/graph_links/serializer.rs
lib/segment/src/vector_storage/chunked_vectors.rs
lib/storage/src/content_manager/consensus/persistent.rs
lib/storage/src/content_manager/snapshots/mod.rs

Does two things in places where it makes sense:
- buffer writes
- explicitly flush write buffers to catch IO errors in our own error handling
Continuation of <https://github.com/qdrant/qdrant/pull/6513>.

Use more write buffers, and flush them

---

lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/map_index/immutable_map_index.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/field_index/map_index/mutable_map_index.rs
lib/segment/src/index/field_index/mmap_point_to_values.rs
lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/mod.rs
lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/tests.rs
lib/segment/src/types.rs

Depends on <https://github.com/qdrant/qdrant/pull/6495>.
Add in-memory payload index for geo points using mmap as storage.
Loading the in-memory full text payload index from mmap is **24x faster** than from RocksDB, as shown in this simple benchmark:
- `bfb --geo-payloads -n 2000000 -d1 --indexing-threshold 100`:
- Old RocksDB based index: 11.78s, 11.86s, 11.57s, 11.66s = avg 11.72s
- New mmap based index: 0.489s, 0.476s, 0.476s, 0.477s = avg 0.480ms (24x faster)

Add in-memory payload index on mmap storage (geo)

---

clippy.toml

Follow up to https://github.com/qdrant/qdrant/pull/6518
There is a large amount of warning with:
```
error: the `Err`-variant returned from this function is very large
--> lib/api/src/grpc/conversions.rs:2210:6
|
2210 | ) -> Result<segment_vectors::NamedVectorStruct, Status> {
|      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 176 bytes
|
= help: try reducing the size of `tonic::Status`, for example by boxing large elements or replacing it with `Box<tonic::Status>`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
```
Given that we use the Tonic's `Status` a lot as error type, I decided to simply raise the the threshold for the time being.
We can decide later if we want to Box all the call …

Fix Clippy 1.87 large error

---

clippy.toml

Extension on <https://github.com/qdrant/qdrant/pull/6529>
May be good to keep track of this. If it ever gets resolved, we can drop the config.

Add comment for why we set custom large-error-threshold

---

lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
lib/segment/src/index/field_index/map_index/mod.rs

Fix regression in <https://github.com/qdrant/qdrant/pull/6495>
When having an immutable full text index based on mmap storage, its files were not included when creating a snapshot. I missed to properly list them. This fixes the problem.

Fix immutable mmap index files not included in snapshot

---

Cargo.toml
src/actix/api/snapshot_api.rs
src/common/snapshots.rs
tests/consensus_tests/test_partial_snapshot.py

This PR adds `recover_partial_snapshot_from` endpoint, that is required to allow cluster manager to use partial snapshot API.
__TODO:__

Add `recover_partial_snapshot_from` endpoint

---

lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/field_index/mod.rs
lib/segment/src/index/field_index/null_index/mmap_null_index.rs
lib/segment/src/index/query_estimator.rs
lib/segment/src/index/struct_payload_index.rs
lib/segment/src/segment/facet.rs
lib/segment/src/types.rs
lib/segment/tests/integration/payload_index_test.rs

Currently null index was only working for `is_empty=false` and `is_null=true` cases.
By making the index aware of the `max_point_offset` available, we can also make it work for `is_empty=true` and `is_null=false`.
This PR also builds the index even if the `IndexSelector` chooses RocksDB-based index. Now the null index is chosen regardless of appendable and on-disk parameters.
In some local manual tests, I can see about 1.8x difference between dev and branch. It is quite small (**~2.5ms vs ~1.4ms**) but noticeable
```shell
bfb -n 1000000 --dim 64
bfb -n 100000 --dim 64 --skip-create --int-payloads 1000 --max-id 1000000
```
then created the index through dashboard
```http
PUT /collections/benchmark/index
{
"field_name": "c",
"field_schema": {
"type": "integer",
"on_disk": true
}
}
```
then …

Use null index more

---

lib/collection/src/collection/mod.rs
tests/consensus_tests/test_force_delete_peer.py

Add new test for force deleting peer while transfers are ongoing. Currently, it looks like Qdrant doesn't abort shard transfers if the source peer is force deleted.

Abort transfer on force peer delete and add test for bug

---

lib/collection/src/collection_manager/segments_updater.rs
tests/basic_grpc_test.sh
tests/openapi/test_payload_operations.py

This PR changes the behavior of the point upsert API so that is always overwrite the existing payload value.
Previously, passing a None payload left the existing payload unchanged.
The main motivation for this change is the bug https://github.com/qdrant/qdrant/issues/6449 where gRPC and REST would behave differently due to different handling of empty vs optional values.
Now passing an empty value or no value at all will always result in clearing the existing payload.
This changed passed the `qdrant-client` congruence tests.

Always overwrite existing payload on upsert

---

Cargo.toml
lib/segment/src/spaces/simple_avx.rs
lib/segment/src/spaces/simple_sse.rs

Rust [v1.87](https://blog.rust-lang.org/2025/05/15/Rust-1.87.0/) has hit our CI.
There is one tiny thing left to fix.
```
error: unnecessary `unsafe` block
--> lib/segment/src/spaces/simple_sse.rs:14:5
|
14 |     unsafe {
|     ^^^^^^ unnecessary `unsafe` block
|
= note: `-D unused-unsafe` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_unsafe)]`
error: unnecessary `unsafe` block
--> lib/segment/src/spaces/simple_avx.rs:12:5
|
12 |     unsafe {
|     ^^^^^^ unnecessary `unsafe` block
error: could not compile `segment` (lib) due to 2 previous errors
```
https://blog.rust-lang.org/2025/05/15/Rust-1.87.0/#safe-architecture-intrinsics
```
Most std::arch intrinsics that are unsafe only due to requiring target features to be enabled are now callable in safe code …
```

Fix unecessary unsafe in Clippy 1.87

---

.github/workflows/coverage.yml

Coverage reports seems to be getting uploaded for `master` instead of `dev`
Logs don't have warnings or errors so the root cause is not 100% clear. But I suspect the problem is that we don't do enough commit info in `upload-and-merge` stage.  My hypothesis is that it's attaching the commit to the wrong branch because default fetch depth is 1 and hence it doesn't have full context and falls back to registering it as master branch. So this is similar to https://github.com/qdrant/qdrant/pull/6345

Fix dev branch coverage

---

lib/segment/src/vector_storage/async_raw_scorer.rs
lib/segment/src/vector_storage/query_scorer/custom_query_scorer.rs
lib/segment/src/vector_storage/query_scorer/multi_custom_query_scorer.rs
lib/segment/src/vector_storage/raw_scorer.rs

In the following code, `TInputQuery` conceptually is not a type paramater of the scorer, but rather of its constructor.
```rust
pub struct CustomQueryScorer<
TInputQuery: Query<DenseVector>, // <---
TStoredQuery: Query<TypedDenseVector<TElement>>,
// ...
> {
query: TStoredQuery,
_input_query: PhantomData<TInputQuery>,
// ...
}
impl<
TInputQuery: Query<DenseVector> + TransformInto</* ... */>, // <---
TStoredQuery: Query<TypedDenseVector<TElement>>,
// ...
> CustomQueryScorer<TInputQuery, TStoredQuery, /* ... */> {
pub fn new(query: TInputQuery, /* ... */) -> Self {
let query: TStoredQuery = query.transform(/* ... */).unwrap();
// ...
```
The first commit in this PR moves `TInputQuery` from `struct CustomQueryScorer` into `CustomQueryScorer::new`, and the same for `MultiCustomQueryScorer`, …

Remove some generics from scorer

---

lib/common/common/src/fixed_length_priority_queue.rs
lib/common/common/src/flags.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/search_context.rs

This PR implements graph healing algorithm, allowing HNSW index to reuse the old graph even if some of the vectors are updated or deleted.
This is done by the new graph search function `GraphLayersBuilder::search_shortcuts_on_level` which finds shortcut links around the deleted points. (check it's documentation comment for more info)
The main graph building is still done in two stages (migrate phase, and main phase).
But in this PR,
- Point migration not just copies links as-is, but it could replace links to deleted nodes with newly found shortcuts around them..
- Migration is done in parallel, similar to the main phase.
By default, this feature is hidden behind the new `hnsw_healing` feature flag.
The threshold is 10% of missing points (if more than that, then the old index is …

HNSW healing

---

tests/consensus_tests/test_shard_wal_delta_transfer.py

Attempts to fix <https://github.com/qdrant/qdrant/issues/6539>
Fixes flakiness in the WAL delta transfer tests.
In the test, transfers are very short. The transfer may already be completed when we're waiting on a specific state to synchronize the test. This was causing flakiness.
Instead of waiting for specific shard transfer progress, just wait for any transfer to be active.
I can't be 100% this will fix flakiness in CI, but I've been seeing good results locally. Over 100 runs I now have 0 failures. If it still appears to be flaky, we can take further action.

Fix WAL delta transfer flakiness

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs

Seems to fix Crasher, will let CI chew on it.
This PR makes sure we handle the on going proxy segments when failing with any error to build a new optimized segment.

Always run cancellation handle for interrupted optimizations

---

tests/consensus_tests/test_consensus_compaction.py

Related to <https://github.com/qdrant/qdrant/issues/6531>
Potentially improves reliability with `wait=true` when setting cluster metadata.

Wait when putting collection metadata

---

lib/gridstore/src/bitmask/gaps.rs

Running `cargo bench --all` fails with
```
error[E0308]: mismatched types
--> lib/gridstore/src/bitmask/gaps.rs:285:25
|
285 |           ) -> RegionGaps {
|  _________________________^
286 | |             if leading + trailing >= region_size_blocks {
287 | |                 return RegionGaps::all_free(region_size_blocks);
...   |
298 | |         }
| |_________^ expected `RegionGaps`, found `()`
error[E0061]: this function takes 3 arguments but 4 arguments were supplied
--> lib/gridstore/src/bitmask/gaps.rs:606:13
|
606 |             RegionGaps::new(1, 2, 3, region_size_blocks),
|             ^^^^^^^^^^^^^^^          ------------------ unexpected argument #4 of type `u16`
|
note: associated function defined here
--> lib/gridstore/src/bitmask/gaps.rs:21:12
|
21  |     pub fn new(
| …
```

Fix compilation of bench

---

Cargo.toml
lib/segment/Cargo.toml
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
lib/segment/src/segment_constructor/rocksdb_builder.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/src/types.rs
lib/segment/src/vector_storage/common.rs
lib/segment/src/vector_storage/dense/mod.rs
lib/segment/src/vector_storage/mod.rs
lib/segment/src/vector_storage/multi_dense/mod.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs
lib/segment/src/vector_storage/raw_scorer.rs
lib/segment/src/vector_storage/sparse/mmap_sparse_vector_storage.rs
lib/segment/src/vector_storage/sparse/mod.rs
lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/vector_storage_base.rs

Depends on <https://github.com/qdrant/qdrant/pull/6569>
Feature flag usage of RocksDB in our vector storage (dense, multi dense and sparse). For now, the flag will remain enabled by default.
```bash
cargo build
cargo build --no-default-features --features parking_lot,web
```
Note that disabling the feature flag does not remove the dependency at compile time yet. It is still being used in a few other places, which will be feature flagged separately. This is just one of the necessary steps forward towards completely removing RocksDB at a future point in time.

Add RocksDB feature flag to vector storage

---

lib/segment/src/id_tracker/id_tracker_base.rs
lib/segment/src/id_tracker/mod.rs
lib/segment/src/id_tracker/simple_id_tracker.rs
lib/segment/src/segment_constructor/rocksdb_builder.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs

Depends on <https://github.com/qdrant/qdrant/pull/6566>
Feature flag usage of RocksDB in our ID trackers.
```bash
cargo build
cargo build --no-default-features --features parking_lot,web
```

Add RocksDB feature flag to ID trackers

---

.github/workflows/integration-tests.yml
tests/consensus_tests/test_force_delete_peer.py
tests/consensus_tests/utils.py

~I did these these~:
- ~Flipped the initial vs later upsert count to avoid extending test duration. Upserting more points in the 2nd upsert ensures that we catch the transfer while it's still ongoing~ 
- ~Solving [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) by returning last transfers after the wait fn~
Simplified the test so we don't need `get_collection_cluster_info` or `wait_for_collection_shard_transfers_count` which depend on transient states and lead to flaky behaviour. Original intention was to ensure that if peer is force deleted while transfers are ongoing, any ongoing transfers from/to the peer must be aborted.

Fix force delete peer flaky test

---

lib/collection/src/operations/verification/query.rs
lib/segment/src/types.rs
tests/openapi/test_strictmode.py

In a previous [PR](https://github.com/qdrant/qdrant/pull/6473), fullscan was prohibited in strict mode when using `search_allow_exact=false`.
However we want to allow querying when no global HNSW is present if the query leverage a multitenant HNSW based payload index.

Strict mode allows fullscan for multitenant payload index

---

lib/collection/src/collection/snapshots.rs
lib/collection/src/operations/types.rs
lib/collection/src/shards/replica_set/execute_read_operation.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/partial_snapshot_meta.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/storage/src/content_manager/conversions.rs
lib/storage/src/content_manager/errors.rs
src/actix/api/snapshot_api.rs
src/actix/helpers.rs
src/common/snapshots.rs
tests/consensus_tests/test_partial_snapshot.py

This PR adds
- `partial_snapshot_recovery_lock`
- which only allows recovering a single partial snapshot request at a time
- and `partial_snapshot_read_lock`
- which explicitly rejects read operations while partial snapshot recovery is in progress
__TODO:__
- _will be implemented in a separate PR_

Add partial snapshot recovery and read operation locks

---

Cargo.lock
Cargo.toml

Routine update of the `wal` crate following some updates there mostly from @jayantpranjal0
This enables us to cut some dependency duplication.

Bump wal crate to prune dependencies

---

docs/redoc/master/openapi.json
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/replica_set/partial_snapshot_meta.rs
lib/collection/src/shards/replica_set/snapshots.rs
lib/collection/src/shards/replica_set/telemetry.rs
lib/collection/src/shards/telemetry.rs
tests/openapi/test_service.py

This PR adds two partial snapshot fields to replica set telemetry:
- `ongoing_create_snapshot_requests ` – counts concurrent create partial snapshot requests
- `recovery_timestamp ` – tracks UNIX timestamp of the last successfully recovered partial snapshot
These fields are needed so that cluster-manager can apply limits on partial snapshot creation/recovery.

Add `partial_snapshot_create_requests` and `*_recovery_timestamp` to telemetry

---

lib/segment/src/index/hnsw_index/hnsw.rs

The PR #6543 (commit https://github.com/qdrant/qdrant/pull/6543/commits/1481fd086ec1e3a128d0f4a61446212fd587e806) introduced a blunder typo: the healing is *enabled* by default, and `QDRANT__FEATURE_FLAGS__HNSW_HEALING=true` *disables* it. The expected behavior is other way around.
This PR fixes it.

Invert feature_flags.hnsw_healing

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to 1.14.2-dev for the [Qdrant 1.14.1](https://github.com/qdrant/qdrant/pull/6584) release.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/6411>.

Bump dev version to 1.14.2-dev

---

lib/sparse/src/index/tests/hw_counter_test.rs

Tackling https://github.com/qdrant/qdrant/issues/6231
There is a common issue when testing sparse vector search with:
- randomly generated data
- randomly generated query vector
There is no guarantee that there will be at least `top` stored vectors with overlapping indices with the query.

Fix flaky test_hw_counter_for_plain_sparse_search

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs
tools/missed_cherry_picks.sh

```
* https://github.com/qdrant/qdrant/pull/6458 - Speed up WAL-delta shard transfer significantly via batching and more careful synchronization
* https://github.com/qdrant/qdrant/pull/6462 - Improve GPU indexing speed for payload-related HNSW links, reuse GPU resources
* https://github.com/qdrant/qdrant/pull/6444, https://github.com/qdrant/qdrant/pull/6495, https://github.com/qdrant/qdrant/pull/6503, https://github.com/qdrant/qdrant/pull/6587 - Greatly improve payload index load time by replacing RocksDB with mmaps as persistence layer
* https://github.com/qdrant/qdrant/pull/6446 - Make GridStore flush slightly faster, update gaps in batch
* https://github.com/qdrant/qdrant/pull/6510 - Optimize GridStore reads, tell the kernel we use random reads
* …
```

Bump version to v1.14.1

---

Cargo.lock
lib/posting_list/Cargo.toml
lib/posting_list/src/builder.rs
lib/posting_list/src/iterator.rs
lib/posting_list/src/lib.rs
lib/posting_list/src/posting_list.rs
lib/posting_list/src/tests.rs
lib/posting_list/src/value_handler.rs
lib/posting_list/src/view.rs
lib/posting_list/src/visitor.rs
lib/segment/Cargo.toml
lib/segment/src/index/field_index/full_text_index/compressed_posting/compressed_chunks_reader.rs
lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/old_mmap_postings.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/tests.rs
lib/segment/src/index/field_index/full_text_index/mod.rs
lib/segment/src/index/field_index/full_text_index/posting_list.rs
lib/segment/src/index/field_index/full_text_index/postings_iterator.rs

builds on top of #6528 
This PR:
- adds a few improvements to generic posting list
- swaps the implementation for a compressed posting list in full text index
- add hw measurement (in the next PR)
- remove previous implementation (since the compatibility test depends from this, we can postpone it to do it later)

Full text index with generic posting list

---

lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/postings_iterator.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs

Builds on top of #6486 
This is merely a refactoring to allow (with less changes) introducing phrase filtering as a separate way to use the full-text index.

[phrase match] `ParsedQuery` as enum

---

lib/posting_list/src/lib.rs
lib/posting_list/src/posting_list.rs
lib/posting_list/src/value_handler.rs
lib/posting_list/src/view.rs
lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mmap_postings.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/tests.rs
lib/segment/src/index/field_index/full_text_index/mod.rs
lib/segment/src/index/field_index/full_text_index/positions.rs

Builds on top of #6617
Make `MmapPostings` generic over the stored value along with the ids. 
To achieve this, it was necessary to create a trait specific to full text index (`MmapPostingValue`), so that it is still compatible with previous implementation, but can also store positions if the right type is used.

[phrase match] Generic mmap postings

---

lib/common/common/src/ext.rs
lib/segment/src/index/hnsw_index/entry_points.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/struct_payload_index.rs

H&M benchmark: https://github.com/qdrant/vector-db-benchmark/actions/runs/14785548595
--- 
ToDo:
More benchmarks in https://github.com/qdrant/qdrant/pull/6571

Attempt to speedup additional links construction by measuring sub-graph connectivity first

---

lib/common/common/src/flags.rs
lib/segment/benches/vector_search.rs
lib/segment/src/id_tracker/simple_id_tracker.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/src/vector_storage/dense/appendable_dense_vector_storage.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/tests/test_appendable_dense_vector_storage.rs

Similar to <https://github.com/qdrant/qdrant/pull/6579> with the same motivation, but for dense vector storage.
Actively migrate away from dense vector storage that still use RocksDB. On segment load, it is replaced with our appendable in-ram dense vector storage that is backed by mmaps.
The migration is behind a runtime feature flag (`migrate_rocksdb_vector_storage`). We'll likely enable it by default in one of the upcoming releases.

Migrate away from RocksDB based dense vector storage

---

lib/segment/src/index/field_index/full_text_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs

Converts `Vec<Option<usize>>` to `Vec<usize>`, using `0` as replacement for `None` to make immutable_inverted_index consistent with mmap_inverted_index

Remove option from immutable_inverted_index

---

lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/tests.rs

GPU vector storage tests involve a combinatorial explosion with all combinations of metric, element type, and dimension.
In total, numerous unnecessary tests slow down our GPU CI.
This PR removes the combinatorial explosion and defines exact test cases.
GPU test is green: https://github.com/qdrant/qdrant/actions/runs/15388832172/job/43293414171

Reduce gpu vector storage tests amount

---

lib/api/src/grpc/conversions.rs
lib/segment/src/fixtures/payload_fixtures.rs
lib/segment/src/types.rs
lib/segment/src/utils/maybe_arc.rs
lib/segment/src/utils/mod.rs

Fixes extremely high memory usage in Distance Matrix API on certain datasets with a large sample rate (>= ~50k).
Dev:
PR:

Fix enormous memory usage in Distance Matrix API on high sample size

---

lib/gridstore/src/blob.rs
lib/gridstore/src/gridstore.rs
lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index_builder.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/field_index/map_index/mutable_map_index.rs
lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs

Depends on <https://github.com/qdrant/qdrant/pull/6634>
Similar to <https://github.com/qdrant/qdrant/pull/6634>, this implements Gridstore as alternative storage backend for a payload index. This implements it for the full text index.

Add mutable full text payload index on top of Gridstore

---

lib/gridstore/src/blob.rs
lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/query_optimization/rescore_formula/value_retriever.rs
lib/segment/src/types.rs

Depends on <https://github.com/qdrant/qdrant/pull/6639>
Similar to <https://github.com/qdrant/qdrant/pull/6639>, this implements Gridstore as alternative storage backend for a payload index. This implements it for the geo index.

 Add mutable geo payload index on top of Gridstore

---

lib/segment/benches/fixture.rs
lib/segment/benches/hnsw_build_graph.rs
lib/segment/src/index/hnsw_index/gpu/gpu_graph_builder.rs
lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
lib/segment/src/index/hnsw_index/gpu/gpu_level_builder.rs
lib/segment/src/index/hnsw_index/gpu/mod.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/graph_links/serializer.rs
lib/segment/src/index/hnsw_index/graph_links/view.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/mod.rs
lib/segment/src/index/hnsw_index/tests/mod.rs

Currently, these two assumptions are scattered all over the `hnsw_index` module code:
- `level_m = if level == 0 { m0 } else { m }`
- `m0 = 2 * m`
This PR gathers them into a single place:
https://github.com/qdrant/qdrant/blob/6056b6d360ceb3b0d0e8fdd69c0f641563482b8d/lib/segment/src/index/hnsw_index/mod.rs#L18-L41

Introduce HnswM

---

lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/struct_payload_index.rs

Depends on <https://github.com/qdrant/qdrant/pull/6644>
Finalize the implementation of mutable payload indices on Gridstore.
A small PR that does two things:
1. bypass Gridstore index selector for boolean index, use existing mmap index because it's mutable already
2. remove RocksDB placeholder in Gridstore index selector
4. [x] Have you checked your code using `cargo clippy --all --all-features` command?

Finalize mutable payload index on Gridstore

---

lib/segment/src/index/hnsw_index/hnsw.rs

This PR changes the amount of points the healing algorithm tries to add.
Previously, when healing a graph node with $X$ alive neighbors and $Y$ deleted neighbors, the healing algorithm would add up to $Y$ new points to the node, total $X + Y$. Now, it will add up to $m_{level} - X$ new points, total $m_{level}$.
While the first approach was better on random datasets, it turned out it was worse on the laion dataset in the [`transform.py`] experiment.
Accuracy results before this change (`dev` 01e5fab9):
| dataset1 | dataset2 | change |
| -------: | -------: | -----: |
|   0.9828 |   0.9683 | -1.48% |
|   0.9668 |   0.9648 | -0.21% |
|   0.9805 |   0.9599 | -2.10% |
|   0.9517 |   0.9461 | -0.59% |
|   0.9850 |   0.9471 | -3.85% |
|   0.9854 |   0.9447 | -4.13% |
|   0.9878 |   0.9694 | …

migrate_point_on_level: heal up to level_m

---

lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
lib/segment/src/index/field_index/map_index/immutable_map_index.rs
lib/segment/src/index/field_index/map_index/mutable_map_index.rs

Don't expose the specialized load methods for the underlying storage, as it's unnecessary and is easily misused.
A tiny cleanup that didn't necessarily fit anywhere else.

Make `load_rocksdb` private everywhere

---

lib/posting_list/src/lib.rs
lib/posting_list/src/value_handler.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_inverted_index_builder.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/positions.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs

Builds on top of #6602 
Adds a `phrase_matching` bool param in the text index parameterization which controls how to store the tokens of each text.

[phrase matching] populate `point_to_doc` structures

---

docs/redoc/master/openapi.json
src/common/telemetry_ops/app_telemetry.rs

In telemetry, report whether the compile time RocksDB feature flag is set.

Report usage of RocksDB feature flag in telemetry

---

Cargo.lock
docs/redoc/master/openapi.json
lib/common/common/Cargo.toml
lib/common/common/src/flags.rs
src/common/telemetry_ops/app_telemetry.rs

With details level 1, it now reports runtime feature flags in telemetry:
If anonymize is set, we report no flags at all.

Expose runtime feature flags in telemetry

---

lib/segment/src/vector_storage/dense/memmap_dense_vector_storage.rs

Minor change, buffer writes when putting vectors on disk.

Buffer when writing into mmap dense vector storage

---

lib/collection/Cargo.toml

Fixes <https://github.com/qdrant/qdrant/pull/6646#discussion_r2140028298>
The `collection` crate has the `rocksdb` feature flag. But it doesn't propagate that to it's `segment` dependency.

In the collection crate, propagate the RocksDB feature flag

---

lib/gridstore/src/gridstore.rs
lib/gridstore/src/tracker.rs

This test was silently broken since it is marked as `ignore`d. At some point we removed the `Drop` implementation for gridstore, and this test wasn't updated. This PR fixes it

[gridstore] flush before dropping in ignored test

---

Cargo.lock

Fix CI [error](https://github.com/qdrant/qdrant/actions/runs/15698923226/job/44229405343) 
```
Run cargo build --tests --workspace --locked
Updating crates.io index
error: the lock file /home/runner/work/qdrant/qdrant/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```
I assume a missing rebase while merging the Dependabot PRs.

Fix CI cargo --locked build

---

lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/graph_layers_healer.rs
lib/segment/src/index/hnsw_index/graph_links.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/mod.rs

This PR updates lets the healing algorithm not just heal points, but also to insert back-links to the healed note into its neighbors.
Because this change is not compatible with the copy-on-write approach introduced in #6543, this PR switches to a more straightforward approach: copy the old graph into `GraphLayersHealer`, then heal the copy, then copy it back. So, most of the changes are refactoring, and the main change (which is small) is distilled in the last commit.
Supercedes #6624.
Accuracy measurement on [`transform.py`](https://github.com/qdrant/vector-db-benchmark/blob/93bd4214761525395959c020a6924be4eaa8c5fe/ansible/playbooks/roles/run-hnsw-indexing-transform/files/transform.py):
<table>
<tr>
<th>commit<br>
<th>dataset1<br>(avg)
<th>dataset2<br>(avg)
<th>diff<br>(avg)
<tr>
<td>dev …

Insert backlinks during healing

---

lib/segment/src/common/rocksdb_buffered_update_wrapper.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/src/vector_storage/dense/simple_dense_vector_storage.rs
lib/segment/src/vector_storage/multi_dense/simple_multi_dense_vector_storage.rs
lib/segment/src/vector_storage/sparse/simple_sparse_vector_storage.rs

In <https://github.com/qdrant/qdrant/pull/6603>, <https://github.com/qdrant/qdrant/pull/6604>, <https://github.com/qdrant/qdrant/pull/6607> we migrated away from RocksDB based vector storage.
However, it forgot to update the storage type in the segment level configuration. Because of it Qdrant would still try to load the old configuration even though it was already migrated.
The logic for loading segments and their storages is nested deeply. I've implemented this in a way where I keep this nesting intact, while allowing the least amount of possible footguns.
In short: before we migrated each storage individually right after they were loaded. Now we load the full segment, and migrate each storage as part of the full segment. This allows us to access/adjust/store the segment configuration …

Fix vector storage migration error

---

Cargo.lock

CI got broken after rebasing and merging #6615: https://github.com/qdrant/qdrant/actions/runs/15780863701/job/44485920051.
Similar issue as in #6712: outdated `Cargo.lock`.
```
Run cargo build --bin qdrant --locked
Updating crates.io index
error: the lock file /home/runner/work/qdrant/qdrant/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
Error: Process completed with exit code 101.
```

Fix CI cargo --locked build (again)

---

lib/segment/src/vector_storage/raw_scorer.rs

This PR reduces the amount of boilerplate in `raw_scorer.rs` by replacing duplicate code with generics.
<table><tr><th>In <code>dev</code><th>In this PR<tr><td>
`raw_scorer_impl<_>`
`raw_scorer_byte_impl<_>`
`raw_scorer_half_impl<_>`
<td>
`raw_scorer_impl<TElementType, _>`
<tr><td>
`new_scorer_with_metric<_, _>`
`new_scorer_byte_with_metric<_, _>`
`new_scorer_half_with_metric<_, _>`
<td>
`new_scorer_with_metric<TElementType, _, _>`
<tr><td>
`raw_multi_scorer_impl<_>`
`raw_multi_scorer_byte_impl<_>`
`raw_multi_scorer_half_impl<_>`
<td>
`raw_multi_scorer_impl<TElementType, _>`
<tr><td>
`new_multi_scorer_with_metric<_, _>`
`new_multi_scorer_byte_with_metric<_, _>`
`new_multi_scorer_half_with_metric<_, _>`
<td>
`new_multi_scorer_with_metric<TElementType, _, _>`
<tr><td>745 lines<td>429 lines …

Generalize RawScorer construction 

---

docs/redoc/master/openapi.json
lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/positions.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/postings_iterator.rs
lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/tests/mod.rs
lib/segment/src/index/field_index/full_text_index/tests/test_congruence.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/index_selector.rs

Builds on top of #6670.
Two fixes for text index:
- Allow immutable text index with rocks-db storage
- Phrases with repeated tokens were being incorrectly handled when checking specific ids.

[phrase matching] Text index fixes

---

Cargo.lock

The `syn` crate is aggressively bumped to a newer version in our `Cargo.lock`.
For example, `cargo check --workspace` will create this same change.

Bump Cargo.lock, syn 2.0.104

---

Cargo.lock
lib/gridstore/src/gridstore.rs
lib/gridstore/src/page.rs

Most changes are related to a refactor to use const generics, which removes a bit of code duplication by drilling down a const generic.
Main change is to use the seq mmap in the `Gridstore::iter` function. Looks like we missed this when introducing the seq mmap

[gridstore] use seq mmap in iter

---

Cargo.lock
Cargo.toml
lib/collection/src/problems/unindexed_field.rs
lib/segment/Cargo.toml
lib/segment/src/types.rs
tests/openapi/test_strictmode.py

Builds on top of #6670 
Fixes the check for phrase index, so that strict mode allows phrase conditions when the text index has `phrase_matching` enabled

[phrase match | strict mode] Allow phrase condition when enabled in index

---

Cargo.lock
Cargo.toml
docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/conversions.rs
lib/api/src/grpc/proto/collections.proto
lib/api/src/grpc/proto/points.proto
lib/api/src/grpc/qdrant.rs
lib/collection/src/problems/unindexed_field.rs
lib/segment/Cargo.toml
lib/segment/src/data_types/index.rs
lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/positions.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/postings_iterator.rs
lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/tests/mod.rs
lib/segment/src/index/field_index/full_text_index/tests/test_congruence.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/query_optimization/condition_converter/match_converter.rs
lib/segment/src/payload_storage/condition_checker.rs
lib/segment/src/types.rs
tests/openapi/test_phrase_matching.py
tests/openapi/test_strictmode.py

- Adds a `Match::Phrase` variant to specify that a text must match by phrase.
- Adds a `phrase_matching` flag to the text index params so that text index registers positions.
Exposes it on rest and grpc

[phrase matching] expose phrase condition

---

lib/collection/src/common/snapshots_manager.rs

We'd like to be able to run back-ups from EKS pods that use role based authentication to our S3 buckets.  To support this, it seems qdrant must use the [AmazonS3Builder::from_env](https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.from_env) method to populate the builder with information from the environment per this feature request from the [object-store](https://github.com/apache/arrow-rs-object-store/issues/282) library.

Enable pod role based auth for s3 snapshots

---

Cargo.lock
lib/segment/Cargo.toml
lib/segment/src/index/field_index/full_text_index/tokenizers/mod.rs

Depends on #6762 
This PR removes [pinyin](https://de.wikipedia.org/wiki/Pinyin) conversion (eg 中国 => ["zhong", "guo"]) in our new multilingual tokenizer implementation. This fixes Chinese stopwords, because the tokens were in pinyin but our stopword list is written with Chinese letters (so basically we did `assert!(["是", "上去", ...].contains("shì"))`) 
Since Pinyin is just the romanized phonetic version of a Chinese word, we can use the original Chinese word without loosing information about the word. We even improve precision, because multiple Chinese words can map to the same Pinyin, e.g. 忘记 and 旺季 is both `["wang", "ji"]` (https://www.quora.com/Is-pinyin-romanization-a-bijective-map).

Fix Chinese stopwords

---

Cargo.lock
Cargo.toml
lib/segment/Cargo.toml
lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/full_text_index/tokenizers/japanese.rs
lib/segment/src/index/field_index/full_text_index/tokenizers/mod.rs
lib/segment/src/index/field_index/full_text_index/tokenizers/multilingual.rs

Implements the new multilingual tokenizer. In detail, this PR changes the following:
- Remove `multilingual-*` cargo features and enable multilingual by default
- Minor refactor of tokenizer to use `Cow<str>` for less cloning and easier string manipulation
- Integration of the new `MultilingualV2` tokenizer (renamed to `MultilingualTokenizer`)
- Less code duplication and other minor code improvements in the new `MultilingualTokenizer`
- End to end tests for stopwords in Japanese and Chinese tokenization test.
Due to lifetimes issues, caused by the underlying tokenization libraries, not all tokenization functions can benefit from clone-less `Cow` usage. This is kept as open TODO and could be investigated in a future PR.

Implement new multilingual tokenizer

---

lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mmap_postings.rs

In `dev`, loading a mmap-backed immutable index involved optimizing in the same way as when mutable turns immutable. This removed posting lists which have no items, and tries to reduce vocabulary size.
However, in the case of mmap->immutable, I don't think this is critical, and requires practically rebuilding the index on load. 
This PR, makes it possible to just turn the mmap structures into in-memory immutable ones by copying the content.

[text index] don't optimize when loading a mmap-backed immutable index

---

tests/openapi/test_discovery.py
tests/openapi/test_init_from_collection.py
tests/openapi/test_multi_vector.py
tests/openapi/test_multicollection_reco.py
tests/openapi/test_query_full.py

This PR removes all the leftover collections after running the `openapi` tests.

Deleted leftover test openapi collections

---

Cargo.lock
lib/collection/src/collection/search.rs
lib/collection/src/collection/sharding_keys.rs
lib/collection/src/operations/types.rs
lib/collection/src/shards/replica_set/execute_read_operation.rs
lib/collection/src/shards/replica_set/mod.rs
lib/collection/src/shards/resolve.rs
lib/segment/src/data_types/facets.rs
lib/storage/Cargo.toml
lib/storage/src/content_manager/consensus_manager.rs
lib/storage/src/content_manager/toc/collection_meta_ops.rs
src/consensus.rs
tests/consensus_tests/test_custom_sharding.py

Currently, new custom shards are initialized directly in `Active` state. In this case peer A (that did not receive custom shard replica) might expect replica to already exist on peer B, but peer B might still be initializing local replica of new custom shard. This leads to annoying errors during search while custom shard is being created.
This PR tries to mitigate this by initializing replicas in `Inititalizing` state (so that each peer would not assume that remote replicas are *instantly* available) and then switching each replica into `Active` state after it's initialized. …

Create new custom shards in `Initializing` state instead of `Active`

---

lib/segment/src/index/hnsw_index/graph_layers_healer.rs
lib/segment/src/index/hnsw_index/hnsw.rs

This PR updates `GraphLayersHealer::heal()` to use quantized vectors when available.
Found during profiling: when memory is low, regular vectors are getting evicted from the disk cache, and the healing process performs a lot of IOPS to retrieve vectors.
Since we use quantized vectors during the regular HNSW build, we'd need the similar for the healing.

GraphLayersHealer: use quantized vectors

---

Cargo.lock
lib/quantization/Cargo.toml
lib/quantization/benches/binary.rs
lib/quantization/build.rs
lib/quantization/cpp/avx2.c
lib/quantization/cpp/neon.c
lib/quantization/cpp/sse.c
lib/quantization/src/encoded_vectors_binary.rs
lib/quantization/tests/integration/empty_storage.rs
lib/quantization/tests/integration/test_binary.rs
lib/quantization/tests/integration/test_binary_encodings.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

This PR introduces an internal implementation for an upcoming feature: asymmetric binary quantization.
API PR is here: https://github.com/qdrant/qdrant/pull/6201
Motivation
Asymmetric quantization is a quantization where vector and query have different quantization algorithms. In this PR we introduce only one asymmetric option: BQ with query encoded as SQ.
Such methods allow for increased accuracy because a more accurate query produces a more accurate score. But scoring will be more complicated, as not each use case is suitable for asymmetric mechanisms.
An example of BQ quantization with SQ query is a [RaBitQ quantization](https://arxiv.org/pdf/2405.12497). We want to have something similar.
We don't use RaBitQ alg, encoding is different, and only scoring is the same. We have our vision …

Asymmetric binary quantization

---

lib/segment/src/index/query_optimization/condition_converter.rs

This `has_id` implementation is is a prime candidate for `AHashSet` because it tests the membership in a set of `u32`.
With some naive benchmarking, I get a 10% latency improvements on large distance matrix requests.
e.g.
```http
POST /collections/benchmark/points/search/matrix/pairs
{
"sample": 500,
"limit": 1000
}
```

Optimize has_id with ahash

---

lib/api/src/rest/models.rs
src/common/metrics.rs

Fixes #6793
Before we created a new prometheus-counter for each collection.
Now we create only one counter with multiple values which is the correct approach.
Linting verified using https://o11y.tools/metricslint/

Fix duplicates in hardware counter metrics

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/collection/src/update_handler.rs
lib/common/common/src/budget.rs

Currently if optimization panics, we can stuck in the loop of failures.
This PR should fix (improve) the endless loop problem.
Actual problem is
```
permit.set_on_release(move || {
// Notify scheduler that resource budget changed
permit_callback(false);
});
```
Which re-tries optimization unconditionally, even if permit was dropped because of panic.
What this PR does:
- Creates a flag to interrupt optimizer loop if optimization fails (this is not actually triggered in experiment, as loop exists before process can start, but still good to have as an extra safety)
- Changes behavior of `on_release` -> `on_manual_release`, to prevent triggering of the callback if permit was destroyed on error. Only explicit release for permission change counts now 
- Moves the check for available disk size …

add flag to break optimization loop on panic

---

Cargo.lock
Cargo.toml

Fixes building `dev`. `indicatif` 0.17.12 was published few days ago (and dependabot bumped dependency on `dev`), but [0.17.12 was yanked][0.18.0-release] (yesterday or today?) and 0.18.0 published instead.
[0.18.0-release]: https://github.com/console-rs/indicatif/pull/715

Upgrade `indicatif` to 0.18.0

---

lib/collection/src/shards/replica_set/mod.rs
lib/storage/src/dispatcher.rs
tests/consensus_tests/test_custom_sharding.py

Follow-up to #6778.
After #6778, we initialize custom shard replicas in `Initializing` state, and so when Qdrant returns response to the client, it does not yet guarantee that custom shard is ready to accept write requests. There will be a small delay while shards switch from `Initializing` into `Active` state and fully available.
This PR adds explicit `wait_for_state` check, so that we ensure all replicas are `Active` before returning response to the client. I've also very slightly tweaked `test_shard_consistency` test, so that it should cover this check as part of existing test. …

Wait until replicas are activated, when creating custom shards

---

lib/collection/src/shards/shard_holder/mod.rs
lib/storage/src/content_manager/consensus/persistent.rs

Something very minor I came across in our code base.
Change [`retain`](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.retain) to [`extract_if`](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.extract_if), in cases where we rely on whether retain has removed any items.
This prevents storing the original list length and checking if it has changed, by just checking whether `extract_if` had extracted any items at all.

Change retain to extract_if where we depend on retain result

---

lib/segment/benches/boolean_filtering.rs
lib/segment/benches/range_filtering.rs
lib/segment/benches/sparse_index_build.rs
lib/segment/src/fixtures/payload_context_fixture.rs
lib/segment/src/fixtures/sparse_fixtures.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/tests/mod.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/field_index/map_index/mutable_map_index.rs
lib/segment/src/index/field_index/numeric_index/mod.rs
lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/tests.rs
lib/segment/src/index/struct_payload_index.rs
lib/segment/src/segment_constructor/segment_builder.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/tests/integration/nested_filtering_test.rs
lib/segment/tests/integration/payload_index_test.rs

The main goal of this PR is to enable support for Gridstore in mutable payload indices unconditionally. It doesn't mean that Gridstore is always used, _yet_. It does mean Gridstore _can_ always be used. Along with this, some other necessary adjustments are made.
So, first, this enableds Gridstore on the mutable payload indices. Before, Gridstore was only supported when compiling without RocksDB.
Initialization of mutable payload indices has been adjusted. It prevents Gridstore from creating files on disk, even if we just try to load an existing index. Before, trying to load when no index exists results in loading an empty index instead, breaking our index.
Now we detect an index load failure when Gridstore is used. When no data exists on disk, we fail on load, and trigger index …

Enable Gridstore in mutable payload indices, don't eagerly create storage

---

lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/mod.rs
lib/segment/src/index/query_estimator.rs
lib/segment/src/index/struct_payload_index.rs
lib/segment/src/types.rs
lib/segment/src/utils/maybe_arc.rs
tests/openapi/test_filter_min_should.py

- Fix `total_conditions_count`, so it doesn't count nested must conditions as multiple conditions
- Change `PrimaryCondition` type to store external ids for: a) easier comparison with original condition b) avoiding mapping of the conditions, which might not be even used
- Change criteria for checking if filter consists only of primary conditions. Previous problem: `min_should` can generate more primary conditions then there are conditions defined (by duplicating conditions)

fix check for pure primary condition filter

---

lib/quantization/src/encoded_vectors.rs
lib/quantization/src/encoded_vectors_u8.rs

Minor fix to make sure we are reporting the correct vector IO count for scalar quantization.

Fix HW vector io for scalar quantization

---

Cargo.lock
Cargo.toml

For some obscure reason Dependabot has been ignoring this one for the past 5 months.
https://github.com/Peternator7/strum/blob/master/CHANGELOG.md

Bump strum 0.27.1

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/segment/src/index/field_index/bool_index/mod.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
lib/segment/src/index/field_index/map_index/immutable_map_index.rs
lib/segment/src/index/field_index/map_index/mutable_map_index.rs
lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
lib/segment/src/index/payload_config.rs
lib/segment/src/index/plain_payload_index.rs
lib/segment/src/index/struct_payload_index.rs

Depends on <https://github.com/qdrant/qdrant/pull/6812>
Fixes a storage compatibility problem in <https://github.com/qdrant/qdrant/pull/6812>. Now we store it in the same format as before, and put the new payload index types at the root level.
More details here: <https://github.com/qdrant/qdrant/pull/6812#issuecomment-3057928785>
Example payload config with these changes:
```json
{
"indexed_fields":{
"mybool":"bool",
"myint":"integer",
"sections":"keyword",
"tag":"keyword",
"text":{
"type":"text",
"tokenizer":"prefix",
"min_token_len":1,
"max_token_len":20,
"lowercase":true
}
},
"indexed_types":{
"mybool":[{"bool_index":{"mutable":"rocks_db"}},{"null_index":{"mmap":{"is_on_disk":true}}}],
"myint":[{"int_map_index":{"mutable":"rocks_db"}},{"int_index":{"mutable":"rocks_db"}},{"null_index":{ …
```

Fix storage: store index type in payload index config

---

lib/segment/src/index/field_index/mod.rs
lib/segment/src/index/query_estimator.rs
lib/segment/src/index/struct_payload_index.rs

Last fix in https://github.com/qdrant/qdrant/pull/6840 broke the cardinality estimation for HasId condition.
Instead of counting points which actually exist in segment, it used total number of points.
This PR returns previous behavior.

fix cardinality estimation for has id

---

lib/segment/src/index/field_index/bool_index/mod.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/field_index/null_index/mmap_null_index.rs
lib/segment/src/index/field_index/numeric_index/mod.rs
lib/segment/src/index/payload_config.rs

Only null and bool mmap indices are mutable, but #6812 marked all mmap indices as mutable 🙈

Review mutability of mmap indices

---

lib/collection/src/operations/vector_ops.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/immutable_inverted_index.rs

We know based on experience that `ahash` is much faster for `u32` keys.
This PR migrates the remaining usages of the std hasher.

Optimize more ahash for u32

---

lib/collection/src/collection/mmr.rs
lib/collection/src/common/diagonal_matrix.rs
lib/collection/src/common/mod.rs
lib/collection/src/common/symmetric_matrix.rs

Builds on #6797 
Optimizes the diagonal matrix used in MMR to only store half of the data in a single, flattened vector.

[MMR] Optimize SymmetricMatrix

---

lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/payload_config.rs
lib/segment/src/index/struct_payload_index.rs

Depends on <https://github.com/qdrant/qdrant/pull/6837>
We've implemented <https://github.com/qdrant/qdrant/pull/6810> and <https://github.com/qdrant/qdrant/pull/6812> alongside each other. This PR makes the two compatible.
Note that this is only relevant for when `migrate_rocksdb_payload_indices` is explicitly set. Qdrant running the default configuration is not affected.

Fix naive payload migration with persisted storage type

---

docs/redoc/master/openapi.json
lib/common/common/src/flags.rs
lib/common/memory/src/fadvise.rs
lib/segment/src/common/mod.rs
lib/segment/src/index/field_index/bool_index/mmap_bool_index.rs
lib/segment/src/index/field_index/bool_index/mod.rs
lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/immutable_inverted_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/mmap_inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/mod.rs
lib/segment/src/index/field_index/full_text_index/mmap_text_index.rs
lib/segment/src/index/field_index/full_text_index/mutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/text_index.rs
lib/segment/src/index/field_index/geo_index/immutable_geo_index.rs
lib/segment/src/index/field_index/geo_index/mmap_geo_index.rs
lib/segment/src/index/field_index/geo_index/mod.rs
lib/segment/src/index/field_index/geo_index/mutable_geo_index.rs
lib/segment/src/index/field_index/histogram.rs
lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/field_index/map_index/immutable_map_index.rs
lib/segment/src/index/field_index/map_index/mmap_map_index.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/field_index/map_index/mutable_map_index.rs
lib/segment/src/index/field_index/null_index/mmap_null_index.rs
lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/mod.rs
lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
lib/segment/src/index/struct_payload_index.rs

This PR is now a collection of:
- https://github.com/qdrant/qdrant/pull/6810
- https://github.com/qdrant/qdrant/pull/6837 (will drop when [#6860](https://github.com/qdrant/qdrant/pull/6860) is merged)
- https://github.com/qdrant/qdrant/pull/6847
---
Depends on <https://github.com/qdrant/qdrant/pull/6812>
A naive implementation for migrating payload indices based on RocksDB into Gridstore.
Rather than carefully migrating, this simply builds the payload indices from scratch.
Naive migration is triggered when a RocksDB based payload index is loaded and the `migrate_rocksdb_payload_indices` runtime feature flag is set.
In a later PR we can dive into actually migrating. I'm quite sure a proper migration will be beneficial on large deployments.
Some other changes:
- restructure payload index …

Naive migration of payload indices from RocksDB to Gridstore

---

lib/collection/src/shards/local_shard/mod.rs

TL;DR:
- I've noticed that all latency spikes that we observe in RW-seg cluster follow the same pattern
- following the logs/pattern I found that we call `std::thread::JoinHandle::join` ***on the async runtime*** during partial snapshot recovery
- I suspect, that the spikes are caused by this "blocking call on async runtime"
- this PR implements the most trivial workaround, so that we can quickly merge it and see if it fixes the issue on RW-seg cluster

Fix read latency spikes during partial snapshot recovery

---

lib/segment/src/index/payload_config.rs
lib/segment/src/index/struct_payload_index.rs

Fix two problems in payload index migrations that has recently been merged in <https://github.com/qdrant/qdrant/pull/6810>.
The first fix is in configuration handling. This config describes the exact type of payload index being used, it is used when loading an index. The implementation was saving changes a bit too aggressively, saving an incomplete configuration in some cases. It must only persist at the end based on a dirty flag. It looks like we lost this logic due to a bad conflict resolution.
The second fix is to make payload index loading more robust. It ensures that we still open RocksDB if any of the indices on disk still relies on it, no matter if we enable migrations or not. Without the fix loading could fail resulting in a dummy segment.
Here's a case that failed before, which …

Fix payload index migration config and edge case handling

---

lib/segment/src/index/struct_payload_index.rs

Delete RocksDB files for payload indices if they are not in use anymore.
More specifically:
- if we open a RocksDB instance if any index still relied on it
- we migrate (all) indices away from RocksDB
- RocksDB is not in use anymore
- we now explicitly delete its files
This is not necessary as a new optimization run will delete these files implicitly. But it's nice to clean up garbage. 🗑️🧻
Files before migration, still using RocksDB:
```bash
$ ls -lh storage/collections/test/0/segments/1078a4b4-48cb-49f5-8dbd-0e6896ab9fbf/payload_index
total 4,0M
-rw-r--r-- 1 130K jul 15 10:38 000014.sst
-rw-r--r-- 1 3,4M jul 15 10:38 000015.sst
-rw-r--r-- 1 305K jul 15 10:38 000016.sst
-rw-r--r-- 1    0 jul 15 10:38 000031.log
-rw-rw-r-- 1  451 jul 15 10:38 config.json
-rw-r--r-- 1   16 jul 15 10:38 …
```

After payload index migration, delete RocksDB files

---

lib/collection/src/collection/collection_ops.rs
lib/collection/src/collection/mod.rs
lib/collection/src/collection/resharding.rs
lib/collection/src/collection/shard_transfer.rs
lib/collection/src/shards/shard_holder/resharding.rs
lib/collection/src/shards/transfer/mod.rs
lib/storage/src/content_manager/toc/collection_meta_ops.rs

Fixing the bug found in chaos testing debug cluster (reproduced in a test [here](https://github.com/qdrant/cluster-manager/pull/345)). It led to a scenario where all the replicas of a shard get marked as Dead on all nodes and they can't recover from each other since every replica is Dead. The root cause was  exactly what I hypothesised [here](https://github.com/qdrant/qdrant/pull/6771#issuecomment-3013167593). 
Put simply if you:
- Have resharding shard streaming transfer between: n1 shard 3 -> n2 shard 2
- Then if node n0 dies and also had an `Resharding/ReshardingScaleDown` replica (say shard 1), we abort resharding and abort any streaming resharding transfers related to n0 (but we don't abort the above mentioned n1:3 -> n2:2 transfer)
- When the n1:3 -> n2:2 is finished, every node …

Fix bug that causes all replicas to die if node is restarted during resharding

---

lib/collection/src/collection/mmr/lazy_matrix.rs
lib/collection/src/collection/mmr/maximum_marginal_relevance.rs
lib/collection/src/collection/mmr/mod.rs

Another optimization for MMR.
MMR is usually used as a reranker with more candidate points than selected points.
Without this PR, MMR computes the entire similarity matrix by calculating `m*m/2` similiarites, where m=# of candidates. 
However, what we actually need to compute is `m*n/2` similarities, where m=# of candidates, and n=limit.
For cases where there are many candidates and small limit, this improves performance more dramatically, for example:
| Case | `dev` (similarities, request timing) | PR (similarities, request_timing) |
| --- | --- | --- |
| `limit=10`, `candidates_limit=1000` | 1M, 44.8ms | 10k, 16.1ms | 
| `limit=10`, `candidates_limit=500` | 250k,  19.7ms | 5k, 12.4ms | 
| `limit=10`, `candidates_limit=100` | 10k, 9.5ms | 1k, 9.0ms | 
Notice that PR is a bit slower on …

[mmr] compute similarities lazily

---

lib/collection/src/collection/mmr/maximal_marginal_relevance.rs
lib/collection/src/collection/mmr/mod.rs
lib/collection/src/collection/query.rs
lib/collection/src/shards/local_shard/query.rs

Fixes:
- `score_threshold` handling: we now only handle it during nearest neighbors search step
- score in the output corresponds to the similarity to the query, already postprocessed

MMR with postprocessed score

---

lib/common/memory/src/checkfs.rs

MUSL builds currently fail because `FsType::from_magic(..)` expects a different number type. :man_shrugging: 
Failure example: https://github.com/qdrant/qdrant/actions/runs/16371351831/job/46260244211#step:7:899

Fix checkfs in MUSL builds

---

lib/common/memory/src/chunked_utils.rs
lib/common/memory/src/mmap_type_readonly.rs
lib/gridstore/src/page.rs
lib/segment/src/vector_storage/dense/mmap_dense_vectors.rs

It turns out `MADV_POPULATE_READ` performance is influenced by the `MADV_RANDOM` and `MADV_SEQUENTIAL` flags.
Obvious in hindsight, but still surprising that the kernel won't enable readahead unconditionlly given that it knows that it will be reading the whole file.
```c
// Slow, many 4K IOPS
madvise(ptr, size, MADV_RANDOM);
madvise(ptr, size, MADV_POPULATE_READ);
```
```c
// Fast, as uses large readahead
madvise(ptr, size, MADV_SEQUENTIAL);
madvise(ptr, size, MADV_POPULATE_READ);
```
Since a lot of our files mmaped twice (for sequential and for random), the fix in this PR is trivial: let `populate()` use the sequential mmap if it available.
Fixed:
- Dense vector storages, except deleted flags
- Gridstore pages (used in sparse vectors)
Some mmaps are not duplicated, so these are not …

MADV_POPULATE_READ on sequential mmaps

---

lib/collection/src/collection/mmr/lazy_matrix.rs
lib/common/common/src/mmap_hashmap.rs
lib/segment/src/index/field_index/map_index/mod.rs

MmapHashMap had a problem with Entry alightment, in case if key value was u128. It required 16bit alightment, but
storage assumed, apparently, that nothing can need more than 8 bit alignment.
This PR introduces 2 unit tests + fix.
Fix is another alignment block inside MmapHashmap. If Required alignment is <8, there are no change and format exactly same as before. If required alignment >8, we put extra empty bytes __before__ bucket offsets, so that
(new_alignment + buckets) % ALIGNMENT = 0.
Compatibility: luckily (thanks to @xzfc) bucket offset is stored explicitly in the header of the file.
So the same code should be able to read both: files with and without offset, even if old files were created for u128 key.

UUID index bug

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

```
* https://github.com/qdrant/qdrant/pull/6931 - gRPC HealthCheck method now works without authentication, making it consistent with REST methods.
* https://github.com/qdrant/qdrant/pull/6923 - Use populate storage components with `MADV_SEQUENTIAL` for better IO performance on indexing
* https://github.com/qdrant/qdrant/pull/6932 - Fix point shard routing broken in 1.15 (**Points created in 1.15.0 in multi-shard collections might not behave properly on updates!**)
* https://github.com/qdrant/qdrant/pull/6903 - Fix compile error in MUSL builds
* https://github.com/qdrant/qdrant/pull/6910 - Fix panic in `/metrics` on empty collection data
* https://github.com/qdrant/qdrant/pull/6916 - Fix UUID index storage, resulted in missing filter results.
```

bump version to v1.15.1

---

Cargo.lock
Cargo.toml
lib/collection/Cargo.toml
lib/collection/src/hash_ring.rs
lib/common/common/src/lib.rs
lib/common/common/src/stable_hash.rs
lib/segment/src/types.rs

Follow-up for #6932. A cleaned up/more explicit version.
For hashes to be stable, we need two things: a stable `Hash` implementation for our types, and a stable `Hasher` implementation.
The default `Hasher` used in the `hashring` crate is `SipHash24`. This PR makes it explicit.
We can't assume that `Hash` is stable neither for types from `std` [\[1\]](https://doc.rust-lang.org/std/hash/trait.Hash.html#portability), nor from third-party crates. Thus, this PR implements hashes by hand via the new trait `StableHash`, without depending on stdandard or third-party implementations. The new `StableHashed` adapter is provided to allow using the `StableHash` implementation in contexts where `Hash` is expected, e.g., in the `hashring` crate. The default `Hash` implementation is kept unstable, …

Introduce StableHash

---

lib/collection/src/operations/universal_query/formula.rs
lib/segment/src/types.rs

`DateTimeWrapper` could not parse it's own `to_string` output. Oops. Fixed now.

Fix `DateTimeWrapper` parsing

---

lib/segment/src/index/field_index/map_index/immutable_map_index.rs
lib/segment/src/index/field_index/map_index/mmap_map_index.rs
lib/segment/src/index/field_index/map_index/mod.rs
lib/segment/src/index/field_index/map_index/mutable_map_index.rs

Similar to #6685, swaps the container of ids per value in mutable map index from `BTreeSet<u32>` to `RoaringBitmap`.
This is not too noticeable on "normal" workloads, but when there is many values per point, it does provide a bit of advantage on insertion. 
For example, with the following command (100k points):
```
bfb -n 300000 --max-keywords 1000 --keywords 10000  --search --match-any 900
```
This is the performance improvement (edit: reran with release build of bfb and perf builds of qdrant)
| build | final upsert RPS | total upsert time | median search RPS | 
| --- | --- | --- | --- |
| dev (perf build) | 1685 | 00:02:57 | 526
| PR (perf build) | 3159 | 00:01:34 | 525
And, with just 1 keyword per point
```
bfb -n 300000 --keywords 10000 --search --match-any 900
```
| build | final …

[map index] use roaring bitmap in mutable map index

---

lib/collection/src/collection_manager/holders/segment_holder.rs
lib/segment/src/data_types/segment_manifest.rs
lib/storage/src/content_manager/conversions.rs
lib/storage/src/content_manager/errors.rs
src/actix/api/snapshot_api.rs
src/actix/helpers.rs
src/common/snapshots.rs
tests/consensus_tests/test_partial_snapshot.py

Small optimization for partial snapshots: instead of creating an "empty" partial snapshot, when snapshot manifest contains no changes (e.g., when snapshot manifest provided by "read" replica is the same as current data on "write" replica), we simply return `NOT MODIFIED` response and "short-circuit" the whole recovery.

Avoid creating partial snapshot if snapshot manifest contains no changes

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Looks like we missed doing it for `1.15.*` and [tests in CM were failing](https://github.com/qdrant/cluster-manager/pull/352) because of min version requirements after recent partial snapshot improvements.
Bumps the development version to 1.15.2-dev for the [Qdrant 1.15.1](https://github.com/qdrant/qdrant/pull/6934) release.
Follows the pattern of <https://github.com/qdrant/qdrant/pull/6588>

Bump dev version to 1.15.2-dev

---

lib/segment/src/index/field_index/full_text_index/tokenizers/config.rs
lib/segment/src/index/field_index/full_text_index/tokenizers/mod.rs

Depends on #6891 
This is a nice-to-have refactor of token processing, which centralizes the processing of all tokenizer options in a single place which applies all the configured ones.

Refactor token processing in `TokenizerConfig`

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/src/grpc/proto/points.proto
lib/api/src/grpc/qdrant.rs
lib/api/src/rest/schema.rs
lib/segment/src/index/query_optimization/rescore_formula/parsed_formula.rs

We had restricted `midpoint` to be in the range (0,1) for the sake of gauss and exp decay. Linear decay can actually accept in the range [0,1]. This PR enables this possibility

[decay formula] allow [0,1] range for midpoint in lin_decay

---

Cargo.lock
Cargo.toml
lib/collection/src/operations/point_ops.rs
lib/segment/src/index/field_index/full_text_index/mod.rs
lib/segment/src/index/field_index/full_text_index/tokenizers/config.rs
lib/segment/src/index/field_index/full_text_index/tokenizers/mod.rs
src/common/inference/bm25.rs
src/common/inference/inference_input.rs
src/common/inference/local_model.rs
src/common/inference/mod.rs
src/common/inference/service.rs

Supersedes #6893 and #6904
Depends on https://github.com/qdrant/qdrant/pull/6891
Implements Bm25 by parsing the inference object's options.
A possible request could look like this:
```json
{
"query": {
"model": "qdrant/bm25",  // Must be set but value can be arbitrary.
"text": "Some input to embedd with bm25",
"options": {
"use_bm25": true,        // Required to parse this options as BM25 configuration.
"k": 1.0,                // Optional hyperparameters. Same for `b` and `avg_len`.
"tokenizer": "word",     // Optional 
"lowercase": true       // Optional
}
},
"using": "sparse"
}
```
In case the option "use_bm25" is enabled but the configuration is invalid, a detailed error is returned:
```
{
"error": "Wrong input: Invalid BM25 config: Error(\"unknown variant `ord`, expected one of …
```

[Bm25] Execution implementation

---

lib/segment/src/common/buffered_dynamic_flags.rs
lib/segment/src/index/field_index/bool_index/mod.rs
lib/segment/src/index/field_index/bool_index/mutable_bool_index.rs
lib/segment/src/index/field_index/field_index_base.rs
lib/segment/src/index/field_index/index_selector.rs

Builds on top of #6954 
Same approach implemented in #6954, but for bool index. Since bool index also used unbuffered updates, this PR switches their flags component to leverage `BufferedDynamicFlags`.

Buffered mutable bool index

---

docs/redoc/master/openapi.json
lib/collection/src/operations/types.rs
src/common/metrics.rs
src/common/telemetry_ops/cluster_telemetry.rs
tests/consensus_tests/test_custom_sharding.py

`test_create_shard_key_read_availability` is dependent on "peer metadata" to propagate through cluster, so this PR exposes peer metadata in telemetry and add explicit `wait_for_peer_metadata` (instead of simple `sleep`) to the test.

Fix `test_create_shard_key_read_availability` flakiness

---

lib/segment/src/vector_storage/chunked_vectors.rs
lib/segment/src/vector_storage/quantized/mod.rs
lib/segment/src/vector_storage/quantized/quantized_ram_storage.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

This PR changes implementation for RAM quantization storage.
Previously, RAM quantization storage was declared as a trait impl:
```
impl quantization::EncodedStorage for ChunkedVectors<u8> {
...
}
```
Now, new `struct QuantizedRamStorage` was introduced:
```
pub struct QuantizedRamStorage {
vectors: ChunkedVectors<u8>,
}
impl quantization::EncodedStorage for QuantizedRamStorage {
...
}
```
All implementations are copied without changes to the logic.
This change is required for the appendable quantization storage, where I'm goig to add additional fields into `QuantizedRamStorage` to describe snapshot file for this data.

Wrap quantization chunked vectors in a separate structure

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to 1.15.3-dev for the https://github.com/qdrant/qdrant/pull/7012 release.
Follows the pattern of https://github.com/qdrant/qdrant/pull/6955

Bump dev version to 1.15.3-dev

---

lib/segment/src/index/field_index/index_selector.rs
lib/segment/src/index/field_index/numeric_index/immutable_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/mmap_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/mod.rs
lib/segment/src/index/field_index/numeric_index/mutable_numeric_index.rs
lib/segment/src/index/field_index/numeric_index/tests.rs
lib/segment/src/index/struct_payload_index.rs

A [stack of PRs](https://github.com/qdrant/qdrant/milestone/34) with the goal of simplifying our payload index internals.
Rather than having a two stage approach - open and load a payload index - this changes to a single stage approach. This now opens and loads payload indices in a single function call.
By using a single stage, we eliminate a bunch of intermediate states we had to keep before. It required explicit handling of this using `Option`s in all payload indices, which is error prone. This now allow us to remove the intermediate variants, simplifying state handling across all our payload indices. It now follows the RAII philosophy.
The full stack of PRs kept all logic in payload indices the same, except that it merged opening and loading into a single function. No changes have been …

Open and load numeric payload indices in single stage

---

lib/quantization/src/encoded_storage.rs
lib/quantization/src/encoded_vectors.rs
lib/quantization/src/encoded_vectors_binary.rs
lib/quantization/src/encoded_vectors_pq.rs
lib/quantization/src/encoded_vectors_u8.rs
lib/segment/src/segment/entry.rs
lib/segment/src/vector_storage/quantized/quantized_mmap_storage.rs
lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs
lib/segment/src/vector_storage/quantized/quantized_ram_storage.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

This PR adds a `flush` function into quantization storage and integration of flush in the segment.
Because dev has no appendable quantization storage yet, all flush implementations are empty.

Quantization flusher

---

lib/segment/src/index/field_index/index_selector.rs

Fix some clippy warnings when linting with:
```bash
cargo clippy --workspace --all-targets --no-default-features -- -D warnings
```
This came up while implementing <https://github.com/qdrant/qdrant/milestone/34>.

Fix clippy warnings when compiling without RocksDB feature flag

---

docs/redoc/master/openapi.json
openapi/openapi-main.ytt.yaml

read `consistency` query param is already there and can be used but it was not part of openapi spec.
This adds it to openapi in the same way as other read operations

add consistency param for count api in openapi

---

lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/mod.rs
lib/segment/src/index/plain_vector_index.rs
lib/segment/src/index/vector_index_search_common.rs
lib/segment/src/segment_constructor/segment_constructor_base.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

Depends on https://github.com/qdrant/qdrant/pull/7048
This PR integrates quantization storage into plain vector index.
It calls vector insert and use quantization for search.
Common code between HNSW and plain search (quantization checks, oversampling code, etc) is moved to the separate file without changes

Using quantization in plain segment

---

lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/shards/local_shard/mod.rs

Small refactoring for Qdrant on Edge. We need to move `SegmentHolder` into `shard` crate, but we don't want `async` in `shard`, and `deduplicate_points` is the only `async` method of `SegmentHolder`.

Remove `async` from `SegmentHolder::deduplicate_points`

---

lib/collection/src/collection_manager/holders/segment_holder.rs
lib/collection/src/config.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/update_handler.rs

Based on #7094. Also required for Qdrant on Edge. Removes `CollectionParams` from `SegmentHolder`, so that it could be cleanly moved into `shard` crate.

Refactor `SegmentHolder` to use `SegmentConfig` (instead of `CollectionParams`)

---

lib/collection/src/collection_manager/holders/segment_holder.rs

The `proxy_all_segments_and_apply`/`proxy_all_segments` function did not preserve the existing segment ID mappings. It's important, because ongoing optimizations depend on this mapping to remain the same.
Fixes this debug assertion:
```
panicked at lib/collection/src/collection_manager/optimizers/segment_optimizer.rs:711:9: assertion `left == right` failed: swapped different number of proxies on unwrap, missing or incorrect segment IDs?
left: 2
right: 3
```
Contains some refactoring which makes the diff a bit harder to read. I've marked the critical part below.

Keep segment ID mapping when proxying all segments

---

docs/grpc/docs.md
docs/redoc/master/openapi.json
lib/api/build.rs
lib/api/src/grpc/proto/points.proto
lib/api/src/grpc/proto/points_internal_service.proto
lib/api/src/grpc/qdrant.rs
lib/api/src/grpc/validate.rs
lib/api/src/rest/schema.rs
lib/api/src/rest/validate.rs
lib/collection/benches/batch_query_bench.rs
lib/collection/src/collection/query.rs
lib/collection/src/operations/universal_query/collection_query.rs
lib/collection/src/operations/universal_query/planned_query.rs
lib/collection/src/operations/universal_query/shard_query.rs
lib/collection/src/shards/local_shard/query.rs
lib/collection/src/tests/shard_query.rs
lib/segment/src/common/reciprocal_rank_fusion.rs
src/common/inference/batch_processing.rs
src/common/inference/batch_processing_grpc.rs
src/common/inference/query_requests_grpc.rs
src/common/inference/query_requests_rest.rs

Allows the `k` parameter of reciprocal rank fusion formula to be provided by user, instead of just hardcoded to 2.
http example request would look like: (edited)
```http
{
"prefetch": [ ... ],
"query": { "rrf": { "k": 60 } }
}
```
or same as before:
```http
{
"prefetch": [ ... ],
"query": { "fusion":  "rrf" }
}
```

Custom RRF `k` parameter

---

lib/segment/src/entry/entry_point.rs
lib/shard/src/proxy_segment/segment_entry.rs

More specifically, don't return a point version from the wrapped segment if that point is already marked for deletion within the proxy.
In some places we rely on `point_version` to tell us if (and what) point (version) exists in a segment. When a proxy segment marks a wrapped point for deletion, we should not expose its point version anymore.
The old behavior broke the following places (and potentially others):
- https://github.com/qdrant/qdrant/blob/5ffe70d3217790cf09a1f2406803de4bdbfa6931/lib/collection/src/collection_manager/holders/segment_holder.rs#L395
- https://github.com/qdrant/qdrant/blob/5ffe70d3217790cf09a1f2406803de4bdbfa6931/lib/collection/src/collection_manager/holders/segment_holder.rs#L564
I'm currently still evaluating if stuff around this code is also sound.
1. [x] Does …

In proxy segment, don't return deleted point versions

---

lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/shards/shard_holder/shard_mapping.rs

Prerequisite for #7047
Migrates to the new shard key format (https://github.com/qdrant/qdrant/pull/5838 and https://github.com/qdrant/qdrant/pull/6209) when loading a collection.

Mirgate from old shard key format on load

---

lib/quantization/src/encoded_storage.rs
lib/quantization/src/encoded_vectors.rs
lib/quantization/src/encoded_vectors_binary.rs
lib/quantization/src/encoded_vectors_pq.rs
lib/quantization/src/encoded_vectors_u8.rs
lib/quantization/tests/integration/empty_storage.rs
lib/segment/src/vector_storage/quantized/quantized_mmap_storage.rs
lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs
lib/segment/src/vector_storage/quantized/quantized_ram_storage.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

This PR removes loading function from this traits:
```
EncodedVectors::load
EncodedStorage::from_file
MultivectorOffsetsStorage::load
```
It's a step before using `ChunkedMmapVectors`, where loading differs from other types of quantization storages.
No new unit tests are required here, each loading case is covered by storage combatibility CI

Remove quantization load from trait

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/common/common/src/disk.rs

If we merge a large amount of empty segments, logical disk size might be much higher than real disk size due to sparse files we use there.
In some corner cases it might cause not-enough-disk-error, which is not actually true.
This PR tries to use block-based file size estimation, which is supposed to closer to real size.

measure disk size of directories if available

---

Cargo.toml
lib/common/memory/src/madvise.rs
lib/segment/src/index/hnsw_index/graph_links/view.rs

This PR adds `will_need_multiple_pages` with the following doc/signature, and enables it in the `GraphLinksView::links_with_vectors` iterator.
```rust
/// Trigger readahead for a memory-mapped region by calling
/// `madvise(MADV_WILLNEED)` on it.
///
/// Use-case: the `region` is inside `MADV_RANDOM` memory map, but it spans
/// across more than one 4KiB page. If you read it in sequence, it will cause
/// multiple page faults, thus multiple 4KiB I/O operations. Avoid this by
/// calling this function before reading the region. It will prefetch the whole
/// region in a single I/O operation. (if possible)
///
/// Note: if the region fits within a single page, this function is a no-op.
#[cfg(unix)]
pub fn will_need_multiple_pages(region: &[u8]) {
```
---
I've experimented with benchmarking …

Add memory::madvise::will_need_multiple_pages()

---

.github/workflows/docker-image.yml

This allows users to securely verify that a Qdrant container image was created by us
Once merged and after the next release, a container image can be verified like this:
```
cosign verify qdrant/qdrant:v1.16.0 --certificate-oidc-issuer=https://token.actions.githubusercontent.com --certificate-identity-regexp='https://github.com/qdrant/.*'
```
All the details: https://docs.sigstore.dev/cosign/signing/signing_with_containers/

Sign container images with cosign

---

lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
lib/segment/src/vector_storage/quantized/mod.rs
lib/segment/src/vector_storage/quantized/quantized_chunked_mmap_storage.rs
lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs
lib/segment/src/vector_storage/quantized/quantized_scorer_builder.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

This PR adds implementation of quantization storage for `ChunkedMmap` with persist `upsert` and `flush` implementation.
Also this PR adds `ChunkedMmap` variant as a quantization storage.
This PR does not have unit test because `ChunkedMmap` does not have any usage and `QuantizedVectors` does not have a create/load mechanism. This PR is mostly about compilation correctness; unit tests are the next step

Chunked mmap as a quantization storage

---

Cargo.lock
Cargo.toml
lib/segment/src/data_types/primitive.rs
lib/segment/src/index/hnsw_index/gpu/gpu_vector_storage/mod.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_links/serializer.rs

This PR is a collection of small fixes.
- `PrimitiveVectorElement: use zerocopy`
```rust
trait PrimitiveVectorElement: … {
…
/// Cast elements to a byte slice. Typically a wrapper around [`zerocopy`]
/// or [`bytemuck`] methods.
///
/// TODO: once [`half::f16`] support the latest [`zerocopy`], we could
/// remove this method in favor of using [`zerocopy::IntoBytes`] directly.
fn as_bytes(vector: &[Self]) -> &[u8];
}
```
The current `half::f16` supports `zerocopy`, so we can drop our wrapper.
- `PrimitiveVectorElement: also use zerocopy::FromBytes`
Since we use zerocopy now, we can get this bound for free (and it could be useful in hnsw-with-vectors implementation).
- `serialize_graph_links: back_index is Vec<PointOffsetType>`
Previously `usize` was used in place where `PointOffsetType` …

Misc fixes

---

lib/segment/src/index/field_index/full_text_index/immutable_text_index.rs
lib/segment/src/index/field_index/full_text_index/inverted_index/immutable_inverted_index.rs

Proper loading was lost in https://github.com/qdrant/qdrant/pull/7004
Index persists all changes, but doesn't keep them loaded, so after applying this patch all previously created indexes should be fixed automatically on load

Restore missed index loading

---

Cargo.lock
Cargo.toml
lib/api/Cargo.toml
lib/common/common/src/defaults.rs

Bumps the development version to 1.15.5-dev for the https://github.com/qdrant/qdrant/pull/7150 release.
Follows the pattern of https://github.com/qdrant/qdrant/pull/7062

Bump dev version to v1.15.5-dev

---

lib/collection/src/collection_manager/collection_updater.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/update_handler.rs

This PR tweaks `UpdateHandler::update_worker_fn` to make it a blocking call instead of async.
`update_worker_fn` is an `async fn`, even though it's almost entirely a blocking call (e.g., `CollectionUpdater::update` call, which makes up 99% of work that `update_worker_fn` does, is a blocking call).
I don't _expect_ this will have any immediate noticeable effect, but it _might_ improve perf somehow or resolve minor/rare issues, because we've seen a bunch of weird bugs caused by blocking async runtime before, and `update` is a pretty hot path (even if it's run on its own dedicated runtime).
3. [x] Have you checked your code using `cargo clippy …

Make `update_worker_fn` a blocking task, instead of async

---

lib/collection/src/collection_manager/collection_updater.rs
lib/collection/src/collection_manager/mod.rs
lib/collection/src/collection_manager/optimizers/indexing_optimizer.rs
lib/collection/src/collection_manager/tests/mod.rs
lib/shard/src/lib.rs
lib/shard/src/update.rs

Qdrant on Edge. We need this in `shard` to be reused by edge.
Last commit in the PR moves stuff around in `segment_updater`/`shard::update` module, but makes no code changes.

Move `segments_updater` from `collection` into `shard` crate

---

lib/shard/src/proxy_segment/segment_entry.rs

Fetching a vector on a proxy segment reacquires a read lock on the wrapped segment under the hood.
This only deadlock if a different thread tries to acquire a write lock in between.
```
2025-08-28T19:46:07.204032Z ERROR qdrant::startup: Panic backtrace:
0: {closure#0}
at ./src/startup.rs:19:25
1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/alloc/src/boxed.rs:1980:9
2: std::panicking::rust_panic_with_hook
at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:841:13
3: std::panicking::begin_panic_handler::{{closure}}
at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:699:13
4: std::sys::backtrace::__rust_end_short_backtrace
at …
```

Fix potential deadlock in ProxySegment all_vectors

---

lib/segment/src/index/vector_index_search_common.rs

This PR skips quantization in plain segment when search parameter `exact` is `true`.
For HNSW case it's safe, HNSW exact changes search params config, and disables quantization

Don't use quantization in exact plain search

---

lib/segment/src/vector_storage/quantized/quantized_chunked_mmap_storage.rs
lib/segment/src/vector_storage/quantized/quantized_multivector_storage.rs
lib/segment/src/vector_storage/quantized/quantized_vectors.rs

In dev there is a bug which is hard to catch. When we call popuate for quantized multivectors, we forget to call populate for multivector offsets file, only for inner vectors.
This PR fixes it. Also, it wraps `ChunkedMmapStorage` in a separate struct to make `quantized_vectors.rs` in the segment more readable.

Populate multivector quantization offsets

---

Cargo.lock
lib/quantization/Cargo.toml
lib/quantization/src/encoded_storage.rs
lib/quantization/src/encoded_vectors_binary.rs
lib/quantization/src/encoded_vectors_pq.rs
lib/quantization/src/encoded_vectors_u8.rs
lib/segment/src/vector_storage/quantized/quantized_chunked_mmap_storage.rs
lib/segment/src/vector_storage/quantized/quantized_mmap_storage.rs
lib/segment/src/vector_storage/quantized/quantized_ram_storage.rs

This PR implements quantization storage builder for `ChunkedMmap`.
It allows the use of `ChunkedMmap` for the `encoding` function in the quantization crate, which is required to build quantization from non-empty `VectorStorage`.
Because `ChunkedMmap::push` returns `Result`, this PR also changed `EncodedStorageBuilder` trait and adds `Result` to `push_vector_data` function to avoid unwarps.

Quantization storage builder for chunked mmap

---

lib/common/common/src/save_on_disk.rs

This reverts commit 80f0b53ceaf0572d29ad3691c0ab1d2441f49d28 from https://github.com/qdrant/qdrant/pull/7126.
It seems to have introduced more flakiness than it resolved.
Related flakiness reports:
- https://github.com/qdrant/qdrant/issues/7156
- https://github.com/qdrant/qdrant/issues/7181

Revert "Fix flaky save_on_disk test race condition (#7126)"

---

docs/grpc/docs.md
lib/api/src/grpc/proto/points.proto
lib/api/src/grpc/qdrant.rs
src/tonic/api/query_common.rs

Fix the TODO that said to add hw stats to FacetResponse.
1. [X] Does your submission pass tests?
2. [X] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [X] Have you checked your code using `cargo clippy --all --all-features` command?

Add hw usage to Facet response

---

Cargo.lock

Ported <https://github.com/qdrant/qdrant/pull/7184> to `dev`.
---
Bumps [tracing-subscriber](https://github.com/tokio-rs/tracing) from 0.3.19 to 0.3.20.
- [Release notes](https://github.com/tokio-rs/tracing/releases)
- [Commits](https://github.com/tokio-rs/tracing/compare/tracing-subscriber-0.3.19...tracing-subscriber-0.3.20)
---
updated-dependencies:
- dependency-name: tracing-subscriber dependency-version: 0.3.20 dependency-type: direct:production ...

build(deps): bump tracing-subscriber from 0.3.19 to 0.3.20

---

lib/collection/src/collection_manager/tests/mod.rs
lib/shard/src/locked_segment.rs
lib/shard/src/segment_holder/mod.rs

Keep the chain of locks on the proxy segment for the integrity of the access.

Chain nested locks for proxy segments

---

lib/collection/src/shards/local_shard/scroll.rs

Always take the scroll lock and segment locks in the same order. 
The update path takes the scroll lock in the opposite order as the read paths.
https://github.com/qdrant/qdrant/blob/dev/lib/collection/src/collection_manager/collection_updater.rs#L55-L70
Now it is always
1. scroll_lock
2. segments lock
3. segment lock

Fix scroll lock ordering

---

lib/storage/src/content_manager/consensus/consensus_wal.rs
lib/storage/src/content_manager/consensus_manager.rs
src/consensus.rs
src/main.rs
src/wal_inspector.rs

Small refactoring. Using `str` is silly.

Use `Path` instead of `str` in `ConsensusWal::new`

---

lib/collection/src/shards/telemetry.rs
lib/segment/src/common/anonymize.rs
lib/storage/src/types.rs
src/common/telemetry_ops/cluster_telemetry.rs

This PR makes anonymization of `PeerId` and `ReplicaState` consistent:
- Disable `PeerId` anonymization in `ReplicaSetTelemetry`, `ClusterInfo`, `ClusterStatusTelemetry` to match changes in #7177. 
- Enable `ReplicaState` anonymization in `ClusterTelemetry` to match other places that anonymize `ClusterTelemetry`.
Past PRs that affect `PeerId` anonymization: #6390, #7177.
I've used this ast-grep rule to find all structs that contain `PeerId`/`PeerInfo`.
```yaml
id: struct-with-peerid-or-peerinfo
language: rust
rule:
kind: struct_item
has:
kind: type_identifier
regex: "^PeerId|PeerInfo$"
stopBy: end
follows:
kind: attribute_item
has:
kind: identifier
regex: "^Anonymize$"
stopBy: end
```

Fixup remaining PeerId anonymization

---

lib/common/common/src/cow.rs
lib/common/common/src/lib.rs
lib/segment/src/data_types/query_context.rs
lib/segment/src/index/hnsw_index/graph_layers.rs
lib/segment/src/index/hnsw_index/graph_layers_builder.rs
lib/segment/src/index/hnsw_index/hnsw.rs
lib/segment/src/index/hnsw_index/point_scorer.rs
lib/segment/src/index/hnsw_index/tests/test_compact_graph_layer.rs
lib/segment/src/vector_storage/query_scorer/custom_query_scorer.rs
lib/segment/src/vector_storage/query_scorer/metric_query_scorer.rs

~~Based on #7171, ignore first three commits during the review.~~
This PR:
1. Adds new method `GraphLayers::links_with_vectors` that uses both quantized and non-quantized vectors stored in the file format implemented in #7171.
2. Uses this new method in `HNSWIndex::search_with_graph`.

HNSW: use new graph format during search

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/shard/src/proxy_segment/mod.rs
lib/shard/src/segment_holder/tests.rs

Add a unit test to assert a proxy segment propagating an older delete to a wrapped segment with a newer point is sound. It proves that this situation is possible in specific circumstances.
This eliminates a faulty debug assertion:
https://github.com/qdrant/qdrant/blob/60e0c07b0ab4cbd1eec053542b9db85441b4c4ae/lib/shard/src/proxy_segment/mod.rs#L298-L304
The debug assertion assumed that the logical point data in a wrapped segment of a proxy cannot change. But that is not true. If the wrapped segment is also a proxy, it may share logical state with other segments through it's write segment.
It means the following is required to make this happen:
- there must be two layers of two proxies
- one of the outer proxies is unproxied half way
- a point is updated through the unproxied segment (now …

Unit test with proxy that propagates older delete to wrapped segment

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/shard/src/segment_holder/mod.rs

Addition alongside <https://github.com/qdrant/qdrant/pull/7208>.
We create proxy segments in two places, and the set of deleted points is set up differently:
1. proxies for optimization: does share pending deletes across proxies
2. proxies for snapshot: does **not** share pending deletes across proxies
In my opinion it is correct that both are implemented differently. This PR adds two comments to emphasize this difference.

Add comment on why we do/don't share deleted points in proxies

---

lib/collection/tests/integration/continuous_snapshot_test.rs
lib/collection/tests/integration/main.rs

The test used to fail before https://github.com/qdrant/qdrant/pull/7208
```
❯ RUST_LOG=info cargo nextest run --all conti --nocapture
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.24s
────────────
Nextest run ID bf351662-3499-4b57-81b3-77b35e71b89c with nextest profile: default
Starting 2 tests across 22 binaries (1343 tests skipped)
START             collection::integration continuous_snapshot_test::test_continuous_snapshot
running 1 test
[2025-08-25T14:27:23Z INFO  wal] Wal { path: "/tmp/test_collectionSTP6GR/0/wal", segment-count: 1, entries: [0, 0)  }: opened
[2025-08-25T14:27:23Z INFO  collection::collection::snapshots] Creating collection snapshot test-0-2025-08-25-14-27-23.snapshot into "/tmp/test_snapshotsfDHEPS/test-0-2025-08-25-14-27-23.snapshot" …
```

Triggering assertion with continous snapshot

---

lib/collection/src/collection/distance_matrix.rs
lib/collection/src/grouping/group_by.rs
lib/collection/src/grouping/types.rs

`do_core_search_batch`, which was used in search matrix API is going to be deprecated and removed. This PR replaces matrix internals with query API and makes some small fixes along the way

refactor matrix api to use query instead of deprecated search

---

lib/api/src/conversions/vectors.rs
lib/api/src/grpc/conversions.rs
lib/collection/src/operations/conversions.rs
lib/segment/src/data_types/vectors.rs
lib/shard/src/search.rs
src/tonic/api/query_common.rs

Some internal APIs were still relying on the old format of `grpc::Vector`. 
This PR covers last missing parts of missing conversions, so that in the next version we can deprecate old format and always generate structures using a new one

make sure that grpc::Vector can always use new format

---

lib/api/build.rs
lib/api/src/grpc/qdrant.rs
lib/segment/src/types.rs

The `Conditions` when using a `MinShould` are currently not validated (REST & gRPC).
Backported from https://github.com/qdrant/qdrant/pull/7216

Fix missing API validation for MinShould

---

src/common/update.rs
tests/openapi/test_batch_update_multivec.py

The validation is completely missing on the point batch update operations.
The new test fails without the fix.
Backported from https://github.com/qdrant/qdrant/pull/7216

Fix missing REST API validation for point batch update

---

lib/api/build.rs
lib/api/src/grpc/qdrant.rs
lib/api/src/grpc/validate.rs

The filter within the `PointsSelector` in gRPC should be validated.
Backported from https://github.com/qdrant/qdrant/pull/7216

Fix missing gRPC api validations points selection

---

lib/segment/src/common/operation_error.rs
lib/segment/src/id_tracker/immutable_id_tracker.rs

This improves error reporting if loading mappings for the immutable ID tracker fails. While this doesn't resolve the load issue, it helps us pinpoint to the place of failure much quicker.
Before, our error looked like this:
```
IO error: failed to fill whole buffer
```
Now it looks like this:
```
Inconsistent storage: Immutable ID tracker failed to read next mapping, reading entry 46001/46077, assuming malformed storage: Inconsistent storage: failed to read numeric point ID from file: failed to fill whole buffer
```

Better immutable ID tracker load errors

---

lib/collection/src/problems/unindexed_field.rs
lib/collection/src/tests/payload.rs
tests/openapi/test_strict_mode_nested.py

Related to https://github.com/qdrant/qdrant/issues/7250
Strict mode check was missing wildcard

fix strict mode validation for nested filters

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs

The optimizer logs how many bytes are needed/available.
This now formats it in human readable format:
From:
```log
Available space: 122273390592, needed for optimization: 347267072
```
To:
```log
Available space: 122.27 GiB, needed for optimization: 347.26 MiB
```

In optimizer, show bytes available/needed in human readable format

---

lib/collection/tests/integration/continuous_snapshot_test.rs
lib/shard/src/segment_holder/mod.rs

This PR fixes the non-atomic copy on write by forcing the serialization of all updates.
During snapshot, a single write segment is shared by all proxy segments.
At the end of the segments snapshot process, deletes are propagated to the wrapped segments.
This happens concurrently with user update operations which are serialized through an update channel.
As demonstrated by the test `test_continuous_snapshot`, it is possible that the delete propagation happens right in between of the CoW for the `set_payload` operation.
```rust
fn set_payload(
&mut self,
op_num: SeqNumberType,
point_id: PointIdType,
payload: &Payload,
key: &Option<JsonPath>,
hw_counter: &HardwareCounterCell,
) -> OperationResult<bool> {
self.move_if_exists(op_num, point_id, hw_counter)?;
// NOT ATOMIC - write segment can be …
```

Fix corruption due to concurrent update during snapshot

---

lib/shard/src/segment_holder/mod.rs

Removing the reverse proxy traversal introduced in https://github.com/qdrant/qdrant/pull/7248/files#r2344371758 happened to trigger one of the new assertion from https://github.com/qdrant/qdrant/pull/7300
```
"Overriding deleted flag ProxyDeletedPoint { local_version: 2443, operation_version: 2443 } with older op_num:0"
```
Tracking the version I found that it was synthetic to replace the absent value.

Fix incorrect delete version on update

---

lib/collection/benches/batch_query_bench.rs
lib/collection/benches/batch_search_bench.rs

Shutdown `shard` explicitly at the end of benchmark to avoid error
```
A Tokio 1.x context was found, but it is being shutdown.
```

Fix Tokio race condition in benchmarks

---

Cargo.lock
Cargo.toml
lib/collection/src/collection_manager/mod.rs
lib/collection/src/collection_manager/segments_searcher.rs
lib/collection/src/shards/local_shard/mod.rs
lib/collection/src/wal_delta.rs
lib/edge/Cargo.toml
lib/edge/examples/edge-cli.rs
lib/edge/src/lib.rs
lib/segment/src/types.rs
lib/shard/src/lib.rs
lib/shard/src/search_result_aggregator.rs
lib/shard/src/wal.rs
src/wal_inspector.rs

Adds `edge` crate with a simplified `LocalShard` re-implementation, that could be used as "embeddable" (e.g., SQLite) version of Qdrant. Only implements update and search, but more stuff would be added in follow-up PRs.

Qdrant on Edge

---

Cargo.lock
Cargo.toml
lib/collection/Cargo.toml
lib/collection/src/collection/collection_ops.rs
lib/collection/src/collection/mod.rs
lib/collection/src/collection_manager/optimizers/config_mismatch_optimizer.rs
lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/collection/src/config.rs
lib/collection/src/operations/config_diff.rs
lib/collection/src/operations/types.rs
lib/segment/Cargo.toml
lib/segment/src/types.rs
lib/storage/src/content_manager/toc/create_collection.rs

This PR replaces serde-based `DiffConfig` implementation with explicit implementation. Depends on #7293.
In `dev`, we have this type coercion that copies fields from `*ConfigDiff` structs into `*Config` structs:
```rust
/// Hacky way to update configuration structures with diff-updates.
/// Intended to only be used in non critical for speed places.
/// TODO: replace with proc macro
pub fn update_config<T: DeserializeOwned + Serialize, Y: DeserializeOwned + Serialize + Merge>(
config: &T,
update: Y,
) -> CollectionResult<T> {
let mut config_values = serde_json::to_value(config)?;
let diff_values = serde_json::to_value(&update)?;
merge_level_0(&mut config_values, diff_values);
let res = serde_json::from_value(config_values)?;
Ok(res)
}
```
It's hacky indeed. It's error-prone: missing/wrong …

DiffConfig: replace serde-based impl with explicit impl

---

Dockerfile

Downgrade the cargo-chef image we're using for building Qdrant. This is needed to fix runtime errors in our NVIDIA GPU image.
More specifically, the changed image still uses Rust 1.90 but switches to an older base image. It now uses Debian bookworm, which shares its libc (amongst others) version with the NVIDIA GPU runtime image.
Sadly, no new [NVIDIA image](https://hub.docker.com/layers/nvidia/opengl/1.2-glvnd-devel-ubuntu22.04/images/sha256-c030a21588ddb89c245c8a2a24d6e68772cfa5939d312bab19f0833b90e9620a) is available and so changing the build image is necessary.
Running the GPU image before this fix:
```bash
$ docker run --gpus=all qdrant/qdrant:v1.15.5-gpu-nvidia
./qdrant: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./qdrant)
./qdrant: …
```

Downgrade cargo-chef base image to fix runtime error on NVIDIA GPU image

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs

This debug log is a bit too verbose when the space required is 0 bytes.
```
2025-09-30T13:21:37.089921Z DEBUG collection::collection_manager::optimizers::segment_optimizer: Available space: 1.03 TiB, needed for optimization: 0 B
2025-09-30T13:21:37.090006Z DEBUG collection::update_handler: Optimizer 'vacuum' running on segments: [225]
2025-09-30T13:21:37.090113Z DEBUG collection::collection_manager::optimizers::segment_optimizer: Available space: 1.03 TiB, needed for optimization: 2.42 MiB
2025-09-30T13:21:37.149219Z DEBUG collection::update_handler: Optimizer 'vacuum' running on segments: [225]
2025-09-30T13:21:37.201201Z DEBUG collection::collection_manager::optimizers::segment_optimizer: Available space: 1.03 TiB, needed for optimization: 0 B
2025-09-30T13:21:37.201268Z DEBUG …
```

Tone down optimizer logging

---

lib/collection/src/shards/local_shard/scroll.rs

There is a use-case where a filter is to be used as a primary source, and then use vector search as fallback. With this PR,  assuming cosine similarity which has output of 0-1, a query like this can be made.
```json
{
"prefetch": [
{
"filter": { "must": { "key": "description", "match": { "text": ... } } }, // full-text filter
},
{ 
"query": ..., // vector query
}
],
"query": { "formula": { "sum": ["$score[0]", "$score[1]"] } }
}
```
This way, results from the full-text filter will rank higher, but if the filter does not have enough results, we'll still have results from vector search.
Alternatively, something that can be done without this PR is to use the condition within the formula query again. But this method will check the same condition twice, and has a worse DX.
```json
{ …
```

Change score of query-less prefetch to 1.0

---

lib/collection/src/collection/clean.rs
lib/collection/src/collection/state_management.rs
lib/collection/src/collection_state.rs
lib/collection/src/operations/mod.rs
lib/collection/src/operations/point_ops.rs
lib/collection/src/shards/collection_shard_distribution.rs
lib/collection/src/shards/shard_holder/mod.rs
lib/collection/src/shards/shard_holder/shard_mapping.rs
lib/collection/src/tests/points_dedup.rs
lib/collection/src/tests/query_prefetch_offset_limit.rs
lib/collection/src/tests/snapshot_test.rs

We have good experiences using `AHash` for `u32` keys in terms of performance.
This PR applies the same migration to `HashMap<ShardId, _>`.
This change was prompted by seeing the standard hashing showing up in profiling when splitting operations by shards.

Use AHash for ShardId HashMap

---

tests/consensus_tests/test_partial_snapshot.py

Fixes:
```bash
================================================================= FAILURES =================================================================
_______________________________________________________ test_partial_snapshot_empty ________________________________________________________
def test_partial_snapshot_empty(tmp_path: pathlib.Path):
resp = create_partial_snapshot(write_peer, shard = 0, manifest = get_snapshot_manifest(read_peer))
>       assert resp.status_code == 304
E       assert 200 == 304
E        +  where 200 = <Response [200]>.status_code
tests/consensus_tests/test_partial_snapshot.py:143: AssertionError
========================================================= short test summary info ==========================================================
FAILED …
```

Fix flaky partial snapshot test

---

lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
lib/collection/src/collection_manager/tests/mod.rs
lib/collection/src/shards/local_shard/snapshot.rs
lib/segment/src/data_types/named_vectors.rs
lib/segment/src/data_types/tiny_map.rs
lib/segment/src/entry/entry_point.rs
lib/segment/src/entry/snapshot_entry.rs
lib/segment/src/segment/entry.rs
lib/segment/src/segment/snapshot.rs
lib/segment/src/segment/tests.rs
lib/segment/tests/integration/segment_on_disk_snapshot.rs
lib/shard/src/locked_segment.rs
lib/shard/src/proxy_segment/mod.rs
lib/shard/src/proxy_segment/segment_entry.rs
lib/shard/src/proxy_segment/snapshot_entry.rs
lib/shard/src/proxy_segment/tests.rs
lib/shard/src/segment_holder/mod.rs
lib/shard/src/segment_holder/snapshot.rs
lib/shard/src/segment_holder/tests.rs
lib/shard/src/update.rs
tests/consensus_tests/test_partial_snapshot.py

Current architecture assumes, that proxy segments are appendable by default and do internal copy-on-write into write segment whenever somehing needs to be changed. This architecture have acient roots and there are no clear reasons why it was designed like this in the first place, but the whole engine was designed around it and it kinda worked, untill we tried to integrate snapshots, which required double proxies. That's where it stated to fall apart with no clear way of reparing. So why appendable proxies are bad?
- Appendable proxies require internal CoW machanism, which duplicates shard-level CoW.
- Appendable proxies used shared write segment and shared delted points, which while technically sound for one level proxifying, introduced a huge amount of mental complexity and made it very …

non appendable proxies

---

lib/collection/tests/integration/continuous_snapshot_test.rs

This test used to be broken with:
```
RUST_LOG=debug cargo nextest run -p collection test_continuous_snapshot --nocapture
...
[2025-09-25T09:37:08Z INFO  shard::proxy_segment::snapshot_entry] Taking a snapshot of a proxy segment
[2025-09-25T09:37:08Z DEBUG segment::segment::snapshot] Taking snapshot of segment af3cee4d-a4a5-4474-a344-749a12aca0ba
[2025-09-25T09:37:08Z DEBUG segment::segment::snapshot] Taking snapshot of segment c496b4a2-e09e-42c9-97ba-f15e5f362061
[2025-09-25T09:37:08Z INFO  shard::proxy_segment::snapshot_entry] Taking a snapshot of a proxy segment
[2025-09-25T09:37:08Z DEBUG segment::segment::snapshot] Taking snapshot of segment 5387da80-1800-4d41-ae7e-d81437068c1e
[2025-09-25T09:37:08Z DEBUG segment::segment::snapshot] Taking snapshot of segment …
```

Test continuous snapshot data loss
